APM:Copter: Copter Struct Reference
Copter Struct Reference
#include <Copter.h>
Public Member Functions
Copter (void)
void setup () override
void loop () override
void mavlink_delay_cb ()
void failsafe_check ()
int8_t dump_log (uint8_t argc, const Menu::arg *argv)
int8_t erase_logs (uint8_t argc, const Menu::arg *argv)
int8_t select_logs (uint8_t argc, const Menu::arg *argv)
bool print_log_menu (void)
int8_t process_logs (uint8_t argc, const Menu::arg *argv)
int8_t main_menu_help (uint8_t, const Menu::arg *)
int8_t setup_mode (uint8_t argc, const Menu::arg *argv)
int8_t setup_factory (uint8_t argc, const Menu::arg *argv)
int8_t setup_set (uint8_t argc, const Menu::arg *argv)
int8_t setup_show (uint8_t argc, const Menu::arg *argv)
int8_t esc_calib (uint8_t argc, const Menu::arg *argv)
int8_t test_mode (uint8_t argc, const Menu::arg *argv)
int8_t test_baro (uint8_t argc, const Menu::arg *argv)
int8_t test_compass (uint8_t argc, const Menu::arg *argv)
int8_t test_ins (uint8_t argc, const Menu::arg *argv)
int8_t test_optflow (uint8_t argc, const Menu::arg *argv)
int8_t test_relay (uint8_t argc, const Menu::arg *argv)
int8_t test_shell (uint8_t argc, const Menu::arg *argv)
int8_t test_rangefinder (uint8_t argc, const Menu::arg *argv)
int8_t reboot_board (uint8_t argc, const Menu::arg *argv)
Public Attributes
LOG_COMMON_STRUCTURES
bool enabled:1
bool alt_healthy:1
int16_t alt_cm
uint32_t last_healthy_ms
LowPassFilterFloat alt_cm_filt
int8_t glitch_count
uint8_t unused1: 1
uint8_t simple_mode: 2
uint8_t pre_arm_rc_check: 1
uint8_t pre_arm_check: 1
uint8_t auto_armed: 1
uint8_t logging_started: 1
uint8_t land_complete: 1
uint8_t new_radio_frame: 1
uint8_t usb_connected: 1
uint8_t rc_receiver_present: 1
uint8_t compass_mot: 1
uint8_t motor_test: 1
uint8_t initialised: 1
uint8_t land_complete_maybe: 1
uint8_t throttle_zero: 1
uint8_t system_time_set: 1
uint8_t gps_base_pos_set: 1
enum HomeState home_state: 2
uint8_t using_interlock: 1
uint8_t motor_emergency_stop: 1
uint8_t land_repo_active: 1
uint8_t motor_interlock_switch: 1
uint8_t in_arming_delay: 1
uint32_t value
int8_t debounced_switch_position
int8_t last_switch_position
uint32_t last_edge_time_ms
bool running
float max_speed
float alt_delta
uint32_t start_ms
uint8_t rc_override_active: 1
uint8_t radio: 1
uint8_t battery: 1
uint8_t gcs: 1
uint8_t ekf: 1
uint8_t terrain: 1
uint8_t adsb: 1
int8_t radio_counter
uint32_t last_heartbeat_ms
uint32_t terrain_first_failure_ms
uint32_t terrain_last_failure_ms
uint8_t baro: 1
uint8_t compass: 1
uint8_t primary_gps
PayloadPlaceStateType state = PayloadPlaceStateType_Calibrating_Hover_Start
uint32_t hover_start_timestamp
float hover_throttle_level
uint32_t descend_start_timestamp
uint32_t place_start_timestamp
float descend_throttle_level
float descend_start_altitude
float descend_max
Location_Class origin_point
Location_Class climb_target
Location_Class return_target
Location_Class descent_target
bool land
bool terrain_used
ThrowModeStage stage
ThrowModeStage prev_stage
uint32_t last_log_ms
bool nextmode_attempted
uint32_t free_fall_start_ms
float free_fall_start_velz
bool takeoff_expected
bool touchdown_expected
uint32_t takeoff_time_ms
float takeoff_alt_cm
Private Member Functions
GCS & gcs ()
void compass_accumulate (void)
void compass_cal_update (void)
void barometer_accumulate (void)
void perf_update (void)
void fast_loop ()
void rc_loop ()
void throttle_loop ()
void update_mount ()
void update_trigger (void)
void update_batt_compass (void)
void ten_hz_logging_loop ()
void twentyfive_hz_logging ()
void three_hz_loop ()
void one_hz_loop ()
void update_GPS (void)
void init_simple_bearing ()
void update_simple_mode (void)
void update_super_simple_bearing (bool force_update)
void read_AHRS (void)
void update_altitude ()
void set_home_state (enum HomeState new_home_state)
bool home_is_set ()
void set_auto_armed (bool b)
void set_simple_mode (uint8_t b)
void set_failsafe_radio (bool b)
void set_failsafe_battery (bool b)
void set_failsafe_gcs (bool b)
void set_land_complete (bool b)
void set_land_complete_maybe (bool b)
void update_using_interlock ()
void set_motor_emergency_stop (bool b)
float get_smoothing_gain ()
void get_pilot_desired_lean_angles (float roll_in, float pitch_in, float &roll_out, float &pitch_out, float angle_max)
float get_pilot_desired_yaw_rate (int16_t stick_angle)
void check_ekf_reset ()
float get_roi_yaw ()
float get_look_ahead_yaw ()
void update_throttle_hover ()
void set_throttle_takeoff ()
float get_pilot_desired_throttle (int16_t throttle_control, float thr_mid=0.0f)
float get_pilot_desired_climb_rate (float throttle_control)
float get_non_takeoff_throttle ()
float get_surface_tracking_climb_rate (int16_t target_rate, float current_alt_target, float dt)
float get_avoidance_adjusted_climbrate (float target_rate)
void auto_takeoff_set_start_alt (void)
void auto_takeoff_attitude_run (float target_yaw_rate)
void set_accel_throttle_I_from_pilot_throttle ()
void rotate_body_frame_to_NE (float &x, float &y)
void gcs_send_heartbeat (void)
void gcs_send_deferred (void)
void send_heartbeat (mavlink_channel_t chan)
void send_attitude (mavlink_channel_t chan)
void send_fence_status (mavlink_channel_t chan)
void send_extended_status1 (mavlink_channel_t chan)
void send_location (mavlink_channel_t chan)
void send_nav_controller_output (mavlink_channel_t chan)
void send_simstate (mavlink_channel_t chan)
void send_hwstatus (mavlink_channel_t chan)
void send_vfr_hud (mavlink_channel_t chan)
void send_current_waypoint (mavlink_channel_t chan)
void send_rangefinder (mavlink_channel_t chan)
void send_proximity (mavlink_channel_t chan, uint16_t count_max)
void send_rpm (mavlink_channel_t chan)
void rpm_update ()
void button_update ()
void init_proximity ()
void update_proximity ()
void stats_update ()
void init_beacon ()
void update_beacon ()
void send_pid_tuning (mavlink_channel_t chan)
void gcs_send_message (enum ap_message id)
void gcs_send_mission_item_reached_message (uint16_t mission_index)
void gcs_data_stream_send (void)
void gcs_check_input (void)
void gcs_send_text (MAV_SEVERITY severity, const char *str)
void do_erase_logs (void)
void Log_Write_AutoTune (uint8_t axis, uint8_t tune_step, float meas_target, float meas_min, float meas_max, float new_gain_rp, float new_gain_rd, float new_gain_sp, float new_ddt)
void Log_Write_AutoTuneDetails (float angle_cd, float rate_cds)
void Log_Write_Current ()
void Log_Write_Optflow ()
void Log_Write_Nav_Tuning ()
void Log_Write_Control_Tuning ()
void Log_Write_Performance ()
void Log_Write_Attitude ()
void Log_Write_MotBatt ()
void Log_Write_Event (uint8_t id)
void Log_Write_Data (uint8_t id, int32_t value)
void Log_Write_Data (uint8_t id, uint32_t value)
void Log_Write_Data (uint8_t id, int16_t value)
void Log_Write_Data (uint8_t id, uint16_t value)
void Log_Write_Data (uint8_t id, float value)
void Log_Write_Error (uint8_t sub_system, uint8_t error_code)
void Log_Write_Baro (void)
void Log_Write_Parameter_Tuning (uint8_t param, float tuning_val, int16_t control_in, int16_t tune_low, int16_t tune_high)
void Log_Write_Home_And_Origin ()
void Log_Sensor_Health ()
void Log_Write_Precland ()
void Log_Write_GuidedTarget (uint8_t target_type, const Vector3f &pos_target, const Vector3f &vel_target)
void Log_Write_Throw (ThrowModeStage stage, float velocity, float velocity_z, float accel, float ef_accel_z, bool throw_detect, bool attitude_ok, bool height_ok, bool position_ok)
void Log_Write_Proximity ()
void Log_Write_Beacon ()
void Log_Write_Vehicle_Startup_Messages ()
void Log_Read (uint16_t log_num, uint16_t start_page, uint16_t end_page)
void start_logging ()
void load_parameters (void)
void convert_pid_parameters (void)
void userhook_init ()
void userhook_FastLoop ()
void userhook_50Hz ()
void userhook_MediumLoop ()
void userhook_SlowLoop ()
void userhook_SuperSlowLoop ()
void update_home_from_EKF ()
void set_home_to_current_location_inflight ()
bool set_home_to_current_location ()
bool set_home_to_current_location_and_lock ()
bool set_home_and_lock (const Location &loc)
bool set_home (const Location &loc)
bool far_from_EKF_origin (const Location &loc)
void set_system_time_from_GPS ()
void exit_mission ()
void do_RTL (void)
bool verify_takeoff ()
bool verify_land ()
bool verify_payload_place ()
bool verify_loiter_unlimited ()
bool verify_loiter_time ()
bool verify_RTL ()
bool verify_wait_delay ()
bool verify_within_distance ()
bool verify_yaw ()
void do_take_picture ()
void log_picture ()
MAV_RESULT mavlink_compassmot (mavlink_channel_t chan)
void delay (uint32_t ms)
bool acro_init (bool ignore_checks)
void acro_run ()
void get_pilot_desired_angle_rates (int16_t roll_in, int16_t pitch_in, int16_t yaw_in, float &roll_out, float &pitch_out, float &yaw_out)
bool althold_init (bool ignore_checks)
void althold_run ()
bool auto_init (bool ignore_checks)
void auto_run ()
void auto_takeoff_start (const Location &dest_loc)
void auto_takeoff_run ()
void auto_wp_start (const Vector3f &destination)
void auto_wp_start (const Location_Class &dest_loc)
void auto_wp_run ()
void auto_spline_run ()
void auto_land_start ()
void auto_land_start (const Vector3f &destination)
void auto_land_run ()
void do_payload_place (const AP_Mission::Mission_Command &cmd)
void auto_payload_place_start ()
void auto_payload_place_start (const Vector3f &destination)
void auto_payload_place_run ()
bool auto_payload_place_run_should_run ()
void auto_payload_place_run_loiter ()
void auto_payload_place_run_descend ()
void auto_payload_place_run_release ()
void auto_rtl_start ()
void auto_rtl_run ()
void auto_circle_movetoedge_start (const Location_Class &circle_center, float radius_m)
void auto_circle_start ()
void auto_circle_run ()
void auto_nav_guided_start ()
void auto_nav_guided_run ()
bool auto_loiter_start ()
void auto_loiter_run ()
uint8_t get_default_auto_yaw_mode (bool rtl)
void set_auto_yaw_mode (uint8_t yaw_mode)
void set_auto_yaw_look_at_heading (float angle_deg, float turn_rate_dps, int8_t direction, uint8_t relative_angle)
void set_auto_yaw_roi (const Location &roi_location)
float get_auto_heading (void)
bool autotune_init (bool ignore_checks)
void autotune_stop ()
bool autotune_start (bool ignore_checks)
void autotune_run ()
void autotune_attitude_control ()
void autotune_backup_gains_and_initialise ()
void autotune_load_orig_gains ()
void autotune_load_tuned_gains ()
void autotune_load_intra_test_gains ()
void autotune_load_twitch_gains ()
void autotune_save_tuning_gains ()
void autotune_update_gcs (uint8_t message_id)
bool autotune_roll_enabled ()
bool autotune_pitch_enabled ()
bool autotune_yaw_enabled ()
void autotune_twitching_test (float measurement, float target, float &measurement_min, float &measurement_max)
void autotune_updating_d_up (float &tune_d, float tune_d_min, float tune_d_max, float tune_d_step_ratio, float &tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float target, float measurement_min, float measurement_max)
void autotune_updating_d_down (float &tune_d, float tune_d_min, float tune_d_step_ratio, float &tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float target, float measurement_min, float measurement_max)
void autotune_updating_p_down (float &tune_p, float tune_p_min, float tune_p_step_ratio, float target, float measurement_max)
void autotune_updating_p_up (float &tune_p, float tune_p_max, float tune_p_step_ratio, float target, float measurement_max)
void autotune_updating_p_up_d_down (float &tune_d, float tune_d_min, float tune_d_step_ratio, float &tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float target, float measurement_min, float measurement_max)
void autotune_twitching_measure_acceleration (float &rate_of_change, float rate_measurement, float &rate_measurement_max)
void autotune_get_poshold_attitude (float &roll_cd, float &pitch_cd, float &yaw_cd)
void avoidance_adsb_update (void)
bool brake_init (bool ignore_checks)
void brake_run ()
void brake_timeout_to_loiter_ms (uint32_t timeout_ms)
bool circle_init (bool ignore_checks)
void circle_run ()
bool drift_init (bool ignore_checks)
void drift_run ()
float get_throttle_assist (float velz, float pilot_throttle_scaled)
bool flip_init (bool ignore_checks)
void flip_run ()
bool guided_init (bool ignore_checks)
bool guided_takeoff_start (float final_alt_above_home)
void guided_pos_control_start ()
void guided_vel_control_start ()
void guided_posvel_control_start ()
void guided_angle_control_start ()
bool guided_set_destination (const Vector3f &destination)
bool guided_set_destination (const Location_Class &dest_loc)
void guided_set_velocity (const Vector3f &velocity)
void guided_set_destination_posvel (const Vector3f &destination, const Vector3f &velocity)
void guided_set_angle (const Quaternion &q, float climb_rate_cms, bool use_yaw_rate, float yaw_rate_rads)
void guided_run ()
void guided_takeoff_run ()
void guided_pos_control_run ()
void guided_vel_control_run ()
void guided_posvel_control_run ()
void guided_angle_control_run ()
void guided_set_desired_velocity_with_accel_and_fence_limits (const Vector3f &vel_des)
void guided_limit_clear ()
void guided_limit_set (uint32_t timeout_ms, float alt_min_cm, float alt_max_cm, float horiz_max_cm)
void guided_limit_init_time_and_pos ()
bool guided_limit_check ()
bool guided_nogps_init (bool ignore_checks)
void guided_nogps_run ()
bool land_init (bool ignore_checks)
void land_run ()
void land_gps_run ()
void land_nogps_run ()
int32_t land_get_alt_above_ground (void)
void land_run_vertical_control (bool pause_descent=false)
void land_run_horizontal_control ()
void land_do_not_use_GPS ()
void set_mode_land_with_pause (mode_reason_t reason)
bool landing_with_GPS ()
bool loiter_init (bool ignore_checks)
void loiter_run ()
bool apogee_init (bool ignore_checks)
void apogee_run ()
bool do_precision_loiter ()
void precision_loiter_xy ()
void set_precision_loiter_enabled (bool value)
bool poshold_init (bool ignore_checks)
void poshold_run ()
void poshold_update_pilot_lean_angle (float &lean_angle_filtered, float &lean_angle_raw)
int16_t poshold_mix_controls (float mix_ratio, int16_t first_control, int16_t second_control)
void poshold_update_brake_angle_from_velocity (int16_t &brake_angle, float velocity)
void poshold_update_wind_comp_estimate ()
void poshold_get_wind_comp_lean_angles (int16_t &roll_angle, int16_t &pitch_angle)
void poshold_roll_controller_to_pilot_override ()
void poshold_pitch_controller_to_pilot_override ()
bool throw_init (bool ignore_checks)
void throw_run ()
bool throw_detected ()
bool throw_attitude_good ()
bool throw_height_good ()
bool throw_position_good ()
bool rtl_init (bool ignore_checks)
void rtl_restart_without_terrain ()
void rtl_run ()
void rtl_climb_start ()
void rtl_return_start ()
void rtl_climb_return_run ()
void rtl_loiterathome_start ()
void rtl_loiterathome_run ()
void rtl_descent_start ()
void rtl_descent_run ()
void rtl_land_start ()
void rtl_land_run ()
void rtl_build_path (bool terrain_following_allowed)
void rtl_compute_return_target (bool terrain_following_allowed)
bool sport_init (bool ignore_checks)
void sport_run ()
bool stabilize_init (bool ignore_checks)
void stabilize_run ()
void crash_check ()
void parachute_check ()
void parachute_release ()
void parachute_manual_release ()
bool avoid_adsb_init (bool ignore_checks)
void avoid_adsb_run ()
bool avoid_adsb_set_velocity (const Vector3f &velocity_neu)
void ekf_check ()
bool ekf_over_threshold ()
void failsafe_ekf_event ()
void failsafe_ekf_off_event (void)
void esc_calibration_startup_check ()
void esc_calibration_passthrough ()
void esc_calibration_auto ()
bool should_disarm_on_failsafe ()
void failsafe_radio_on_event ()
void failsafe_radio_off_event ()
void failsafe_battery_event (void)
void failsafe_gcs_check ()
void failsafe_gcs_off_event (void)
void failsafe_terrain_check ()
void failsafe_terrain_set_status (bool data_ok)
void failsafe_terrain_on_event ()
void set_mode_RTL_or_land_with_pause (mode_reason_t reason)
void update_events ()
void failsafe_enable ()
void failsafe_disable ()
void fence_check ()
void fence_send_mavlink_status (mavlink_channel_t chan)
void update_sensor_status_flags (void)
bool set_mode (control_mode_t mode, mode_reason_t reason)
bool gcs_set_mode (uint8_t mode)
void update_flight_mode ()
void exit_mode (control_mode_t old_control_mode, control_mode_t new_control_mode)
bool mode_requires_GPS (control_mode_t mode)
bool mode_has_manual_throttle (control_mode_t mode)
bool mode_allows_arming (control_mode_t mode, bool arming_from_gcs)
void notify_flight_mode (control_mode_t mode)
void heli_init ()
void check_dynamic_flight (void)
void update_heli_control_dynamics (void)
void heli_update_landing_swash ()
void heli_update_rotor_speed_targets ()
bool heli_acro_init (bool ignore_checks)
void heli_acro_run ()
bool heli_stabilize_init (bool ignore_checks)
void heli_stabilize_run ()
void read_inertia ()
bool land_complete_maybe ()
void update_land_and_crash_detectors ()
void update_land_detector ()
void update_throttle_thr_mix ()
void update_ground_effect_detector (void)
void landinggear_update ()
void update_notify ()
void motor_test_output ()
bool mavlink_motor_test_check (mavlink_channel_t chan, bool check_rc)
uint8_t mavlink_motor_test_start (mavlink_channel_t chan, uint8_t motor_seq, uint8_t throttle_type, uint16_t throttle_value, float timeout_sec)
void motor_test_stop ()
void arm_motors_check ()
void auto_disarm_check ()
bool init_arm_motors (bool arming_from_gcs)
void init_disarm_motors ()
void motors_output ()
void lost_vehicle_check ()
void run_nav_updates (void)
void calc_distance_and_bearing ()
void calc_wp_distance ()
void calc_wp_bearing ()
void calc_home_distance_and_bearing ()
void run_autopilot ()
void perf_info_reset ()
void perf_ignore_this_loop ()
void perf_info_check_loop_time (uint32_t time_in_micros)
uint16_t perf_info_get_num_loops ()
uint32_t perf_info_get_max_time ()
uint32_t perf_info_get_min_time ()
uint16_t perf_info_get_num_long_running ()
uint32_t perf_info_get_num_dropped ()
Vector3f pv_location_to_vector (const Location &loc)
float pv_alt_above_origin (float alt_above_home_cm)
float pv_alt_above_home (float alt_above_origin_cm)
float pv_get_bearing_cd (const Vector3f &origin, const Vector3f &destination)
float pv_get_horizontal_distance_cm (const Vector3f &origin, const Vector3f &destination)
float pv_distance_to_home_cm (const Vector3f &destination)
void default_dead_zones ()
void init_rc_in ()
void init_rc_out ()
void enable_motor_output ()
void read_radio ()
void set_throttle_and_failsafe (uint16_t throttle_pwm)
void set_throttle_zero_flag (int16_t throttle_control)
void radio_passthrough_to_motors ()
void init_barometer (bool full_calibration)
void read_barometer (void)
void init_rangefinder (void)
void read_rangefinder (void)
bool rangefinder_alt_ok ()
void init_compass ()
void init_optflow ()
void update_optical_flow (void)
void init_precland ()
void update_precland ()
void read_battery (void)
void read_receiver_rssi (void)
void epm_update ()
void gripper_update ()
void terrain_update ()
void terrain_logging ()
bool terrain_use ()
void report_batt_monitor ()
void report_frame ()
void report_radio ()
void report_ins ()
void report_flight_modes ()
void report_optflow ()
void print_radio_values ()
void print_switch (uint8_t p, uint8_t m, bool b)
void print_accel_offsets_and_scaling (void)
void print_gyro_offsets (void)
void report_compass ()
void print_blanks (int16_t num)
void print_divider (void)
void print_enabled (bool b)
void report_version ()
void read_control_switch ()
bool check_if_auxsw_mode_used (uint8_t auxsw_mode_check)
bool check_duplicate_auxsw (void)
void reset_control_switch ()
uint8_t read_3pos_switch (uint8_t chan)
void read_aux_switches ()
void init_aux_switches ()
void init_aux_switch_function (int8_t ch_option, uint8_t ch_flag)
void do_aux_switch_function (int8_t ch_function, uint8_t ch_flag)
void save_trim ()
void auto_trim ()
void init_ardupilot ()
void startup_INS_ground ()
bool calibrate_gyros ()
bool position_ok ()
bool ekf_position_ok ()
bool optflow_position_ok ()
void update_auto_armed ()
void check_usb_mux (void)
bool should_log (uint32_t mask)
void set_default_frame_class ()
void allocate_motors (void)
uint8_t get_frame_mav_type ()
const char * get_frame_string ()
bool current_mode_has_user_takeoff (bool must_navigate)
bool do_user_takeoff (float takeoff_alt_cm, bool must_navigate)
void takeoff_timer_start (float alt_cm)
void takeoff_stop ()
void takeoff_get_climb_rates (float &pilot_climb_rate, float &takeoff_climb_rate)
void print_hit_enter ()
void tuning ()
void gcs_send_text_fmt (MAV_SEVERITY severity, const char *fmt,...)
bool start_command (const AP_Mission::Mission_Command &cmd)
bool verify_command (const AP_Mission::Mission_Command &cmd)
bool verify_command_callback (const AP_Mission::Mission_Command &cmd)
Location_Class terrain_adjusted_location (const AP_Mission::Mission_Command &cmd) const
bool do_guided (const AP_Mission::Mission_Command &cmd)
void do_takeoff (const AP_Mission::Mission_Command &cmd)
void do_nav_wp (const AP_Mission::Mission_Command &cmd)
void do_land (const AP_Mission::Mission_Command &cmd)
void do_loiter_unlimited (const AP_Mission::Mission_Command &cmd)
void do_circle (const AP_Mission::Mission_Command &cmd)
void do_loiter_time (const AP_Mission::Mission_Command &cmd)
void do_spline_wp (const AP_Mission::Mission_Command &cmd)
void do_nav_guided_enable (const AP_Mission::Mission_Command &cmd)
void do_guided_limits (const AP_Mission::Mission_Command &cmd)
void do_nav_delay (const AP_Mission::Mission_Command &cmd)
void do_wait_delay (const AP_Mission::Mission_Command &cmd)
void do_within_distance (const AP_Mission::Mission_Command &cmd)
void do_yaw (const AP_Mission::Mission_Command &cmd)
void do_change_speed (const AP_Mission::Mission_Command &cmd)
void do_set_home (const AP_Mission::Mission_Command &cmd)
void do_roi (const AP_Mission::Mission_Command &cmd)
void do_mount_control (const AP_Mission::Mission_Command &cmd)
void do_digicam_configure (const AP_Mission::Mission_Command &cmd)
void do_digicam_control (const AP_Mission::Mission_Command &cmd)
void do_parachute (const AP_Mission::Mission_Command &cmd)
void do_gripper (const AP_Mission::Mission_Command &cmd)
bool verify_nav_wp (const AP_Mission::Mission_Command &cmd)
bool verify_circle (const AP_Mission::Mission_Command &cmd)
bool verify_spline_wp (const AP_Mission::Mission_Command &cmd)
bool verify_nav_guided_enable (const AP_Mission::Mission_Command &cmd)
bool verify_nav_delay (const AP_Mission::Mission_Command &cmd)
void auto_spline_start (const Location_Class &destination, bool stopped_at_start, AC_WPNav::spline_segment_end_type seg_end_type, const Location_Class &next_destination)
void print_flight_mode (AP_HAL::BetterStream *port, uint8_t mode)
void log_init (void)
void run_cli (AP_HAL::UARTDriver *port)
void init_capabilities (void)
void dataflash_periodic (void)
void accel_cal_update (void)
Private Attributes
AP_Vehicle::MultiCopter aparm
AP_HAL::BetterStream * cliSerial
Parameters g
ParametersG2 g2
AP_Scheduler scheduler
AP_Notify notify
uint8_t command_ack_counter
bool in_log_download
RC_Channel * channel_roll
RC_Channel * channel_pitch
RC_Channel * channel_throttle
RC_Channel * channel_yaw
DataFlash_Class DataFlash
AP_GPS gps
AP_Int8 * flight_modes
AP_Baro barometer
Compass compass
AP_InertialSensor ins
RangeFinder rangefinder {serial_manager, ROTATION_PITCH_270}
struct {
bool enabled:1
bool alt_healthy:1
int16_t alt_cm
uint32_t last_healthy_ms
LowPassFilterFloat alt_cm_filt
int8_t glitch_count
} rangefinder_state = { false, false, 0, 0 }
AP_RPM rpm_sensor
NavEKF2 EKF2 {&ahrs, barometer, rangefinder}
NavEKF3 EKF3 {&ahrs, barometer, rangefinder}
AP_AHRS_NavEKF ahrs {ins, barometer, gps, rangefinder, EKF2, EKF3, AP_AHRS_NavEKF::FLAG_ALWAYS_USE_EKF}
SITL::SITL sitl
AP_Mission mission
AP_Arming_Copter arming {ahrs, barometer, compass, battery, inertial_nav, ins}
OpticalFlow optflow {ahrs}
float ekfGndSpdLimit
float ekfNavVelGainScaler
uint32_t ekfYawReset_ms = 0
int8_t ekf_primary_core
AP_SerialManager serial_manager
GCS_MAVLINK_Copter gcs_chan [MAVLINK_COMM_NUM_BUFFERS]
GCS _gcs
union {
struct {
uint8_t unused1: 1
uint8_t simple_mode: 2
uint8_t pre_arm_rc_check: 1
uint8_t pre_arm_check: 1
uint8_t auto_armed: 1
uint8_t logging_started: 1
uint8_t land_complete: 1
uint8_t new_radio_frame: 1
uint8_t usb_connected: 1
uint8_t rc_receiver_present: 1
uint8_t compass_mot: 1
uint8_t motor_test: 1
uint8_t initialised: 1
uint8_t land_complete_maybe: 1
uint8_t throttle_zero: 1
uint8_t system_time_set: 1
uint8_t gps_base_pos_set: 1
enum HomeState home_state: 2
uint8_t using_interlock: 1
uint8_t motor_emergency_stop: 1
uint8_t land_repo_active: 1
uint8_t motor_interlock_switch: 1
uint8_t in_arming_delay: 1
}
uint32_t value
} ap
control_mode_t control_mode
mode_reason_t control_mode_reason = MODE_REASON_UNKNOWN
control_mode_t prev_control_mode
mode_reason_t prev_control_mode_reason = MODE_REASON_UNKNOWN
struct {
int8_t debounced_switch_position
int8_t last_switch_position
uint32_t last_edge_time_ms
} control_switch_state
struct {
bool running
float max_speed
float alt_delta
uint32_t start_ms
} takeoff_state
float auto_takeoff_no_nav_alt_cm
RCMapper rcmap
AP_BoardConfig BoardConfig
uint8_t receiver_rssi
struct {
uint8_t rc_override_active: 1
uint8_t radio: 1
uint8_t battery: 1
uint8_t gcs: 1
uint8_t ekf: 1
uint8_t terrain: 1
uint8_t adsb: 1
int8_t radio_counter
uint32_t last_heartbeat_ms
uint32_t terrain_first_failure_ms
uint32_t terrain_last_failure_ms
} failsafe
struct {
uint8_t baro: 1
uint8_t compass: 1
uint8_t primary_gps
} sensor_health
MOTOR_CLASS * motors
const struct AP_Param::GroupInfo * motors_var_info
float scaleLongDown
int32_t wp_bearing
int32_t home_bearing
int32_t home_distance
uint32_t wp_distance
LandStateType land_state = LandStateType_FlyToLocation
struct {
PayloadPlaceStateType state = PayloadPlaceStateType_Calibrating_Hover_Start
uint32_t hover_start_timestamp
float hover_throttle_level
uint32_t descend_start_timestamp
uint32_t place_start_timestamp
float descend_throttle_level
float descend_start_altitude
float descend_max
} nav_payload_place
AutoMode auto_mode
GuidedMode guided_mode
RTLState rtl_state
bool rtl_state_complete
struct {
Location_Class origin_point
Location_Class climb_target
Location_Class return_target
Location_Class descent_target
bool land
bool terrain_used
} rtl_path
bool circle_pilot_yaw_override
float simple_cos_yaw
float simple_sin_yaw
int32_t super_simple_last_bearing
float super_simple_cos_yaw
float super_simple_sin_yaw
int32_t initial_armed_bearing
uint16_t loiter_time_max
uint32_t loiter_time
uint32_t brake_timeout_start
uint32_t brake_timeout_ms
int32_t nav_delay_time_max
uint32_t nav_delay_time_start
Vector3f flip_orig_attitude
struct {
ThrowModeStage stage
ThrowModeStage prev_stage
uint32_t last_log_ms
bool nextmode_attempted
uint32_t free_fall_start_ms
float free_fall_start_velz
} throw_state = {Throw_Disarmed, Throw_Disarmed, 0, false, 0, 0.0f}
AP_BattMonitor battery
AP_Frsky_Telem frsky_telemetry
uint32_t control_sensors_present
uint32_t control_sensors_enabled
uint32_t control_sensors_health
int16_t climb_rate
float target_rangefinder_alt
int32_t baro_alt
float baro_climbrate
LowPassFilterVector3f land_accel_ef_filter
LowPassFilterFloat rc_throttle_control_in_filter
Location_Class current_loc
uint8_t auto_yaw_mode
Vector3f roi_WP
float yaw_look_at_WP_bearing
int32_t yaw_look_at_heading
int16_t yaw_look_at_heading_slew
float yaw_look_ahead_bearing
int32_t condition_value
uint32_t condition_start
float G_Dt
AP_InertialNav_NavEKF inertial_nav
AC_AttitudeControl * attitude_control
AC_PosControl * pos_control
AC_WPNav * wp_nav
AC_Circle * circle_nav
int16_t pmTest1
uint32_t fast_loopTimer
uint16_t mainLoop_count
uint32_t rtl_loiter_start_time
uint32_t arm_time_ms
uint8_t auto_trim_counter
AP_Relay relay
AP_ServoRelayEvents ServoRelayEvents
AP_Camera camera
AP_Mount camera_mount
AC_Fence fence
AC_Avoid avoid
AP_Rally_Copter rally
AP_RSSI rssi
AC_Sprayer sprayer
AP_Parachute parachute
AP_LandingGear landinggear
AC_PrecLand precland
AP_ADSB adsb {ahrs}
AP_Avoidance_Copter avoidance_adsb {ahrs, adsb}
bool in_mavlink_delay
bool gcs_out_of_time
uint32_t last_radio_update_ms
AP_Param param_loader
struct {
bool takeoff_expected
bool touchdown_expected
uint32_t takeoff_time_ms
float takeoff_alt_cm
} gndeffect_state
bool upgrading_frame_params
bool _precision_loiter_enabled
Static Private Attributes
static const uint8_t num_gcs = MAVLINK_COMM_NUM_BUFFERS
static const AP_Scheduler::Task scheduler_tasks []
static const AP_Param::Info var_info []
static const struct LogStructure log_structure []
Friends
class GCS_MAVLINK_Copter
class AP_Rally_Copter
class Parameters
class ParametersG2
class AP_Avoidance_Copter
class AP_Arming_Copter
Detailed Description
Definition at line 134 of file Copter.h.
Constructor & Destructor Documentation
Copter::Copter (void)
Definition at line 23 of file Copter.cpp.
Member Function Documentation
void Copter::accel_cal_update (void) private
Definition at line 222 of file sensors.cpp.
Referenced by gcs_set_mode().
bool Copter::acro_init (bool ignore_checks) private
Definition at line 9 of file control_acro.cpp.
Referenced by set_mode().
void Copter::acro_run () private
Definition at line 24 of file control_acro.cpp.
Referenced by update_flight_mode().
void Copter::allocate_motors (void) private
Definition at line 543 of file system.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
bool Copter::althold_init (bool ignore_checks) private
Definition at line 9 of file control_althold.cpp.
Referenced by set_mode().
void Copter::althold_run () private
Definition at line 36 of file control_althold.cpp.
Referenced by update_flight_mode().
bool Copter::apogee_init (bool ignore_checks) private
Definition at line 5 of file control_apogee.cpp.
Referenced by set_mode().
void Copter::apogee_run () private
Definition at line 10 of file control_apogee.cpp.
Referenced by update_flight_mode().
void Copter::arm_motors_check () private
Definition at line 12 of file motors.cpp.
Referenced by gcs_set_mode().
void Copter::auto_circle_movetoedge_start (const Location_Class & circle_center, float radius_m) private
Definition at line 433 of file control_auto.cpp.
Referenced by do_circle().
void Copter::auto_circle_run () private
Definition at line 497 of file control_auto.cpp.
Referenced by auto_run().
void Copter::auto_circle_start () private
Definition at line 487 of file control_auto.cpp.
Referenced by auto_circle_movetoedge_start(), and verify_circle().
void Copter::auto_disarm_check () private
Definition at line 71 of file motors.cpp.
Referenced by gcs_set_mode().
bool Copter::auto_init (bool ignore_checks) private
Definition at line 21 of file control_auto.cpp.
Referenced by set_mode().
void Copter::auto_land_run () private
Definition at line 389 of file control_auto.cpp.
Referenced by auto_run().
void Copter::auto_land_start () private
Definition at line 359 of file control_auto.cpp.
Referenced by do_land(), and verify_land().
void Copter::auto_land_start (const Vector3f & destination) private
Definition at line 370 of file control_auto.cpp.
void Copter::auto_loiter_run () private
Definition at line 559 of file control_auto.cpp.
Referenced by auto_run().
bool Copter::auto_loiter_start () private
Definition at line 533 of file control_auto.cpp.
Referenced by exit_mission().
void Copter::auto_nav_guided_run () private
Definition at line 524 of file control_auto.cpp.
Referenced by auto_run().
void Copter::auto_nav_guided_start () private
Definition at line 511 of file control_auto.cpp.
Referenced by do_nav_guided_enable().
void Copter::auto_payload_place_run () private
Definition at line 808 of file control_auto.cpp.
Referenced by auto_run().
void Copter::auto_payload_place_run_descend () private
Definition at line 862 of file control_auto.cpp.
Referenced by auto_payload_place_run().
void Copter::auto_payload_place_run_loiter () private
Definition at line 846 of file control_auto.cpp.
Referenced by auto_payload_place_run().
void Copter::auto_payload_place_run_release () private
bool Copter::auto_payload_place_run_should_run () private
Definition at line 784 of file control_auto.cpp.
Referenced by auto_payload_place_run().
void Copter::auto_payload_place_start () private
Definition at line 754 of file control_auto.cpp.
Referenced by do_payload_place(), and verify_payload_place().
void Copter::auto_payload_place_start (const Vector3f & destination) private
Definition at line 766 of file control_auto.cpp.
void Copter::auto_rtl_run () private
Definition at line 425 of file control_auto.cpp.
Referenced by auto_run().
void Copter::auto_rtl_start () private
Definition at line 415 of file control_auto.cpp.
Referenced by do_RTL().
void Copter::auto_run () private
Definition at line 55 of file control_auto.cpp.
Referenced by update_flight_mode().
void Copter::auto_spline_run () private
Definition at line 310 of file control_auto.cpp.
Referenced by auto_run().
void Copter::auto_spline_start (const Location_Class & destination, bool stopped_at_start, AC_WPNav::spline_segment_end_type seg_end_type, const Location_Class & next_destination) private
Definition at line 288 of file control_auto.cpp.
Referenced by do_spline_wp(), and gcs_set_mode().
void Copter::auto_takeoff_attitude_run (float target_yaw_rate) private
Definition at line 161 of file takeoff.cpp.
Referenced by auto_takeoff_run().
void Copter::auto_takeoff_run () private
Definition at line 150 of file control_auto.cpp.
Referenced by auto_run().
void Copter::auto_takeoff_set_start_alt (void) private
Definition at line 145 of file takeoff.cpp.
Referenced by auto_takeoff_start().
void Copter::auto_takeoff_start (const Location & dest_loc) private
Definition at line 102 of file control_auto.cpp.
Referenced by do_takeoff().
void Copter::auto_trim () private
Definition at line 617 of file switches.cpp.
Referenced by gcs_set_mode().
void Copter::auto_wp_run () private
Definition at line 238 of file control_auto.cpp.
Referenced by auto_run().
void Copter::auto_wp_start (const Vector3f & destination) private
Definition at line 203 of file control_auto.cpp.
Referenced by do_land(), do_loiter_unlimited(), do_nav_wp(), do_payload_place(), and verify_payload_place().
void Copter::auto_wp_start (const Location_Class & dest_loc) private
Definition at line 218 of file control_auto.cpp.
void Copter::autotune_attitude_control () private
Definition at line 367 of file control_autotune.cpp.
void Copter::autotune_backup_gains_and_initialise () private
Definition at line 770 of file control_autotune.cpp.
void Copter::autotune_get_poshold_attitude (float & roll_cd, float & pitch_cd, float & yaw_cd) private
Definition at line 1343 of file control_autotune.cpp.
bool Copter::autotune_init (bool ignore_checks) private
Definition at line 164 of file control_autotune.cpp.
Referenced by set_mode().
void Copter::autotune_load_intra_test_gains () private
Definition at line 901 of file control_autotune.cpp.
void Copter::autotune_load_orig_gains () private
Definition at line 828 of file control_autotune.cpp.
void Copter::autotune_load_tuned_gains () private
Definition at line 862 of file control_autotune.cpp.
void Copter::autotune_load_twitch_gains () private
Definition at line 929 of file control_autotune.cpp.
bool Copter::autotune_pitch_enabled () inline private
Definition at line 1067 of file control_autotune.cpp.
bool Copter::autotune_roll_enabled () inline private
Definition at line 1063 of file control_autotune.cpp.
void Copter::autotune_run () private
Definition at line 265 of file control_autotune.cpp.
Referenced by update_flight_mode().
void Copter::autotune_save_tuning_gains () private
Definition at line 956 of file control_autotune.cpp.
Referenced by init_disarm_motors().
bool Copter::autotune_start (bool ignore_checks) private
Definition at line 232 of file control_autotune.cpp.
void Copter::autotune_stop () private
Definition at line 215 of file control_autotune.cpp.
Referenced by exit_mode().
void Copter::autotune_twitching_measure_acceleration (float & rate_of_change, float rate_measurement, float & rate_measurement_max) private
Definition at line 1334 of file control_autotune.cpp.
void Copter::autotune_twitching_test (float measurement, float target, float & measurement_min, float & measurement_max) private
Definition at line 1077 of file control_autotune.cpp.
void Copter::autotune_update_gcs (uint8_t message_id) private
Definition at line 1041 of file control_autotune.cpp.
void Copter::autotune_updating_d_down (float & tune_d, float tune_d_min, float tune_d_step_ratio, float & tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float target, float measurement_min, float measurement_max) private
Definition at line 1172 of file control_autotune.cpp.
void Copter::autotune_updating_d_up (float & tune_d, float tune_d_min, float tune_d_max, float tune_d_step_ratio, float & tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float target, float measurement_min, float measurement_max) private
Definition at line 1117 of file control_autotune.cpp.
void Copter::autotune_updating_p_down (float & tune_p, float tune_p_min, float tune_p_step_ratio, float target, float measurement_max) private
Definition at line 1227 of file control_autotune.cpp.
void Copter::autotune_updating_p_up (float & tune_p, float tune_p_max, float tune_p_step_ratio, float target, float measurement_max) private
Definition at line 1256 of file control_autotune.cpp.
void Copter::autotune_updating_p_up_d_down (float & tune_d, float tune_d_min, float tune_d_step_ratio, float & tune_p, float tune_p_min, float tune_p_max, float tune_p_step_ratio, float target, float measurement_min, float measurement_max) private
Definition at line 1285 of file control_autotune.cpp.
bool Copter::autotune_yaw_enabled () inline private
Definition at line 1071 of file control_autotune.cpp.
bool Copter::avoid_adsb_init (bool ignore_checks) private
Definition at line 13 of file control_avoid_adsb.cpp.
Referenced by set_mode().
void Copter::avoid_adsb_run () private
Definition at line 32 of file control_avoid_adsb.cpp.
Referenced by update_flight_mode().
bool Copter::avoid_adsb_set_velocity (const Vector3f & velocity_neu) private
Definition at line 19 of file control_avoid_adsb.cpp.
void Copter::avoidance_adsb_update (void) private
Definition at line 4 of file avoidance_adsb.cpp.
void Copter::barometer_accumulate (void) private
Definition at line 193 of file ArduCopter.cpp.
bool Copter::brake_init (bool ignore_checks) private
Definition at line 8 of file control_brake.cpp.
Referenced by set_mode().
void Copter::brake_run () private
Definition at line 38 of file control_brake.cpp.
Referenced by update_flight_mode().
void Copter::brake_timeout_to_loiter_ms (uint32_t timeout_ms) private
Definition at line 88 of file control_brake.cpp.
void Copter::button_update (void) private
Definition at line 253 of file sensors.cpp.
void Copter::calc_distance_and_bearing () private
Definition at line 16 of file navigation.cpp.
Referenced by gcs_set_mode(), init_arm_motors(), and run_nav_updates().
void Copter::calc_home_distance_and_bearing () private
Definition at line 78 of file navigation.cpp.
Referenced by calc_distance_and_bearing(), and gcs_set_mode().
void Copter::calc_wp_bearing () private
Definition at line 51 of file navigation.cpp.
Referenced by calc_distance_and_bearing(), and gcs_set_mode().
void Copter::calc_wp_distance () private
Definition at line 24 of file navigation.cpp.
Referenced by calc_distance_and_bearing(), gcs_set_mode(), and verify_within_distance().
bool Copter::calibrate_gyros () private
Definition at line 334 of file system.cpp.
Referenced by gcs_set_mode().
bool Copter::check_duplicate_auxsw (void) private
Definition at line 83 of file switches.cpp.
Referenced by gcs_set_mode().
void Copter::check_dynamic_flight (void) private
Referenced by gcs_set_mode().
void Copter::check_ekf_reset () private
Definition at line 171 of file ekf_check.cpp.
Referenced by fast_loop().
bool Copter::check_if_auxsw_mode_used (uint8_t auxsw_mode_check) private
Definition at line 74 of file switches.cpp.
Referenced by gcs_set_mode(), landinggear_update(), lost_vehicle_check(), and update_using_interlock().
void Copter::check_usb_mux (void) private
Definition at line 442 of file system.cpp.
Referenced by gcs_set_mode(), init_ardupilot(), mavlink_delay_cb(), and one_hz_loop().
bool Copter::circle_init (bool ignore_checks) private
Definition at line 8 of file control_circle.cpp.
Referenced by set_mode().
void Copter::circle_run () private
Definition at line 31 of file control_circle.cpp.
Referenced by update_flight_mode().
void Copter::compass_accumulate (void) private
Definition at line 183 of file ArduCopter.cpp.
void Copter::compass_cal_update (void) private
Definition at line 194 of file sensors.cpp.
void Copter::convert_pid_parameters (void) private
Definition at line 1082 of file Parameters.cpp.
Referenced by allocate_motors().
void Copter::crash_check () private
Definition at line 11 of file crash_check.cpp.
Referenced by update_land_and_crash_detectors().
bool Copter::current_mode_has_user_takeoff (bool must_navigate) private
Definition at line 10 of file takeoff.cpp.
Referenced by do_user_takeoff(), and gcs_set_mode().
void Copter::dataflash_periodic (void) private
Definition at line 451 of file ArduCopter.cpp.
Referenced by gcs_set_mode().
void Copter::default_dead_zones () private
Definition at line 7 of file radio.cpp.
Referenced by gcs_set_mode(), and init_rc_in().
void Copter::delay (uint32_t ms) private
Definition at line 3 of file compat.cpp.
Referenced by esc_calibration_auto(), esc_calibration_passthrough(), esc_calibration_startup_check(), init_ardupilot(), init_rc_out(), setup_factory(), test_baro(), test_compass(), test_ins(), test_optflow(), test_rangefinder(), and test_relay().
void Copter::do_aux_switch_function (int8_t ch_function, uint8_t ch_flag) private
Definition at line 206 of file switches.cpp.
Referenced by gcs_set_mode().
void Copter::do_change_speed (const AP_Mission::Mission_Command & cmd) private
Definition at line 1095 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_circle (const AP_Mission::Mission_Command & cmd) private
Definition at line 454 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_digicam_configure (const AP_Mission::Mission_Command & cmd) private
Definition at line 1125 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_digicam_control (const AP_Mission::Mission_Command & cmd) private
Definition at line 1137 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_erase_logs (void) private
Definition at line 151 of file Log.cpp.
Referenced by erase_logs(), and log_init().
void Copter::do_gripper (const AP_Mission::Mission_Command & cmd) private
Definition at line 624 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
bool Copter::do_guided (const AP_Mission::Mission_Command & cmd) private
Definition at line 1066 of file commands_logic.cpp.
Referenced by gcs_set_mode().
void Copter::do_guided_limits (const AP_Mission::Mission_Command & cmd) private
Definition at line 645 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_land (const AP_Mission::Mission_Command & cmd) private
Definition at line 378 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_loiter_time (const AP_Mission::Mission_Command & cmd) private
Definition at line 487 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_loiter_unlimited (const AP_Mission::Mission_Command & cmd) private
Definition at line 421 of file commands_logic.cpp.
Referenced by do_loiter_time(), gcs_set_mode(), and start_command().
void Copter::do_mount_control (const AP_Mission::Mission_Command & cmd) private
Definition at line 1174 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_nav_delay (const AP_Mission::Mission_Command & cmd) private
Definition at line 585 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_nav_guided_enable (const AP_Mission::Mission_Command & cmd) private
Definition at line 572 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_nav_wp (const AP_Mission::Mission_Command & cmd) private
Definition at line 322 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_parachute (const AP_Mission::Mission_Command & cmd) private
Definition at line 601 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_payload_place (const AP_Mission::Mission_Command & cmd) private
Definition at line 400 of file commands_logic.cpp.
Referenced by start_command().
bool Copter::do_precision_loiter () private
Definition at line 39 of file control_loiter.cpp.
Referenced by loiter_run().
void Copter::do_roi (const AP_Mission::Mission_Command & cmd) private
Definition at line 1117 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_RTL (void) private
Definition at line 304 of file commands_logic.cpp.
Referenced by start_command().
void Copter::do_set_home (const AP_Mission::Mission_Command & cmd) private
Definition at line 1102 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_spline_wp (const AP_Mission::Mission_Command & cmd) private
Definition at line 498 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_take_picture () private
Definition at line 1150 of file commands_logic.cpp.
Referenced by update_GPS().
void Copter::do_takeoff (const AP_Mission::Mission_Command & cmd) private
Definition at line 315 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
bool Copter::do_user_takeoff (float takeoff_alt_cm, bool must_navigate) private
Definition at line 26 of file takeoff.cpp.
Referenced by gcs_set_mode().
void Copter::do_wait_delay (const AP_Mission::Mission_Command & cmd) private
Definition at line 1000 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_within_distance (const AP_Mission::Mission_Command & cmd) private
Definition at line 1006 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and start_command().
void Copter::do_yaw (const AP_Mission::Mission_Command & cmd) private
Definition at line 1011 of file commands_logic.cpp.
Referenced by do_guided(), gcs_set_mode(), and start_command().
bool Copter::drift_init (bool ignore_checks) private
Definition at line 30 of file control_drift.cpp.
Referenced by set_mode().
void Copter::drift_run () private
Definition at line 41 of file control_drift.cpp.
Referenced by update_flight_mode().
int8_t Copter::dump_log (uint8_t argc, const Menu::arg * argv)
Definition at line 62 of file Log.cpp.
Referenced by gcs_set_mode(), and log_init().
void Copter::ekf_check () private
Definition at line 29 of file ekf_check.cpp.
bool Copter::ekf_over_threshold () private
Definition at line 90 of file ekf_check.cpp.
bool Copter::ekf_position_ok () private
Definition at line 361 of file system.cpp.
Referenced by gcs_set_mode(), and position_ok().
void Copter::enable_motor_output () private
Definition at line 92 of file radio.cpp.
Referenced by gcs_set_mode(), init_arm_motors(), init_rc_out(), mavlink_compassmot(), and mavlink_motor_test_start().
void Copter::epm_update () private
Referenced by gcs_set_mode().
int8_t Copter::erase_logs (uint8_t argc, const Menu::arg * argv)
Definition at line 88 of file Log.cpp.
Referenced by gcs_set_mode(), and log_init().
int8_t Copter::esc_calib (uint8_t argc, const Menu::arg * argv)
Definition at line 159 of file setup.cpp.
Referenced by gcs_set_mode().
void Copter::esc_calibration_auto () private
Definition at line 121 of file esc_calibration.cpp.
Referenced by esc_calibration_startup_check().
void Copter::esc_calibration_passthrough () private
Definition at line 76 of file esc_calibration.cpp.
Referenced by esc_calibration_startup_check().
void Copter::esc_calibration_startup_check () private
Definition at line 19 of file esc_calibration.cpp.
Referenced by init_rc_out().
void Copter::exit_mission () private
Definition at line 283 of file commands_logic.cpp.
Referenced by Copter().
void Copter::exit_mode (control_mode_t old_control_mode, control_mode_t new_control_mode) private
Definition at line 263 of file flight_mode.cpp.
Referenced by gcs_set_mode(), and set_mode().
void Copter::failsafe_battery_event (void) private
Definition at line 45 of file events.cpp.
Referenced by read_battery().
void Copter::failsafe_check ()
Definition at line 35 of file failsafe.cpp.
Referenced by gcs_set_mode().
void Copter::failsafe_disable () private
Definition at line 27 of file failsafe.cpp.
Referenced by init_arm_motors(), mavlink_compassmot(), and run_cli().
void Copter::failsafe_ekf_event () private
Definition at line 117 of file ekf_check.cpp.
void Copter::failsafe_ekf_off_event (void) private
Definition at line 158 of file ekf_check.cpp.
void Copter::failsafe_enable () private
Definition at line 18 of file failsafe.cpp.
Referenced by init_ardupilot(), init_arm_motors(), and mavlink_compassmot().
void Copter::failsafe_gcs_check () private
Definition at line 75 of file events.cpp.
Referenced by three_hz_loop().
void Copter::failsafe_gcs_off_event (void) private
Definition at line 125 of file events.cpp.
Referenced by failsafe_gcs_check().
void Copter::failsafe_radio_off_event () private
Definition at line 38 of file events.cpp.
Referenced by set_failsafe_radio().
void Copter::failsafe_radio_on_event () private
Definition at line 7 of file events.cpp.
Referenced by set_failsafe_radio().
void Copter::failsafe_terrain_check () private
Definition at line 133 of file events.cpp.
Referenced by three_hz_loop().
void Copter::failsafe_terrain_on_event () private
Definition at line 172 of file events.cpp.
Referenced by auto_circle_movetoedge_start(), auto_spline_start(), auto_takeoff_start(), auto_wp_start(), and failsafe_terrain_check().
void Copter::failsafe_terrain_set_status (bool data_ok) private
Definition at line 152 of file events.cpp.
Referenced by auto_loiter_run(), auto_takeoff_run(), auto_wp_run(), rtl_climb_return_run(), and rtl_loiterathome_run().
bool Copter::far_from_EKF_origin (const Location & loc) private
Definition at line 114 of file commands.cpp.
Referenced by do_set_home().
void Copter::fast_loop () private
Definition at line 256 of file ArduCopter.cpp.
Referenced by loop().
void Copter::fence_check () private
Definition at line 9 of file fence.cpp.
Referenced by three_hz_loop().
void Copter::fence_send_mavlink_status (mavlink_channel_t chan) private
Definition at line 59 of file fence.cpp.
Referenced by send_fence_status().
bool Copter::flip_init (bool ignore_checks) private
Definition at line 40 of file control_flip.cpp.
Referenced by set_mode().
void Copter::flip_run () private
Definition at line 95 of file control_flip.cpp.
Referenced by update_flight_mode().
GCS& Copter::gcs () inline private
Definition at line 243 of file Copter.h.
Referenced by gcs_send_deferred(), gcs_send_text(), gcs_send_text_fmt(), and init_ardupilot().
void Copter::gcs_check_input (void) private
Definition at line 2071 of file GCS_Mavlink.cpp.
Referenced by mavlink_delay_cb(), and read_AHRS().
void Copter::gcs_data_stream_send (void) private
Definition at line 2059 of file GCS_Mavlink.cpp.
Referenced by mavlink_delay_cb().
void Copter::gcs_send_deferred (void) private
Definition at line 11 of file GCS_Mavlink.cpp.
Referenced by mavlink_delay_cb().
void Copter::gcs_send_heartbeat (void) private
Definition at line 6 of file GCS_Mavlink.cpp.
Referenced by mavlink_delay_cb().
void Copter::gcs_send_message (enum ap_message id) private
Definition at line 2034 of file GCS_Mavlink.cpp.
Referenced by gcs_send_deferred(), gcs_send_heartbeat(), log_picture(), mavlink_delay_cb(), twentyfive_hz_logging(), and update_trigger().
void Copter::gcs_send_mission_item_reached_message (uint16_t mission_index) private
Definition at line 2046 of file GCS_Mavlink.cpp.
Referenced by verify_command_callback().
void Copter::gcs_send_text (MAV_SEVERITY severity, const char * str) private
Definition at line 2084 of file GCS_Mavlink.cpp.
Referenced by auto_init(), crash_check(), do_erase_logs(), esc_calibration_auto(), esc_calibration_passthrough(), esc_calibration_startup_check(), failsafe_battery_event(), failsafe_terrain_on_event(), init_ardupilot(), init_arm_motors(), init_barometer(), init_disarm_motors(), log_init(), lost_vehicle_check(), mavlink_delay_cb(), parachute_manual_release(), parachute_release(), rtl_restart_without_terrain(), set_mode(), and throw_run().
void Copter::gcs_send_text_fmt (MAV_SEVERITY severity, const char * fmt, ...) private
Definition at line 2095 of file GCS_Mavlink.cpp.
Referenced by do_nav_delay(), gcs_set_mode(), perf_update(), start_command(), verify_command(), verify_nav_wp(), verify_payload_place(), and verify_spline_wp().
bool Copter::gcs_set_mode (uint8_t mode) inline private
Definition at line 953 of file Copter.h.
Referenced by GCS_MAVLINK_Copter::handleMessage().
float Copter::get_auto_heading (void) private
Definition at line 725 of file control_auto.cpp.
Referenced by auto_spline_run(), auto_wp_run(), rtl_climb_return_run(), and rtl_loiterathome_run().
float Copter::get_avoidance_adjusted_climbrate (float target_rate) private
Definition at line 283 of file Attitude.cpp.
Referenced by althold_run(), loiter_run(), poshold_run(), and sport_run().
uint8_t Copter::get_default_auto_yaw_mode (bool rtl) private
Definition at line 593 of file control_auto.cpp.
Referenced by auto_circle_movetoedge_start(), auto_spline_start(), auto_wp_start(), rtl_loiterathome_start(), rtl_return_start(), and set_auto_yaw_roi().
uint8_t Copter::get_frame_mav_type () private
Definition at line 482 of file system.cpp.
Referenced by gcs_set_mode(), init_ardupilot(), and send_heartbeat().
const char * Copter::get_frame_string () private
Definition at line 509 of file system.cpp.
Referenced by gcs_set_mode(), init_ardupilot(), Log_Read(), Log_Write_Vehicle_Startup_Messages(), and report_frame().
float Copter::get_look_ahead_yaw () private
Definition at line 89 of file Attitude.cpp.
Referenced by get_auto_heading().
float Copter::get_non_takeoff_throttle () private
Definition at line 216 of file Attitude.cpp.
Referenced by acro_init(), stabilize_init(), and update_land_detector().
void Copter::get_pilot_desired_angle_rates (int16_t roll_in, int16_t pitch_in, int16_t yaw_in, float & roll_out, float & pitch_out, float & yaw_out) private
Definition at line 57 of file control_acro.cpp.
Referenced by acro_run().
float Copter::get_pilot_desired_climb_rate (float throttle_control) private
Definition at line 182 of file Attitude.cpp.
Referenced by althold_run(), circle_run(), loiter_run(), poshold_run(), and sport_run().
void Copter::get_pilot_desired_lean_angles (float roll_in, float pitch_in, float & roll_out, float & pitch_out, float angle_max) private
Definition at line 12 of file Attitude.cpp.
Referenced by althold_run(), drift_run(), land_nogps_run(), poshold_run(), and stabilize_run().
float Copter::get_pilot_desired_throttle (int16_t throttle_control, float thr_mid = 0.0f) private
Definition at line 146 of file Attitude.cpp.
Referenced by acro_init(), acro_run(), drift_run(), flip_run(), stabilize_init(), and stabilize_run().
float Copter::get_pilot_desired_yaw_rate (int16_t stick_angle) private
Definition at line 44 of file Attitude.cpp.
Referenced by althold_run(), auto_loiter_run(), auto_spline_run(), auto_takeoff_run(), auto_wp_run(), circle_run(), get_pilot_desired_angle_rates(), land_nogps_run(), land_run_horizontal_control(), loiter_run(), poshold_run(), rtl_climb_return_run(), rtl_descent_run(), rtl_loiterathome_run(), sport_run(), and stabilize_run().
float Copter::get_roi_yaw () private
Definition at line 76 of file Attitude.cpp.
Referenced by get_auto_heading().
float Copter::get_smoothing_gain () private
Definition at line 5 of file Attitude.cpp.
Referenced by althold_run(), auto_circle_run(), auto_land_run(), auto_loiter_run(), auto_payload_place_run(), auto_payload_place_run_loiter(), auto_spline_run(), auto_takeoff_attitude_run(), auto_takeoff_run(), auto_wp_run(), brake_run(), circle_run(), drift_run(), flip_run(), land_gps_run(), land_nogps_run(), land_run_horizontal_control(), loiter_run(), poshold_run(), rtl_climb_return_run(), rtl_descent_run(), rtl_land_run(), rtl_loiterathome_run(), stabilize_run(), and throw_run().
float Copter::get_surface_tracking_climb_rate (int16_t target_rate, float current_alt_target, float dt) private
Definition at line 223 of file Attitude.cpp.
Referenced by althold_run(), circle_run(), loiter_run(), poshold_run(), and sport_run().
float Copter::get_throttle_assist (float velz, float pilot_throttle_scaled) private
Definition at line 111 of file control_drift.cpp.
Referenced by drift_run().
void Copter::gripper_update () private
Definition at line 244 of file sensors.cpp.
Referenced by gcs_set_mode().
void Copter::guided_angle_control_run () private
Definition at line 563 of file control_guided.cpp.
Referenced by guided_nogps_run().
void Copter::guided_angle_control_start () private
Definition at line 147 of file control_guided.cpp.
Referenced by guided_nogps_init().
bool Copter::guided_init (bool ignore_checks) private
Definition at line 39 of file control_guided.cpp.
Referenced by auto_nav_guided_start(), avoid_adsb_init(), and set_mode().
bool Copter::guided_limit_check () private
Definition at line 696 of file control_guided.cpp.
Referenced by verify_nav_guided_enable().
void Copter::guided_limit_clear () private
Definition at line 666 of file control_guided.cpp.
Referenced by auto_init().
void Copter::guided_limit_init_time_and_pos () private
Definition at line 685 of file control_guided.cpp.
Referenced by auto_nav_guided_start(), and do_nav_guided_enable().
void Copter::guided_limit_set (uint32_t timeout_ms, float alt_min_cm, float alt_max_cm, float horiz_max_cm) private
Definition at line 675 of file control_guided.cpp.
Referenced by do_guided_limits().
bool Copter::guided_nogps_init (bool ignore_checks) private
Definition at line 8 of file control_guided_nogps.cpp.
Referenced by set_mode().
void Copter::guided_nogps_run () private
Definition at line 17 of file control_guided_nogps.cpp.
Referenced by update_flight_mode().
void Copter::guided_pos_control_run () private
Definition at line 388 of file control_guided.cpp.
void Copter::guided_pos_control_start () private
Definition at line 82 of file control_guided.cpp.
void Copter::guided_posvel_control_run () private
Definition at line 489 of file control_guided.cpp.
void Copter::guided_posvel_control_start () private
Definition at line 119 of file control_guided.cpp.
void Copter::guided_run () private
Definition at line 300 of file control_guided.cpp.
Referenced by auto_nav_guided_run(), avoid_adsb_run(), and update_flight_mode().
void Copter::guided_set_angle (const Quaternion & q, float climb_rate_cms, bool use_yaw_rate, float yaw_rate_rads) private
Definition at line 269 of file control_guided.cpp.
void Copter::guided_set_desired_velocity_with_accel_and_fence_limits (const Vector3f & vel_des) private
Definition at line 627 of file control_guided.cpp.
bool Copter::guided_set_destination (const Vector3f & destination) private
Definition at line 178 of file control_guided.cpp.
Referenced by do_guided().
bool Copter::guided_set_destination (const Location_Class & dest_loc) private
Definition at line 206 of file control_guided.cpp.
void Copter::guided_set_destination_posvel (const Vector3f & destination, const Vector3f & velocity) private
Definition at line 252 of file control_guided.cpp.
void Copter::guided_set_velocity (const Vector3f & velocity) private
Definition at line 236 of file control_guided.cpp.
Referenced by avoid_adsb_set_velocity().
void Copter::guided_takeoff_run () private
Definition at line 334 of file control_guided.cpp.
bool Copter::guided_takeoff_start (float final_alt_above_home) private
Definition at line 54 of file control_guided.cpp.
Referenced by do_user_takeoff().
void Copter::guided_vel_control_run () private
Definition at line 435 of file control_guided.cpp.
void Copter::guided_vel_control_start () private
Definition at line 105 of file control_guided.cpp.
bool Copter::heli_acro_init (bool ignore_checks) private
Referenced by gcs_set_mode(), and set_mode().
void Copter::heli_acro_run () private
Referenced by gcs_set_mode(), and update_flight_mode().
void Copter::heli_init () private
Referenced by gcs_set_mode(), and init_ardupilot().
bool Copter::heli_stabilize_init (bool ignore_checks) private
Referenced by gcs_set_mode(), and set_mode().
void Copter::heli_stabilize_run () private
Referenced by gcs_set_mode(), and update_flight_mode().
void Copter::heli_update_landing_swash () private
Referenced by gcs_set_mode(), and throttle_loop().
void Copter::heli_update_rotor_speed_targets () private
Referenced by gcs_set_mode(), and throttle_loop().
bool Copter::home_is_set () private
Definition at line 20 of file AP_State.cpp.
void Copter::init_ardupilot () private
Definition at line 82 of file system.cpp.
Referenced by gcs_set_mode(), and setup().
bool Copter::init_arm_motors (bool arming_from_gcs) private
Definition at line 123 of file motors.cpp.
Referenced by arm_motors_check(), and gcs_set_mode().
void Copter::init_aux_switch_function (int8_t ch_option, uint8_t ch_flag) private
Definition at line 177 of file switches.cpp.
Referenced by gcs_set_mode().
void Copter::init_aux_switches () private
Definition at line 153 of file switches.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::init_barometer (bool full_calibration) private
Definition at line 3 of file sensors.cpp.
Referenced by gcs_set_mode(), init_ardupilot(), and test_baro().
void Copter::init_beacon () private
Definition at line 454 of file sensors.cpp.
Referenced by init_ardupilot().
void Copter::init_capabilities (void) private
Definition at line 3 of file capabilities.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::init_compass () private
Definition at line 101 of file sensors.cpp.
Referenced by gcs_set_mode(), init_ardupilot(), and mavlink_compassmot().
void Copter::init_disarm_motors () private
Definition at line 223 of file motors.cpp.
Referenced by arm_motors_check(), auto_disarm_check(), brake_run(), crash_check(), exit_mission(), failsafe_battery_event(), failsafe_gcs_check(), failsafe_radio_on_event(), failsafe_terrain_on_event(), fence_check(), gcs_set_mode(), land_gps_run(), land_nogps_run(), parachute_release(), rtl_land_run(), and set_land_complete().
void Copter::init_optflow () private
Definition at line 113 of file sensors.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::init_precland () private
Definition at line 9 of file precision_landing.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::init_proximity (void) private
Definition at line 259 of file sensors.cpp.
Referenced by init_ardupilot().
void Copter::init_rangefinder (void) private
Definition at line 27 of file sensors.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::init_rc_in () private
Definition at line 22 of file radio.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::init_rc_out () private
Definition at line 49 of file radio.cpp.
Referenced by gcs_set_mode(), init_ardupilot(), mavlink_compassmot(), and mavlink_motor_test_start().
void Copter::init_simple_bearing () private
Definition at line 562 of file ArduCopter.cpp.
Referenced by init_arm_motors().
bool Copter::land_complete_maybe () private
Referenced by gcs_set_mode().
void Copter::land_do_not_use_GPS () private
Definition at line 305 of file control_land.cpp.
int32_t Copter::land_get_alt_above_ground (void) private
Definition at line 152 of file control_land.cpp.
Referenced by land_run_horizontal_control(), and land_run_vertical_control().
void Copter::land_gps_run () private
Definition at line 54 of file control_land.cpp.
Referenced by land_run().
bool Copter::land_init (bool ignore_checks) private
Definition at line 9 of file control_land.cpp.
Referenced by set_mode().
void Copter::land_nogps_run () private
Definition at line 91 of file control_land.cpp.
Referenced by land_run().
void Copter::land_run () private
Definition at line 42 of file control_land.cpp.
Referenced by update_flight_mode().
void Copter::land_run_horizontal_control () private
Definition at line 211 of file control_land.cpp.
Referenced by auto_land_run(), auto_payload_place_run_descend(), auto_payload_place_run_loiter(), land_gps_run(), and rtl_land_run().
void Copter::land_run_vertical_control (bool pause_descent = false) private
Definition at line 166 of file control_land.cpp.
Referenced by auto_land_run(), auto_payload_place_run_descend(), land_gps_run(), land_nogps_run(), and rtl_land_run().
bool Copter::landing_with_GPS () private
Definition at line 322 of file control_land.cpp.
Referenced by ten_hz_logging_loop().
void Copter::landinggear_update () private
Definition at line 5 of file landing_gear.cpp.
Referenced by gcs_set_mode().
void Copter::load_parameters (void) private
Definition at line 1047 of file Parameters.cpp.
Referenced by init_ardupilot().
void Copter::log_init (void) private
Definition at line 965 of file Log.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::log_picture () private
Definition at line 1157 of file commands_logic.cpp.
Referenced by do_digicam_control(), and do_take_picture().
void Copter::Log_Read (uint16_t log_num, uint16_t start_page, uint16_t end_page) private
Definition at line 916 of file Log.cpp.
Referenced by dump_log(), and log_init().
void Copter::Log_Sensor_Health () private
Definition at line 611 of file Log.cpp.
Referenced by fast_loop(), and log_init().
void Copter::Log_Write_Attitude () private
Definition at line 374 of file Log.cpp.
Referenced by log_init(), ten_hz_logging_loop(), and twentyfive_hz_logging().
void Copter::Log_Write_AutoTune (uint8_t axis, uint8_t tune_step, float meas_target, float meas_min, float meas_max, float new_gain_rp, float new_gain_rd, float new_gain_sp, float new_ddt) private
Definition at line 174 of file Log.cpp.
Referenced by log_init().
void Copter::Log_Write_AutoTuneDetails (float angle_cd, float rate_cds) private
Definition at line 200 of file Log.cpp.
Referenced by log_init().
void Copter::Log_Write_Baro (void) private
Definition at line 563 of file Log.cpp.
Referenced by log_init(), and read_barometer().
void Copter::Log_Write_Beacon () private
Definition at line 838 of file Log.cpp.
Referenced by log_init(), and ten_hz_logging_loop().
void Copter::Log_Write_Control_Tuning () private
Definition at line 313 of file Log.cpp.
Referenced by log_init(), and update_altitude().
void Copter::Log_Write_Current () private
Definition at line 213 of file Log.cpp.
Referenced by log_init(), and read_battery().
void Copter::Log_Write_Data (uint8_t id, int32_t value) private
Definition at line 488 of file Log.cpp.
Referenced by init_simple_bearing(), log_init(), and one_hz_loop().
void Copter::Log_Write_Data (uint8_t id, uint32_t value) private
Definition at line 509 of file Log.cpp.
UNUSED_FUNCTION void Copter::Log_Write_Data (uint8_t id, int16_t value) private
Definition at line 445 of file Log.cpp.
UNUSED_FUNCTION void Copter::Log_Write_Data (uint8_t id, uint16_t value) private
Definition at line 467 of file Log.cpp.
UNUSED_FUNCTION void Copter::Log_Write_Data (uint8_t id, float value) private
Definition at line 531 of file Log.cpp.
void Copter::Log_Write_Error (uint8_t sub_system, uint8_t error_code) private
Definition at line 552 of file Log.cpp.
Referenced by auto_circle_movetoedge_start(), auto_takeoff_start(), crash_check(), do_circle(), failsafe_battery_event(), failsafe_check(), failsafe_gcs_check(), failsafe_gcs_off_event(), failsafe_radio_off_event(), failsafe_radio_on_event(), failsafe_terrain_check(), failsafe_terrain_on_event(), fence_check(), flip_run(), init_compass(), log_init(), Log_Sensor_Health(), parachute_check(), parachute_manual_release(), read_radio(), rtl_climb_start(), rtl_compute_return_target(), rtl_restart_without_terrain(), and set_mode().
void Copter::Log_Write_Event (uint8_t id) private
Definition at line 424 of file Log.cpp.
Referenced by do_gripper(), do_parachute(), flip_init(), flip_run(), init_arm_motors(), init_disarm_motors(), land_nogps_run(), land_run_horizontal_control(), landinggear_update(), log_init(), Log_Sensor_Health(), motors_output(), parachute_release(), rtl_descent_run(), set_auto_armed(), set_home_state(), set_land_complete(), set_land_complete_maybe(), set_motor_emergency_stop(), set_simple_mode(), and set_system_time_from_GPS().
void Copter::Log_Write_GuidedTarget (uint8_t target_type, const Vector3f & pos_target, const Vector3f & vel_target) private
Definition at line 707 of file Log.cpp.
Referenced by log_init().
void Copter::Log_Write_Home_And_Origin () private
Definition at line 596 of file Log.cpp.
Referenced by log_init(), Log_Write_Vehicle_Startup_Messages(), and set_home().
void Copter::Log_Write_MotBatt () private
Definition at line 402 of file Log.cpp.
Referenced by log_init(), and ten_hz_logging_loop().
void Copter::Log_Write_Nav_Tuning () private
Definition at line 270 of file Log.cpp.
Referenced by log_init(), and ten_hz_logging_loop().
void Copter::Log_Write_Optflow () private
Definition at line 232 of file Log.cpp.
Referenced by log_init(), and update_optical_flow().
void Copter::Log_Write_Parameter_Tuning (uint8_t param, float tuning_val, int16_t control_in, int16_t tune_low, int16_t tune_high) private
Definition at line 580 of file Log.cpp.
Referenced by log_init(), and tuning().
void Copter::Log_Write_Performance () private
Definition at line 356 of file Log.cpp.
Referenced by log_init(), and perf_update().
void Copter::Log_Write_Precland () private
Definition at line 666 of file Log.cpp.
Referenced by log_init(), and twentyfive_hz_logging().
void Copter::Log_Write_Proximity () private
Definition at line 776 of file Log.cpp.
Referenced by log_init(), and ten_hz_logging_loop().
void Copter::Log_Write_Throw (ThrowModeStage stage, float velocity, float velocity_z, float accel, float ef_accel_z, bool throw_detect, bool attitude_ok, bool height_ok, bool position_ok) private
Definition at line 739 of file Log.cpp.
Referenced by log_init(), and throw_run().
void Copter::Log_Write_Vehicle_Startup_Messages () private
Definition at line 932 of file Log.cpp.
Referenced by start_logging().
bool Copter::loiter_init (bool ignore_checks) private
Definition at line 8 of file control_loiter.cpp.
Referenced by set_mode().
void Copter::loiter_run () private
Definition at line 76 of file control_loiter.cpp.
Referenced by update_flight_mode().
void Copter::loop () override virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 221 of file ArduCopter.cpp.
void Copter::lost_vehicle_check () private
Definition at line 312 of file motors.cpp.
Referenced by gcs_set_mode().
int8_t Copter::main_menu_help (uint8_t argc, const Menu::arg * argv)
Definition at line 14 of file system.cpp.
Referenced by gcs_set_mode().
MAV_RESULT Copter::mavlink_compassmot (mavlink_channel_t chan) private
Definition at line 8 of file compassmot.cpp.
void Copter::mavlink_delay_cb ()
Definition at line 2002 of file GCS_Mavlink.cpp.
Referenced by gcs_set_mode().
bool Copter::mavlink_motor_test_check (mavlink_channel_t chan, bool check_rc) private
Definition at line 73 of file motor_test.cpp.
Referenced by gcs_set_mode(), and mavlink_motor_test_start().
uint8_t Copter::mavlink_motor_test_start (mavlink_channel_t chan, uint8_t motor_seq, uint8_t throttle_type, uint16_t throttle_value, float timeout_sec) private
Definition at line 100 of file motor_test.cpp.
Referenced by gcs_set_mode().
bool Copter::mode_allows_arming (control_mode_t mode, bool arming_from_gcs) private
Definition at line 344 of file flight_mode.cpp.
Referenced by gcs_set_mode(), and set_land_complete().
bool Copter::mode_has_manual_throttle (control_mode_t mode) private
Definition at line 331 of file flight_mode.cpp.
Referenced by acro_init(), arm_motors_check(), auto_disarm_check(), exit_mode(), fence_check(), gcs_set_mode(), mode_allows_arming(), set_land_complete(), stabilize_init(), update_auto_armed(), update_ground_effect_detector(), update_throttle_hover(), and update_throttle_thr_mix().
bool Copter::mode_requires_GPS (control_mode_t mode) private
Definition at line 311 of file flight_mode.cpp.
Referenced by gcs_set_mode(), and ten_hz_logging_loop().
void Copter::motor_test_output () private
Definition at line 20 of file motor_test.cpp.
Referenced by gcs_set_mode(), and motors_output().
void Copter::motor_test_stop () private
Definition at line 145 of file motor_test.cpp.
Referenced by gcs_set_mode(), and motor_test_output().
void Copter::motors_output () private
Definition at line 276 of file motors.cpp.
Referenced by fast_loop(), and gcs_set_mode().
void Copter::notify_flight_mode (control_mode_t mode) private
Definition at line 353 of file flight_mode.cpp.
Referenced by gcs_set_mode(), init_ardupilot(), and set_mode().
void Copter::one_hz_loop () private
Definition at line 481 of file ArduCopter.cpp.
bool Copter::optflow_position_ok () private
Definition at line 381 of file system.cpp.
Referenced by gcs_set_mode(), position_ok(), and update_ground_effect_detector().
void Copter::parachute_check () private
Definition at line 63 of file crash_check.cpp.
Referenced by update_land_and_crash_detectors().
void Copter::parachute_manual_release () private
Definition at line 154 of file crash_check.cpp.
void Copter::parachute_release () private
Definition at line 136 of file crash_check.cpp.
Referenced by do_parachute(), parachute_check(), and parachute_manual_release().
void Copter::perf_ignore_this_loop () private
Definition at line 30 of file perf_info.cpp.
Referenced by gcs_set_mode(), and init_arm_motors().
void Copter::perf_info_check_loop_time (uint32_t time_in_micros) private
Definition at line 36 of file perf_info.cpp.
Referenced by gcs_set_mode(), and loop().
uint32_t Copter::perf_info_get_max_time () private
Definition at line 64 of file perf_info.cpp.
Referenced by gcs_set_mode(), Log_Write_Performance(), and perf_update().
uint32_t Copter::perf_info_get_min_time () private
Definition at line 70 of file perf_info.cpp.
Referenced by gcs_set_mode(), and perf_update().
uint32_t Copter::perf_info_get_num_dropped () private
Definition at line 82 of file perf_info.cpp.
Referenced by gcs_set_mode(), and Log_Write_Performance().
uint16_t Copter::perf_info_get_num_long_running () private
Definition at line 76 of file perf_info.cpp.
Referenced by gcs_set_mode(), Log_Write_Performance(), and perf_update().
uint16_t Copter::perf_info_get_num_loops () private
Definition at line 58 of file perf_info.cpp.
Referenced by gcs_set_mode(), Log_Write_Performance(), and perf_update().
void Copter::perf_info_reset () private
Definition at line 20 of file perf_info.cpp.
Referenced by gcs_set_mode(), perf_update(), and setup().
void Copter::perf_update (void) private
Definition at line 198 of file ArduCopter.cpp.
void Copter::poshold_get_wind_comp_lean_angles (int16_t & roll_angle, int16_t & pitch_angle) private
Definition at line 646 of file control_poshold.cpp.
Referenced by poshold_run().
bool Copter::poshold_init (bool ignore_checks) private
Definition at line 76 of file control_poshold.cpp.
Referenced by set_mode().
int16_t Copter::poshold_mix_controls (float mix_ratio, int16_t first_control, int16_t second_control) private
Definition at line 575 of file control_poshold.cpp.
Referenced by poshold_run().
void Copter::poshold_pitch_controller_to_pilot_override () private
Definition at line 672 of file control_poshold.cpp.
Referenced by poshold_run().
void Copter::poshold_roll_controller_to_pilot_override () private
Definition at line 661 of file control_poshold.cpp.
Referenced by poshold_run().
void Copter::poshold_run () private
Definition at line 134 of file control_poshold.cpp.
Referenced by update_flight_mode().
void Copter::poshold_update_brake_angle_from_velocity (int16_t & brake_angle, float velocity) private
Definition at line 584 of file control_poshold.cpp.
Referenced by poshold_run().
void Copter::poshold_update_pilot_lean_angle (float & lean_angle_filtered, float & lean_angle_raw) private
Definition at line 553 of file control_poshold.cpp.
Referenced by poshold_run().
void Copter::poshold_update_wind_comp_estimate () private
Definition at line 610 of file control_poshold.cpp.
Referenced by poshold_run().
bool Copter::position_ok () private
Definition at line 349 of file system.cpp.
Referenced by auto_init(), auto_loiter_start(), brake_init(), calc_home_distance_and_bearing(), circle_init(), drift_init(), gcs_set_mode(), get_look_ahead_yaw(), land_init(), loiter_init(), poshold_init(), rtl_init(), and update_ground_effect_detector().
void Copter::precision_loiter_xy () private
Definition at line 57 of file control_loiter.cpp.
Referenced by loiter_run().
void Copter::print_accel_offsets_and_scaling (void) private
Definition at line 389 of file setup.cpp.
Referenced by gcs_set_mode(), and report_ins().
void Copter::print_blanks (int16_t num) private
Definition at line 461 of file setup.cpp.
Referenced by gcs_set_mode(), report_batt_monitor(), report_compass(), report_flight_modes(), report_frame(), report_ins(), report_optflow(), report_radio(), report_version(), and setup_show().
void Copter::print_divider (void) private
Definition at line 469 of file setup.cpp.
Referenced by gcs_set_mode(), report_batt_monitor(), report_compass(), report_flight_modes(), report_frame(), report_ins(), report_optflow(), report_radio(), and report_version().
void Copter::print_enabled (bool b) private
Definition at line 477 of file setup.cpp.
Referenced by gcs_set_mode(), report_batt_monitor(), report_compass(), report_optflow(), test_compass(), and test_optflow().
void Copter::print_flight_mode (AP_HAL::BetterStream * port, uint8_t mode) private
Definition at line 439 of file flight_mode.cpp.
Referenced by gcs_set_mode(), Log_Read(), and print_switch().
void Copter::print_gyro_offsets (void) private
Definition at line 402 of file setup.cpp.
Referenced by gcs_set_mode(), and report_ins().
void Copter::print_hit_enter () private
Definition at line 272 of file test.cpp.
Referenced by gcs_set_mode(), test_baro(), test_compass(), test_ins(), test_optflow(), test_rangefinder(), and test_relay().
bool Copter::print_log_menu (void)
Definition at line 25 of file Log.cpp.
Referenced by gcs_set_mode(), and log_init().
void Copter::print_radio_values () private
Definition at line 370 of file setup.cpp.
Referenced by gcs_set_mode(), and report_radio().
void Copter::print_switch (uint8_t p, uint8_t m, bool b) private
Definition at line 378 of file setup.cpp.
Referenced by gcs_set_mode(), and report_flight_modes().
int8_t Copter::process_logs (uint8_t argc, const Menu::arg * argv)
Definition at line 144 of file Log.cpp.
Referenced by gcs_set_mode(), and log_init().
float Copter::pv_alt_above_home (float alt_above_origin_cm) private
Definition at line 26 of file position_vector.cpp.
Referenced by gcs_set_mode(), and read_inertia().
float Copter::pv_alt_above_origin (float alt_above_home_cm) private
Definition at line 19 of file position_vector.cpp.
Referenced by gcs_set_mode(), and pv_location_to_vector().
float Copter::pv_distance_to_home_cm (const Vector3f & destination) private
Definition at line 49 of file position_vector.cpp.
Referenced by gcs_set_mode().
float Copter::pv_get_bearing_cd (const Vector3f & origin, const Vector3f & destination) private
Definition at line 33 of file position_vector.cpp.
Referenced by calc_home_distance_and_bearing(), gcs_set_mode(), and get_roi_yaw().
float Copter::pv_get_horizontal_distance_cm (const Vector3f & origin, const Vector3f & destination) private
Definition at line 43 of file position_vector.cpp.
Referenced by calc_home_distance_and_bearing(), gcs_set_mode(), and pv_distance_to_home_cm().
Vector3f Copter::pv_location_to_vector (const Location & loc) private
Definition at line 11 of file position_vector.cpp.
Referenced by calc_home_distance_and_bearing(), gcs_set_mode(), pv_distance_to_home_cm(), set_auto_yaw_roi(), and verify_circle().
void Copter::radio_passthrough_to_motors () private
Definition at line 199 of file radio.cpp.
Referenced by gcs_set_mode(), and read_radio().
bool Copter::rangefinder_alt_ok () private
Definition at line 82 of file sensors.cpp.
Referenced by althold_run(), circle_run(), gcs_set_mode(), land_get_alt_above_ground(), land_run_vertical_control(), loiter_run(), poshold_run(), sport_run(), update_land_detector(), and update_precland().
void Copter::rc_loop () private
Definition at line 304 of file ArduCopter.cpp.
uint8_t Copter::read_3pos_switch (uint8_t chan) private
Definition at line 111 of file switches.cpp.
Referenced by gcs_set_mode().
void Copter::read_AHRS (void) private
Definition at line 623 of file ArduCopter.cpp.
Referenced by fast_loop().
void Copter::read_aux_switches () private
Definition at line 130 of file switches.cpp.
Referenced by gcs_set_mode().
void Copter::read_barometer (void) private
Definition at line 15 of file sensors.cpp.
Referenced by gcs_set_mode(), test_baro(), and update_altitude().
void Copter::read_battery (void) private
Definition at line 157 of file sensors.cpp.
Referenced by gcs_set_mode(), mavlink_compassmot(), and update_batt_compass().
void Copter::read_control_switch () private
Definition at line 16 of file switches.cpp.
Referenced by gcs_set_mode(), and rc_loop().
void Copter::read_inertia () private
Definition at line 4 of file inertia.cpp.
Referenced by fast_loop(), and gcs_set_mode().
void Copter::read_radio () private
Definition at line 99 of file radio.cpp.
Referenced by esc_calibration_passthrough(), gcs_set_mode(), init_rc_out(), mavlink_compassmot(), and rc_loop().
void Copter::read_rangefinder (void) private
Definition at line 37 of file sensors.cpp.
Referenced by gcs_set_mode().
void Copter::read_receiver_rssi (void) private
Definition at line 189 of file sensors.cpp.
Referenced by gcs_set_mode().
int8_t Copter::reboot_board (uint8_t argc, const Menu::arg * argv)
Definition at line 39 of file system.cpp.
Referenced by gcs_set_mode().
void Copter::report_batt_monitor () private
Definition at line 301 of file setup.cpp.
Referenced by gcs_set_mode(), and setup_show().
void Copter::report_compass () private
Definition at line 414 of file setup.cpp.
Referenced by gcs_set_mode(), mavlink_compassmot(), setup_show(), and test_compass().
void Copter::report_flight_modes () private
Definition at line 343 of file setup.cpp.
Referenced by gcs_set_mode(), and setup_show().
void Copter::report_frame () private
Definition at line 315 of file setup.cpp.
Referenced by gcs_set_mode(), and setup_show().
void Copter::report_ins () private
Definition at line 333 of file setup.cpp.
Referenced by gcs_set_mode(), and setup_show().
void Copter::report_optflow () private
Definition at line 354 of file setup.cpp.
Referenced by gcs_set_mode(), and setup_show().
void Copter::report_radio () private
Definition at line 324 of file setup.cpp.
Referenced by gcs_set_mode(), and setup_show().
void Copter::report_version () private
Definition at line 486 of file setup.cpp.
Referenced by gcs_set_mode(), init_ardupilot(), and setup_show().
void Copter::reset_control_switch () private
Definition at line 104 of file switches.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::rotate_body_frame_to_NE (float & x, float & y) private
Definition at line 303 of file Attitude.cpp.
void Copter::rpm_update (void) private
Definition at line 90 of file sensors.cpp.
void Copter::rtl_build_path (bool terrain_following_allowed) private
Definition at line 398 of file control_rtl.cpp.
Referenced by rtl_init(), and rtl_restart_without_terrain().
void Copter::rtl_climb_return_run () private
Definition at line 132 of file control_rtl.cpp.
Referenced by rtl_run().
void Copter::rtl_climb_start () private
Definition at line 89 of file control_rtl.cpp.
Referenced by rtl_init(), and rtl_restart_without_terrain().
void Copter::rtl_compute_return_target (bool terrain_following_allowed) private
Definition at line 423 of file control_rtl.cpp.
Referenced by rtl_build_path().
void Copter::rtl_descent_run () private
Definition at line 277 of file control_rtl.cpp.
Referenced by rtl_run().
void Copter::rtl_descent_start () private
Definition at line 260 of file control_rtl.cpp.
Referenced by rtl_run().
bool Copter::rtl_init (bool ignore_checks) private
Definition at line 11 of file control_rtl.cpp.
Referenced by auto_rtl_start(), and set_mode().
void Copter::rtl_land_run () private
Definition at line 362 of file control_rtl.cpp.
Referenced by rtl_run().
void Copter::rtl_land_start () private
Definition at line 342 of file control_rtl.cpp.
Referenced by rtl_run().
void Copter::rtl_loiterathome_run () private
Definition at line 199 of file control_rtl.cpp.
Referenced by rtl_run().
void Copter::rtl_loiterathome_start () private
Definition at line 183 of file control_rtl.cpp.
Referenced by rtl_run().
void Copter::rtl_restart_without_terrain () private
Definition at line 23 of file control_rtl.cpp.
Referenced by failsafe_terrain_on_event(), and rtl_return_start().
void Copter::rtl_return_start () private
Definition at line 116 of file control_rtl.cpp.
Referenced by rtl_run().
void Copter::rtl_run () private
Definition at line 36 of file control_rtl.cpp.
Referenced by auto_rtl_run(), and update_flight_mode().
void Copter::run_autopilot () private
Definition at line 93 of file navigation.cpp.
Referenced by gcs_set_mode(), and run_nav_updates().
void Copter::run_cli (AP_HAL::UARTDriver * port) private
Definition at line 46 of file system.cpp.
Referenced by gcs_check_input(), and gcs_set_mode().
void Copter::run_nav_updates (void) private
Definition at line 6 of file navigation.cpp.
Referenced by gcs_set_mode().
void Copter::save_trim (void) private
Definition at line 605 of file switches.cpp.
Referenced by gcs_set_mode().
int8_t Copter::select_logs (uint8_t argc, const Menu::arg * argv)
Definition at line 96 of file Log.cpp.
Referenced by gcs_set_mode(), and log_init().
NOINLINE void Copter::send_attitude (mavlink_channel_t chan) private
Definition at line 87 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_current_waypoint (mavlink_channel_t chan) private
Definition at line 205 of file GCS_Mavlink.cpp.
NOINLINE void Copter::send_extended_status1 (mavlink_channel_t chan) private
Definition at line 109 of file GCS_Mavlink.cpp.
NOINLINE void Copter::send_fence_status (mavlink_channel_t chan) private
Definition at line 102 of file GCS_Mavlink.cpp.
NOINLINE void Copter::send_heartbeat (mavlink_channel_t chan) private
Definition at line 27 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_hwstatus (mavlink_channel_t chan) private
Definition at line 185 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_location (mavlink_channel_t chan) private
Definition at line 135 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_nav_controller_output (mavlink_channel_t chan) private
Definition at line 162 of file GCS_Mavlink.cpp.
void Copter::send_pid_tuning (mavlink_channel_t chan) private
Definition at line 278 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_proximity (mavlink_channel_t chan, uint16_t count_max) private
Definition at line 224 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_rangefinder (mavlink_channel_t chan) private
Definition at line 211 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_rpm (mavlink_channel_t chan) private
Definition at line 264 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_simstate (mavlink_channel_t chan) private
Definition at line 178 of file GCS_Mavlink.cpp.
void NOINLINE Copter::send_vfr_hud (mavlink_channel_t chan) private
Definition at line 193 of file GCS_Mavlink.cpp.
void Copter::set_accel_throttle_I_from_pilot_throttle () private
Definition at line 294 of file Attitude.cpp.
Referenced by exit_mode().
void Copter::set_auto_armed (bool b) private
Definition at line 26 of file AP_State.cpp.
Referenced by do_user_takeoff(), throw_run(), and update_auto_armed().
void Copter::set_auto_yaw_look_at_heading (float angle_deg, float turn_rate_dps, int8_t direction, uint8_t relative_angle) private
Definition at line 654 of file control_auto.cpp.
Referenced by do_yaw().
void Copter::set_auto_yaw_mode (uint8_t yaw_mode) private
Definition at line 617 of file control_auto.cpp.
Referenced by auto_circle_movetoedge_start(), auto_init(), auto_land_start(), auto_loiter_start(), auto_payload_place_start(), auto_spline_run(), auto_spline_start(), auto_takeoff_start(), auto_wp_run(), auto_wp_start(), rtl_climb_return_run(), rtl_climb_start(), rtl_descent_start(), rtl_land_start(), rtl_loiterathome_run(), rtl_loiterathome_start(), rtl_return_start(), set_auto_yaw_look_at_heading(), set_auto_yaw_roi(), and verify_yaw().
void Copter::set_auto_yaw_roi (const Location & roi_location) private
Definition at line 687 of file control_auto.cpp.
Referenced by do_roi().
void Copter::set_default_frame_class () private
Definition at line 473 of file system.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::set_failsafe_battery (bool b) private
Definition at line 90 of file AP_State.cpp.
Referenced by failsafe_battery_event(), and init_arm_motors().
void Copter::set_failsafe_gcs (bool b) private
Definition at line 97 of file AP_State.cpp.
Referenced by failsafe_gcs_check().
void Copter::set_failsafe_radio (bool b) private
Definition at line 63 of file AP_State.cpp.
Referenced by read_radio(), and set_throttle_and_failsafe().
bool Copter::set_home (const Location & loc) private
Definition at line 72 of file commands.cpp.
Referenced by do_set_home(), set_home_and_lock(), set_home_to_current_location(), and set_home_to_current_location_inflight().
bool Copter::set_home_and_lock (const Location & loc) private
Definition at line 60 of file commands.cpp.
void Copter::set_home_state (enum HomeState new_home_state) private
Definition at line 4 of file AP_State.cpp.
Referenced by set_home(), set_home_and_lock(), and set_home_to_current_location_and_lock().
bool Copter::set_home_to_current_location () private
Definition at line 39 of file commands.cpp.
Referenced by do_set_home(), init_arm_motors(), set_home_to_current_location_and_lock(), and update_home_from_EKF().
bool Copter::set_home_to_current_location_and_lock () private
Definition at line 49 of file commands.cpp.
void Copter::set_home_to_current_location_inflight () private
Definition at line 28 of file commands.cpp.
Referenced by update_home_from_EKF().
void Copter::set_land_complete (bool b) private
Definition at line 92 of file land_detector.cpp.
Referenced by acro_run(), althold_run(), auto_takeoff_run(), circle_run(), drift_run(), init_ardupilot(), init_disarm_motors(), loiter_run(), poshold_run(), sport_run(), stabilize_run(), and update_land_detector().
void Copter::set_land_complete_maybe (bool b) private
Definition at line 119 of file land_detector.cpp.
Referenced by init_ardupilot(), init_disarm_motors(), and update_land_detector().
bool Copter::set_mode (control_mode_t mode, mode_reason_t reason) private
Definition at line 12 of file flight_mode.cpp.
Referenced by brake_run(), exit_mission(), fence_check(), flip_run(), gcs_set_mode(), land_nogps_run(), land_run_horizontal_control(), rtl_climb_start(), rtl_descent_run(), set_mode_land_with_pause(), set_mode_RTL_or_land_with_pause(), and throw_run().
void Copter::set_mode_land_with_pause (mode_reason_t reason) private
Definition at line 312 of file control_land.cpp.
Referenced by failsafe_battery_event(), failsafe_radio_on_event(), and set_mode_RTL_or_land_with_pause().
void Copter::set_mode_RTL_or_land_with_pause (mode_reason_t reason) private
Definition at line 189 of file events.cpp.
Referenced by failsafe_battery_event(), failsafe_gcs_check(), failsafe_radio_on_event(), and failsafe_terrain_on_event().
void Copter::set_motor_emergency_stop (bool b) private
Definition at line 116 of file AP_State.cpp.
void Copter::set_precision_loiter_enabled (bool value) inline private
Definition at line 880 of file Copter.h.
void Copter::set_simple_mode (uint8_t b) private
Definition at line 39 of file AP_State.cpp.
void Copter::set_system_time_from_GPS () private
Definition at line 127 of file commands.cpp.
Referenced by update_GPS().
void Copter::set_throttle_and_failsafe (uint16_t throttle_pwm) private
Definition at line 136 of file radio.cpp.
Referenced by gcs_set_mode(), and read_radio().
void Copter::set_throttle_takeoff () private
Definition at line 136 of file Attitude.cpp.
Referenced by althold_run(), auto_spline_run(), auto_takeoff_run(), auto_takeoff_start(), auto_wp_run(), circle_run(), loiter_run(), poshold_run(), and sport_run().
void Copter::set_throttle_zero_flag (int16_t throttle_control) private
Definition at line 182 of file radio.cpp.
Referenced by gcs_set_mode(), and read_radio().
void Copter::setup () override virtual
Implements AP_HAL::HAL::Callbacks.
Definition at line 160 of file ArduCopter.cpp.
int8_t Copter::setup_factory (uint8_t argc, const Menu::arg * argv)
Definition at line 36 of file setup.cpp.
Referenced by gcs_set_mode().
int8_t Copter::setup_mode (uint8_t argc, const Menu::arg * argv)
Definition at line 24 of file setup.cpp.
Referenced by gcs_set_mode().
int8_t Copter::setup_set (uint8_t argc, const Menu::arg * argv)
Definition at line 62 of file setup.cpp.
Referenced by gcs_set_mode().
int8_t Copter::setup_show (uint8_t argc, const Menu::arg * argv)
Definition at line 122 of file setup.cpp.
Referenced by gcs_set_mode().
bool Copter::should_disarm_on_failsafe () private
Definition at line 201 of file events.cpp.
Referenced by failsafe_battery_event(), failsafe_gcs_check(), failsafe_radio_on_event(), and failsafe_terrain_on_event().
bool Copter::should_log (uint32_t mask) private
Definition at line 456 of file system.cpp.
Referenced by fast_loop(), gcs_set_mode(), init_ardupilot(), init_simple_bearing(), log_picture(), Log_Write_Data(), Log_Write_Event(), one_hz_loop(), perf_update(), read_barometer(), read_battery(), read_rangefinder(), rpm_update(), set_home(), start_command(), ten_hz_logging_loop(), terrain_logging(), twentyfive_hz_logging(), update_altitude(), update_batt_compass(), update_GPS(), and update_trigger().
bool Copter::sport_init (bool ignore_checks) private
Definition at line 8 of file control_sport.cpp.
Referenced by set_mode().
void Copter::sport_run () private
Definition at line 25 of file control_sport.cpp.
Referenced by update_flight_mode().
bool Copter::stabilize_init (bool ignore_checks) private
Definition at line 8 of file control_stabilize.cpp.
Referenced by set_mode().
void Copter::stabilize_run () private
Definition at line 23 of file control_stabilize.cpp.
Referenced by update_flight_mode().
bool Copter::start_command (const AP_Mission::Mission_Command & cmd) private
navigation commands
do commands
Definition at line 4 of file commands_logic.cpp.
Referenced by Copter(), and gcs_set_mode().
void Copter::start_logging () private
Definition at line 947 of file Log.cpp.
Referenced by log_init(), and should_log().
void Copter::startup_INS_ground () private
Definition at line 320 of file system.cpp.
Referenced by gcs_set_mode(), and init_ardupilot().
void Copter::stats_update (void) private
Definition at line 216 of file ArduCopter.cpp.
void Copter::takeoff_get_climb_rates (float & pilot_climb_rate, float & takeoff_climb_rate) private
Definition at line 87 of file takeoff.cpp.
Referenced by althold_run(), gcs_set_mode(), loiter_run(), poshold_run(), and sport_run().
void Copter::takeoff_stop () private
Definition at line 77 of file takeoff.cpp.
Referenced by althold_init(), exit_mode(), gcs_set_mode(), and takeoff_get_climb_rates().
void Copter::takeoff_timer_start (float alt_cm) private
Definition at line 59 of file takeoff.cpp.
Referenced by althold_run(), do_user_takeoff(), gcs_set_mode(), loiter_run(), poshold_run(), and sport_run().
void Copter::ten_hz_logging_loop () private
Definition at line 378 of file ArduCopter.cpp.
Location_Class Copter::terrain_adjusted_location (const AP_Mission::Mission_Command & cmd) const private
Definition at line 358 of file commands_logic.cpp.
Referenced by do_land(), do_payload_place(), and gcs_set_mode().
void Copter::terrain_logging () private
Definition at line 21 of file terrain.cpp.
Referenced by gcs_set_mode(), and one_hz_loop().
void Copter::terrain_update () private
Definition at line 4 of file terrain.cpp.
Referenced by gcs_set_mode().
bool Copter::terrain_use () private
Definition at line 31 of file terrain.cpp.
Referenced by gcs_set_mode(), rtl_compute_return_target(), and update_precland().
int8_t Copter::test_baro (uint8_t argc, const Menu::arg * argv)
Definition at line 35 of file test.cpp.
Referenced by gcs_set_mode().
int8_t Copter::test_compass (uint8_t argc, const Menu::arg * argv)
Definition at line 60 of file test.cpp.
Referenced by gcs_set_mode().
int8_t Copter::test_ins (uint8_t argc, const Menu::arg * argv)
Definition at line 145 of file test.cpp.
Referenced by gcs_set_mode().
int8_t Copter::test_mode (uint8_t argc, const Menu::arg * argv)
Definition at line 28 of file test.cpp.
Referenced by gcs_set_mode().
int8_t Copter::test_optflow (uint8_t argc, const Menu::arg * argv)
Definition at line 177 of file test.cpp.
Referenced by gcs_set_mode().
int8_t Copter::test_rangefinder (uint8_t argc, const Menu::arg * argv)
Definition at line 244 of file test.cpp.
Referenced by gcs_set_mode().
int8_t Copter::test_relay (uint8_t argc, const Menu::arg * argv)
Definition at line 207 of file test.cpp.
Referenced by gcs_set_mode().
int8_t Copter::test_shell (uint8_t argc, const Menu::arg * argv)
Definition at line 233 of file test.cpp.
Referenced by gcs_set_mode().
void Copter::three_hz_loop () private
Definition at line 457 of file ArduCopter.cpp.
void Copter::throttle_loop () private
Definition at line 314 of file ArduCopter.cpp.
bool Copter::throw_attitude_good () private
Definition at line 251 of file control_throw.cpp.
Referenced by throw_run().
bool Copter::throw_detected () private
Definition at line 206 of file control_throw.cpp.
Referenced by throw_run().
bool Copter::throw_height_good () private
Definition at line 258 of file control_throw.cpp.
Referenced by throw_run().
bool Copter::throw_init (bool ignore_checks) private
Definition at line 5 of file control_throw.cpp.
Referenced by set_mode().
bool Copter::throw_position_good () private
Definition at line 264 of file control_throw.cpp.
Referenced by throw_run().
void Copter::throw_run () private
Definition at line 26 of file control_throw.cpp.
Referenced by update_flight_mode().
void Copter::tuning () private
Definition at line 10 of file tuning.cpp.
Referenced by gcs_set_mode(), and three_hz_loop().
void Copter::twentyfive_hz_logging () private
Definition at line 420 of file ArduCopter.cpp.
void Copter::update_altitude () private
Definition at line 637 of file ArduCopter.cpp.
void Copter::update_auto_armed () private
Definition at line 404 of file system.cpp.
Referenced by gcs_set_mode(), and throttle_loop().
void Copter::update_batt_compass (void) private
Definition at line 360 of file ArduCopter.cpp.
void Copter::update_beacon () private
Definition at line 460 of file sensors.cpp.
void Copter::update_events (void) private
Definition at line 221 of file events.cpp.
Referenced by three_hz_loop().
void Copter::update_flight_mode () private
Definition at line 163 of file flight_mode.cpp.
Referenced by fast_loop(), and gcs_set_mode().
void Copter::update_GPS (void) private
Definition at line 525 of file ArduCopter.cpp.
void Copter::update_ground_effect_detector (void) private
Definition at line 3 of file baro_ground_effect.cpp.
Referenced by gcs_set_mode(), and throttle_loop().
void Copter::update_heli_control_dynamics (void) private
Referenced by fast_loop(), and gcs_set_mode().
void Copter::update_home_from_EKF () private
Definition at line 11 of file commands.cpp.
Referenced by fast_loop().
void Copter::update_land_and_crash_detectors () private
Definition at line 14 of file land_detector.cpp.
Referenced by fast_loop(), and gcs_set_mode().
void Copter::update_land_detector () private
Definition at line 33 of file land_detector.cpp.
Referenced by gcs_set_mode(), and update_land_and_crash_detectors().
void Copter::update_mount () private
Definition at line 336 of file ArduCopter.cpp.
void Copter::update_notify () private
Definition at line 6 of file leds.cpp.
Referenced by esc_calibration_passthrough(), gcs_set_mode(), and init_arm_motors().
void Copter::update_optical_flow (void) private
Definition at line 128 of file sensors.cpp.
Referenced by gcs_set_mode().
void Copter::update_precland () private
Definition at line 14 of file precision_landing.cpp.
Referenced by gcs_set_mode().
void Copter::update_proximity (void) private
Definition at line 268 of file sensors.cpp.
void Copter::update_sensor_status_flags (void) private
Definition at line 279 of file sensors.cpp.
Referenced by one_hz_loop(), and send_extended_status1().
void Copter::update_simple_mode (void) private
Definition at line 580 of file ArduCopter.cpp.
Referenced by althold_run(), land_nogps_run(), land_run_horizontal_control(), loiter_run(), poshold_run(), rtl_descent_run(), sport_run(), and stabilize_run().
void Copter::update_super_simple_bearing (bool force_update) private
Definition at line 609 of file ArduCopter.cpp.
Referenced by calc_home_distance_and_bearing(), and set_simple_mode().
void Copter::update_throttle_hover () private
Definition at line 106 of file Attitude.cpp.
void Copter::update_throttle_thr_mix () private
Definition at line 134 of file land_detector.cpp.
Referenced by gcs_set_mode(), and throttle_loop().
void Copter::update_trigger (void) private
Definition at line 345 of file ArduCopter.cpp.
void Copter::update_using_interlock () private
Definition at line 104 of file AP_State.cpp.
Referenced by init_ardupilot(), and one_hz_loop().
void Copter::userhook_50Hz () private
void Copter::userhook_FastLoop () private
void Copter::userhook_init () private
void Copter::userhook_MediumLoop () private
void Copter::userhook_SlowLoop () private
void Copter::userhook_SuperSlowLoop () private
bool Copter::verify_circle (const AP_Mission::Mission_Command & cmd) private
Definition at line 912 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and verify_command().
bool Copter::verify_command (const AP_Mission::Mission_Command & cmd) private
conditional commands
Definition at line 202 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and verify_command_callback().
bool Copter::verify_command_callback (const AP_Mission::Mission_Command & cmd) private
Definition at line 178 of file commands_logic.cpp.
Referenced by Copter(), and gcs_set_mode().
bool Copter::verify_land () private
Definition at line 666 of file commands_logic.cpp.
Referenced by verify_command().
bool Copter::verify_loiter_time () private
Definition at line 895 of file commands_logic.cpp.
Referenced by verify_command().
bool Copter::verify_loiter_unlimited () private
Definition at line 889 of file commands_logic.cpp.
Referenced by verify_command().
bool Copter::verify_nav_delay (const AP_Mission::Mission_Command & cmd) private
Definition at line 986 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and verify_command().
bool Copter::verify_nav_guided_enable (const AP_Mission::Mission_Command & cmd) private
Definition at line 973 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and verify_command().
bool Copter::verify_nav_wp (const AP_Mission::Mission_Command & cmd) private
Definition at line 865 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and verify_command().
bool Copter::verify_payload_place () private
Definition at line 711 of file commands_logic.cpp.
Referenced by verify_command().
bool Copter::verify_RTL () private
Definition at line 944 of file commands_logic.cpp.
Referenced by verify_command().
bool Copter::verify_spline_wp (const AP_Mission::Mission_Command & cmd) private
Definition at line 950 of file commands_logic.cpp.
Referenced by gcs_set_mode(), and verify_command().
bool Copter::verify_takeoff () private
Definition at line 659 of file commands_logic.cpp.
Referenced by verify_command().
bool Copter::verify_wait_delay () private
Definition at line 1025 of file commands_logic.cpp.
Referenced by verify_command().
bool Copter::verify_within_distance () private
Definition at line 1034 of file commands_logic.cpp.
Referenced by verify_command().
bool Copter::verify_yaw () private
Definition at line 1046 of file commands_logic.cpp.
Referenced by verify_command().
Friends And Related Function Documentation
friend class AP_Arming_Copter friend
Definition at line 144 of file Copter.h.
friend class AP_Avoidance_Copter friend
Definition at line 140 of file Copter.h.
friend class AP_Rally_Copter friend
Definition at line 137 of file Copter.h.
friend class GCS_MAVLINK_Copter friend
Definition at line 136 of file Copter.h.
friend class Parameters friend
Definition at line 138 of file Copter.h.
friend class ParametersG2 friend
Definition at line 139 of file Copter.h.
Member Data Documentation
GCS Copter::_gcs private
Definition at line 242 of file Copter.h.
Referenced by gcs().
bool Copter::_precision_loiter_enabled private
Definition at line 881 of file Copter.h.
Referenced by do_precision_loiter(), and set_precision_loiter_enabled().
uint8_t Copter::adsb
Definition at line 321 of file Copter.h.
Referenced by avoidance_adsb_update(), one_hz_loop(), and set_mode().
AP_ADSB Copter::adsb {ahrs} private
Definition at line 577 of file Copter.h.
AP_AHRS_NavEKF Copter::ahrs {ins, barometer, gps, rangefinder, EKF2, EKF3, AP_AHRS_NavEKF::FLAG_ALWAYS_USE_EKF} private
Definition at line 210 of file Copter.h.
Referenced by accel_cal_update(), allocate_motors(), apogee_run(), calc_home_distance_and_bearing(), Copter(), drift_run(), ekf_position_ok(), flip_init(), flip_run(), get_pilot_desired_angle_rates(), init_ardupilot(), init_arm_motors(), init_compass(), init_disarm_motors(), init_simple_bearing(), log_picture(), Log_Write_Attitude(), Log_Write_Baro(), Log_Write_Home_And_Origin(), one_hz_loop(), optflow_position_ok(), poshold_get_wind_comp_lean_angles(), poshold_run(), pv_alt_above_home(), pv_alt_above_origin(), pv_distance_to_home_cm(), read_AHRS(), read_rangefinder(), rotate_body_frame_to_NE(), rtl_compute_return_target(), rtl_loiterathome_run(), send_attitude(), send_location(), send_pid_tuning(), send_vfr_hud(), set_auto_yaw_mode(), set_home(), sport_run(), startup_INS_ground(), ten_hz_logging_loop(), test_compass(), test_ins(), throw_attitude_good(), throw_detected(), throw_run(), tuning(), twentyfive_hz_logging(), update_batt_compass(), update_flight_mode(), update_GPS(), update_ground_effect_detector(), update_land_and_crash_detectors(), update_optical_flow(), update_sensor_status_flags(), update_simple_mode(), update_throttle_hover(), update_throttle_thr_mix(), update_trigger(), and verify_yaw().
int16_t Copter::alt_cm
Definition at line 199 of file Copter.h.
Referenced by gcs_set_mode(), and takeoff_timer_start().
LowPassFilterFloat Copter::alt_cm_filt
Definition at line 201 of file Copter.h.
float Copter::alt_delta
Definition at line 298 of file Copter.h.
bool Copter::alt_healthy
Definition at line 198 of file Copter.h.
union { ... } Copter::ap
Referenced by acro_init(), acro_run(), althold_run(), arm_motors_check(), auto_disarm_check(), auto_init(), auto_land_run(), auto_loiter_run(), auto_payload_place_run_should_run(), auto_spline_run(), auto_takeoff_run(), auto_takeoff_set_start_alt(), auto_wp_run(), brake_run(), check_usb_mux(), circle_run(), crash_check(), do_precision_loiter(), do_user_takeoff(), drift_run(), esc_calibration_startup_check(), exit_mission(), exit_mode(), fence_check(), flip_init(), home_is_set(), init_ardupilot(), init_arm_motors(), init_disarm_motors(), init_rc_in(), init_rc_out(), land_gps_run(), land_init(), land_nogps_run(), land_run_horizontal_control(), land_run_vertical_control(), Log_Write_Home_And_Origin(), loiter_run(), lost_vehicle_check(), mavlink_compassmot(), mavlink_motor_test_check(), mavlink_motor_test_start(), motor_test_output(), motor_test_stop(), motors_output(), one_hz_loop(), parachute_check(), parachute_manual_release(), poshold_init(), poshold_run(), read_battery(), read_inertia(), read_radio(), rtl_climb_return_run(), rtl_descent_run(), rtl_land_run(), rtl_loiterathome_run(), send_heartbeat(), set_auto_armed(), set_home(), set_home_state(), set_land_complete(), set_land_complete_maybe(), set_motor_emergency_stop(), set_simple_mode(), set_system_time_from_GPS(), set_throttle_and_failsafe(), set_throttle_zero_flag(), should_disarm_on_failsafe(), sport_run(), stabilize_init(), stabilize_run(), start_logging(), update_auto_armed(), update_ground_effect_detector(), update_home_from_EKF(), update_land_detector(), update_sensor_status_flags(), update_simple_mode(), update_super_simple_bearing(), update_throttle_hover(), update_throttle_thr_mix(), update_using_interlock(), verify_land(), and verify_payload_place().
AP_Vehicle::MultiCopter Copter::aparm private
Definition at line 154 of file Copter.h.
Referenced by allocate_motors(), althold_run(), drift_run(), flip_init(), get_pilot_desired_angle_rates(), get_pilot_desired_lean_angles(), land_nogps_run(), land_run_horizontal_control(), poshold_run(), sport_run(), and stabilize_run().
uint32_t Copter::arm_time_ms private
Definition at line 510 of file Copter.h.
Referenced by init_arm_motors(), and motors_output().
AP_Arming_Copter Copter::arming {ahrs, barometer, compass, battery, inertial_nav, ins} private
Definition at line 220 of file Copter.h.
Referenced by esc_calibration_startup_check(), init_arm_motors(), init_rc_out(), mavlink_compassmot(), mavlink_motor_test_check(), and one_hz_loop().
AC_AttitudeControl* Copter::attitude_control private
Definition at line 493 of file Copter.h.
Referenced by acro_run(), allocate_motors(), althold_run(), auto_circle_run(), auto_land_run(), auto_loiter_run(), auto_payload_place_run(), auto_payload_place_run_loiter(), auto_spline_run(), auto_takeoff_attitude_run(), auto_takeoff_run(), auto_wp_run(), brake_run(), circle_run(), crash_check(), drift_run(), exit_mode(), fast_loop(), flip_run(), get_pilot_desired_angle_rates(), init_ardupilot(), land_gps_run(), land_nogps_run(), land_run_horizontal_control(), Log_Write_Attitude(), Log_Write_Control_Tuning(), loiter_run(), parachute_check(), poshold_run(), rtl_climb_return_run(), rtl_descent_run(), rtl_land_run(), rtl_loiterathome_run(), send_nav_controller_output(), send_pid_tuning(), set_accel_throttle_I_from_pilot_throttle(), set_auto_yaw_look_at_heading(), sport_run(), stabilize_run(), ten_hz_logging_loop(), throw_run(), tuning(), twentyfive_hz_logging(), update_ground_effect_detector(), update_land_detector(), and update_throttle_thr_mix().
uint8_t Copter::auto_armed
Definition at line 257 of file Copter.h.
AutoMode Copter::auto_mode private
Definition at line 373 of file Copter.h.
Referenced by auto_circle_movetoedge_start(), auto_circle_start(), auto_init(), auto_land_start(), auto_loiter_start(), auto_nav_guided_start(), auto_payload_place_start(), auto_rtl_start(), auto_run(), auto_spline_start(), auto_takeoff_start(), auto_wp_start(), Copter(), do_guided(), landinggear_update(), and verify_circle().
float Copter::auto_takeoff_no_nav_alt_cm private
Definition at line 303 of file Copter.h.
Referenced by auto_takeoff_attitude_run(), and auto_takeoff_set_start_alt().
uint8_t Copter::auto_trim_counter private
Definition at line 513 of file Copter.h.
Referenced by arm_motors_check(), and Copter().
uint8_t Copter::auto_yaw_mode private
Definition at line 462 of file Copter.h.
Referenced by auto_init(), auto_spline_run(), auto_spline_start(), auto_wp_run(), auto_wp_start(), Copter(), get_auto_heading(), rtl_climb_return_run(), rtl_loiterathome_run(), set_auto_yaw_mode(), and verify_yaw().
AC_Avoid Copter::avoid private
Definition at line 537 of file Copter.h.
Referenced by althold_run(), Copter(), get_avoidance_adjusted_climbrate(), and init_ardupilot().
AP_Avoidance_Copter Copter::avoidance_adsb {ahrs, adsb} private
Definition at line 580 of file Copter.h.
Referenced by avoidance_adsb_update().
uint8_t Copter::baro
Definition at line 332 of file Copter.h.
int32_t Copter::baro_alt private
Definition at line 449 of file Copter.h.
Referenced by Copter(), Log_Write_Control_Tuning(), parachute_check(), read_barometer(), and test_baro().
float Copter::baro_climbrate private
Definition at line 450 of file Copter.h.
Referenced by Copter(), and read_barometer().
AP_Baro Copter::barometer private
Definition at line 191 of file Copter.h.
Referenced by barometer_accumulate(), init_ardupilot(), init_barometer(), Log_Sensor_Health(), Log_Write_Baro(), read_barometer(), test_baro(), and update_sensor_status_flags().
uint8_t Copter::battery
Definition at line 317 of file Copter.h.
Referenced by Copter(), init_ardupilot(), Log_Write_Current(), mavlink_compassmot(), read_battery(), report_batt_monitor(), and send_extended_status1().
AP_BattMonitor Copter::battery private
Definition at line 433 of file Copter.h.
AP_BoardConfig Copter::BoardConfig private
Definition at line 308 of file Copter.h.
Referenced by init_ardupilot(), and init_rc_out().
uint32_t Copter::brake_timeout_ms private
Definition at line 413 of file Copter.h.
Referenced by brake_init(), brake_run(), and brake_timeout_to_loiter_ms().
uint32_t Copter::brake_timeout_start private
Definition at line 412 of file Copter.h.
Referenced by brake_run(), and brake_timeout_to_loiter_ms().
AP_Camera Copter::camera private
Definition at line 523 of file Copter.h.
Referenced by Copter(), do_digicam_configure(), do_digicam_control(), do_take_picture(), log_picture(), start_command(), update_GPS(), and update_trigger().
AP_Mount Copter::camera_mount private
Definition at line 529 of file Copter.h.
Referenced by Copter(), do_mount_control(), exit_mode(), fast_loop(), init_ardupilot(), set_auto_yaw_roi(), and update_mount().
RC_Channel* Copter::channel_pitch private
Definition at line 179 of file Copter.h.
Referenced by acro_run(), althold_run(), default_dead_zones(), drift_run(), flip_init(), flip_run(), init_rc_in(), land_nogps_run(), land_run_horizontal_control(), loiter_run(), lost_vehicle_check(), poshold_run(), radio_passthrough_to_motors(), rtl_descent_run(), sport_run(), stabilize_run(), and update_simple_mode().
RC_Channel* Copter::channel_roll private
Definition at line 178 of file Copter.h.
Referenced by acro_run(), althold_run(), default_dead_zones(), drift_run(), flip_init(), flip_run(), init_rc_in(), land_nogps_run(), land_run_horizontal_control(), loiter_run(), lost_vehicle_check(), poshold_run(), radio_passthrough_to_motors(), rtl_descent_run(), sport_run(), stabilize_run(), and update_simple_mode().
RC_Channel* Copter::channel_throttle private
Definition at line 180 of file Copter.h.
Referenced by acro_init(), acro_run(), althold_run(), arm_motors_check(), auto_disarm_check(), circle_run(), compass_cal_update(), default_dead_zones(), drift_run(), esc_calibration_passthrough(), esc_calibration_startup_check(), flip_run(), get_pilot_desired_climb_rate(), get_pilot_desired_throttle(), init_rc_in(), init_rc_out(), loiter_run(), mavlink_compassmot(), motor_test_output(), one_hz_loop(), poshold_run(), radio_passthrough_to_motors(), read_radio(), set_throttle_and_failsafe(), sport_run(), stabilize_init(), stabilize_run(), update_ground_effect_detector(), and update_throttle_thr_mix().
RC_Channel* Copter::channel_yaw private
Definition at line 181 of file Copter.h.
Referenced by acro_run(), althold_run(), arm_motors_check(), auto_loiter_run(), auto_spline_run(), auto_takeoff_run(), auto_wp_run(), circle_run(), compass_cal_update(), default_dead_zones(), drift_run(), init_rc_in(), land_nogps_run(), land_run_horizontal_control(), loiter_run(), poshold_run(), radio_passthrough_to_motors(), rtl_climb_return_run(), rtl_descent_run(), rtl_loiterathome_run(), sport_run(), and stabilize_run().
AC_Circle* Copter::circle_nav private
Definition at line 496 of file Copter.h.
Referenced by allocate_motors(), auto_circle_movetoedge_start(), auto_circle_run(), auto_circle_start(), circle_init(), circle_run(), tuning(), and verify_circle().
bool Copter::circle_pilot_yaw_override private
Definition at line 393 of file Copter.h.
Referenced by circle_init(), circle_run(), and Copter().
int16_t Copter::climb_rate private
Definition at line 447 of file Copter.h.
Referenced by Copter(), Log_Write_Control_Tuning(), read_inertia(), send_vfr_hud(), and update_throttle_hover().
Location_Class Copter::climb_target
Definition at line 385 of file Copter.h.
AP_HAL::BetterStream* Copter::cliSerial private
Definition at line 159 of file Copter.h.
Referenced by dump_log(), esc_calib(), init_ardupilot(), init_compass(), Log_Read(), main_menu_help(), print_accel_offsets_and_scaling(), print_blanks(), print_divider(), print_enabled(), print_gyro_offsets(), print_hit_enter(), print_log_menu(), print_radio_values(), print_switch(), report_batt_monitor(), report_compass(), report_flight_modes(), report_frame(), report_ins(), report_optflow(), report_radio(), report_version(), run_cli(), select_logs(), setup(), setup_factory(), setup_mode(), setup_set(), setup_show(), test_baro(), test_compass(), test_ins(), test_optflow(), test_rangefinder(), test_relay(), and test_shell().
uint8_t Copter::command_ack_counter private
Definition at line 172 of file Copter.h.
Referenced by mavlink_compassmot().
Compass Copter::compass private
Definition at line 192 of file Copter.h.
Referenced by compass_accumulate(), compass_cal_update(), init_compass(), init_disarm_motors(), Log_Sensor_Health(), mavlink_compassmot(), read_battery(), report_compass(), set_home(), test_compass(), tuning(), update_batt_compass(), and update_sensor_status_flags().
uint8_t Copter::compass
Definition at line 333 of file Copter.h.
uint8_t Copter::compass_mot
Definition at line 263 of file Copter.h.
uint32_t Copter::condition_start private
Definition at line 481 of file Copter.h.
Referenced by Copter(), do_wait_delay(), and verify_wait_delay().
int32_t Copter::condition_value private
Definition at line 480 of file Copter.h.
Referenced by Copter(), do_wait_delay(), do_within_distance(), verify_wait_delay(), and verify_within_distance().
control_mode_t Copter::control_mode private
Definition at line 282 of file Copter.h.
Referenced by acro_init(), arm_motors_check(), auto_disarm_check(), avoid_adsb_set_velocity(), calc_wp_bearing(), calc_wp_distance(), Copter(), crash_check(), current_mode_has_user_takeoff(), do_guided(), do_user_takeoff(), failsafe_battery_event(), failsafe_gcs_check(), failsafe_radio_on_event(), failsafe_terrain_check(), failsafe_terrain_on_event(), fence_check(), flip_init(), init_ardupilot(), init_arm_motors(), landing_with_GPS(), landinggear_update(), Log_Write_Vehicle_Startup_Messages(), motors_output(), parachute_check(), run_autopilot(), send_heartbeat(), set_land_complete(), set_mode(), should_disarm_on_failsafe(), stabilize_init(), ten_hz_logging_loop(), update_auto_armed(), update_flight_mode(), update_ground_effect_detector(), update_sensor_status_flags(), update_throttle_hover(), update_throttle_thr_mix(), and verify_command_callback().
mode_reason_t Copter::control_mode_reason = MODE_REASON_UNKNOWN private
Definition at line 283 of file Copter.h.
Referenced by init_arm_motors(), Log_Write_Vehicle_Startup_Messages(), and set_mode().
uint32_t Copter::control_sensors_enabled private
Definition at line 442 of file Copter.h.
Referenced by send_extended_status1(), and update_sensor_status_flags().
uint32_t Copter::control_sensors_health private
Definition at line 443 of file Copter.h.
Referenced by send_extended_status1(), and update_sensor_status_flags().
uint32_t Copter::control_sensors_present private
Definition at line 441 of file Copter.h.
Referenced by send_extended_status1(), and update_sensor_status_flags().
struct { ... } Copter::control_switch_state
Location_Class Copter::current_loc private
Definition at line 458 of file Copter.h.
Referenced by auto_takeoff_start(), Copter(), do_circle(), do_loiter_unlimited(), do_nav_wp(), do_spline_wp(), do_user_takeoff(), fence_check(), land_get_alt_above_ground(), log_picture(), parachute_check(), parachute_manual_release(), read_inertia(), rtl_compute_return_target(), rtl_descent_run(), send_location(), send_vfr_hud(), terrain_adjusted_location(), update_GPS(), update_precland(), and update_trigger().
DataFlash_Class Copter::DataFlash private
Definition at line 184 of file Copter.h.
Referenced by dataflash_periodic(), do_erase_logs(), dump_log(), init_ardupilot(), init_arm_motors(), init_disarm_motors(), log_init(), log_picture(), Log_Read(), Log_Write_Attitude(), Log_Write_AutoTune(), Log_Write_AutoTuneDetails(), Log_Write_Baro(), Log_Write_Beacon(), Log_Write_Control_Tuning(), Log_Write_Current(), Log_Write_Data(), Log_Write_Error(), Log_Write_Event(), Log_Write_GuidedTarget(), Log_Write_Home_And_Origin(), Log_Write_MotBatt(), Log_Write_Nav_Tuning(), Log_Write_Optflow(), Log_Write_Parameter_Tuning(), Log_Write_Performance(), Log_Write_Precland(), Log_Write_Proximity(), Log_Write_Throw(), Log_Write_Vehicle_Startup_Messages(), perf_info_reset(), print_log_menu(), read_rangefinder(), rpm_update(), set_home(), set_mode(), should_log(), start_command(), start_logging(), ten_hz_logging_loop(), terrain_logging(), twentyfive_hz_logging(), update_batt_compass(), update_GPS(), and update_trigger().
int8_t Copter::debounced_switch_position
Definition at line 290 of file Copter.h.
float Copter::descend_max
Definition at line 369 of file Copter.h.
float Copter::descend_start_altitude
Definition at line 368 of file Copter.h.
uint32_t Copter::descend_start_timestamp
Definition at line 365 of file Copter.h.
float Copter::descend_throttle_level
Definition at line 367 of file Copter.h.
Location_Class Copter::descent_target
Definition at line 387 of file Copter.h.
uint8_t Copter::ekf
Definition at line 319 of file Copter.h.
NavEKF2 Copter::EKF2 {&ahrs, barometer, rangefinder} private
Definition at line 208 of file Copter.h.
NavEKF3 Copter::EKF3 {&ahrs, barometer, rangefinder} private
Definition at line 209 of file Copter.h.
int8_t Copter::ekf_primary_core private
Definition at line 235 of file Copter.h.
float Copter::ekfGndSpdLimit private
Definition at line 228 of file Copter.h.
Referenced by auto_payload_place_run_loiter(), brake_run(), land_run_horizontal_control(), loiter_run(), poshold_run(), rtl_descent_run(), throw_run(), and update_flight_mode().
float Copter::ekfNavVelGainScaler private
Definition at line 231 of file Copter.h.
Referenced by auto_payload_place_run_loiter(), brake_run(), land_run_horizontal_control(), loiter_run(), poshold_run(), rtl_descent_run(), throw_run(), and update_flight_mode().
uint32_t Copter::ekfYawReset_ms = 0 private
Definition at line 234 of file Copter.h.
bool Copter::enabled
Definition at line 197 of file Copter.h.
struct { ... } Copter::failsafe
Referenced by auto_loiter_run(), auto_spline_run(), auto_takeoff_run(), auto_wp_run(), circle_run(), failsafe_battery_event(), failsafe_check(), failsafe_gcs_check(), failsafe_radio_on_event(), failsafe_terrain_check(), failsafe_terrain_on_event(), failsafe_terrain_set_status(), fence_check(), get_pilot_desired_climb_rate(), land_nogps_run(), land_run_horizontal_control(), loiter_run(), poshold_run(), position_ok(), read_battery(), read_radio(), rtl_climb_return_run(), rtl_descent_run(), rtl_init(), rtl_loiterathome_run(), rtl_run(), send_heartbeat(), set_failsafe_battery(), set_failsafe_gcs(), set_failsafe_radio(), set_throttle_and_failsafe(), tuning(), update_auto_armed(), and update_sensor_status_flags().
uint32_t Copter::fast_loopTimer private
Definition at line 504 of file Copter.h.
Referenced by Copter(), loop(), setup(), and test_compass().
AC_Fence Copter::fence private
Definition at line 534 of file Copter.h.
Referenced by Copter(), failsafe_check(), fence_check(), fence_send_mavlink_status(), rtl_compute_return_target(), and set_mode().
AP_Int8* Copter::flight_modes private
Definition at line 189 of file Copter.h.
Referenced by Copter(), and report_flight_modes().
Vector3f Copter::flip_orig_attitude private
Definition at line 420 of file Copter.h.
Referenced by flip_init(), and flip_run().
uint32_t Copter::free_fall_start_ms
Definition at line 428 of file Copter.h.
float Copter::free_fall_start_velz
Definition at line 429 of file Copter.h.
AP_Frsky_Telem Copter::frsky_telemetry private
Definition at line 437 of file Copter.h.
Referenced by Copter(), init_ardupilot(), set_mode(), and update_sensor_status_flags().
Parameters Copter::g private
Definition at line 162 of file Copter.h.
Referenced by acro_run(), allocate_motors(), althold_init(), althold_run(), auto_disarm_check(), auto_land_run(), auto_loiter_run(), auto_payload_place_run(), auto_spline_run(), auto_takeoff_run(), auto_wp_run(), brake_run(), circle_init(), circle_run(), compass_accumulate(), Copter(), crash_check(), drift_run(), esc_calibration_auto(), esc_calibration_passthrough(), esc_calibration_startup_check(), failsafe_battery_event(), failsafe_gcs_check(), failsafe_radio_on_event(), flip_run(), gcs_check_input(), get_default_auto_yaw_mode(), get_pilot_desired_angle_rates(), get_pilot_desired_climb_rate(), get_pilot_desired_yaw_rate(), get_smoothing_gain(), get_surface_tracking_climb_rate(), init_ardupilot(), init_rc_out(), land_gps_run(), land_nogps_run(), land_run_horizontal_control(), land_run_vertical_control(), loiter_init(), loiter_run(), mavlink_compassmot(), mavlink_motor_test_start(), motor_test_stop(), one_hz_loop(), poshold_init(), poshold_run(), poshold_update_brake_angle_from_velocity(), poshold_update_pilot_lean_angle(), print_log_menu(), read_battery(), read_radio(), report_compass(), report_flight_modes(), report_version(), rtl_build_path(), rtl_climb_return_run(), rtl_climb_start(), rtl_compute_return_target(), rtl_descent_run(), rtl_land_run(), rtl_loiterathome_run(), select_logs(), send_pid_tuning(), set_accel_throttle_I_from_pilot_throttle(), set_home(), set_land_complete(), set_throttle_and_failsafe(), should_log(), sport_init(), sport_run(), stabilize_run(), start_logging(), takeoff_timer_start(), ten_hz_logging_loop(), terrain_use(), test_compass(), throw_run(), tuning(), twentyfive_hz_logging(), update_batt_compass(), update_optical_flow(), and update_sensor_status_flags().
ParametersG2 Copter::g2 private
Definition at line 163 of file Copter.h.
Referenced by acro_init(), acro_run(), allocate_motors(), auto_takeoff_attitude_run(), auto_takeoff_set_start_alt(), button_update(), Copter(), do_gripper(), failsafe_check(), get_frame_mav_type(), get_frame_string(), get_pilot_desired_yaw_rate(), gripper_update(), init_ardupilot(), init_beacon(), init_proximity(), init_rc_out(), land_run_horizontal_control(), Log_Write_Beacon(), Log_Write_Proximity(), motors_output(), one_hz_loop(), send_proximity(), set_default_frame_class(), set_land_complete(), stats_update(), throw_detected(), throw_run(), update_beacon(), update_ground_effect_detector(), update_proximity(), and verify_payload_place().
float Copter::G_Dt private
Definition at line 486 of file Copter.h.
Referenced by althold_run(), brake_run(), circle_run(), Copter(), land_run_vertical_control(), loiter_run(), loop(), poshold_run(), read_inertia(), rtl_descent_run(), sport_run(), test_compass(), and throw_run().
uint8_t Copter::gcs
Definition at line 318 of file Copter.h.
GCS_MAVLINK_Copter Copter::gcs_chan[MAVLINK_COMM_NUM_BUFFERS] private
Definition at line 241 of file Copter.h.
Referenced by gcs_check_input(), gcs_data_stream_send(), gcs_send_message(), gcs_send_mission_item_reached_message(), init_ardupilot(), log_init(), mavlink_compassmot(), mavlink_delay_cb(), mavlink_motor_test_check(), and send_heartbeat().
bool Copter::gcs_out_of_time private
Definition at line 586 of file Copter.h.
Referenced by Copter().
int8_t Copter::glitch_count
Definition at line 202 of file Copter.h.
struct { ... } Copter::gndeffect_state
Referenced by update_ground_effect_detector().
AP_GPS Copter::gps private
Definition at line 186 of file Copter.h.
Referenced by GCS_MAVLINK_Copter::handleMessage(), init_ardupilot(), log_picture(), Log_Sensor_Health(), send_location(), send_vfr_hud(), set_home(), set_system_time_from_GPS(), update_GPS(), update_sensor_status_flags(), and update_trigger().
uint8_t Copter::gps_base_pos_set
Definition at line 269 of file Copter.h.
GuidedMode Copter::guided_mode private
Definition at line 376 of file Copter.h.
Referenced by calc_wp_bearing(), calc_wp_distance(), and Copter().
int32_t Copter::home_bearing private
Definition at line 354 of file Copter.h.
Referenced by calc_home_distance_and_bearing(), Copter(), and update_super_simple_bearing().
int32_t Copter::home_distance private
Definition at line 356 of file Copter.h.
Referenced by calc_home_distance_and_bearing(), Copter(), fence_check(), and update_super_simple_bearing().
enum HomeState Copter::home_state
Definition at line 270 of file Copter.h.
uint32_t Copter::hover_start_timestamp
Definition at line 363 of file Copter.h.
float Copter::hover_throttle_level
Definition at line 364 of file Copter.h.
uint8_t Copter::in_arming_delay
Definition at line 275 of file Copter.h.
bool Copter::in_log_download private
Definition at line 175 of file Copter.h.
Referenced by should_log(), and start_logging().
bool Copter::in_mavlink_delay private
Definition at line 583 of file Copter.h.
Referenced by Copter(), erase_logs(), mavlink_delay_cb(), and should_log().
AP_InertialNav_NavEKF Copter::inertial_nav private
Definition at line 489 of file Copter.h.
Referenced by allocate_motors(), althold_init(), apogee_run(), auto_circle_movetoedge_start(), auto_land_start(), auto_loiter_start(), auto_payload_place_start(), auto_takeoff_attitude_run(), auto_takeoff_set_start_alt(), brake_init(), calc_home_distance_and_bearing(), Copter(), drift_run(), ekf_position_ok(), far_from_EKF_origin(), get_look_ahead_yaw(), get_roi_yaw(), get_surface_tracking_climb_rate(), land_init(), land_run_horizontal_control(), Log_Write_Control_Tuning(), Log_Write_Nav_Tuning(), loiter_init(), optflow_position_ok(), poshold_init(), poshold_run(), poshold_update_wind_comp_estimate(), precision_loiter_xy(), pv_alt_above_home(), pv_alt_above_origin(), pv_location_to_vector(), read_inertia(), rtl_land_start(), send_location(), set_home_to_current_location(), set_home_to_current_location_inflight(), sport_init(), throw_detected(), throw_run(), update_ground_effect_detector(), update_land_detector(), verify_circle(), and verify_payload_place().
int32_t Copter::initial_armed_bearing private
Definition at line 405 of file Copter.h.
Referenced by Copter(), get_auto_heading(), init_arm_motors(), and rtl_loiterathome_run().
uint8_t Copter::initialised
Definition at line 265 of file Copter.h.
Referenced by gcs_check_input(), gcs_data_stream_send(), gcs_send_message(), gcs_send_mission_item_reached_message(), init_ardupilot(), and mavlink_delay_cb().
AP_InertialSensor Copter::ins private
Definition at line 193 of file Copter.h.
Referenced by accel_cal_update(), apogee_run(), fast_loop(), GCS_MAVLINK_Copter::handleMessage(), init_ardupilot(), Log_Write_Performance(), loop(), one_hz_loop(), print_accel_offsets_and_scaling(), print_gyro_offsets(), send_attitude(), startup_INS_ground(), ten_hz_logging_loop(), test_compass(), test_ins(), throw_detected(), throw_run(), twentyfive_hz_logging(), and update_sensor_status_flags().
bool Copter::land
Definition at line 388 of file Copter.h.
LowPassFilterVector3f Copter::land_accel_ef_filter private
Definition at line 451 of file Copter.h.
Referenced by Copter(), crash_check(), update_land_and_crash_detectors(), and update_land_detector().
uint8_t Copter::land_complete
Definition at line 259 of file Copter.h.
uint8_t Copter::land_complete_maybe
Definition at line 266 of file Copter.h.
uint8_t Copter::land_repo_active
Definition at line 273 of file Copter.h.
LandStateType Copter::land_state = LandStateType_FlyToLocation private
Definition at line 359 of file Copter.h.
Referenced by do_land(), and verify_land().
AP_LandingGear Copter::landinggear private
Definition at line 558 of file Copter.h.
Referenced by landinggear_update(), and parachute_release().
uint32_t Copter::last_edge_time_ms
Definition at line 292 of file Copter.h.
uint32_t Copter::last_healthy_ms
Definition at line 200 of file Copter.h.
uint32_t Copter::last_heartbeat_ms
Definition at line 325 of file Copter.h.
uint32_t Copter::last_log_ms
Definition at line 426 of file Copter.h.
uint32_t Copter::last_radio_update_ms private
Definition at line 589 of file Copter.h.
Referenced by failsafe_check(), init_rc_out(), and read_radio().
int8_t Copter::last_switch_position
Definition at line 291 of file Copter.h.
Copter::LOG_COMMON_STRUCTURES
Definition at line 867 of file Log.cpp.
const struct LogStructure Copter::log_structure[] static private
Definition at line 623 of file Copter.h.
Referenced by log_init(), and Log_Write_Beacon().
uint8_t Copter::logging_started
Definition at line 258 of file Copter.h.
uint32_t Copter::loiter_time private
Definition at line 409 of file Copter.h.
Referenced by Copter(), do_loiter_time(), do_nav_wp(), do_spline_wp(), verify_loiter_time(), verify_nav_wp(), and verify_spline_wp().
uint16_t Copter::loiter_time_max private
Definition at line 408 of file Copter.h.
Referenced by Copter(), do_loiter_time(), do_nav_wp(), do_spline_wp(), verify_loiter_time(), verify_nav_wp(), and verify_spline_wp().
uint16_t Copter::mainLoop_count private
Definition at line 506 of file Copter.h.
Referenced by Copter(), failsafe_check(), and loop().
float Copter::max_speed
Definition at line 297 of file Copter.h.
AP_Mission Copter::mission private
Definition at line 217 of file Copter.h.
Referenced by auto_init(), Copter(), do_spline_wp(), exit_mode(), init_ardupilot(), init_disarm_motors(), run_autopilot(), send_current_waypoint(), set_home(), start_command(), and start_logging().
uint8_t Copter::motor_emergency_stop
Definition at line 272 of file Copter.h.
uint8_t Copter::motor_interlock_switch
Definition at line 274 of file Copter.h.
uint8_t Copter::motor_test
Definition at line 264 of file Copter.h.
MOTOR_CLASS* Copter::motors private
Definition at line 344 of file Copter.h.
Referenced by acro_init(), acro_run(), allocate_motors(), althold_init(), althold_run(), arm_motors_check(), auto_disarm_check(), auto_init(), auto_land_run(), auto_loiter_run(), auto_payload_place_run(), auto_payload_place_run_should_run(), auto_spline_run(), auto_takeoff_run(), auto_takeoff_set_start_alt(), auto_wp_run(), brake_run(), circle_run(), compass_cal_update(), crash_check(), do_user_takeoff(), drift_run(), ekf_position_ok(), enable_motor_output(), esc_calib(), esc_calibration_auto(), esc_calibration_passthrough(), exit_mode(), failsafe_battery_event(), failsafe_check(), failsafe_gcs_check(), failsafe_radio_on_event(), fence_check(), flip_init(), flip_run(), get_non_takeoff_throttle(), get_pilot_desired_throttle(), get_surface_tracking_climb_rate(), init_ardupilot(), init_arm_motors(), init_disarm_motors(), init_rc_out(), land_gps_run(), land_nogps_run(), Log_Write_Control_Tuning(), Log_Write_MotBatt(), loiter_init(), loiter_run(), lost_vehicle_check(), mavlink_compassmot(), mavlink_motor_test_start(), motor_test_output(), motor_test_stop(), motors_output(), one_hz_loop(), optflow_position_ok(), parachute_check(), poshold_init(), poshold_run(), radio_passthrough_to_motors(), read_barometer(), read_battery(), read_radio(), rtl_climb_return_run(), rtl_descent_run(), rtl_land_run(), rtl_loiterathome_run(), run_cli(), send_heartbeat(), send_vfr_hud(), set_accel_throttle_I_from_pilot_throttle(), set_land_complete(), set_mode(), set_throttle_and_failsafe(), set_throttle_zero_flag(), should_log(), sport_run(), stabilize_init(), stabilize_run(), ten_hz_logging_loop(), throw_init(), throw_run(), tuning(), twentyfive_hz_logging(), update_auto_armed(), update_batt_compass(), update_ground_effect_detector(), update_home_from_EKF(), update_land_detector(), update_throttle_hover(), update_throttle_thr_mix(), and verify_payload_place().
const struct AP_Param::GroupInfo* Copter::motors_var_info private
Definition at line 345 of file Copter.h.
Referenced by allocate_motors().
int32_t Copter::nav_delay_time_max private
Definition at line 416 of file Copter.h.
Referenced by do_nav_delay(), and verify_nav_delay().
uint32_t Copter::nav_delay_time_start private
Definition at line 417 of file Copter.h.
Referenced by do_nav_delay(), and verify_nav_delay().
struct { ... } Copter::nav_payload_place
Referenced by auto_payload_place_run(), auto_payload_place_start(), do_payload_place(), and verify_payload_place().
uint8_t Copter::new_radio_frame
Definition at line 260 of file Copter.h.
bool Copter::nextmode_attempted
Definition at line 427 of file Copter.h.
AP_Notify Copter::notify private
Definition at line 169 of file Copter.h.
Referenced by gcs_send_text(), gcs_send_text_fmt(), init_ardupilot(), mavlink_delay_cb(), notify_flight_mode(), and update_notify().
const uint8_t Copter::num_gcs = MAVLINK_COMM_NUM_BUFFERS static private
Definition at line 239 of file Copter.h.
Referenced by gcs_check_input(), gcs_data_stream_send(), gcs_send_message(), gcs_send_mission_item_reached_message(), init_ardupilot(), and log_init().
OpticalFlow Copter::optflow {ahrs} private
Definition at line 224 of file Copter.h.
Referenced by init_ardupilot(), init_optflow(), Log_Write_Attitude(), Log_Write_Optflow(), optflow_position_ok(), report_optflow(), test_compass(), test_optflow(), update_optical_flow(), and update_sensor_status_flags().
Location_Class Copter::origin_point
Definition at line 384 of file Copter.h.
AP_Parachute Copter::parachute private
Definition at line 554 of file Copter.h.
Referenced by Copter(), do_parachute(), parachute_check(), parachute_manual_release(), and parachute_release().
AP_Param Copter::param_loader private
Definition at line 593 of file Copter.h.
Referenced by Copter().
uint32_t Copter::place_start_timestamp
Definition at line 366 of file Copter.h.
int16_t Copter::pmTest1 private
Definition at line 499 of file Copter.h.
Referenced by Copter(), Log_Write_Performance(), and perf_update().
AC_PosControl* Copter::pos_control private
Definition at line 494 of file Copter.h.
Referenced by acro_init(), allocate_motors(), althold_init(), althold_run(), auto_circle_run(), auto_land_start(), auto_loiter_run(), auto_loiter_start(), auto_payload_place_run_loiter(), auto_payload_place_start(), auto_spline_run(), auto_takeoff_attitude_run(), auto_takeoff_run(), auto_wp_run(), brake_init(), brake_run(), circle_init(), circle_run(), get_avoidance_adjusted_climbrate(), init_ardupilot(), land_get_alt_above_ground(), land_init(), land_run_horizontal_control(), land_run_vertical_control(), Log_Write_Control_Tuning(), Log_Write_Nav_Tuning(), loiter_init(), loiter_run(), poshold_init(), poshold_run(), poshold_update_wind_comp_estimate(), precision_loiter_xy(), rtl_build_path(), rtl_climb_return_run(), rtl_descent_run(), rtl_descent_start(), rtl_land_start(), rtl_loiterathome_run(), send_nav_controller_output(), set_throttle_takeoff(), sport_init(), sport_run(), stabilize_init(), ten_hz_logging_loop(), throw_height_good(), throw_position_good(), throw_run(), twentyfive_hz_logging(), update_ground_effect_detector(), update_throttle_hover(), and update_throttle_thr_mix().
uint8_t Copter::pre_arm_check
Definition at line 256 of file Copter.h.
uint8_t Copter::pre_arm_rc_check
Definition at line 255 of file Copter.h.
AC_PrecLand Copter::precland private
Definition at line 567 of file Copter.h.
Referenced by Copter(), do_precision_loiter(), land_run_horizontal_control(), land_run_vertical_control(), Log_Write_Precland(), precision_loiter_xy(), and update_sensor_status_flags().
control_mode_t Copter::prev_control_mode private
Definition at line 285 of file Copter.h.
Referenced by AP_Avoidance_Copter::handle_avoidance(), AP_Avoidance_Copter::handle_recovery(), and set_mode().
mode_reason_t Copter::prev_control_mode_reason = MODE_REASON_UNKNOWN private
Definition at line 286 of file Copter.h.
Referenced by set_mode().
ThrowModeStage Copter::prev_stage
Definition at line 425 of file Copter.h.
uint8_t Copter::primary_gps
Definition at line 334 of file Copter.h.
uint8_t Copter::radio
Definition at line 316 of file Copter.h.
int8_t Copter::radio_counter
Definition at line 323 of file Copter.h.
AP_Rally_Copter Copter::rally private
Definition at line 541 of file Copter.h.
Referenced by Copter(), Log_Write_Vehicle_Startup_Messages(), and rtl_compute_return_target().
RangeFinder Copter::rangefinder {serial_manager, ROTATION_PITCH_270} private
Definition at line 195 of file Copter.h.
Referenced by Copter(), init_proximity(), init_rangefinder(), read_rangefinder(), send_rangefinder(), terrain_update(), test_rangefinder(), and update_sensor_status_flags().
struct { ... } Copter::rangefinder_state
Referenced by get_surface_tracking_climb_rate(), init_rangefinder(), land_get_alt_above_ground(), land_run_vertical_control(), Log_Write_Control_Tuning(), rangefinder_alt_ok(), read_rangefinder(), update_land_detector(), update_precland(), and update_sensor_status_flags().
uint8_t Copter::rc_override_active
Definition at line 315 of file Copter.h.
uint8_t Copter::rc_receiver_present
Definition at line 262 of file Copter.h.
LowPassFilterFloat Copter::rc_throttle_control_in_filter private
Definition at line 454 of file Copter.h.
Referenced by Copter(), land_nogps_run(), land_run_horizontal_control(), read_radio(), and rtl_descent_run().
RCMapper Copter::rcmap private
Definition at line 305 of file Copter.h.
Referenced by init_rc_in().
uint8_t Copter::receiver_rssi private
Definition at line 311 of file Copter.h.
Referenced by read_receiver_rssi().
AP_Relay Copter::relay private
Definition at line 516 of file Copter.h.
Referenced by Copter(), init_ardupilot(), and test_relay().
Location_Class Copter::return_target
Definition at line 386 of file Copter.h.
Vector3f Copter::roi_WP private
Definition at line 465 of file Copter.h.
Referenced by get_roi_yaw(), and set_auto_yaw_roi().
AP_RPM Copter::rpm_sensor private
Definition at line 205 of file Copter.h.
Referenced by init_ardupilot(), rpm_update(), and send_rpm().
AP_RSSI Copter::rssi private
Definition at line 545 of file Copter.h.
Referenced by init_ardupilot(), read_receiver_rssi(), and ten_hz_logging_loop().
uint32_t Copter::rtl_loiter_start_time private
Definition at line 508 of file Copter.h.
Referenced by Copter(), rtl_loiterathome_run(), and rtl_loiterathome_start().
struct { ... } Copter::rtl_path
Referenced by rtl_build_path(), rtl_climb_start(), rtl_compute_return_target(), rtl_descent_run(), rtl_restart_without_terrain(), rtl_return_start(), and rtl_run().
RTLState Copter::rtl_state private
Definition at line 379 of file Copter.h.
Referenced by Copter(), landinggear_update(), rtl_climb_start(), rtl_descent_start(), rtl_land_start(), rtl_loiterathome_start(), rtl_return_start(), rtl_run(), and verify_RTL().
bool Copter::rtl_state_complete private
Definition at line 380 of file Copter.h.
Referenced by Copter(), rtl_climb_return_run(), rtl_climb_start(), rtl_descent_run(), rtl_descent_start(), rtl_land_run(), rtl_land_start(), rtl_loiterathome_run(), rtl_loiterathome_start(), rtl_return_start(), rtl_run(), and verify_RTL().
bool Copter::running
Definition at line 296 of file Copter.h.
float Copter::scaleLongDown private
Definition at line 349 of file Copter.h.
Referenced by Copter(), pv_location_to_vector(), and set_home().
AP_Scheduler Copter::scheduler private
Definition at line 166 of file Copter.h.
Referenced by crash_check(), init_rc_out(), loop(), parachute_check(), perf_update(), send_extended_status1(), setup(), startup_INS_ground(), test_compass(), test_ins(), and update_land_detector().
const AP_Scheduler::Task Copter::scheduler_tasks static private
Definition at line 621 of file Copter.h.
Referenced by setup().
struct { ... } Copter::sensor_health
Referenced by Copter(), and Log_Sensor_Health().
AP_SerialManager Copter::serial_manager private
Definition at line 238 of file Copter.h.
Referenced by init_ardupilot().
AP_ServoRelayEvents Copter::ServoRelayEvents private
Definition at line 519 of file Copter.h.
Referenced by Copter(), init_ardupilot(), start_command(), and update_events().
float Copter::simple_cos_yaw private
Definition at line 398 of file Copter.h.
Referenced by Copter(), init_simple_bearing(), and update_simple_mode().
uint8_t Copter::simple_mode
Definition at line 254 of file Copter.h.
float Copter::simple_sin_yaw private
Definition at line 399 of file Copter.h.
Referenced by Copter(), init_simple_bearing(), and update_simple_mode().
SITL::SITL Copter::sitl private
Definition at line 213 of file Copter.h.
Referenced by Log_Write_Attitude(), and send_simstate().
AC_Sprayer Copter::sprayer private
Definition at line 549 of file Copter.h.
Referenced by Copter(), init_arm_motors(), and three_hz_loop().
ThrowModeStage Copter::stage
Definition at line 424 of file Copter.h.
Referenced by log_init().
uint32_t Copter::start_ms
Definition at line 299 of file Copter.h.
PayloadPlaceStateType Copter::state = PayloadPlaceStateType_Calibrating_Hover_Start
Definition at line 362 of file Copter.h.
float Copter::super_simple_cos_yaw private
Definition at line 401 of file Copter.h.
Referenced by Copter(), init_simple_bearing(), update_simple_mode(), and update_super_simple_bearing().
int32_t Copter::super_simple_last_bearing private
Definition at line 400 of file Copter.h.
Referenced by Copter(), init_simple_bearing(), and update_super_simple_bearing().
float Copter::super_simple_sin_yaw private
Definition at line 402 of file Copter.h.
Referenced by Copter(), init_simple_bearing(), update_simple_mode(), and update_super_simple_bearing().
uint8_t Copter::system_time_set
Definition at line 268 of file Copter.h.
float Copter::takeoff_alt_cm
Definition at line 615 of file Copter.h.
Referenced by gcs_set_mode().
bool Copter::takeoff_expected
Definition at line 612 of file Copter.h.
struct { ... } Copter::takeoff_state
Referenced by althold_run(), loiter_run(), poshold_run(), sport_run(), takeoff_get_climb_rates(), takeoff_stop(), and takeoff_timer_start().
uint32_t Copter::takeoff_time_ms
Definition at line 614 of file Copter.h.
float Copter::target_rangefinder_alt private
Definition at line 448 of file Copter.h.
Referenced by Copter(), get_surface_tracking_climb_rate(), and Log_Write_Control_Tuning().
uint8_t Copter::terrain
Definition at line 320 of file Copter.h.
Referenced by Copter(), init_ardupilot(), Log_Write_Control_Tuning(), terrain_logging(), terrain_update(), and update_sensor_status_flags().
uint32_t Copter::terrain_first_failure_ms
Definition at line 326 of file Copter.h.
uint32_t Copter::terrain_last_failure_ms
Definition at line 327 of file Copter.h.
bool Copter::terrain_used
Definition at line 389 of file Copter.h.
uint8_t Copter::throttle_zero
Definition at line 267 of file Copter.h.
struct { ... } Copter::throw_state
Referenced by throw_detected(), throw_init(), and throw_run().
bool Copter::touchdown_expected
Definition at line 613 of file Copter.h.
uint8_t Copter::unused1
Definition at line 253 of file Copter.h.
bool Copter::upgrading_frame_params private
Definition at line 619 of file Copter.h.
Referenced by allocate_motors().
uint8_t Copter::usb_connected
Definition at line 261 of file Copter.h.
uint8_t Copter::using_interlock
Definition at line 271 of file Copter.h.
uint32_t Copter::value
Definition at line 277 of file Copter.h.
Referenced by log_init(), and set_precision_loiter_enabled().
const AP_Param::Info Copter::var_info static private
Definition at line 622 of file Copter.h.
Referenced by Copter().
int32_t Copter::wp_bearing private
Definition at line 352 of file Copter.h.
Referenced by calc_wp_bearing(), Copter(), and send_nav_controller_output().
uint32_t Copter::wp_distance private
Definition at line 358 of file Copter.h.
Referenced by calc_wp_distance(), Copter(), send_nav_controller_output(), and verify_within_distance().
AC_WPNav* Copter::wp_nav private
Definition at line 495 of file Copter.h.
Referenced by allocate_motors(), auto_circle_movetoedge_start(), auto_init(), auto_land_run(), auto_land_start(), auto_loiter_run(), auto_loiter_start(), auto_payload_place_run(), auto_payload_place_run_loiter(), auto_payload_place_start(), auto_spline_run(), auto_spline_start(), auto_takeoff_attitude_run(), auto_takeoff_run(), auto_takeoff_start(), auto_wp_run(), auto_wp_start(), brake_init(), brake_run(), calc_wp_bearing(), calc_wp_distance(), circle_init(), circle_run(), do_change_speed(), do_loiter_unlimited(), do_nav_wp(), do_precision_loiter(), get_auto_heading(), init_ardupilot(), land_gps_run(), land_init(), land_run_horizontal_control(), loiter_init(), loiter_run(), poshold_init(), poshold_run(), precision_loiter_xy(), read_rangefinder(), rtl_climb_return_run(), rtl_climb_start(), rtl_descent_run(), rtl_descent_start(), rtl_land_run(), rtl_land_start(), rtl_loiterathome_run(), rtl_return_start(), takeoff_timer_start(), throw_run(), tuning(), verify_circle(), verify_land(), verify_loiter_time(), verify_nav_wp(), verify_payload_place(), verify_spline_wp(), and verify_takeoff().
float Copter::yaw_look_ahead_bearing private
Definition at line 477 of file Copter.h.
Referenced by Copter(), get_look_ahead_yaw(), and set_auto_yaw_mode().
int32_t Copter::yaw_look_at_heading private
Definition at line 471 of file Copter.h.
Referenced by Copter(), get_auto_heading(), set_auto_yaw_look_at_heading(), and verify_yaw().
int16_t Copter::yaw_look_at_heading_slew private
Definition at line 474 of file Copter.h.
Referenced by Copter(), and set_auto_yaw_look_at_heading().
float Copter::yaw_look_at_WP_bearing private
Definition at line 468 of file Copter.h.
Referenced by Copter(), get_roi_yaw(), and set_auto_yaw_mode().
The documentation for this struct was generated from the following files:
ArduCopter/Copter.h
ArduCopter/Log.cpp
ArduCopter/AP_State.cpp
ArduCopter/ArduCopter.cpp
ArduCopter/Attitude.cpp
ArduCopter/avoidance_adsb.cpp
ArduCopter/baro_ground_effect.cpp
ArduCopter/capabilities.cpp
ArduCopter/commands.cpp
ArduCopter/commands_logic.cpp
ArduCopter/compassmot.cpp
ArduCopter/compat.cpp
ArduCopter/control_acro.cpp
ArduCopter/control_althold.cpp
ArduCopter/control_apogee.cpp
ArduCopter/control_auto.cpp
ArduCopter/control_autotune.cpp
ArduCopter/control_avoid_adsb.cpp
ArduCopter/control_brake.cpp
ArduCopter/control_circle.cpp
ArduCopter/control_drift.cpp
ArduCopter/control_flip.cpp
ArduCopter/control_guided.cpp
ArduCopter/control_guided_nogps.cpp
ArduCopter/control_land.cpp
ArduCopter/control_loiter.cpp
ArduCopter/control_poshold.cpp
ArduCopter/control_rtl.cpp
ArduCopter/control_sport.cpp
ArduCopter/control_stabilize.cpp
ArduCopter/control_throw.cpp
ArduCopter/Copter.cpp
ArduCopter/crash_check.cpp
ArduCopter/ekf_check.cpp
ArduCopter/esc_calibration.cpp
ArduCopter/events.cpp
ArduCopter/failsafe.cpp
ArduCopter/fence.cpp
ArduCopter/flight_mode.cpp
ArduCopter/GCS_Mavlink.cpp
ArduCopter/inertia.cpp
ArduCopter/land_detector.cpp
ArduCopter/landing_gear.cpp
ArduCopter/leds.cpp
ArduCopter/motor_test.cpp
ArduCopter/motors.cpp
ArduCopter/navigation.cpp
ArduCopter/Parameters.cpp
ArduCopter/perf_info.cpp
ArduCopter/position_vector.cpp
ArduCopter/precision_landing.cpp
ArduCopter/radio.cpp
ArduCopter/sensors.cpp
ArduCopter/setup.cpp
ArduCopter/switches.cpp
ArduCopter/system.cpp
ArduCopter/takeoff.cpp
ArduCopter/terrain.cpp
ArduCopter/test.cpp
ArduCopter/tuning.cpp