APM:Copter: AP_Avoidance_Copter Class Reference
AP_Avoidance_Copter Class Reference
#include <avoidance_adsb.h>
Public Member Functions
AP_Avoidance_Copter (AP_AHRS &ahrs, class AP_ADSB &adsb)
Public Member Functions inherited from AP_Avoidance
AP_Avoidance (AP_AHRS &ahrs, class AP_ADSB &adsb)
void add_obstacle (uint32_t obstacle_timestamp_ms, const MAV_COLLISION_SRC src, uint32_t src_id, const Location &loc, const Vector3f &vel_ned)
void add_obstacle (uint32_t obstacle_timestamp_ms, const MAV_COLLISION_SRC src, uint32_t src_id, const Location &loc, float cog, float hspeed, float vspeed)
void update ()
void enable ()
void disable ()
MAV_COLLISION_THREAT_LEVEL current_threat_level () const
void handle_msg (const mavlink_message_t &msg)
Protected Member Functions
MAV_COLLISION_ACTION handle_avoidance (const AP_Avoidance::Obstacle *obstacle, MAV_COLLISION_ACTION requested_action) override
void handle_recovery (uint8_t recovery_action) override
bool check_flightmode (bool allow_mode_change)
bool handle_avoidance_vertical (const AP_Avoidance::Obstacle *obstacle, bool allow_mode_change)
bool handle_avoidance_horizontal (const AP_Avoidance::Obstacle *obstacle, bool allow_mode_change)
bool handle_avoidance_perpendicular (const AP_Avoidance::Obstacle *obstacle, bool allow_mode_change)
Protected Member Functions inherited from AP_Avoidance
void handle_avoidance_local (AP_Avoidance::Obstacle *threat)
void handle_threat_gcs_notify (AP_Avoidance::Obstacle *threat)
AP_Avoidance::Obstacle * most_serious_threat ()
MAV_COLLISION_ACTION mav_avoidance_action ()
bool get_destination_perpendicular (const AP_Avoidance::Obstacle *obstacle, Vector3f &newdest_neu, const float wp_speed_xy, const float wp_speed_z, const uint8_t _minimum_avoid_height)
bool get_vector_perpendicular (const AP_Avoidance::Obstacle *obstacle, Vector3f &vec_neu)
Protected Attributes
control_mode_t prev_control_mode = RTL
Protected Attributes inherited from AP_Avoidance
uint32_t _last_state_change_ms
MAV_COLLISION_THREAT_LEVEL _threat_level
uint32_t _gcs_cleared_messages_first_sent
const AP_AHRS & _ahrs
Private Member Functions
void set_mode_else_try_RTL_else_LAND (control_mode_t mode)
Additional Inherited Members
Static Public Attributes inherited from AP_Avoidance
static const struct AP_Param::GroupInfo var_info []
Static Protected Member Functions inherited from AP_Avoidance
static Vector3f perpendicular_xyz (const Location &p1, const Vector3f &v1, const Location &p2)
static Vector2f perpendicular_xy (const Location &p1, const Vector3f &v1, const Location &p2)
Static Protected Attributes inherited from AP_Avoidance
static const uint8_t _gcs_cleared_messages_duration
Detailed Description
Definition at line 9 of file avoidance_adsb.h.
Constructor & Destructor Documentation
AP_Avoidance_Copter::AP_Avoidance_Copter (AP_AHRS & ahrs, class AP_ADSB & adsb) inline
Definition at line 13 of file avoidance_adsb.h.
Member Function Documentation
bool AP_Avoidance_Copter::check_flightmode (bool allow_mode_change) protected
Definition at line 144 of file avoidance_adsb.cpp.
Referenced by AP_Avoidance_Copter().
MAV_COLLISION_ACTION AP_Avoidance_Copter::handle_avoidance (const AP_Avoidance::Obstacle * obstacle, MAV_COLLISION_ACTION requested_action) override protected virtual
Implements AP_Avoidance.
Definition at line 12 of file avoidance_adsb.cpp.
Referenced by AP_Avoidance_Copter().
bool AP_Avoidance_Copter::handle_avoidance_horizontal (const AP_Avoidance::Obstacle * obstacle, bool allow_mode_change) protected
Definition at line 189 of file avoidance_adsb.cpp.
Referenced by AP_Avoidance_Copter().
bool AP_Avoidance_Copter::handle_avoidance_perpendicular (const AP_Avoidance::Obstacle * obstacle, bool allow_mode_change) protected
Definition at line 219 of file avoidance_adsb.cpp.
Referenced by AP_Avoidance_Copter().
bool AP_Avoidance_Copter::handle_avoidance_vertical (const AP_Avoidance::Obstacle * obstacle, bool allow_mode_change) protected
Definition at line 158 of file avoidance_adsb.cpp.
Referenced by AP_Avoidance_Copter().
void AP_Avoidance_Copter::handle_recovery (uint8_t recovery_action) override protected virtual
Implements AP_Avoidance.
Definition at line 97 of file avoidance_adsb.cpp.
Referenced by AP_Avoidance_Copter().
void AP_Avoidance_Copter::set_mode_else_try_RTL_else_LAND (control_mode_t mode) private
Definition at line 133 of file avoidance_adsb.cpp.
Referenced by AP_Avoidance_Copter().
Member Data Documentation
control_mode_t AP_Avoidance_Copter::prev_control_mode = RTL protected
Definition at line 42 of file avoidance_adsb.h.
The documentation for this class was generated from the following files:
ArduCopter/avoidance_adsb.h
ArduCopter/avoidance_adsb.cpp