APM:Copter: ArduCopter/Copter.cpp File Reference
Copter.cpp File Reference
#include "Copter.h"
#include "version.h"
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
Copter copter
Variable Documentation
Copter copter
Definition at line 115 of file Copter.cpp.
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
Definition at line 18 of file Copter.cpp.
Referenced by Copter::accel_cal_update(), Copter::apogee_run(), AP_Arming_Copter::arm_checks(), AP_Arming_Copter::board_voltage_checks(), Copter::check_usb_mux(), Copter::compass_cal_update(), Copter::delay(), Copter::do_nav_delay(), Copter::esc_calib(), Copter::esc_calibration_auto(), Copter::failsafe_gcs_check(), Copter::gcs_send_text_fmt(), GCS_MAVLINK_Copter::handleMessage(), Copter::init_ardupilot(), Copter::init_arm_motors(), Copter::init_capabilities(), Copter::init_disarm_motors(), Copter::init_rc_out(), Copter::load_parameters(), Copter::Log_Read(), Copter::Log_Write_Performance(), Copter::mavlink_compassmot(), Copter::mavlink_motor_test_check(), Copter::read_radio(), Copter::reboot_board(), Copter::run_cli(), Copter::send_hwstatus(), Copter::set_system_time_from_GPS(), Copter::setup(), Copter::test_shell(), and Copter::update_sensor_status_flags().