APM:Libraries: libraries/AP_OpticalFlow/examples/AP_OpticalFlow_test/AP_OpticalFlow_test.cpp File Reference
AP_OpticalFlow_test.cpp File Reference
#include <AP_AHRS/AP_AHRS.h>
#include <AP_Baro/AP_Baro.h>
#include <AP_Compass/AP_Compass.h>
#include <AP_GPS/AP_GPS.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_InertialSensor/AP_InertialSensor.h>
#include <AP_NavEKF2/AP_NavEKF2.h>
#include <AP_NavEKF3/AP_NavEKF3.h>
#include <AP_OpticalFlow/AP_OpticalFlow.h>
#include <AP_RangeFinder/AP_RangeFinder.h>
Classes
class DummyVehicle
Functions
static OpticalFlow optflow (vehicle.ahrs)
void setup ()
void loop ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static DummyVehicle vehicle
Function Documentation
AP_HAL_MAIN ()
Referenced by loop().
void loop (void)
Definition at line 52 of file AP_OpticalFlow_test.cpp.
static OpticalFlow optflow (vehicle. ahrs) static
Referenced by GCS_MAVLINK::handle_set_mode(), AP_AHRS::set_optflow(), and setup().
void setup (void)
Definition at line 36 of file AP_OpticalFlow_test.cpp.
Variable Documentation
const AP_HAL::HAL& hal = AP_HAL::get_HAL()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 17 of file AP_OpticalFlow_test.cpp.
DummyVehicle vehicle static
Definition at line 33 of file AP_OpticalFlow_test.cpp.