APM:Libraries: PX4::PX4_I2C Class Reference
PX4::PX4_I2C Class Reference
#include <I2CWrapper.h>
Public Member Functions
PX4_I2C (uint8_t bus)
bool do_transfer (uint8_t address, const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len)
void set_retries (uint8_t retries)
uint8_t map_bus_number (uint8_t bus) const
Private Attributes
bool init_done
bool init_ok
char devname [10]
char devpath [14]
Static Private Attributes
static uint8_t instance
Detailed Description
Definition at line 14 of file I2CWrapper.h.
Constructor & Destructor Documentation
PX4::PX4_I2C::PX4_I2C (uint8_t bus)
Definition at line 31 of file I2CDevice.cpp.
Member Function Documentation
bool PX4::PX4_I2C::do_transfer (uint8_t address, const uint8_t * send, uint32_t send_len, uint8_t * recv, uint32_t recv_len)
Definition at line 65 of file I2CDevice.cpp.
Referenced by PX4::I2CDevice::transfer().
uint8_t PX4::PX4_I2C::map_bus_number (uint8_t bus) const
Definition at line 38 of file I2CDevice.cpp.
Referenced by set_retries().
void PX4::PX4_I2C::set_retries (uint8_t retries) inline
Definition at line 19 of file I2CWrapper.h.
Referenced by PX4::I2CDevice::set_retries().
Member Data Documentation
char PX4::PX4_I2C::devname[10] private
Definition at line 29 of file I2CWrapper.h.
Referenced by do_transfer().
char PX4::PX4_I2C::devpath[14] private
Definition at line 30 of file I2CWrapper.h.
Referenced by do_transfer().
bool PX4::PX4_I2C::init_done private
Definition at line 27 of file I2CWrapper.h.
Referenced by do_transfer().
bool PX4::PX4_I2C::init_ok private
Definition at line 28 of file I2CWrapper.h.
Referenced by do_transfer().
uint8_t PX4::PX4_I2C::instance static private
Definition at line 26 of file I2CWrapper.h.
Referenced by do_transfer().
The documentation for this class was generated from the following files:
libraries/AP_HAL_PX4/I2CWrapper.h
libraries/AP_HAL_PX4/I2CDevice.cpp