APM:Libraries: GCS_MAVLINK Class Reference
GCS_MAVLINK Class Reference abstract
MAVLink transport control class.
#include <GCS.h>
Public Types
enum streams {
STREAM_RAW_SENSORS, STREAM_EXTENDED_STATUS, STREAM_RC_CHANNELS, STREAM_RAW_CONTROLLER,
STREAM_POSITION, STREAM_EXTRA1, STREAM_EXTRA2, STREAM_EXTRA3,
STREAM_PARAMS, STREAM_ADSB, NUM_STREAMS
}
Public Member Functions
GCS_MAVLINK ()
FUNCTOR_TYPEDEF (run_cli_fn, void, AP_HAL::UARTDriver *)
void update (run_cli_fn run_cli)
void init (AP_HAL::UARTDriver *port, mavlink_channel_t mav_chan)
void setup_uart (const AP_SerialManager &serial_manager, AP_SerialManager::SerialProtocol protocol, uint8_t instance)
void send_message (enum ap_message id)
void send_text (MAV_SEVERITY severity, const char *str)
virtual void data_stream_send (void)=0
void queued_param_send ()
Send the next pending parameter, called from deferred message handling code.
void queued_waypoint_send ()
Send the next pending waypoint, called from deferred message handling code.
void set_snoop (void(*_msg_snoop)(const mavlink_message_t *msg))
virtual void packetReceived (const mavlink_status_t &status, mavlink_message_t &msg)
AP_HAL::UARTDriver * get_uart ()
bool stream_trigger (enum streams stream_num)
void reset_cli_timeout ()
void send_meminfo (void)
void send_power_status (void)
void send_ahrs2 (AP_AHRS &ahrs)
bool send_gps_raw (AP_GPS &gps)
void send_system_time (AP_GPS &gps)
void send_radio_in (uint8_t receiver_rssi)
void send_raw_imu (const AP_InertialSensor &ins, const Compass &compass)
void send_scaled_pressure (AP_Baro &barometer)
void send_sensor_offsets (const AP_InertialSensor &ins, const Compass &compass, AP_Baro &barometer)
void send_ahrs (AP_AHRS &ahrs)
void send_battery2 (const AP_BattMonitor &battery)
void send_autopilot_version (uint8_t major_version, uint8_t minor_version, uint8_t patch_version, uint8_t version_type) const
void send_local_position (const AP_AHRS &ahrs) const
void send_vibration (const AP_InertialSensor &ins) const
void send_home (const Location &home) const
void send_heartbeat (uint8_t type, uint8_t base_mode, uint32_t custom_mode, uint8_t system_status)
void send_servo_output_raw (bool hil)
void send_accelcal_vehicle_position (uint8_t position)
bool telemetry_delayed (mavlink_channel_t chan)
virtual uint32_t telem_delay () const =0
Static Public Member Functions
static void send_home_all (const Location &home)
static void send_collision_all (const AP_Avoidance::Obstacle &threat, MAV_COLLISION_ACTION behaviour)
static uint8_t active_channel_mask (void)
static uint8_t streaming_channel_mask (void)
static void send_statustext_all (MAV_SEVERITY severity, const char *fmt,...)
static void send_statustext_chan (MAV_SEVERITY severity, uint8_t dest_chan, const char *fmt,...)
static void send_parameter_value_all (const char *param_name, ap_var_type param_type, float param_value)
static void send_to_components (const mavlink_message_t *msg)
static void disable_channel_routing (mavlink_channel_t chan)
static bool find_by_mavtype (uint8_t mav_type, uint8_t &sysid, uint8_t &compid, mavlink_channel_t &channel)
static void update_signing_timestamp (uint64_t timestamp_usec)
static uint8_t packet_overhead_chan (mavlink_channel_t chan)
Public Attributes
bool initialised
uint32_t last_heartbeat_time
uint16_t mission_item_reached_index = AP_MISSION_CMD_INDEX_NONE
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
static uint32_t last_radio_status_remrssi_ms
Protected Member Functions
virtual bool accept_packet (const mavlink_status_t &status, mavlink_message_t &msg)
uint8_t packet_overhead (void) const
void handle_log_send (DataFlash_Class &dataflash)
void handle_request_data_stream (mavlink_message_t *msg, bool save)
FUNCTOR_TYPEDEF (set_mode_fn, bool, uint8_t)
void handle_set_mode (mavlink_message_t *msg, set_mode_fn set_mode)
void handle_mission_request_list (AP_Mission &mission, mavlink_message_t *msg)
void handle_mission_request (AP_Mission &mission, mavlink_message_t *msg)
void handle_mission_clear_all (AP_Mission &mission, mavlink_message_t *msg)
void handle_mission_set_current (AP_Mission &mission, mavlink_message_t *msg)
void handle_mission_count (AP_Mission &mission, mavlink_message_t *msg)
void handle_mission_write_partial_list (AP_Mission &mission, mavlink_message_t *msg)
bool handle_mission_item (mavlink_message_t *msg, AP_Mission &mission)
void handle_param_set (mavlink_message_t *msg, DataFlash_Class *DataFlash)
void handle_param_request_list (mavlink_message_t *msg)
void handle_param_request_read (mavlink_message_t *msg)
void handle_gimbal_report (AP_Mount &mount, mavlink_message_t *msg) const
void handle_radio_status (mavlink_message_t *msg, DataFlash_Class &dataflash, bool log_radio)
void handle_serial_control (mavlink_message_t *msg, AP_GPS &gps)
void handle_gps_inject (const mavlink_message_t *msg, AP_GPS &gps)
void handle_common_message (mavlink_message_t *msg)
void handle_log_message (mavlink_message_t *msg, DataFlash_Class &dataflash)
void handle_setup_signing (const mavlink_message_t *msg)
uint8_t handle_preflight_reboot (const mavlink_command_long_t &packet, bool disable_overrides)
uint8_t handle_rc_bind (const mavlink_command_long_t &packet)
void handle_device_op_read (mavlink_message_t *msg)
void handle_device_op_write (mavlink_message_t *msg)
void handle_timesync (mavlink_message_t *msg)
Protected Attributes
bool waypoint_receiving
uint16_t waypoint_request_i
uint16_t waypoint_request_last
AP_Param * _queued_parameter
next parameter to
mavlink_channel_t chan
AP_Int16 streamRates [NUM_STREAMS]
Private Member Functions
float adjust_rate_for_stream_trigger (enum streams stream_num)
virtual void handleMessage (mavlink_message_t *msg)=0
virtual bool try_send_message (enum ap_message id)=0
virtual bool handle_guided_request (AP_Mission::Mission_Command &cmd)=0
virtual void handle_change_alt_request (AP_Mission::Mission_Command &cmd)=0
void handle_log_request_list (mavlink_message_t *msg, DataFlash_Class &dataflash)
void handle_log_request_data (mavlink_message_t *msg, DataFlash_Class &dataflash)
void handle_log_request_erase (mavlink_message_t *msg, DataFlash_Class &dataflash)
void handle_log_request_end (mavlink_message_t *msg, DataFlash_Class &dataflash)
void handle_log_send_listing (DataFlash_Class &dataflash)
bool handle_log_send_data (DataFlash_Class &dataflash)
void lock_channel (mavlink_channel_t chan, bool lock)
bool have_flow_control (void)
void load_signing_key (void)
bool signing_enabled (void) const
Static Private Member Functions
static bool signing_key_save (const struct SigningKey &key)
static bool signing_key_load (struct SigningKey &key)
static void save_signing_timestamp (bool force_save_now)
Private Attributes
AP_HAL::UARTDriver * _port
The stream we are communicating over.
enum ap_var_type _queued_parameter_type
type of the next
AP_Param::ParamToken _queued_parameter_token
uint16_t _queued_parameter_index
AP_Param token for.
uint16_t _queued_parameter_count
saved count of
uint32_t _queued_parameter_send_time_ms
uint16_t packet_drops
so that we can report to a GCS the number of parameters it should
uint8_t crlf_count
uint16_t waypoint_dest_sysid
uint16_t waypoint_dest_compid
uint16_t waypoint_count
uint32_t waypoint_timelast_receive
uint32_t waypoint_timelast_request
const uint16_t waypoint_receive_timeout = 8000
uint8_t stream_ticks [NUM_STREAMS]
uint8_t stream_slowdown
uint32_t _cli_timeout
uint8_t _log_listing:1
uint8_t _log_sending:1
uint16_t _log_next_list_entry
uint16_t _log_last_list_entry
uint16_t _log_num_logs
uint16_t _log_num_data
uint32_t _log_data_offset
uint32_t _log_data_size
uint32_t _log_data_remaining
uint16_t _log_data_page
enum ap_message deferred_messages [MSG_RETRY_DEFERRED]
uint8_t next_deferred_message
uint8_t num_deferred_messages
mavlink_signing_t signing
Static Private Attributes
static uint32_t reserve_param_space_start_ms
static uint8_t mavlink_active = 0
static uint8_t chan_is_streaming = 0
static MAVLink_routing routing
static AP_Frsky_Telem * frsky_telemetry_p
static const AP_SerialManager * serialmanager_p
static void(* msg_snoop)(const mavlink_message_t *msg) = nullptr
static mavlink_signing_streams_t signing_streams
static uint32_t last_signing_save_ms
static StorageAccess _signing_storage
Detailed Description
MAVLink transport control class.
Definition at line 80 of file GCS.h.
Member Enumeration Documentation
enum GCS_MAVLINK::streams
Enumerator
STREAM_RAW_SENSORS
STREAM_EXTENDED_STATUS
STREAM_RC_CHANNELS
STREAM_RAW_CONTROLLER
STREAM_POSITION
STREAM_EXTRA1
STREAM_EXTRA2
STREAM_EXTRA3
STREAM_PARAMS
STREAM_ADSB
NUM_STREAMS
Definition at line 111 of file GCS.h.
Constructor & Destructor Documentation
GCS_MAVLINK::GCS_MAVLINK ()
Definition at line 41 of file GCS_Common.cpp.
Member Function Documentation
virtual bool GCS_MAVLINK::accept_packet (const mavlink_status_t & status, mavlink_message_t & msg) inline protected virtual
Definition at line 210 of file GCS.h.
Referenced by packetReceived().
static uint8_t GCS_MAVLINK::active_channel_mask (void) inline static
Definition at line 164 of file GCS.h.
Referenced by MAVLink_routing::handle_heartbeat(), AP_Button::send_report(), and GCS::send_statustext().
float GCS_MAVLINK::adjust_rate_for_stream_trigger (enum streams stream_num) private
Definition at line 1684 of file GCS_Common.cpp.
Referenced by stream_trigger().
virtual void GCS_MAVLINK::data_stream_send (void) pure virtual
Implemented in GCS_MAVLINK_routing.
static void GCS_MAVLINK::disable_channel_routing (mavlink_channel_t chan) inline static
Definition at line 188 of file GCS.h.
static bool GCS_MAVLINK::find_by_mavtype (uint8_t mav_type, uint8_t & sysid, uint8_t & compid, mavlink_channel_t & channel) inline static
Definition at line 194 of file GCS.h.
Referenced by AP_Mount_SToRM32::find_gimbal().
GCS_MAVLINK::FUNCTOR_TYPEDEF (run_cli_fn , void , AP_HAL::UARTDriver *)
GCS_MAVLINK::FUNCTOR_TYPEDEF (set_mode_fn , bool , uint8_t) protected
AP_HAL::UARTDriver* GCS_MAVLINK::get_uart () inline
Definition at line 101 of file GCS.h.
Referenced by AP_AccelCal::_printf(), and AP_InertialSensor_UserInteract_MAVLink::printf().
virtual void GCS_MAVLINK::handle_change_alt_request (AP_Mission::Mission_Command & cmd) private pure virtual
Implemented in GCS_MAVLINK_routing.
Referenced by handle_mission_item().
void GCS_MAVLINK::handle_common_message (mavlink_message_t * msg) protected
Definition at line 1864 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_device_op_read (mavlink_message_t * msg) protected
Definition at line 29 of file GCS_DeviceOp.cpp.
Referenced by handle_common_message().
void GCS_MAVLINK::handle_device_op_write (mavlink_message_t * msg) protected
Definition at line 81 of file GCS_DeviceOp.cpp.
Referenced by handle_common_message().
void GCS_MAVLINK::handle_gimbal_report (AP_Mount & mount, mavlink_message_t * msg) const protected
Definition at line 482 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_gps_inject (const mavlink_message_t * msg, AP_GPS & gps) protected
Definition at line 906 of file GCS_Common.cpp.
virtual bool GCS_MAVLINK::handle_guided_request (AP_Mission::Mission_Command & cmd) private pure virtual
Implemented in GCS_MAVLINK_routing.
Referenced by handle_mission_item().
void GCS_MAVLINK::handle_log_message (mavlink_message_t * msg, DataFlash_Class & dataflash) protected
handle all types of log download requests from the GCS
Definition at line 30 of file GCS_Logs.cpp.
void GCS_MAVLINK::handle_log_request_data (mavlink_message_t * msg, DataFlash_Class & dataflash) private
handle request for log data
Definition at line 84 of file GCS_Logs.cpp.
Referenced by handle_log_message().
void GCS_MAVLINK::handle_log_request_end (mavlink_message_t * msg, DataFlash_Class & dataflash) private
handle request to stop transfer and resume normal logging
Definition at line 135 of file GCS_Logs.cpp.
Referenced by handle_log_message().
void GCS_MAVLINK::handle_log_request_erase (mavlink_message_t * msg, DataFlash_Class & dataflash) private
handle request to erase log data
Definition at line 124 of file GCS_Logs.cpp.
Referenced by handle_log_message().
void GCS_MAVLINK::handle_log_request_list (mavlink_message_t * msg, DataFlash_Class & dataflash) private
handle all types of log download requests from the GCS
Definition at line 52 of file GCS_Logs.cpp.
Referenced by handle_log_message().
void GCS_MAVLINK::handle_log_send (DataFlash_Class & dataflash) protected
trigger sending of log messages if there are some pending
Definition at line 145 of file GCS_Logs.cpp.
Referenced by handle_log_request_data(), and packet_overhead().
bool GCS_MAVLINK::handle_log_send_data (DataFlash_Class & dataflash) private
trigger sending of log data if there are some pending
Definition at line 210 of file GCS_Logs.cpp.
Referenced by handle_log_send().
void GCS_MAVLINK::handle_log_send_listing (DataFlash_Class & dataflash) private
trigger sending of log messages if there are some pending
Definition at line 181 of file GCS_Logs.cpp.
Referenced by handle_log_request_list(), and handle_log_send().
void GCS_MAVLINK::handle_mission_clear_all (AP_Mission & mission, mavlink_message_t * msg) protected
Definition at line 438 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_mission_count (AP_Mission & mission, mavlink_message_t * msg) protected
Definition at line 411 of file GCS_Common.cpp.
bool GCS_MAVLINK::handle_mission_item (mavlink_message_t * msg, AP_Mission & mission) protected
Definition at line 769 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_mission_request (AP_Mission & mission, mavlink_message_t * msg) protected
Definition at line 289 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_mission_request_list (AP_Mission & mission, mavlink_message_t * msg) protected
Definition at line 271 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_mission_set_current (AP_Mission & mission, mavlink_message_t * msg) protected
Definition at line 396 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_mission_write_partial_list (AP_Mission & mission, mavlink_message_t * msg) protected
Definition at line 457 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_param_request_list (mavlink_message_t * msg) protected
Definition at line 577 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_param_request_read (mavlink_message_t * msg) protected
Definition at line 594 of file GCS_Common.cpp.
Referenced by handle_common_message().
void GCS_MAVLINK::handle_param_set (mavlink_message_t * msg, DataFlash_Class * DataFlash) protected
Definition at line 642 of file GCS_Common.cpp.
uint8_t GCS_MAVLINK::handle_preflight_reboot (const mavlink_command_long_t & packet, bool disable_overrides) protected
Definition at line 1783 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_radio_status (mavlink_message_t * msg, DataFlash_Class & dataflash, bool log_radio) protected
Definition at line 731 of file GCS_Common.cpp.
uint8_t GCS_MAVLINK::handle_rc_bind (const mavlink_command_long_t & packet) protected
Definition at line 1821 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_request_data_stream (mavlink_message_t * msg, bool save) protected
Definition at line 516 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_serial_control (mavlink_message_t * msg, AP_GPS & gps) protected
handle a SERIAL_CONTROL message
Definition at line 30 of file GCS_serial_control.cpp.
void GCS_MAVLINK::handle_set_mode (mavlink_message_t * msg, set_mode_fn set_mode) protected
Definition at line 1472 of file GCS_Common.cpp.
void GCS_MAVLINK::handle_setup_signing (const mavlink_message_t * msg) protected
Definition at line 66 of file GCS_Signing.cpp.
Referenced by handle_common_message().
void GCS_MAVLINK::handle_timesync (mavlink_message_t * msg) protected
Definition at line 1836 of file GCS_Common.cpp.
Referenced by handle_common_message().
virtual void GCS_MAVLINK::handleMessage (mavlink_message_t * msg) private pure virtual
Implemented in GCS_MAVLINK_routing.
Referenced by packetReceived().
bool GCS_MAVLINK::have_flow_control (void) private
Definition at line 491 of file GCS_Common.cpp.
Referenced by handle_log_send(), and queued_param_send().
void GCS_MAVLINK::init (AP_HAL::UARTDriver * port, mavlink_channel_t mav_chan)
Definition at line 47 of file GCS_Common.cpp.
Referenced by setup(), and setup_uart().
void GCS_MAVLINK::load_signing_key (void) private
Definition at line 116 of file GCS_Signing.cpp.
Referenced by setup_uart().
void GCS_MAVLINK::lock_channel (mavlink_channel_t chan, bool lock) private
Definition at line 59 of file GCS_MAVLink.cpp.
Referenced by handle_serial_control().
uint8_t GCS_MAVLINK::packet_overhead (void) const inline protected
Definition at line 220 of file GCS.h.
Referenced by queued_param_send().
uint8_t GCS_MAVLINK::packet_overhead_chan (mavlink_channel_t chan) static
Definition at line 238 of file GCS_Signing.cpp.
Referenced by MAVLink_routing::check_and_forward(), find_by_mavtype(), MAVLink_routing::handle_heartbeat(), packet_overhead(), and MAVLink_routing::send_to_components().
void GCS_MAVLINK::packetReceived (const mavlink_status_t & status, mavlink_message_t & msg) virtual
Definition at line 969 of file GCS_Common.cpp.
Referenced by set_snoop(), and update().
void GCS_MAVLINK::queued_param_send ()
Send the next pending parameter, called from deferred message handling code.
Definition at line 147 of file GCS_Common.cpp.
void GCS_MAVLINK::queued_waypoint_send ()
Send the next pending waypoint, called from deferred message handling code.
Definition at line 203 of file GCS_Common.cpp.
Referenced by handle_mission_item().
void GCS_MAVLINK::reset_cli_timeout ()
Definition at line 216 of file GCS_Common.cpp.
Referenced by init().
void GCS_MAVLINK::save_signing_timestamp (bool force_save_now) static private
Definition at line 193 of file GCS_Signing.cpp.
Referenced by send_message().
void GCS_MAVLINK::send_accelcal_vehicle_position (uint8_t position)
Definition at line 1761 of file GCS_Common.cpp.
Referenced by AP_AccelCal::update().
void GCS_MAVLINK::send_ahrs (AP_AHRS & ahrs)
Definition at line 1305 of file GCS_Common.cpp.
void GCS_MAVLINK::send_ahrs2 (AP_AHRS & ahrs)
Definition at line 237 of file GCS_Common.cpp.
void GCS_MAVLINK::send_autopilot_version (uint8_t major_version, uint8_t minor_version, uint8_t patch_version, uint8_t version_type) const
Definition at line 1541 of file GCS_Common.cpp.
void GCS_MAVLINK::send_battery2 (const AP_BattMonitor & battery)
Definition at line 1456 of file GCS_Common.cpp.
void GCS_MAVLINK::send_collision_all (const AP_Avoidance::Obstacle & threat, MAV_COLLISION_ACTION behaviour) static
Definition at line 1740 of file GCS_Common.cpp.
Referenced by AP_Avoidance::handle_threat_gcs_notify().
bool GCS_MAVLINK::send_gps_raw (AP_GPS & gps)
Definition at line 1058 of file GCS_Common.cpp.
void GCS_MAVLINK::send_heartbeat (uint8_t type, uint8_t base_mode, uint32_t custom_mode, uint8_t system_status)
Definition at line 1673 of file GCS_Common.cpp.
void GCS_MAVLINK::send_home (const Location & home) const
Definition at line 1635 of file GCS_Common.cpp.
void GCS_MAVLINK::send_home_all (const Location & home) static
Definition at line 1650 of file GCS_Common.cpp.
void GCS_MAVLINK::send_local_position (const AP_AHRS & ahrs) const
Definition at line 1597 of file GCS_Common.cpp.
void GCS_MAVLINK::send_meminfo (void)
Definition at line 220 of file GCS_Common.cpp.
void GCS_MAVLINK::send_message (enum ap_message id)
Definition at line 917 of file GCS_Common.cpp.
Referenced by handle_mission_item(), and update().
void GCS_MAVLINK::send_parameter_value_all (const char * param_name, ap_var_type param_type, float param_value) static
Definition at line 1432 of file GCS_Common.cpp.
Referenced by AP_Param::save(), AP_Param::send_parameter(), and streaming_channel_mask().
void GCS_MAVLINK::send_power_status (void)
Definition at line 228 of file GCS_Common.cpp.
void GCS_MAVLINK::send_radio_in (uint8_t receiver_rssi)
Definition at line 1107 of file GCS_Common.cpp.
void GCS_MAVLINK::send_raw_imu (const AP_InertialSensor & ins, const Compass & compass)
Definition at line 1161 of file GCS_Common.cpp.
void GCS_MAVLINK::send_scaled_pressure (AP_Baro & barometer)
Definition at line 1242 of file GCS_Common.cpp.
void GCS_MAVLINK::send_sensor_offsets (const AP_InertialSensor & ins, const Compass & compass, AP_Baro & barometer)
Definition at line 1276 of file GCS_Common.cpp.
void GCS_MAVLINK::send_servo_output_raw (bool hil)
Definition at line 1716 of file GCS_Common.cpp.
void GCS_MAVLINK::send_statustext_all (MAV_SEVERITY severity, const char * fmt, ...) static
Definition at line 1322 of file GCS_Common.cpp.
Referenced by AP_GPS::_broadcast_gps_type(), AP_GPS_UBLOX::_parse_gps(), AP_GPS_UBLOX::_save_cfg(), AP_Arming::airspeed_checks(), AP_Arming::arm(), AP_Arming::arm_checks(), AP_Arming::barometer_checks(), AP_Arming::battery_checks(), AP_Arming::board_voltage_checks(), AP_GPS_UBLOX::broadcast_configuration_failure_reason(), AP_GPS::broadcast_first_configuration_failure_reason(), AP_Landing_Deepstall::build_approach_path(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), AP_AdvancedFailsafe::check(), AP_Tuning::check_controller_error(), SoaringController::check_cruise_criteria(), AP_Tuning::check_input(), AP_Tuning::check_selector_switch(), NavEKF2_core::checkAttitudeAlignmentStatus(), NavEKF3_core::checkAttitudeAlignmentStatus(), AP_Arming::compass_checks(), NavEKF2_core::controlMagYawReset(), NavEKF3_core::controlMagYawReset(), AP_Arming::disarm(), AP_ICEngine::engine_control(), AP_Arming::gps_checks(), AP_ADSB::handle_transceiver_report(), AP_Arming::hardware_safety_check(), AP_MotorsTri::init(), AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_Airspeed::init(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), NavEKF3_core::InitialiseFilterBootstrap(), AP_Arming::ins_checks(), AP_Mission::jump_to_landing_sequence(), AP_Arming::logging_checks(), AP_Arming::manual_transmitter_checks(), AP_Tuning::next_parameter(), AP_Landing_Deepstall::override_servos(), AP_MotorsHeli::parameter_check(), AP_MotorsHeli_Single::parameter_check(), AP_Landing_Deepstall::predict_travel_distance(), AP_BoardConfig::px4_sensor_error(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), NavEKF2_core::realignYawGPS(), NavEKF3_core::realignYawGPS(), AP_Landing::restart_landing_sequence(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setOrigin(), NavEKF3_core::setOrigin(), NavEKF3_core::setup_core(), AP_Camera::setup_feedback_callback(), streaming_channel_mask(), AP_Landing::type_slope_adjust_landing_slope_for_rangefinder_bump(), AP_Landing::type_slope_do_land(), AP_Landing::type_slope_setup_landing_glide_slope(), AP_Landing::type_slope_verify_land(), AP_ICEngine::update(), AP_ADSB::update(), AP_Airspeed::update_calibration(), AP_Landing_Deepstall::update_steering(), SoaringController::update_thermalling(), and AP_Landing::verify_land().
void GCS_MAVLINK::send_statustext_chan (MAV_SEVERITY severity, uint8_t dest_chan, const char * fmt, ...) static
Definition at line 1336 of file GCS_Common.cpp.
Referenced by AC_Fence::handle_msg(), send_text(), and streaming_channel_mask().
void GCS_MAVLINK::send_system_time (AP_GPS & gps)
Definition at line 1095 of file GCS_Common.cpp.
void GCS_MAVLINK::send_text (MAV_SEVERITY severity, const char * str)
Definition at line 726 of file GCS_Common.cpp.
Referenced by AP_AccelCal::_printf(), handle_mission_item(), handle_mission_write_partial_list(), handle_param_request_list(), and AP_InertialSensor_UserInteract_MAVLink::printf().
static void GCS_MAVLINK::send_to_components (const mavlink_message_t * msg) inline static
Definition at line 183 of file GCS.h.
Referenced by AP_Camera::configure(), AP_Camera::control(), and AP_Camera::trigger_pic().
void GCS_MAVLINK::send_vibration (const AP_InertialSensor & ins) const
Definition at line 1620 of file GCS_Common.cpp.
void GCS_MAVLINK::set_snoop (void(*)(const mavlink_message_t *msg) _msg_snoop) inline
Definition at line 93 of file GCS.h.
Referenced by AP_InertialSensor_UserInteract_MAVLink::blocking_read(), AP_AccelCal::collect_sample(), and AP_AccelCal::update().
void GCS_MAVLINK::setup_uart (const AP_SerialManager & serial_manager, AP_SerialManager::SerialProtocol protocol, uint8_t instance)
Definition at line 67 of file GCS_Common.cpp.
bool GCS_MAVLINK::signing_enabled (void) const private
Definition at line 226 of file GCS_Signing.cpp.
bool GCS_MAVLINK::signing_key_load (struct SigningKey & key) static private
Definition at line 49 of file GCS_Signing.cpp.
bool GCS_MAVLINK::signing_key_save (const struct SigningKey & key) static private
Definition at line 41 of file GCS_Signing.cpp.
bool GCS_MAVLINK::stream_trigger (enum streams stream_num)
Definition at line 682 of file GCS_Common.cpp.
static uint8_t GCS_MAVLINK::streaming_channel_mask (void) inline static
Definition at line 167 of file GCS.h.
Referenced by GCS::send_statustext().
virtual uint32_t GCS_MAVLINK::telem_delay () const pure virtual
Implemented in GCS_MAVLINK_routing.
Referenced by find_by_mavtype(), and telemetry_delayed().
bool GCS_MAVLINK::telemetry_delayed (mavlink_channel_t chan)
Definition at line 1697 of file GCS_Common.cpp.
Referenced by find_by_mavtype().
virtual bool GCS_MAVLINK::try_send_message (enum ap_message id) private pure virtual
Implemented in GCS_MAVLINK_routing.
Referenced by send_message().
void GCS_MAVLINK::update (run_cli_fn run_cli)
Definition at line 1000 of file GCS_Common.cpp.
void GCS_MAVLINK::update_signing_timestamp (uint64_t timestamp_usec) static
Definition at line 164 of file GCS_Signing.cpp.
Referenced by find_by_mavtype().
Member Data Documentation
uint32_t GCS_MAVLINK::_cli_timeout private
Definition at line 313 of file GCS.h.
Referenced by reset_cli_timeout(), and update().
uint32_t GCS_MAVLINK::_log_data_offset private
Definition at line 331 of file GCS.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
uint16_t GCS_MAVLINK::_log_data_page private
Definition at line 340 of file GCS.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
uint32_t GCS_MAVLINK::_log_data_remaining private
Definition at line 337 of file GCS.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
uint32_t GCS_MAVLINK::_log_data_size private
Definition at line 334 of file GCS.h.
Referenced by handle_log_request_data().
uint16_t GCS_MAVLINK::_log_last_list_entry private
Definition at line 322 of file GCS.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
uint8_t GCS_MAVLINK::_log_listing private
Definition at line 315 of file GCS.h.
Referenced by handle_log_request_data(), handle_log_request_list(), handle_log_send(), and handle_log_send_listing().
uint16_t GCS_MAVLINK::_log_next_list_entry private
Definition at line 319 of file GCS.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
uint16_t GCS_MAVLINK::_log_num_data private
Definition at line 328 of file GCS.h.
Referenced by handle_log_request_data(), and handle_log_send_data().
uint16_t GCS_MAVLINK::_log_num_logs private
Definition at line 325 of file GCS.h.
Referenced by handle_log_request_list(), and handle_log_send_listing().
uint8_t GCS_MAVLINK::_log_sending private
Definition at line 316 of file GCS.h.
Referenced by handle_log_request_data(), handle_log_request_end(), handle_log_request_list(), handle_log_send(), and handle_log_send_data().
AP_HAL::UARTDriver* GCS_MAVLINK::_port private
The stream we are communicating over.
Definition at line 267 of file GCS.h.
Referenced by get_uart(), init(), and update().
AP_Param* GCS_MAVLINK::_queued_parameter protected
next parameter to
Definition at line 217 of file GCS.h.
Referenced by adjust_rate_for_stream_trigger(), handle_param_request_list(), init(), and queued_param_send().
uint16_t GCS_MAVLINK::_queued_parameter_count private
saved count of
Definition at line 277 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
uint16_t GCS_MAVLINK::_queued_parameter_index private
AP_Param token for.
next queued
Definition at line 275 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
uint32_t GCS_MAVLINK::_queued_parameter_send_time_ms private
Definition at line 280 of file GCS.h.
Referenced by queued_param_send().
AP_Param::ParamToken GCS_MAVLINK::_queued_parameter_token private
Definition at line 273 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
enum ap_var_type GCS_MAVLINK::_queued_parameter_type private
type of the next
Perform queued sending operations
Definition at line 271 of file GCS.h.
Referenced by handle_param_request_list(), and queued_param_send().
StorageAccess GCS_MAVLINK::_signing_storage static private
Definition at line 390 of file GCS.h.
mavlink_channel_t GCS_MAVLINK::chan protected
Definition at line 219 of file GCS.h.
Referenced by comm_get_available(), comm_get_txspace(), comm_receive_ch(), comm_send_buffer(), find_by_mavtype(), handle_device_op_read(), handle_device_op_write(), handle_gimbal_report(), handle_log_send(), handle_log_send_data(), handle_log_send_listing(), handle_mission_clear_all(), handle_mission_count(), handle_mission_item(), handle_mission_request(), handle_mission_request_list(), handle_mission_set_current(), handle_param_request_read(), handle_serial_control(), handle_set_mode(), handle_timesync(), have_flow_control(), init(), lock_channel(), packetReceived(), queued_param_send(), queued_waypoint_send(), send_accelcal_vehicle_position(), send_ahrs(), send_ahrs2(), send_autopilot_version(), send_battery2(), send_collision_all(), send_gps_raw(), send_heartbeat(), send_home(), send_home_all(), send_local_position(), send_meminfo(), send_parameter_value_all(), send_power_status(), send_radio_in(), send_raw_imu(), send_scaled_pressure(), send_sensor_offsets(), send_servo_output_raw(), send_system_time(), send_text(), send_vibration(), setup_uart(), stream_trigger(), and update().
uint8_t GCS_MAVLINK::chan_is_streaming = 0 static private
Definition at line 354 of file GCS.h.
Referenced by send_statustext_all(), stream_trigger(), and streaming_channel_mask().
uint8_t GCS_MAVLINK::crlf_count private
Definition at line 295 of file GCS.h.
Referenced by update().
enum ap_message GCS_MAVLINK::deferred_messages[MSG_RETRY_DEFERRED] private
Definition at line 343 of file GCS.h.
Referenced by send_message().
AP_Frsky_Telem* GCS_MAVLINK::frsky_telemetry_p static private
Definition at line 360 of file GCS.h.
Referenced by GCS::register_frsky_telemetry_callback(), and GCS::send_statustext().
bool GCS_MAVLINK::initialised
Definition at line 106 of file GCS.h.
Referenced by init(), queued_param_send(), and queued_waypoint_send().
uint32_t GCS_MAVLINK::last_heartbeat_time
Definition at line 129 of file GCS.h.
Referenced by handle_log_send_data(), and handle_log_send_listing().
uint32_t GCS_MAVLINK::last_radio_status_remrssi_ms static
Definition at line 132 of file GCS.h.
Referenced by handle_radio_status().
uint32_t GCS_MAVLINK::last_signing_save_ms static private
Definition at line 388 of file GCS.h.
uint8_t GCS_MAVLINK::mavlink_active = 0 static private
Definition at line 351 of file GCS.h.
Referenced by active_channel_mask(), packetReceived(), send_collision_all(), send_home_all(), send_parameter_value_all(), send_statustext_all(), and update().
uint16_t GCS_MAVLINK::mission_item_reached_index = AP_MISSION_CMD_INDEX_NONE
Definition at line 135 of file GCS.h.
void(* GCS_MAVLINK::msg_snoop)(const mavlink_message_t *msg) = nullptr static private
Definition at line 365 of file GCS.h.
Referenced by packetReceived(), and set_snoop().
uint8_t GCS_MAVLINK::next_deferred_message private
Definition at line 344 of file GCS.h.
Referenced by send_message().
uint8_t GCS_MAVLINK::num_deferred_messages private
Definition at line 345 of file GCS.h.
Referenced by send_message().
uint16_t GCS_MAVLINK::packet_drops private
so that we can report to a GCS the number of parameters it should
Count the number of reportable parameters.
Not all parameters can be reported via MAVlink. We count the numberrequests the full set.
Returns
The number of reportable parameters.
Definition at line 292 of file GCS.h.
uint32_t GCS_MAVLINK::reserve_param_space_start_ms static private
Definition at line 348 of file GCS.h.
Referenced by handle_param_request_read().
MAVLink_routing GCS_MAVLINK::routing static private
Definition at line 357 of file GCS.h.
Referenced by disable_channel_routing(), find_by_mavtype(), packetReceived(), and send_to_components().
const AP_SerialManager * GCS_MAVLINK::serialmanager_p static private
Definition at line 362 of file GCS.h.
Referenced by packetReceived(), and setup_uart().
mavlink_signing_t GCS_MAVLINK::signing private
Definition at line 386 of file GCS.h.
mavlink_signing_streams_t GCS_MAVLINK::signing_streams static private
Definition at line 387 of file GCS.h.
uint8_t GCS_MAVLINK::stream_slowdown private
Definition at line 309 of file GCS.h.
Referenced by handle_radio_status(), stream_trigger(), and update().
uint8_t GCS_MAVLINK::stream_ticks[NUM_STREAMS] private
Definition at line 306 of file GCS.h.
Referenced by stream_trigger().
AP_Int16 GCS_MAVLINK::streamRates[NUM_STREAMS] protected
Definition at line 225 of file GCS.h.
Referenced by handle_request_data_stream(), and stream_trigger().
const AP_Param::GroupInfo GCS_MAVLINK::var_info static
Initial value:
= {
    AP_GROUPEND
}
Definition at line 103 of file GCS.h.
Referenced by GCS_MAVLINK().
uint16_t GCS_MAVLINK::waypoint_count private
Definition at line 300 of file GCS.h.
uint16_t GCS_MAVLINK::waypoint_dest_compid private
Definition at line 299 of file GCS.h.
Referenced by handle_mission_request_list(), and queued_waypoint_send().
uint16_t GCS_MAVLINK::waypoint_dest_sysid private
Definition at line 298 of file GCS.h.
Referenced by handle_mission_request_list(), and queued_waypoint_send().
const uint16_t GCS_MAVLINK::waypoint_receive_timeout = 8000 private
Definition at line 303 of file GCS.h.
Referenced by update().
bool GCS_MAVLINK::waypoint_receiving protected
Definition at line 212 of file GCS.h.
Referenced by adjust_rate_for_stream_trigger(), handle_mission_count(), handle_mission_item(), handle_mission_request_list(), handle_mission_write_partial_list(), queued_waypoint_send(), and update().
uint16_t GCS_MAVLINK::waypoint_request_i protected
Definition at line 214 of file GCS.h.
Referenced by handle_mission_count(), handle_mission_item(), handle_mission_write_partial_list(), and queued_waypoint_send().
uint16_t GCS_MAVLINK::waypoint_request_last protected
Definition at line 215 of file GCS.h.
Referenced by handle_mission_count(), handle_mission_item(), handle_mission_write_partial_list(), and queued_waypoint_send().
uint32_t GCS_MAVLINK::waypoint_timelast_receive private
Definition at line 301 of file GCS.h.
Referenced by handle_mission_count(), handle_mission_item(), handle_mission_write_partial_list(), and update().
uint32_t GCS_MAVLINK::waypoint_timelast_request private
Definition at line 302 of file GCS.h.
Referenced by handle_mission_count(), handle_mission_item(), handle_mission_write_partial_list(), and update().
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/examples/routing/routing.cpp
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/GCS_DeviceOp.cpp
libraries/GCS_MAVLink/GCS_Logs.cpp
libraries/GCS_MAVLink/GCS_MAVLink.cpp
libraries/GCS_MAVLink/GCS_serial_control.cpp
libraries/GCS_MAVLink/GCS_Signing.cpp