APM:Libraries: HALSITL::RCOutput Class Reference
HALSITL::RCOutput Class Reference
#include <RCOutput.h>
Public Member Functions
RCOutput (SITL_State *sitlState)
void init () override
void set_freq (uint32_t chmask, uint16_t freq_hz) override
uint16_t get_freq (uint8_t ch) override
void enable_ch (uint8_t ch) override
void disable_ch (uint8_t ch) override
void write (uint8_t ch, uint16_t period_us) override
uint16_t read (uint8_t ch) override
void read (uint16_t *period_us, uint8_t len) override
void cork (void)
void push (void)
Public Member Functions inherited from AP_HAL::RCOutput
virtual uint16_t read_last_sent (uint8_t ch)
virtual void read_last_sent (uint16_t *period_us, uint8_t len)
virtual void set_safety_pwm (uint32_t chmask, uint16_t period_us)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
virtual void force_safety_no_wait (void)
virtual void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
virtual float scale_esc_to_unity (uint16_t pwm)
virtual bool enable_sbus_out (uint16_t rate_gz)
virtual void timer_tick (void)
virtual void set_output_mode (enum output_mode mode)
Private Attributes
SITL_State * _sitlState
uint16_t _freq_hz
uint16_t _enable_mask
bool _corked
uint16_t _pending [SITL_NUM_CHANNELS]
Additional Inherited Members
Public Types inherited from AP_HAL::RCOutput
enum output_mode { MODE_PWM_NORMAL, MODE_PWM_ONESHOT, MODE_PWM_BRUSHED16KHZ }
Detailed Description
Definition at line 7 of file RCOutput.h.
Constructor & Destructor Documentation
HALSITL::RCOutput::RCOutput (SITL_State * sitlState) inline explicit
Definition at line 9 of file RCOutput.h.
Member Function Documentation
void RCOutput::cork (void) virtual
Implements AP_HAL::RCOutput.
Definition at line 70 of file RCOutput.cpp.
Referenced by RCOutput().
void RCOutput::disable_ch (uint8_t ch) override virtual
Implements AP_HAL::RCOutput.
Definition at line 38 of file RCOutput.cpp.
Referenced by RCOutput().
void RCOutput::enable_ch (uint8_t ch) override virtual
Implements AP_HAL::RCOutput.
Definition at line 30 of file RCOutput.cpp.
Referenced by RCOutput().
uint16_t RCOutput::get_freq (uint8_t ch) override virtual
Implements AP_HAL::RCOutput.
Definition at line 25 of file RCOutput.cpp.
Referenced by RCOutput().
void RCOutput::init (void) override virtual
Implements AP_HAL::RCOutput.
Definition at line 17 of file RCOutput.cpp.
Referenced by RCOutput().
void RCOutput::push (void) virtual
Implements AP_HAL::RCOutput.
Definition at line 76 of file RCOutput.cpp.
Referenced by RCOutput().
uint16_t RCOutput::read (uint8_t ch) override virtual
Implements AP_HAL::RCOutput.
Definition at line 57 of file RCOutput.cpp.
Referenced by RCOutput().
void RCOutput::read (uint16_t * period_us, uint8_t len) override virtual
Implements AP_HAL::RCOutput.
Definition at line 65 of file RCOutput.cpp.
void RCOutput::set_freq (uint32_t chmask, uint16_t freq_hz) override virtual
Implements AP_HAL::RCOutput.
Definition at line 19 of file RCOutput.cpp.
Referenced by RCOutput().
void RCOutput::write (uint8_t ch, uint16_t period_us) override virtual
Implements AP_HAL::RCOutput.
Definition at line 46 of file RCOutput.cpp.
Referenced by RCOutput().
Member Data Documentation
bool HALSITL::RCOutput::_corked private
Definition at line 25 of file RCOutput.h.
Referenced by cork(), push(), and write().
uint16_t HALSITL::RCOutput::_enable_mask private
Definition at line 24 of file RCOutput.h.
Referenced by disable_ch(), enable_ch(), and write().
uint16_t HALSITL::RCOutput::_freq_hz private
Definition at line 23 of file RCOutput.h.
Referenced by get_freq(), and set_freq().
uint16_t HALSITL::RCOutput::_pending[SITL_NUM_CHANNELS] private
Definition at line 26 of file RCOutput.h.
Referenced by cork(), push(), and write().
SITL_State* HALSITL::RCOutput::_sitlState private
Definition at line 22 of file RCOutput.h.
Referenced by cork(), push(), read(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/RCOutput.h
libraries/AP_HAL_SITL/RCOutput.cpp