APM:Libraries: AP_RangeFinder_Backend Class Reference
AP_RangeFinder_Backend Class Reference abstract
#include <RangeFinder_Backend.h>
Public Member Functions
AP_RangeFinder_Backend (RangeFinder &_ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state)
virtual ~AP_RangeFinder_Backend (void)
virtual void update ()=0
bool out_of_range (void) const
virtual void handle_msg (mavlink_message_t *msg)
Protected Member Functions
void update_status ()
void set_status (RangeFinder::RangeFinder_Status status)
Protected Attributes
RangeFinder & ranger
RangeFinder::RangeFinder_State & state
AP_HAL::Semaphore * _sem
Detailed Description
Definition at line 21 of file RangeFinder_Backend.h.
Constructor & Destructor Documentation
AP_RangeFinder_Backend::AP_RangeFinder_Backend (RangeFinder & _ranger, uint8_t instance, RangeFinder::RangeFinder_State & _state)
Definition at line 27 of file RangeFinder_Backend.cpp.
virtual AP_RangeFinder_Backend::~AP_RangeFinder_Backend (void) inline virtual
Definition at line 29 of file RangeFinder_Backend.h.
Member Function Documentation
virtual void AP_RangeFinder_Backend::handle_msg (mavlink_message_t * msg) inline virtual
Reimplemented in AP_RangeFinder_MAVLink.
Definition at line 39 of file RangeFinder_Backend.h.
Referenced by RangeFinder::handle_msg().
bool AP_RangeFinder_Backend::out_of_range (void) const inline
Definition at line 35 of file RangeFinder_Backend.h.
Referenced by AP_RangeFinder_PX4_PWM::update().
void AP_RangeFinder_Backend::set_status (RangeFinder::RangeFinder_Status status) protected
Definition at line 48 of file RangeFinder_Backend.cpp.
Referenced by AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_RangeFinder_PX4_PWM::AP_RangeFinder_PX4_PWM(), handle_msg(), AP_RangeFinder_LightWareI2C::timer(), AP_RangeFinder_PulsedLightLRF::timer(), AP_RangeFinder_trone::update(), AP_RangeFinder_MaxsonarSerialLV::update(), AP_RangeFinder_LightWareSerial::update(), AP_RangeFinder_uLanding::update(), AP_RangeFinder_MAVLink::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_RangeFinder_PX4_PWM::update(), AP_RangeFinder_LeddarOne::update(), update_status(), and AP_RangeFinder_PX4_PWM::~AP_RangeFinder_PX4_PWM().
virtual void AP_RangeFinder_Backend::update () pure virtual
Implemented in AP_RangeFinder_Bebop, AP_RangeFinder_LeddarOne, AP_RangeFinder_PX4_PWM, AP_RangeFinder_BBB_PRU, AP_RangeFinder_PulsedLightLRF, AP_RangeFinder_MaxsonarI2CXL, AP_RangeFinder_MAVLink, AP_RangeFinder_uLanding, AP_RangeFinder_LightWareSerial, AP_RangeFinder_MaxsonarSerialLV, AP_RangeFinder_analog, AP_RangeFinder_LightWareI2C, and AP_RangeFinder_trone.
Referenced by RangeFinder::update(), and ~AP_RangeFinder_Backend().
void AP_RangeFinder_Backend::update_status () protected
Definition at line 35 of file RangeFinder_Backend.cpp.
Referenced by handle_msg(), AP_RangeFinder_LightWareI2C::timer(), AP_RangeFinder_PulsedLightLRF::timer(), AP_RangeFinder_trone::update(), AP_RangeFinder_analog::update(), AP_RangeFinder_LightWareSerial::update(), AP_RangeFinder_MaxsonarSerialLV::update(), AP_RangeFinder_uLanding::update(), AP_RangeFinder_MAVLink::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_RangeFinder_PX4_PWM::update(), and AP_RangeFinder_LeddarOne::update().
Member Data Documentation
AP_HAL::Semaphore* AP_RangeFinder_Backend::_sem protected
Definition at line 53 of file RangeFinder_Backend.h.
Referenced by AP_RangeFinder_MaxsonarI2CXL::_timer(), AP_RangeFinder_Backend(), AP_RangeFinder_trone::timer(), AP_RangeFinder_trone::update(), and AP_RangeFinder_MaxsonarI2CXL::update().
RangeFinder& AP_RangeFinder_Backend::ranger protected
Definition at line 49 of file RangeFinder_Backend.h.
Referenced by AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_RangeFinder_LightWareI2C::get_reading(), out_of_range(), AP_RangeFinder_analog::update(), AP_RangeFinder_PX4_PWM::update(), update_status(), and AP_RangeFinder_analog::update_voltage().
RangeFinder::RangeFinder_State& AP_RangeFinder_Backend::state protected
Definition at line 50 of file RangeFinder_Backend.h.
Referenced by AP_RangeFinder_LightWareI2C::get_reading(), set_status(), AP_RangeFinder_LightWareI2C::timer(), AP_RangeFinder_PulsedLightLRF::timer(), AP_RangeFinder_trone::update(), AP_RangeFinder_analog::update(), AP_RangeFinder_MaxsonarSerialLV::update(), AP_RangeFinder_LightWareSerial::update(), AP_RangeFinder_uLanding::update(), AP_RangeFinder_MAVLink::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_RangeFinder_BBB_PRU::update(), AP_RangeFinder_PX4_PWM::update(), AP_RangeFinder_LeddarOne::update(), update_status(), and AP_RangeFinder_analog::update_voltage().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/RangeFinder_Backend.h
libraries/AP_RangeFinder/RangeFinder_Backend.cpp