APM:Libraries: AP_InertialSensor_QURT Class Reference
AP_InertialSensor_QURT Class Reference
#include <AP_InertialSensor_QURT.h>
Public Member Functions
AP_InertialSensor_QURT (AP_InertialSensor &imu)
bool update () override
void accumulate (void) override
void data_ready (void)
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void start ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
Static Public Member Functions
static AP_InertialSensor_Backend * detect (AP_InertialSensor &imu)
Private Member Functions
bool init_sensor ()
void init_mpu9250 ()
Private Attributes
uint64_t last_timestamp
uint32_t start_time_ms
uint8_t gyro_instance
uint8_t accel_instance
ObjectBuffer< mpu9x50_data > buf {100}
Additional Inherited Members
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09, DEVTYPE_L3G4200D = 0x10, DEVTYPE_ACC_LSM303D = 0x11, DEVTYPE_ACC_BMA180 = 0x12,
DEVTYPE_ACC_MPU6000 = 0x13, DEVTYPE_ACC_MPU9250 = 0x16, DEVTYPE_GYR_MPU6000 = 0x21, DEVTYPE_GYR_L3GD20 = 0x22,
DEVTYPE_GYR_MPU9250 = 0x24
}
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false)
void _set_accel_max_abs_offset (uint8_t instance, float offset)
uint32_t _accel_raw_sample_rate (uint8_t instance) const
uint32_t _gyro_raw_sample_rate (uint8_t instance) const
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
void _inc_accel_error_count (uint8_t instance)
void _inc_gyro_error_count (uint8_t instance)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
void update_gyro (uint8_t instance)
void update_accel (uint8_t instance)
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance)
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
AP_HAL::Semaphore * _sem
int16_t _id = -1
int8_t _last_accel_filter_hz [INS_MAX_INSTANCES]
int8_t _last_gyro_filter_hz [INS_MAX_INSTANCES]
Detailed Description
Definition at line 17 of file AP_InertialSensor_QURT.h.
Constructor & Destructor Documentation
AP_InertialSensor_QURT::AP_InertialSensor_QURT (AP_InertialSensor & imu)
Definition at line 10 of file AP_InertialSensor_QURT.cpp.
Referenced by detect().
Member Function Documentation
void AP_InertialSensor_QURT::accumulate (void) override virtual
Reimplemented from AP_InertialSensor_Backend.
Definition at line 97 of file AP_InertialSensor_QURT.cpp.
Referenced by update().
void AP_InertialSensor_QURT::data_ready (void)
Definition at line 83 of file AP_InertialSensor_QURT.cpp.
AP_InertialSensor_Backend * AP_InertialSensor_QURT::detect (AP_InertialSensor & imu) static
Definition at line 18 of file AP_InertialSensor_QURT.cpp.
Referenced by AP_InertialSensor::detect_backends().
void AP_InertialSensor_QURT::init_mpu9250 (void) private
Definition at line 54 of file AP_InertialSensor_QURT.cpp.
Referenced by init_sensor().
bool AP_InertialSensor_QURT::init_sensor (void) private
Definition at line 31 of file AP_InertialSensor_QURT.cpp.
Referenced by detect().
bool AP_InertialSensor_QURT::update (void) override virtual
Implements AP_InertialSensor_Backend.
Definition at line 120 of file AP_InertialSensor_QURT.cpp.
Member Data Documentation
uint8_t AP_InertialSensor_QURT::accel_instance private
Definition at line 39 of file AP_InertialSensor_QURT.h.
Referenced by accumulate(), init_sensor(), and update().
ObjectBuffer<mpu9x50_data> AP_InertialSensor_QURT::buf {100} private
Definition at line 41 of file AP_InertialSensor_QURT.h.
Referenced by accumulate(), and data_ready().
uint8_t AP_InertialSensor_QURT::gyro_instance private
Definition at line 38 of file AP_InertialSensor_QURT.h.
Referenced by accumulate(), init_sensor(), and update().
uint64_t AP_InertialSensor_QURT::last_timestamp private
Definition at line 35 of file AP_InertialSensor_QURT.h.
uint32_t AP_InertialSensor_QURT::start_time_ms private
Definition at line 36 of file AP_InertialSensor_QURT.h.
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_QURT.h
libraries/AP_InertialSensor/AP_InertialSensor_QURT.cpp