APM:Libraries: PX4::RCOutput_Tap Class Reference
PX4::RCOutput_Tap Class Reference
#include <RCOutput_Tap.h>
Public Member Functions
void init () override
void set_freq (uint32_t chmask, uint16_t freq_hz) override
uint16_t get_freq (uint8_t ch) override
void enable_ch (uint8_t ch) override
void disable_ch (uint8_t ch) override
void write (uint8_t ch, uint16_t period_us) override
uint16_t read (uint8_t ch) override
void read (uint16_t *period_us, uint8_t len) override
void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm) override
void cork () override
void push () override
Public Member Functions inherited from AP_HAL::RCOutput
virtual uint16_t read_last_sent (uint8_t ch)
virtual void read_last_sent (uint16_t *period_us, uint8_t len)
virtual void set_safety_pwm (uint32_t chmask, uint16_t period_us)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
virtual void force_safety_no_wait (void)
virtual float scale_esc_to_unity (uint16_t pwm)
virtual bool enable_sbus_out (uint16_t rate_gz)
virtual void timer_tick (void)
virtual void set_output_mode (enum output_mode mode)
Private Member Functions
int _send_packet (EscPacket &p)
bool _uart_open ()
void _uart_close ()
Static Private Member Functions
static uint8_t _crc8_esc (uint8_t *p, uint8_t len)
static uint8_t _crc_packet (EscPacket &p)
Private Attributes
perf_counter_t _perf_rcout
uint8_t _enabled_channels
bool _corking
uint8_t _channels_count = MAX_MOTORS
uint8_t _next_channel_reply
uint16_t _period [MAX_MOTORS]
uint16_t _esc_pwm_min
uint16_t _esc_pwm_max
int _uart_fd = -1
Static Private Attributes
static const uint8_t MAX_MOTORS = 4
Additional Inherited Members
Public Types inherited from AP_HAL::RCOutput
enum output_mode { MODE_PWM_NORMAL, MODE_PWM_ONESHOT, MODE_PWM_BRUSHED16KHZ }
Detailed Description
Definition at line 61 of file RCOutput_Tap.h.
Member Function Documentation
uint8_t RCOutput_Tap::_crc8_esc (uint8_t * p, uint8_t len) static private
Definition at line 419 of file RCOutput_Tap.cpp.
Referenced by set_esc_scaling().
uint8_t RCOutput_Tap::_crc_packet (EscPacket & p) static private
Definition at line 430 of file RCOutput_Tap.cpp.
Referenced by set_esc_scaling().
int RCOutput_Tap::_send_packet (EscPacket & p) private
Definition at line 407 of file RCOutput_Tap.cpp.
void RCOutput_Tap::_uart_close () private
Definition at line 309 of file RCOutput_Tap.cpp.
bool RCOutput_Tap::_uart_open () private
Definition at line 318 of file RCOutput_Tap.cpp.
void RCOutput_Tap::cork (void) override virtual
Implements AP_HAL::RCOutput.
Definition at line 498 of file RCOutput_Tap.cpp.
Referenced by set_esc_scaling().
void RCOutput_Tap::disable_ch (uint8_t ch) override virtual
Implements AP_HAL::RCOutput.
Definition at line 457 of file RCOutput_Tap.cpp.
void RCOutput_Tap::enable_ch (uint8_t ch) override virtual
Implements AP_HAL::RCOutput.
Definition at line 449 of file RCOutput_Tap.cpp.
uint16_t RCOutput_Tap::get_freq (uint8_t ch) override virtual
Implements AP_HAL::RCOutput.
Definition at line 444 of file RCOutput_Tap.cpp.
void RCOutput_Tap::init (void) override virtual
Implements AP_HAL::RCOutput.
Definition at line 354 of file RCOutput_Tap.cpp.
void RCOutput_Tap::push (void) override virtual
Implements AP_HAL::RCOutput.
Definition at line 503 of file RCOutput_Tap.cpp.
Referenced by set_esc_scaling().
uint16_t RCOutput_Tap::read (uint8_t ch) override virtual
Implements AP_HAL::RCOutput.
Definition at line 483 of file RCOutput_Tap.cpp.
void RCOutput_Tap::read (uint16_t * period_us, uint8_t len) override virtual
Implements AP_HAL::RCOutput.
Definition at line 491 of file RCOutput_Tap.cpp.
void PX4::RCOutput_Tap::set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm) inline override virtual
Reimplemented from AP_HAL::RCOutput.
Definition at line 72 of file RCOutput_Tap.h.
void RCOutput_Tap::set_freq (uint32_t chmask, uint16_t freq_hz) override virtual
Implements AP_HAL::RCOutput.
Definition at line 440 of file RCOutput_Tap.cpp.
void RCOutput_Tap::write (uint8_t ch, uint16_t period_us) override virtual
Implements AP_HAL::RCOutput.
Definition at line 466 of file RCOutput_Tap.cpp.
Member Data Documentation
uint8_t PX4::RCOutput_Tap::_channels_count = MAX_MOTORS private
Definition at line 95 of file RCOutput_Tap.h.
bool PX4::RCOutput_Tap::_corking private
Definition at line 93 of file RCOutput_Tap.h.
uint8_t PX4::RCOutput_Tap::_enabled_channels private
Definition at line 92 of file RCOutput_Tap.h.
uint16_t PX4::RCOutput_Tap::_esc_pwm_max private
Definition at line 100 of file RCOutput_Tap.h.
Referenced by set_esc_scaling().
uint16_t PX4::RCOutput_Tap::_esc_pwm_min private
Definition at line 99 of file RCOutput_Tap.h.
Referenced by set_esc_scaling().
uint8_t PX4::RCOutput_Tap::_next_channel_reply private
Definition at line 96 of file RCOutput_Tap.h.
perf_counter_t PX4::RCOutput_Tap::_perf_rcout private
Definition at line 90 of file RCOutput_Tap.h.
uint16_t PX4::RCOutput_Tap::_period[MAX_MOTORS] private
Definition at line 98 of file RCOutput_Tap.h.
int PX4::RCOutput_Tap::_uart_fd = -1 private
Definition at line 101 of file RCOutput_Tap.h.
const uint8_t PX4::RCOutput_Tap::MAX_MOTORS = 4 static private
Definition at line 84 of file RCOutput_Tap.h.
The documentation for this class was generated from the following files:
libraries/AP_HAL_PX4/RCOutput_Tap.h
libraries/AP_HAL_PX4/RCOutput_Tap.cpp