APM:Libraries: Location_Class Class Reference
Location_Class Class Reference
#include <Location.h>
Public Types
enum ALT_FRAME { ALT_FRAME_ABSOLUTE = 0, ALT_FRAME_ABOVE_HOME = 1, ALT_FRAME_ABOVE_ORIGIN = 2, ALT_FRAME_ABOVE_TERRAIN = 3 }
enumeration of possible altitude types
Public Member Functions
Location_Class ()
constructors
Location_Class (int32_t latitude, int32_t longitude, int32_t alt_in_cm, ALT_FRAME frame)
Location_Class (const Location &loc)
Location_Class (const Vector3f &ekf_offset_neu)
Location_Class & operator= (const struct Location &loc)
void set_alt_cm (int32_t alt_cm, ALT_FRAME frame)
bool get_alt_cm (ALT_FRAME desired_frame, int32_t &ret_alt_cm) const
get altitude in desired frame
ALT_FRAME get_alt_frame () const
bool change_alt_frame (ALT_FRAME desired_frame)
bool get_vector_xy_from_origin_NEU (Vector3f &vec_neu) const
bool get_vector_from_origin_NEU (Vector3f &vec_neu) const
float get_distance (const struct Location &loc2) const
void offset (float ofs_north, float ofs_east)
bool is_zero (void)
void zero (void)
Static Public Member Functions
static void set_ahrs (const AP_AHRS_NavEKF *ahrs)
accept reference to ahrs and (indirectly) EKF
static void set_terrain (AP_Terrain *terrain)
Static Private Attributes
static const AP_AHRS_NavEKF * _ahrs = nullptr
static AP_Terrain * _terrain = nullptr
Additional Inherited Members
Public Attributes inherited from Location
union {
Location_Option_Flags flags
options bitmask (1<<0 = relative altitude)
uint8_t options
};
int32_t alt:24
param 2 - Altitude in centimeters (meters * 100) see LOCATION_ALT_MAX_M
int32_t lat
param 3 - Latitude * 10**7
int32_t lng
param 4 - Longitude * 10**7
Detailed Description
Definition at line 17 of file Location.h.
Member Enumeration Documentation
enum Location_Class::ALT_FRAME
enumeration of possible altitude types
Enumerator
ALT_FRAME_ABSOLUTE
ALT_FRAME_ABOVE_HOME
ALT_FRAME_ABOVE_ORIGIN
ALT_FRAME_ABOVE_TERRAIN
Definition at line 22 of file Location.h.
Constructor & Destructor Documentation
Location_Class::Location_Class ()
constructors
Definition at line 17 of file Location.cpp.
Location_Class::Location_Class (int32_t latitude, int32_t longitude, int32_t alt_in_cm, ALT_FRAME frame)
Definition at line 22 of file Location.cpp.
Location_Class::Location_Class (const Location & loc)
Definition at line 30 of file Location.cpp.
Location_Class::Location_Class (const Vector3f & ekf_offset_neu)
Definition at line 38 of file Location.cpp.
Member Function Documentation
bool Location_Class::change_alt_frame (ALT_FRAME desired_frame)
Definition at line 89 of file Location.cpp.
Referenced by AC_WPNav::set_spline_destination(), and set_terrain().
bool Location_Class::get_alt_cm (ALT_FRAME desired_frame, int32_t & ret_alt_cm) const
get altitude in desired frame
Definition at line 115 of file Location.cpp.
Referenced by change_alt_frame(), AC_Fence::check_destination_within_fence(), get_vector_from_origin_NEU(), AC_WPNav::get_vector_NEU(), and set_terrain().
Location_Class::ALT_FRAME Location_Class::get_alt_frame () const
Definition at line 100 of file Location.cpp.
Referenced by get_alt_cm(), AC_WPNav::get_vector_NEU(), AC_WPNav::set_spline_destination(), and set_terrain().
float Location_Class::get_distance (const struct Location & loc2) const
Definition at line 223 of file Location.cpp.
Referenced by AP_ADSB::determine_furthest_aircraft(), AP_ADSB::handle_vehicle(), and set_terrain().
bool Location_Class::get_vector_from_origin_NEU (Vector3f & vec_neu) const
Definition at line 205 of file Location.cpp.
Referenced by set_terrain().
bool Location_Class::get_vector_xy_from_origin_NEU (Vector3f & vec_neu) const
Definition at line 193 of file Location.cpp.
Referenced by get_vector_from_origin_NEU(), AC_WPNav::get_vector_NEU(), and set_terrain().
bool Location_Class::is_zero (void) inline
Definition at line 70 of file Location.h.
Referenced by AP_ADSB::handle_vehicle(), and AP_ADSB::update().
void Location_Class::offset (float ofs_north, float ofs_east)
Definition at line 231 of file Location.cpp.
Referenced by Location_Class(), and set_terrain().
Location_Class & Location_Class::operator= (const struct Location & loc)
Definition at line 54 of file Location.cpp.
Referenced by set_terrain().
static void Location_Class::set_ahrs (const AP_AHRS_NavEKF * ahrs) inline static
accept reference to ahrs and (indirectly) EKF
Definition at line 36 of file Location.h.
void Location_Class::set_alt_cm (int32_t alt_cm, ALT_FRAME frame)
Definition at line 63 of file Location.cpp.
Referenced by change_alt_frame(), Location_Class(), and set_terrain().
static void Location_Class::set_terrain (AP_Terrain * terrain) inline static
Definition at line 37 of file Location.h.
void Location_Class::zero (void) inline
Definition at line 72 of file Location.h.
Referenced by Location_Class(), and AP_ADSB::update().
Member Data Documentation
const AP_AHRS_NavEKF * Location_Class::_ahrs = nullptr static private
Definition at line 75 of file Location.h.
Referenced by get_alt_cm(), get_vector_xy_from_origin_NEU(), Location_Class(), and set_ahrs().
AP_Terrain * Location_Class::_terrain = nullptr static private
Definition at line 76 of file Location.h.
Referenced by get_alt_cm(), and set_terrain().
The documentation for this class was generated from the following files:
libraries/AP_Common/Location.h
libraries/AP_Common/Location.cpp