APM:Libraries: AP_GPS_GSOF Class Reference
AP_GPS_GSOF Class Reference
#include <AP_GPS_GSOF.h>
Classes
struct gsof_msg_parser_t
Public Member Functions
AP_GPS_GSOF (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
AP_GPS::GPS_Status highest_supported_status (void)
bool read ()
void inject_data (const uint8_t *data, uint16_t len) override
Public Member Functions inherited from AP_GPS_Backend
AP_GPS_Backend (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
virtual ~AP_GPS_Backend (void)
virtual bool is_configured (void)
virtual void send_mavlink_gps_rtk (mavlink_channel_t chan)
virtual void send_mavlink_gps2_rtk (mavlink_channel_t chan)
virtual void broadcast_configuration_failure_reason (void) const
virtual void handle_msg (const mavlink_message_t *msg)
virtual void handle_gnss_msg (const AP_GPS::GPS_State &msg)
virtual float get_lag (void) const
Private Member Functions
bool parse (uint8_t temp)
bool process_message ()
void requestBaud (uint8_t portindex)
void requestGSOF (uint8_t messagetype, uint8_t portindex)
double SwapDouble (uint8_t *src, uint32_t pos)
float SwapFloat (uint8_t *src, uint32_t pos)
uint32_t SwapUint32 (uint8_t *src, uint32_t pos)
uint16_t SwapUint16 (uint8_t *src, uint32_t pos)
Private Attributes
struct AP_GPS_GSOF::gsof_msg_parser_t gsof_msg
uint8_t packetcount = 0
uint32_t gsofmsg_time = 0
uint8_t gsofmsgreq_index = 0
uint8_t gsofmsgreq [5] = {1,2,8,9,12}
uint32_t last_injected_data_ms = 0
Static Private Attributes
static const uint8_t GSOF_STX = 0x02
static const uint8_t GSOF_ETX = 0x03
Additional Inherited Members
Protected Member Functions inherited from AP_GPS_Backend
int32_t swap_int32 (int32_t v) const
int16_t swap_int16 (int16_t v) const
void fill_3d_velocity (void)
void make_gps_time (uint32_t bcd_date, uint32_t bcd_milliseconds)
Protected Attributes inherited from AP_GPS_Backend
AP_HAL::UARTDriver * port
UART we are attached to.
AP_GPS & gps
access to frontend (for parameters)
AP_GPS::GPS_State & state
public state for this instance
Detailed Description
Definition at line 25 of file AP_GPS_GSOF.h.
Constructor & Destructor Documentation
AP_GPS_GSOF::AP_GPS_GSOF (AP_GPS & _gps, AP_GPS::GPS_State & _state, AP_HAL::UARTDriver * _port)
Definition at line 41 of file AP_GPS_GSOF.cpp.
Member Function Documentation
AP_GPS::GPS_Status AP_GPS_GSOF::highest_supported_status (void) inline virtual
Reimplemented from AP_GPS_Backend.
Definition at line 30 of file AP_GPS_GSOF.h.
void AP_GPS_GSOF::inject_data (const uint8_t * data, uint16_t len) override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 346 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status().
bool AP_GPS_GSOF::parse (uint8_t temp) private
Definition at line 82 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status(), and read().
bool AP_GPS_GSOF::process_message (void) private
Definition at line 243 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status(), and parse().
bool AP_GPS_GSOF::read (void) virtual
Implements AP_GPS_Backend.
Definition at line 59 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status().
void AP_GPS_GSOF::requestBaud (uint8_t portindex) private
Definition at line 138 of file AP_GPS_GSOF.cpp.
Referenced by AP_GPS_GSOF(), and highest_supported_status().
void AP_GPS_GSOF::requestGSOF (uint8_t messagetype, uint8_t portindex) private
Definition at line 159 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status(), and read().
double AP_GPS_GSOF::SwapDouble (uint8_t * src, uint32_t pos) private
Definition at line 181 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status(), and process_message().
float AP_GPS_GSOF::SwapFloat (uint8_t * src, uint32_t pos) private
Definition at line 200 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status(), and process_message().
uint16_t AP_GPS_GSOF::SwapUint16 (uint8_t * src, uint32_t pos) private
Definition at line 230 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status(), and process_message().
uint32_t AP_GPS_GSOF::SwapUint32 (uint8_t * src, uint32_t pos) private
Definition at line 215 of file AP_GPS_GSOF.cpp.
Referenced by highest_supported_status(), and process_message().
Member Data Documentation
const uint8_t AP_GPS_GSOF::GSOF_ETX = 0x03 static private
Definition at line 77 of file AP_GPS_GSOF.h.
struct AP_GPS_GSOF::gsof_msg_parser_t AP_GPS_GSOF::gsof_msg private
Referenced by AP_GPS_GSOF(), parse(), and process_message().
const uint8_t AP_GPS_GSOF::GSOF_STX = 0x02 static private
Definition at line 76 of file AP_GPS_GSOF.h.
Referenced by parse().
uint32_t AP_GPS_GSOF::gsofmsg_time = 0 private
Definition at line 81 of file AP_GPS_GSOF.h.
Referenced by AP_GPS_GSOF(), and read().
uint8_t AP_GPS_GSOF::gsofmsgreq[5] = {1,2,8,9,12} private
Definition at line 83 of file AP_GPS_GSOF.h.
Referenced by read().
uint8_t AP_GPS_GSOF::gsofmsgreq_index = 0 private
Definition at line 82 of file AP_GPS_GSOF.h.
Referenced by read().
uint32_t AP_GPS_GSOF::last_injected_data_ms = 0 private
Definition at line 85 of file AP_GPS_GSOF.h.
Referenced by inject_data().
uint8_t AP_GPS_GSOF::packetcount = 0 private
Definition at line 79 of file AP_GPS_GSOF.h.
Referenced by requestBaud(), and requestGSOF().
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS_GSOF.h
libraries/AP_GPS/AP_GPS_GSOF.cpp