APM:Libraries: Linux::DigitalSource_Sysfs Class Reference
Linux::DigitalSource_Sysfs Class Reference
#include <GPIO_Sysfs.h>
Public Member Functions
~DigitalSource_Sysfs ()
uint8_t read ()
void write (uint8_t value)
void mode (uint8_t output)
void toggle ()
Private Member Functions
DigitalSource_Sysfs (unsigned pin, int value_fd)
Private Attributes
int _value_fd
unsigned _pin
Friends
class GPIO_Sysfs
Detailed Description
Definition at line 10 of file GPIO_Sysfs.h.
Constructor & Destructor Documentation
Linux::DigitalSource_Sysfs::~DigitalSource_Sysfs ()
Linux::DigitalSource_Sysfs::DigitalSource_Sysfs (unsigned pin, int value_fd) private
Member Function Documentation
void Linux::DigitalSource_Sysfs::mode (uint8_t output) virtual
Implements AP_HAL::DigitalSource.
Referenced by Linux::GPIO_Sysfs::from().
uint8_t Linux::DigitalSource_Sysfs::read () virtual
Implements AP_HAL::DigitalSource.
Referenced by Linux::GPIO_Sysfs::from().
void Linux::DigitalSource_Sysfs::toggle () virtual
Implements AP_HAL::DigitalSource.
Referenced by Linux::GPIO_Sysfs::from().
void Linux::DigitalSource_Sysfs::write (uint8_t value) virtual
Implements AP_HAL::DigitalSource.
Referenced by Linux::GPIO_Sysfs::from().
Friends And Related Function Documentation
friend class GPIO_Sysfs friend
Definition at line 11 of file GPIO_Sysfs.h.
Member Data Documentation
unsigned Linux::DigitalSource_Sysfs::_pin private
Definition at line 22 of file GPIO_Sysfs.h.
int Linux::DigitalSource_Sysfs::_value_fd private
Definition at line 21 of file GPIO_Sysfs.h.
The documentation for this class was generated from the following file:
libraries/AP_HAL_Linux/GPIO_Sysfs.h