APM:Libraries: AP_Compass_Backend Class Reference
AP_Compass_Backend Class Reference abstract
#include <AP_Compass_Backend.h>
Public Types
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01, DEVTYPE_HMC5883 = 0x07, DEVTYPE_LSM303D = 0x02, DEVTYPE_AK8963 = 0x04,
DEVTYPE_BMM150 = 0x05, DEVTYPE_LSM9DS1 = 0x06, DEVTYPE_LIS3MDL = 0x08, DEVTYPE_AK09916 = 0x09,
DEVTYPE_IST8310 = 0x0A
}
Public Member Functions
AP_Compass_Backend (Compass &compass)
virtual ~AP_Compass_Backend (void)
virtual void read (void)=0
virtual void accumulate (void)
virtual void handle_mag_msg (Vector3f &mag)
Protected Member Functions
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint32_t time_us, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
uint8_t register_compass (void) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
Protected Attributes
Compass & _compass
AP_HAL::Semaphore * _sem
Private Member Functions
void apply_corrections (Vector3f &mag, uint8_t i)
Detailed Description
Definition at line 25 of file AP_Compass_Backend.h.
Member Enumeration Documentation
enum AP_Compass_Backend::DevTypes
Enumerator
DEVTYPE_HMC5883_OLD
DEVTYPE_HMC5883
DEVTYPE_LSM303D
DEVTYPE_AK8963
DEVTYPE_BMM150
DEVTYPE_LSM9DS1
DEVTYPE_LIS3MDL
DEVTYPE_AK09916
DEVTYPE_IST8310
Definition at line 52 of file AP_Compass_Backend.h.
Constructor & Destructor Documentation
AP_Compass_Backend::AP_Compass_Backend (Compass & compass)
Definition at line 8 of file AP_Compass_Backend.cpp.
virtual AP_Compass_Backend::~AP_Compass_Backend (void) inline virtual
Definition at line 32 of file AP_Compass_Backend.h.
Member Function Documentation
virtual void AP_Compass_Backend::accumulate (void) inline virtual
Reimplemented in AP_Compass_PX4.
Definition at line 39 of file AP_Compass_Backend.h.
Referenced by Compass::accumulate().
void AP_Compass_Backend::apply_corrections (Vector3f & mag, uint8_t i) private
void AP_Compass_Backend::correct_field (Vector3f & mag, uint8_t i) protected
Definition at line 41 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_LSM9DS1::_update(), AP_Compass_LSM303D::_update(), AP_Compass_BMM150::_update(), AP_Compass_AK8963::_update(), AP_Compass_PX4::accumulate(), AP_Compass_HIL::read(), AP_Compass_IST8310::timer(), AP_Compass_AK09916::timer(), AP_Compass_LIS3MDL::timer(), AP_Compass_QURT::timer_update(), and AP_Compass_QFLIGHT::timer_update().
virtual void AP_Compass_Backend::handle_mag_msg (Vector3f & mag) inline virtual
Reimplemented in AP_Compass_UAVCAN.
Definition at line 42 of file AP_Compass_Backend.h.
bool AP_Compass_Backend::is_external (uint8_t instance) protected
Definition at line 122 of file AP_Compass_Backend.cpp.
void AP_Compass_Backend::publish_filtered_field (const Vector3f & mag, uint8_t instance) protected
Definition at line 78 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_QURT::init(), AP_Compass_QURT::read(), AP_Compass_PX4::read(), AP_Compass_HIL::read(), AP_Compass_QFLIGHT::read(), AP_Compass_LSM9DS1::read(), AP_Compass_LSM303D::read(), AP_Compass_BMM150::read(), AP_Compass_IST8310::read(), AP_Compass_AK09916::read(), AP_Compass_AK8963::read(), and AP_Compass_LIS3MDL::read().
void AP_Compass_Backend::publish_raw_field (const Vector3f & mag, uint32_t time_us, uint8_t instance) protected
Definition at line 29 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_LSM9DS1::_update(), AP_Compass_LSM303D::_update(), AP_Compass_BMM150::_update(), AP_Compass_AK8963::_update(), AP_Compass_PX4::accumulate(), AP_Compass_HIL::read(), AP_Compass_IST8310::timer(), AP_Compass_AK09916::timer(), AP_Compass_LIS3MDL::timer(), AP_Compass_QURT::timer_update(), and AP_Compass_QFLIGHT::timer_update().
virtual void AP_Compass_Backend::read (void) pure virtual
Implemented in AP_Compass_AK8963, AP_Compass_LIS3MDL, AP_Compass_AK09916, AP_Compass_IST8310, AP_Compass_BMM150, AP_Compass_HMC5843, AP_Compass_LSM303D, AP_Compass_LSM9DS1, AP_Compass_QFLIGHT, AP_Compass_HIL, AP_Compass_PX4, AP_Compass_UAVCAN, and AP_Compass_QURT.
Referenced by Compass::read(), and ~AP_Compass_Backend().
uint8_t AP_Compass_Backend::register_compass (void) const protected
Definition at line 98 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_PX4::init(), AP_Compass_HIL::init(), AP_Compass_QFLIGHT::init(), AP_Compass_QURT::init(), AP_Compass_LSM9DS1::init(), AP_Compass_LSM303D::init(), AP_Compass_BMM150::init(), AP_Compass_AK8963::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), and AP_Compass_LIS3MDL::init().
void AP_Compass_Backend::rotate_field (Vector3f & mag, uint8_t instance) protected
Definition at line 14 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_LSM9DS1::_update(), AP_Compass_LSM303D::_update(), AP_Compass_BMM150::_update(), AP_Compass_AK8963::_update(), AP_Compass_PX4::accumulate(), AP_Compass_HIL::read(), AP_Compass_IST8310::timer(), AP_Compass_AK09916::timer(), AP_Compass_LIS3MDL::timer(), AP_Compass_QURT::timer_update(), and AP_Compass_QFLIGHT::timer_update().
void AP_Compass_Backend::set_dev_id (uint8_t instance, uint32_t dev_id) protected
Definition at line 107 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_PX4::init(), AP_Compass_LSM303D::init(), AP_Compass_LSM9DS1::init(), AP_Compass_BMM150::init(), AP_Compass_AK8963::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), and AP_Compass_LIS3MDL::init().
void AP_Compass_Backend::set_external (uint8_t instance, bool external) protected
Definition at line 115 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_PX4::init(), AP_Compass_LSM303D::init(), AP_Compass_AK09916::init(), and AP_Compass_LIS3MDL::init().
void AP_Compass_Backend::set_last_update_usec (uint32_t last_update, uint8_t instance) protected
Definition at line 88 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_HIL::read().
void AP_Compass_Backend::set_rotation (uint8_t instance, enum Rotation rotation) protected
Definition at line 128 of file AP_Compass_Backend.cpp.
Referenced by AP_Compass_LSM303D::init(), AP_Compass_LSM9DS1::init(), AP_Compass_AK8963::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), and AP_Compass_LIS3MDL::init().
Member Data Documentation
Compass& AP_Compass_Backend::_compass protected
Definition at line 102 of file AP_Compass_Backend.h.
Referenced by AP_Compass_HIL::AP_Compass_HIL(), correct_field(), is_external(), publish_filtered_field(), publish_raw_field(), AP_Compass_HIL::read(), register_compass(), rotate_field(), set_dev_id(), set_external(), set_last_update_usec(), and set_rotation().
AP_HAL::Semaphore* AP_Compass_Backend::_sem protected
Definition at line 105 of file AP_Compass_Backend.h.
Referenced by AP_Compass_LSM9DS1::_update(), AP_Compass_LSM303D::_update(), AP_Compass_BMM150::_update(), AP_Compass_AK8963::_update(), AP_Compass_Backend(), AP_Compass_LSM303D::read(), AP_Compass_LSM9DS1::read(), AP_Compass_BMM150::read(), AP_Compass_IST8310::read(), AP_Compass_AK09916::read(), AP_Compass_AK8963::read(), AP_Compass_LIS3MDL::read(), AP_Compass_IST8310::timer(), AP_Compass_AK09916::timer(), and AP_Compass_LIS3MDL::timer().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_Backend.h
libraries/AP_Compass/AP_Compass_Backend.cpp