APM:Libraries: AnalogSource_Raspilot Class Reference
AnalogSource_Raspilot Class Reference
#include <AnalogIn_Raspilot.h>
Public Member Functions
AnalogSource_Raspilot (int16_t pin)
float read_average ()
float read_latest ()
void set_pin (uint8_t p)
void set_stop_pin (uint8_t p)
void set_settle_time (uint16_t settle_time_ms)
float voltage_average ()
float voltage_latest ()
float voltage_average_ratiometric ()
Private Attributes
int16_t _pin
float _value
Friends
class AnalogIn_Raspilot
Detailed Description
Definition at line 10 of file AnalogIn_Raspilot.h.
Constructor & Destructor Documentation
AnalogSource_Raspilot::AnalogSource_Raspilot (int16_t pin)
Definition at line 9 of file AnalogIn_Raspilot.cpp.
Referenced by AnalogIn_Raspilot::channel().
Member Function Documentation
float AnalogSource_Raspilot::read_average () virtual
Implements AP_HAL::AnalogSource.
Definition at line 22 of file AnalogIn_Raspilot.cpp.
float AnalogSource_Raspilot::read_latest () virtual
Implements AP_HAL::AnalogSource.
Definition at line 27 of file AnalogIn_Raspilot.cpp.
Referenced by read_average().
void AnalogSource_Raspilot::set_pin (uint8_t p) virtual
Implements AP_HAL::AnalogSource.
Definition at line 14 of file AnalogIn_Raspilot.cpp.
void AnalogSource_Raspilot::set_settle_time (uint16_t settle_time_ms) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 18 of file AnalogIn_Raspilot.h.
void AnalogSource_Raspilot::set_stop_pin (uint8_t p) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 17 of file AnalogIn_Raspilot.h.
float AnalogSource_Raspilot::voltage_average () virtual
Implements AP_HAL::AnalogSource.
Definition at line 32 of file AnalogIn_Raspilot.cpp.
Referenced by set_settle_time().
float AnalogSource_Raspilot::voltage_average_ratiometric () virtual
Implements AP_HAL::AnalogSource.
Definition at line 42 of file AnalogIn_Raspilot.cpp.
Referenced by set_settle_time().
float AnalogSource_Raspilot::voltage_latest () virtual
Implements AP_HAL::AnalogSource.
Definition at line 37 of file AnalogIn_Raspilot.cpp.
Referenced by set_settle_time().
Friends And Related Function Documentation
friend class AnalogIn_Raspilot friend
Definition at line 12 of file AnalogIn_Raspilot.h.
Member Data Documentation
int16_t AnalogSource_Raspilot::_pin private
Definition at line 23 of file AnalogIn_Raspilot.h.
Referenced by AnalogIn_Raspilot::_update(), and set_pin().
float AnalogSource_Raspilot::_value private
Definition at line 24 of file AnalogIn_Raspilot.h.
Referenced by AnalogIn_Raspilot::_update(), read_latest(), voltage_average(), voltage_average_ratiometric(), and voltage_latest().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/AnalogIn_Raspilot.h
libraries/AP_HAL_Linux/AnalogIn_Raspilot.cpp