APM:Libraries: HALSITL::ADCSource Class Reference
HALSITL::ADCSource Class Reference
#include <AnalogIn.h>
Public Member Functions
ADCSource (SITL_State *sitlState, int16_t pin)
float read_average ()
float read_latest ()
void set_pin (uint8_t p)
float voltage_average ()
float voltage_latest ()
float voltage_average_ratiometric ()
void set_stop_pin (uint8_t pin)
void set_settle_time (uint16_t settle_time_ms)
Private Attributes
SITL_State * _sitlState
int16_t _pin
Friends
class HALSITL::AnalogIn
Detailed Description
Definition at line 8 of file AnalogIn.h.
Constructor & Destructor Documentation
ADCSource::ADCSource (SITL_State * sitlState, int16_t pin)
Definition at line 12 of file AnalogIn.cpp.
Referenced by HALSITL::AnalogIn::channel().
Member Function Documentation
float ADCSource::read_average () virtual
Implements AP_HAL::AnalogSource.
Definition at line 17 of file AnalogIn.cpp.
Referenced by voltage_average().
float ADCSource::read_latest () virtual
Implements AP_HAL::AnalogSource.
Definition at line 29 of file AnalogIn.cpp.
Referenced by read_average(), and voltage_latest().
void ADCSource::set_pin (uint8_t p) virtual
Implements AP_HAL::AnalogSource.
Definition at line 52 of file AnalogIn.cpp.
void HALSITL::ADCSource::set_settle_time (uint16_t settle_time_ms) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 24 of file AnalogIn.h.
void HALSITL::ADCSource::set_stop_pin (uint8_t pin) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 23 of file AnalogIn.h.
float ADCSource::voltage_average () virtual
Implements AP_HAL::AnalogSource.
Definition at line 21 of file AnalogIn.cpp.
Referenced by voltage_average_ratiometric().
float HALSITL::ADCSource::voltage_average_ratiometric () inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 20 of file AnalogIn.h.
float ADCSource::voltage_latest () virtual
Implements AP_HAL::AnalogSource.
Definition at line 25 of file AnalogIn.cpp.
Friends And Related Function Documentation
friend class HALSITL::AnalogIn friend
Definition at line 10 of file AnalogIn.h.
Member Data Documentation
int16_t HALSITL::ADCSource::_pin private
Definition at line 28 of file AnalogIn.h.
Referenced by read_latest(), and set_pin().
SITL_State* HALSITL::ADCSource::_sitlState private
Definition at line 27 of file AnalogIn.h.
Referenced by HALSITL::AnalogIn::channel(), and read_latest().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/AnalogIn.h
libraries/AP_HAL_SITL/AnalogIn.cpp