APM:Libraries: Bitmask Class Reference
Bitmask Class Reference
#include <Bitmask.h>
Public Member Functions
Bitmask (uint16_t numbits)
~Bitmask (void)
void set (uint16_t bit)
void clear (uint16_t bit)
void clearall (void)
bool get (uint16_t bit)
bool empty (void)
Private Attributes
uint16_t numwords
uint32_t * bits
Detailed Description
Definition at line 19 of file Bitmask.h.
Constructor & Destructor Documentation
Bitmask::Bitmask (uint16_t numbits) inline
Definition at line 21 of file Bitmask.h.
Bitmask::~Bitmask (void) inline
Definition at line 25 of file Bitmask.h.
Member Function Documentation
void Bitmask::clear (uint16_t bit) inline
Definition at line 37 of file Bitmask.h.
Referenced by PX4::PX4Storage::_mtd_load(), and PX4::PX4Storage::_mtd_write().
void Bitmask::clearall (void) inline
Definition at line 44 of file Bitmask.h.
Referenced by PX4::PX4Storage::_storage_open().
bool Bitmask::empty (void) inline
Definition at line 58 of file Bitmask.h.
Referenced by PX4::PX4Storage::_timer_tick().
bool Bitmask::get (uint16_t bit) inline
Definition at line 51 of file Bitmask.h.
Referenced by PX4::PX4Storage::_timer_tick().
void Bitmask::set (uint16_t bit) inline
Definition at line 30 of file Bitmask.h.
Referenced by PX4::PX4Storage::_mark_dirty(), and PX4::PX4Storage::_mtd_write().
Member Data Documentation
uint32_t* Bitmask::bits private
Definition at line 69 of file Bitmask.h.
Referenced by Bitmask(), clear(), clearall(), empty(), get(), set(), and ~Bitmask().
uint16_t Bitmask::numwords private
Definition at line 68 of file Bitmask.h.
Referenced by Bitmask(), clearall(), and empty().
The documentation for this class was generated from the following file:
libraries/AP_Common/Bitmask.h