APM:Libraries: NotifyDevice Class Reference
NotifyDevice Class Reference abstract
#include <NotifyDevice.h>
Public Member Functions
virtual ~NotifyDevice ()
virtual bool init (void)=0
virtual void update ()=0
virtual void handle_led_control (mavlink_message_t *msg)
virtual void handle_play_tune (mavlink_message_t *msg)
Public Attributes
const AP_Notify * pNotify
Detailed Description
Definition at line 8 of file NotifyDevice.h.
Constructor & Destructor Documentation
virtual NotifyDevice::~NotifyDevice () inline virtual
Definition at line 10 of file NotifyDevice.h.
Member Function Documentation
virtual void NotifyDevice::handle_led_control (mavlink_message_t * msg) inline virtual
Reimplemented in OreoLED_PX4, and RGBLed.
Definition at line 18 of file NotifyDevice.h.
Referenced by AP_Notify::handle_led_control().
virtual void NotifyDevice::handle_play_tune (mavlink_message_t * msg) inline virtual
Reimplemented in ToneAlarm_PX4.
Definition at line 21 of file NotifyDevice.h.
Referenced by AP_Notify::handle_play_tune().
virtual bool NotifyDevice::init (void) pure virtual
Implemented in Buzzer, OreoLED_PX4, ExternalLED, RGBLed, ToneAlarm_PX4_Solo, AP_BoardLED, ToneAlarm_PX4, ToneAlarm_Linux, and Display.
Referenced by AP_Notify::init(), and ~NotifyDevice().
virtual void NotifyDevice::update () pure virtual
Implemented in Buzzer, OreoLED_PX4, RGBLed, ExternalLED, ToneAlarm_PX4_Solo, AP_BoardLED, ToneAlarm_PX4, ToneAlarm_Linux, and Display.
Referenced by AP_Notify::update(), and ~NotifyDevice().
Member Data Documentation
const AP_Notify* NotifyDevice::pNotify
Definition at line 24 of file NotifyDevice.h.
Referenced by RGBLed::handle_led_control(), Display::init(), AP_Notify::init(), RGBLed::set_rgb(), ToneAlarm_Linux::update(), ToneAlarm_PX4::update(), RGBLed::update(), RGBLed::update_colours(), Display::update_mode(), and Display::update_text().
The documentation for this class was generated from the following file:
libraries/AP_Notify/NotifyDevice.h