APM:Libraries: Matrix3< T > Class Template Reference
Matrix3< T > Class Template Reference
#include <matrix3.h>
Public Member Functions
constexpr Matrix3 ()
constexpr Matrix3 (const Vector3< T > &a0, const Vector3< T > &b0, const Vector3< T > &c0)
constexpr Matrix3 (const T ax, const T ay, const T az, const T bx, const T by, const T bz, const T cx, const T cy, const T cz)
void operator() (const Vector3< T > &a0, const Vector3< T > &b0, const Vector3< T > &c0)
bool operator== (const Matrix3< T > &m)
bool operator!= (const Matrix3< T > &m)
Matrix3< T > operator- (void) const
Matrix3< T > operator+ (const Matrix3< T > &m) const
Matrix3< T > & operator+= (const Matrix3< T > &m)
Matrix3< T > operator- (const Matrix3< T > &m) const
Matrix3< T > & operator-= (const Matrix3< T > &m)
Matrix3< T > operator* (const T num) const
Matrix3< T > & operator*= (const T num)
Matrix3< T > operator/ (const T num) const
Matrix3< T > & operator/= (const T num)
Vector3< T > & operator[] (uint8_t i)
const Vector3< T > & operator[] (uint8_t i) const
Vector3< T > operator* (const Vector3< T > &v) const
Vector3< T > mul_transpose (const Vector3< T > &v) const
Vector2< T > mulXY (const Vector3< T > &v) const
Vector3< T > colx (void) const
Vector3< T > coly (void) const
Vector3< T > colz (void) const
Matrix3< T > operator* (const Matrix3< T > &m) const
Matrix3< T > & operator*= (const Matrix3< T > &m)
Matrix3< T > transposed (void) const
void transpose (void)
T det () const
bool inverse (Matrix3< T > &inv) const
bool invert ()
void zero (void)
void identity (void)
bool is_nan (void)
void from_euler (float roll, float pitch, float yaw)
void to_euler (float *roll, float *pitch, float *yaw) const
Vector3< T > to_euler312 () const
void from_euler312 (float roll, float pitch, float yaw)
void rotate (const Vector3< T > &g)
void from_axis_angle (const Vector3< T > &v, float theta)
void normalize (void)
Public Attributes
Vector3< T > a
Vector3< T > b
Vector3< T > c
Detailed Description
template<typename T>
class Matrix3< T >
Definition at line 44 of file matrix3.h.
Constructor & Destructor Documentation
template<typename T> constexpr Matrix3< T >::Matrix3 () inline
Definition at line 52 of file matrix3.h.
template<typename T> constexpr Matrix3< T >::Matrix3 (const Vector3< T > & a0, const Vector3< T > & b0, const Vector3< T > & c0) inline
Definition at line 55 of file matrix3.h.
template<typename T> constexpr Matrix3< T >::Matrix3 (const T ax, const T ay, const T az, const T bx, const T by, const T bz, const T cx, const T cy, const T cz) inline
Definition at line 61 of file matrix3.h.
Member Function Documentation
template<typename T> Vector3<T> Matrix3< T >::colx (void) const inline
Definition at line 157 of file matrix3.h.
Referenced by AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), and Vector3< T >::operator*().
template<typename T> Vector3<T> Matrix3< T >::coly (void) const inline
Definition at line 163 of file matrix3.h.
Referenced by Vector3< T >::operator*().
template<typename T> Vector3<T> Matrix3< T >::colz (void) const inline
Definition at line 169 of file matrix3.h.
Referenced by Vector3< T >::operator*().
template<typename T > template double Matrix3< T >::det () const
Calculate the determinant of this matrix.
Returns
The value of the determinant.
Definition at line 184 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), and Matrix3< float >::transpose().
template<typename T> void Matrix3< T >::from_axis_angle (const Vector3< T > & v, float theta)
Definition at line 235 of file matrix3.cpp.
Referenced by SITL::Calibration::_calibration_poses(), Matrix3< float >::is_nan(), and test_rotation_accuracy().
template<typename T > template void Matrix3< T >::from_euler (float roll, float pitch, float yaw)
Definition at line 26 of file matrix3.cpp.
Referenced by SITL::Calibration::_calibration_poses(), HALSITL::SITL_State::_ground_sonar(), Compass::_setup_earth_field(), HALSITL::SITL_State::_update_gps(), SITL::Aircraft::Aircraft(), AP_AHRS::AP_AHRS(), AP_AHRS_View::AP_AHRS_View(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcQuatAndFieldStates(), SITL::Motor::calculate_forces(), AP_AHRS_DCM::drift_correction_yaw(), SITL::FlightAxis::FlightAxis(), Matrix3< T >::from_axis_angle(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), SITL::Gimbal::Gimbal(), Matrix3< float >::is_nan(), loop(), missing_rotations(), SITL::XPlane::receive_data(), SITL::last_letter::recv_fdm(), SITL::CRRCSim::recv_fdm(), SITL::JSBSim::recv_fdm(), AP_AHRS_DCM::reset(), AP_AHRS_DCM::reset_attitude(), Compass::setHIL(), AP_Mount_Servo::stabilize(), test_conversion(), test_euler(), test_frame_transforms(), test_quaternion(), test_rotation_accuracy(), AP_OpticalFlow_SITL::update(), SITL::Gimbal::update(), SITL::Aircraft::update_dynamics(), SITL::Aircraft::update_mag_field_bf(), AP_AHRS_NavEKF::update_SITL(), and AP_AHRS::update_trig().
template<typename T > void Matrix3< T >::from_euler312 (float roll, float pitch, float yaw)
Definition at line 79 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), Quaternion::from_vector312(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), and Matrix3< float >::is_nan().
template<typename T> void Matrix3< T >::identity (void) inline
Definition at line 219 of file matrix3.h.
Referenced by SITL::Calibration::_calibration_poses(), AP_AHRS_DCM::AP_AHRS_DCM(), AP_AHRS_NavEKF::AP_AHRS_NavEKF(), AP_AHRS_View::AP_AHRS_View(), and test_matrix_rotate().
template<typename T> template bool Matrix3< T >::inverse (Matrix3< T > & inv) const
Calculate the inverse of this matrix.
Parameters
inv[in] Where to store the result.
Returns
If this matrix is invertible, then true is returned. Otherwise, inv is unmodified and false is returned.
Definition at line 192 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), TEST_P(), and Matrix3< float >::transpose().
template<typename T > template bool Matrix3< T >::invert ()
Invert this matrix if it is invertible.
Returns
Return true if this matrix could be successfully inverted and false otherwise.
Definition at line 214 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), and Matrix3< float >::transpose().
template<typename T> bool Matrix3< T >::is_nan (void) inline
Definition at line 227 of file matrix3.h.
Referenced by AP_AHRS_DCM::check_matrix(), and test_conversion().
template<typename T> template Vector3< double > Matrix3< T >::mul_transpose (const Vector3< T > & v) const
Definition at line 152 of file matrix3.cpp.
Referenced by AP_AHRS_DCM::drift_correction(), Matrix3< T >::from_axis_angle(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), Matrix3< float >::operator[](), Vector3< T >::rotate_inverse(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), NavEKF2_core::SelectVelPosFusion(), NavEKF3_core::SelectVelPosFusion(), Compass::setHIL(), AP_OpticalFlow_SITL::update(), AC_PrecLand_SITL::update(), NavEKF2_core::UpdateStrapdownEquationsNED(), and NavEKF3_core::UpdateStrapdownEquationsNED().
template<typename T> template Vector2< double > Matrix3< T >::mulXY (const Vector3< T > & v) const
Definition at line 144 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), Matrix3< float >::operator[](), and AP_AHRS_DCM::yaw_error_compass().
template<typename T > void Matrix3< T >::normalize (void)
Definition at line 122 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), Matrix3< float >::is_nan(), SITL::XPlane::receive_data(), SITL::Gimbal::update(), SITL::Tracker::update(), SITL::SimRover::update(), and SITL::Aircraft::update_dynamics().
template<typename T> bool Matrix3< T >::operator!= (const Matrix3< T > & m) inline
Definition at line 81 of file matrix3.h.
template<typename T> void Matrix3< T >::operator() (const Vector3< T > & a0, const Vector3< T > & b0, const Vector3< T > & c0) inline
Definition at line 69 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator* (const T num) const inline
Definition at line 113 of file matrix3.h.
Referenced by Matrix3< float >::colz(), Matrix3< T >::from_axis_angle(), and Matrix3< float >::operator[]().
template<typename T> Vector3< T > Matrix3< T >::operator* (const Vector3< T > & v) const
Definition at line 135 of file matrix3.cpp.
template<typename T> Matrix3< T > Matrix3< T >::operator* (const Matrix3< T > & m) const
Definition at line 161 of file matrix3.cpp.
template<typename T> Matrix3<T>& Matrix3< T >::operator*= (const T num) inline
Definition at line 117 of file matrix3.h.
template<typename T> Matrix3<T>& Matrix3< T >::operator*= (const Matrix3< T > & m) inline
Definition at line 177 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator+ (const Matrix3< T > & m) const inline
Definition at line 93 of file matrix3.h.
template<typename T> Matrix3<T>& Matrix3< T >::operator+= (const Matrix3< T > & m) inline
Definition at line 97 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator- (void) const inline
Definition at line 87 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator- (const Matrix3< T > & m) const inline
Definition at line 103 of file matrix3.h.
template<typename T> Matrix3<T>& Matrix3< T >::operator-= (const Matrix3< T > & m) inline
Definition at line 107 of file matrix3.h.
template<typename T> Matrix3<T> Matrix3< T >::operator/ (const T num) const inline
Definition at line 121 of file matrix3.h.
template<typename T> Matrix3<T>& Matrix3< T >::operator/= (const T num) inline
Definition at line 125 of file matrix3.h.
template<typename T> bool Matrix3< T >::operator== (const Matrix3< T > & m) inline
Definition at line 75 of file matrix3.h.
template<typename T> Vector3<T>& Matrix3< T >::operator[] (uint8_t i) inline
Definition at line 131 of file matrix3.h.
template<typename T> const Vector3<T>& Matrix3< T >::operator[] (uint8_t i) const inline
Definition at line 139 of file matrix3.h.
template<typename T> template void Matrix3< T >::rotate (const Vector3< T > & g)
Definition at line 102 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), Matrix3< float >::is_nan(), AP_AHRS_DCM::matrix_update(), SITL::XPlane::receive_data(), test_matrix_rotate(), test_rotation_accuracy(), SITL::Gimbal::update(), SITL::Tracker::update(), SITL::SimRover::update(), and SITL::Aircraft::update_dynamics().
template<typename T > template void Matrix3< T >::to_euler (float * roll, float * pitch, float * yaw) const
Definition at line 49 of file matrix3.cpp.
Referenced by AP_AHRS::calc_trig(), SITL::SITL::convert_earth_frame(), SITL::JSBSim::create_templates(), AP_AHRS_DCM::euler_angles(), SITL::Aircraft::fill_fdm(), Matrix3< T >::from_axis_angle(), Matrix3< float >::is_nan(), SITL::Aircraft::smooth_sensors(), AP_Mount_Servo::stabilize(), test_conversion(), test_euler(), test_quaternion(), test_rotation_accuracy(), SITL::Tracker::update(), AP_AHRS_View::update(), and SITL::Aircraft::update_dynamics().
template<typename T > Vector3< T > Matrix3< T >::to_euler312 () const
Definition at line 68 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), Matrix3< float >::is_nan(), Quaternion::to_vector312(), and SITL::Gimbal::update().
template<typename T> void Matrix3< T >::transpose (void) inline
Definition at line 185 of file matrix3.h.
Referenced by AP_Mount_Servo::stabilize(), AP_AHRS_View::update(), and SITL::FlightAxis::update().
template<typename T > template Matrix3< double > Matrix3< T >::transposed (void) const
Definition at line 176 of file matrix3.cpp.
Referenced by SoloGimbalEKF::alignHeading(), AP_AHRS::AP_AHRS(), SITL::Submarine::calculate_forces(), SITL::Frame::calculate_forces(), SITL::Plane::calculate_forces(), Matrix3< T >::from_axis_angle(), have_rotation(), Matrix3< float >::operator*=(), SITL::XPlane::receive_data(), Matrix3< float >::transpose(), SITL::Gimbal::update(), SITL::Tracker::update(), SITL::SimRover::update(), SITL::Balloon::update(), SITL::Helicopter::update(), SITL::SingleCopter::update(), SITL::FlightAxis::update(), SITL::Aircraft::update_dynamics(), SITL::Aircraft::update_mag_field_bf(), and AP_AHRS::update_trig().
template<typename T > template void Matrix3< T >::zero (void)
Definition at line 225 of file matrix3.cpp.
Referenced by Matrix3< T >::from_axis_angle(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), and Matrix3< float >::transpose().
Member Data Documentation
template<typename T> Vector3<T> Matrix3< T >::a
Definition at line 48 of file matrix3.h.
Referenced by AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), AP_AHRS::calc_trig(), Quaternion::from_rotation_matrix(), Matrix3< T >::inverse(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator!=(), Matrix3< T >::operator*(), Matrix3< float >::operator+(), Matrix3< float >::operator-(), Matrix3< float >::operator==(), Matrix3< float >::operator[](), Matrix3< T >::rotate(), Quaternion::rotation_matrix(), Quaternion::rotation_matrix_norm(), test_matrix_rotate(), and Airspeed_Calibration::update().
template<typename T> Vector3<T> Matrix3< T >::b
Definition at line 48 of file matrix3.h.
Referenced by AP_TECS::_update_throttle_with_airspeed(), AP_TECS::_update_throttle_without_airspeed(), AP_AHRS::calc_trig(), Quaternion::from_rotation_matrix(), Matrix3< T >::inverse(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator!=(), Matrix3< T >::operator*(), Matrix3< float >::operator+(), Matrix3< float >::operator-(), Matrix3< float >::operator==(), Matrix3< T >::rotate(), Quaternion::rotation_matrix(), Quaternion::rotation_matrix_norm(), test_matrix_rotate(), and Airspeed_Calibration::update().
template<typename T> Vector3<T> Matrix3< T >::c
Definition at line 48 of file matrix3.h.
Referenced by AP_AHRS::calc_trig(), Compass::calculate_heading(), AP_AHRS_DCM::check_matrix(), AP_AHRS_DCM::drift_correction_yaw(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), Quaternion::from_rotation_matrix(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), AP_AHRS::get_yaw_rate_earth(), Matrix3< T >::inverse(), AP_AHRS_DCM::normalize(), Matrix3< float >::operator!=(), Matrix3< T >::operator*(), Matrix3< float >::operator+(), Matrix3< float >::operator-(), Matrix3< float >::operator==(), Matrix3< T >::rotate(), Quaternion::rotation_matrix(), Quaternion::rotation_matrix_norm(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), NavEKF2_core::selectHeightForFusion(), NavEKF3_core::selectHeightForFusion(), test_matrix_rotate(), AP_OpticalFlow_SITL::update(), Airspeed_Calibration::update(), SITL::Balloon::update(), and AP_TECS::update_50hz().
The documentation for this class was generated from the following files:
libraries/AP_Math/matrix3.h
libraries/AP_Math/matrix3.cpp