APM:Libraries: AP_InertialSensor Class Reference
AP_InertialSensor Class Reference
#include <AP_InertialSensor.h>
Classes
struct PeakHoldState
Public Types
enum Gyro_Calibration_Timing { GYRO_CAL_NEVER = 0, GYRO_CAL_STARTUP_ONLY = 1 }
Public Member Functions
AP_InertialSensor ()
void init (uint16_t sample_rate_hz)
uint8_t register_gyro (uint16_t raw_sample_rate_hz, uint32_t id)
uint8_t register_accel (uint16_t raw_sample_rate_hz, uint32_t id)
bool calibrate_trim (float &trim_roll, float &trim_pitch)
bool calibrating () const
calibrating - returns true if the gyros or accels are currently being calibrated
void init_gyro (void)
const Vector3f & get_gyro (uint8_t i) const
const Vector3f & get_gyro (void) const
const Vector3f & get_gyro_offsets (uint8_t i) const
const Vector3f & get_gyro_offsets (void) const
bool get_delta_angle (uint8_t i, Vector3f &delta_angle) const
bool get_delta_angle (Vector3f &delta_angle) const
float get_delta_angle_dt (uint8_t i) const
float get_delta_angle_dt () const
bool get_delta_velocity (uint8_t i, Vector3f &delta_velocity) const
bool get_delta_velocity (Vector3f &delta_velocity) const
float get_delta_velocity_dt (uint8_t i) const
float get_delta_velocity_dt () const
const Vector3f & get_accel (uint8_t i) const
const Vector3f & get_accel (void) const
uint32_t get_gyro_error_count (uint8_t i) const
uint32_t get_accel_error_count (uint8_t i) const
bool get_gyro_health (uint8_t instance) const
bool get_gyro_health (void) const
bool get_gyro_health_all (void) const
uint8_t get_gyro_count (void) const
bool gyro_calibrated_ok (uint8_t instance) const
bool gyro_calibrated_ok_all () const
bool use_gyro (uint8_t instance) const
Gyro_Calibration_Timing gyro_calibration_timing ()
bool get_accel_health (uint8_t instance) const
bool get_accel_health (void) const
bool get_accel_health_all (void) const
uint8_t get_accel_count (void) const
bool accel_calibrated_ok_all () const
bool use_accel (uint8_t instance) const
const Vector3f & get_accel_offsets (uint8_t i) const
const Vector3f & get_accel_offsets (void) const
const Vector3f & get_accel_scale (uint8_t i) const
const Vector3f & get_accel_scale (void) const
const Vector3f & get_imu_pos_offset (uint8_t instance) const
const Vector3f & get_imu_pos_offset (void) const
float get_temperature (uint8_t instance) const
float get_delta_time () const
float get_gyro_drift_rate (void) const
void update (void)
void wait_for_sample (void)
void set_board_orientation (enum Rotation orientation)
uint16_t get_sample_rate (void) const
float get_loop_delta_t (void) const
uint16_t error_count (void) const
bool healthy (void) const
uint8_t get_primary_accel (void) const
uint8_t get_primary_gyro (void) const
void set_hil_mode (void)
uint8_t get_gyro_filter_hz (void) const
uint8_t get_accel_filter_hz (void) const
void set_dataflash (DataFlash_Class *dataflash)
void set_raw_logging (bool enable)
void calc_vibration_and_clipping (uint8_t instance, const Vector3f &accel, float dt)
Vector3f get_vibration_levels () const
Vector3f get_vibration_levels (uint8_t instance) const
uint32_t get_accel_clip_count (uint8_t instance) const
bool is_still ()
void set_accel (uint8_t instance, const Vector3f &accel)
void set_gyro (uint8_t instance, const Vector3f &gyro)
void set_delta_time (float delta_time)
void set_delta_velocity (uint8_t instance, float deltavt, const Vector3f &deltav)
void set_delta_angle (uint8_t instance, const Vector3f &deltaa, float deltaat)
AuxiliaryBus * get_auxiliary_bus (int16_t backend_id)
AuxiliaryBus * get_auxiliary_bus (int16_t backend_id, uint8_t instance)
void detect_backends (void)
void set_accel_peak_hold (uint8_t instance, const Vector3f &accel)
float get_accel_peak_hold_neg_x () const
AP_AccelCal * get_acal () const
bool get_fixed_mount_accel_cal_sample (uint8_t sample_num, Vector3f &ret) const
bool get_primary_accel_cal_sample_avg (uint8_t sample_num, Vector3f &ret) const
bool get_new_trim (float &trim_roll, float &trim_pitch)
void acal_init ()
void acal_update ()
bool accel_cal_requires_reboot () const
Static Public Member Functions
static AP_InertialSensor * get_instance ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
bool _add_backend (AP_InertialSensor_Backend *backend)
void _start_backends ()
AP_InertialSensor_Backend * _find_backend (int16_t backend_id, uint8_t instance)
void _init_gyro ()
bool _calculate_trim (const Vector3f &accel_sample, float &trim_roll, float &trim_pitch)
void _save_gyro_calibration ()
void _acal_save_calibrations ()
void _acal_event_failure ()
AccelCalibrator * _acal_get_calibrator (uint8_t i)
Private Attributes
AP_InertialSensor_Backend * _backends [INS_MAX_BACKENDS]
uint8_t _gyro_count
uint8_t _accel_count
uint8_t _backend_count
uint16_t _sample_rate
float _loop_delta_t
Vector3f _accel [INS_MAX_INSTANCES]
Vector3f _delta_velocity [INS_MAX_INSTANCES]
float _delta_velocity_dt [INS_MAX_INSTANCES]
bool _delta_velocity_valid [INS_MAX_INSTANCES]
Vector3f _delta_velocity_acc [INS_MAX_INSTANCES]
float _delta_velocity_acc_dt [INS_MAX_INSTANCES]
LowPassFilter2pVector3f _accel_filter [INS_MAX_INSTANCES]
LowPassFilter2pVector3f _gyro_filter [INS_MAX_INSTANCES]
Vector3f _accel_filtered [INS_MAX_INSTANCES]
Vector3f _gyro_filtered [INS_MAX_INSTANCES]
bool _new_accel_data [INS_MAX_INSTANCES]
bool _new_gyro_data [INS_MAX_INSTANCES]
Vector3f _gyro [INS_MAX_INSTANCES]
Vector3f _delta_angle [INS_MAX_INSTANCES]
float _delta_angle_dt [INS_MAX_INSTANCES]
bool _delta_angle_valid [INS_MAX_INSTANCES]
float _delta_angle_acc_dt [INS_MAX_INSTANCES]
Vector3f _delta_angle_acc [INS_MAX_INSTANCES]
Vector3f _last_delta_angle [INS_MAX_INSTANCES]
Vector3f _last_raw_gyro [INS_MAX_INSTANCES]
AP_Int16 _old_product_id
AP_Int32 _accel_id [INS_MAX_INSTANCES]
AP_Int32 _gyro_id [INS_MAX_INSTANCES]
AP_Vector3f _accel_scale [INS_MAX_INSTANCES]
AP_Vector3f _accel_offset [INS_MAX_INSTANCES]
AP_Vector3f _gyro_offset [INS_MAX_INSTANCES]
AP_Vector3f _accel_pos [INS_MAX_INSTANCES]
float _accel_max_abs_offsets [INS_MAX_INSTANCES]
uint16_t _accel_raw_sample_rates [INS_MAX_INSTANCES]
uint16_t _gyro_raw_sample_rates [INS_MAX_INSTANCES]
float _temperature [INS_MAX_INSTANCES]
AP_Int8 _accel_filter_cutoff
AP_Int8 _gyro_filter_cutoff
AP_Int8 _gyro_cal_timing
AP_Int8 _use [INS_MAX_INSTANCES]
AP_Int8 _fast_sampling_mask
enum Rotation _board_orientation
enum Rotation _gyro_orientation [INS_MAX_INSTANCES]
enum Rotation _accel_orientation [INS_MAX_INSTANCES]
bool _gyro_cal_ok [INS_MAX_INSTANCES]
bool _accel_id_ok [INS_MAX_INSTANCES]
uint8_t _primary_gyro
uint8_t _primary_accel
bool _have_sample:1
bool _hil_mode:1
bool _calibrating:1
bool _log_raw_data:1
bool _backends_detected:1
float _delta_time
uint32_t _last_sample_usec
uint32_t _next_sample_usec
uint32_t _sample_period_usec
bool _gyro_healthy [INS_MAX_INSTANCES]
bool _accel_healthy [INS_MAX_INSTANCES]
uint32_t _accel_error_count [INS_MAX_INSTANCES]
uint32_t _gyro_error_count [INS_MAX_INSTANCES]
uint32_t _accel_clip_count [INS_MAX_INSTANCES]
LowPassFilterVector3f _accel_vibe_floor_filter [INS_VIBRATION_CHECK_INSTANCES]
LowPassFilterVector3f _accel_vibe_filter [INS_VIBRATION_CHECK_INSTANCES]
struct AP_InertialSensor::PeakHoldState _peak_hold_state
AP_Float _still_threshold
struct {
float delta_time
} _hil
AP_Int8 _acc_body_aligned
AP_Int8 _trim_option
DataFlash_Class * _dataflash
AP_AccelCal * _acal
AccelCalibrator * _accel_calibrator
float _trim_pitch
float _trim_roll
bool _new_trim
bool _accel_cal_requires_reboot
uint32_t _accel_startup_error_count [INS_MAX_INSTANCES]
uint32_t _gyro_startup_error_count [INS_MAX_INSTANCES]
bool _startup_error_counts_set
uint32_t _startup_ms
Static Private Attributes
static AP_InertialSensor * _s_instance = nullptr
Friends
class AP_InertialSensor_Backend
Detailed Description
Definition at line 43 of file AP_InertialSensor.h.
Member Enumeration Documentation
enum AP_InertialSensor::Gyro_Calibration_Timing
Enumerator
GYRO_CAL_NEVER
GYRO_CAL_STARTUP_ONLY
Definition at line 52 of file AP_InertialSensor.h.
Constructor & Destructor Documentation
AP_InertialSensor::AP_InertialSensor ()
Definition at line 435 of file AP_InertialSensor.cpp.
Referenced by get_instance().
Member Function Documentation
void AP_InertialSensor::_acal_event_failure () private virtual
Reimplemented from AP_AccelCal_Client.
Definition at line 1674 of file AP_InertialSensor.cpp.
AccelCalibrator* AP_InertialSensor::_acal_get_calibrator (uint8_t i) inline private virtual
Implements AP_AccelCal_Client.
Definition at line 443 of file AP_InertialSensor.h.
void AP_InertialSensor::_acal_save_calibrations () private virtual
Implements AP_AccelCal_Client.
Definition at line 1610 of file AP_InertialSensor.cpp.
bool AP_InertialSensor::_add_backend (AP_InertialSensor_Backend * backend) private
Definition at line 645 of file AP_InertialSensor.cpp.
Referenced by accel_cal_requires_reboot(), and detect_backends().
bool AP_InertialSensor::_calculate_trim (const Vector3f & accel_sample, float & trim_roll, float & trim_pitch) private
Definition at line 815 of file AP_InertialSensor.cpp.
Referenced by accel_cal_requires_reboot(), and calibrate_trim().
AP_InertialSensor_Backend * AP_InertialSensor::_find_backend (int16_t backend_id, uint8_t instance) private
Definition at line 590 of file AP_InertialSensor.cpp.
Referenced by accel_cal_requires_reboot(), and get_auxiliary_bus().
void AP_InertialSensor::_init_gyro () private
Definition at line 1016 of file AP_InertialSensor.cpp.
Referenced by accel_cal_requires_reboot(), and init_gyro().
void AP_InertialSensor::_save_gyro_calibration () private
Definition at line 1155 of file AP_InertialSensor.cpp.
Referenced by accel_cal_requires_reboot(), and init_gyro().
void AP_InertialSensor::_start_backends () private
Definition at line 575 of file AP_InertialSensor.cpp.
Referenced by accel_cal_requires_reboot(), and init().
void AP_InertialSensor::acal_init ()
Definition at line 1582 of file AP_InertialSensor.cpp.
Referenced by get_acal().
void AP_InertialSensor::acal_update ()
Definition at line 1594 of file AP_InertialSensor.cpp.
Referenced by get_acal().
bool AP_InertialSensor::accel_cal_requires_reboot () const inline
Definition at line 258 of file AP_InertialSensor.h.
Referenced by AP_Arming::ins_checks().
bool AP_InertialSensor::accel_calibrated_ok_all () const
Definition at line 956 of file AP_InertialSensor.cpp.
Referenced by get_accel_count(), and AP_Arming::ins_checks().
void AP_InertialSensor::calc_vibration_and_clipping (uint8_t instance, const Vector3f & accel, float dt)
Definition at line 1518 of file AP_InertialSensor.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and set_raw_logging().
bool AP_InertialSensor::calibrate_trim (float & trim_roll, float & trim_pitch)
Definition at line 904 of file AP_InertialSensor.cpp.
bool AP_InertialSensor::calibrating () const inline
calibrating - returns true if the gyros or accels are currently being calibrated
Definition at line 75 of file AP_InertialSensor.h.
void AP_InertialSensor::detect_backends (void)
Definition at line 661 of file AP_InertialSensor.cpp.
Referenced by _start_backends(), get_auxiliary_bus(), and AP_Compass_AK8963::probe_mpu9250().
uint16_t AP_InertialSensor::error_count (void) const inline
Definition at line 185 of file AP_InertialSensor.h.
AP_AccelCal* AP_InertialSensor::get_acal () const inline
Definition at line 240 of file AP_InertialSensor.h.
const Vector3f& AP_InertialSensor::get_accel (uint8_t i) const inline
Fetch the current accelerometer values
Returns
vector of current accelerations in m/s/s
Definition at line 113 of file AP_InertialSensor.h.
Referenced by AP_AHRS_DCM::drift_correction(), AP_YawController::get_servo_out(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), AP_Arming::ins_checks(), DataFlash_Class::Log_Write_IMU(), AP_AHRS_DCM::reset(), run_test(), GCS_MAVLINK::send_raw_imu(), AP_TECS::update_50hz(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_EKF3().
const Vector3f& AP_InertialSensor::get_accel (void) const inline
Definition at line 114 of file AP_InertialSensor.h.
Referenced by _init_gyro(), calibrate_trim(), get_accel(), and get_delta_velocity().
uint32_t AP_InertialSensor::get_accel_clip_count (uint8_t instance) const
Definition at line 840 of file AP_InertialSensor.cpp.
Referenced by get_vibration_levels(), DataFlash_Class::Log_Write_Vibration(), and GCS_MAVLINK::send_vibration().
uint8_t AP_InertialSensor::get_accel_count (void) const inline
Definition at line 132 of file AP_InertialSensor.h.
Referenced by _acal_get_calibrator(), accel_calibrated_ok_all(), AP_AHRS_DCM::drift_correction(), get_accel_clip_count(), get_accel_health_all(), init(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), AP_Arming::ins_checks(), DataFlash_Class::Log_Write_IMU(), DataFlash_Class::Log_Write_IMUDT(), NavEKF2_core::readDeltaVelocity(), NavEKF3_core::readDeltaVelocity(), run_test(), GCS_MAVLINK::send_raw_imu(), setup(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_EKF3().
uint32_t AP_InertialSensor::get_accel_error_count (uint8_t i) const inline
Definition at line 117 of file AP_InertialSensor.h.
Referenced by DataFlash_Class::Log_Write_IMU().
uint8_t AP_InertialSensor::get_accel_filter_hz (void) const inline
Definition at line 198 of file AP_InertialSensor.h.
bool AP_InertialSensor::get_accel_health (uint8_t instance) const inline
Definition at line 129 of file AP_InertialSensor.h.
Referenced by AP_AHRS_DCM::drift_correction(), DataFlash_Class::Log_Write_IMU(), run_test(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_EKF3().
bool AP_InertialSensor::get_accel_health (void) const inline
Definition at line 130 of file AP_InertialSensor.h.
Referenced by calibrate_trim(), get_accel_health(), get_accel_health_all(), get_delta_velocity(), healthy(), and use_accel().
bool AP_InertialSensor::get_accel_health_all (void) const
Definition at line 888 of file AP_InertialSensor.cpp.
Referenced by get_accel_health(), and AP_Arming::ins_checks().
const Vector3f& AP_InertialSensor::get_accel_offsets (uint8_t i) const inline
Definition at line 137 of file AP_InertialSensor.h.
Referenced by display_offsets_and_scaling(), GCS_MAVLINK::send_sensor_offsets(), and AP_InertialSensor_SITL::timer_update().
const Vector3f& AP_InertialSensor::get_accel_offsets (void) const inline
Definition at line 138 of file AP_InertialSensor.h.
Referenced by get_accel_offsets().
float AP_InertialSensor::get_accel_peak_hold_neg_x () const inline
Definition at line 237 of file AP_InertialSensor.h.
const Vector3f& AP_InertialSensor::get_accel_scale (uint8_t i) const inline
Definition at line 141 of file AP_InertialSensor.h.
Referenced by display_offsets_and_scaling().
const Vector3f& AP_InertialSensor::get_accel_scale (void) const inline
Definition at line 142 of file AP_InertialSensor.h.
Referenced by get_accel_scale().
AuxiliaryBus* AP_InertialSensor::get_auxiliary_bus (int16_t backend_id) inline
Definition at line 230 of file AP_InertialSensor.h.
Referenced by AP_AK8963_BusDriver_Auxiliary::AP_AK8963_BusDriver_Auxiliary(), and get_auxiliary_bus().
AuxiliaryBus * AP_InertialSensor::get_auxiliary_bus (int16_t backend_id, uint8_t instance)
Definition at line 1505 of file AP_InertialSensor.cpp.
bool AP_InertialSensor::get_delta_angle (uint8_t i, Vector3f & delta_angle) const
Definition at line 1378 of file AP_InertialSensor.cpp.
Referenced by get_gyro_offsets(), DataFlash_Class::Log_Write_IMUDT(), AP_AHRS_DCM::matrix_update(), NavEKF2_core::readDeltaAngle(), and NavEKF3_core::readDeltaAngle().
bool AP_InertialSensor::get_delta_angle (Vector3f & delta_angle) const inline
Definition at line 97 of file AP_InertialSensor.h.
Referenced by get_delta_angle().
float AP_InertialSensor::get_delta_angle_dt (uint8_t i) const
Definition at line 1421 of file AP_InertialSensor.cpp.
Referenced by DataFlash_Class::Log_Write_IMUDT(), NavEKF2_core::readIMUData(), and NavEKF3_core::readIMUData().
float AP_InertialSensor::get_delta_angle_dt () const inline
Definition at line 100 of file AP_InertialSensor.h.
Referenced by get_delta_angle(), and get_delta_angle_dt().
float AP_InertialSensor::get_delta_time () const inline
Definition at line 159 of file AP_InertialSensor.h.
Referenced by get_delta_angle(), get_delta_angle_dt(), get_delta_velocity(), get_delta_velocity_dt(), DataFlash_Class::Log_Write_IMUDT(), and AP_AHRS_DCM::update().
bool AP_InertialSensor::get_delta_velocity (uint8_t i, Vector3f & delta_velocity) const
Definition at line 1395 of file AP_InertialSensor.cpp.
Referenced by AP_AHRS_DCM::drift_correction(), get_delta_angle_dt(), AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), AP_AHRS::getCorrectedDeltaVelocityNED(), DataFlash_Class::Log_Write_IMUDT(), NavEKF2_core::readDeltaVelocity(), and NavEKF3_core::readDeltaVelocity().
bool AP_InertialSensor::get_delta_velocity (Vector3f & delta_velocity) const inline
Definition at line 104 of file AP_InertialSensor.h.
Referenced by get_delta_velocity().
float AP_InertialSensor::get_delta_velocity_dt (uint8_t i) const
Definition at line 1410 of file AP_InertialSensor.cpp.
Referenced by AP_AHRS_DCM::drift_correction(), AP_AHRS_NavEKF::getCorrectedDeltaVelocityNED(), AP_AHRS::getCorrectedDeltaVelocityNED(), DataFlash_Class::Log_Write_IMUDT(), NavEKF2_core::readDeltaVelocity(), and NavEKF3_core::readDeltaVelocity().
float AP_InertialSensor::get_delta_velocity_dt () const inline
Definition at line 107 of file AP_InertialSensor.h.
Referenced by get_delta_velocity(), and get_delta_velocity_dt().
bool AP_InertialSensor::get_fixed_mount_accel_cal_sample (uint8_t sample_num, Vector3f & ret) const
Definition at line 1699 of file AP_InertialSensor.cpp.
Referenced by _acal_save_calibrations(), and get_acal().
const Vector3f& AP_InertialSensor::get_gyro (uint8_t i) const inline
Fetch the current gyro values
Returns
vector of rotational rates in radians/sec
Definition at line 88 of file AP_InertialSensor.h.
Referenced by NavEKF2_core::detectOptFlowTakeoff(), NavEKF3_core::detectOptFlowTakeoff(), AP_AHRS::get_gyro_latest(), AP_Arming::ins_checks(), DataFlash_Class::Log_Write_IMU(), run_test(), GCS_MAVLINK::send_raw_imu(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_EKF3().
const Vector3f& AP_InertialSensor::get_gyro (void) const inline
Definition at line 89 of file AP_InertialSensor.h.
Referenced by _init_gyro(), get_delta_angle(), and get_gyro().
uint8_t AP_InertialSensor::get_gyro_count (void) const inline
Definition at line 123 of file AP_InertialSensor.h.
Referenced by _init_gyro(), get_gyro_health_all(), gyro_calibrated_ok_all(), AP_Arming::ins_checks(), DataFlash_Class::Log_Write_IMU(), DataFlash_Class::Log_Write_IMUDT(), AP_AHRS_DCM::matrix_update(), NavEKF2_core::readDeltaAngle(), NavEKF3_core::readDeltaAngle(), run_test(), GCS_MAVLINK::send_raw_imu(), and setup().
float AP_InertialSensor::get_gyro_drift_rate (void) const inline
Definition at line 163 of file AP_InertialSensor.h.
Referenced by AP_AHRS::AP_AHRS().
uint32_t AP_InertialSensor::get_gyro_error_count (uint8_t i) const inline
Definition at line 116 of file AP_InertialSensor.h.
Referenced by DataFlash_Class::Log_Write_IMU().
uint8_t AP_InertialSensor::get_gyro_filter_hz (void) const inline
Definition at line 195 of file AP_InertialSensor.h.
bool AP_InertialSensor::get_gyro_health (uint8_t instance) const inline
Definition at line 120 of file AP_InertialSensor.h.
Referenced by NavEKF2_core::detectOptFlowTakeoff(), NavEKF3_core::detectOptFlowTakeoff(), DataFlash_Class::Log_Write_IMU(), AP_AHRS_DCM::matrix_update(), and run_test().
bool AP_InertialSensor::get_gyro_health (void) const inline
Definition at line 121 of file AP_InertialSensor.h.
Referenced by get_delta_angle(), get_gyro_health(), get_gyro_health_all(), healthy(), and use_gyro().
bool AP_InertialSensor::get_gyro_health_all (void) const
Definition at line 849 of file AP_InertialSensor.cpp.
Referenced by get_gyro_health(), and AP_Arming::ins_checks().
const Vector3f& AP_InertialSensor::get_gyro_offsets (uint8_t i) const inline
Definition at line 92 of file AP_InertialSensor.h.
Referenced by display_offsets_and_scaling(), GCS_MAVLINK::send_sensor_offsets(), and AP_InertialSensor_SITL::timer_update().
const Vector3f& AP_InertialSensor::get_gyro_offsets (void) const inline
Definition at line 93 of file AP_InertialSensor.h.
Referenced by get_gyro_offsets().
const Vector3f& AP_InertialSensor::get_imu_pos_offset (uint8_t instance) const inline
Definition at line 145 of file AP_InertialSensor.h.
Referenced by AC_PrecLand::construct_pos_meas_using_rangefinder(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), and AC_PrecLand::run_output_prediction().
const Vector3f& AP_InertialSensor::get_imu_pos_offset (void) const inline
Definition at line 148 of file AP_InertialSensor.h.
AP_InertialSensor * AP_InertialSensor::get_instance () static
Definition at line 496 of file AP_InertialSensor.cpp.
Referenced by AP_Compass_AK8963::probe_mpu9250().
float AP_InertialSensor::get_loop_delta_t (void) const inline
Definition at line 183 of file AP_InertialSensor.h.
Referenced by NavEKF2_core::InitialiseFilterBootstrap(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), NavEKF2_core::readIMUData(), and NavEKF3_core::readIMUData().
bool AP_InertialSensor::get_new_trim (float & trim_roll, float & trim_pitch)
Definition at line 1685 of file AP_InertialSensor.cpp.
Referenced by get_acal().
uint8_t AP_InertialSensor::get_primary_accel (void) const inline
Definition at line 188 of file AP_InertialSensor.h.
Referenced by AP_AHRS_DCM::drift_correction(), AP_AHRS::get_accel_ef(), AP_AHRS::get_primary_accel_index(), AP_AHRS_NavEKF::get_primary_accel_index(), AP_AHRS_NavEKF::get_primary_IMU_index(), NavEKF2_core::readIMUData(), NavEKF3_core::readIMUData(), AP_AHRS_NavEKF::update_EKF2(), and AP_AHRS_NavEKF::update_EKF3().
bool AP_InertialSensor::get_primary_accel_cal_sample_avg (uint8_t sample_num, Vector3f & ret) const
Definition at line 1712 of file AP_InertialSensor.cpp.
Referenced by _acal_save_calibrations(), and get_acal().
uint8_t AP_InertialSensor::get_primary_gyro (void) const inline
Definition at line 189 of file AP_InertialSensor.h.
Referenced by AP_AHRS::get_primary_gyro_index(), AP_AHRS_NavEKF::get_primary_gyro_index(), NavEKF2_core::readIMUData(), and NavEKF3_core::readIMUData().
uint16_t AP_InertialSensor::get_sample_rate (void) const inline
Definition at line 180 of file AP_InertialSensor.h.
Referenced by calibrate_trim(), NavEKF2_core::setup_core(), NavEKF3_core::setup_core(), NavEKF3::UpdateFilter(), and NavEKF2::UpdateFilter().
float AP_InertialSensor::get_temperature (uint8_t instance) const inline
Definition at line 154 of file AP_InertialSensor.h.
Referenced by DataFlash_Class::Log_Write_IMU().
Vector3f AP_InertialSensor::get_vibration_levels () const inline
Definition at line 210 of file AP_InertialSensor.h.
Referenced by get_vibration_levels(), is_still(), DataFlash_Class::Log_Write_Vibration(), and GCS_MAVLINK::send_vibration().
Vector3f AP_InertialSensor::get_vibration_levels (uint8_t instance) const
Definition at line 1559 of file AP_InertialSensor.cpp.
bool AP_InertialSensor::gyro_calibrated_ok (uint8_t instance) const inline
Definition at line 124 of file AP_InertialSensor.h.
Referenced by gyro_calibrated_ok_all().
bool AP_InertialSensor::gyro_calibrated_ok_all () const
Definition at line 861 of file AP_InertialSensor.cpp.
Referenced by gyro_calibrated_ok(), and AP_Arming::ins_checks().
Gyro_Calibration_Timing AP_InertialSensor::gyro_calibration_timing () inline
Definition at line 127 of file AP_InertialSensor.h.
Referenced by init().
bool AP_InertialSensor::healthy (void) const inline
Definition at line 186 of file AP_InertialSensor.h.
Referenced by AP_AHRS_DCM::drift_correction().
void AP_InertialSensor::init (uint16_t sample_rate_hz)
Perform startup initialisation.
Called to initialise the state of the IMU.
Gyros will be calibrated unless INS_GYRO_CAL is zero
Parameters
style The initialisation startup style.
Definition at line 613 of file AP_InertialSensor.cpp.
Referenced by SchedTest::setup(), and setup().
void AP_InertialSensor::init_gyro (void)
Perform cold-start initialisation for just the gyros.
Note
This should not be called unless ::init has previously been called, as ::init may perform other work
Definition at line 831 of file AP_InertialSensor.cpp.
Referenced by calibrating(), and init().
bool AP_InertialSensor::is_still ()
Definition at line 1572 of file AP_InertialSensor.cpp.
Referenced by get_vibration_levels().
uint8_t AP_InertialSensor::register_accel (uint16_t raw_sample_rate_hz, uint32_t id)
Definition at line 539 of file AP_InertialSensor.cpp.
Referenced by AP_InertialSensor_HIL::_init_sensor(), AP_InertialSensor_PX4::_init_sensor(), AP_InertialSensor_SITL::init_sensor(), AP_InertialSensor_QFLIGHT::init_sensor(), AP_InertialSensor_QURT::init_sensor(), AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_L3G4200D::start(), AP_InertialSensor_BMI160::start(), and AP_InertialSensor_Invensense::start().
uint8_t AP_InertialSensor::register_gyro (uint16_t raw_sample_rate_hz, uint32_t id)
Register a new gyro/accel driver, allocating an instance number
Definition at line 507 of file AP_InertialSensor.cpp.
Referenced by AP_InertialSensor_HIL::_init_sensor(), AP_InertialSensor_PX4::_init_sensor(), AP_InertialSensor_SITL::init_sensor(), AP_InertialSensor_QFLIGHT::init_sensor(), AP_InertialSensor_QURT::init_sensor(), AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_L3G4200D::start(), AP_InertialSensor_BMI160::start(), and AP_InertialSensor_Invensense::start().
void AP_InertialSensor::set_accel (uint8_t instance, const Vector3f & accel)
Definition at line 1433 of file AP_InertialSensor.cpp.
Referenced by get_vibration_levels().
void AP_InertialSensor::set_accel_peak_hold (uint8_t instance, const Vector3f & accel)
Definition at line 1542 of file AP_InertialSensor.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and get_auxiliary_bus().
void AP_InertialSensor::set_board_orientation (enum Rotation orientation) inline
Definition at line 175 of file AP_InertialSensor.h.
Referenced by AP_AHRS::set_orientation().
void AP_InertialSensor::set_dataflash (DataFlash_Class * dataflash) inline
Definition at line 201 of file AP_InertialSensor.h.
void AP_InertialSensor::set_delta_angle (uint8_t instance, const Vector3f & deltaa, float deltaat)
Definition at line 1493 of file AP_InertialSensor.cpp.
Referenced by get_vibration_levels().
void AP_InertialSensor::set_delta_time (float delta_time)
Definition at line 1473 of file AP_InertialSensor.cpp.
Referenced by get_vibration_levels().
void AP_InertialSensor::set_delta_velocity (uint8_t instance, float deltavt, const Vector3f & deltav)
Definition at line 1481 of file AP_InertialSensor.cpp.
Referenced by get_vibration_levels().
void AP_InertialSensor::set_gyro (uint8_t instance, const Vector3f & gyro)
Definition at line 1451 of file AP_InertialSensor.cpp.
Referenced by get_vibration_levels().
void AP_InertialSensor::set_hil_mode (void) inline
Definition at line 192 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_HIL::_init_sensor().
void AP_InertialSensor::set_raw_logging (bool enable) inline
Definition at line 204 of file AP_InertialSensor.h.
void AP_InertialSensor::update (void)
Definition at line 1171 of file AP_InertialSensor.cpp.
Referenced by _init_gyro(), calibrate_trim(), get_gyro_drift_rate(), SchedTest::ins_update(), AP_AHRS_DCM::reset(), run_test(), and AP_AHRS_DCM::update().
bool AP_InertialSensor::use_accel (uint8_t instance) const
Definition at line 1006 of file AP_InertialSensor.cpp.
Referenced by AP_AHRS_DCM::drift_correction(), get_accel_count(), AP_Arming::ins_checks(), NavEKF2_core::readIMUData(), and NavEKF3_core::readIMUData().
bool AP_InertialSensor::use_gyro (uint8_t instance) const
Definition at line 878 of file AP_InertialSensor.cpp.
Referenced by gyro_calibrated_ok(), AP_Arming::ins_checks(), DataFlash_Class::Log_Write_IMUDT(), NavEKF2_core::readIMUData(), and NavEKF3_core::readIMUData().
void AP_InertialSensor::wait_for_sample (void)
Definition at line 1276 of file AP_InertialSensor.cpp.
Referenced by calibrate_trim(), get_gyro_drift_rate(), SchedTest::loop(), AP_AHRS_DCM::reset(), run_test(), and update().
Friends And Related Function Documentation
friend class AP_InertialSensor_Backend friend
Definition at line 45 of file AP_InertialSensor.h.
Member Data Documentation
AP_AccelCal* AP_InertialSensor::_acal private
Definition at line 434 of file AP_InertialSensor.h.
Referenced by acal_init(), acal_update(), and get_acal().
AP_Int8 AP_InertialSensor::_acc_body_aligned private
Definition at line 428 of file AP_InertialSensor.h.
Referenced by get_fixed_mount_accel_cal_sample().
Vector3f AP_InertialSensor::_accel[INS_MAX_INSTANCES] private
Definition at line 293 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_accel(), and set_accel().
bool AP_InertialSensor::_accel_cal_requires_reboot private
Definition at line 449 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), and accel_cal_requires_reboot().
AccelCalibrator* AP_InertialSensor::_accel_calibrator private
Definition at line 436 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), AP_InertialSensor_Backend::_publish_accel(), acal_init(), get_fixed_mount_accel_cal_sample(), and get_primary_accel_cal_sample_avg().
uint32_t AP_InertialSensor::_accel_clip_count[INS_MAX_INSTANCES] private
Definition at line 407 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), calc_vibration_and_clipping(), get_accel_clip_count(), and AP_InertialSensor_Backend::increment_clip_count().
uint8_t AP_InertialSensor::_accel_count private
Definition at line 285 of file AP_InertialSensor.h.
Referenced by _acal_event_failure(), _acal_save_calibrations(), _start_backends(), get_accel_count(), get_accel_health(), get_fixed_mount_accel_cal_sample(), get_primary_accel_cal_sample_avg(), init(), register_accel(), and set_accel().
uint32_t AP_InertialSensor::_accel_error_count[INS_MAX_INSTANCES] private
Definition at line 403 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_inc_accel_error_count(), AP_InertialSensor_Backend::_set_accel_error_count(), AP_InertialSensor(), get_accel_error_count(), and update().
LowPassFilter2pVector3f AP_InertialSensor::_accel_filter[INS_MAX_INSTANCES] private
Definition at line 303 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and AP_InertialSensor_Backend::update_accel().
AP_Int8 AP_InertialSensor::_accel_filter_cutoff private
Definition at line 348 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_accel_filter_cutoff(), and get_accel_filter_hz().
Vector3f AP_InertialSensor::_accel_filtered[INS_MAX_INSTANCES] private
Definition at line 305 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), and AP_InertialSensor_Backend::update_accel().
bool AP_InertialSensor::_accel_healthy[INS_MAX_INSTANCES] private
Definition at line 401 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_accel_health(), set_accel(), set_gyro(), and update().
AP_Int32 AP_InertialSensor::_accel_id[INS_MAX_INSTANCES] private
Definition at line 326 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), accel_calibrated_ok_all(), and register_accel().
bool AP_InertialSensor::_accel_id_ok[INS_MAX_INSTANCES] private
Definition at line 367 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), accel_calibrated_ok_all(), and register_accel().
float AP_InertialSensor::_accel_max_abs_offsets[INS_MAX_INSTANCES] private
Definition at line 338 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_set_accel_max_abs_offset(), and AP_InertialSensor().
AP_Vector3f AP_InertialSensor::_accel_offset[INS_MAX_INSTANCES] private
Definition at line 331 of file AP_InertialSensor.h.
Referenced by _acal_event_failure(), _acal_save_calibrations(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor_Backend::_rotate_and_correct_accel(), accel_calibrated_ok_all(), and get_accel_offsets().
enum Rotation AP_InertialSensor::_accel_orientation[INS_MAX_INSTANCES] private
Definition at line 363 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_rotate_and_correct_accel(), and AP_InertialSensor_Backend::set_accel_orientation().
AP_Vector3f AP_InertialSensor::_accel_pos[INS_MAX_INSTANCES] private
Definition at line 335 of file AP_InertialSensor.h.
Referenced by get_imu_pos_offset().
uint16_t AP_InertialSensor::_accel_raw_sample_rates[INS_MAX_INSTANCES] private
Definition at line 341 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_accel_raw_sample_rate(), AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor(), and register_accel().
AP_Vector3f AP_InertialSensor::_accel_scale[INS_MAX_INSTANCES] private
Definition at line 330 of file AP_InertialSensor.h.
Referenced by _acal_event_failure(), _acal_save_calibrations(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor_Backend::_rotate_and_correct_accel(), accel_calibrated_ok_all(), get_accel_scale(), and init().
uint32_t AP_InertialSensor::_accel_startup_error_count[INS_MAX_INSTANCES] private
Definition at line 452 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), and update().
LowPassFilterVector3f AP_InertialSensor::_accel_vibe_filter[INS_VIBRATION_CHECK_INSTANCES] private
Definition at line 409 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), calc_vibration_and_clipping(), and get_vibration_levels().
LowPassFilterVector3f AP_InertialSensor::_accel_vibe_floor_filter[INS_VIBRATION_CHECK_INSTANCES] private
Definition at line 408 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), and calc_vibration_and_clipping().
uint8_t AP_InertialSensor::_backend_count private
Definition at line 286 of file AP_InertialSensor.h.
Referenced by _add_backend(), _find_backend(), _start_backends(), detect_backends(), update(), and wait_for_sample().
AP_InertialSensor_Backend* AP_InertialSensor::_backends[INS_MAX_BACKENDS] private
Definition at line 279 of file AP_InertialSensor.h.
Referenced by _add_backend(), _find_backend(), _start_backends(), AP_InertialSensor(), update(), and wait_for_sample().
bool AP_InertialSensor::_backends_detected private
Definition at line 385 of file AP_InertialSensor.h.
Referenced by _find_backend(), and detect_backends().
enum Rotation AP_InertialSensor::_board_orientation private
Definition at line 359 of file AP_InertialSensor.h.
Referenced by _init_gyro(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor_Backend::_rotate_and_correct_accel(), AP_InertialSensor_Backend::_rotate_and_correct_gyro(), get_fixed_mount_accel_cal_sample(), get_primary_accel_cal_sample_avg(), and set_board_orientation().
bool AP_InertialSensor::_calibrating private
Definition at line 380 of file AP_InertialSensor.h.
Referenced by _init_gyro(), calibrate_trim(), and calibrating().
DataFlash_Class* AP_InertialSensor::_dataflash private
Definition at line 431 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::get_dataflash(), and set_dataflash().
Vector3f AP_InertialSensor::_delta_angle[INS_MAX_INSTANCES] private
Definition at line 312 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_delta_angle(), and set_delta_angle().
Vector3f AP_InertialSensor::_delta_angle_acc[INS_MAX_INSTANCES] private
Definition at line 317 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_publish_gyro(), AP_InertialSensor(), and update().
float AP_InertialSensor::_delta_angle_acc_dt[INS_MAX_INSTANCES] private
Definition at line 316 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_publish_gyro(), AP_InertialSensor(), and update().
float AP_InertialSensor::_delta_angle_dt[INS_MAX_INSTANCES] private
Definition at line 313 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_delta_angle_dt(), and set_delta_angle().
bool AP_InertialSensor::_delta_angle_valid[INS_MAX_INSTANCES] private
Definition at line 314 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), AP_InertialSensor(), get_delta_angle(), get_delta_angle_dt(), set_delta_angle(), and update().
float AP_InertialSensor::_delta_time private
Definition at line 388 of file AP_InertialSensor.h.
Referenced by get_delta_time(), init(), and wait_for_sample().
Vector3f AP_InertialSensor::_delta_velocity[INS_MAX_INSTANCES] private
Definition at line 294 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_delta_velocity(), and set_delta_velocity().
Vector3f AP_InertialSensor::_delta_velocity_acc[INS_MAX_INSTANCES] private
Definition at line 298 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor(), and update().
float AP_InertialSensor::_delta_velocity_acc_dt[INS_MAX_INSTANCES] private
Definition at line 300 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor(), and update().
float AP_InertialSensor::_delta_velocity_dt[INS_MAX_INSTANCES] private
Definition at line 295 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), get_delta_velocity_dt(), and set_delta_velocity().
bool AP_InertialSensor::_delta_velocity_valid[INS_MAX_INSTANCES] private
Definition at line 296 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_accel(), AP_InertialSensor(), get_delta_velocity(), get_delta_velocity_dt(), set_delta_velocity(), and update().
AP_Int8 AP_InertialSensor::_fast_sampling_mask private
Definition at line 356 of file AP_InertialSensor.h.
Referenced by detect_backends(), and AP_InertialSensor_Backend::enable_fast_sampling().
Vector3f AP_InertialSensor::_gyro[INS_MAX_INSTANCES] private
Definition at line 311 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_gyro(), and set_gyro().
bool AP_InertialSensor::_gyro_cal_ok[INS_MAX_INSTANCES] private
Definition at line 366 of file AP_InertialSensor.h.
Referenced by _init_gyro(), AP_InertialSensor(), gyro_calibrated_ok(), register_gyro(), and set_gyro().
AP_Int8 AP_InertialSensor::_gyro_cal_timing private
Definition at line 350 of file AP_InertialSensor.h.
Referenced by gyro_calibration_timing().
uint8_t AP_InertialSensor::_gyro_count private
Definition at line 284 of file AP_InertialSensor.h.
Referenced by _save_gyro_calibration(), _start_backends(), get_gyro_count(), get_gyro_health(), init(), register_gyro(), and set_gyro().
uint32_t AP_InertialSensor::_gyro_error_count[INS_MAX_INSTANCES] private
Definition at line 404 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_inc_gyro_error_count(), AP_InertialSensor_Backend::_set_gyro_error_count(), AP_InertialSensor(), get_gyro_error_count(), and update().
LowPassFilter2pVector3f AP_InertialSensor::_gyro_filter[INS_MAX_INSTANCES] private
Definition at line 304 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor_Backend::update_gyro().
AP_Int8 AP_InertialSensor::_gyro_filter_cutoff private
Definition at line 349 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_gyro_filter_cutoff(), and get_gyro_filter_hz().
Vector3f AP_InertialSensor::_gyro_filtered[INS_MAX_INSTANCES] private
Definition at line 306 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor_Backend::update_gyro().
bool AP_InertialSensor::_gyro_healthy[INS_MAX_INSTANCES] private
Definition at line 400 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_gyro(), get_gyro_health(), set_gyro(), and update().
AP_Int32 AP_InertialSensor::_gyro_id[INS_MAX_INSTANCES] private
Definition at line 327 of file AP_InertialSensor.h.
Referenced by _save_gyro_calibration(), gyro_calibrated_ok_all(), and register_gyro().
AP_Vector3f AP_InertialSensor::_gyro_offset[INS_MAX_INSTANCES] private
Definition at line 332 of file AP_InertialSensor.h.
Referenced by _init_gyro(), AP_InertialSensor_Backend::_rotate_and_correct_gyro(), _save_gyro_calibration(), and get_gyro_offsets().
enum Rotation AP_InertialSensor::_gyro_orientation[INS_MAX_INSTANCES] private
Definition at line 362 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_rotate_and_correct_gyro(), and AP_InertialSensor_Backend::set_gyro_orientation().
uint16_t AP_InertialSensor::_gyro_raw_sample_rates[INS_MAX_INSTANCES] private
Definition at line 342 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_gyro_raw_sample_rate(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::_publish_gyro(), AP_InertialSensor(), and register_gyro().
uint32_t AP_InertialSensor::_gyro_startup_error_count[INS_MAX_INSTANCES] private
Definition at line 453 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), and update().
bool AP_InertialSensor::_have_sample private
Definition at line 374 of file AP_InertialSensor.h.
Referenced by init(), update(), and wait_for_sample().
struct { ... } AP_InertialSensor::_hil
Referenced by set_delta_time(), and wait_for_sample().
bool AP_InertialSensor::_hil_mode private
Definition at line 377 of file AP_InertialSensor.h.
Referenced by accel_calibrated_ok_all(), detect_backends(), set_hil_mode(), update(), and wait_for_sample().
Vector3f AP_InertialSensor::_last_delta_angle[INS_MAX_INSTANCES] private
Definition at line 318 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor().
Vector3f AP_InertialSensor::_last_raw_gyro[INS_MAX_INSTANCES] private
Definition at line 319 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), and AP_InertialSensor().
uint32_t AP_InertialSensor::_last_sample_usec private
Definition at line 391 of file AP_InertialSensor.h.
Referenced by init(), and wait_for_sample().
bool AP_InertialSensor::_log_raw_data private
Definition at line 383 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::get_dataflash(), and set_raw_logging().
float AP_InertialSensor::_loop_delta_t private
Definition at line 290 of file AP_InertialSensor.h.
Referenced by get_loop_delta_t(), and init().
bool AP_InertialSensor::_new_accel_data[INS_MAX_INSTANCES] private
Definition at line 307 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::update_accel(), and wait_for_sample().
bool AP_InertialSensor::_new_gyro_data[INS_MAX_INSTANCES] private
Definition at line 308 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), AP_InertialSensor_Backend::update_gyro(), and wait_for_sample().
bool AP_InertialSensor::_new_trim private
Definition at line 447 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), and get_new_trim().
uint32_t AP_InertialSensor::_next_sample_usec private
Definition at line 394 of file AP_InertialSensor.h.
Referenced by init(), and wait_for_sample().
AP_Int16 AP_InertialSensor::_old_product_id private
Definition at line 322 of file AP_InertialSensor.h.
struct AP_InertialSensor::PeakHoldState AP_InertialSensor::_peak_hold_state private
Referenced by get_accel_peak_hold_neg_x(), and set_accel_peak_hold().
uint8_t AP_InertialSensor::_primary_accel private
Definition at line 371 of file AP_InertialSensor.h.
Referenced by get_accel(), get_accel_health(), get_accel_offsets(), get_accel_scale(), get_delta_angle_dt(), get_delta_velocity(), get_delta_velocity_dt(), get_imu_pos_offset(), get_primary_accel(), get_vibration_levels(), set_accel(), set_accel_peak_hold(), set_gyro(), and update().
uint8_t AP_InertialSensor::_primary_gyro private
Definition at line 370 of file AP_InertialSensor.h.
Referenced by get_delta_angle(), get_gyro(), get_gyro_health(), get_gyro_offsets(), get_primary_gyro(), and update().
AP_InertialSensor * AP_InertialSensor::_s_instance = nullptr static private
Definition at line 433 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor(), and get_instance().
uint32_t AP_InertialSensor::_sample_period_usec private
Definition at line 397 of file AP_InertialSensor.h.
Referenced by init(), and wait_for_sample().
uint16_t AP_InertialSensor::_sample_rate private
Definition at line 289 of file AP_InertialSensor.h.
Referenced by get_sample_rate(), AP_InertialSensor_Backend::get_sample_rate_hz(), and init().
bool AP_InertialSensor::_startup_error_counts_set private
Definition at line 454 of file AP_InertialSensor.h.
Referenced by update().
uint32_t AP_InertialSensor::_startup_ms private
Definition at line 455 of file AP_InertialSensor.h.
Referenced by update().
AP_Float AP_InertialSensor::_still_threshold private
Definition at line 418 of file AP_InertialSensor.h.
Referenced by is_still().
float AP_InertialSensor::_temperature[INS_MAX_INSTANCES] private
Definition at line 345 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor_Backend::_publish_temperature(), and get_temperature().
AP_Int8 AP_InertialSensor::_trim_option private
Definition at line 429 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations().
float AP_InertialSensor::_trim_pitch private
Definition at line 445 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), and get_new_trim().
float AP_InertialSensor::_trim_roll private
Definition at line 446 of file AP_InertialSensor.h.
Referenced by _acal_save_calibrations(), and get_new_trim().
AP_Int8 AP_InertialSensor::_use[INS_MAX_INSTANCES] private
Definition at line 353 of file AP_InertialSensor.h.
Referenced by update(), use_accel(), and use_gyro().
float AP_InertialSensor::delta_time
Definition at line 424 of file AP_InertialSensor.h.
Referenced by get_vibration_levels(), and set_delta_time().
const AP_Param::GroupInfo AP_InertialSensor::var_info static
Definition at line 172 of file AP_InertialSensor.h.
Referenced by AP_InertialSensor().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor.h
libraries/AP_InertialSensor/AP_InertialSensor.cpp