APM:Libraries: AP_HAL::Semaphore Class Reference
AP_HAL::Semaphore Class Reference abstract
#include <Semaphores.h>
Public Member Functions
virtual bool take (uint32_t timeout_ms) WARN_IF_UNUSED=0
virtual bool take_nonblocking () WARN_IF_UNUSED=0
virtual bool give ()=0
virtual ~Semaphore (void)
Detailed Description
Definition at line 7 of file Semaphores.h.
Constructor & Destructor Documentation
virtual AP_HAL::Semaphore::~Semaphore (void) inline virtual
Definition at line 12 of file Semaphores.h.
Member Function Documentation
virtual bool AP_HAL::Semaphore::give () pure virtual
Implemented in Linux::Semaphore, PX4::Semaphore, QURT::Semaphore, HALSITL::Semaphore, VRBRAIN::Semaphore, and Empty::Semaphore.
Referenced by AP_Baro_BMP085::_calculate(), Linux::RCOutput_Bebop::_clear_error(), AP_Airspeed_MS4525::_collect(), Linux::RCOutput_Bebop::_get_info(), AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_Baro_BMP280::_init(), AP_RangeFinder_MaxsonarI2CXL::_init(), AP_Baro_MS56XX::_init(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), Linux::RCOutput_Bebop::_play_sound(), Linux::SPIUARTDriver::_read_fd(), Linux::RCOutput_Bebop::_set_ref_speed(), Linux::RCOutput_Bebop::_start_prop(), Linux::RCOutput_Bebop::_stop_prop(), Display_SH1106_I2C::_timer(), Display_SSD1306_I2C::_timer(), AP_RangeFinder_MaxsonarI2CXL::_timer(), AP_Baro_MS56XX::_timer(), Linux::RCOutput_Bebop::_toggle_gpio(), AP_Compass_LSM9DS1::_update(), AP_Compass_LSM303D::_update(), AP_Compass_BMM150::_update(), AP_Compass_AK8963::_update(), AP_Baro_BMP280::_update_pressure(), AP_Baro_BMP280::_update_temperature(), AP_Compass_AK8963::_update_timer(), Linux::SPIUARTDriver::_write_fd(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_Airspeed_MS5525::calculate(), Display_SH1106_I2C::clear_pixel(), Display_SSD1306_I2C::clear_pixel(), Display_SH1106_I2C::clear_screen(), Display_SSD1306_I2C::clear_screen(), AP_RangeFinder_LightWareI2C::detect(), AP_Airspeed_MS4525::get_differential_pressure(), AP_Airspeed_MS5525::get_differential_pressure(), AP_Airspeed_MS4525::get_temperature(), AP_Airspeed_MS5525::get_temperature(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), ToshibaLED_I2C::hw_init(), Display_SH1106_I2C::hw_init(), Display_SSD1306_I2C::hw_init(), TSYS01::init(), AP_RangeFinder_trone::init(), AP_Compass_LSM9DS1::init(), AP_Airspeed_MS4525::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Airspeed_MS5525::init(), AP_Compass_BMM150::init(), AP_Compass_AK8963::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), AP_Compass_LIS3MDL::init(), Linux::RCOutput_Bebop::play_note(), Linux::RCOutput_PCA9685::push(), DataFlash_MAVLink::push_log_blocks(), AP_Compass_LSM9DS1::read(), AP_Compass_LSM303D::read(), AP_Compass_BMM150::read(), AP_Compass_IST8310::read(), AP_Compass_AK09916::read(), AP_Compass_LIS3MDL::read(), AP_Compass_AK8963::read(), AP_IRLock_I2C::read_frames(), Linux::RCOutput_Bebop::read_obs_data(), Linux::RCOutput_PCA9685::reset_all_channels(), AP_OpticalFlow_PX4Flow::scan_buses(), Linux::RCOutput_PCA9685::set_freq(), Display_SH1106_I2C::set_pixel(), Display_SSD1306_I2C::set_pixel(), AP_OpticalFlow_Pixart::setup_sensor(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_Invensense::start(), AP_RangeFinder_trone::timer(), AP_Compass_IST8310::timer(), AP_Compass_AK09916::timer(), AP_Compass_LIS3MDL::timer(), AP_OpticalFlow_Pixart::timer(), AP_Baro_QFLIGHT::timer_update(), AP_Baro_QFLIGHT::update(), AP_RangeFinder_trone::update(), AP_Baro_BMP280::update(), AP_Baro_BMP085::update(), AP_OpticalFlow_Pixart::update(), AP_IRLock_I2C::update(), AP_Baro_MS56XX::update(), AP_RangeFinder_MaxsonarI2CXL::update(), AP_InertialSensor_Backend::update_accel(), AP_InertialSensor_Backend::update_gyro(), and DataFlash_MAVLink::WritePrioritisedBlock().
virtual bool AP_HAL::Semaphore::take (uint32_t timeout_ms) pure virtual
Implemented in Linux::Semaphore, PX4::Semaphore, QURT::Semaphore, HALSITL::Semaphore, VRBRAIN::Semaphore, and Empty::Semaphore.
Referenced by AP_Baro_BMP085::_calculate(), Linux::RCOutput_Bebop::_clear_error(), AP_Airspeed_MS4525::_collect(), Linux::RCOutput_Bebop::_get_info(), AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_Baro_BMP280::_init(), AP_RangeFinder_MaxsonarI2CXL::_init(), AP_Baro_MS56XX::_init(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), Linux::RCOutput_Bebop::_play_sound(), Linux::RCOutput_Bebop::_set_ref_speed(), Linux::RCOutput_Bebop::_start_prop(), Linux::RCOutput_Bebop::_stop_prop(), Display_SH1106_I2C::_timer(), Display_SSD1306_I2C::_timer(), AP_RangeFinder_MaxsonarI2CXL::_timer(), AP_Baro_MS56XX::_timer(), Linux::RCOutput_Bebop::_toggle_gpio(), AP_Compass_LSM9DS1::_update(), AP_Compass_LSM303D::_update(), AP_Compass_BMM150::_update(), AP_Compass_AK8963::_update(), AP_Baro_BMP280::_update_pressure(), AP_Baro_BMP280::_update_temperature(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_Airspeed_MS5525::calculate(), Display_SSD1306_I2C::clear_pixel(), Display_SH1106_I2C::clear_pixel(), Display_SSD1306_I2C::clear_screen(), Display_SH1106_I2C::clear_screen(), AP_RangeFinder_LightWareI2C::detect(), AP_Airspeed_MS4525::get_differential_pressure(), AP_Airspeed_MS5525::get_differential_pressure(), AP_Airspeed_MS4525::get_temperature(), AP_Airspeed_MS5525::get_temperature(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), ToshibaLED_I2C::hw_init(), Display_SH1106_I2C::hw_init(), Display_SSD1306_I2C::hw_init(), TSYS01::init(), AP_RangeFinder_trone::init(), AP_Compass_LSM9DS1::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Compass_BMM150::init(), AP_Compass_AK8963::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), AP_Compass_LIS3MDL::init(), Linux::RCOutput_Bebop::play_note(), AP_IRLock_I2C::read_frames(), Linux::RCOutput_Bebop::read_obs_data(), Linux::RCOutput_PCA9685::reset_all_channels(), AP_OpticalFlow_PX4Flow::scan_buses(), Linux::RCOutput_PCA9685::set_freq(), Display_SSD1306_I2C::set_pixel(), Display_SH1106_I2C::set_pixel(), AP_OpticalFlow_Pixart::setup_sensor(), AP_InertialSensor_BMI160::start(), AP_InertialSensor_Invensense::start(), AP_RangeFinder_trone::timer(), AP_Compass_IST8310::timer(), AP_Compass_AK09916::timer(), AP_Compass_LIS3MDL::timer(), AP_OpticalFlow_Pixart::timer(), AP_Baro_QFLIGHT::timer_update(), AP_RangeFinder_trone::update(), AP_OpticalFlow_Pixart::update(), AP_IRLock_I2C::update(), AP_Baro_MS56XX::update(), AP_InertialSensor_Backend::update_accel(), and AP_InertialSensor_Backend::update_gyro().
virtual bool AP_HAL::Semaphore::take_nonblocking () pure virtual
Implemented in Linux::Semaphore, PX4::Semaphore, QURT::Semaphore, HALSITL::Semaphore, VRBRAIN::Semaphore, and Empty::Semaphore.
Referenced by Linux::SPIUARTDriver::_read_fd(), AP_Compass_AK8963::_update_timer(), Linux::SPIUARTDriver::_write_fd(), Linux::RCOutput_PCA9685::push(), DataFlash_MAVLink::push_log_blocks(), AP_Compass_LSM303D::read(), AP_Compass_LSM9DS1::read(), AP_Compass_BMM150::read(), AP_Compass_IST8310::read(), AP_Compass_AK09916::read(), AP_Compass_AK8963::read(), AP_Compass_LIS3MDL::read(), AP_Baro_QFLIGHT::update(), AP_Baro_BMP280::update(), AP_Baro_BMP085::update(), AP_RangeFinder_MaxsonarI2CXL::update(), and DataFlash_MAVLink::WritePrioritisedBlock().
The documentation for this class was generated from the following file:
libraries/AP_HAL/Semaphores.h