APM:Libraries: Linux::TimerPollable Class Reference
Linux::TimerPollable Class Reference
#include <PollerThread.h>
Classes
class WrapperCb
Public Types
using PeriodicCb = AP_HAL::Device::PeriodicCb
Public Member Functions
virtual ~TimerPollable ()
void on_can_read () override
bool setup_timer (uint32_t timeout_usec)
bool adjust_timer (uint32_t timeout_usec)
Public Member Functions inherited from Linux::Pollable
Pollable (int fd)
Pollable ()
virtual ~Pollable ()
int get_fd () const
virtual void on_can_write ()
virtual void on_error ()
virtual void on_hang_up ()
Protected Member Functions
TimerPollable (PeriodicCb cb, WrapperCb *wrapper)
Protected Attributes
PeriodicCb _cb
WrapperCb * _wrapper
bool _removeme = false
Protected Attributes inherited from Linux::Pollable
int _fd = -1
Friends
class PollerThread
Detailed Description
Definition at line 29 of file PollerThread.h.
Member Typedef Documentation
using Linux::TimerPollable::PeriodicCb = AP_HAL::Device::PeriodicCb
Definition at line 41 of file PollerThread.h.
Constructor & Destructor Documentation
virtual Linux::TimerPollable::~TimerPollable () inline virtual
Definition at line 43 of file PollerThread.h.
Linux::TimerPollable::TimerPollable (PeriodicCb cb, WrapperCb * wrapper) inline protected
Definition at line 51 of file PollerThread.h.
Referenced by Linux::PollerThread::add_timer().
Member Function Documentation
bool Linux::TimerPollable::adjust_timer (uint32_t timeout_usec)
Definition at line 71 of file PollerThread.cpp.
Referenced by setup_timer(), Linux::PollerThread::~PollerThread(), and ~TimerPollable().
void Linux::TimerPollable::on_can_read () override virtual
Reimplemented from Linux::Pollable.
Definition at line 28 of file PollerThread.cpp.
Referenced by ~TimerPollable().
bool Linux::TimerPollable::setup_timer (uint32_t timeout_usec)
Definition at line 51 of file PollerThread.cpp.
Referenced by Linux::PollerThread::add_timer(), and ~TimerPollable().
Friends And Related Function Documentation
friend class PollerThread friend
Definition at line 30 of file PollerThread.h.
Member Data Documentation
PeriodicCb Linux::TimerPollable::_cb protected
Definition at line 57 of file PollerThread.h.
Referenced by on_can_read().
bool Linux::TimerPollable::_removeme = false protected
Definition at line 59 of file PollerThread.h.
Referenced by Linux::PollerThread::_cleanup_timers(), and on_can_read().
WrapperCb* Linux::TimerPollable::_wrapper protected
Definition at line 58 of file PollerThread.h.
Referenced by on_can_read().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/PollerThread.h
libraries/AP_HAL_Linux/PollerThread.cpp