APM:Libraries: AP_HAL::Util Class Reference
AP_HAL::Util Class Reference abstract
#include <Util.h>
Public Types
enum safety_state { SAFETY_NONE, SAFETY_DISARMED, SAFETY_ARMED }
enum perf_counter_type { PC_COUNT, PC_ELAPSED, PC_INTERVAL }
typedef void * perf_counter_t
Public Member Functions
int snprintf (char *str, size_t size, const char *format,...)
int vsnprintf (char *str, size_t size, const char *format, va_list ap)
void set_soft_armed (const bool b)
bool get_soft_armed () const
void set_capabilities (uint64_t cap)
void clear_capabilities (uint64_t cap)
uint64_t get_capabilities () const
virtual const char * get_custom_log_directory ()
virtual const char * get_custom_terrain_directory () const
virtual const char * get_custom_defaults_file () const
virtual bool run_debug_shell (AP_HAL::BetterStream *stream)=0
virtual enum safety_state safety_switch_state (void)
virtual void set_system_clock (uint64_t time_utc_usec)
uint64_t get_system_clock_ms () const
void get_system_clock_utc (int32_t &hour, int32_t &min, int32_t &sec, int32_t &ms) const
uint32_t get_time_utc (int32_t hour, int32_t min, int32_t sec, int32_t ms) const
virtual bool get_system_id (char buf[40])
virtual uint32_t available_memory (void)
virtual void commandline_arguments (uint8_t &argc, char *const *&argv)
virtual bool toneAlarm_init ()
virtual void toneAlarm_set_tune (uint8_t tune)
virtual void _toneAlarm_timer_tick ()
virtual AP_HAL::Stream * get_shell_stream ()
virtual void set_imu_temp (float current)
virtual void set_imu_target_temp (int8_t *target)
virtual perf_counter_t perf_alloc (perf_counter_type t, const char *name)
virtual void perf_begin (perf_counter_t h)
virtual void perf_end (perf_counter_t h)
virtual void perf_count (perf_counter_t h)
virtual Semaphore * new_semaphore (void)
virtual void * dma_allocate (size_t size)
virtual void dma_free (void *ptr, size_t size)
Protected Attributes
bool soft_armed = false
uint64_t capabilities = 0
Detailed Description
Definition at line 6 of file Util.h.
Member Typedef Documentation
typedef void* AP_HAL::Util::perf_counter_t
Definition at line 105 of file Util.h.
Member Enumeration Documentation
enum AP_HAL::Util::perf_counter_type
Enumerator
PC_COUNT
count the number of times an event occurs
PC_ELAPSED
measure the time elapsed performing an event
PC_INTERVAL
measure the interval between instances of an event
Definition at line 100 of file Util.h.
enum AP_HAL::Util::safety_state
Enumerator
SAFETY_NONE
SAFETY_DISARMED
SAFETY_ARMED
Definition at line 34 of file Util.h.
Member Function Documentation
virtual void AP_HAL::Util::_toneAlarm_timer_tick () inline virtual
Reimplemented in Linux::Util.
Definition at line 84 of file Util.h.
virtual uint32_t AP_HAL::Util::available_memory (void) inline virtual
how much free memory do we have in bytes. If unknown return 4096
Reimplemented in Linux::Util, PX4::PX4Util, VRBRAIN::VRBRAINUtil, QURT::Util, and HALSITL::Util.
Definition at line 72 of file Util.h.
Referenced by AC_PolyFence_loader::create_point_array(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), GCS_MAVLINK::send_meminfo(), PX4::NSHShellStream::start_shell(), and VRBRAIN::NSHShellStream::start_shell().
void AP_HAL::Util::clear_capabilities (uint64_t cap) inline
Definition at line 18 of file Util.h.
virtual void AP_HAL::Util::commandline_arguments (uint8_t & argc, char *const *& argv) inline virtual
return commandline arguments, if available
Reimplemented in Linux::Util.
Definition at line 77 of file Util.h.
virtual void* AP_HAL::Util::dma_allocate (size_t size) inline virtual
Reimplemented in PX4::PX4Util.
Definition at line 115 of file Util.h.
Referenced by AP_InertialSensor_Invensense::start().
virtual void AP_HAL::Util::dma_free (void * ptr, size_t size) inline virtual
Reimplemented in PX4::PX4Util.
Definition at line 116 of file Util.h.
Referenced by AP_InertialSensor_Invensense::~AP_InertialSensor_Invensense().
uint64_t AP_HAL::Util::get_capabilities () const inline
Definition at line 19 of file Util.h.
Referenced by GCS_MAVLINK::send_autopilot_version().
virtual const char* AP_HAL::Util::get_custom_defaults_file () const inline virtual
Reimplemented in HALSITL::Util.
Definition at line 25 of file Util.h.
Referenced by AP_Param::reload_defaults_file().
virtual const char* AP_HAL::Util::get_custom_log_directory () inline virtual
Reimplemented in Linux::Util.
Definition at line 21 of file Util.h.
virtual const char* AP_HAL::Util::get_custom_terrain_directory () const inline virtual
Definition at line 22 of file Util.h.
virtual AP_HAL::Stream* AP_HAL::Util::get_shell_stream () inline virtual
Reimplemented in PX4::PX4Util, and VRBRAIN::VRBRAINUtil.
Definition at line 89 of file Util.h.
Referenced by GCS_MAVLINK::handle_serial_control().
bool AP_HAL::Util::get_soft_armed () const inline
Definition at line 15 of file Util.h.
Referenced by PX4::PX4Storage::_mtd_load(), VRBRAIN::VRBRAINRCOutput::_publish_actuators(), PX4::PX4RCOutput::_publish_actuators(), AP_GPS_UBLOX::_request_next_config(), PX4::PX4RCOutput::_send_outputs(), PX4::PX4AnalogIn::_timer_tick(), AP_InertialSensor::acal_update(), AP_AHRS_NavEKF::active_EKF_type(), AP_Tuning::check_controller_error(), NavEKF2_core::controlFilterModes(), NavEKF3_core::controlFilterModes(), Compass::handle_mag_cal_command(), SoloGimbalEKF::predictCovariance(), DataFlash_Block::Prep(), AP_GPS_UBLOX::read(), PX4::NSHShellStream::start_shell(), VRBRAIN::NSHShellStream::start_shell(), PX4::PX4UARTDriver::try_initialise(), VRBRAIN::VRBRAINUARTDriver::try_initialise(), AP_ICEngine::update(), and AP_AHRS_DCM::use_fast_gains().
uint64_t AP_HAL::Util::get_system_clock_ms () const
Definition at line 54 of file Util.cpp.
Referenced by set_system_clock(), and AP_Stats::update().
void AP_HAL::Util::get_system_clock_utc (int32_t & hour, int32_t & min, int32_t & sec, int32_t & ms) const
Definition at line 69 of file Util.cpp.
Referenced by set_system_clock().
virtual bool AP_HAL::Util::get_system_id (char buf[40]) inline virtual
Reimplemented in PX4::PX4Util, and VRBRAIN::VRBRAINUtil.
Definition at line 67 of file Util.h.
Referenced by GCS_MAVLINK::handle_param_request_list(), and DFMessageWriter_WriteSysInfo::process().
uint32_t AP_HAL::Util::get_time_utc (int32_t hour, int32_t min, int32_t sec, int32_t ms) const
Definition at line 88 of file Util.cpp.
Referenced by set_system_clock().
virtual Semaphore* AP_HAL::Util::new_semaphore (void) inline virtual
Reimplemented in Linux::Util, PX4::PX4Util, VRBRAIN::VRBRAINUtil, QURT::Util, and HALSITL::Util.
Definition at line 112 of file Util.h.
Referenced by AP_Airspeed_Backend::AP_Airspeed_Backend(), AP_Baro_Backend::AP_Baro_Backend(), AP_Compass_Backend::AP_Compass_Backend(), AP_InertialSensor_Backend::AP_InertialSensor_Backend(), AP_RangeFinder_Backend::AP_RangeFinder_Backend(), Display_SH1106_I2C::Display_SH1106_I2C(), Display_SSD1306_I2C::Display_SSD1306_I2C(), AP_IRLock_I2C::init(), DataFlash_MAVLink::Init(), and OpticalFlow_backend::OpticalFlow_backend().
virtual perf_counter_t AP_HAL::Util::perf_alloc (perf_counter_type t, const char * name) inline virtual
Reimplemented in Linux::Util, PX4::PX4Util, and VRBRAIN::VRBRAINUtil.
Definition at line 106 of file Util.h.
Referenced by AP_Compass_IST8310::init(), NavEKF2_core::NavEKF2_core(), NavEKF3_core::NavEKF3_core(), and AP_Scheduler::run().
virtual void AP_HAL::Util::perf_begin (perf_counter_t h) inline virtual
Reimplemented in Linux::Util, PX4::PX4Util, and VRBRAIN::VRBRAINUtil.
Definition at line 107 of file Util.h.
Referenced by NavEKF2_core::CovariancePrediction(), NavEKF3_core::CovariancePrediction(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), NavEKF2_core::FuseMagnetometer(), NavEKF2_core::FuseSideslip(), NavEKF3_core::FuseSideslip(), NavEKF2_core::FuseVelPosNED(), NavEKF3_core::FuseVelPosNED(), AP_Scheduler::run(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), NavEKF2_core::SelectMagFusion(), NavEKF3_core::SelectMagFusion(), DataFlash_MAVLink::send_log_block(), NavEKF2_core::UpdateFilter(), and NavEKF3_core::UpdateFilter().
virtual void AP_HAL::Util::perf_count (perf_counter_t h) inline virtual
Reimplemented in Linux::Util, PX4::PX4Util, and VRBRAIN::VRBRAINUtil.
Definition at line 109 of file Util.h.
Referenced by AP_Compass_IST8310::start_conversion(), and AP_Compass_IST8310::timer().
virtual void AP_HAL::Util::perf_end (perf_counter_t h) inline virtual
Reimplemented in Linux::Util, PX4::PX4Util, and VRBRAIN::VRBRAINUtil.
Definition at line 108 of file Util.h.
Referenced by NavEKF2_core::CovariancePrediction(), NavEKF3_core::CovariancePrediction(), NavEKF2_core::EstimateTerrainOffset(), NavEKF3_core::EstimateTerrainOffset(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), NavEKF2_core::FuseMagnetometer(), NavEKF2_core::FuseSideslip(), NavEKF3_core::FuseSideslip(), NavEKF2_core::FuseVelPosNED(), NavEKF3_core::FuseVelPosNED(), AP_Scheduler::run(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), NavEKF2_core::SelectMagFusion(), NavEKF3_core::SelectMagFusion(), DataFlash_MAVLink::send_log_block(), NavEKF2_core::UpdateFilter(), and NavEKF3_core::UpdateFilter().
virtual bool AP_HAL::Util::run_debug_shell (AP_HAL::BetterStream * stream) pure virtual
Implemented in Linux::Util, PX4::PX4Util, VRBRAIN::VRBRAINUtil, QURT::Util, HALSITL::Util, and Empty::Util.
Referenced by get_custom_defaults_file().
virtual enum safety_state AP_HAL::Util::safety_switch_state (void) inline virtual
Reimplemented in PX4::PX4Util, and VRBRAIN::VRBRAINUtil.
Definition at line 41 of file Util.h.
Referenced by VRBRAIN::VRBRAINRCOutput::_publish_actuators(), PX4::PX4RCOutput::_publish_actuators(), VRBRAIN::VRBRAINRCOutput::force_safety_pending_requests(), PX4::PX4RCOutput::force_safety_pending_requests(), AP_Arming::hardware_safety_check(), AP_BoardConfig::px4_setup_safety(), PX4::PX4UARTDriver::try_initialise(), and VRBRAIN::VRBRAINUARTDriver::try_initialise().
void AP_HAL::Util::set_capabilities (uint64_t cap) inline
Definition at line 17 of file Util.h.
Referenced by GCS_MAVLINK::setup_uart().
virtual void AP_HAL::Util::set_imu_target_temp (int8_t * target) inline virtual
Reimplemented in PX4::PX4Util, VRBRAIN::VRBRAINUtil, and Linux::Util.
Definition at line 95 of file Util.h.
Referenced by AP_BoardConfig::init().
virtual void AP_HAL::Util::set_imu_temp (float current) inline virtual
Reimplemented in PX4::PX4Util, VRBRAIN::VRBRAINUtil, and Linux::Util.
Definition at line 92 of file Util.h.
Referenced by AP_InertialSensor_Backend::_publish_temperature().
void AP_HAL::Util::set_soft_armed (const bool b) inline
Definition at line 14 of file Util.h.
virtual void AP_HAL::Util::set_system_clock (uint64_t time_utc_usec) inline virtual
Reimplemented in Linux::Util, PX4::PX4Util, and VRBRAIN::VRBRAINUtil.
Definition at line 46 of file Util.h.
int AP_HAL::Util::snprintf (char * str, size_t size, const char * format, ...)
Definition at line 35 of file Util.cpp.
Referenced by AP_GPS::_broadcast_gps_type(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), PX4::PX4Util::get_system_id(), VRBRAIN::VRBRAINUtil::get_system_id(), and test_printf().
virtual bool AP_HAL::Util::toneAlarm_init () inline virtual
Reimplemented in Linux::Util.
Definition at line 82 of file Util.h.
Referenced by ToneAlarm_Linux::init().
virtual void AP_HAL::Util::toneAlarm_set_tune (uint8_t tune) inline virtual
Reimplemented in Linux::Util.
Definition at line 83 of file Util.h.
Referenced by ToneAlarm_Linux::play_tune().
int AP_HAL::Util::vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 44 of file Util.cpp.
Referenced by AP_AccelCal::_printf(), AP_InertialSensor_UserInteract_MAVLink::printf(), GCS_MAVLINK::send_statustext_all(), and GCS_MAVLINK::send_statustext_chan().
Member Data Documentation
uint64_t AP_HAL::Util::capabilities = 0 protected
Definition at line 122 of file Util.h.
Referenced by clear_capabilities(), get_capabilities(), and set_capabilities().
bool AP_HAL::Util::soft_armed = false protected
Definition at line 121 of file Util.h.
Referenced by get_soft_armed(), and set_soft_armed().
The documentation for this class was generated from the following files:
libraries/AP_HAL/Util.h
libraries/AP_HAL/Util.cpp