APM:Libraries: AP_Rally Class Reference
AP_Rally Class Reference
Object managing Rally Points.
#include <AP_Rally.h>
Public Member Functions
AP_Rally (AP_AHRS &ahrs)
bool get_rally_point_with_index (uint8_t i, RallyLocation &ret) const
bool set_rally_point_with_index (uint8_t i, const RallyLocation &rallyLoc)
uint8_t get_rally_total () const
uint8_t get_rally_max (void) const
float get_rally_limit_km () const
Location rally_location_to_location (const RallyLocation &ret) const
Location calc_best_rally_or_home_location (const Location &current_loc, float rtl_home_alt) const
bool find_nearest_rally_point (const Location &myloc, RallyLocation &ret) const
uint32_t last_change_time_ms (void) const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
virtual bool is_valid (const Location &rally_point) const
Private Attributes
const AP_AHRS & _ahrs
AP_Int8 _rally_point_total_count
AP_Float _rally_limit_km
AP_Int8 _rally_incl_home
uint32_t _last_change_time_ms
Static Private Attributes
static StorageAccess _storage
Detailed Description
Object managing Rally Points.
Definition at line 37 of file AP_Rally.h.
Constructor & Destructor Documentation
AP_Rally::AP_Rally (AP_AHRS & ahrs)
Definition at line 59 of file AP_Rally.cpp.
Member Function Documentation
Location AP_Rally::calc_best_rally_or_home_location (const Location & current_loc, float rtl_home_alt) const
Definition at line 154 of file AP_Rally.cpp.
bool AP_Rally::find_nearest_rally_point (const Location & myloc, RallyLocation & ret) const
Definition at line 120 of file AP_Rally.cpp.
Referenced by calc_best_rally_or_home_location().
float AP_Rally::get_rally_limit_km () const inline
Definition at line 48 of file AP_Rally.h.
uint8_t AP_Rally::get_rally_max (void) const inline
Definition at line 46 of file AP_Rally.h.
Referenced by set_rally_point_with_index().
bool AP_Rally::get_rally_point_with_index (uint8_t i, RallyLocation & ret) const
Definition at line 67 of file AP_Rally.cpp.
Referenced by find_nearest_rally_point(), and DataFlash_Class::Log_Write_Rally().
uint8_t AP_Rally::get_rally_total () const inline
Definition at line 45 of file AP_Rally.h.
Referenced by DataFlash_Class::Log_Write_Rally().
virtual bool AP_Rally::is_valid (const Location & rally_point) const inline private virtual
Definition at line 63 of file AP_Rally.h.
Referenced by find_nearest_rally_point().
uint32_t AP_Rally::last_change_time_ms (void) const inline
Definition at line 57 of file AP_Rally.h.
Location AP_Rally::rally_location_to_location (const RallyLocation & ret) const
Definition at line 101 of file AP_Rally.cpp.
Referenced by calc_best_rally_or_home_location(), and find_nearest_rally_point().
bool AP_Rally::set_rally_point_with_index (uint8_t i, const RallyLocation & rallyLoc)
Definition at line 83 of file AP_Rally.cpp.
Member Data Documentation
const AP_AHRS& AP_Rally::_ahrs private
Definition at line 68 of file AP_Rally.h.
Referenced by calc_best_rally_or_home_location(), find_nearest_rally_point(), and rally_location_to_location().
uint32_t AP_Rally::_last_change_time_ms private
Definition at line 75 of file AP_Rally.h.
Referenced by set_rally_point_with_index().
AP_Int8 AP_Rally::_rally_incl_home private
Definition at line 73 of file AP_Rally.h.
Referenced by find_nearest_rally_point().
AP_Float AP_Rally::_rally_limit_km private
Definition at line 72 of file AP_Rally.h.
Referenced by find_nearest_rally_point().
AP_Int8 AP_Rally::_rally_point_total_count private
Definition at line 71 of file AP_Rally.h.
Referenced by find_nearest_rally_point(), get_rally_point_with_index(), and set_rally_point_with_index().
StorageAccess AP_Rally::_storage static private
Definition at line 65 of file AP_Rally.h.
Referenced by get_rally_point_with_index(), and set_rally_point_with_index().
const AP_Param::GroupInfo AP_Rally::var_info static
Initial value:
= {
    AP_GROUPINFO("TOTAL", 0, AP_Rally, _rally_point_total_count, 0),
    AP_GROUPINFO("LIMIT_KM", 1, AP_Rally, _rally_limit_km, RALLY_LIMIT_KM_DEFAULT),
    AP_GROUPINFO("INCL_HOME", 2, AP_Rally, _rally_incl_home, RALLY_INCLUDE_HOME_DEFAULT),
    AP_GROUPEND
}
Definition at line 60 of file AP_Rally.h.
Referenced by AP_Rally().
The documentation for this class was generated from the following files:
libraries/AP_Rally/AP_Rally.h
libraries/AP_Rally/AP_Rally.cpp