APM:Libraries: QURT::UARTDriver Class Reference
QURT::UARTDriver Class Reference
#include <UARTDriver.h>
Public Member Functions
UARTDriver (const char *name)
void set_device_path (const char *path)
void begin (uint32_t b)
void begin (uint32_t b, uint16_t rxS, uint16_t txS)
void end ()
void flush ()
bool is_initialized ()
void set_blocking_writes (bool blocking)
bool tx_pending ()
int16_t available ()
int16_t txspace ()
int16_t read ()
size_t write (uint8_t c)
size_t write (const uint8_t *buffer, size_t size)
void _read_callback (char *buf, size_t size)
void timer_tick (void)
Public Member Functions inherited from AP_HAL::UARTDriver
UARTDriver ()
virtual void set_flow_control (enum flow_control flow_control_setting)
virtual enum flow_control get_flow_control (void)
void printf (const char *s,...) FMT_PRINTF(2
void void vprintf (const char *s, va_list ap)
Public Member Functions inherited from AP_HAL::BetterStream
BetterStream (void)
Public Member Functions inherited from AP_HAL::Print
Print ()
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Private Member Functions
int write_fd (const uint8_t *buf, uint16_t n)
Private Attributes
const char * devname
int fd = -1
Semaphore lock
ByteBuffer * readbuf
ByteBuffer * writebuf
bool nonblocking_writes = false
volatile bool in_timer = false
volatile bool initialised = false
uint64_t last_write_time_us
Additional Inherited Members
Public Types inherited from AP_HAL::UARTDriver
enum flow_control { FLOW_CONTROL_DISABLE =0, FLOW_CONTROL_ENABLE =1, FLOW_CONTROL_AUTO =2 }
Detailed Description
Definition at line 22 of file UARTDriver.h.
Constructor & Destructor Documentation
UARTDriver::UARTDriver (const char * name)
Definition at line 33 of file UARTDriver.cpp.
Member Function Documentation
void UARTDriver::_read_callback (char * buf, size_t size)
Definition at line 73 of file UARTDriver.cpp.
Referenced by set_device_path().
int16_t UARTDriver::available (void) virtual
Implements AP_HAL::Stream.
Definition at line 187 of file UARTDriver.cpp.
Referenced by set_device_path().
void UARTDriver::begin (uint32_t b) virtual
Implements AP_HAL::UARTDriver.
Definition at line 38 of file UARTDriver.cpp.
Referenced by set_device_path().
void UARTDriver::begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace) virtual
Extended port open method
Allows for both opening with specified buffer sizes, and re-opening to adjust a subset of the port's settings.
Note
Buffer sizes greater than ::_max_buffer_size will be rounded down.
Parameters
baud Selects the speed that the port will be configured to. If zero, the port speed is left unchanged.
rxSpace Sets the receive buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_rx_buffer_size if it is currently closed.
txSpace Sets the transmit buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_tx_buffer_size if it is currently closed.
Implements AP_HAL::UARTDriver.
Definition at line 84 of file UARTDriver.cpp.
void UARTDriver::end () virtual
Implements AP_HAL::UARTDriver.
Definition at line 149 of file UARTDriver.cpp.
Referenced by set_device_path().
void UARTDriver::flush (void) virtual
Implements AP_HAL::UARTDriver.
Definition at line 167 of file UARTDriver.cpp.
Referenced by set_device_path().
bool UARTDriver::is_initialized () virtual
Implements AP_HAL::UARTDriver.
Definition at line 171 of file UARTDriver.cpp.
Referenced by set_device_path().
int16_t UARTDriver::read (void) virtual
Implements AP_HAL::Stream.
Definition at line 203 of file UARTDriver.cpp.
Referenced by set_device_path().
void UARTDriver::set_blocking_writes (bool blocking) virtual
Implements AP_HAL::UARTDriver.
Definition at line 176 of file UARTDriver.cpp.
Referenced by set_device_path().
void QURT::UARTDriver::set_device_path (const char * path) inline
Definition at line 28 of file UARTDriver.h.
Referenced by HAL_QURT::run().
void UARTDriver::timer_tick (void)
Definition at line 272 of file UARTDriver.cpp.
Referenced by set_device_path().
bool UARTDriver::tx_pending () virtual
Implements AP_HAL::UARTDriver.
Definition at line 181 of file UARTDriver.cpp.
Referenced by set_device_path().
int16_t UARTDriver::txspace (void) virtual
Implements AP_HAL::Stream.
Definition at line 195 of file UARTDriver.cpp.
Referenced by set_device_path().
size_t UARTDriver::write (uint8_t c) virtual
Implements AP_HAL::Print.
Definition at line 222 of file UARTDriver.cpp.
Referenced by set_device_path(), timer_tick(), and write().
size_t UARTDriver::write (const uint8_t * buffer, size_t size) virtual
Implements AP_HAL::Print.
Definition at line 243 of file UARTDriver.cpp.
int QURT::UARTDriver::write_fd (const uint8_t * buf, uint16_t n) private
Member Data Documentation
const char* QURT::UARTDriver::devname private
Definition at line 54 of file UARTDriver.h.
Referenced by begin(), and set_device_path().
int QURT::UARTDriver::fd = -1 private
Definition at line 55 of file UARTDriver.h.
Referenced by begin(), end(), is_initialized(), and timer_tick().
volatile bool QURT::UARTDriver::in_timer = false private
Definition at line 62 of file UARTDriver.h.
Referenced by timer_tick().
volatile bool QURT::UARTDriver::initialised = false private
Definition at line 63 of file UARTDriver.h.
Referenced by available(), begin(), end(), is_initialized(), read(), timer_tick(), txspace(), and write().
uint64_t QURT::UARTDriver::last_write_time_us private
Definition at line 65 of file UARTDriver.h.
Semaphore QURT::UARTDriver::lock private
Definition at line 56 of file UARTDriver.h.
Referenced by read(), timer_tick(), and write().
bool QURT::UARTDriver::nonblocking_writes = false private
Definition at line 61 of file UARTDriver.h.
Referenced by set_blocking_writes(), and write().
ByteBuffer* QURT::UARTDriver::readbuf private
Definition at line 58 of file UARTDriver.h.
Referenced by _read_callback(), available(), begin(), end(), and read().
ByteBuffer* QURT::UARTDriver::writebuf private
Definition at line 59 of file UARTDriver.h.
Referenced by begin(), end(), timer_tick(), txspace(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_QURT/UARTDriver.h
libraries/AP_HAL_QURT/UARTDriver.cpp