APM:Libraries: SITL::CRRCSim Class Reference
SITL::CRRCSim Class Reference
#include <SIM_CRRCSim.h>
Classes
struct fdm_packet
struct servo_packet
Public Member Functions
CRRCSim (const char *home_str, const char *frame_str)
void update (const struct sitl_input &input)
Public Member Functions inherited from SITL::Aircraft
Aircraft (const char *home_str, const char *frame_str)
void set_speedup (float speedup)
void set_instance (uint8_t _instance)
void set_autotest_dir (const char *_autotest_dir)
virtual void set_interface_ports (const char *address, const int port_in, const int port_out)
void fill_fdm (struct sitl_fdm &fdm)
void smooth_sensors (void)
float get_rate_hz (void) const
const Vector3f & get_gyro (void) const
const Vector3f & get_velocity_ef (void) const
const Vector3f & get_velocity_air_ef (void) const
const Matrix3f & get_dcm (void) const
const Vector3f & get_mag_field_bf (void) const
virtual float gross_mass () const
Static Public Member Functions
static Aircraft * create (const char *home_str, const char *frame_str)
Static Public Member Functions inherited from SITL::Aircraft
static double rand_normal (double mean, double stddev)
static bool parse_home (const char *home_str, Location &loc, float &yaw_degrees)
Private Member Functions
void send_servos_heli (const struct sitl_input &input)
void send_servos_fixed_wing (const struct sitl_input &input)
void recv_fdm (const struct sitl_input &input)
void send_servos (const struct sitl_input &input)
Private Attributes
bool heli_servos
double last_timestamp
SocketAPM sock
Additional Inherited Members
Protected Types inherited from SITL::Aircraft
enum { GROUND_BEHAVIOR_NONE = 0, GROUND_BEHAVIOR_NO_MOVEMENT, GROUND_BEHAVIOR_FWD_ONLY, GROUND_BEHAVIOR_TAILSITTER }
Protected Member Functions inherited from SITL::Aircraft
float ground_height_difference () const
virtual bool on_ground () const
float hagl () const
void update_position (void)
void update_mag_field_bf (void)
void time_advance (float deltat)
void setup_frame_time (float rate, float speedup)
void adjust_frame_time (float rate)
void sync_frame_time (void)
void add_noise (float throttle)
uint64_t get_wall_time_us (void) const
void update_dynamics (const Vector3f &rot_accel)
void update_wind (const struct sitl_input &input)
bool get_mag_field_ef (float latitude_deg, float longitude_deg, float &intensity_gauss, float &declination_deg, float &inclination_deg)
float filtered_idx (float v, uint8_t idx)
float filtered_servo_angle (const struct sitl_input &input, uint8_t idx)
float filtered_servo_range (const struct sitl_input &input, uint8_t idx)
Protected Attributes inherited from SITL::Aircraft
SITL * sitl
Location home
Location location
float ground_level
float home_yaw
float frame_height
Matrix3f dcm
Vector3f gyro
Vector3f gyro_prev
Vector3f ang_accel
Vector3f velocity_ef
Vector3f wind_ef
Vector3f velocity_air_ef
Vector3f velocity_air_bf
Vector3f position
float mass
Vector3f accel_body
float airspeed
float airspeed_pitot
float battery_voltage = -1
float battery_current = 0
float rpm1 = 0
float rpm2 = 0
uint8_t rcin_chan_count = 0
float rcin [8]
float turbulence_azimuth = 0
float turbulence_horizontal_speed = 0
float turbulence_vertical_speed = 0
Vector3f mag_bf
uint64_t time_now_us
const float gyro_noise
const float accel_noise
float rate_hz
float achieved_rate_hz
float target_speedup
uint64_t frame_time_us
float scaled_frame_time_us
uint64_t last_wall_time_us
uint8_t instance
const char * autotest_dir
const char * frame
bool use_time_sync = true
float last_speedup = -1
enum SITL::Aircraft:: { ... } ground_behavior
bool use_smoothing
AP_Terrain * terrain
const float FEET_TO_METERS = 0.3048f
const float KNOTS_TO_METERS_PER_SECOND = 0.51444f
Detailed Description
Definition at line 30 of file SIM_CRRCSim.h.
Constructor & Destructor Documentation
SITL::CRRCSim::CRRCSim (const char * home_str, const char * frame_str)
Definition at line 29 of file SIM_CRRCSim.cpp.
Referenced by create().
Member Function Documentation
static Aircraft* SITL::CRRCSim::create (const char * home_str, const char * frame_str) inline static
Definition at line 38 of file SIM_CRRCSim.h.
void SITL::CRRCSim::recv_fdm (const struct sitl_input & input) private
Definition at line 106 of file SIM_CRRCSim.cpp.
Referenced by update().
void SITL::CRRCSim::send_servos (const struct sitl_input & input) private
Definition at line 93 of file SIM_CRRCSim.cpp.
Referenced by recv_fdm(), and update().
void SITL::CRRCSim::send_servos_fixed_wing (const struct sitl_input & input) private
Definition at line 73 of file SIM_CRRCSim.cpp.
Referenced by send_servos().
void SITL::CRRCSim::send_servos_heli (const struct sitl_input & input) private
Definition at line 47 of file SIM_CRRCSim.cpp.
Referenced by send_servos().
void SITL::CRRCSim::update (const struct sitl_input & input) virtual
Implements SITL::Aircraft.
Definition at line 149 of file SIM_CRRCSim.cpp.
Member Data Documentation
bool SITL::CRRCSim::heli_servos private
Definition at line 74 of file SIM_CRRCSim.h.
Referenced by CRRCSim(), and send_servos().
double SITL::CRRCSim::last_timestamp private
Definition at line 75 of file SIM_CRRCSim.h.
Referenced by recv_fdm().
SocketAPM SITL::CRRCSim::sock private
Definition at line 76 of file SIM_CRRCSim.h.
Referenced by CRRCSim(), recv_fdm(), send_servos_fixed_wing(), and send_servos_heli().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_CRRCSim.h
libraries/SITL/SIM_CRRCSim.cpp