APM:Libraries: AP_RPM_Pin Class Reference
AP_RPM_Pin Class Reference
#include <RPM_Pin.h>
Classes
struct IrqState
Public Member Functions
AP_RPM_Pin (AP_RPM &ranger, uint8_t instance, AP_RPM::RPM_State &_state)
void update (void)
Public Member Functions inherited from AP_RPM_Backend
AP_RPM_Backend (AP_RPM &_ap_rpm, uint8_t instance, AP_RPM::RPM_State &_state)
virtual ~AP_RPM_Backend (void)
int8_t get_pin (void) const
Static Private Member Functions
static void irq_handler (uint8_t instance)
static int irq_handler0 (int irq, void *context)
static int irq_handler1 (int irq, void *context)
Private Attributes
ModeFilterFloat_Size5 signal_quality_filter {3}
uint8_t last_pin = -1
uint32_t last_gpio
Static Private Attributes
static struct IrqState irq_state [RPM_MAX_INSTANCES]
Additional Inherited Members
Protected Attributes inherited from AP_RPM_Backend
AP_RPM & ap_rpm
AP_RPM::RPM_State & state
Detailed Description
Definition at line 22 of file RPM_Pin.h.
Constructor & Destructor Documentation
AP_RPM_Pin::AP_RPM_Pin (AP_RPM & ranger, uint8_t instance, AP_RPM::RPM_State & _state)
Definition at line 30 of file RPM_Pin.cpp.
Member Function Documentation
void AP_RPM_Pin::irq_handler (uint8_t instance) static private
Definition at line 38 of file RPM_Pin.cpp.
Referenced by irq_handler0(), and irq_handler1().
int AP_RPM_Pin::irq_handler0 (int irq, void * context) static private
Definition at line 55 of file RPM_Pin.cpp.
Referenced by update().
int AP_RPM_Pin::irq_handler1 (int irq, void * context) static private
Definition at line 64 of file RPM_Pin.cpp.
Referenced by update().
void AP_RPM_Pin::update (void) virtual
Implements AP_RPM_Backend.
Definition at line 70 of file RPM_Pin.cpp.
Member Data Documentation
AP_RPM_Pin::IrqState AP_RPM_Pin::irq_state static private
Definition at line 44 of file RPM_Pin.h.
Referenced by irq_handler(), and update().
uint32_t AP_RPM_Pin::last_gpio private
Definition at line 38 of file RPM_Pin.h.
Referenced by update().
uint8_t AP_RPM_Pin::last_pin = -1 private
Definition at line 37 of file RPM_Pin.h.
Referenced by update().
ModeFilterFloat_Size5 AP_RPM_Pin::signal_quality_filter {3} private
Definition at line 36 of file RPM_Pin.h.
Referenced by update().
The documentation for this class was generated from the following files:
libraries/AP_RPM/RPM_Pin.h
libraries/AP_RPM/RPM_Pin.cpp