APM:Libraries: AnalogSource_ADS1115 Class Reference
AnalogSource_ADS1115 Class Reference
#include <AnalogIn_ADS1115.h>
Public Member Functions
AnalogSource_ADS1115 (int16_t pin)
float read_average ()
float read_latest ()
void set_pin (uint8_t p)
void set_stop_pin (uint8_t p)
void set_settle_time (uint16_t settle_time_ms)
float voltage_average ()
float voltage_latest ()
float voltage_average_ratiometric ()
Private Attributes
int16_t _pin
float _value
Friends
class AnalogIn_ADS1115
Detailed Description
Definition at line 8 of file AnalogIn_ADS1115.h.
Constructor & Destructor Documentation
AnalogSource_ADS1115::AnalogSource_ADS1115 (int16_t pin)
Definition at line 3 of file AnalogIn_ADS1115.cpp.
Referenced by AnalogIn_ADS1115::channel().
Member Function Documentation
float AnalogSource_ADS1115::read_average () virtual
Implements AP_HAL::AnalogSource.
Definition at line 17 of file AnalogIn_ADS1115.cpp.
float AnalogSource_ADS1115::read_latest () virtual
Implements AP_HAL::AnalogSource.
Definition at line 22 of file AnalogIn_ADS1115.cpp.
Referenced by read_average().
void AnalogSource_ADS1115::set_pin (uint8_t p) virtual
Implements AP_HAL::AnalogSource.
Definition at line 9 of file AnalogIn_ADS1115.cpp.
void AnalogSource_ADS1115::set_settle_time (uint16_t settle_time_ms) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 16 of file AnalogIn_ADS1115.h.
void AnalogSource_ADS1115::set_stop_pin (uint8_t p) inline virtual
Implements AP_HAL::AnalogSource.
Definition at line 15 of file AnalogIn_ADS1115.h.
float AnalogSource_ADS1115::voltage_average () virtual
Implements AP_HAL::AnalogSource.
Definition at line 27 of file AnalogIn_ADS1115.cpp.
Referenced by set_settle_time().
float AnalogSource_ADS1115::voltage_average_ratiometric () virtual
Implements AP_HAL::AnalogSource.
Definition at line 37 of file AnalogIn_ADS1115.cpp.
Referenced by set_settle_time().
float AnalogSource_ADS1115::voltage_latest () virtual
Implements AP_HAL::AnalogSource.
Definition at line 32 of file AnalogIn_ADS1115.cpp.
Referenced by set_settle_time().
Friends And Related Function Documentation
friend class AnalogIn_ADS1115 friend
Definition at line 10 of file AnalogIn_ADS1115.h.
Member Data Documentation
int16_t AnalogSource_ADS1115::_pin private
Definition at line 21 of file AnalogIn_ADS1115.h.
Referenced by AnalogIn_ADS1115::_update(), and set_pin().
float AnalogSource_ADS1115::_value private
Definition at line 22 of file AnalogIn_ADS1115.h.
Referenced by AnalogIn_ADS1115::_update(), read_latest(), voltage_average(), voltage_average_ratiometric(), and voltage_latest().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/AnalogIn_ADS1115.h
libraries/AP_HAL_Linux/AnalogIn_ADS1115.cpp