APM:Libraries: AP_Param Class Reference
AP_Param Class Reference
#include <AP_Param.h>
Classes
struct ConversionInfo
struct EEPROM_header
struct GroupInfo
struct GroupNesting
struct Info
struct Param_header
struct param_override
struct ParamToken
Public Types
enum { CONVERT_FLAG_REVERSE =1, CONVERT_FLAG_FORCE =2 }
Public Member Functions
AP_Param (const struct Info *info)
AP_Param ()
void copy_name_info (const struct AP_Param::Info *info, const struct GroupInfo *ginfo, const struct GroupNesting &group_nesting, uint8_t idx, char *buffer, size_t bufferSize, bool force_scalar=false) const
void copy_name_token (const ParamToken &token, char *buffer, size_t bufferSize, bool force_scalar=false) const
void notify () const
bool save (bool force_save=false)
bool load (void)
void set_float (float value, enum ap_var_type var_type)
float cast_to_float (enum ap_var_type type) const
cast a variable to a float given its type
bool configured_in_defaults_file (void) const
bool configured_in_storage (void) const
bool configured (void) const
Static Public Member Functions
static bool setup ()
static bool initialised (void)
static uint32_t group_id (const struct GroupInfo *grpinfo, uint32_t base, uint8_t i, uint8_t shift)
static AP_Param * find (const char *name, enum ap_var_type *ptype)
static bool set_default_by_name (const char *name, float value)
static AP_Param * find_by_index (uint16_t idx, enum ap_var_type *ptype, ParamToken *token)
static bool find_key_by_pointer_group (const void *ptr, uint16_t vindex, const struct GroupInfo *group_info, ptrdiff_t offset, uint16_t &key)
static bool find_key_by_pointer (const void *ptr, uint16_t &key)
static AP_Param * find_object (const char *name)
static bool load_all (bool check_defaults_file=true)
static void reload_defaults_file (bool panic_on_error=true)
static void load_object_from_eeprom (const void *object_pointer, const struct GroupInfo *group_info)
static void set_value (enum ap_var_type type, void *ptr, float def_value)
static void setup_object_defaults (const void *object_pointer, const struct GroupInfo *group_info)
static bool set_object_value (const void *object_pointer, const struct GroupInfo *group_info, const char *name, float value)
static void setup_sketch_defaults (void)
static bool find_old_parameter (const struct ConversionInfo *info, AP_Param *value)
static void convert_old_parameters (const struct ConversionInfo *conversion_table, uint8_t table_size, uint8_t flags=0)
static void convert_old_parameter (const struct ConversionInfo *info, float scaler, uint8_t flags=0)
static void convert_parent_class (uint8_t param_key, void *object_pointer, const struct AP_Param::GroupInfo *group_info)
static void erase_all (void)
static void show_all (AP_HAL::BetterStream *port, bool showKeyValues=false)
print the value of all variables
static void show (const AP_Param *param, const char *name, enum ap_var_type ptype, AP_HAL::BetterStream *port)
print the value of one variable
static void show (const AP_Param *param, const ParamToken &token, enum ap_var_type ptype, AP_HAL::BetterStream *port)
print the value of one variable
static AP_Param * first (ParamToken *token, enum ap_var_type *ptype)
static AP_Param * next (ParamToken *token, enum ap_var_type *ptype)
static AP_Param * next_scalar (ParamToken *token, enum ap_var_type *ptype)
static bool check_var_info (void)
static uint16_t count_parameters (void)
static void set_hide_disabled_groups (bool value)
static void set_frame_type_flags (uint16_t flags_to_set)
static bool check_frame_type (uint16_t flags)
Private Member Functions
const struct Info * find_var_info_group (const struct GroupInfo *group_info, uint16_t vindex, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
const struct Info * find_var_info (uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
const struct Info * find_var_info_token (const ParamToken &token, uint32_t *group_element, const struct GroupInfo *&group_ret, struct GroupNesting &group_nesting, uint8_t *idx) const
void add_vector3f_suffix (char *buffer, size_t buffer_size, uint8_t idx) const
void send_parameter (const char *name, enum ap_var_type param_header_type, uint8_t idx) const
Static Private Member Functions
static bool check_group_info (const struct GroupInfo *group_info, uint16_t *total_size, uint8_t max_bits, uint8_t prefix_length)
static bool duplicate_key (uint16_t vindex, uint16_t key)
static bool adjust_group_offset (uint16_t vindex, const struct GroupInfo &group_info, ptrdiff_t &new_offset)
static bool get_base (const struct Info &info, ptrdiff_t &base)
static const struct GroupInfo * get_group_info (const struct GroupInfo &ginfo)
get group_info pointer based on flags
static const struct GroupInfo * get_group_info (const struct Info &ginfo)
get group_info pointer based on flags
static const struct Info * find_by_header_group (struct Param_header phdr, void **ptr, uint16_t vindex, const struct GroupInfo *group_info, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset)
static const struct Info * find_by_header (struct Param_header phdr, void **ptr)
static AP_Param * find_group (const char *name, uint16_t vindex, ptrdiff_t group_offset, const struct GroupInfo *group_info, enum ap_var_type *ptype)
static void write_sentinal (uint16_t ofs)
static uint16_t get_key (const Param_header &phdr)
static void set_key (Param_header &phdr, uint16_t key)
static bool is_sentinal (const Param_header &phrd)
static bool scan (const struct Param_header *phdr, uint16_t *pofs)
static uint8_t type_size (enum ap_var_type type)
static void eeprom_write_check (const void *ptr, uint16_t ofs, uint8_t size)
static AP_Param * next_group (uint16_t vindex, const struct GroupInfo *group_info, bool *found_current, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, ParamToken *token, enum ap_var_type *ptype)
static float get_default_value (const AP_Param *object_ptr, const float *def_value_ptr)
Static Private Attributes
static const uint8_t _group_level_shift = 6
static const uint8_t _group_bits = 18
static const uint16_t _sentinal_key = 0x1FF
static const uint8_t _sentinal_type = 0x1F
static const uint8_t _sentinal_group = 0xFF
static uint16_t _frame_type_flags
static StorageAccess _storage
static uint16_t _num_vars
static uint16_t _parameter_count
static const struct Info * _var_info
static struct param_override * param_overrides = nullptr
static uint16_t num_param_overrides = 0
static const uint8_t k_EEPROM_magic0 = 0x50
static const uint8_t k_EEPROM_magic1 = 0x41
"AP"
static const uint8_t k_EEPROM_revision = 6
current format revision
static bool _hide_disabled_groups = true
Detailed Description
Base class for variables.
Provides naming and lookup services for variables.
Definition at line 120 of file AP_Param.h.
Member Enumeration Documentation
anonymous enum
Enumerator
CONVERT_FLAG_REVERSE
CONVERT_FLAG_FORCE
Definition at line 330 of file AP_Param.h.
Constructor & Destructor Documentation
AP_Param::AP_Param (const struct Info * info) inline
Definition at line 163 of file AP_Param.h.
AP_Param::AP_Param () inline
Definition at line 172 of file AP_Param.h.
Member Function Documentation
void AP_Param::add_vector3f_suffix (char * buffer, size_t buffer_size, uint8_t idx) const private
add a _X, _Y, _Z suffix to the name of a Vector3f element
Parameters
buffer
buffer_size
idx Suffix: 0 –> _X; 1 –> _Y; 2 –> _Z; (other –> undefined)
Definition at line 679 of file AP_Param.cpp.
Referenced by copy_name_info().
bool AP_Param::adjust_group_offset (uint16_t vindex, const struct GroupInfo & group_info, ptrdiff_t & new_offset) static private
Definition at line 314 of file AP_Param.cpp.
Referenced by find_by_header_group(), find_group(), find_key_by_pointer_group(), find_var_info_group(), load_object_from_eeprom(), and next_group().
float AP_Param::cast_to_float (enum ap_var_type type) const
cast a variable to a float given its type
Definition at line 1562 of file AP_Param.cpp.
Referenced by convert_old_parameter(), GCS_MAVLINK::handle_param_request_read(), GCS_MAVLINK::handle_param_set(), DataFlash_Backend::Log_Write_Parameter(), GCS_MAVLINK::queued_param_send(), save(), and send_parameter().
bool AP_Param::check_frame_type (uint16_t flags) static
Definition at line 139 of file AP_Param.cpp.
Referenced by next(), next_group(), and set_frame_type_flags().
bool AP_Param::check_group_info (const struct GroupInfo * group_info, uint16_t * total_size, uint8_t max_bits, uint8_t prefix_length) static private
Definition at line 149 of file AP_Param.cpp.
Referenced by check_var_info().
bool AP_Param::check_var_info (void) static
Definition at line 238 of file AP_Param.cpp.
bool AP_Param::configured (void) const inline
Definition at line 387 of file AP_Param.h.
Referenced by AP_ParamT< T, PT >::set_default().
bool AP_Param::configured_in_defaults_file (void) const
Definition at line 1150 of file AP_Param.cpp.
Referenced by configured().
bool AP_Param::configured_in_storage (void) const
Definition at line 1120 of file AP_Param.cpp.
Referenced by configured(), convert_old_parameter(), and set_float().
void AP_Param::convert_old_parameter (const struct ConversionInfo * info, float scaler, uint8_t flags = 0) static
Definition at line 1653 of file AP_Param.cpp.
Referenced by convert_old_parameters().
void AP_Param::convert_old_parameters (const struct ConversionInfo * conversion_table, uint8_t table_size, uint8_t flags = 0) static
Definition at line 1711 of file AP_Param.cpp.
void AP_Param::convert_parent_class (uint8_t param_key, void * object_pointer, const struct AP_Param::GroupInfo * group_info) static
Definition at line 1725 of file AP_Param.cpp.
void AP_Param::copy_name_info (const struct AP_Param::Info * info, const struct GroupInfo * ginfo, const struct GroupNesting & group_nesting, uint8_t idx, char * buffer, size_t bufferSize, bool force_scalar = false) const
Copy the variable's name, prefixed by any containing group name, to a buffer.
If the variable has no name, the buffer will contain an empty string.
Note that if the combination of names is larger than the buffer, the result in the buffer will be truncated.
Parameters
token token giving current variable
buffer The destination buffer
bufferSize Total size of the destination buffer.
Definition at line 710 of file AP_Param.cpp.
Referenced by copy_name_token(), notify(), and save().
void AP_Param::copy_name_token (const ParamToken & token, char * buffer, size_t bufferSize, bool force_scalar = false) const
Copy the variable's name, prefixed by any containing group name, to a buffer.
Uses token to look up AP_Param::Info for the variable
Definition at line 695 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::handle_param_request_read(), DataFlash_Backend::Log_Write_Parameter(), GCS_MAVLINK::queued_param_send(), and show().
uint16_t AP_Param::count_parameters (void) static
Definition at line 1989 of file AP_Param.cpp.
Referenced by configured(), GCS_MAVLINK::handle_param_request_list(), GCS_MAVLINK::handle_param_request_read(), and GCS_MAVLINK::send_parameter_value_all().
bool AP_Param::duplicate_key (uint16_t vindex, uint16_t key) static private
Definition at line 203 of file AP_Param.cpp.
Referenced by check_var_info().
void AP_Param::eeprom_write_check (const void * ptr, uint16_t ofs, uint8_t size) static private
Definition at line 78 of file AP_Param.cpp.
Referenced by erase_all(), save(), and write_sentinal().
void AP_Param::erase_all (void) static
Erase all variables in EEPROM.
Definition at line 97 of file AP_Param.cpp.
Referenced by HALSITL::SITL_State::_parse_command_line(), and setup().
AP_Param * AP_Param::find (const char * name, enum ap_var_type * ptype) static
Find a variable by name.
If the variable has no name, it cannot be found by this interface.
Parameters
name The full name of the variable to be found.
Returns
A pointer to the variable, or nullptr if it does not exist.
Definition at line 802 of file AP_Param.cpp.
Referenced by HALSITL::SITL_State::_set_param_default(), AP_Proximity_SITL::AP_Proximity_SITL(), convert_old_parameter(), GCS_MAVLINK::handle_param_request_read(), GCS_MAVLINK::handle_param_set(), set_default_by_name(), and set_float().
const struct AP_Param::Info * AP_Param::find_by_header (struct Param_header phdr, void ** ptr) static private
Definition at line 405 of file AP_Param.cpp.
Referenced by load_all(), and load_object_from_eeprom().
const struct AP_Param::Info * AP_Param::find_by_header_group (struct Param_header phdr, void ** ptr, uint16_t vindex, const struct GroupInfo * group_info, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset) static private
Definition at line 354 of file AP_Param.cpp.
Referenced by find_by_header().
AP_Param * AP_Param::find_by_index (uint16_t idx, enum ap_var_type * ptype, ParamToken * token) static
Find a variable by index.
Parameters
idx The index of the variable
Returns
A pointer to the variable, or nullptr if it does not exist.
Definition at line 837 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::handle_param_request_read().
AP_Param * AP_Param::find_group (const char * name, uint16_t vindex, ptrdiff_t group_offset, const struct GroupInfo * group_info, enum ap_var_type * ptype) static private
Definition at line 738 of file AP_Param.cpp.
Referenced by find().
bool AP_Param::find_key_by_pointer (const void * ptr, uint16_t & key) static
Definition at line 893 of file AP_Param.cpp.
Referenced by load_object_from_eeprom().
bool AP_Param::find_key_by_pointer_group (const void * ptr, uint16_t vindex, const struct GroupInfo * group_info, ptrdiff_t offset, uint16_t & key) static
Find a variable by pointer
Parameters
p Pointer to variable
Returns
key for variable
Definition at line 853 of file AP_Param.cpp.
Referenced by find_key_by_pointer().
AP_Param * AP_Param::find_object (const char * name) static
Find a object in the top level var_info table
If the variable has no name, it cannot be found by this interface.
Parameters
name The full name of the variable to be found.
Definition at line 920 of file AP_Param.cpp.
Referenced by HALSITL::SITL_State::_sitl_setup(), SITL::Aircraft::Aircraft(), AP_Beacon_SITL::AP_Beacon_SITL(), AP_OpticalFlow_SITL::AP_OpticalFlow_SITL(), AP_Proximity_SITL::AP_Proximity_SITL(), AP_RPM_SITL::AP_RPM_SITL(), AP_IRLock_SITL::init(), AP_InertialSensor_SITL::init_sensor(), SITL::ADSB::update(), and AP_AHRS_NavEKF::update_SITL().
bool AP_Param::find_old_parameter (const struct ConversionInfo * info, AP_Param * value) static
Definition at line 1631 of file AP_Param.cpp.
Referenced by convert_old_parameter(), convert_parent_class(), SRV_Channels::upgrade_motors_servo(), and SRV_Channels::upgrade_parameters().
const struct AP_Param::Info * AP_Param::find_var_info (uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 507 of file AP_Param.cpp.
Referenced by configured_in_defaults_file(), configured_in_storage(), load(), notify(), and save().
const struct AP_Param::Info * AP_Param::find_var_info_group (const struct GroupInfo * group_info, uint16_t vindex, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 436 of file AP_Param.cpp.
Referenced by find_var_info(), and find_var_info_token().
const struct AP_Param::Info * AP_Param::find_var_info_token (const ParamToken & token, uint32_t * group_element, const struct GroupInfo *& group_ret, struct GroupNesting & group_nesting, uint8_t * idx) const private
Definition at line 549 of file AP_Param.cpp.
Referenced by copy_name_token(), and next_scalar().
AP_Param * AP_Param::first (ParamToken * token, enum ap_var_type * ptype) static
Returns the first variable
Returns
The first variable in _var_info, or nullptr if there are none.
Definition at line 1363 of file AP_Param.cpp.
Referenced by count_parameters(), find_by_index(), GCS_MAVLINK::handle_param_request_list(), DFMessageWriter_DFLogStart::reset(), and show_all().
bool AP_Param::get_base (const struct Info & info, ptrdiff_t & base) static private
Definition at line 341 of file AP_Param.cpp.
Referenced by adjust_group_offset(), find(), find_by_header(), find_by_header_group(), find_group(), find_key_by_pointer_group(), find_object(), find_var_info(), find_var_info_group(), find_var_info_token(), first(), load(), next_group(), and setup_sketch_defaults().
float AP_Param::get_default_value (const AP_Param * object_ptr, const float * def_value_ptr) static private
Definition at line 1942 of file AP_Param.cpp.
Referenced by load(), save(), setup_object_defaults(), and setup_sketch_defaults().
const struct AP_Param::GroupInfo * AP_Param::get_group_info (const struct GroupInfo & ginfo) static private
get group_info pointer based on flags
Definition at line 218 of file AP_Param.cpp.
Referenced by check_group_info(), check_var_info(), find(), find_by_header(), find_by_header_group(), find_group(), find_key_by_pointer(), find_key_by_pointer_group(), find_var_info(), find_var_info_group(), find_var_info_token(), load_object_from_eeprom(), next(), and next_group().
const struct AP_Param::GroupInfo * AP_Param::get_group_info (const struct Info & ginfo) static private
get group_info pointer based on flags
Definition at line 229 of file AP_Param.cpp.
uint16_t AP_Param::get_key (const Param_header & phdr) static private
Definition at line 614 of file AP_Param.cpp.
Referenced by find_by_header(), is_sentinal(), load_object_from_eeprom(), and scan().
uint32_t AP_Param::group_id (const struct GroupInfo * grpinfo, uint32_t base, uint8_t i, uint8_t shift) static
Definition at line 119 of file AP_Param.cpp.
Referenced by find_by_header_group(), find_var_info_group(), and next_group().
bool AP_Param::initialised (void) static
Definition at line 303 of file AP_Param.cpp.
bool AP_Param::is_sentinal (const Param_header & phrd) static private
Definition at line 631 of file AP_Param.cpp.
Referenced by load_all(), load_object_from_eeprom(), and scan().
bool AP_Param::load (void)
Load the variable from EEPROM.
Returns
True if the variable was loaded successfully.
Definition at line 1057 of file AP_Param.cpp.
bool AP_Param::load_all (bool check_defaults_file = true) static
Load all variables from EEPROM
This function performs a best-efforts attempt to load all of the variables from EEPROM. If some fail to load, their values will remain as they are.
Returns
False if any variable failed to load
Definition at line 1253 of file AP_Param.cpp.
void AP_Param::load_object_from_eeprom (const void * object_pointer, const struct GroupInfo * group_info) static
Definition at line 1311 of file AP_Param.cpp.
Referenced by AP_BoardConfig::px4_setup_canbus().
AP_Param * AP_Param::next (ParamToken * token, enum ap_var_type * ptype) static
Returns the next variable in _var_info, recursing into groups as needed
Definition at line 1457 of file AP_Param.cpp.
Referenced by next_scalar().
AP_Param * AP_Param::next_group (uint16_t vindex, const struct GroupInfo * group_info, bool * found_current, uint32_t group_base, uint8_t group_shift, ptrdiff_t group_offset, ParamToken * token, enum ap_var_type * ptype) static private
Returns the next variable in a group, recursing into groups as needed
Definition at line 1384 of file AP_Param.cpp.
Referenced by next().
AP_Param * AP_Param::next_scalar (ParamToken * token, enum ap_var_type * ptype) static
Returns the next scalar variable in _var_info, recursing into groups as needed
Returns the next scalar in _var_info, recursing into groups as needed
Definition at line 1511 of file AP_Param.cpp.
Referenced by count_parameters(), find_by_index(), DFMessageWriter_DFLogStart::process(), GCS_MAVLINK::queued_param_send(), and show_all().
void AP_Param::notify () const
Notify GCS of current parameter value
Definition at line 935 of file AP_Param.cpp.
Referenced by AP_ParamT< T, PT >::set_and_notify(), and AP_ParamV< T, PT >::set_and_notify().
void AP_Param::reload_defaults_file (bool panic_on_error = true) static
reoad the hal.util defaults file. Called after pointer parameters have been allocated
Definition at line 1288 of file AP_Param.cpp.
Referenced by load_all().
bool AP_Param::save (bool force_save = false)
Save the current value of the variable to EEPROM.
Parameters
force_save If true then force save even if default
Returns
True if the variable was saved successfully.
Definition at line 963 of file AP_Param.cpp.
Referenced by convert_old_parameter(), GCS_MAVLINK::handle_param_set(), AP_ParamT< T, PT >::set_and_save(), AP_ParamV< T, PT >::set_and_save(), and AP_ParamT< T, PT >::set_and_save_ifchanged().
bool AP_Param::scan (const struct Param_header * phdr, uint16_t * pofs) static private
Definition at line 648 of file AP_Param.cpp.
Referenced by configured_in_storage(), find_old_parameter(), load(), and save().
void AP_Param::send_parameter (const char * name, enum ap_var_type param_header_type, uint8_t idx) const private
Definition at line 1953 of file AP_Param.cpp.
Referenced by notify(), and save().
bool AP_Param::set_default_by_name (const char * name, float value) static
set a default value by name
Parameters
name The full name of the variable to be found.
value The default value
Returns
true if the variable is found
Definition at line 2007 of file AP_Param.cpp.
Referenced by SITL::FlightAxis::FlightAxis(), AP_BoardConfig::px4_setup_pwm(), and SITL::XPlane::XPlane().
void AP_Param::set_float (float value, enum ap_var_type var_type)
Definition at line 1751 of file AP_Param.cpp.
Referenced by GCS_MAVLINK::handle_param_set(), and set_float().
static void AP_Param::set_frame_type_flags (uint16_t flags_to_set) inline static
Definition at line 395 of file AP_Param.h.
static void AP_Param::set_hide_disabled_groups (bool value) inline static
Definition at line 392 of file AP_Param.h.
Referenced by HALSITL::SITL_State::_parse_command_line().
void AP_Param::set_key (Param_header & phdr, uint16_t key) static private
Definition at line 622 of file AP_Param.cpp.
Referenced by configured_in_storage(), find_old_parameter(), load(), save(), and write_sentinal().
bool AP_Param::set_object_value (const void * object_pointer, const struct GroupInfo * group_info, const char * name, float value) static
Definition at line 1212 of file AP_Param.cpp.
Referenced by setup().
void AP_Param::set_value (enum ap_var_type type, void * ptr, float def_value) static
Definition at line 1172 of file AP_Param.cpp.
Referenced by convert_old_parameter(), load(), set_object_value(), setup_object_defaults(), and setup_sketch_defaults().
bool AP_Param::setup (void) static
Definition at line 284 of file AP_Param.cpp.
Referenced by setup_sketch_defaults().
void AP_Param::setup_object_defaults (const void * object_pointer, const struct GroupInfo * group_info) static
Definition at line 1195 of file AP_Param.cpp.
Referenced by AC_AttitudeControl::AC_AttitudeControl(), AC_AttitudeControl_Heli::AC_AttitudeControl_Heli(), AC_AttitudeControl_Multi::AC_AttitudeControl_Multi(), AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), AC_Avoid::AC_Avoid(), AC_Circle::AC_Circle(), AC_Fence::AC_Fence(), AC_InputManager::AC_InputManager(), AC_InputManager_Heli::AC_InputManager_Heli(), AC_P::AC_P(), AC_PI_2D::AC_PI_2D(), AC_PID::AC_PID(), AC_PosControl::AC_PosControl(), AC_PrecLand::AC_PrecLand(), AC_Sprayer::AC_Sprayer(), AC_WPNav::AC_WPNav(), AP_ADSB::AP_ADSB(), AP_AdvancedFailsafe::AP_AdvancedFailsafe(), AP_AHRS::AP_AHRS(), AP_Airspeed::AP_Airspeed(), AP_Arming::AP_Arming(), AP_Avoidance::AP_Avoidance(), AP_Baro::AP_Baro(), AP_BattMonitor::AP_BattMonitor(), AP_Beacon::AP_Beacon(), AP_BoardConfig::AP_BoardConfig(), AP_Button::AP_Button(), AP_Camera::AP_Camera(), AP_GPS::AP_GPS(), AP_Gripper::AP_Gripper(), AP_ICEngine::AP_ICEngine(), AP_InertialSensor::AP_InertialSensor(), AP_L1_Control::AP_L1_Control(), AP_Landing::AP_Landing(), AP_Landing_Deepstall::AP_Landing_Deepstall(), AP_LandingGear::AP_LandingGear(), AP_LeakDetector::AP_LeakDetector(), AP_Mission::AP_Mission(), AP_Motors6DOF::AP_Motors6DOF(), AP_MotorsHeli::AP_MotorsHeli(), AP_MotorsHeli_Dual::AP_MotorsHeli_Dual(), AP_MotorsHeli_Single::AP_MotorsHeli_Single(), AP_MotorsMulticopter::AP_MotorsMulticopter(), AP_Mount::AP_Mount(), AP_Notify::AP_Notify(), AP_Parachute::AP_Parachute(), AP_PitchController::AP_PitchController(), AP_Proximity::AP_Proximity(), AP_Rally::AP_Rally(), AP_Relay::AP_Relay(), AP_RollController::AP_RollController(), AP_RPM::AP_RPM(), AP_RSSI::AP_RSSI(), AP_Scheduler::AP_Scheduler(), AP_SerialManager::AP_SerialManager(), AP_SteerController::AP_SteerController(), AP_TECS::AP_TECS(), AP_Tuning::AP_Tuning(), AP_YawController::AP_YawController(), Compass::Compass(), DataFlash_Class::DataFlash_Class(), GCS_MAVLINK::GCS_MAVLINK(), JSButton::JSButton(), NavEKF2::NavEKF2(), NavEKF3::NavEKF3(), OpticalFlow::OpticalFlow(), PID::PID(), RangeFinder::RangeFinder(), RC_Channel::RC_Channel(), RC_Channels::RC_Channels(), RCMapper::RCMapper(), SITL::SITL::SITL(), SoaringController::SoaringController(), SoloGimbalEKF::SoloGimbalEKF(), SRV_Channel::SRV_Channel(), and SRV_Channels::SRV_Channels().
void AP_Param::setup_sketch_defaults (void) static
Definition at line 1235 of file AP_Param.cpp.
void AP_Param::show (const AP_Param * param, const char * name, enum ap_var_type ptype, AP_HAL::BetterStream * port) static
print the value of one variable
Definition at line 1580 of file AP_Param.cpp.
Referenced by show(), and show_all().
void AP_Param::show (const AP_Param * param, const ParamToken & token, enum ap_var_type ptype, AP_HAL::BetterStream * port) static
print the value of one variable
Definition at line 1602 of file AP_Param.cpp.
void AP_Param::show_all (AP_HAL::BetterStream * port, bool showKeyValues = false) static
print the value of all variables
Definition at line 1612 of file AP_Param.cpp.
uint8_t AP_Param::type_size (enum ap_var_type type) static private
Definition at line 590 of file AP_Param.cpp.
Referenced by check_group_info(), check_var_info(), convert_old_parameter(), convert_parent_class(), find_old_parameter(), load(), load_all(), load_object_from_eeprom(), save(), and scan().
void AP_Param::write_sentinal (uint16_t ofs) static private
Definition at line 86 of file AP_Param.cpp.
Referenced by erase_all(), and save().
Member Data Documentation
uint16_t AP_Param::_frame_type_flags static private
Definition at line 442 of file AP_Param.h.
Referenced by check_frame_type(), and set_frame_type_flags().
const uint8_t AP_Param::_group_bits = 18 static private
Definition at line 436 of file AP_Param.h.
Referenced by check_group_info(), find_by_header_group(), and find_var_info_group().
const uint8_t AP_Param::_group_level_shift = 6 static private
Definition at line 435 of file AP_Param.h.
Referenced by check_group_info(), find_by_header_group(), find_var_info_group(), and next_group().
bool AP_Param::_hide_disabled_groups = true static private
Definition at line 555 of file AP_Param.h.
Referenced by eeprom_write_check(), next_scalar(), and set_hide_disabled_groups().
uint16_t AP_Param::_num_vars static private
Definition at line 536 of file AP_Param.h.
Referenced by AP_Param(), check_var_info(), duplicate_key(), find(), find_by_header(), find_key_by_pointer(), find_object(), find_var_info(), first(), next(), and setup_sketch_defaults().
uint16_t AP_Param::_parameter_count static private
Definition at line 537 of file AP_Param.h.
Referenced by count_parameters(), load_object_from_eeprom(), and save().
const uint8_t AP_Param::_sentinal_group = 0xFF static private
Definition at line 440 of file AP_Param.h.
Referenced by is_sentinal(), and write_sentinal().
const uint16_t AP_Param::_sentinal_key = 0x1FF static private
Definition at line 438 of file AP_Param.h.
Referenced by is_sentinal(), and write_sentinal().
const uint8_t AP_Param::_sentinal_type = 0x1F static private
Definition at line 439 of file AP_Param.h.
Referenced by is_sentinal(), and write_sentinal().
StorageAccess AP_Param::_storage static private
Definition at line 535 of file AP_Param.h.
Referenced by eeprom_write_check(), find_old_parameter(), load(), load_all(), load_object_from_eeprom(), save(), scan(), and setup().
const AP_Param::Info * AP_Param::_var_info static private
Definition at line 538 of file AP_Param.h.
Referenced by adjust_group_offset(), AP_Param(), check_var_info(), duplicate_key(), find(), find_by_header(), find_by_header_group(), find_group(), find_key_by_pointer(), find_key_by_pointer_group(), find_object(), find_var_info(), find_var_info_group(), find_var_info_token(), first(), initialised(), next(), next_group(), and setup_sketch_defaults().
const uint8_t AP_Param::k_EEPROM_magic0 = 0x50 static private
Definition at line 551 of file AP_Param.h.
Referenced by erase_all(), and setup().
const uint8_t AP_Param::k_EEPROM_magic1 = 0x41 static private
"AP"
Definition at line 552 of file AP_Param.h.
Referenced by erase_all(), and setup().
const uint8_t AP_Param::k_EEPROM_revision = 6 static private
current format revision
Definition at line 553 of file AP_Param.h.
Referenced by erase_all(), and setup().
uint16_t AP_Param::num_param_overrides = 0 static private
Definition at line 548 of file AP_Param.h.
Referenced by configured_in_defaults_file(), get_default_value(), and set_float().
struct AP_Param::param_override * AP_Param::param_overrides = nullptr static private
Definition at line 547 of file AP_Param.h.
Referenced by configured_in_defaults_file(), get_default_value(), and set_float().
The documentation for this class was generated from the following files:
libraries/AP_Param/AP_Param.h
libraries/AP_Param/AP_Param.cpp