APM:Libraries: AP_BattMonitor_Backend Class Reference
AP_BattMonitor_Backend Class Reference abstract
#include <AP_BattMonitor_Backend.h>
Public Member Functions
AP_BattMonitor_Backend (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state)
virtual ~AP_BattMonitor_Backend (void)
virtual void init ()
virtual void read ()=0
uint8_t capacity_remaining_pct () const
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
void set_capacity (uint32_t capacity)
set capacity for this instance
int32_t get_capacity () const
get capacity for this instance
Protected Attributes
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
uint8_t _instance
Detailed Description
Definition at line 21 of file AP_BattMonitor_Backend.h.
Constructor & Destructor Documentation
AP_BattMonitor_Backend::AP_BattMonitor_Backend (AP_BattMonitor & mon, uint8_t instance, AP_BattMonitor::BattMonitor_State & mon_state)
Definition at line 25 of file AP_BattMonitor_Backend.cpp.
virtual AP_BattMonitor_Backend::~AP_BattMonitor_Backend (void) inline virtual
Definition at line 29 of file AP_BattMonitor_Backend.h.
Member Function Documentation
uint8_t AP_BattMonitor_Backend::capacity_remaining_pct () const
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
Definition at line 33 of file AP_BattMonitor_Backend.cpp.
Referenced by AP_BattMonitor::capacity_remaining_pct(), and init().
int32_t AP_BattMonitor_Backend::get_capacity () const
get capacity for this instance
Definition at line 50 of file AP_BattMonitor_Backend.cpp.
Referenced by init(), and AP_BattMonitor_SMBus_Solo::timer().
virtual void AP_BattMonitor_Backend::init (void) inline virtual
Reimplemented in AP_BattMonitor_Bebop.
Definition at line 32 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor::init().
virtual void AP_BattMonitor_Backend::read () pure virtual
Implemented in AP_BattMonitor_Analog, AP_BattMonitor_Bebop, AP_BattMonitor_SMBus_Maxell, and AP_BattMonitor_SMBus_Solo.
Referenced by init(), and AP_BattMonitor::read().
void AP_BattMonitor_Backend::set_capacity (uint32_t capacity)
set capacity for this instance
Definition at line 44 of file AP_BattMonitor_Backend.cpp.
Referenced by init(), and AP_BattMonitor_SMBus_Solo::timer().
Member Data Documentation
uint8_t AP_BattMonitor_Backend::_instance protected
Definition at line 49 of file AP_BattMonitor_Backend.h.
Referenced by get_capacity(), and set_capacity().
AP_BattMonitor& AP_BattMonitor_Backend::_mon protected
Definition at line 47 of file AP_BattMonitor_Backend.h.
Referenced by capacity_remaining_pct(), get_capacity(), AP_BattMonitor_Analog::read(), and set_capacity().
AP_BattMonitor::BattMonitor_State& AP_BattMonitor_Backend::_state protected
Definition at line 48 of file AP_BattMonitor_Backend.h.
Referenced by AP_BattMonitor_Analog::AP_BattMonitor_Analog(), capacity_remaining_pct(), AP_BattMonitor_Analog::read(), AP_BattMonitor_SMBus_Solo::timer(), and AP_BattMonitor_SMBus_Maxell::timer().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_Backend.h
libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp