APM:Libraries: AP_BattMonitor_SMBus_Maxell Class Reference
AP_BattMonitor_SMBus_Maxell Class Reference
#include <AP_BattMonitor_SMBus_Maxell.h>
Public Member Functions
AP_BattMonitor_SMBus_Maxell (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
void read () override
Read the battery voltage and current. Should be called at 10hz.
Public Member Functions inherited from AP_BattMonitor_SMBus
AP_BattMonitor_SMBus (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state)
Constructor.
virtual ~AP_BattMonitor_SMBus ()
Public Member Functions inherited from AP_BattMonitor_Backend
AP_BattMonitor_Backend (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state)
virtual ~AP_BattMonitor_Backend (void)
virtual void init ()
uint8_t capacity_remaining_pct () const
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
void set_capacity (uint32_t capacity)
set capacity for this instance
int32_t get_capacity () const
get capacity for this instance
Private Member Functions
void timer (void)
bool read_word (uint8_t reg, uint16_t &data) const
bool check_pec_support ()
uint8_t read_block (uint8_t reg, uint8_t *data, bool append_zero) const
uint8_t get_PEC (const uint8_t i2c_addr, uint8_t cmd, bool reading, const uint8_t buff[], uint8_t len) const
get_PEC - calculate packet error correction code of buffer
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
uint8_t _pec_confirmed
bool _pec_supported
Additional Inherited Members
Protected Attributes inherited from AP_BattMonitor_Backend
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
uint8_t _instance
Detailed Description
Definition at line 9 of file AP_BattMonitor_SMBus_Maxell.h.
Constructor & Destructor Documentation
AP_BattMonitor_SMBus_Maxell::AP_BattMonitor_SMBus_Maxell (AP_BattMonitor & mon, uint8_t instance, AP_BattMonitor::BattMonitor_State & mon_state, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
Definition at line 45 of file AP_BattMonitor_SMBus_Maxell.cpp.
Member Function Documentation
bool AP_BattMonitor_SMBus_Maxell::check_pec_support () private
Definition at line 164 of file AP_BattMonitor_SMBus_Maxell.cpp.
Referenced by timer().
uint8_t AP_BattMonitor_SMBus_Maxell::get_PEC (const uint8_t i2c_addr, uint8_t cmd, bool reading, const uint8_t buff[], uint8_t len) const private
get_PEC - calculate packet error correction code of buffer
Definition at line 205 of file AP_BattMonitor_SMBus_Maxell.cpp.
Referenced by read_block(), and read_word().
void AP_BattMonitor_SMBus_Maxell::read (void) override virtual
Read the battery voltage and current. Should be called at 10hz.
Implements AP_BattMonitor_Backend.
Definition at line 55 of file AP_BattMonitor_SMBus_Maxell.cpp.
uint8_t AP_BattMonitor_SMBus_Maxell::read_block (uint8_t reg, uint8_t * data, bool append_zero) const private
Definition at line 119 of file AP_BattMonitor_SMBus_Maxell.cpp.
Referenced by check_pec_support().
bool AP_BattMonitor_SMBus_Maxell::read_word (uint8_t reg, uint16_t & data) const private
Definition at line 92 of file AP_BattMonitor_SMBus_Maxell.cpp.
Referenced by check_pec_support(), and timer().
void AP_BattMonitor_SMBus_Maxell::timer (void) private
Definition at line 60 of file AP_BattMonitor_SMBus_Maxell.cpp.
Referenced by AP_BattMonitor_SMBus_Maxell().
Member Data Documentation
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_BattMonitor_SMBus_Maxell::_dev private
Definition at line 40 of file AP_BattMonitor_SMBus_Maxell.h.
Referenced by AP_BattMonitor_SMBus_Maxell(), read_block(), and read_word().
uint8_t AP_BattMonitor_SMBus_Maxell::_pec_confirmed private
Definition at line 41 of file AP_BattMonitor_SMBus_Maxell.h.
Referenced by check_pec_support().
bool AP_BattMonitor_SMBus_Maxell::_pec_supported private
Definition at line 42 of file AP_BattMonitor_SMBus_Maxell.h.
Referenced by check_pec_support(), read_block(), and read_word().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Maxell.h
libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Maxell.cpp