APM:Libraries: AP_BoardConfig Class Reference
AP_BoardConfig Class Reference
#include <AP_BoardConfig.h>
Public Types
enum px4_board_type {
PX4_BOARD_AUTO = 0, PX4_BOARD_PX4V1 = 1, PX4_BOARD_PIXHAWK = 2, PX4_BOARD_PIXHAWK2 = 3,
PX4_BOARD_PIXRACER = 4, PX4_BOARD_PHMINI = 5, PX4_BOARD_PH2SLIM = 6, PX4_BOARD_AEROFC = 7,
PX4_BOARD_AUAV21 = 20, PX4_BOARD_OLDDRIVERS = 100, VRX_BOARD_BRAIN51 = 7, VRX_BOARD_BRAIN52 = 8,
VRX_BOARD_UBRAIN51 = 9, VRX_BOARD_UBRAIN52 = 10, VRX_BOARD_CORE10 = 11, VRX_BOARD_BRAIN54 = 12
}
Public Member Functions
AP_BoardConfig (void)
void init (void)
void set_default_safety_ignore_mask (uint16_t mask)
Static Public Member Functions
static bool px4_start_driver (main_fn_t main_function, const char *name, const char *arguments)
static void px4_sensor_error (const char *reason)
static enum px4_board_type get_board_type (void)
static int8_t get_can_enable ()
static int8_t get_can_debug ()
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void px4_drivers_start (void)
void px4_setup (void)
void px4_setup_pwm (void)
void px4_setup_safety (void)
void px4_setup_safety_mask (void)
void px4_setup_uart (void)
void px4_setup_sbus (void)
void px4_setup_canbus (void)
void px4_setup_drivers (void)
void px4_setup_peripherals (void)
void px4_setup_px4io (void)
void px4_tone_alarm (const char *tone_string)
bool spi_check_register (const char *devname, uint8_t regnum, uint8_t value, uint8_t read_flag=0x80)
void px4_autodetect (void)
Private Attributes
AP_Int16 vehicleSerialNumber
struct {
AP_Int8 pwm_count
AP_Int8 safety_enable
AP_Int32 ignore_safety_channels
AP_Int8 ser1_rtscts
AP_Int8 ser2_rtscts
AP_Int8 sbus_out_rate
AP_Int8 board_type
AP_Int8 io_enable
} px4
AP_Int8 _imu_target_temperature
Static Private Attributes
static enum px4_board_type px4_configured_board
Detailed Description
Definition at line 20 of file AP_BoardConfig.h.
Member Enumeration Documentation
enum AP_BoardConfig::px4_board_type
Enumerator
PX4_BOARD_AUTO
PX4_BOARD_PX4V1
PX4_BOARD_PIXHAWK
PX4_BOARD_PIXHAWK2
PX4_BOARD_PIXRACER
PX4_BOARD_PHMINI
PX4_BOARD_PH2SLIM
PX4_BOARD_AEROFC
PX4_BOARD_AUAV21
PX4_BOARD_OLDDRIVERS
VRX_BOARD_BRAIN51
VRX_BOARD_BRAIN52
VRX_BOARD_UBRAIN51
VRX_BOARD_UBRAIN52
VRX_BOARD_CORE10
VRX_BOARD_BRAIN54
Definition at line 60 of file AP_BoardConfig.h.
Constructor & Destructor Documentation
AP_BoardConfig::AP_BoardConfig (void) inline
Definition at line 23 of file AP_BoardConfig.h.
Member Function Documentation
static enum px4_board_type AP_BoardConfig::get_board_type (void) inline static
Definition at line 88 of file AP_BoardConfig.h.
Referenced by Compass::_detect_backends(), AP_InertialSensor::detect_backends(), AP_Baro::init(), and OpticalFlow::init().
static int8_t AP_BoardConfig::get_can_debug () inline static
Definition at line 101 of file AP_BoardConfig.h.
Referenced by AP_GPS::detect_instance().
static int8_t AP_BoardConfig::get_can_enable () inline static
Definition at line 93 of file AP_BoardConfig.h.
Referenced by Compass::_detect_backends(), PX4::PX4RCOutput::_send_outputs(), AP_GPS::detect_instance(), and AP_Baro::init().
void AP_BoardConfig::init (void)
Definition at line 189 of file AP_BoardConfig.cpp.
Referenced by AP_BoardConfig(), SchedTest::setup(), and setup().
void AP_BoardConfig::px4_autodetect (void) private
Definition at line 471 of file px4_drivers.cpp.
Referenced by px4_setup_drivers().
void AP_BoardConfig::px4_drivers_start (void) private
void AP_BoardConfig::px4_sensor_error (const char * reason) static
Definition at line 524 of file px4_drivers.cpp.
Referenced by PX4::PX4Storage::_mtd_load(), px4_autodetect(), px4_setup_drivers(), px4_setup_peripherals(), and px4_setup_px4io().
void AP_BoardConfig::px4_setup (void) private
Definition at line 542 of file px4_drivers.cpp.
Referenced by init().
void AP_BoardConfig::px4_setup_canbus (void) private
Definition at line 210 of file px4_drivers.cpp.
Referenced by px4_setup().
void AP_BoardConfig::px4_setup_drivers (void) private
Definition at line 292 of file px4_drivers.cpp.
Referenced by px4_setup().
void AP_BoardConfig::px4_setup_peripherals (void) private
Definition at line 405 of file px4_drivers.cpp.
Referenced by px4_setup().
void AP_BoardConfig::px4_setup_pwm (void) private
Definition at line 68 of file px4_drivers.cpp.
Referenced by px4_setup().
void AP_BoardConfig::px4_setup_px4io (void) private
Definition at line 347 of file px4_drivers.cpp.
Referenced by px4_setup_peripherals().
void AP_BoardConfig::px4_setup_safety (void) private
Definition at line 160 of file px4_drivers.cpp.
Referenced by px4_setup().
void AP_BoardConfig::px4_setup_safety_mask (void) private
Definition at line 130 of file px4_drivers.cpp.
Referenced by px4_setup_safety(), and set_default_safety_ignore_mask().
void AP_BoardConfig::px4_setup_sbus (void) private
Definition at line 178 of file px4_drivers.cpp.
Referenced by px4_setup().
void AP_BoardConfig::px4_setup_uart (void) private
Definition at line 117 of file px4_drivers.cpp.
Referenced by px4_setup().
bool AP_BoardConfig::px4_start_driver (main_fn_t main_function, const char * name, const char * arguments) static
Definition at line 255 of file px4_drivers.cpp.
Referenced by PX4::PX4Storage::_mtd_load(), AP_RPM_PX4_PWM::AP_RPM_PX4_PWM(), AP_RangeFinder_PX4_PWM::detect(), OreoLED_PX4::init(), px4_setup_drivers(), px4_setup_peripherals(), px4_setup_px4io(), and px4_tone_alarm().
void AP_BoardConfig::px4_tone_alarm (const char * tone_string) private
Definition at line 339 of file px4_drivers.cpp.
Referenced by px4_setup_px4io().
void AP_BoardConfig::set_default_safety_ignore_mask (uint16_t mask)
Definition at line 209 of file AP_BoardConfig.cpp.
bool AP_BoardConfig::spi_check_register (const char * devname, uint8_t regnum, uint8_t value, uint8_t read_flag = 0x80) private
Definition at line 442 of file px4_drivers.cpp.
Referenced by px4_autodetect().
Member Data Documentation
AP_Int8 AP_BoardConfig::_imu_target_temperature private
Definition at line 158 of file AP_BoardConfig.h.
Referenced by init(), and px4_setup_drivers().
AP_Int8 AP_BoardConfig::board_type
Definition at line 126 of file AP_BoardConfig.h.
AP_Int32 AP_BoardConfig::ignore_safety_channels
Definition at line 120 of file AP_BoardConfig.h.
AP_Int8 AP_BoardConfig::io_enable
Definition at line 127 of file AP_BoardConfig.h.
AP_Int8 AP_BoardConfig::pwm_count
Definition at line 118 of file AP_BoardConfig.h.
struct { ... } AP_BoardConfig::px4
Referenced by px4_autodetect(), px4_setup_drivers(), px4_setup_peripherals(), px4_setup_pwm(), px4_setup_safety(), px4_setup_safety_mask(), px4_setup_sbus(), px4_setup_uart(), and set_default_safety_ignore_mask().
AP_BoardConfig::px4_board_type AP_BoardConfig::px4_configured_board static private
Definition at line 130 of file AP_BoardConfig.h.
Referenced by get_board_type(), and px4_setup_drivers().
AP_Int8 AP_BoardConfig::safety_enable
Definition at line 119 of file AP_BoardConfig.h.
AP_Int8 AP_BoardConfig::sbus_out_rate
Definition at line 124 of file AP_BoardConfig.h.
AP_Int8 AP_BoardConfig::ser1_rtscts
Definition at line 122 of file AP_BoardConfig.h.
AP_Int8 AP_BoardConfig::ser2_rtscts
Definition at line 123 of file AP_BoardConfig.h.
const AP_Param::GroupInfo AP_BoardConfig::var_info static
Definition at line 30 of file AP_BoardConfig.h.
Referenced by AP_BoardConfig().
AP_Int16 AP_BoardConfig::vehicleSerialNumber private
Definition at line 110 of file AP_BoardConfig.h.
The documentation for this class was generated from the following files:
libraries/AP_BoardConfig/AP_BoardConfig.h
libraries/AP_BoardConfig/AP_BoardConfig.cpp
libraries/AP_BoardConfig/px4_drivers.cpp