APM:Libraries: AP_InertialNav Class Reference
AP_InertialNav Class Reference abstract
#include <AP_InertialNav.h>
Public Member Functions
AP_InertialNav ()
virtual void update (float dt)=0
virtual nav_filter_status get_filter_status () const =0
virtual struct Location get_origin () const =0
virtual const Vector3f & get_position () const =0
virtual bool get_location (struct Location &loc) const =0
virtual int32_t get_latitude () const =0
virtual int32_t get_longitude () const =0
virtual const Vector3f & get_velocity () const =0
virtual float get_velocity_xy () const =0
virtual float get_altitude () const =0
virtual bool get_hgt_ctrl_limit (float &limit) const =0
virtual float get_velocity_z () const =0
Detailed Description
Definition at line 23 of file AP_InertialNav.h.
Constructor & Destructor Documentation
AP_InertialNav::AP_InertialNav () inline
Definition at line 28 of file AP_InertialNav.h.
Member Function Documentation
virtual float AP_InertialNav::get_altitude () const pure virtual
get_altitude - get latest altitude estimate in cm above the reference position
Returns
Implemented in AP_InertialNav_NavEKF.
Referenced by AC_Avoid::adjust_velocity_z(), AP_InertialNav(), AC_Avoid::get_alt_above_home(), AC_PosControl::get_alt_error(), AC_PosControl::get_stopping_point_z(), AC_WPNav::get_terrain_offset(), AC_PosControl::pos_to_rate_z(), AC_PosControl::relax_alt_hold_controllers(), AC_PosControl::set_alt_target_to_current_alt(), and AC_PosControl::set_alt_target_with_slew().
virtual nav_filter_status AP_InertialNav::get_filter_status () const pure virtual
get_filter_status : returns filter status as a series of flags
Implemented in AP_InertialNav_NavEKF.
Referenced by AP_InertialNav(), AC_Fence::pre_arm_check(), and AC_PrecLand::update().
virtual bool AP_InertialNav::get_hgt_ctrl_limit (float & limit) const pure virtual
get_hgt_ctrl_limit - get maximum height to be observed by the control loops in cm and a validity flag this is used to limit height during optical flow navigation it will return invalid when no limiting is required
Returns
Implemented in AP_InertialNav_NavEKF.
Referenced by AC_Avoid::adjust_velocity_z(), and AP_InertialNav().
virtual int32_t AP_InertialNav::get_latitude () const pure virtual
get_latitude - returns the latitude of the current position estimation in 100 nano degrees (i.e. degree value multiplied by 10,000,000)
Returns
Implemented in AP_InertialNav_NavEKF.
Referenced by AP_InertialNav().
virtual bool AP_InertialNav::get_location (struct Location & loc) const pure virtual
get_llh - updates the provided location with the latest calculated location including absolute altitude returns true on success (i.e. the EKF knows it's latest position), false on failure
Implemented in AP_InertialNav_NavEKF.
Referenced by AP_InertialNav(), AC_Fence::check_destination_within_fence(), and AC_Fence::load_polygon_from_eeprom().
virtual int32_t AP_InertialNav::get_longitude () const pure virtual
get_longitude - returns the longitude of the current position estimation in 100 nano degrees (i.e. degree value multiplied by 10,000,000)
Returns
Implemented in AP_InertialNav_NavEKF.
Referenced by AP_InertialNav().
virtual struct Location AP_InertialNav::get_origin () const pure virtual
get_origin - returns the inertial navigation origin in lat/lon/alt
Returns
origin Location
Implemented in AP_InertialNav_NavEKF.
Referenced by AC_Fence::check_destination_within_fence(), AC_Avoid::get_alt_above_home(), AC_Avoid::get_position(), and AC_Fence::load_polygon_from_eeprom().
virtual const Vector3f& AP_InertialNav::get_position () const pure virtual
get_position - returns the current position relative to the home location in cm.
Returns
Implemented in AP_InertialNav_NavEKF.
Referenced by AC_Avoid::adjust_velocity_polygon(), AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), AP_InertialNav(), AC_Fence::check_fence(), AC_Circle::get_closest_point_on_circle(), AC_WPNav::get_loiter_bearing_to_target(), AC_Avoid::get_position(), AC_PosControl::get_stopping_point_xy(), AC_PrecLand::get_target_position_cm(), AC_WPNav::get_wp_bearing_to_destination(), AC_WPNav::get_wp_distance_to_destination(), AC_WPNav::init_loiter_target(), AC_Circle::init_start_angle(), AC_PosControl::init_takeoff(), AC_PosControl::init_vel_controller_xyz(), AC_WPNav::loiter_soften_for_landing(), AC_PosControl::pos_to_rate_xy(), and AC_WPNav::shift_wp_origin_to_current_pos().
virtual const Vector3f& AP_InertialNav::get_velocity () const pure virtual
get_velocity - returns the current velocity in cm/s
Returns
velocity vector: .x : latitude velocity in cm/s .y : longitude velocity in cm/s .z : vertical velocity in cm/s
Implemented in AP_InertialNav_NavEKF.
Referenced by AC_WPNav::advance_wp_target_along_track(), AP_InertialNav(), AC_PosControl::get_stopping_point_xy(), AC_WPNav::init_brake_target(), AC_WPNav::init_loiter_target(), AC_PosControl::init_vel_controller_xyz(), AC_PosControl::rate_to_accel_xy(), AC_PosControl::rate_to_accel_z(), AC_WPNav::set_wp_origin_and_destination(), AC_Sprayer::update(), and AC_PrecLand::update().
virtual float AP_InertialNav::get_velocity_xy () const pure virtual
get_velocity_xy - returns the current horizontal velocity in cm/s
Returns
the current horizontal velocity in cm/s
Implemented in AP_InertialNav_NavEKF.
Referenced by AP_InertialNav().
virtual float AP_InertialNav::get_velocity_z () const pure virtual
get_velocity_z - returns the current climbrate.
See also
get_velocity().z
Returns
climbrate in cm/s (positive up)
Implemented in AP_InertialNav_NavEKF.
Referenced by AP_InertialNav(), AC_PosControl::get_stopping_point_z(), and AC_PosControl::relax_alt_hold_controllers().
virtual void AP_InertialNav::update (float dt) pure virtual
update - updates velocity and position estimates using latest info from accelerometers augmented with gps and baro readings
Parameters
dt : time since last update in seconds
Implemented in AP_InertialNav_NavEKF.
Referenced by AP_InertialNav().
The documentation for this class was generated from the following file:
libraries/AP_InertialNav/AP_InertialNav.h