APM:Libraries: Linux::RCInput Class Reference
Linux::RCInput Class Reference
#include <RCInput.h>
Public Member Functions
RCInput ()
virtual void init ()
bool new_input ()
uint8_t num_channels ()
uint16_t read (uint8_t ch)
uint8_t read (uint16_t *periods, uint8_t len)
bool set_overrides (int16_t *overrides, uint8_t len)
bool set_override (uint8_t channel, int16_t override)
void clear_overrides ()
virtual void _timer_tick ()
bool add_dsm_input (const uint8_t *bytes, size_t nbytes)
void add_sbus_input (const uint8_t *bytes, size_t nbytes)
bool add_sumd_input (const uint8_t *bytes, size_t nbytes)
bool add_st24_input (const uint8_t *bytes, size_t nbytes)
bool add_srxl_input (const uint8_t *bytes, size_t nbytes)
Public Member Functions inherited from AP_HAL::RCInput
virtual void teardown ()
virtual bool rc_bind (int dsmMode)
Static Public Member Functions
static RCInput * from (AP_HAL::RCInput *rcinput)
Protected Member Functions
void _process_rc_pulse (uint16_t width_s0, uint16_t width_s1)
void _update_periods (uint16_t *periods, uint8_t len)
void _process_ppmsum_pulse (uint16_t width)
void _process_sbus_pulse (uint16_t width_s0, uint16_t width_s1)
void _process_dsm_pulse (uint16_t width_s0, uint16_t width_s1)
Protected Attributes
std::atomic< unsigned int > rc_input_count
std::atomic< unsigned int > last_rc_input_count
uint16_t _pwm_values [LINUX_RC_INPUT_NUM_CHANNELS]
uint8_t _num_channels
uint16_t _override [LINUX_RC_INPUT_NUM_CHANNELS]
struct {
int8_t _channel_counter
uint16_t _pulse_capt [LINUX_RC_INPUT_NUM_CHANNELS]
} ppm_state
struct {
uint16_t bytes [25]
uint16_t bit_ofs
} sbus_state
struct {
uint16_t bytes [16]
uint16_t bit_ofs
} dsm_state
struct {
uint8_t frame [16]
uint8_t partial_frame_count
uint32_t last_input_ms
} dsm
struct {
uint8_t frame [25]
uint8_t partial_frame_count
uint32_t last_input_ms
} sbus
Detailed Description
Definition at line 11 of file RCInput.h.
Constructor & Destructor Documentation
RCInput::RCInput ()
Definition at line 28 of file RCInput.cpp.
Member Function Documentation
void RCInput::_process_dsm_pulse (uint16_t width_s0, uint16_t width_s1) protected
Definition at line 239 of file RCInput.cpp.
Referenced by _process_rc_pulse().
void RCInput::_process_ppmsum_pulse (uint16_t width) protected
Definition at line 107 of file RCInput.cpp.
Referenced by _process_rc_pulse().
void RCInput::_process_rc_pulse (uint16_t width_s0, uint16_t width_s1) protected
Definition at line 320 of file RCInput.cpp.
Referenced by Linux::RCInput_ZYNQ::_timer_tick(), Linux::RCInput_PRU::_timer_tick(), Linux::RCInput_AioPRU::_timer_tick(), _timer_tick(), and Linux::RCInput_RPI::_timer_tick().
void RCInput::_process_sbus_pulse (uint16_t width_s0, uint16_t width_s1) protected
Definition at line 156 of file RCInput.cpp.
Referenced by _process_rc_pulse().
virtual void Linux::RCInput::_timer_tick (void) inline virtual
Reimplemented in Linux::RCInput_RPI, Linux::RCInput_115200, Linux::RCInput_DSM, Linux::RCInput_Multi, Linux::RCInput_AioPRU, Linux::RCInput_SBUS, Linux::RCInput_UART, Linux::RCInput_PRU, Linux::RCInput_UDP, Linux::RCInput_ZYNQ, and Linux::RCInput_Navio2.
Definition at line 31 of file RCInput.h.
Referenced by Linux::Scheduler::_rcin_task(), Linux::Scheduler::_timer_task(), and Linux::RCInput_Multi::_timer_tick().
void RCInput::_update_periods (uint16_t * periods, uint8_t len) protected
Definition at line 345 of file RCInput.cpp.
Referenced by Linux::RCInput_Raspilot::_poll_data(), Linux::RCInput_Navio2::_timer_tick(), Linux::RCInput_UDP::_timer_tick(), Linux::RCInput_UART::_timer_tick(), and _timer_tick().
bool RCInput::add_dsm_input (const uint8_t * bytes, size_t nbytes)
Definition at line 361 of file RCInput.cpp.
Referenced by _timer_tick(), Linux::RCInput_DSM::_timer_tick(), and Linux::RCInput_115200::_timer_tick().
void RCInput::add_sbus_input (const uint8_t * bytes, size_t nbytes)
Definition at line 521 of file RCInput.cpp.
Referenced by Linux::RCInput_SBUS::_timer_tick(), and _timer_tick().
bool RCInput::add_srxl_input (const uint8_t * bytes, size_t nbytes)
Definition at line 490 of file RCInput.cpp.
Referenced by _timer_tick(), and Linux::RCInput_115200::_timer_tick().
bool RCInput::add_st24_input (const uint8_t * bytes, size_t nbytes)
Definition at line 460 of file RCInput.cpp.
Referenced by _timer_tick(), and Linux::RCInput_115200::_timer_tick().
bool RCInput::add_sumd_input (const uint8_t * bytes, size_t nbytes)
Definition at line 430 of file RCInput.cpp.
Referenced by _timer_tick(), and Linux::RCInput_115200::_timer_tick().
void RCInput::clear_overrides () virtual
Implements AP_HAL::RCInput.
Definition at line 96 of file RCInput.cpp.
Referenced by from().
static RCInput* Linux::RCInput::from (AP_HAL::RCInput * rcinput) inline static
Definition at line 15 of file RCInput.h.
Referenced by Linux::Scheduler::_rcin_task(), and Linux::Scheduler::_timer_task().
void RCInput::init () virtual
Call init from the platform hal instance init, so that both the type of the RCInput implementation and init argument (e.g. ISRRegistry) are known to the programmer. (It's too difficult to describe this dependency in the C++ type system.)
Implements AP_HAL::RCInput.
Reimplemented in Linux::RCInput_RPI, Linux::RCInput_115200, Linux::RCInput_DSM, Linux::RCInput_Multi, Linux::RCInput_AioPRU, Linux::RCInput_SBUS, Linux::RCInput_UART, Linux::RCInput_PRU, Linux::RCInput_UDP, Linux::RCInput_ZYNQ, Linux::RCInput_Raspilot, and Linux::RCInput_Navio2.
Definition at line 33 of file RCInput.cpp.
Referenced by from(), and Linux::RCInput_Multi::init().
bool RCInput::new_input () virtual
Return true if there has been new input since the last call to new_input()
Implements AP_HAL::RCInput.
Definition at line 37 of file RCInput.cpp.
Referenced by Linux::RCInput_Multi::_timer_tick(), and from().
uint8_t RCInput::num_channels () virtual
Return the number of valid channels in the last read
Implements AP_HAL::RCInput.
Definition at line 46 of file RCInput.cpp.
Referenced by Linux::RCInput_Multi::_timer_tick(), and from().
uint16_t RCInput::read (uint8_t ch) virtual
Implements AP_HAL::RCInput.
Definition at line 51 of file RCInput.cpp.
Referenced by Linux::RCInput_UART::_timer_tick(), Linux::RCInput_SBUS::_timer_tick(), Linux::RCInput_Multi::_timer_tick(), Linux::RCInput_115200::_timer_tick(), from(), and read().
uint8_t RCInput::read (uint16_t * periods, uint8_t len) virtual
Implements AP_HAL::RCInput.
Definition at line 62 of file RCInput.cpp.
bool RCInput::set_override (uint8_t channel, int16_t override) virtual
Implements AP_HAL::RCInput.
Definition at line 83 of file RCInput.cpp.
Referenced by from(), and set_overrides().
bool RCInput::set_overrides (int16_t * overrides, uint8_t len) virtual
Overrides: these are really grody and don't belong here but we need them at the moment to make the port work. case v of: v == -1 -> no change to this channel v == 0 -> do not override this channel v > 0 -> set v as override.
Implements AP_HAL::RCInput.
Definition at line 71 of file RCInput.cpp.
Referenced by from().
Member Data Documentation
int8_t Linux::RCInput::_channel_counter
Definition at line 67 of file RCInput.h.
uint8_t Linux::RCInput::_num_channels protected
Definition at line 56 of file RCInput.h.
Referenced by _process_dsm_pulse(), _process_ppmsum_pulse(), _process_sbus_pulse(), Linux::RCInput_Multi::_timer_tick(), _update_periods(), add_dsm_input(), add_sbus_input(), add_srxl_input(), add_st24_input(), add_sumd_input(), num_channels(), and read().
uint16_t Linux::RCInput::_override[LINUX_RC_INPUT_NUM_CHANNELS] protected
Definition at line 63 of file RCInput.h.
Referenced by clear_overrides(), read(), and set_override().
uint16_t Linux::RCInput::_pulse_capt[LINUX_RC_INPUT_NUM_CHANNELS]
Definition at line 68 of file RCInput.h.
uint16_t Linux::RCInput::_pwm_values[LINUX_RC_INPUT_NUM_CHANNELS] protected
Definition at line 55 of file RCInput.h.
Referenced by _process_dsm_pulse(), _process_ppmsum_pulse(), _process_sbus_pulse(), Linux::RCInput_Multi::_timer_tick(), _update_periods(), add_dsm_input(), add_sbus_input(), add_srxl_input(), add_st24_input(), add_sumd_input(), and read().
uint16_t Linux::RCInput::bit_ofs
Definition at line 74 of file RCInput.h.
Referenced by _process_dsm_pulse(), and _process_sbus_pulse().
uint16_t Linux::RCInput::bytes[16]
Definition at line 73 of file RCInput.h.
Referenced by _process_dsm_pulse(), _process_sbus_pulse(), Linux::RCInput_SBUS::_timer_tick(), Linux::RCInput_115200::_timer_tick(), Linux::RCInput_DSM::_timer_tick(), and _timer_tick().
struct { ... } Linux::RCInput::dsm
Referenced by add_dsm_input().
struct { ... } Linux::RCInput::dsm_state
Referenced by _process_dsm_pulse().
uint8_t Linux::RCInput::frame[25]
Definition at line 85 of file RCInput.h.
uint32_t Linux::RCInput::last_input_ms
Definition at line 87 of file RCInput.h.
std::atomic<unsigned int> Linux::RCInput::last_rc_input_count protected
Definition at line 53 of file RCInput.h.
Referenced by new_input().
uint8_t Linux::RCInput::partial_frame_count
Definition at line 86 of file RCInput.h.
struct { ... } Linux::RCInput::ppm_state
Referenced by _process_ppmsum_pulse(), and RCInput().
std::atomic<unsigned int> Linux::RCInput::rc_input_count protected
Definition at line 52 of file RCInput.h.
Referenced by _process_dsm_pulse(), _process_ppmsum_pulse(), _process_sbus_pulse(), Linux::RCInput_Multi::_timer_tick(), _update_periods(), add_dsm_input(), add_sbus_input(), add_srxl_input(), add_st24_input(), add_sumd_input(), new_input(), and set_override().
struct { ... } Linux::RCInput::sbus
Referenced by add_sbus_input().
struct { ... } Linux::RCInput::sbus_state
Referenced by _process_sbus_pulse().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/RCInput.h
libraries/AP_HAL_Linux/RCInput.cpp