APM:Libraries: DFMessageWriter_DFLogStart Class Reference
DFMessageWriter_DFLogStart Class Reference
#include <DFMessageWriter.h>
Public Member Functions
DFMessageWriter_DFLogStart (const char *firmware_string)
virtual void set_dataflash_backend (class DataFlash_Backend *backend)
void reset ()
void process ()
bool fmt_done ()
void set_mission (const AP_Mission *mission)
Public Member Functions inherited from DFMessageWriter
virtual bool finished ()
Private Types
enum log_start_blockwriter_stage {
ls_blockwriter_stage_init, ls_blockwriter_stage_formats, ls_blockwriter_stage_parms, ls_blockwriter_stage_sysinfo,
ls_blockwriter_stage_write_entire_mission, ls_blockwriter_stage_vehicle_messages, ls_blockwriter_stage_done
}
Private Attributes
bool _fmt_done = false
log_start_blockwriter_stage stage = ls_blockwriter_stage_init
uint16_t next_format_to_send
AP_Param::ParamToken token
AP_Param * ap
enum ap_var_type type
DFMessageWriter_WriteSysInfo _writesysinfo
DFMessageWriter_WriteEntireMission _writeentiremission
Additional Inherited Members
Protected Attributes inherited from DFMessageWriter
bool _finished = false
DataFlash_Backend * _dataflash_backend = nullptr
Detailed Description
Definition at line 67 of file DFMessageWriter.h.
Member Enumeration Documentation
enum DFMessageWriter_DFLogStart::log_start_blockwriter_stage private
Enumerator
ls_blockwriter_stage_init
ls_blockwriter_stage_formats
ls_blockwriter_stage_parms
ls_blockwriter_stage_sysinfo
ls_blockwriter_stage_write_entire_mission
ls_blockwriter_stage_vehicle_messages
ls_blockwriter_stage_done
Definition at line 89 of file DFMessageWriter.h.
Constructor & Destructor Documentation
DFMessageWriter_DFLogStart::DFMessageWriter_DFLogStart (const char * firmware_string) inline
Definition at line 69 of file DFMessageWriter.h.
Member Function Documentation
bool DFMessageWriter_DFLogStart::fmt_done () inline
Definition at line 83 of file DFMessageWriter.h.
Referenced by DataFlash_Backend::WriteBlockCheckStartupMessages().
void DFMessageWriter_DFLogStart::process () virtual
Implements DFMessageWriter.
Definition at line 28 of file DFMessageWriter.cpp.
Referenced by DataFlash_Backend::WriteMoreStartupMessages().
void DFMessageWriter_DFLogStart::reset () virtual
Implements DFMessageWriter.
Definition at line 15 of file DFMessageWriter.cpp.
Referenced by DataFlash_Block::start_new_log(), and DataFlash_Backend::start_new_log_reset_variables().
virtual void DFMessageWriter_DFLogStart::set_dataflash_backend (class DataFlash_Backend * backend) inline virtual
Reimplemented from DFMessageWriter.
Definition at line 75 of file DFMessageWriter.h.
Referenced by DataFlash_Backend::DataFlash_Backend().
void DFMessageWriter_DFLogStart::set_mission (const AP_Mission * mission)
Definition at line 100 of file DFMessageWriter.cpp.
Referenced by DataFlash_Backend::set_mission().
Member Data Documentation
bool DFMessageWriter_DFLogStart::_fmt_done = false private
Definition at line 99 of file DFMessageWriter.h.
DFMessageWriter_WriteEntireMission DFMessageWriter_DFLogStart::_writeentiremission private
Definition at line 110 of file DFMessageWriter.h.
DFMessageWriter_WriteSysInfo DFMessageWriter_DFLogStart::_writesysinfo private
Definition at line 109 of file DFMessageWriter.h.
AP_Param* DFMessageWriter_DFLogStart::ap private
Definition at line 105 of file DFMessageWriter.h.
uint16_t DFMessageWriter_DFLogStart::next_format_to_send private
Definition at line 103 of file DFMessageWriter.h.
log_start_blockwriter_stage DFMessageWriter_DFLogStart::stage = ls_blockwriter_stage_init private
Definition at line 101 of file DFMessageWriter.h.
AP_Param::ParamToken DFMessageWriter_DFLogStart::token private
Definition at line 104 of file DFMessageWriter.h.
enum ap_var_type DFMessageWriter_DFLogStart::type private
Definition at line 106 of file DFMessageWriter.h.
The documentation for this class was generated from the following files:
libraries/DataFlash/DFMessageWriter.h
libraries/DataFlash/DFMessageWriter.cpp