APM:Libraries: QURT::UDPDriver Class Reference
QURT::UDPDriver Class Reference
#include <UDPDriver.h>
Public Member Functions
void begin (uint32_t b)
void begin (uint32_t b, uint16_t rxS, uint16_t txS)
void end ()
void flush ()
bool is_initialized ()
void set_blocking_writes (bool blocking)
bool tx_pending ()
int16_t available ()
int16_t txspace ()
int16_t read ()
size_t write (uint8_t c)
size_t write (const uint8_t *buffer, size_t size)
uint32_t socket_check (uint8_t *buf, int len, uint32_t *nbytes)
uint32_t socket_input (const uint8_t *buf, int len, uint32_t *nbytes)
enum flow_control get_flow_control (void)
Public Member Functions inherited from AP_HAL::UARTDriver
UARTDriver ()
virtual void set_flow_control (enum flow_control flow_control_setting)
void printf (const char *s,...) FMT_PRINTF(2
void void vprintf (const char *s, va_list ap)
Public Member Functions inherited from AP_HAL::BetterStream
BetterStream (void)
Public Member Functions inherited from AP_HAL::Print
Print ()
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Static Public Member Functions
static UDPDriver * from (AP_HAL::UARTDriver *d)
Private Attributes
Semaphore lock
bool initialised
bool nonblocking_writes = true
ByteBuffer * readbuf
ByteBuffer * writebuf
Additional Inherited Members
Public Types inherited from AP_HAL::UARTDriver
enum flow_control { FLOW_CONTROL_DISABLE =0, FLOW_CONTROL_ENABLE =1, FLOW_CONTROL_AUTO =2 }
Detailed Description
Definition at line 22 of file UDPDriver.h.
Member Function Documentation
int16_t UDPDriver::available (void) virtual
Implements AP_HAL::Stream.
Definition at line 101 of file UDPDriver.cpp.
Referenced by from().
void UDPDriver::begin (uint32_t b) virtual
Implements AP_HAL::UARTDriver.
Definition at line 30 of file UDPDriver.cpp.
Referenced by from().
void UDPDriver::begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace) virtual
Extended port open method
Allows for both opening with specified buffer sizes, and re-opening to adjust a subset of the port's settings.
Note
Buffer sizes greater than ::_max_buffer_size will be rounded down.
Parameters
baud Selects the speed that the port will be configured to. If zero, the port speed is left unchanged.
rxSpace Sets the receive buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_rx_buffer_size if it is currently closed.
txSpace Sets the transmit buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_tx_buffer_size if it is currently closed.
Implements AP_HAL::UARTDriver.
Definition at line 35 of file UDPDriver.cpp.
void UDPDriver::end () virtual
Implements AP_HAL::UARTDriver.
Definition at line 67 of file UDPDriver.cpp.
Referenced by from().
void UDPDriver::flush (void) virtual
Implements AP_HAL::UARTDriver.
Definition at line 81 of file UDPDriver.cpp.
Referenced by from().
static UDPDriver* QURT::UDPDriver::from (AP_HAL::UARTDriver * d) inline static
Definition at line 24 of file UDPDriver.h.
Referenced by ardupilot_socket_check(), and ardupilot_socket_input().
enum flow_control QURT::UDPDriver::get_flow_control (void) inline virtual
Reimplemented from AP_HAL::UARTDriver.
Definition at line 46 of file UDPDriver.h.
bool UDPDriver::is_initialized () virtual
Implements AP_HAL::UARTDriver.
Definition at line 85 of file UDPDriver.cpp.
Referenced by from().
int16_t UDPDriver::read (void) virtual
Implements AP_HAL::Stream.
Definition at line 117 of file UDPDriver.cpp.
Referenced by from().
void UDPDriver::set_blocking_writes (bool blocking) virtual
Implements AP_HAL::UARTDriver.
Definition at line 90 of file UDPDriver.cpp.
Referenced by from().
uint32_t UDPDriver::socket_check (uint8_t * buf, int len, uint32_t * nbytes)
Definition at line 182 of file UDPDriver.cpp.
Referenced by ardupilot_socket_check(), and from().
uint32_t UDPDriver::socket_input (const uint8_t * buf, int len, uint32_t * nbytes)
Definition at line 242 of file UDPDriver.cpp.
Referenced by ardupilot_socket_input(), and from().
bool UDPDriver::tx_pending () virtual
Implements AP_HAL::UARTDriver.
Definition at line 95 of file UDPDriver.cpp.
Referenced by from().
int16_t UDPDriver::txspace (void) virtual
Implements AP_HAL::Stream.
Definition at line 109 of file UDPDriver.cpp.
Referenced by from().
size_t UDPDriver::write (uint8_t c) virtual
Implements AP_HAL::Print.
Definition at line 136 of file UDPDriver.cpp.
Referenced by from(), and write().
size_t UDPDriver::write (const uint8_t * buffer, size_t size) virtual
Implements AP_HAL::Print.
Definition at line 157 of file UDPDriver.cpp.
Member Data Documentation
bool QURT::UDPDriver::initialised private
Definition at line 50 of file UDPDriver.h.
Referenced by available(), begin(), end(), is_initialized(), read(), socket_check(), socket_input(), txspace(), and write().
Semaphore QURT::UDPDriver::lock private
Definition at line 49 of file UDPDriver.h.
Referenced by read(), and write().
bool QURT::UDPDriver::nonblocking_writes = true private
Definition at line 51 of file UDPDriver.h.
Referenced by set_blocking_writes(), and write().
ByteBuffer* QURT::UDPDriver::readbuf private
Definition at line 53 of file UDPDriver.h.
Referenced by available(), begin(), end(), read(), and socket_input().
ByteBuffer* QURT::UDPDriver::writebuf private
Definition at line 54 of file UDPDriver.h.
Referenced by begin(), end(), socket_check(), txspace(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_QURT/UDPDriver.h
libraries/AP_HAL_QURT/UDPDriver.cpp