APM:Libraries: Empty::Semaphore Class Reference
Empty::Semaphore Class Reference
#include <Semaphores.h>
Public Member Functions
Semaphore ()
bool give ()
bool take (uint32_t timeout_ms)
bool take_nonblocking ()
Public Member Functions inherited from AP_HAL::Semaphore
virtual ~Semaphore (void)
Private Attributes
bool _taken
Detailed Description
Definition at line 5 of file Semaphores.h.
Constructor & Destructor Documentation
Empty::Semaphore::Semaphore () inline
Definition at line 7 of file Semaphores.h.
Member Function Documentation
bool Semaphore::give () virtual
Implements AP_HAL::Semaphore.
Definition at line 6 of file Semaphores.cpp.
Referenced by Semaphore().
bool Semaphore::take (uint32_t timeout_ms) virtual
Implements AP_HAL::Semaphore.
Definition at line 15 of file Semaphores.cpp.
Referenced by Semaphore().
bool Semaphore::take_nonblocking () virtual
Implements AP_HAL::Semaphore.
Definition at line 19 of file Semaphores.cpp.
Referenced by Semaphore(), and take().
Member Data Documentation
bool Empty::Semaphore::_taken private
Definition at line 12 of file Semaphores.h.
Referenced by give(), and take_nonblocking().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Empty/Semaphores.h
libraries/AP_HAL_Empty/Semaphores.cpp