APM:Libraries: AP_ADSB Class Reference
AP_ADSB Class Reference
#include <AP_ADSB.h>
Classes
struct adsb_vehicle_t
Public Member Functions
AP_ADSB (const AP_AHRS &ahrs)
void update (void)
uint16_t get_vehicle_count ()
void send_adsb_vehicle (mavlink_channel_t chan)
void set_stall_speed_cm (const uint16_t stall_speed_cm)
void set_is_auto_mode (const bool is_in_auto_mode)
void set_is_flying (const bool is_flying)
UAVIONIX_ADSB_RF_HEALTH get_transceiver_status (void)
Location_Class get_location (const adsb_vehicle_t &vehicle) const
bool enabled () const
bool next_sample (adsb_vehicle_t &obstacle)
void handle_message (const mavlink_channel_t chan, const mavlink_message_t *msg)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void init ()
void deinit ()
void determine_furthest_aircraft (void)
bool find_index (const adsb_vehicle_t &vehicle, uint16_t *index) const
void delete_vehicle (const uint16_t index)
void set_vehicle (const uint16_t index, const adsb_vehicle_t &vehicle)
uint32_t genICAO (const Location_Class &loc)
void set_callsign (const char *str, const bool append_icao)
void send_configure (const mavlink_channel_t chan)
void send_dynamic_out (const mavlink_channel_t chan)
void handle_vehicle (const mavlink_message_t *msg)
void handle_transceiver_report (mavlink_channel_t chan, const mavlink_message_t *msg)
void push_sample (adsb_vehicle_t &vehicle)
Private Attributes
const AP_AHRS & _ahrs
AP_Int8 _enabled
Location_Class _my_loc
struct {
AP_Int16 list_size_param
uint16_t list_size = 1
adsb_vehicle_t * vehicle_list = nullptr
uint16_t vehicle_count
AP_Int32 list_radius
uint32_t send_start_ms [MAVLINK_COMM_NUM_BUFFERS]
uint16_t send_index [MAVLINK_COMM_NUM_BUFFERS]
} in_state
struct {
uint32_t last_config_ms
uint32_t last_report_ms
int8_t chan = -1
uint32_t chan_last_ms
UAVIONIX_ADSB_RF_HEALTH status
bool is_flying
bool _is_in_auto_mode
struct {
int32_t ICAO_id
AP_Int32 ICAO_id_param
int32_t ICAO_id_param_prev = -1
char callsign [9]
AP_Int8 emitterType
AP_Int8 lengthWidth
AP_Int8 gpsLatOffset
AP_Int8 gpsLonOffset
uint16_t stall_speed_cm
AP_Int8 rfSelect
} cfg
} out_state
uint16_t furthest_vehicle_index
float furthest_vehicle_distance
AP_Buffer< adsb_vehicle_t, max_samples > samples
Static Private Attributes
static const uint8_t max_samples = 30
Detailed Description
Definition at line 32 of file AP_ADSB.h.
Constructor & Destructor Documentation
AP_ADSB::AP_ADSB (const AP_AHRS & ahrs) inline
Definition at line 42 of file AP_ADSB.h.
Member Function Documentation
void AP_ADSB::deinit (void) private
Definition at line 149 of file AP_ADSB.cpp.
Referenced by enabled(), and update().
void AP_ADSB::delete_vehicle (const uint16_t index) private
Definition at line 290 of file AP_ADSB.cpp.
Referenced by enabled(), handle_vehicle(), and update().
void AP_ADSB::determine_furthest_aircraft (void) private
Definition at line 255 of file AP_ADSB.cpp.
Referenced by enabled(), and handle_vehicle().
bool AP_ADSB::enabled () const inline
Definition at line 69 of file AP_ADSB.h.
Referenced by AP_Avoidance::update().
bool AP_ADSB::find_index (const adsb_vehicle_t & vehicle, uint16_t * index) const private
Definition at line 312 of file AP_ADSB.cpp.
Referenced by enabled(), and handle_vehicle().
uint32_t AP_ADSB::genICAO (const Location_Class & loc) private
Definition at line 577 of file AP_ADSB.cpp.
Referenced by enabled(), and update().
Location_Class AP_ADSB::get_location (const adsb_vehicle_t & vehicle) const
Definition at line 275 of file AP_ADSB.cpp.
Referenced by determine_furthest_aircraft(), AP_Avoidance::get_adsb_samples(), get_transceiver_status(), and handle_vehicle().
UAVIONIX_ADSB_RF_HEALTH AP_ADSB::get_transceiver_status (void) inline
Definition at line 64 of file AP_ADSB.h.
uint16_t AP_ADSB::get_vehicle_count () inline
Definition at line 54 of file AP_ADSB.h.
void AP_ADSB::handle_message (const mavlink_channel_t chan, const mavlink_message_t * msg)
Definition at line 650 of file AP_ADSB.cpp.
Referenced by enabled().
void AP_ADSB::handle_transceiver_report (mavlink_channel_t chan, const mavlink_message_t * msg) private
Definition at line 557 of file AP_ADSB.cpp.
Referenced by enabled(), and handle_message().
void AP_ADSB::handle_vehicle (const mavlink_message_t * msg) private
Definition at line 327 of file AP_ADSB.cpp.
Referenced by enabled(), and handle_message().
void AP_ADSB::init (void) private
Definition at line 120 of file AP_ADSB.cpp.
Referenced by enabled(), and update().
bool AP_ADSB::next_sample (adsb_vehicle_t & obstacle)
Definition at line 645 of file AP_ADSB.cpp.
Referenced by enabled(), and AP_Avoidance::get_adsb_samples().
void AP_ADSB::push_sample (adsb_vehicle_t & vehicle) private
Definition at line 640 of file AP_ADSB.cpp.
Referenced by handle_vehicle().
void AP_ADSB::send_adsb_vehicle (mavlink_channel_t chan)
Definition at line 421 of file AP_ADSB.cpp.
Referenced by get_vehicle_count().
void AP_ADSB::send_configure (const mavlink_channel_t chan) private
Definition at line 538 of file AP_ADSB.cpp.
Referenced by enabled(), and update().
void AP_ADSB::send_dynamic_out (const mavlink_channel_t chan) private
Definition at line 463 of file AP_ADSB.cpp.
Referenced by enabled(), and update().
void AP_ADSB::set_callsign (const char * str, const bool append_icao) private
Definition at line 594 of file AP_ADSB.cpp.
Referenced by enabled(), init(), and update().
void AP_ADSB::set_is_auto_mode (const bool is_in_auto_mode) inline
Definition at line 61 of file AP_ADSB.h.
void AP_ADSB::set_is_flying (const bool is_flying) inline
Definition at line 62 of file AP_ADSB.h.
void AP_ADSB::set_stall_speed_cm (const uint16_t stall_speed_cm) inline
Definition at line 59 of file AP_ADSB.h.
void AP_ADSB::set_vehicle (const uint16_t index, const adsb_vehicle_t & vehicle) private
Definition at line 414 of file AP_ADSB.cpp.
Referenced by enabled(), and handle_vehicle().
void AP_ADSB::update (void)
Definition at line 161 of file AP_ADSB.cpp.
Member Data Documentation
const AP_AHRS& AP_ADSB::_ahrs private
Definition at line 114 of file AP_ADSB.h.
Referenced by genICAO(), send_dynamic_out(), and update().
AP_Int8 AP_ADSB::_enabled private
Definition at line 116 of file AP_ADSB.h.
Referenced by enabled(), init(), and update().
bool AP_ADSB::_is_in_auto_mode
Definition at line 144 of file AP_ADSB.h.
Location_Class AP_ADSB::_my_loc private
Definition at line 118 of file AP_ADSB.h.
Referenced by determine_furthest_aircraft(), handle_vehicle(), send_dynamic_out(), and update().
char AP_ADSB::callsign[9]
Definition at line 151 of file AP_ADSB.h.
struct { ... } AP_ADSB::cfg
int8_t AP_ADSB::chan = -1
Definition at line 140 of file AP_ADSB.h.
Referenced by get_vehicle_count(), handle_transceiver_report(), send_adsb_vehicle(), and update().
uint32_t AP_ADSB::chan_last_ms
Definition at line 141 of file AP_ADSB.h.
AP_Int8 AP_ADSB::emitterType
Definition at line 152 of file AP_ADSB.h.
float AP_ADSB::furthest_vehicle_distance private
Definition at line 165 of file AP_ADSB.h.
Referenced by delete_vehicle(), determine_furthest_aircraft(), handle_vehicle(), and init().
uint16_t AP_ADSB::furthest_vehicle_index private
Definition at line 164 of file AP_ADSB.h.
Referenced by delete_vehicle(), determine_furthest_aircraft(), handle_vehicle(), and init().
AP_Int8 AP_ADSB::gpsLatOffset
Definition at line 154 of file AP_ADSB.h.
AP_Int8 AP_ADSB::gpsLonOffset
Definition at line 155 of file AP_ADSB.h.
int32_t AP_ADSB::ICAO_id
Definition at line 148 of file AP_ADSB.h.
AP_Int32 AP_ADSB::ICAO_id_param
Definition at line 149 of file AP_ADSB.h.
int32_t AP_ADSB::ICAO_id_param_prev = -1
Definition at line 150 of file AP_ADSB.h.
struct { ... } AP_ADSB::in_state
Referenced by deinit(), delete_vehicle(), determine_furthest_aircraft(), find_index(), get_vehicle_count(), handle_vehicle(), init(), send_adsb_vehicle(), set_vehicle(), and update().
bool AP_ADSB::is_flying
Definition at line 143 of file AP_ADSB.h.
Referenced by set_is_flying().
uint32_t AP_ADSB::last_config_ms
Definition at line 138 of file AP_ADSB.h.
uint32_t AP_ADSB::last_report_ms
Definition at line 139 of file AP_ADSB.h.
AP_Int8 AP_ADSB::lengthWidth
Definition at line 153 of file AP_ADSB.h.
AP_Int32 AP_ADSB::list_radius
Definition at line 128 of file AP_ADSB.h.
uint16_t AP_ADSB::list_size = 1
Definition at line 125 of file AP_ADSB.h.
AP_Int16 AP_ADSB::list_size_param
Definition at line 124 of file AP_ADSB.h.
const uint8_t AP_ADSB::max_samples = 30 static private
Definition at line 167 of file AP_ADSB.h.
struct { ... } AP_ADSB::out_state
Referenced by get_transceiver_status(), handle_transceiver_report(), handle_vehicle(), send_configure(), send_dynamic_out(), set_callsign(), set_is_auto_mode(), set_is_flying(), set_stall_speed_cm(), and update().
AP_Int8 AP_ADSB::rfSelect
Definition at line 157 of file AP_ADSB.h.
AP_Buffer<adsb_vehicle_t, max_samples> AP_ADSB::samples private
Definition at line 168 of file AP_ADSB.h.
Referenced by next_sample(), and push_sample().
uint16_t AP_ADSB::send_index[MAVLINK_COMM_NUM_BUFFERS]
Definition at line 132 of file AP_ADSB.h.
uint32_t AP_ADSB::send_start_ms[MAVLINK_COMM_NUM_BUFFERS]
Definition at line 131 of file AP_ADSB.h.
uint16_t AP_ADSB::stall_speed_cm
Definition at line 156 of file AP_ADSB.h.
Referenced by set_stall_speed_cm().
UAVIONIX_ADSB_RF_HEALTH AP_ADSB::status
Definition at line 142 of file AP_ADSB.h.
const AP_Param::GroupInfo AP_ADSB::var_info static
Definition at line 49 of file AP_ADSB.h.
Referenced by AP_ADSB().
uint16_t AP_ADSB::vehicle_count
Definition at line 127 of file AP_ADSB.h.
adsb_vehicle_t* AP_ADSB::vehicle_list = nullptr
Definition at line 126 of file AP_ADSB.h.
The documentation for this class was generated from the following files:
libraries/AP_ADSB/AP_ADSB.h
libraries/AP_ADSB/AP_ADSB.cpp