APM:Libraries: AP_RangeFinder_PulsedLightLRF Class Reference
AP_RangeFinder_PulsedLightLRF Class Reference
#include <AP_RangeFinder_PulsedLightLRF.h>
Public Member Functions
void update (void) override
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder &_ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state)
virtual ~AP_RangeFinder_Backend (void)
bool out_of_range (void) const
virtual void handle_msg (mavlink_message_t *msg)
Static Public Member Functions
static AP_RangeFinder_Backend * detect (uint8_t bus, RangeFinder &ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state, RangeFinder::RangeFinder_Type rftype)
Private Types
enum { PHASE_MEASURE, PHASE_COLLECT }
Private Member Functions
AP_RangeFinder_PulsedLightLRF (uint8_t bus, RangeFinder &ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state, RangeFinder::RangeFinder_Type rftype)
bool init (void)
void timer (void)
bool lidar_transfer (const uint8_t *send, unsigned send_len, uint8_t *recv, unsigned recv_len)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
uint8_t sw_version
uint8_t hw_version
uint8_t check_reg_counter
bool v2_hardware
uint16_t last_distance_cm
RangeFinder::RangeFinder_Type rftype
enum AP_RangeFinder_PulsedLightLRF:: { ... } phase
Additional Inherited Members
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status ()
void set_status (RangeFinder::RangeFinder_Status status)
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder & ranger
RangeFinder::RangeFinder_State & state
AP_HAL::Semaphore * _sem
Detailed Description
Definition at line 17 of file AP_RangeFinder_PulsedLightLRF.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
PHASE_MEASURE
PHASE_COLLECT
Definition at line 50 of file AP_RangeFinder_PulsedLightLRF.h.
Constructor & Destructor Documentation
AP_RangeFinder_PulsedLightLRF::AP_RangeFinder_PulsedLightLRF (uint8_t bus, RangeFinder & ranger, uint8_t instance, RangeFinder::RangeFinder_State & _state, RangeFinder::RangeFinder_Type rftype) private
Definition at line 47 of file AP_RangeFinder_PulsedLightLRF.cpp.
Referenced by detect(), and update().
Member Function Documentation
AP_RangeFinder_Backend * AP_RangeFinder_PulsedLightLRF::detect (uint8_t bus, RangeFinder & ranger, uint8_t instance, RangeFinder::RangeFinder_State & _state, RangeFinder::RangeFinder_Type rftype) static
Definition at line 60 of file AP_RangeFinder_PulsedLightLRF.cpp.
Referenced by RangeFinder::detect_instance().
bool AP_RangeFinder_PulsedLightLRF::init (void) private
Definition at line 146 of file AP_RangeFinder_PulsedLightLRF.cpp.
Referenced by detect(), and update().
bool AP_RangeFinder_PulsedLightLRF::lidar_transfer (const uint8_t * send, unsigned send_len, uint8_t * recv, unsigned recv_len) private
Referenced by update().
void AP_RangeFinder_PulsedLightLRF::timer (void) private
Definition at line 77 of file AP_RangeFinder_PulsedLightLRF.cpp.
Referenced by init(), and update().
void AP_RangeFinder_PulsedLightLRF::update (void) inline override virtual
Implements AP_RangeFinder_Backend.
Definition at line 27 of file AP_RangeFinder_PulsedLightLRF.h.
Member Data Documentation
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_RangeFinder_PulsedLightLRF::_dev private
Definition at line 41 of file AP_RangeFinder_PulsedLightLRF.h.
Referenced by init(), and timer().
uint8_t AP_RangeFinder_PulsedLightLRF::check_reg_counter private
Definition at line 45 of file AP_RangeFinder_PulsedLightLRF.h.
Referenced by timer().
uint8_t AP_RangeFinder_PulsedLightLRF::hw_version private
Definition at line 44 of file AP_RangeFinder_PulsedLightLRF.h.
Referenced by init().
uint16_t AP_RangeFinder_PulsedLightLRF::last_distance_cm private
Definition at line 47 of file AP_RangeFinder_PulsedLightLRF.h.
Referenced by timer().
enum { ... } AP_RangeFinder_PulsedLightLRF::phase
Referenced by init(), and timer().
RangeFinder::RangeFinder_Type AP_RangeFinder_PulsedLightLRF::rftype private
Definition at line 48 of file AP_RangeFinder_PulsedLightLRF.h.
Referenced by init().
uint8_t AP_RangeFinder_PulsedLightLRF::sw_version private
Definition at line 43 of file AP_RangeFinder_PulsedLightLRF.h.
Referenced by init().
bool AP_RangeFinder_PulsedLightLRF::v2_hardware private
Definition at line 46 of file AP_RangeFinder_PulsedLightLRF.h.
Referenced by init(), and timer().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_PulsedLightLRF.h
libraries/AP_RangeFinder/AP_RangeFinder_PulsedLightLRF.cpp