APM:Libraries: AP_UAVCAN Class Reference
AP_UAVCAN Class Reference
#include <AP_UAVCAN.h>
Classes
struct Baro_Info
struct Mag_Info
class RaiiSynchronizer
class SystemClock
Public Member Functions
AP_UAVCAN ()
~AP_UAVCAN ()
uint8_t register_gps_listener (AP_GPS_Backend *new_listener, uint8_t preferred_channel)
void remove_gps_listener (AP_GPS_Backend *rem_listener)
AP_GPS::GPS_State * find_gps_node (uint8_t node)
void update_gps_state (uint8_t node)
uint8_t register_baro_listener (AP_Baro_Backend *new_listener, uint8_t preferred_channel)
void remove_baro_listener (AP_Baro_Backend *rem_listener)
Baro_Info * find_baro_node (uint8_t node)
void update_baro_state (uint8_t node)
uint8_t register_mag_listener (AP_Compass_Backend *new_listener, uint8_t preferred_channel)
void remove_mag_listener (AP_Compass_Backend *rem_listener)
Mag_Info * find_mag_node (uint8_t node)
void update_mag_state (uint8_t node)
bool rc_out_sem_take ()
void rc_out_sem_give ()
void do_cyclic (void)
bool try_init (void)
void rco_set_safety_pwm (uint32_t chmask, uint16_t pulse_len)
void rco_set_failsafe_pwm (uint32_t chmask, uint16_t pulse_len)
void rco_force_safety_on (void)
void rco_force_safety_off (void)
void rco_arm_actuators (bool arm)
void rco_write (uint16_t pulse_len, uint8_t ch)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
uavcan::ISystemClock & get_system_clock ()
uavcan::ICanDriver * get_can_driver ()
uavcan::Node< 0 > * get_node ()
Private Attributes
uint8_t _gps_nodes [AP_UAVCAN_MAX_GPS_NODES]
uint8_t _gps_node_taken [AP_UAVCAN_MAX_GPS_NODES]
AP_GPS::GPS_State _gps_node_state [AP_UAVCAN_MAX_GPS_NODES]
uint8_t _gps_listener_to_node [AP_UAVCAN_MAX_LISTENERS]
AP_GPS_Backend * _gps_listeners [AP_UAVCAN_MAX_LISTENERS]
uint8_t _baro_nodes [AP_UAVCAN_MAX_BARO_NODES]
uint8_t _baro_node_taken [AP_UAVCAN_MAX_BARO_NODES]
Baro_Info _baro_node_state [AP_UAVCAN_MAX_BARO_NODES]
uint8_t _baro_listener_to_node [AP_UAVCAN_MAX_LISTENERS]
AP_Baro_Backend * _baro_listeners [AP_UAVCAN_MAX_LISTENERS]
uint8_t _mag_nodes [AP_UAVCAN_MAX_MAG_NODES]
uint8_t _mag_node_taken [AP_UAVCAN_MAX_MAG_NODES]
Mag_Info _mag_node_state [AP_UAVCAN_MAX_MAG_NODES]
uint8_t _mag_listener_to_node [AP_UAVCAN_MAX_LISTENERS]
AP_Compass_Backend * _mag_listeners [AP_UAVCAN_MAX_LISTENERS]
struct {
uint16_t pulse
uint16_t safety_pulse
uint16_t failsafe_pulse
bool active
} _rco_conf [UAVCAN_RCO_NUMBER]
bool _initialized
uint8_t _rco_armed
uint8_t _rco_safety
AP_HAL::Semaphore * _rc_out_sem
uavcan::Node< 0 > * _node = nullptr
uavcan::HeapBasedPoolAllocator< UAVCAN_NODE_POOL_BLOCK_SIZE, AP_UAVCAN::RaiiSynchronizer > _node_allocator
AP_Int8 _uavcan_node
Detailed Description
Definition at line 45 of file AP_UAVCAN.h.
Constructor & Destructor Documentation
AP_UAVCAN::AP_UAVCAN ()
AP_UAVCAN::~AP_UAVCAN ()
Member Function Documentation
void AP_UAVCAN::do_cyclic (void)
Baro_Info* AP_UAVCAN::find_baro_node (uint8_t node)
AP_GPS::GPS_State* AP_UAVCAN::find_gps_node (uint8_t node)
Mag_Info* AP_UAVCAN::find_mag_node (uint8_t node)
uavcan::ICanDriver* AP_UAVCAN::get_can_driver () private
uavcan::Node<0>* AP_UAVCAN::get_node () private
uavcan::ISystemClock& AP_UAVCAN::get_system_clock () private
void AP_UAVCAN::rc_out_sem_give ()
Referenced by PX4::PX4RCOutput::_send_outputs().
bool AP_UAVCAN::rc_out_sem_take ()
Referenced by PX4::PX4RCOutput::_send_outputs().
void AP_UAVCAN::rco_arm_actuators (bool arm)
Referenced by PX4::PX4RCOutput::_send_outputs().
void AP_UAVCAN::rco_force_safety_off (void)
void AP_UAVCAN::rco_force_safety_on (void)
void AP_UAVCAN::rco_set_failsafe_pwm (uint32_t chmask, uint16_t pulse_len)
void AP_UAVCAN::rco_set_safety_pwm (uint32_t chmask, uint16_t pulse_len)
void AP_UAVCAN::rco_write (uint16_t pulse_len, uint8_t ch)
Referenced by PX4::PX4RCOutput::_send_outputs().
uint8_t AP_UAVCAN::register_baro_listener (AP_Baro_Backend * new_listener, uint8_t preferred_channel)
uint8_t AP_UAVCAN::register_gps_listener (AP_GPS_Backend * new_listener, uint8_t preferred_channel)
Referenced by AP_GPS::detect_instance().
uint8_t AP_UAVCAN::register_mag_listener (AP_Compass_Backend * new_listener, uint8_t preferred_channel)
void AP_UAVCAN::remove_baro_listener (AP_Baro_Backend * rem_listener)
void AP_UAVCAN::remove_gps_listener (AP_GPS_Backend * rem_listener)
void AP_UAVCAN::remove_mag_listener (AP_Compass_Backend * rem_listener)
bool AP_UAVCAN::try_init (void)
void AP_UAVCAN::update_baro_state (uint8_t node)
void AP_UAVCAN::update_gps_state (uint8_t node)
void AP_UAVCAN::update_mag_state (uint8_t node)
Member Data Documentation
uint8_t AP_UAVCAN::_baro_listener_to_node[AP_UAVCAN_MAX_LISTENERS] private
Definition at line 114 of file AP_UAVCAN.h.
AP_Baro_Backend* AP_UAVCAN::_baro_listeners[AP_UAVCAN_MAX_LISTENERS] private
Definition at line 115 of file AP_UAVCAN.h.
Baro_Info AP_UAVCAN::_baro_node_state[AP_UAVCAN_MAX_BARO_NODES] private
Definition at line 113 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_baro_node_taken[AP_UAVCAN_MAX_BARO_NODES] private
Definition at line 112 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_baro_nodes[AP_UAVCAN_MAX_BARO_NODES] private
Definition at line 111 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_gps_listener_to_node[AP_UAVCAN_MAX_LISTENERS] private
Definition at line 106 of file AP_UAVCAN.h.
AP_GPS_Backend* AP_UAVCAN::_gps_listeners[AP_UAVCAN_MAX_LISTENERS] private
Definition at line 108 of file AP_UAVCAN.h.
AP_GPS::GPS_State AP_UAVCAN::_gps_node_state[AP_UAVCAN_MAX_GPS_NODES] private
Definition at line 103 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_gps_node_taken[AP_UAVCAN_MAX_GPS_NODES] private
Definition at line 101 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_gps_nodes[AP_UAVCAN_MAX_GPS_NODES] private
Definition at line 99 of file AP_UAVCAN.h.
bool AP_UAVCAN::_initialized private
Definition at line 131 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_mag_listener_to_node[AP_UAVCAN_MAX_LISTENERS] private
Definition at line 121 of file AP_UAVCAN.h.
AP_Compass_Backend* AP_UAVCAN::_mag_listeners[AP_UAVCAN_MAX_LISTENERS] private
Definition at line 122 of file AP_UAVCAN.h.
Mag_Info AP_UAVCAN::_mag_node_state[AP_UAVCAN_MAX_MAG_NODES] private
Definition at line 120 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_mag_node_taken[AP_UAVCAN_MAX_MAG_NODES] private
Definition at line 119 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_mag_nodes[AP_UAVCAN_MAX_MAG_NODES] private
Definition at line 118 of file AP_UAVCAN.h.
uavcan::Node<0>* AP_UAVCAN::_node = nullptr private
Definition at line 172 of file AP_UAVCAN.h.
uavcan::HeapBasedPoolAllocator<UAVCAN_NODE_POOL_BLOCK_SIZE, AP_UAVCAN::RaiiSynchronizer> AP_UAVCAN::_node_allocator private
Definition at line 191 of file AP_UAVCAN.h.
AP_HAL::Semaphore* AP_UAVCAN::_rc_out_sem private
Definition at line 135 of file AP_UAVCAN.h.
uint8_t AP_UAVCAN::_rco_armed private
Definition at line 132 of file AP_UAVCAN.h.
struct { ... } AP_UAVCAN::_rco_conf[UAVCAN_RCO_NUMBER]
uint8_t AP_UAVCAN::_rco_safety private
Definition at line 133 of file AP_UAVCAN.h.
AP_Int8 AP_UAVCAN::_uavcan_node private
Definition at line 193 of file AP_UAVCAN.h.
bool AP_UAVCAN::active
Definition at line 128 of file AP_UAVCAN.h.
uint16_t AP_UAVCAN::failsafe_pulse
Definition at line 127 of file AP_UAVCAN.h.
uint16_t AP_UAVCAN::pulse
Definition at line 125 of file AP_UAVCAN.h.
uint16_t AP_UAVCAN::safety_pulse
Definition at line 126 of file AP_UAVCAN.h.
const struct AP_Param::GroupInfo AP_UAVCAN::var_info[] static
Definition at line 50 of file AP_UAVCAN.h.
Referenced by AP_BoardConfig::px4_setup_canbus().
The documentation for this class was generated from the following file:
libraries/AP_UAVCAN/AP_UAVCAN.h