APM:Libraries: AP_HAL::Stream Class Reference
AP_HAL::Stream Class Reference abstract
#include <Stream.h>
Public Member Functions
virtual uint32_t available ()=0
virtual uint32_t txspace ()=0
virtual int16_t read ()=0
Public Member Functions inherited from AP_HAL::Print
Print ()
virtual size_t write (uint8_t)=0
virtual size_t write (const uint8_t *buffer, size_t size)=0
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Detailed Description
Definition at line 9 of file Stream.h.
Member Function Documentation
virtual uint32_t AP_HAL::Stream::available () pure virtual
Implemented in HALSITL::UARTDriver, QURT::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, Empty::UARTDriver, PX4::NSHShellStream, and VRBRAIN::NSHShellStream.
Referenced by Menu::_check_for_input(), AP_GPS_SBP::_sbp_process(), AP_InertialSensor_UserInteractStream::blocking_read(), AP_Proximity_LightWareSF40C::check_for_reply(), comm_get_available(), console_loopback(), drive(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_MaxsonarSerialLV::get_reading(), AP_RangeFinder_uLanding::get_reading(), AP_RangeFinder_LeddarOne::get_reading(), GCS_MAVLINK::handle_serial_control(), loop(), AP_RangeFinder_LeddarOne::parse_response(), AP_GPS_ERB::read(), AP_GPS_NOVA::read(), AP_GPS_MTK::read(), AP_GPS_SIRF::read(), AP_GPS_GSOF::read(), AP_GPS_MTK19::read(), AP_GPS_SBF::read(), AP_GPS_NMEA::read(), AP_GPS_UBLOX::read(), AP_Mount_SToRM32_serial::read_incoming(), AP_Mount_Alexmos::read_incoming(), AP_Proximity_TeraRangerTower::read_sensor_data(), run_test(), AP_Frsky_Telem::send_SPort(), AP_Frsky_Telem::send_SPort_Passthrough(), and AP_Beacon_Pozyx::update().
virtual int16_t AP_HAL::Stream::read () pure virtual
Implemented in HALSITL::UARTDriver, QURT::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, Empty::UARTDriver, PX4::NSHShellStream, and VRBRAIN::NSHShellStream.
Referenced by Menu::_check_for_input(), AP_GPS_SBP::_sbp_process(), AP_InertialSensor_UserInteractStream::blocking_read(), AP_Proximity_LightWareSF40C::check_for_reply(), comm_receive_ch(), console_loopback(), AP_GPS::detect_instance(), AP_RangeFinder_LightWareSerial::get_reading(), AP_RangeFinder_MaxsonarSerialLV::get_reading(), AP_RangeFinder_uLanding::get_reading(), AP_RangeFinder_LeddarOne::get_reading(), GCS_MAVLINK::handle_serial_control(), loop(), AP_RangeFinder_LeddarOne::parse_response(), AP_GPS_ERB::read(), AP_GPS_NOVA::read(), AP_GPS_MTK::read(), AP_GPS_SIRF::read(), AP_GPS_MTK19::read(), AP_GPS_GSOF::read(), AP_GPS_SBF::read(), AP_GPS_NMEA::read(), AP_GPS_UBLOX::read(), AP_Mount_SToRM32_serial::read_incoming(), AP_Mount_Alexmos::read_incoming(), AP_Proximity_TeraRangerTower::read_sensor_data(), run_test(), AP_Frsky_Telem::send_SPort(), AP_Frsky_Telem::send_SPort_Passthrough(), and AP_Beacon_Pozyx::update().
virtual uint32_t AP_HAL::Stream::txspace () pure virtual
Implemented in HALSITL::UARTDriver, QURT::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, Empty::UARTDriver, PX4::NSHShellStream, and VRBRAIN::NSHShellStream.
Referenced by AP_GPS_UBLOX::_configure_message_rate(), AP_AccelCal::_printf(), AP_GPS_UBLOX::_request_next_config(), AP_GPS_UBLOX::_request_port(), AP_GPS_UBLOX::_send_message(), AP_Mount_SToRM32_serial::can_send(), comm_get_txspace(), AP_Mount_SToRM32_serial::get_angles(), GCS_MAVLINK::handle_serial_control(), AP_GPS_NOVA::inject_data(), AP_GPS_SBP::inject_data(), AP_GPS_SBF::inject_data(), AP_GPS_GSOF::inject_data(), AP_GPS_UBLOX::inject_data(), AP_GPS_ERB::inject_data(), AP_InertialSensor_UserInteract_MAVLink::printf(), AP_GPS::send_blob_update(), AP_Mount_Alexmos::send_command(), AP_Frsky_Telem::send_SPort(), AP_Frsky_Telem::send_SPort_Passthrough(), and AP_Mount_SToRM32_serial::send_target_angles().
The documentation for this class was generated from the following file:
libraries/AP_HAL/utility/Stream.h