APM:Libraries: RC_Channels Class Reference
RC_Channels Class Reference
#include <RC_Channel.h>
Public Member Functions
RC_Channels (void)
Static Public Member Functions
static RC_Channel * rc_channel (uint8_t chan)
static void set_pwm_all (void)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Attributes
RC_Channel obj_channels [NUM_RC_CHANNELS]
Static Private Attributes
static RC_Channel * channels
Friends
class SRV_Channels
Detailed Description
Definition at line 132 of file RC_Channel.h.
Constructor & Destructor Documentation
RC_Channels::RC_Channels (void)
Definition at line 105 of file RC_Channels.cpp.
Member Function Documentation
static RC_Channel* RC_Channels::rc_channel (uint8_t chan) inline static
Definition at line 140 of file RC_Channel.h.
Referenced by AP_Tuning::check_input(), AP_Tuning::check_selector_switch(), SRV_Channels::copy_radio_in_out(), SRV_Channel::output_ch(), SRV_Channels::set_output_limit(), SRV_Channels::set_trim_to_radio_in_for(), and setup().
void RC_Channels::set_pwm_all (void) static
Definition at line 122 of file RC_Channels.cpp.
Referenced by loop().
Friends And Related Function Documentation
friend class SRV_Channels friend
Definition at line 134 of file RC_Channel.h.
Member Data Documentation
RC_Channel * RC_Channels::channels static private
Definition at line 148 of file RC_Channel.h.
Referenced by RC_Channels(), set_pwm_all(), and SRV_Channels::upgrade_parameters().
RC_Channel RC_Channels::obj_channels[NUM_RC_CHANNELS] private
Definition at line 149 of file RC_Channel.h.
Referenced by RC_Channels().
const AP_Param::GroupInfo RC_Channels::var_info static
Definition at line 138 of file RC_Channel.h.
Referenced by RC_Channels().
The documentation for this class was generated from the following files:
libraries/RC_Channel/RC_Channel.h
libraries/RC_Channel/RC_Channels.cpp