APM:Libraries: DataFlash_Block Class Reference
DataFlash_Block Class Reference abstract
#include <DataFlash_Block.h>
Classes
struct PageHeader
Public Member Functions
DataFlash_Block (DataFlash_Class &front, DFMessageWriter_DFLogStart *writer)
virtual bool CardInserted (void)=0
void EraseAll ()
bool NeedPrep (void)
void Prep ()
bool WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)
uint16_t find_last_log () override
void get_log_boundaries (uint16_t log_num, uint16_t &start_page, uint16_t &end_page)
void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)
int16_t get_log_data_raw (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
uint16_t get_num_logs () override
uint16_t start_new_log (void)
void LogReadProcess (const uint16_t list_entry, uint16_t start_page, uint16_t end_page, print_mode_fn print_mode, AP_HAL::BetterStream *port)
void DumpPageInfo (AP_HAL::BetterStream *port)
void ShowDeviceInfo (AP_HAL::BetterStream *port)
void ListAvailableLogs (AP_HAL::BetterStream *port)
uint32_t bufferspace_available ()
Public Member Functions inherited from DataFlash_Backend
FUNCTOR_TYPEDEF (print_mode_fn, void, AP_HAL::BetterStream *, uint8_t)
FUNCTOR_TYPEDEF (vehicle_startup_message_Log_Writer, void)
DataFlash_Backend (DataFlash_Class &front, class DFMessageWriter_DFLogStart *writer)
vehicle_startup_message_Log_Writer vehicle_message_writer ()
void internal_error ()
bool WriteBlock (const void *pBuffer, uint16_t size)
bool WriteCriticalBlock (const void *pBuffer, uint16_t size)
void EnableWrites (bool enable)
virtual bool logging_started (void) const
virtual void Init ()
void set_mission (const AP_Mission *mission)
virtual void stop_logging (void)=0
void Log_Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
virtual void flush (void)
virtual void remote_log_block_status_msg (mavlink_channel_t chan, mavlink_message_t *msg)
virtual void periodic_tasks ()
uint8_t num_types () const
const struct LogStructure * structure (uint8_t structure) const
void Log_Write_EntireMission (const AP_Mission &mission)
bool Log_Write_Format (const struct LogStructure *structure)
bool Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t &mav_cmd)
bool Log_Write_Message (const char *message)
bool Log_Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
bool Log_Write_Mode (uint8_t mode, uint8_t reason=0)
bool Log_Write_Parameter (const char *name, float value)
bool Log_Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type)
uint32_t num_dropped (void) const
bool Log_Write_Emit_FMT (uint8_t msg_type)
bool Log_Write (uint8_t msg_type, va_list arg_list, bool is_critical=false)
virtual bool logging_enabled () const =0
virtual bool logging_failed () const =0
virtual void vehicle_was_disarmed ()
Protected Member Functions
virtual void ReadManufacturerID ()=0
Protected Member Functions inherited from DataFlash_Backend
virtual void periodic_10Hz (const uint32_t now)
virtual void periodic_1Hz (const uint32_t now)
virtual void periodic_fullrate (const uint32_t now)
void _print_log_entry (uint8_t msg_type, print_mode_fn print_mode, AP_HAL::BetterStream *port)
virtual bool WriteBlockCheckStartupMessages ()
virtual void WriteMoreStartupMessages ()
virtual void push_log_blocks ()
virtual void start_new_log_reset_variables ()
Protected Attributes
uint8_t df_manufacturer
uint16_t df_device
uint16_t df_PageSize
uint16_t df_NumPages
Protected Attributes inherited from DataFlash_Backend
uint32_t dropped
uint8_t internal_errors
DataFlash_Class & _front
bool _writes_enabled = false
DFMessageWriter_DFLogStart * _startup_messagewriter
bool _writing_startup_messages
uint32_t _internal_errors
uint32_t _dropped
Private Member Functions
virtual void WaitReady ()=0
virtual void BufferToPage (uint8_t BufferNum, uint16_t PageAdr, uint8_t wait)=0
virtual void PageToBuffer (uint8_t BufferNum, uint16_t PageAdr)=0
virtual void PageErase (uint16_t PageAdr)=0
virtual void BlockErase (uint16_t BlockAdr)=0
virtual void ChipErase ()=0
virtual void BlockWrite (uint8_t BufferNum, uint16_t IntPageAdr, const void *pHeader, uint8_t hdr_size, const void *pBuffer, uint16_t size)=0
virtual bool BlockRead (uint8_t BufferNum, uint16_t IntPageAdr, void *pBuffer, uint16_t size)=0
bool NeedErase (void)
void StartRead (uint16_t PageAdr)
uint16_t find_last_page (void)
uint16_t find_last_page_of_log (uint16_t log_number)
bool check_wrapped (void)
uint16_t GetPage (void)
uint16_t GetWritePage (void)
void StartWrite (uint16_t PageAdr)
void FinishWrite (void)
bool ReadBlock (void *pBuffer, uint16_t size)
void SetFileNumber (uint16_t FileNumber)
uint16_t GetFilePage ()
uint16_t GetFileNumber ()
void _print_log_formats (AP_HAL::BetterStream *port)
Private Attributes
uint8_t df_BufferNum
uint8_t df_Read_BufferNum
uint16_t df_BufferIdx
uint16_t df_Read_BufferIdx
uint16_t df_PageAdr
uint16_t df_Read_PageAdr
uint16_t df_FileNumber
uint16_t df_FilePage
bool adding_fmt_headers
Additional Inherited Members
Public Attributes inherited from DataFlash_Backend
bool log_write_started
Detailed Description
Definition at line 10 of file DataFlash_Block.h.
Constructor & Destructor Documentation
DataFlash_Block::DataFlash_Block (DataFlash_Class & front, DFMessageWriter_DFLogStart * writer) inline
Definition at line 13 of file DataFlash_Block.h.
Member Function Documentation
void DataFlash_Block::_print_log_formats (AP_HAL::BetterStream * port) private
Definition at line 453 of file LogFile.cpp.
Referenced by LogReadProcess().
virtual void DataFlash_Block::BlockErase (uint16_t BlockAdr) private pure virtual
Implemented in DataFlash_SITL.
Referenced by EraseAll().
virtual bool DataFlash_Block::BlockRead (uint8_t BufferNum, uint16_t IntPageAdr, void * pBuffer, uint16_t size) private pure virtual
Implemented in DataFlash_SITL.
Referenced by ReadBlock(), and StartRead().
virtual void DataFlash_Block::BlockWrite (uint8_t BufferNum, uint16_t IntPageAdr, const void * pHeader, uint8_t hdr_size, const void * pBuffer, uint16_t size) private pure virtual
Implemented in DataFlash_SITL.
Referenced by WritePrioritisedBlock().
uint32_t DataFlash_Block::bufferspace_available () virtual
Implements DataFlash_Backend.
Definition at line 15 of file DataFlash_Block.cpp.
Referenced by DataFlash_Block().
virtual void DataFlash_Block::BufferToPage (uint8_t BufferNum, uint16_t PageAdr, uint8_t wait) private pure virtual
Implemented in DataFlash_SITL.
Referenced by FinishWrite().
virtual bool DataFlash_Block::CardInserted (void) pure virtual
Implements DataFlash_Backend.
Implemented in DataFlash_SITL.
Referenced by DataFlash_Block(), ShowDeviceInfo(), and WritePrioritisedBlock().
bool DataFlash_Block::check_wrapped (void) private
Definition at line 165 of file LogFile.cpp.
Referenced by find_last_page_of_log().
virtual void DataFlash_Block::ChipErase () private pure virtual
Implemented in DataFlash_SITL.
void DataFlash_Block::DumpPageInfo (AP_HAL::BetterStream * port) virtual
Implements DataFlash_Backend.
Definition at line 525 of file LogFile.cpp.
Referenced by DataFlash_Block().
void DataFlash_Block::EraseAll () virtual
Implements DataFlash_Backend.
Definition at line 180 of file DataFlash_Block.cpp.
Referenced by DataFlash_Block(), and Prep().
uint16_t DataFlash_Block::find_last_log (void) override virtual
Implements DataFlash_Backend.
Definition at line 175 of file LogFile.cpp.
Referenced by DataFlash_Block(), get_log_boundaries(), ListAvailableLogs(), and start_new_log().
uint16_t DataFlash_Block::find_last_page (void) private
Definition at line 183 of file LogFile.cpp.
Referenced by find_last_log(), find_last_page_of_log(), get_log_boundaries(), get_num_logs(), and start_new_log().
uint16_t DataFlash_Block::find_last_page_of_log (uint16_t log_number) private
Definition at line 224 of file LogFile.cpp.
Referenced by get_log_boundaries().
void DataFlash_Block::FinishWrite (void) private
Definition at line 31 of file DataFlash_Block.cpp.
Referenced by EraseAll(), get_log_boundaries(), LogReadProcess(), and WritePrioritisedBlock().
void DataFlash_Block::get_log_boundaries (uint16_t log_num, uint16_t & start_page, uint16_t & end_page) virtual
Implements DataFlash_Backend.
Definition at line 101 of file LogFile.cpp.
Referenced by DataFlash_Block(), get_log_info(), and ListAvailableLogs().
int16_t DataFlash_Block::get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data) virtual
get data from a log, accounting for adding FMT headers
Implements DataFlash_Backend.
Definition at line 261 of file DataFlash_Block.cpp.
Referenced by DataFlash_Block().
int16_t DataFlash_Block::get_log_data_raw (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data)
get raw data from a log
Definition at line 234 of file DataFlash_Block.cpp.
Referenced by DataFlash_Block(), and get_log_data().
void DataFlash_Block::get_log_info (uint16_t log_num, uint32_t & size, uint32_t & time_utc) virtual
Implements DataFlash_Backend.
Definition at line 153 of file LogFile.cpp.
Referenced by DataFlash_Block().
uint16_t DataFlash_Block::get_num_logs (void) override virtual
Implements DataFlash_Backend.
Definition at line 25 of file LogFile.cpp.
Referenced by DataFlash_Block(), get_log_boundaries(), and ListAvailableLogs().
uint16_t DataFlash_Block::GetFileNumber () private
Definition at line 170 of file DataFlash_Block.cpp.
Referenced by check_wrapped(), DumpPageInfo(), find_last_log(), find_last_page(), find_last_page_of_log(), get_log_boundaries(), get_num_logs(), and start_new_log().
uint16_t DataFlash_Block::GetFilePage () private
Definition at line 175 of file DataFlash_Block.cpp.
Referenced by DumpPageInfo(), find_last_page(), find_last_page_of_log(), and start_new_log().
uint16_t DataFlash_Block::GetPage (void) private
Definition at line 99 of file DataFlash_Block.cpp.
Referenced by LogReadProcess().
uint16_t DataFlash_Block::GetWritePage (void) private
Definition at line 93 of file DataFlash_Block.cpp.
void DataFlash_Block::ListAvailableLogs (AP_HAL::BetterStream * port) virtual
Implements DataFlash_Backend.
Definition at line 556 of file LogFile.cpp.
Referenced by DataFlash_Block().
void DataFlash_Block::LogReadProcess (const uint16_t list_entry, uint16_t start_page, uint16_t end_page, print_mode_fn print_mode, AP_HAL::BetterStream * port) virtual
Implements DataFlash_Backend.
Definition at line 465 of file LogFile.cpp.
Referenced by DataFlash_Block().
bool DataFlash_Block::NeedErase (void) private
Definition at line 220 of file DataFlash_Block.cpp.
Referenced by NeedPrep(), and Prep().
bool DataFlash_Block::NeedPrep (void) virtual
Implements DataFlash_Backend.
Definition at line 201 of file DataFlash_Block.cpp.
Referenced by DataFlash_Block().
virtual void DataFlash_Block::PageErase (uint16_t PageAdr) private pure virtual
Implemented in DataFlash_SITL.
virtual void DataFlash_Block::PageToBuffer (uint8_t BufferNum, uint16_t PageAdr) private pure virtual
Implemented in DataFlash_SITL.
Referenced by ReadBlock(), and StartRead().
void DataFlash_Block::Prep () virtual
Implements DataFlash_Backend.
Definition at line 206 of file DataFlash_Block.cpp.
Referenced by DataFlash_Block().
bool DataFlash_Block::ReadBlock (void * pBuffer, uint16_t size) private virtual
Implements DataFlash_Backend.
Definition at line 125 of file DataFlash_Block.cpp.
Referenced by DataFlash_Backend::_print_log_entry(), get_log_data_raw(), LogReadProcess(), and NeedErase().
virtual void DataFlash_Block::ReadManufacturerID () protected pure virtual
Implemented in DataFlash_SITL.
Referenced by ShowDeviceInfo().
void DataFlash_Block::SetFileNumber (uint16_t FileNumber) private
Definition at line 164 of file DataFlash_Block.cpp.
Referenced by start_new_log().
void DataFlash_Block::ShowDeviceInfo (AP_HAL::BetterStream * port) virtual
Implements DataFlash_Backend.
Definition at line 538 of file LogFile.cpp.
Referenced by DataFlash_Block().
uint16_t DataFlash_Block::start_new_log (void) virtual
Implements DataFlash_Backend.
Definition at line 59 of file LogFile.cpp.
Referenced by DataFlash_Block().
void DataFlash_Block::StartRead (uint16_t PageAdr) private
Definition at line 104 of file DataFlash_Block.cpp.
Referenced by check_wrapped(), DumpPageInfo(), find_last_log(), find_last_page(), find_last_page_of_log(), get_log_boundaries(), get_log_data_raw(), get_num_logs(), LogReadProcess(), NeedErase(), and start_new_log().
void DataFlash_Block::StartWrite (uint16_t PageAdr) private
Definition at line 23 of file DataFlash_Block.cpp.
Referenced by EraseAll(), and start_new_log().
virtual void DataFlash_Block::WaitReady () private pure virtual
Implemented in DataFlash_SITL.
Referenced by ReadBlock(), StartRead(), and StartWrite().
bool DataFlash_Block::WritePrioritisedBlock (const void * pBuffer, uint16_t size, bool is_critical) virtual
Implements DataFlash_Backend.
Definition at line 45 of file DataFlash_Block.cpp.
Referenced by DataFlash_Block().
Member Data Documentation
bool DataFlash_Block::adding_fmt_headers private
Definition at line 62 of file DataFlash_Block.h.
Referenced by get_log_data().
uint16_t DataFlash_Block::df_BufferIdx private
Definition at line 54 of file DataFlash_Block.h.
Referenced by FinishWrite(), get_log_boundaries(), LogReadProcess(), StartWrite(), and WritePrioritisedBlock().
uint8_t DataFlash_Block::df_BufferNum private
Definition at line 52 of file DataFlash_Block.h.
Referenced by FinishWrite(), StartWrite(), and WritePrioritisedBlock().
uint16_t DataFlash_Block::df_device protected
Definition at line 111 of file DataFlash_Block.h.
Referenced by DataFlash_SITL::ReadManufacturerID(), and ShowDeviceInfo().
uint16_t DataFlash_Block::df_FileNumber private
Definition at line 58 of file DataFlash_Block.h.
Referenced by GetFileNumber(), ReadBlock(), SetFileNumber(), StartRead(), and WritePrioritisedBlock().
uint16_t DataFlash_Block::df_FilePage private
Definition at line 59 of file DataFlash_Block.h.
Referenced by GetFilePage(), ReadBlock(), SetFileNumber(), StartRead(), and WritePrioritisedBlock().
uint8_t DataFlash_Block::df_manufacturer protected
Definition at line 110 of file DataFlash_Block.h.
Referenced by DataFlash_SITL::ReadManufacturerID(), and ShowDeviceInfo().
uint16_t DataFlash_Block::df_NumPages protected
Definition at line 115 of file DataFlash_Block.h.
Referenced by bufferspace_available(), check_wrapped(), DumpPageInfo(), EraseAll(), find_last_page(), find_last_page_of_log(), FinishWrite(), get_log_boundaries(), get_log_data_raw(), get_log_info(), DataFlash_SITL::Init(), NeedErase(), ReadBlock(), and ShowDeviceInfo().
uint16_t DataFlash_Block::df_PageAdr private
Definition at line 56 of file DataFlash_Block.h.
Referenced by FinishWrite(), GetWritePage(), and StartWrite().
uint16_t DataFlash_Block::df_PageSize protected
Definition at line 114 of file DataFlash_Block.h.
Referenced by bufferspace_available(), get_log_data_raw(), get_log_info(), DataFlash_SITL::Init(), DataFlash_SITL::PageSize(), ReadBlock(), ShowDeviceInfo(), and WritePrioritisedBlock().
uint16_t DataFlash_Block::df_Read_BufferIdx private
Definition at line 55 of file DataFlash_Block.h.
Referenced by get_log_data_raw(), ReadBlock(), and StartRead().
uint8_t DataFlash_Block::df_Read_BufferNum private
Definition at line 53 of file DataFlash_Block.h.
Referenced by ReadBlock(), and StartRead().
uint16_t DataFlash_Block::df_Read_PageAdr private
Definition at line 57 of file DataFlash_Block.h.
Referenced by get_log_data_raw(), GetPage(), ReadBlock(), and StartRead().
The documentation for this class was generated from the following files:
libraries/DataFlash/DataFlash_Block.h
libraries/DataFlash/DataFlash_Block.cpp
libraries/DataFlash/LogFile.cpp