APM:Libraries: GCS Class Reference
GCS Class Reference
global GCS object
#include <GCS.h>
Classes
struct statustext_t
Public Member Functions
GCS ()
virtual void send_statustext (MAV_SEVERITY severity, uint8_t dest_bitmask, const char *text)
void service_statustext (void)
void set_dataflash (DataFlash_Class *dataflash)
void register_frsky_telemetry_callback (AP_Frsky_Telem *frsky_telemetry)
Static Public Member Functions
static class GCS * instance ()
Public Attributes
DataFlash_Class * dataflash_p
AP_Frsky_Telem * frsky_telemetry_p
Private Attributes
ObjectArray< statustext_t > _statustext_queue {_status_capacity}
Static Private Attributes
static GCS * _singleton = nullptr
static const uint8_t _status_capacity = 5
Detailed Description
global GCS object
Definition at line 400 of file GCS.h.
Constructor & Destructor Documentation
GCS::GCS () inline
Definition at line 405 of file GCS.h.
Member Function Documentation
static class GCS* GCS::instance (void) inline static
Definition at line 417 of file GCS.h.
Referenced by gcs().
void GCS::register_frsky_telemetry_callback (AP_Frsky_Telem * frsky_telemetry) inline
Definition at line 438 of file GCS.h.
Referenced by AP_Frsky_Telem::init().
void GCS::send_statustext (MAV_SEVERITY severity, uint8_t dest_bitmask, const char * text) virtual
Definition at line 1350 of file GCS_Common.cpp.
Referenced by instance(), GCS_MAVLINK::send_statustext_all(), and GCS_MAVLINK::send_statustext_chan().
void GCS::service_statustext (void)
Definition at line 1384 of file GCS_Common.cpp.
Referenced by instance().
void GCS::set_dataflash (DataFlash_Class * dataflash) inline
Definition at line 427 of file GCS.h.
Member Data Documentation
GCS * GCS::_singleton = nullptr static private
Definition at line 447 of file GCS.h.
Referenced by instance().
const uint8_t GCS::_status_capacity = 5 static private
Definition at line 455 of file GCS.h.
ObjectArray<statustext_t> GCS::_statustext_queue {_status_capacity} private
Definition at line 460 of file GCS.h.
DataFlash_Class* GCS::dataflash_p
Definition at line 432 of file GCS.h.
Referenced by set_dataflash().
AP_Frsky_Telem* GCS::frsky_telemetry_p
Definition at line 443 of file GCS.h.
The documentation for this class was generated from the following files:
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp