APM:Libraries: Compass Class Reference
Compass Class Reference
#include <AP_Compass.h>
Classes
struct mag_state
Public Types
enum LearnType { LEARN_NONE =0, LEARN_INTERNAL =1, LEARN_EKF =2 }
Public Member Functions
Compass ()
bool init ()
bool read ()
void accumulate ()
float calculate_heading (const Matrix3f &dcm_matrix) const
float calculate_heading (const Matrix3f &dcm_matrix, uint8_t i) const
void set_offsets (uint8_t i, const Vector3f &offsets)
void set_and_save_offsets (uint8_t i, const Vector3f &offsets)
void set_and_save_diagonals (uint8_t i, const Vector3f &diagonals)
void set_and_save_offdiagonals (uint8_t i, const Vector3f &diagonals)
void save_offsets (uint8_t i)
void save_offsets (void)
uint8_t get_count (void) const
const Vector3f & get_field (uint8_t i) const
Return the current field as a Vector3f in milligauss.
const Vector3f & get_field (void) const
void compass_cal_update ()
void start_calibration_all (bool retry=false, bool autosave=false, float delay_sec=0.0f, bool autoreboot=false)
void cancel_calibration_all ()
bool compass_cal_requires_reboot ()
bool is_calibrating () const
uint8_t handle_mag_cal_command (const mavlink_command_long_t &packet)
void send_mag_cal_progress (mavlink_channel_t chan)
void send_mag_cal_report (mavlink_channel_t chan)
bool consistent () const
bool healthy (uint8_t i) const
Return the health of a compass.
bool healthy (void) const
uint8_t get_healthy_mask () const
const Vector3f & get_offsets (uint8_t i) const
const Vector3f & get_offsets (void) const
void set_initial_location (int32_t latitude, int32_t longitude)
void set_and_save_offsets (uint8_t i, int x, int y, int z)
bool learn_offsets_enabled () const
void learn_offsets (void)
bool use_for_yaw (uint8_t i) const
return true if the compass should be used for yaw calculations
bool use_for_yaw (void) const
return true if the compass should be used for yaw calculations
void set_declination (float radians, bool save_to_eeprom=true)
float get_declination () const
void set_board_orientation (enum Rotation orientation)
void motor_compensation_type (const uint8_t comp_type)
uint8_t get_motor_compensation_type () const
get the motor compensation value.
void set_motor_compensation (uint8_t i, const Vector3f &motor_comp_factor)
const Vector3f & get_motor_compensation (uint8_t i) const
get motor compensation factors as a vector
const Vector3f & get_motor_compensation (void) const
void save_motor_compensation ()
const Vector3f & get_motor_offsets (uint8_t i) const
const Vector3f & get_motor_offsets (void) const
void set_throttle (float thr_pct)
void set_current (float amps)
bool configured (uint8_t i)
bool configured (void)
uint8_t get_primary (void) const
void setHIL (uint8_t instance, float roll, float pitch, float yaw)
void setHIL (uint8_t instance, const Vector3f &mag, uint32_t last_update_usec)
const Vector3f & getHIL (uint8_t instance) const
void _setup_earth_field ()
void set_hil_mode (void)
uint32_t last_update_usec (void) const
uint32_t last_update_usec (uint8_t i) const
enum LearnType get_learn_type (void) const
uint16_t get_offsets_max (void) const
Public Attributes
struct {
Vector3f Bearth
float last_declination
bool healthy [COMPASS_MAX_INSTANCES]
Vector3f field [COMPASS_MAX_INSTANCES]
} _hil
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
uint8_t register_compass (void)
bool _add_backend (AP_Compass_Backend *backend, const char *name, bool external)
void _detect_backends (void)
bool _accept_calibration (uint8_t i)
bool _accept_calibration_mask (uint8_t mask)
void _cancel_calibration (uint8_t i)
void _cancel_calibration_mask (uint8_t mask)
uint8_t _get_cal_mask () const
bool _start_calibration (uint8_t i, bool retry=false, float delay_sec=0.0f)
bool _start_calibration_mask (uint8_t mask, bool retry=false, bool autosave=false, float delay_sec=0.0f, bool autoreboot=false)
bool _auto_reboot ()
Private Attributes
bool _cal_saved [COMPASS_MAX_INSTANCES]
bool _cal_autosave
bool _compass_cal_autoreboot
bool _cal_complete_requires_reboot
bool _cal_has_run
AP_Compass_Backend * _backends [COMPASS_MAX_BACKEND]
uint8_t _backend_count
uint8_t _compass_count
AP_Int8 _learn
enum Rotation _board_orientation
AP_Int8 _primary
AP_Float _declination
AP_Int8 _auto_declination
bool _null_init_done
AP_Int8 _motor_comp_type
float _thr_or_curr
struct Compass::mag_state _state [COMPASS_MAX_INSTANCES]
AP_Int16 _offset_max
CompassCalibrator _calibrator [COMPASS_MAX_INSTANCES]
bool _hil_mode:1
AP_Float _calibration_threshold
Static Private Attributes
static const uint8_t _mag_history_size = 20
Friends
class AP_Compass_Backend
Detailed Description
Definition at line 45 of file AP_Compass.h.
Member Enumeration Documentation
enum Compass::LearnType
Enumerator
LEARN_NONE
LEARN_INTERNAL
LEARN_EKF
Definition at line 274 of file AP_Compass.h.
Constructor & Destructor Documentation
Compass::Compass (void)
Constructor
Definition at line 429 of file AP_Compass.cpp.
Member Function Documentation
bool Compass::_accept_calibration (uint8_t i) private
Definition at line 132 of file AP_Compass_Calibration.cpp.
Referenced by _accept_calibration_mask(), compass_cal_update(), and get_offsets_max().
bool Compass::_accept_calibration_mask (uint8_t mask) private
Definition at line 160 of file AP_Compass_Calibration.cpp.
Referenced by get_offsets_max(), and handle_mag_cal_command().
bool Compass::_add_backend (AP_Compass_Backend * backend, const char * name, bool external) private
Definition at line 479 of file AP_Compass.cpp.
Referenced by _detect_backends(), and get_offsets_max().
bool Compass::_auto_reboot () inline private
Definition at line 308 of file AP_Compass.h.
Referenced by compass_cal_update().
void Compass::_cancel_calibration (uint8_t i) private
Definition at line 104 of file AP_Compass_Calibration.cpp.
Referenced by _cancel_calibration_mask(), and get_offsets_max().
void Compass::_cancel_calibration_mask (uint8_t mask) private
Definition at line 116 of file AP_Compass_Calibration.cpp.
Referenced by _start_calibration_mask(), cancel_calibration_all(), get_offsets_max(), and handle_mag_cal_command().
void Compass::_detect_backends (void) private
Definition at line 497 of file AP_Compass.cpp.
Referenced by get_offsets_max(), and init().
uint8_t Compass::_get_cal_mask () const private
Definition at line 255 of file AP_Compass_Calibration.cpp.
Referenced by get_offsets_max(), send_mag_cal_progress(), and send_mag_cal_report().
void Compass::_setup_earth_field (void)
Definition at line 980 of file AP_Compass.cpp.
Referenced by AP_Compass_HIL::AP_Compass_HIL(), get_primary(), and setHIL().
bool Compass::_start_calibration (uint8_t i, bool retry = false, float delay_sec = 0.0f) private
Definition at line 45 of file AP_Compass_Calibration.cpp.
Referenced by _start_calibration_mask(), get_offsets_max(), and start_calibration_all().
bool Compass::_start_calibration_mask (uint8_t mask, bool retry = false, bool autosave = false, float delay_sec = 0.0f, bool autoreboot = false) private
Definition at line 74 of file AP_Compass_Calibration.cpp.
Referenced by get_offsets_max(), and handle_mag_cal_command().
void Compass::accumulate (void)
use spare CPU cycles to accumulate values from the compass if possible (this method should also be implemented in the backends)
Definition at line 712 of file AP_Compass.cpp.
Referenced by loop().
float Compass::calculate_heading (const Matrix3f & dcm_matrix) const inline
Calculate the tilt-compensated heading_ variables.
Parameters
dcm_matrix The current orientation rotation matrix
Returns
heading in radians
Definition at line 74 of file AP_Compass.h.
Referenced by AP_AHRS_DCM::drift_correction_yaw(), and loop().
float Compass::calculate_heading (const Matrix3f & dcm_matrix, uint8_t i) const
Definition at line 861 of file AP_Compass.cpp.
void Compass::cancel_calibration_all ()
Definition at line 126 of file AP_Compass_Calibration.cpp.
Referenced by compass_cal_update(), get_field(), and handle_mag_cal_command().
bool Compass::compass_cal_requires_reboot () inline
Definition at line 119 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks().
void Compass::compass_cal_update ()
Definition at line 10 of file AP_Compass_Calibration.cpp.
Referenced by get_field().
bool Compass::configured (uint8_t i)
Returns True if the compasses have been configured (i.e. offsets saved)
Returns
True if compass has been configured
Definition at line 894 of file AP_Compass.cpp.
Referenced by AP_Arming::compass_checks().
bool Compass::configured (void)
Definition at line 924 of file AP_Compass.cpp.
Referenced by set_current().
bool Compass::consistent () const
Definition at line 1006 of file AP_Compass.cpp.
Referenced by compass_cal_requires_reboot(), AP_Arming::compass_checks(), NavEKF2_core::readMagData(), and NavEKF3_core::readMagData().
uint8_t Compass::get_count (void) const inline
Definition at line 106 of file AP_Compass.h.
Referenced by configured(), consistent(), DataFlash_Class::Log_Write_Compass(), loop(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), GCS_MAVLINK::send_raw_imu(), and setup().
float Compass::get_declination () const
Definition at line 852 of file AP_Compass.cpp.
Referenced by _setup_earth_field(), NavEKF2_core::alignMagStateDeclination(), NavEKF3_core::alignMagStateDeclination(), SoloGimbalEKF::calcMagHeadingInnov(), NavEKF2_core::calcQuatAndFieldStates(), NavEKF3_core::calcQuatAndFieldStates(), NavEKF2_core::FuseDeclination(), NavEKF3_core::FuseDeclination(), NavEKF2_core::fuseEulerYaw(), NavEKF3_core::fuseEulerYaw(), learn_offsets_enabled(), GCS_MAVLINK::send_sensor_offsets(), setHIL(), and AP_AHRS_DCM::yaw_error_compass().
const Vector3f& Compass::get_field (uint8_t i) const inline
Return the current field as a Vector3f in milligauss.
Definition at line 109 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks(), DataFlash_Class::Log_Write_Compass(), loop(), SoloGimbalEKF::readMagData(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), GCS_MAVLINK::send_raw_imu(), and AP_AHRS_DCM::yaw_error_compass().
const Vector3f& Compass::get_field (void) const inline
Definition at line 110 of file AP_Compass.h.
Referenced by calculate_heading(), consistent(), and get_field().
uint8_t Compass::get_healthy_mask () const
Definition at line 734 of file AP_Compass.cpp.
Referenced by healthy().
enum LearnType Compass::get_learn_type (void) const inline
Definition at line 281 of file AP_Compass.h.
const Vector3f& Compass::get_motor_compensation (uint8_t i) const inline
get motor compensation factors as a vector
Definition at line 206 of file AP_Compass.h.
const Vector3f& Compass::get_motor_compensation (void) const inline
Definition at line 207 of file AP_Compass.h.
Referenced by get_motor_compensation().
uint8_t Compass::get_motor_compensation_type () const inline
get the motor compensation value.
Definition at line 194 of file AP_Compass.h.
const Vector3f& Compass::get_motor_offsets (uint8_t i) const inline
Returns the current motor compensation offset values
Returns
The current compass offsets in milligauss.
Definition at line 219 of file AP_Compass.h.
Referenced by DataFlash_Class::Log_Write_Compass().
const Vector3f& Compass::get_motor_offsets (void) const inline
Definition at line 220 of file AP_Compass.h.
Referenced by get_motor_offsets().
const Vector3f& Compass::get_offsets (uint8_t i) const inline
Returns the current offset values
Returns
The current compass offsets in milligauss.
Definition at line 142 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks(), NavEKF2_core::getMagOffsets(), NavEKF3_core::getMagOffsets(), DataFlash_Class::Log_Write_Compass(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), and GCS_MAVLINK::send_sensor_offsets().
const Vector3f& Compass::get_offsets (void) const inline
Definition at line 143 of file AP_Compass.h.
Referenced by configured(), and get_offsets().
uint16_t Compass::get_offsets_max (void) const inline
Definition at line 286 of file AP_Compass.h.
Referenced by _start_calibration(), and AP_Arming::compass_checks().
uint8_t Compass::get_primary (void) const inline
Returns the instance of the primary compass
Returns
the instance number of the primary compass
Definition at line 249 of file AP_Compass.h.
Referenced by _start_calibration(), calculate_heading(), get_field(), get_motor_compensation(), get_motor_offsets(), get_offsets(), healthy(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), last_update_usec(), and use_for_yaw().
const Vector3f & Compass::getHIL (uint8_t instance) const
Definition at line 974 of file AP_Compass.cpp.
Referenced by get_primary().
uint8_t Compass::handle_mag_cal_command (const mavlink_command_long_t & packet)
Definition at line 270 of file AP_Compass_Calibration.cpp.
Referenced by compass_cal_requires_reboot().
bool Compass::healthy (uint8_t i) const inline
Return the health of a compass.
Definition at line 134 of file AP_Compass.h.
bool Compass::healthy (void) const inline
Definition at line 135 of file AP_Compass.h.
Referenced by _start_calibration(), get_healthy_mask(), healthy(), read(), and use_for_yaw().
bool Compass::init (void)
Initialize the compass device.
Returns
True if the compass was initialized OK, false if it was not found or is not functioning.
Definition at line 455 of file AP_Compass.cpp.
Referenced by setup().
bool Compass::is_calibrating () const
Definition at line 239 of file AP_Compass_Calibration.cpp.
Referenced by _accept_calibration(), _start_calibration(), compass_cal_requires_reboot(), compass_cal_update(), and AP_Arming::compass_checks().
uint32_t Compass::last_update_usec (void) const inline
Definition at line 261 of file AP_Compass.h.
Referenced by AP_AHRS_DCM::drift_correction_yaw(), get_primary(), DataFlash_Class::Log_Write_Compass(), AP_Compass_HIL::read(), SoloGimbalEKF::readMagData(), NavEKF2_core::readMagData(), and NavEKF3_core::readMagData().
uint32_t Compass::last_update_usec (uint8_t i) const inline
Definition at line 262 of file AP_Compass.h.
void Compass::learn_offsets (void)
Perform automatic offset updates
Definition at line 29 of file Compass_learn.cpp.
Referenced by learn_offsets_enabled(), and loop().
bool Compass::learn_offsets_enabled () const inline
Definition at line 164 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks().
void Compass::motor_compensation_type (const uint8_t comp_type)
Set the motor compensation type
Parameters
comp_type 0 = disabled, 1 = enabled use throttle, 2 = enabled use current
Definition at line 995 of file AP_Compass.cpp.
Referenced by set_board_orientation().
bool Compass::read (void)
Read the compass and update the mag_ variables.
Definition at line 721 of file AP_Compass.cpp.
Referenced by AP_AHRS_DCM::drift_correction_yaw(), init(), and loop().
uint8_t Compass::register_compass (void) private
Register a new compas driver, allocating an instance number
Returns
number of compass instances
Definition at line 471 of file AP_Compass.cpp.
Referenced by get_offsets_max(), and AP_Compass_Backend::register_compass().
void Compass::save_motor_compensation ()
Saves the current motor compensation x/y/z values.
This should be invoked periodically to save the offset values calculated by the motor compensation auto learning
Definition at line 804 of file AP_Compass.cpp.
Referenced by get_motor_compensation().
void Compass::save_offsets (uint8_t i)
Saves the current offset x/y/z values for one or all compasses
Parameters
i compass instance
This should be invoked periodically to save the offset values maintained by ::learn_offsets.
Definition at line 783 of file AP_Compass.cpp.
void Compass::save_offsets (void)
Definition at line 790 of file AP_Compass.cpp.
Referenced by calculate_heading(), and set_and_save_offsets().
void Compass::send_mag_cal_progress (mavlink_channel_t chan)
Definition at line 176 of file AP_Compass_Calibration.cpp.
Referenced by compass_cal_requires_reboot().
void Compass::send_mag_cal_report (mavlink_channel_t chan)
Definition at line 207 of file AP_Compass_Calibration.cpp.
Referenced by compass_cal_requires_reboot().
void Compass::set_and_save_diagonals (uint8_t i, const Vector3f & diagonals)
Definition at line 765 of file AP_Compass.cpp.
Referenced by _accept_calibration(), and calculate_heading().
void Compass::set_and_save_offdiagonals (uint8_t i, const Vector3f & diagonals)
Definition at line 774 of file AP_Compass.cpp.
Referenced by _accept_calibration(), and calculate_heading().
void Compass::set_and_save_offsets (uint8_t i, const Vector3f & offsets)
Sets and saves the compass offset x/y/z values.
Parameters
i compass instance
offsets Offsets to the raw mag_ values in milligauss.
Definition at line 755 of file AP_Compass.cpp.
Referenced by _accept_calibration(), calculate_heading(), set_and_save_offsets(), and setup().
void Compass::set_and_save_offsets (uint8_t i, int x, int y, int z) inline
Program new offset values.
Parameters
i compass instance
x Offset to the raw mag_x value in milligauss.
y Offset to the raw mag_y value in milligauss.
z Offset to the raw mag_z value in milligauss.
Definition at line 159 of file AP_Compass.h.
void Compass::set_board_orientation (enum Rotation orientation) inline
Definition at line 183 of file AP_Compass.h.
Referenced by AP_AHRS::set_orientation().
void Compass::set_current (float amps) inline
Set the current used by system in amps
Parameters
amps current flowing to the motors expressed in amps
Definition at line 232 of file AP_Compass.h.
void Compass::set_declination (float radians, bool save_to_eeprom = true)
Sets the local magnetic field declination.
Parameters
radians Local field declination.
save_to_eeprom true to save to eeprom (false saves only to memory)
Definition at line 842 of file AP_Compass.cpp.
Referenced by learn_offsets_enabled(), and setup().
void Compass::set_hil_mode (void) inline
Definition at line 258 of file AP_Compass.h.
void Compass::set_initial_location (int32_t latitude, int32_t longitude)
Sets the initial location used to get declination
Parameters
latitude GPS Latitude.
longitude GPS Longitude.
Definition at line 813 of file AP_Compass.cpp.
Referenced by get_offsets().
void Compass::set_motor_compensation (uint8_t i, const Vector3f & motor_comp_factor)
Set the motor compensation factor x/y/z values.
Parameters
i instance of compass
offsets Offsets multiplied by the throttle value and added to the raw mag_ values.
Definition at line 798 of file AP_Compass.cpp.
Referenced by get_motor_compensation_type(), and motor_compensation_type().
void Compass::set_offsets (uint8_t i, const Vector3f & offsets)
Sets offset x/y/z values.
Parameters
i compass instance
offsets Offsets to the raw mag_ values in milligauss.
Definition at line 746 of file AP_Compass.cpp.
Referenced by calculate_heading().
void Compass::set_throttle (float thr_pct) inline
Set the throttle as a percentage from 0.0 to 1.0
Parameters
thr_pct throttle expressed as a percentage from 0 to 1.0
Definition at line 224 of file AP_Compass.h.
void Compass::setHIL (uint8_t instance, float roll, float pitch, float yaw)
Definition at line 935 of file AP_Compass.cpp.
Referenced by HALSITL::SITL_State::_update_compass(), and get_primary().
void Compass::setHIL (uint8_t instance, const Vector3f & mag, uint32_t last_update_usec)
Definition at line 967 of file AP_Compass.cpp.
void Compass::start_calibration_all (bool retry = false, bool autosave = false, float delay_sec = 0.0f, bool autoreboot = false)
Definition at line 91 of file AP_Compass_Calibration.cpp.
Referenced by get_field(), and handle_mag_cal_command().
bool Compass::use_for_yaw (uint8_t i) const
return true if the compass should be used for yaw calculations
return true if the specified compass can be used for yaw calculations
Definition at line 836 of file AP_Compass.cpp.
Referenced by AP_AHRS_NavEKF::active_EKF_type(), AP_Arming::compass_checks(), loop(), SoloGimbalEKF::readMagData(), NavEKF2_core::readMagData(), NavEKF3_core::readMagData(), AP_AHRS_DCM::use_compass(), NavEKF2_core::use_compass(), NavEKF3_core::use_compass(), and AP_AHRS::use_compass().
bool Compass::use_for_yaw (void) const
return true if the compass should be used for yaw calculations
Definition at line 828 of file AP_Compass.cpp.
Referenced by _start_calibration(), configured(), consistent(), and learn_offsets_enabled().
Friends And Related Function Documentation
friend class AP_Compass_Backend friend
Definition at line 47 of file AP_Compass.h.
Member Data Documentation
AP_Int8 Compass::_auto_declination private
Definition at line 340 of file AP_Compass.h.
Referenced by set_initial_location().
uint8_t Compass::_backend_count private
Definition at line 322 of file AP_Compass.h.
Referenced by _add_backend(), _detect_backends(), accumulate(), and read().
AP_Compass_Backend* Compass::_backends[COMPASS_MAX_BACKEND] private
Definition at line 321 of file AP_Compass.h.
Referenced by _add_backend(), _detect_backends(), accumulate(), Compass(), and read().
enum Rotation Compass::_board_orientation private
Definition at line 331 of file AP_Compass.h.
Referenced by AP_Compass_Backend::rotate_field(), set_board_orientation(), and setHIL().
bool Compass::_cal_autosave private
Definition at line 313 of file AP_Compass.h.
Referenced by _start_calibration_mask(), compass_cal_update(), and start_calibration_all().
bool Compass::_cal_complete_requires_reboot private
Definition at line 317 of file AP_Compass.h.
Referenced by _accept_calibration(), and compass_cal_requires_reboot().
bool Compass::_cal_has_run private
Definition at line 318 of file AP_Compass.h.
Referenced by compass_cal_update().
bool Compass::_cal_saved[COMPASS_MAX_INSTANCES] private
Definition at line 312 of file AP_Compass.h.
Referenced by _accept_calibration(), _cancel_calibration(), _start_calibration(), compass_cal_update(), and send_mag_cal_report().
AP_Float Compass::_calibration_threshold private
Definition at line 397 of file AP_Compass.h.
Referenced by _start_calibration().
CompassCalibrator Compass::_calibrator[COMPASS_MAX_INSTANCES] private
Definition at line 392 of file AP_Compass.h.
Referenced by _accept_calibration(), _accept_calibration_mask(), _cancel_calibration(), _get_cal_mask(), _start_calibration(), compass_cal_update(), is_calibrating(), AP_Compass_Backend::publish_raw_field(), send_mag_cal_progress(), and send_mag_cal_report().
bool Compass::_compass_cal_autoreboot private
Definition at line 316 of file AP_Compass.h.
Referenced by _auto_reboot(), _start_calibration_mask(), and start_calibration_all().
uint8_t Compass::_compass_count private
Definition at line 325 of file AP_Compass.h.
Referenced by _detect_backends(), get_count(), init(), and register_compass().
AP_Float Compass::_declination private
Definition at line 337 of file AP_Compass.h.
Referenced by calculate_heading(), get_declination(), set_declination(), and set_initial_location().
struct { ... } Compass::_hil
Referenced by _setup_earth_field(), getHIL(), AP_Compass_HIL::read(), and setHIL().
bool Compass::_hil_mode private
Definition at line 395 of file AP_Compass.h.
Referenced by _detect_backends(), and set_hil_mode().
AP_Int8 Compass::_learn private
Definition at line 328 of file AP_Compass.h.
Referenced by _start_calibration(), get_learn_type(), learn_offsets(), and learn_offsets_enabled().
const uint8_t Compass::_mag_history_size = 20 static private
Definition at line 346 of file AP_Compass.h.
Referenced by learn_offsets().
AP_Int8 Compass::_motor_comp_type private
Definition at line 350 of file AP_Compass.h.
Referenced by AP_Compass_Backend::correct_field(), get_motor_compensation_type(), motor_compensation_type(), save_motor_compensation(), set_current(), and set_throttle().
bool Compass::_null_init_done private
Definition at line 343 of file AP_Compass.h.
Referenced by learn_offsets().
AP_Int16 Compass::_offset_max private
Definition at line 390 of file AP_Compass.h.
Referenced by get_offsets_max().
AP_Int8 Compass::_primary private
Definition at line 334 of file AP_Compass.h.
Referenced by get_primary().
struct Compass::mag_state Compass::_state[COMPASS_MAX_INSTANCES] private
Referenced by _start_calibration(), Compass(), configured(), AP_Compass_Backend::correct_field(), get_field(), get_motor_compensation(), get_motor_offsets(), get_offsets(), healthy(), AP_Compass_Backend::is_external(), last_update_usec(), learn_offsets(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_Backend::publish_raw_field(), read(), AP_Compass_Backend::rotate_field(), save_motor_compensation(), save_offsets(), set_and_save_diagonals(), set_and_save_offdiagonals(), set_and_save_offsets(), AP_Compass_Backend::set_dev_id(), AP_Compass_Backend::set_external(), AP_Compass_Backend::set_last_update_usec(), set_motor_compensation(), set_offsets(), AP_Compass_Backend::set_rotation(), setHIL(), and use_for_yaw().
float Compass::_thr_or_curr private
Definition at line 353 of file AP_Compass.h.
Referenced by AP_Compass_Backend::correct_field(), motor_compensation_type(), set_current(), and set_throttle().
Vector3f Compass::Bearth
Definition at line 268 of file AP_Compass.h.
Vector3f Compass::field[COMPASS_MAX_INSTANCES]
Definition at line 271 of file AP_Compass.h.
Referenced by calculate_heading(), learn_offsets(), and AP_Compass_HIL::read().
bool Compass::healthy[COMPASS_MAX_INSTANCES]
Definition at line 270 of file AP_Compass.h.
Referenced by AP_Arming::compass_checks(), NavEKF2_core::getMagOffsets(), NavEKF3_core::getMagOffsets(), DataFlash_Class::Log_Write_Compass(), loop(), and AP_Compass_HIL::read().
float Compass::last_declination
Definition at line 269 of file AP_Compass.h.
const AP_Param::GroupInfo Compass::var_info static
Definition at line 264 of file AP_Compass.h.
Referenced by Compass().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass.h
libraries/AP_Compass/AP_Compass.cpp
libraries/AP_Compass/AP_Compass_Calibration.cpp
libraries/AP_Compass/Compass_learn.cpp