APM:Libraries: AP_HAL::AnalogIn Class Reference
AP_HAL::AnalogIn Class Reference abstract
#include <AnalogIn.h>
Public Member Functions
virtual void init ()=0
virtual AP_HAL::AnalogSource * channel (int16_t n)=0
virtual float board_voltage (void)=0
virtual float servorail_voltage (void)
virtual uint16_t power_status_flags (void)
Detailed Description
Definition at line 40 of file AnalogIn.h.
Member Function Documentation
virtual float AP_HAL::AnalogIn::board_voltage (void) pure virtual
Implemented in VRBRAIN::VRBRAINAnalogIn, AnalogIn_IIO, PX4::PX4AnalogIn, HALSITL::AnalogIn, AnalogIn_Raspilot, AnalogIn_ADS1115, AnalogIn_Navio2, and Empty::AnalogIn.
Referenced by AP_Airspeed_MS4525::_voltage_correction(), AP_Arming::board_voltage_checks(), DataFlash_Class::Log_Write_Power(), and GCS_MAVLINK::send_power_status().
virtual AP_HAL::AnalogSource* AP_HAL::AnalogIn::channel (int16_t n) pure virtual
Implemented in VRBRAIN::VRBRAINAnalogIn, PX4::PX4AnalogIn, AnalogIn_IIO, HALSITL::AnalogIn, AnalogIn_Navio2, AnalogIn_Raspilot, AnalogIn_ADS1115, and Empty::AnalogIn.
Referenced by AP_Airspeed_Analog::AP_Airspeed_Analog(), AP_BattMonitor_Analog::AP_BattMonitor_Analog(), AP_LeakDetector_Analog::AP_LeakDetector_Analog(), AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_RSSI::init(), and setup().
virtual void AP_HAL::AnalogIn::init () pure virtual
Implemented in VRBRAIN::VRBRAINAnalogIn, PX4::PX4AnalogIn, AnalogIn_IIO, HALSITL::AnalogIn, AnalogIn_Navio2, AnalogIn_Raspilot, AnalogIn_ADS1115, and Empty::AnalogIn.
Referenced by main_loop(), AP_BoardConfig::px4_setup_peripherals(), HAL_Linux::run(), and HAL_SITL::run().
virtual uint16_t AP_HAL::AnalogIn::power_status_flags (void) inline virtual
Reimplemented in VRBRAIN::VRBRAINAnalogIn, and PX4::PX4AnalogIn.
Definition at line 52 of file AnalogIn.h.
Referenced by DataFlash_Class::Log_Write_Power(), and GCS_MAVLINK::send_power_status().
virtual float AP_HAL::AnalogIn::servorail_voltage (void) inline virtual
Reimplemented in VRBRAIN::VRBRAINAnalogIn, PX4::PX4AnalogIn, and AnalogIn_Navio2.
Definition at line 49 of file AnalogIn.h.
Referenced by DataFlash_Class::Log_Write_Power(), and GCS_MAVLINK::send_power_status().
The documentation for this class was generated from the following file:
libraries/AP_HAL/AnalogIn.h