APM:Libraries: AP_Module Class Reference
AP_Module Class Reference
#include <AP_Module.h>
Classes
struct hook_list
Static Public Member Functions
static void init (const char *module_path)
static void call_hook_setup_start (void)
static void call_hook_setup_complete (void)
static void call_hook_AHRS_update (const AP_AHRS_NavEKF &ahrs)
static void call_hook_gyro_sample (uint8_t instance, float dt, const Vector3f &gyro)
static void call_hook_accel_sample (uint8_t instance, float dt, const Vector3f &accel, bool fsync_set)
Private Types
enum ModuleHooks {
HOOK_SETUP_START = 0, HOOK_SETUP_COMPLETE, HOOK_AHRS_UPDATE, HOOK_GYRO_SAMPLE,
HOOK_ACCEL_SAMPLE, NUM_HOOKS
}
Static Private Member Functions
static void module_scan (const char *path)
Static Private Attributes
static struct hook_list * hooks [NUM_HOOKS]
static const char * hook_names [NUM_HOOKS]
Detailed Description
Definition at line 43 of file AP_Module.h.
Member Enumeration Documentation
enum AP_Module::ModuleHooks private
Enumerator
HOOK_SETUP_START
HOOK_SETUP_COMPLETE
HOOK_AHRS_UPDATE
HOOK_GYRO_SAMPLE
HOOK_ACCEL_SAMPLE
NUM_HOOKS
Definition at line 67 of file AP_Module.h.
Member Function Documentation
void AP_Module::call_hook_accel_sample (uint8_t instance, float dt, const Vector3f & accel, bool fsync_set) static
Definition at line 254 of file AP_Module.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_accel_raw_sample().
void AP_Module::call_hook_AHRS_update (const AP_AHRS_NavEKF & ahrs) static
Definition at line 132 of file AP_Module.cpp.
Referenced by AP_AHRS_NavEKF::update().
void AP_Module::call_hook_gyro_sample (uint8_t instance, float dt, const Vector3f & gyro) static
Definition at line 224 of file AP_Module.cpp.
Referenced by AP_InertialSensor_Backend::_notify_new_gyro_raw_sample().
void AP_Module::call_hook_setup_complete (void) static
Definition at line 118 of file AP_Module.cpp.
Referenced by HAL_Linux::run().
void AP_Module::call_hook_setup_start (void) static
Definition at line 104 of file AP_Module.cpp.
Referenced by HAL_Linux::run().
void AP_Module::init (const char * module_path) static
Definition at line 76 of file AP_Module.cpp.
Referenced by HAL_Linux::run().
void AP_Module::module_scan (const char * path) static private
Definition at line 41 of file AP_Module.cpp.
Referenced by init().
Member Data Documentation
const char * AP_Module::hook_names static private
Initial value:
= {
    "ap_hook_setup_start",
    "ap_hook_setup_complete",
    "ap_hook_AHRS_update",
    "ap_hook_gyro_sample",
    "ap_hook_accel_sample",
}
Definition at line 88 of file AP_Module.h.
Referenced by module_scan().
struct AP_Module::hook_list * AP_Module::hooks static private
Definition at line 83 of file AP_Module.h.
Referenced by call_hook_accel_sample(), call_hook_AHRS_update(), call_hook_gyro_sample(), call_hook_setup_complete(), call_hook_setup_start(), and module_scan().
The documentation for this class was generated from the following files:
libraries/AP_Module/AP_Module.h
libraries/AP_Module/AP_Module.cpp