APM:Libraries: Linux::I2CDeviceManager Class Reference
Linux::I2CDeviceManager Class Reference
#include <I2CDevice.h>
Public Member Functions
I2CDeviceManager ()
AP_HAL::OwnPtr< AP_HAL::I2CDevice > get_device (std::vector< const char * > devpaths, uint8_t address)
AP_HAL::OwnPtr< AP_HAL::I2CDevice > get_device (uint8_t bus, uint8_t address) override
void teardown ()
Static Public Member Functions
static I2CDeviceManager * from (AP_HAL::I2CDeviceManager *i2c_mgr)
Protected Member Functions
void _unregister (I2CBus &b)
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _create_device (I2CBus &b, uint8_t address) const
Protected Attributes
std::vector< I2CBus * > _buses
Friends
class I2CDevice
Detailed Description
Definition at line 86 of file I2CDevice.h.
Constructor & Destructor Documentation
Linux::I2CDeviceManager::I2CDeviceManager ()
Definition at line 279 of file I2CDevice.cpp.
Member Function Documentation
AP_HAL::OwnPtr< AP_HAL::I2CDevice > Linux::I2CDeviceManager::_create_device (I2CBus & b, uint8_t address) const protected
Definition at line 377 of file I2CDevice.cpp.
void Linux::I2CDeviceManager::_unregister (I2CBus & b) protected
Definition at line 387 of file I2CDevice.cpp.
Referenced by Linux::I2CDevice::~I2CDevice().
static I2CDeviceManager* Linux::I2CDeviceManager::from (AP_HAL::I2CDeviceManager * i2c_mgr) inline static
Definition at line 90 of file I2CDevice.h.
Referenced by Compass::_detect_backends(), and Linux::I2CDevice::~I2CDevice().
AP_HAL::OwnPtr< AP_HAL::I2CDevice > Linux::I2CDeviceManager::get_device (std::vector< const char * > devpaths, uint8_t address)
Definition at line 286 of file I2CDevice.cpp.
Referenced by Compass::_detect_backends().
AP_HAL::OwnPtr< AP_HAL::I2CDevice > Linux::I2CDeviceManager::get_device (uint8_t bus, uint8_t address) override virtual
Implements AP_HAL::I2CDeviceManager.
Definition at line 347 of file I2CDevice.cpp.
void Linux::I2CDeviceManager::teardown ()
Definition at line 404 of file I2CDevice.cpp.
Friends And Related Function Documentation
friend class I2CDevice friend
Definition at line 88 of file I2CDevice.h.
Member Data Documentation
std::vector<I2CBus*> Linux::I2CDeviceManager::_buses protected
Definition at line 121 of file I2CDevice.h.
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/I2CDevice.h
libraries/AP_HAL_Linux/I2CDevice.cpp