APM:Libraries: HALSITL::EEPROMStorage Class Reference
HALSITL::EEPROMStorage Class Reference
#include <Storage.h>
Public Member Functions
EEPROMStorage ()
void init ()
void read_block (void *dst, uint16_t src, size_t n)
void write_block (uint16_t dst, const void *src, size_t n)
Private Member Functions
void _eeprom_open (void)
Private Attributes
int _eeprom_fd
Detailed Description
Definition at line 6 of file Storage.h.
Constructor & Destructor Documentation
HALSITL::EEPROMStorage::EEPROMStorage () inline
Definition at line 8 of file Storage.h.
Member Function Documentation
void EEPROMStorage::_eeprom_open (void) private
Definition at line 13 of file Storage.cpp.
Referenced by read_block(), and write_block().
void HALSITL::EEPROMStorage::init (void) inline virtual
Implements AP_HAL::Storage.
Definition at line 11 of file Storage.h.
void EEPROMStorage::read_block (void * dst, uint16_t src, size_t n) virtual
Implements AP_HAL::Storage.
Definition at line 21 of file Storage.cpp.
Referenced by init().
void EEPROMStorage::write_block (uint16_t dst, const void * src, size_t n) virtual
Implements AP_HAL::Storage.
Definition at line 28 of file Storage.cpp.
Referenced by init().
Member Data Documentation
int HALSITL::EEPROMStorage::_eeprom_fd private
Definition at line 16 of file Storage.h.
Referenced by _eeprom_open(), EEPROMStorage(), read_block(), and write_block().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/Storage.h
libraries/AP_HAL_SITL/Storage.cpp