APM:Libraries: PX4::PX4Storage Class Reference
PX4::PX4Storage Class Reference
#include <Storage.h>
Public Member Functions
PX4Storage ()
void init ()
void read_block (void *dst, uint16_t src, size_t n)
void write_block (uint16_t dst, const void *src, size_t n)
void _timer_tick (void)
Private Member Functions
void _storage_create (void)
void _storage_open (void)
void _mark_dirty (uint16_t loc, uint16_t length)
uint8_t _buffer[PX4_STORAGE_SIZE] __attribute__ ((aligned(4)))
void bus_lock (bool lock)
void _mtd_load (void)
void _mtd_write (uint16_t line)
Private Attributes
volatile bool _initialised
Bitmask _dirty_mask {PX4_STORAGE_NUM_LINES}
perf_counter_t _perf_storage
perf_counter_t _perf_errors
int _fd = -1
Detailed Description
Definition at line 30 of file Storage.h.
Constructor & Destructor Documentation
PX4Storage::PX4Storage (void)
Definition at line 34 of file Storage.cpp.
Member Function Documentation
uint8_t _buffer [PX4_STORAGE_SIZE] PX4::PX4Storage::__attribute__ ((aligned(4))) private
void PX4Storage::_mark_dirty (uint16_t loc, uint16_t length) private
Definition at line 73 of file Storage.cpp.
Referenced by write_block().
void PX4Storage::_mtd_load (void) private
Definition at line 198 of file Storage.cpp.
Referenced by _storage_open().
void PX4Storage::_mtd_write (uint16_t line) private
Definition at line 172 of file Storage.cpp.
Referenced by _timer_tick().
void PX4::PX4Storage::_storage_create (void) private
void PX4Storage::_storage_open (void) private
Definition at line 40 of file Storage.cpp.
Referenced by read_block(), and write_block().
void PX4Storage::_timer_tick (void)
Definition at line 104 of file Storage.cpp.
Referenced by init().
void PX4Storage::bus_lock (bool lock) private
Definition at line 148 of file Storage.cpp.
Referenced by _mtd_load(), and _mtd_write().
void PX4::PX4Storage::init (void) inline virtual
Implements AP_HAL::Storage.
Definition at line 34 of file Storage.h.
void PX4Storage::read_block (void * dst, uint16_t src, size_t n) virtual
Implements AP_HAL::Storage.
Definition at line 83 of file Storage.cpp.
Referenced by init().
void PX4Storage::write_block (uint16_t dst, const void * src, size_t n) virtual
Implements AP_HAL::Storage.
Definition at line 92 of file Storage.cpp.
Referenced by init().
Member Data Documentation
Bitmask PX4::PX4Storage::_dirty_mask {PX4_STORAGE_NUM_LINES} private
Definition at line 46 of file Storage.h.
Referenced by _mark_dirty(), _mtd_load(), _mtd_write(), _storage_open(), and _timer_tick().
int PX4::PX4Storage::_fd = -1 private
Definition at line 51 of file Storage.h.
Referenced by _mtd_write(), and _timer_tick().
volatile bool PX4::PX4Storage::_initialised private
Definition at line 41 of file Storage.h.
Referenced by _storage_open(), and _timer_tick().
perf_counter_t PX4::PX4Storage::_perf_errors private
Definition at line 48 of file Storage.h.
Referenced by _mtd_load(), _mtd_write(), and _timer_tick().
perf_counter_t PX4::PX4Storage::_perf_storage private
Definition at line 47 of file Storage.h.
Referenced by _timer_tick().
The documentation for this class was generated from the following files:
libraries/AP_HAL_PX4/Storage.h
libraries/AP_HAL_PX4/Storage.cpp