APM:Libraries: SRV_Channel Class Reference
SRV_Channel Class Reference
#include <SRV_Channel.h>
Public Types
enum Aux_servo_function_t {
k_none = 0, k_manual = 1, k_flap = 2, k_flap_auto = 3,
k_aileron = 4, k_unused1 = 5, k_mount_pan = 6, k_mount_tilt = 7,
k_mount_roll = 8, k_mount_open = 9, k_cam_trigger = 10, k_egg_drop = 11,
k_mount2_pan = 12, k_mount2_tilt = 13, k_mount2_roll = 14, k_mount2_open = 15,
k_dspoiler1 = 16, k_dspoiler2 = 17, k_aileron_with_input = 18, k_elevator = 19,
k_elevator_with_input = 20, k_rudder = 21, k_sprayer_pump = 22, k_sprayer_spinner = 23,
k_flaperon1 = 24, k_flaperon2 = 25, k_steering = 26, k_parachute_release = 27,
k_gripper = 28, k_landing_gear_control = 29, k_engine_run_enable = 30, k_heli_rsc = 31,
k_heli_tail_rsc = 32, k_motor1 = 33, k_motor2 = 34, k_motor3 = 35,
k_motor4 = 36, k_motor5 = 37, k_motor6 = 38, k_motor7 = 39,
k_motor8 = 40, k_motor_tilt = 41, k_rcin1 = 51, k_rcin2 = 52,
k_rcin3 = 53, k_rcin4 = 54, k_rcin5 = 55, k_rcin6 = 56,
k_rcin7 = 57, k_rcin8 = 58, k_rcin9 = 59, k_rcin10 = 60,
k_rcin11 = 61, k_rcin12 = 62, k_rcin13 = 63, k_rcin14 = 64,
k_rcin15 = 65, k_rcin16 = 66, k_ignition = 67, k_choke = 68,
k_starter = 69, k_throttle = 70, k_tracker_yaw = 71, k_tracker_pitch = 72,
k_throttleLeft = 73, k_throttleRight = 74, k_nr_aux_servo_functions
}
enum LimitValue { SRV_CHANNEL_LIMIT_TRIM, SRV_CHANNEL_LIMIT_MIN, SRV_CHANNEL_LIMIT_MAX, SRV_CHANNEL_LIMIT_ZERO_PWM }
Public Member Functions
SRV_Channel (void)
void set_output_pwm (uint16_t pwm)
uint16_t get_output_pwm (void) const
void set_angle (int16_t angle)
void set_range (uint16_t high)
bool get_reversed (void) const
void set_output_min (uint16_t pwm)
void set_output_max (uint16_t pwm)
uint16_t get_output_min (void) const
uint16_t get_output_max (void) const
uint16_t get_trim (void) const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Types
typedef uint16_t servo_mask_t
Private Member Functions
uint16_t pwm_from_range (int16_t scaled_value) const
uint16_t pwm_from_angle (int16_t scaled_value) const
void calc_pwm (int16_t output_scaled)
void output_ch (void)
map a function to a servo channel and output it
void aux_servo_function_setup (void)
uint16_t get_limit_pwm (LimitValue limit) const
float get_output_norm (void)
Private Attributes
AP_Int16 servo_min
AP_Int16 servo_max
AP_Int16 servo_trim
AP_Int8 reversed
AP_Int8 function
uint16_t output_pwm
bool type_angle:1
bool type_setup:1
uint8_t ch_num
uint16_t high_out
Static Private Attributes
static servo_mask_t have_pwm_mask
Friends
class SRV_Channels
Detailed Description
Definition at line 30 of file SRV_Channel.h.
Member Typedef Documentation
typedef uint16_t SRV_Channel::servo_mask_t private
Definition at line 198 of file SRV_Channel.h.
Member Enumeration Documentation
enum SRV_Channel::Aux_servo_function_t
Enumerator
k_none
disabled
k_manual
manual, just pass-thru the RC in signal
k_flap
flap
k_flap_auto
flap automated
k_aileron
aileron
k_unused1
unused function
k_mount_pan
mount yaw (pan)
k_mount_tilt
mount pitch (tilt)
k_mount_roll
mount roll
k_mount_open
mount open (deploy) / close (retract)
k_cam_trigger
camera trigger
k_egg_drop
egg drop
k_mount2_pan
mount2 yaw (pan)
k_mount2_tilt
mount2 pitch (tilt)
k_mount2_roll
mount2 roll
k_mount2_open
mount2 open (deploy) / close (retract)
k_dspoiler1
differential spoiler 1 (left wing)
k_dspoiler2
differential spoiler 2 (right wing)
k_aileron_with_input
aileron, with rc input
k_elevator
elevator
k_elevator_with_input
elevator, with rc input
k_rudder
secondary rudder channel
k_sprayer_pump
crop sprayer pump channel
k_sprayer_spinner
crop sprayer spinner channel
k_flaperon1
flaperon, left wing
k_flaperon2
flaperon, right wing
k_steering
ground steering, used to separate from rudder
k_parachute_release
parachute release
k_gripper
gripper
k_landing_gear_control
landing gear controller
k_engine_run_enable
engine kill switch, used for gas airplanes and helicopters
k_heli_rsc
helicopter RSC output
k_heli_tail_rsc
helicopter tail RSC output
k_motor1
these allow remapping of copter motors
k_motor2
k_motor3
k_motor4
k_motor5
k_motor6
k_motor7
k_motor8
k_motor_tilt
tiltrotor motor tilt control
k_rcin1
these are for pass-thru from arbitrary rc inputs
k_rcin2
k_rcin3
k_rcin4
k_rcin5
k_rcin6
k_rcin7
k_rcin8
k_rcin9
k_rcin10
k_rcin11
k_rcin12
k_rcin13
k_rcin14
k_rcin15
k_rcin16
k_ignition
k_choke
k_starter
k_throttle
k_tracker_yaw
antennatracker yaw
k_tracker_pitch
antennatracker pitch
k_throttleLeft
k_throttleRight
k_nr_aux_servo_functions
This must be the last enum value (only add new values before this one)
Definition at line 38 of file SRV_Channel.h.
enum SRV_Channel::LimitValue
Enumerator
SRV_CHANNEL_LIMIT_TRIM
SRV_CHANNEL_LIMIT_MIN
SRV_CHANNEL_LIMIT_MAX
SRV_CHANNEL_LIMIT_ZERO_PWM
Definition at line 110 of file SRV_Channel.h.
Constructor & Destructor Documentation
SRV_Channel::SRV_Channel (void)
Definition at line 76 of file SRV_Channel.cpp.
Member Function Documentation
void SRV_Channel::aux_servo_function_setup (void) private
Definition at line 83 of file SRV_Channel_aux.cpp.
void SRV_Channel::calc_pwm (int16_t output_scaled) private
Definition at line 115 of file SRV_Channel.cpp.
Referenced by SRV_Channels::calc_pwm(), SRV_Channels::disable_passthrough(), and SRV_Channels::limit_slew_rate().
uint16_t SRV_Channel::get_limit_pwm (LimitValue limit) const private
Definition at line 174 of file SRV_Channel.cpp.
Referenced by SRV_Channels::set_failsafe_limit(), SRV_Channels::set_output_limit(), and SRV_Channels::set_safety_limit().
uint16_t SRV_Channel::get_output_max (void) const inline
Definition at line 146 of file SRV_Channel.h.
Referenced by AP_Motors::calc_pwm_output_0to1(), AP_Motors::calc_pwm_output_1to1(), AP_MotorsTri::calc_yaw_radio_output(), SRV_Channels::limit_slew_rate(), SRV_Channels::set_esc_scaling_for(), and SRV_Channels::set_output_pwm_trimmed().
uint16_t SRV_Channel::get_output_min (void) const inline
Definition at line 143 of file SRV_Channel.h.
Referenced by AP_Motors::calc_pwm_output_0to1(), AP_Motors::calc_pwm_output_1to1(), AP_MotorsTri::calc_yaw_radio_output(), SRV_Channels::limit_slew_rate(), SRV_Channels::set_esc_scaling_for(), and SRV_Channels::set_output_pwm_trimmed().
float SRV_Channel::get_output_norm (void) private
Definition at line 154 of file SRV_Channel.cpp.
uint16_t SRV_Channel::get_output_pwm (void) const inline
Definition at line 121 of file SRV_Channel.h.
Referenced by GCS_MAVLINK::send_servo_output_raw(), and AP_Landing_Deepstall::verify_land().
bool SRV_Channel::get_reversed (void) const inline
Definition at line 130 of file SRV_Channel.h.
Referenced by AP_Motors::calc_pwm_output_0to1(), AP_Motors::calc_pwm_output_1to1(), AP_MotorsTri::calc_yaw_radio_output(), get_output_norm(), SRV_Channels::move_servo(), and SRV_Channels::set_trim_to_min_for().
uint16_t SRV_Channel::get_trim (void) const inline
Definition at line 149 of file SRV_Channel.h.
Referenced by AP_Motors::calc_pwm_output_1to1(), AP_MotorsTri::calc_yaw_radio_output(), AP_MotorsTri::output_to_motors(), and AP_ServoRelayEvents::update_events().
void SRV_Channel::output_ch (void) private
map a function to a servo channel and output it
Definition at line 28 of file SRV_Channel_aux.cpp.
uint16_t SRV_Channel::pwm_from_angle (int16_t scaled_value) const private
Definition at line 103 of file SRV_Channel.cpp.
Referenced by calc_pwm().
uint16_t SRV_Channel::pwm_from_range (int16_t scaled_value) const private
Definition at line 85 of file SRV_Channel.cpp.
Referenced by calc_pwm().
void SRV_Channel::set_angle (int16_t angle)
Definition at line 136 of file SRV_Channel.cpp.
Referenced by aux_servo_function_setup(), get_output_pwm(), AP_MotorsCoax::init(), AP_MotorsSingle::init(), AP_MotorsHeli_Single::init_outputs(), and SRV_Channels::set_reversible_throttle().
void SRV_Channel::set_output_max (uint16_t pwm) inline
Definition at line 138 of file SRV_Channel.h.
Referenced by AP_MotorsHeli::reset_swash_servo().
void SRV_Channel::set_output_min (uint16_t pwm) inline
Definition at line 135 of file SRV_Channel.h.
Referenced by AP_MotorsHeli::reset_swash_servo().
void SRV_Channel::set_output_pwm (uint16_t pwm)
Definition at line 129 of file SRV_Channel.cpp.
Referenced by calc_pwm(), AP_ServoRelayEvents::do_set_servo(), SRV_Channels::move_servo(), SRV_Channels::output_trim_all(), AP_Landing_Deepstall::override_servos(), SRV_Channels::set_output_limit(), and AP_ServoRelayEvents::update_events().
void SRV_Channel::set_range (uint16_t high)
Definition at line 144 of file SRV_Channel.cpp.
Referenced by aux_servo_function_setup(), get_output_pwm(), AP_MotorsHeli::reset_swash_servo(), and SRV_Channels::set_reversible_throttle().
Friends And Related Function Documentation
friend class SRV_Channels friend
Definition at line 32 of file SRV_Channel.h.
Member Data Documentation
uint8_t SRV_Channel::ch_num private
Definition at line 171 of file SRV_Channel.h.
Referenced by calc_pwm(), SRV_Channels::copy_radio_in_out(), SRV_Channels::enable_aux_servos(), SRV_Channels::limit_slew_rate(), output_ch(), SRV_Channels::set_failsafe_limit(), SRV_Channels::set_failsafe_pwm(), SRV_Channels::set_output_limit(), set_output_pwm(), SRV_Channels::set_safety_limit(), SRV_Channels::set_trim_to_radio_in_for(), and SRV_Channels::SRV_Channels().
AP_Int8 SRV_Channel::function private
Definition at line 159 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), SRV_Channels::constrain_pwm(), SRV_Channels::limit_slew_rate(), SRV_Channels::move_servo(), SRV_Channels::set_failsafe_limit(), SRV_Channels::set_failsafe_pwm(), SRV_Channels::set_output_limit(), SRV_Channels::set_safety_limit(), and SRV_Channels::upgrade_parameters().
SRV_Channel::servo_mask_t SRV_Channel::have_pwm_mask static private
Definition at line 202 of file SRV_Channel.h.
Referenced by calc_pwm(), set_output_pwm(), SRV_Channels::set_output_scaled(), and SRV_Channel().
uint16_t SRV_Channel::high_out private
Definition at line 174 of file SRV_Channel.h.
Referenced by pwm_from_angle(), pwm_from_range(), set_angle(), and set_range().
uint16_t SRV_Channel::output_pwm private
Definition at line 162 of file SRV_Channel.h.
Referenced by SRV_Channels::constrain_pwm(), get_output_norm(), get_output_pwm(), SRV_Channels::limit_slew_rate(), output_ch(), and set_output_pwm().
AP_Int8 SRV_Channel::reversed private
Definition at line 158 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), get_reversed(), pwm_from_angle(), pwm_from_range(), SRV_Channels::upgrade_motors_servo(), and SRV_Channels::upgrade_parameters().
AP_Int16 SRV_Channel::servo_max private
Definition at line 155 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), SRV_Channels::constrain_pwm(), get_limit_pwm(), get_output_max(), get_output_norm(), SRV_Channels::move_servo(), pwm_from_angle(), pwm_from_range(), set_output_max(), SRV_Channels::set_trim_to_min_for(), SRV_Channels::upgrade_motors_servo(), and SRV_Channels::upgrade_parameters().
AP_Int16 SRV_Channel::servo_min private
Definition at line 154 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), SRV_Channels::constrain_pwm(), get_limit_pwm(), get_output_min(), get_output_norm(), SRV_Channels::move_servo(), pwm_from_angle(), pwm_from_range(), set_output_min(), SRV_Channels::set_trim_to_min_for(), SRV_Channels::upgrade_motors_servo(), and SRV_Channels::upgrade_parameters().
AP_Int16 SRV_Channel::servo_trim private
Definition at line 156 of file SRV_Channel.h.
Referenced by SRV_Channels::adjust_trim(), get_limit_pwm(), get_trim(), pwm_from_angle(), SRV_Channels::save_trim(), SRV_Channels::set_output_to_trim(), SRV_Channels::upgrade_motors_servo(), and SRV_Channels::upgrade_parameters().
bool SRV_Channel::type_angle private
Definition at line 165 of file SRV_Channel.h.
Referenced by calc_pwm(), set_angle(), and set_range().
bool SRV_Channel::type_setup private
Definition at line 168 of file SRV_Channel.h.
Referenced by aux_servo_function_setup(), set_angle(), and set_range().
const AP_Param::GroupInfo SRV_Channel::var_info static
Definition at line 36 of file SRV_Channel.h.
Referenced by SRV_Channel().
The documentation for this class was generated from the following files:
libraries/SRV_Channel/SRV_Channel.h
libraries/SRV_Channel/SRV_Channel.cpp
libraries/SRV_Channel/SRV_Channel_aux.cpp