APM:Libraries: AP_HAL::UARTDriver Class Reference
AP_HAL::UARTDriver Class Reference abstract
#include <UARTDriver.h>
Public Types
enum flow_control { FLOW_CONTROL_DISABLE =0, FLOW_CONTROL_ENABLE =1, FLOW_CONTROL_AUTO =2 }
Public Member Functions
UARTDriver ()
virtual void begin (uint32_t baud)=0
virtual void begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace)=0
virtual void end ()=0
virtual void flush ()=0
virtual bool is_initialized ()=0
virtual void set_blocking_writes (bool blocking)=0
virtual bool tx_pending ()=0
virtual void set_flow_control (enum flow_control flow_control_setting)
virtual enum flow_control get_flow_control (void)
void printf (const char *s,...) FMT_PRINTF(2
void void vprintf (const char *s, va_list ap)
Public Member Functions inherited from AP_HAL::BetterStream
BetterStream (void)
Public Member Functions inherited from AP_HAL::Stream
virtual uint32_t available ()=0
virtual uint32_t txspace ()=0
virtual int16_t read ()=0
Public Member Functions inherited from AP_HAL::Print
Print ()
virtual size_t write (uint8_t)=0
virtual size_t write (const uint8_t *buffer, size_t size)=0
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Detailed Description
Definition at line 11 of file UARTDriver.h.
Member Enumeration Documentation
enum AP_HAL::UARTDriver::flow_control
Enumerator
FLOW_CONTROL_DISABLE
FLOW_CONTROL_ENABLE
FLOW_CONTROL_AUTO
Definition at line 42 of file UARTDriver.h.
Constructor & Destructor Documentation
AP_HAL::UARTDriver::UARTDriver () inline
Definition at line 13 of file UARTDriver.h.
Member Function Documentation
virtual void AP_HAL::UARTDriver::begin (uint32_t baud) pure virtual
Implemented in QURT::UARTDriver, HALSITL::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, and Empty::UARTDriver.
Referenced by AP_GPS_UBLOX::_parse_gps(), AP_Beacon_Pozyx::AP_Beacon_Pozyx(), AP_Proximity_LightWareSF40C::AP_Proximity_LightWareSF40C(), AP_Proximity_TeraRangerTower::AP_Proximity_TeraRangerTower(), AP_RangeFinder_LeddarOne::AP_RangeFinder_LeddarOne(), AP_RangeFinder_LightWareSerial::AP_RangeFinder_LightWareSerial(), AP_RangeFinder_MaxsonarSerialLV::AP_RangeFinder_MaxsonarSerialLV(), AP_RangeFinder_uLanding::AP_RangeFinder_uLanding(), AP_GPS::detect_instance(), GCS_MAVLINK::handle_serial_control(), main_loop(), HAL_Linux::run(), HAL_Empty::run(), HAL_SITL::run(), HAL_QURT::run(), setup(), setup_uart(), GCS_MAVLINK::setup_uart(), AP_Frsky_Telem::tick(), and UARTDriver().
virtual void AP_HAL::UARTDriver::begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace) pure virtual
Extended port open method
Allows for both opening with specified buffer sizes, and re-opening to adjust a subset of the port's settings.
Note
Buffer sizes greater than ::_max_buffer_size will be rounded down.
Parameters
baud Selects the speed that the port will be configured to. If zero, the port speed is left unchanged.
rxSpace Sets the receive buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_rx_buffer_size if it is currently closed.
txSpace Sets the transmit buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_tx_buffer_size if it is currently closed.
Implemented in QURT::UARTDriver, HALSITL::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, Linux::RPIOUARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, Linux::SPIUARTDriver, and Empty::UARTDriver.
virtual void AP_HAL::UARTDriver::end () pure virtual
Implemented in QURT::UARTDriver, HALSITL::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, and Empty::UARTDriver.
Referenced by UARTDriver().
virtual void AP_HAL::UARTDriver::flush () pure virtual
Implemented in QURT::UARTDriver, HALSITL::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, and Empty::UARTDriver.
Referenced by UARTDriver().
virtual enum flow_control AP_HAL::UARTDriver::get_flow_control (void) inline virtual
Reimplemented in HALSITL::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, and VRBRAIN::VRBRAINUARTDriver.
Definition at line 46 of file UARTDriver.h.
Referenced by GCS_MAVLINK::have_flow_control(), and GCS_MAVLINK::setup_uart().
virtual bool AP_HAL::UARTDriver::is_initialized () pure virtual
Implemented in QURT::UARTDriver, HALSITL::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, and Empty::UARTDriver.
Referenced by loop(), and UARTDriver().
void AP_HAL::UARTDriver::printf (const char * s, ...) virtual
Reimplemented from AP_HAL::BetterStream.
Definition at line 27 of file UARTDriver.cpp.
Referenced by AP_InertialSensor::_acal_save_calibrations(), Linux::CameraSensor_Mt9v117::_apply_patch(), AP_InertialSensor::_calculate_trim(), AP_Compass_LSM9DS1::_check_id(), Linux::CameraSensor_Mt9v117::_config_change(), AP_InertialSensor_BMI160::_configure_fifo(), AP_InertialSensor_BMI160::_configure_int1_pin(), AP_ADC_ADS1115::_convert_register_data_to_mv(), Linux::VideoIn::_dequeue_frame(), Compass::_detect_backends(), AP_Compass_LSM9DS1::_dump_registers(), AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_InertialSensor_BMI160::_init(), VRBRAIN::VRBRAINRCOutput::_init_alt_channels(), PX4::PX4RCOutput::_init_alt_channels(), AP_InertialSensor::_init_gyro(), AP_GPS_UBLOX::_parse_gps(), Linux::VideoIn::_queue_buffer(), AP_InertialSensor_LSM9DS0::_read_data_transaction_a(), AP_InertialSensor_LSM9DS0::_read_data_transaction_g(), AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_BMI160::_read_fifo(), Linux::CameraSensor_Mt9v117::_read_reg16(), Linux::CameraSensor_Mt9v117::_read_reg8(), AP_Compass_LSM303D::_read_sample(), Linux::Scheduler::_register_timesliced_proc(), AP_InertialSensor_Invensense::_set_filter_register(), QURT::Scheduler::_timer_thread(), VRBRAIN::VRBRAINScheduler::_timer_thread(), PX4::PX4Scheduler::_timer_thread(), Linux::RCInput_UDP::_timer_tick(), HALSITL::UARTDriver::_uart_start_connection(), PX4::PX4UARTDriver::_write_fd(), VRBRAIN::VRBRAINUARTDriver::_write_fd(), Linux::CameraSensor_Mt9v117::_write_reg16(), Linux::CameraSensor_Mt9v117::_write_reg32(), Linux::CameraSensor_Mt9v117::_write_reg8(), Linux::VideoIn::allocate_buffers(), AP_RangeFinder_PX4_PWM::AP_RangeFinder_PX4_PWM(), AP_RPM_PX4_PWM::AP_RPM_PX4_PWM(), Linux::SPIUARTDriver::begin(), PX4::PX4UARTDriver::begin(), VRBRAIN::VRBRAINUARTDriver::begin(), HALSITL::UARTDriver::begin(), Linux::Perf::begin(), AP_InertialSensor_UserInteract_MAVLink::blocking_read(), AnalogIn_ADS1115::channel(), AnalogIn_Raspilot::channel(), AnalogIn_Navio2::channel(), PX4::PX4AnalogIn::channel(), VRBRAIN::VRBRAINAnalogIn::channel(), check_result(), console_loopback(), AP_Param::convert_old_parameter(), Linux::Perf::count(), AP_RangeFinder_PX4_PWM::detect(), AP_InertialSensor::detect_backends(), AP_GPS::detect_instance(), display_offsets_and_scaling(), drive(), Linux::PWM_Sysfs_Base::enable(), Linux::Perf::end(), SchedTest::five_second_call(), get_flow_control(), Linux::PWM_Sysfs_Base::get_period(), Linux::PWM_Sysfs_Base::get_polarity(), MenuCommands::gpio_input_channel(), MenuCommands::gpio_output_channel(), Compass::handle_mag_cal_command(), handle_message(), GCS_MAVLINK::handle_preflight_reboot(), GCS_MAVLINK::handle_setup_signing(), AP_Compass_PX4::init(), PX4::PX4RCOutput::init(), VRBRAIN::VRBRAINRCOutput::init(), Linux::RCInput_UDP::init(), AP_IRLock_SITL::init(), VRBRAIN::VRBRAINGPIO::init(), ToneAlarm_Linux::init(), AP_Compass_LSM9DS1::init(), ToneAlarm_PX4::init(), ToneAlarm_PX4_Solo::init(), PX4::PX4GPIO::init(), OreoLED_PX4::init(), AP_Compass_BMM150::init(), AP_Compass_AK8963::init(), DataFlash_Class::Init(), AP_ADSB::init(), Linux::ToneAlarm::init(), AP_Avoidance::init(), MissionTest::init_mission(), MissionTest::init_mission_endless_loop(), MissionTest::init_mission_ends_with_do_commands(), MissionTest::init_mission_ends_with_jump_command(), MissionTest::init_mission_jump_to_nonnav(), MissionTest::init_mission_no_nav_commands(), MissionTest::init_mission_starts_with_do_commands(), inverse4x4(), Linux::PWM_Sysfs_Base::is_enabled(), AP_Param::load_object_from_eeprom(), GCS_MAVLINK::load_signing_key(), DataFlashTest_AllTypes::Log_Write_TypeMessages(), DataFlashTest_AllTypes::Log_Write_TypeMessages_Log_Write(), FlashTest::loop(), RC_UART::loop(), loop(), DataFlashTest::loop(), DataFlashTest_AllTypes::loop(), missing_rotations(), MissionTest::mission_complete(), motor_order_test(), SchedTest::one_hz_print(), Linux::VideoIn::open_device(), AP_Invensense_AuxiliaryBusSlave::passthrough_read(), AP_Invensense_AuxiliaryBusSlave::passthrough_write(), MissionTest::print_mission(), print_pwm(), print_radio_values(), print_vector(), AP_BoardConfig::px4_autodetect(), AP_BoardConfig::px4_setup_canbus(), AP_BoardConfig::px4_setup_pwm(), AP_BoardConfig::px4_setup_safety_mask(), AP_BoardConfig::px4_setup_sbus(), PX4::PX4RCInput::rc_bind(), AP_GPS_MTK19::read(), AP_Invensense_AuxiliaryBusSlave::read(), readTemp(), HALSITL::Scheduler::reboot(), QURT::Scheduler::register_io_process(), Linux::Scheduler::register_io_process(), VRBRAIN::VRBRAINScheduler::register_io_process(), PX4::PX4Scheduler::register_io_process(), QURT::Scheduler::register_timer_process(), Linux::Scheduler::register_timer_process(), VRBRAIN::VRBRAINScheduler::register_timer_process(), PX4::PX4Scheduler::register_timer_process(), PX4::PX4Util::run_debug_shell(), VRBRAIN::VRBRAINUtil::run_debug_shell(), MissionTest::run_max_cmd_test(), MissionTest::run_mission_test(), MissionTest::run_replace_cmd_test(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_test(), MissionTest::run_set_current_cmd_while_stopped_test(), run_test(), SoloGimbalEKF::RunEKF(), AP_Param::save(), SRV_Channels::set_aux_channel_default(), AnalogSource_Navio2::set_channel(), Linux::VideoIn::set_crop(), PX4::PX4RCOutput::set_failsafe_pwm(), VRBRAIN::VRBRAINRCOutput::set_failsafe_pwm(), Linux::VideoIn::set_format(), VRBRAIN::VRBRAINRCOutput::set_freq(), PX4::PX4RCOutput::set_freq(), VRBRAIN::VRBRAINRCOutput::set_freq_fd(), PX4::PX4RCOutput::set_freq_fd(), Linux::PWM_Sysfs_Base::set_period(), Linux::PWM_Sysfs_Base::set_polarity(), PX4::PX4RCOutput::set_safety_pwm(), VRBRAIN::VRBRAINRCOutput::set_safety_pwm(), MissionTest::setup(), FlashTest::setup(), RC_UART::setup(), setup(), DataFlashTest::setup(), DataFlashTest_AllTypes::setup(), HALSITL::Scheduler::sitl_end_atomic(), stability_test(), MissionTest::start_cmd(), PX4::NSHShellStream::start_shell(), VRBRAIN::NSHShellStream::start_shell(), test_accuracy(), test_conversion(), test_conversions(), test_euler(), test_eulers(), test_frame_transforms(), test_gpio_input(), test_gpio_output(), test_high_low_byte(), test_matrix_eulers(), test_matrix_inverse(), test_matrix_rotate(), test_one_offset(), test_passed_waypoint(), test_printf(), test_quaternion_eulers(), test_rotate_inverse(), test_rotation_accuracy(), test_uart(), test_wgs_conversion_functions(), test_wrap_cd(), Linux::SPIDevice::transfer(), Linux::SPIDevice::transfer_fullduplex(), AP_InertialSensor_LSM9DS0::update(), AP_OpticalFlow_Onboard::update(), SoloGimbal_Parameters::update(), MissionTest::verify_cmd(), and AP_InertialSensor::wait_for_sample().
virtual void AP_HAL::UARTDriver::set_blocking_writes (bool blocking) pure virtual
Implemented in HALSITL::UARTDriver, QURT::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, and Empty::UARTDriver.
Referenced by setup(), and UARTDriver().
virtual void AP_HAL::UARTDriver::set_flow_control (enum flow_control flow_control_setting) inline virtual
Reimplemented in Linux::UARTDriver.
Definition at line 45 of file UARTDriver.h.
Referenced by AP_GPS::detect_instance(), GCS_MAVLINK::handle_serial_control(), AP_Frsky_Telem::init(), AP_BoardConfig::px4_setup_uart(), and GCS_MAVLINK::setup_uart().
virtual bool AP_HAL::UARTDriver::tx_pending () pure virtual
Implemented in HALSITL::UARTDriver, QURT::UARTDriver, QURT::UDPDriver, Linux::UARTDriver, PX4::PX4UARTDriver, VRBRAIN::VRBRAINUARTDriver, and Empty::UARTDriver.
Referenced by UARTDriver().
void AP_HAL::UARTDriver::vprintf (const char * s, va_list ap) virtual
Implements AP_HAL::BetterStream.
Definition at line 35 of file UARTDriver.cpp.
Referenced by get_flow_control(), and printf().
The documentation for this class was generated from the following files:
libraries/AP_HAL/UARTDriver.h
libraries/AP_HAL/UARTDriver.cpp