APM:Libraries: AP_Gripper_Backend Class Reference
AP_Gripper_Backend Class Reference abstract
#include <AP_Gripper_Backend.h>
Public Member Functions
AP_Gripper_Backend (struct AP_Gripper::Backend_Config &_config)
void init ()
void update ()
virtual void grab ()=0
virtual void release ()=0
virtual bool valid () const
virtual bool released () const =0
virtual bool grabbed () const =0
virtual void init_gripper ()=0
virtual void update_gripper ()
Protected Attributes
struct AP_Gripper::Backend_Config & config
Detailed Description
Definition at line 20 of file AP_Gripper_Backend.h.
Constructor & Destructor Documentation
AP_Gripper_Backend::AP_Gripper_Backend (struct AP_Gripper::Backend_Config & _config) inline
Definition at line 22 of file AP_Gripper_Backend.h.
Member Function Documentation
virtual void AP_Gripper_Backend::grab () pure virtual
Implemented in AP_Gripper_EPM, and AP_Gripper_Servo.
Referenced by AP_Gripper_Backend().
virtual bool AP_Gripper_Backend::grabbed () const pure virtual
Implemented in AP_Gripper_EPM, and AP_Gripper_Servo.
Referenced by valid().
void AP_Gripper_Backend::init (void)
Definition at line 5 of file AP_Gripper_Backend.cpp.
Referenced by AP_Gripper_Backend(), and AP_Gripper::init().
virtual void AP_Gripper_Backend::init_gripper () pure virtual
Implemented in AP_Gripper_Servo, and AP_Gripper_EPM.
Referenced by init(), and valid().
virtual void AP_Gripper_Backend::release () pure virtual
Implemented in AP_Gripper_EPM, and AP_Gripper_Servo.
Referenced by AP_Gripper_Backend().
virtual bool AP_Gripper_Backend::released () const pure virtual
Implemented in AP_Gripper_EPM, and AP_Gripper_Servo.
Referenced by valid().
void AP_Gripper_Backend::update (void)
Definition at line 11 of file AP_Gripper_Backend.cpp.
Referenced by AP_Gripper_Backend().
virtual void AP_Gripper_Backend::update_gripper () inline virtual
Reimplemented in AP_Gripper_Servo, and AP_Gripper_EPM.
Definition at line 50 of file AP_Gripper_Backend.h.
Referenced by update().
virtual bool AP_Gripper_Backend::valid () const inline virtual
Reimplemented in AP_Gripper_Servo.
Definition at line 38 of file AP_Gripper_Backend.h.
Referenced by AP_Gripper_Servo::valid().
Member Data Documentation
struct AP_Gripper::Backend_Config& AP_Gripper_Backend::config protected
Definition at line 54 of file AP_Gripper_Backend.h.
Referenced by AP_Gripper_Servo::grab(), AP_Gripper_EPM::grab(), AP_Gripper_Servo::grabbed(), AP_Gripper_EPM::grabbed(), AP_Gripper_EPM::make_uavcan_command(), AP_Gripper_EPM::neutral(), AP_Gripper_Servo::release(), AP_Gripper_EPM::release(), AP_Gripper_Servo::released(), AP_Gripper_EPM::released(), and AP_Gripper_EPM::update_gripper().
The documentation for this class was generated from the following files:
libraries/AP_Gripper/AP_Gripper_Backend.h
libraries/AP_Gripper/AP_Gripper_Backend.cpp