APM:Libraries: AP_HAL::I2CDeviceManager Class Reference
AP_HAL::I2CDeviceManager Class Reference abstract
#include <I2CDevice.h>
Public Member Functions
virtual OwnPtr< AP_HAL::I2CDevice > get_device (uint8_t bus, uint8_t address)=0
Detailed Description
Definition at line 77 of file I2CDevice.h.
Member Function Documentation
virtual OwnPtr<AP_HAL::I2CDevice> AP_HAL::I2CDeviceManager::get_device (uint8_t bus, uint8_t address) pure virtual
Implemented in Linux::I2CDeviceManager, VRBRAIN::I2CDeviceManager, PX4::I2CDeviceManager, and Empty::I2CDeviceManager.
Referenced by Compass::_detect_backends(), AP_InertialSensor::detect_backends(), RangeFinder::detect_instance(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), NavioLED_I2C::hw_init(), ToshibaLED_I2C::hw_init(), AP_IRLock_I2C::init(), Display::init(), TSYS01::init(), AP_ADC_ADS1115::init(), AP_Baro::init(), AP_Airspeed_MS4525::init(), AP_Airspeed_MS5525::init(), Linux::OpticalFlow_Onboard::init(), AP_BattMonitor::init(), and AP_OpticalFlow_PX4Flow::scan_buses().
The documentation for this class was generated from the following file:
libraries/AP_HAL/I2CDevice.h