APM:Libraries: AP_InertialSensor_HIL Class Reference
AP_InertialSensor_HIL Class Reference
#include <AP_InertialSensor_HIL.h>
Public Member Functions
AP_InertialSensor_HIL (AP_InertialSensor &imu)
bool update ()
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
AP_InertialSensor_Backend (const AP_InertialSensor_Backend &that)=delete
virtual ~AP_InertialSensor_Backend (void)
virtual void accumulate ()
virtual void start ()
virtual AuxiliaryBus * get_auxiliary_bus ()
int16_t get_id () const
Static Public Member Functions
static AP_InertialSensor_Backend * detect (AP_InertialSensor &imu)
Private Member Functions
bool _init_sensor (void)
Additional Inherited Members
Public Types inherited from AP_InertialSensor_Backend
enum DevTypes {
DEVTYPE_BMI160 = 0x09, DEVTYPE_L3G4200D = 0x10, DEVTYPE_ACC_LSM303D = 0x11, DEVTYPE_ACC_BMA180 = 0x12,
DEVTYPE_ACC_MPU6000 = 0x13, DEVTYPE_ACC_MPU9250 = 0x16, DEVTYPE_GYR_MPU6000 = 0x21, DEVTYPE_GYR_L3GD20 = 0x22,
DEVTYPE_GYR_MPU9250 = 0x24
}
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_gyro (uint8_t instance, const Vector3f &gyro)
void _notify_new_gyro_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0)
void _publish_accel (uint8_t instance, const Vector3f &accel)
void _notify_new_accel_raw_sample (uint8_t instance, const Vector3f &accel, uint64_t sample_us=0, bool fsync_set=false)
void _set_accel_max_abs_offset (uint8_t instance, float offset)
uint32_t _accel_raw_sample_rate (uint8_t instance) const
uint32_t _gyro_raw_sample_rate (uint8_t instance) const
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
void _inc_accel_error_count (uint8_t instance)
void _inc_gyro_error_count (uint8_t instance)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
void update_gyro (uint8_t instance)
void update_accel (uint8_t instance)
void set_gyro_orientation (uint8_t instance, enum Rotation rotation)
void set_accel_orientation (uint8_t instance, enum Rotation rotation)
void increment_clip_count (uint8_t instance)
bool enable_fast_sampling (uint8_t instance)
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
AP_HAL::Semaphore * _sem
int16_t _id = -1
int8_t _last_accel_filter_hz [INS_MAX_INSTANCES]
int8_t _last_gyro_filter_hz [INS_MAX_INSTANCES]
Detailed Description
Definition at line 6 of file AP_InertialSensor_HIL.h.
Constructor & Destructor Documentation
AP_InertialSensor_HIL::AP_InertialSensor_HIL (AP_InertialSensor & imu)
Definition at line 6 of file AP_InertialSensor_HIL.cpp.
Referenced by detect().
Member Function Documentation
bool AP_InertialSensor_HIL::_init_sensor (void) private
Definition at line 27 of file AP_InertialSensor_HIL.cpp.
Referenced by detect().
AP_InertialSensor_Backend * AP_InertialSensor_HIL::detect (AP_InertialSensor & imu) static
Definition at line 14 of file AP_InertialSensor_HIL.cpp.
Referenced by AP_InertialSensor::detect_backends().
bool AP_InertialSensor_HIL::update (void) virtual
Implements AP_InertialSensor_Backend.
Definition at line 38 of file AP_InertialSensor_HIL.cpp.
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_HIL.h
libraries/AP_InertialSensor/AP_InertialSensor_HIL.cpp