APM:Libraries: VRBRAIN::I2CDevice Class Reference
VRBRAIN::I2CDevice Class Reference
#include <I2CDevice.h>
Public Member Functions
I2CDevice (uint8_t bus, uint8_t address)
~I2CDevice ()
void set_address (uint8_t address) override
void set_retries (uint8_t retries) override
bool set_speed (enum Device::Speed speed) override
bool transfer (const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len) override
bool read_registers_multiple (uint8_t first_reg, uint8_t *recv, uint32_t recv_len, uint8_t times) override
AP_HAL::Device::PeriodicHandle register_periodic_callback (uint32_t period_usec, AP_HAL::Device::PeriodicCb) override
bool adjust_periodic_callback (AP_HAL::Device::PeriodicHandle h, uint32_t period_usec) override
AP_HAL::Semaphore * get_semaphore () override
Public Member Functions inherited from AP_HAL::I2CDevice
I2CDevice ()
virtual bool set_speed (Device::Speed speed) override=0
virtual Device::PeriodicHandle register_periodic_callback (uint32_t period_usec, Device::PeriodicCb) override=0
virtual void set_split_transfers (bool set)
Public Member Functions inherited from AP_HAL::Device
FUNCTOR_TYPEDEF (PeriodicCb, void)
Device (enum BusType type)
enum BusType bus_type (void) const
uint8_t bus_num (void) const
uint32_t get_bus_id (void) const
uint8_t get_bus_address (void) const
void set_device_type (uint8_t devtype)
virtual ~Device ()
bool read_registers (uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_register (uint8_t reg, uint8_t val, bool checked=false)
void set_checked_register (uint8_t reg, uint8_t val)
bool setup_checked_registers (uint8_t num_regs, uint8_t frequency=10)
bool check_next_register (void)
bool read (uint8_t *recv, uint32_t recv_len)
virtual PeriodicHandle register_periodic_callback (uint32_t period_usec, PeriodicCb)=0
virtual bool unregister_callback (PeriodicHandle h)
virtual bool set_chip_select (bool set)
void set_read_flag (uint8_t flag)
uint32_t get_bus_id_devtype (uint8_t devtype)
Static Public Member Functions
static I2CDevice * from (AP_HAL::I2CDevice *dev)
Static Public Member Functions inherited from AP_HAL::Device
static uint32_t make_bus_id (enum BusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype)
static uint32_t change_bus_id (uint32_t old_id, uint8_t devtype)
Private Attributes
Empty::Semaphore semaphore
VRBRAIN_I2C _bus
uint8_t _address
uint8_t _retries = 0
Additional Inherited Members
Public Types inherited from AP_HAL::Device
enum BusType { BUS_TYPE_UNKNOWN = 0, BUS_TYPE_I2C = 1, BUS_TYPE_SPI = 2, BUS_TYPE_UAVCAN = 3 }
enum Speed { SPEED_HIGH, SPEED_LOW }
typedef void * PeriodicHandle
Protected Member Functions inherited from AP_HAL::Device
void set_device_address (uint8_t address)
void set_device_bus (uint8_t bus)
Protected Attributes inherited from AP_HAL::Device
uint8_t _read_flag = 0
union DeviceId _bus_id
Detailed Description
Definition at line 30 of file I2CDevice.h.
Constructor & Destructor Documentation
VRBRAIN::I2CDevice::I2CDevice (uint8_t bus, uint8_t address)
Definition at line 48 of file I2CDevice.cpp.
VRBRAIN::I2CDevice::~I2CDevice () virtual
Reimplemented from AP_HAL::I2CDevice.
Definition at line 54 of file I2CDevice.cpp.
Referenced by from().
Member Function Documentation
bool VRBRAIN::I2CDevice::adjust_periodic_callback (AP_HAL::Device::PeriodicHandle h, uint32_t period_usec) inline override virtual
Implements AP_HAL::I2CDevice.
Definition at line 65 of file I2CDevice.h.
static I2CDevice* VRBRAIN::I2CDevice::from (AP_HAL::I2CDevice * dev) inline static
Definition at line 32 of file I2CDevice.h.
AP_HAL::Semaphore* VRBRAIN::I2CDevice::get_semaphore () inline override virtual
Implements AP_HAL::I2CDevice.
Definition at line 71 of file I2CDevice.h.
bool VRBRAIN::I2CDevice::read_registers_multiple (uint8_t first_reg, uint8_t * recv, uint32_t recv_len, uint8_t times) override virtual
Implements AP_HAL::I2CDevice.
Definition at line 64 of file I2CDevice.cpp.
Referenced by set_speed().
AP_HAL::Device::PeriodicHandle VRBRAIN::I2CDevice::register_periodic_callback (uint32_t period_usec, AP_HAL::Device::PeriodicCb) inline override
Definition at line 57 of file I2CDevice.h.
void VRBRAIN::I2CDevice::set_address (uint8_t address) inline override virtual
Implements AP_HAL::I2CDevice.
Definition at line 41 of file I2CDevice.h.
void VRBRAIN::I2CDevice::set_retries (uint8_t retries) inline override virtual
Reimplemented from AP_HAL::Device.
Definition at line 44 of file I2CDevice.h.
bool VRBRAIN::I2CDevice::set_speed (enum Device::Speed speed) inline override
Definition at line 47 of file I2CDevice.h.
bool VRBRAIN::I2CDevice::transfer (const uint8_t * send, uint32_t send_len, uint8_t * recv, uint32_t recv_len) override virtual
Implements AP_HAL::I2CDevice.
Definition at line 58 of file I2CDevice.cpp.
Referenced by set_speed().
Member Data Documentation
uint8_t VRBRAIN::I2CDevice::_address private
Definition at line 77 of file I2CDevice.h.
Referenced by set_address(), and transfer().
VRBRAIN_I2C VRBRAIN::I2CDevice::_bus private
Definition at line 76 of file I2CDevice.h.
Referenced by transfer().
uint8_t VRBRAIN::I2CDevice::_retries = 0 private
Definition at line 78 of file I2CDevice.h.
Referenced by set_retries().
Empty::Semaphore VRBRAIN::I2CDevice::semaphore private
Definition at line 75 of file I2CDevice.h.
Referenced by get_semaphore().
The documentation for this class was generated from the following files:
libraries/AP_HAL_VRBRAIN/I2CDevice.h
libraries/AP_HAL_VRBRAIN/I2CDevice.cpp