APM:Libraries: FilterWithBuffer< T, FILTER_SIZE > Class Template Reference
FilterWithBuffer< T, FILTER_SIZE > Class Template Reference
#include <FilterWithBuffer.h>
Public Member Functions
FilterWithBuffer ()
virtual T apply (T sample)
virtual void reset ()
uint8_t get_filter_size () const
T get_sample (uint8_t i) const
Protected Attributes
T samples [FILTER_SIZE]
uint8_t sample_index
Detailed Description
template<class T, uint8_t FILTER_SIZE>
class FilterWithBuffer< T, FILTER_SIZE >
Definition at line 27 of file FilterWithBuffer.h.
Constructor & Destructor Documentation
template<class T , uint8_t FILTER_SIZE> FilterWithBuffer< T, FILTER_SIZE >::FilterWithBuffer ()
Definition at line 82 of file FilterWithBuffer.h.
Member Function Documentation
template<class T, uint8_t FILTER_SIZE> T FilterWithBuffer< T, FILTER_SIZE >::apply (T sample) virtual
Implements Filter< T >.
Reimplemented in AverageIntegralFilter< T, U, FILTER_SIZE >, AverageIntegralFilter< int32_t, int32_t, 10 >, AverageFilter< T, U, FILTER_SIZE >, AverageFilter< float, float, 5 >, AverageFilter< int32_t, int32_t, FILTER_SIZE >, ModeFilter< T, FILTER_SIZE >, and ModeFilter< float, 5 >.
Definition at line 104 of file FilterWithBuffer.h.
Referenced by AverageFilter< T, U, FILTER_SIZE >::apply(), AverageIntegralFilter< T, U, FILTER_SIZE >::apply(), and DerivativeFilter< T, FILTER_SIZE >::update().
template<class T, uint8_t FILTER_SIZE> uint8_t FilterWithBuffer< T, FILTER_SIZE >::get_filter_size () const inline
Definition at line 40 of file FilterWithBuffer.h.
template<class T, uint8_t FILTER_SIZE> T FilterWithBuffer< T, FILTER_SIZE >::get_sample (uint8_t i) const inline
Definition at line 44 of file FilterWithBuffer.h.
template<class T , uint8_t FILTER_SIZE> void FilterWithBuffer< T, FILTER_SIZE >::reset (void) virtual
Implements Filter< T >.
Reimplemented in DerivativeFilter< T, FILTER_SIZE >, DerivativeFilter< float, 7 >, AverageFilter< T, U, FILTER_SIZE >, AverageFilter< float, float, 5 >, and AverageFilter< int32_t, int32_t, FILTER_SIZE >.
Definition at line 91 of file FilterWithBuffer.h.
Referenced by FilterWithBuffer< T, FILTER_SIZE >::FilterWithBuffer(), AverageFilter< T, U, FILTER_SIZE >::reset(), and DerivativeFilter< T, FILTER_SIZE >::reset().
Member Data Documentation
template<class T, uint8_t FILTER_SIZE> uint8_t FilterWithBuffer< T, FILTER_SIZE >::sample_index protected
Definition at line 50 of file FilterWithBuffer.h.
Referenced by FilterWithBuffer< T, FILTER_SIZE >::apply(), AverageIntegralFilter< T, U, FILTER_SIZE >::apply(), and FilterWithBuffer< T, FILTER_SIZE >::reset().
template<class T, uint8_t FILTER_SIZE> T FilterWithBuffer< T, FILTER_SIZE >::samples[FILTER_SIZE] protected
Definition at line 49 of file FilterWithBuffer.h.
Referenced by FilterWithBuffer< T, FILTER_SIZE >::apply(), AverageIntegralFilter< T, U, FILTER_SIZE >::apply(), FilterWithBuffer< float, FILTER_SIZE >::get_sample(), and FilterWithBuffer< T, FILTER_SIZE >::reset().
The documentation for this class was generated from the following file:
libraries/Filter/FilterWithBuffer.h