APM:Libraries: HALSITL::GPIO Class Reference
HALSITL::GPIO Class Reference
#include <GPIO.h>
Public Member Functions
GPIO (SITL_State *sitlState)
void init ()
void pinMode (uint8_t pin, uint8_t output)
int8_t analogPinToDigitalPin (uint8_t pin)
uint8_t read (uint8_t pin)
void write (uint8_t pin, uint8_t value)
void toggle (uint8_t pin)
AP_HAL::DigitalSource * channel (uint16_t n)
bool attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode)
bool usb_connected (void)
Public Member Functions inherited from AP_HAL::GPIO
GPIO ()
virtual void pinMode (uint8_t pin, uint8_t output, uint8_t alt)
Private Attributes
SITL_State * _sitlState
Detailed Description
Definition at line 5 of file GPIO.h.
Constructor & Destructor Documentation
HALSITL::GPIO::GPIO (SITL_State * sitlState) inline explicit
Definition at line 7 of file GPIO.h.
Member Function Documentation
int8_t GPIO::analogPinToDigitalPin (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 14 of file GPIO.cpp.
Referenced by GPIO().
bool GPIO::attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode) virtual
Implements AP_HAL::GPIO.
Definition at line 61 of file GPIO.cpp.
Referenced by GPIO().
AP_HAL::DigitalSource * GPIO::channel (uint16_t n) virtual
Implements AP_HAL::GPIO.
Definition at line 51 of file GPIO.cpp.
Referenced by GPIO().
void GPIO::init (void) virtual
Implements AP_HAL::GPIO.
Definition at line 8 of file GPIO.cpp.
Referenced by GPIO().
void GPIO::pinMode (uint8_t pin, uint8_t output) virtual
Implements AP_HAL::GPIO.
Definition at line 11 of file GPIO.cpp.
Referenced by GPIO().
uint8_t GPIO::read (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 19 of file GPIO.cpp.
Referenced by GPIO(), and toggle().
void GPIO::toggle (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 45 of file GPIO.cpp.
Referenced by GPIO().
bool GPIO::usb_connected (void) virtual
Implements AP_HAL::GPIO.
Definition at line 66 of file GPIO.cpp.
Referenced by GPIO().
void GPIO::write (uint8_t pin, uint8_t value) virtual
Implements AP_HAL::GPIO.
Definition at line 28 of file GPIO.cpp.
Referenced by GPIO(), and toggle().
Member Data Documentation
SITL_State* HALSITL::GPIO::_sitlState private
Definition at line 26 of file GPIO.h.
Referenced by read(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/GPIO.h
libraries/AP_HAL_SITL/GPIO.cpp