APM:Libraries: AP_RangeFinder_trone Class Reference
AP_RangeFinder_trone Class Reference
#include <AP_RangeFinder_trone.h>
Public Member Functions
void update (void)
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder &_ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state)
virtual ~AP_RangeFinder_Backend (void)
bool out_of_range (void) const
virtual void handle_msg (mavlink_message_t *msg)
Static Public Member Functions
static AP_RangeFinder_Backend * detect (uint8_t bus, RangeFinder &ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state)
Private Member Functions
AP_RangeFinder_trone (uint8_t bus, RangeFinder &ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state)
bool measure (void)
bool collect (uint16_t &distance_cm)
bool init (void)
void timer (void)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev
struct {
uint32_t sum
uint32_t count
} accum
Additional Inherited Members
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status ()
void set_status (RangeFinder::RangeFinder_Status status)
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder & ranger
RangeFinder::RangeFinder_State & state
AP_HAL::Semaphore * _sem
Detailed Description
Definition at line 7 of file AP_RangeFinder_trone.h.
Constructor & Destructor Documentation
AP_RangeFinder_trone::AP_RangeFinder_trone (uint8_t bus, RangeFinder & ranger, uint8_t instance, RangeFinder::RangeFinder_State & _state) private
Definition at line 38 of file AP_RangeFinder_trone.cpp.
Referenced by detect().
Member Function Documentation
bool AP_RangeFinder_trone::collect (uint16_t & distance_cm) private
Definition at line 115 of file AP_RangeFinder_trone.cpp.
Referenced by init(), and timer().
AP_RangeFinder_Backend * AP_RangeFinder_trone::detect (uint8_t bus, RangeFinder & ranger, uint8_t instance, RangeFinder::RangeFinder_State & _state) static
Definition at line 49 of file AP_RangeFinder_trone.cpp.
Referenced by RangeFinder::detect_instance().
bool AP_RangeFinder_trone::init (void) private
Definition at line 68 of file AP_RangeFinder_trone.cpp.
Referenced by detect().
bool AP_RangeFinder_trone::measure (void) private
Definition at line 108 of file AP_RangeFinder_trone.cpp.
Referenced by init(), and timer().
void AP_RangeFinder_trone::timer (void) private
Definition at line 137 of file AP_RangeFinder_trone.cpp.
Referenced by init().
void AP_RangeFinder_trone::update (void) virtual
Implements AP_RangeFinder_Backend.
Definition at line 155 of file AP_RangeFinder_trone.cpp.
Member Data Documentation
struct { ... } AP_RangeFinder_trone::accum
Referenced by timer(), and update().
uint32_t AP_RangeFinder_trone::count
Definition at line 31 of file AP_RangeFinder_trone.h.
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_RangeFinder_trone::dev private
Definition at line 27 of file AP_RangeFinder_trone.h.
Referenced by collect(), init(), and measure().
uint32_t AP_RangeFinder_trone::sum
Definition at line 30 of file AP_RangeFinder_trone.h.
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_trone.h
libraries/AP_RangeFinder/AP_RangeFinder_trone.cpp