APM:Libraries: AP_Frsky_Telem Class Reference
AP_Frsky_Telem Class Reference
#include <AP_Frsky_Telem.h>
Public Member Functions
AP_Frsky_Telem (AP_AHRS &ahrs, const AP_BattMonitor &battery, const RangeFinder &rng)
void init (const AP_SerialManager &serial_manager, const char *firmware_str, const uint8_t mav_type, const AP_Float *fs_batt_voltage=nullptr, const AP_Float *fs_batt_mah=nullptr, const uint32_t *ap_valuep=nullptr)
void queue_message (MAV_SEVERITY severity, const char *text)
void update_control_mode (uint8_t mode)
void set_is_flying (bool is_flying)
void update_sensor_status_flags (uint32_t error_mask)
Static Public Attributes
static ObjectArray< mavlink_statustext_t > _statustext_queue
Private Member Functions
void send_SPort_Passthrough (void)
void send_SPort (void)
void send_D (void)
void tick (void)
void calc_crc (uint8_t byte)
void send_crc (void)
void send_byte (uint8_t value)
void send_uint32 (uint16_t id, uint32_t data)
void send_uint16 (uint16_t id, uint16_t data)
bool get_next_msg_chunk (void)
void check_sensor_status_flags (void)
void check_ekf_status (void)
uint32_t calc_param (void)
uint32_t calc_gps_latlng (bool *send_latitude)
uint32_t calc_gps_status (void)
uint32_t calc_batt (void)
uint32_t calc_ap_status (void)
uint32_t calc_home (void)
uint32_t calc_velandyaw (void)
uint32_t calc_attiandrng (void)
uint16_t prep_number (int32_t number, uint8_t digits, uint8_t power)
void calc_nav_alt (void)
float format_gps (float dec)
void calc_gps_position (void)
Private Attributes
AP_AHRS & _ahrs
const AP_BattMonitor & _battery
const RangeFinder & _rng
AP_HAL::UARTDriver * _port
AP_SerialManager::SerialProtocol _protocol
bool _initialised_uart
uint16_t _crc
struct {
uint8_t mav_type
const AP_Float * fs_batt_voltage
const AP_Float * fs_batt_mah
} _params
struct {
uint8_t control_mode
uint32_t value
const uint32_t * valuep
uint32_t sensor_status_flags
} _ap
uint32_t check_sensor_status_timer
uint32_t check_ekf_status_timer
uint8_t _paramID
struct {
char lat_ns
char lon_ew
uint16_t latdddmm
uint16_t latmmmm
uint16_t londddmm
uint16_t lonmmmm
uint16_t alt_gps_meters
uint16_t alt_gps_cm
uint16_t alt_nav_meters
uint16_t alt_nav_cm
int16_t speed_in_meter
uint16_t speed_in_centimeter
} _gps
struct {
uint8_t new_byte
bool send_attiandrng
bool send_latitude
uint32_t params_timer
uint32_t ap_status_timer
uint32_t batt_timer
uint32_t gps_status_timer
uint32_t home_timer
uint32_t velandyaw_timer
uint32_t gps_latlng_timer
} _passthrough
struct {
bool sport_status
uint8_t fas_call
uint8_t gps_call
uint8_t vario_call
uint8_t various_call
} _SPort
struct {
uint32_t last_200ms_frame
uint32_t last_1000ms_frame
} _D
struct {
uint32_t chunk
uint8_t repeats
uint8_t char_index
} _msg_chunk
Detailed Description
Definition at line 111 of file AP_Frsky_Telem.h.
Constructor & Destructor Documentation
AP_Frsky_Telem::AP_Frsky_Telem (AP_AHRS & ahrs, const AP_BattMonitor & battery, const RangeFinder & rng)
Definition at line 30 of file AP_Frsky_Telem.cpp.
Member Function Documentation
uint32_t AP_Frsky_Telem::calc_ap_status (void) private
Definition at line 669 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
uint32_t AP_Frsky_Telem::calc_attiandrng (void) private
Definition at line 747 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
uint32_t AP_Frsky_Telem::calc_batt (void) private
Definition at line 652 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
void AP_Frsky_Telem::calc_crc (uint8_t byte) private
Definition at line 337 of file AP_Frsky_Telem.cpp.
Referenced by send_byte().
uint32_t AP_Frsky_Telem::calc_gps_latlng (bool * send_latitude) private
Definition at line 602 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
void AP_Frsky_Telem::calc_gps_position (void) private
Definition at line 859 of file AP_Frsky_Telem.cpp.
Referenced by send_D(), and send_SPort().
uint32_t AP_Frsky_Telem::calc_gps_status (void) private
Definition at line 630 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
uint32_t AP_Frsky_Telem::calc_home (void) private
Definition at line 692 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
void AP_Frsky_Telem::calc_nav_alt (void) private
Definition at line 829 of file AP_Frsky_Telem.cpp.
Referenced by send_D(), and send_SPort().
uint32_t AP_Frsky_Telem::calc_param (void) private
Definition at line 565 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
uint32_t AP_Frsky_Telem::calc_velandyaw (void) private
Definition at line 722 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
void AP_Frsky_Telem::check_ekf_status (void) private
Definition at line 527 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
void AP_Frsky_Telem::check_sensor_status_flags (void) private
Definition at line 477 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
float AP_Frsky_Telem::format_gps (float dec) private
Definition at line 849 of file AP_Frsky_Telem.cpp.
Referenced by calc_gps_position().
bool AP_Frsky_Telem::get_next_msg_chunk (void) private
Definition at line 418 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort_Passthrough().
void AP_Frsky_Telem::init (const AP_SerialManager & serial_manager, const char * firmware_str, const uint8_t mav_type, const AP_Float * fs_batt_voltage = nullptr, const AP_Float * fs_batt_mah = nullptr, const uint32_t * ap_valuep = nullptr)
Definition at line 39 of file AP_Frsky_Telem.cpp.
uint16_t AP_Frsky_Telem::prep_number (int32_t number, uint8_t digits, uint8_t power) private
Definition at line 764 of file AP_Frsky_Telem.cpp.
Referenced by calc_attiandrng(), calc_batt(), calc_gps_status(), calc_home(), and calc_velandyaw().
void AP_Frsky_Telem::queue_message (MAV_SEVERITY severity, const char * text)
Definition at line 460 of file AP_Frsky_Telem.cpp.
Referenced by check_ekf_status(), check_sensor_status_flags(), init(), and GCS::send_statustext().
void AP_Frsky_Telem::send_byte (uint8_t value) private
Definition at line 358 of file AP_Frsky_Telem.cpp.
Referenced by send_crc(), send_uint16(), and send_uint32().
void AP_Frsky_Telem::send_crc (void) private
Definition at line 348 of file AP_Frsky_Telem.cpp.
Referenced by send_uint32().
void AP_Frsky_Telem::send_D (void) private
Definition at line 273 of file AP_Frsky_Telem.cpp.
Referenced by tick().
void AP_Frsky_Telem::send_SPort (void) private
Definition at line 162 of file AP_Frsky_Telem.cpp.
Referenced by tick().
void AP_Frsky_Telem::send_SPort_Passthrough (void) private
Definition at line 76 of file AP_Frsky_Telem.cpp.
Referenced by tick().
void AP_Frsky_Telem::send_uint16 (uint16_t id, uint16_t data) private
Definition at line 404 of file AP_Frsky_Telem.cpp.
Referenced by send_D().
void AP_Frsky_Telem::send_uint32 (uint16_t id, uint32_t data) private
Definition at line 387 of file AP_Frsky_Telem.cpp.
Referenced by send_SPort(), and send_SPort_Passthrough().
void AP_Frsky_Telem::set_is_flying (bool is_flying) inline
Definition at line 129 of file AP_Frsky_Telem.h.
void AP_Frsky_Telem::tick (void) private
Definition at line 311 of file AP_Frsky_Telem.cpp.
Referenced by init().
void AP_Frsky_Telem::update_control_mode (uint8_t mode) inline
Definition at line 124 of file AP_Frsky_Telem.h.
void AP_Frsky_Telem::update_sensor_status_flags (uint32_t error_mask) inline
Definition at line 135 of file AP_Frsky_Telem.h.
Member Data Documentation
AP_AHRS& AP_Frsky_Telem::_ahrs private
Definition at line 140 of file AP_Frsky_Telem.h.
Referenced by calc_attiandrng(), calc_gps_latlng(), calc_gps_position(), calc_gps_status(), calc_home(), calc_nav_alt(), calc_velandyaw(), check_ekf_status(), send_D(), and send_SPort().
struct { ... } AP_Frsky_Telem::_ap
Referenced by calc_ap_status(), check_sensor_status_flags(), init(), send_D(), send_SPort(), send_SPort_Passthrough(), set_is_flying(), update_control_mode(), and update_sensor_status_flags().
const AP_BattMonitor& AP_Frsky_Telem::_battery private
Definition at line 141 of file AP_Frsky_Telem.h.
Referenced by calc_batt(), calc_param(), send_D(), and send_SPort().
uint16_t AP_Frsky_Telem::_crc private
Definition at line 146 of file AP_Frsky_Telem.h.
Referenced by calc_crc(), and send_crc().
struct { ... } AP_Frsky_Telem::_D
Referenced by send_D().
struct { ... } AP_Frsky_Telem::_gps
Referenced by calc_gps_position(), calc_nav_alt(), send_D(), and send_SPort().
bool AP_Frsky_Telem::_initialised_uart private
Definition at line 145 of file AP_Frsky_Telem.h.
Referenced by tick().
struct { ... } AP_Frsky_Telem::_msg_chunk
Referenced by get_next_msg_chunk(), and send_SPort_Passthrough().
uint8_t AP_Frsky_Telem::_paramID private
Definition at line 165 of file AP_Frsky_Telem.h.
Referenced by calc_param().
struct { ... } AP_Frsky_Telem::_params
Referenced by calc_param(), and init().
struct { ... } AP_Frsky_Telem::_passthrough
Referenced by send_SPort_Passthrough().
AP_HAL::UARTDriver* AP_Frsky_Telem::_port private
Definition at line 143 of file AP_Frsky_Telem.h.
Referenced by init(), send_byte(), send_SPort(), send_SPort_Passthrough(), send_uint16(), and tick().
AP_SerialManager::SerialProtocol AP_Frsky_Telem::_protocol private
Definition at line 144 of file AP_Frsky_Telem.h.
Referenced by init(), send_byte(), and tick().
const RangeFinder& AP_Frsky_Telem::_rng private
Definition at line 142 of file AP_Frsky_Telem.h.
Referenced by calc_attiandrng().
struct { ... } AP_Frsky_Telem::_SPort
Referenced by send_SPort().
ObjectArray< mavlink_statustext_t > AP_Frsky_Telem::_statustext_queue static
Definition at line 137 of file AP_Frsky_Telem.h.
Referenced by get_next_msg_chunk(), and queue_message().
uint16_t AP_Frsky_Telem::alt_gps_cm
Definition at line 175 of file AP_Frsky_Telem.h.
uint16_t AP_Frsky_Telem::alt_gps_meters
Definition at line 174 of file AP_Frsky_Telem.h.
uint16_t AP_Frsky_Telem::alt_nav_cm
Definition at line 177 of file AP_Frsky_Telem.h.
uint16_t AP_Frsky_Telem::alt_nav_meters
Definition at line 176 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::ap_status_timer
Definition at line 188 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::batt_timer
Definition at line 189 of file AP_Frsky_Telem.h.
uint8_t AP_Frsky_Telem::char_index
Definition at line 215 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::check_ekf_status_timer private
Definition at line 164 of file AP_Frsky_Telem.h.
Referenced by check_ekf_status().
uint32_t AP_Frsky_Telem::check_sensor_status_timer private
Definition at line 163 of file AP_Frsky_Telem.h.
Referenced by check_sensor_status_flags().
uint32_t AP_Frsky_Telem::chunk
Definition at line 213 of file AP_Frsky_Telem.h.
uint8_t AP_Frsky_Telem::control_mode
Definition at line 157 of file AP_Frsky_Telem.h.
uint8_t AP_Frsky_Telem::fas_call
Definition at line 199 of file AP_Frsky_Telem.h.
const AP_Float* AP_Frsky_Telem::fs_batt_mah
Definition at line 152 of file AP_Frsky_Telem.h.
Referenced by init().
const AP_Float* AP_Frsky_Telem::fs_batt_voltage
Definition at line 151 of file AP_Frsky_Telem.h.
Referenced by init().
uint8_t AP_Frsky_Telem::gps_call
Definition at line 200 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::gps_latlng_timer
Definition at line 193 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::gps_status_timer
Definition at line 190 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::home_timer
Definition at line 191 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::last_1000ms_frame
Definition at line 208 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::last_200ms_frame
Definition at line 207 of file AP_Frsky_Telem.h.
char AP_Frsky_Telem::lat_ns
Definition at line 169 of file AP_Frsky_Telem.h.
uint16_t AP_Frsky_Telem::latdddmm
Definition at line 170 of file AP_Frsky_Telem.h.
uint16_t AP_Frsky_Telem::latmmmm
Definition at line 171 of file AP_Frsky_Telem.h.
char AP_Frsky_Telem::lon_ew
Definition at line 169 of file AP_Frsky_Telem.h.
uint16_t AP_Frsky_Telem::londddmm
Definition at line 172 of file AP_Frsky_Telem.h.
uint16_t AP_Frsky_Telem::lonmmmm
Definition at line 173 of file AP_Frsky_Telem.h.
uint8_t AP_Frsky_Telem::mav_type
Definition at line 150 of file AP_Frsky_Telem.h.
Referenced by init().
uint8_t AP_Frsky_Telem::new_byte
Definition at line 184 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::params_timer
Definition at line 187 of file AP_Frsky_Telem.h.
uint8_t AP_Frsky_Telem::repeats
Definition at line 214 of file AP_Frsky_Telem.h.
bool AP_Frsky_Telem::send_attiandrng
Definition at line 185 of file AP_Frsky_Telem.h.
bool AP_Frsky_Telem::send_latitude
Definition at line 186 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::sensor_status_flags
Definition at line 160 of file AP_Frsky_Telem.h.
uint16_t AP_Frsky_Telem::speed_in_centimeter
Definition at line 179 of file AP_Frsky_Telem.h.
int16_t AP_Frsky_Telem::speed_in_meter
Definition at line 178 of file AP_Frsky_Telem.h.
bool AP_Frsky_Telem::sport_status
Definition at line 198 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::value
Definition at line 158 of file AP_Frsky_Telem.h.
const uint32_t* AP_Frsky_Telem::valuep
Definition at line 159 of file AP_Frsky_Telem.h.
uint8_t AP_Frsky_Telem::vario_call
Definition at line 201 of file AP_Frsky_Telem.h.
uint8_t AP_Frsky_Telem::various_call
Definition at line 202 of file AP_Frsky_Telem.h.
uint32_t AP_Frsky_Telem::velandyaw_timer
Definition at line 192 of file AP_Frsky_Telem.h.
The documentation for this class was generated from the following files:
libraries/AP_Frsky_Telem/AP_Frsky_Telem.h
libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp