APM:Libraries: QURT::RCOutput Class Reference
QURT::RCOutput Class Reference
#include <RCOutput.h>
Public Member Functions
RCOutput (const char *_device_path)
void set_device_path (const char *path)
void init ()
void set_freq (uint32_t chmask, uint16_t freq_hz)
uint16_t get_freq (uint8_t ch)
void enable_ch (uint8_t ch)
void disable_ch (uint8_t ch)
void write (uint8_t ch, uint16_t period_us)
uint16_t read (uint8_t ch)
void read (uint16_t *period_us, uint8_t len)
void cork (void) override
void push (void) override
void timer_update (void)
Public Member Functions inherited from AP_HAL::RCOutput
virtual uint16_t read_last_sent (uint8_t ch)
virtual void read_last_sent (uint16_t *period_us, uint8_t len)
virtual void set_safety_pwm (uint32_t chmask, uint16_t period_us)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
virtual void force_safety_no_wait (void)
virtual void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
virtual float scale_esc_to_unity (uint16_t pwm)
virtual bool enable_sbus_out (uint16_t rate_gz)
virtual void timer_tick (void)
virtual void set_output_mode (enum output_mode mode)
Private Attributes
const char * device_path
const uint32_t baudrate = 115200
int fd = -1
uint16_t enable_mask
uint16_t period [channel_count]
volatile bool need_write
bool corked
Static Private Attributes
static const uint8_t channel_count = 4
Additional Inherited Members
Public Types inherited from AP_HAL::RCOutput
enum output_mode { MODE_PWM_NORMAL, MODE_PWM_ONESHOT, MODE_PWM_BRUSHED16KHZ }
Detailed Description
Definition at line 8 of file RCOutput.h.
Constructor & Destructor Documentation
QURT::RCOutput::RCOutput (const char * _device_path) inline
Definition at line 11 of file RCOutput.h.
Member Function Documentation
void RCOutput::cork (void) override virtual
Implements AP_HAL::RCOutput.
Definition at line 112 of file RCOutput.cpp.
Referenced by set_device_path().
void RCOutput::disable_ch (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 39 of file RCOutput.cpp.
Referenced by set_device_path().
void RCOutput::enable_ch (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 31 of file RCOutput.cpp.
Referenced by set_device_path().
uint16_t RCOutput::get_freq (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 25 of file RCOutput.cpp.
Referenced by set_device_path().
void RCOutput::init (void) virtual
Implements AP_HAL::RCOutput.
Definition at line 16 of file RCOutput.cpp.
Referenced by set_device_path().
void RCOutput::push (void) override virtual
Implements AP_HAL::RCOutput.
Definition at line 117 of file RCOutput.cpp.
Referenced by set_device_path().
uint16_t RCOutput::read (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 58 of file RCOutput.cpp.
Referenced by read(), and set_device_path().
void RCOutput::read (uint16_t * period_us, uint8_t len) virtual
Implements AP_HAL::RCOutput.
Definition at line 66 of file RCOutput.cpp.
void QURT::RCOutput::set_device_path (const char * path) inline
Definition at line 15 of file RCOutput.h.
Referenced by HAL_QURT::run().
void RCOutput::set_freq (uint32_t chmask, uint16_t freq_hz) virtual
Implements AP_HAL::RCOutput.
Definition at line 20 of file RCOutput.cpp.
Referenced by set_device_path().
void RCOutput::timer_update (void)
Definition at line 78 of file RCOutput.cpp.
Referenced by set_device_path().
void RCOutput::write (uint8_t ch, uint16_t period_us) virtual
Implements AP_HAL::RCOutput.
Definition at line 47 of file RCOutput.cpp.
Referenced by set_device_path(), and timer_update().
Member Data Documentation
const uint32_t QURT::RCOutput::baudrate = 115200 private
Definition at line 34 of file RCOutput.h.
const uint8_t QURT::RCOutput::channel_count = 4 static private
Definition at line 35 of file RCOutput.h.
Referenced by disable_ch(), enable_ch(), read(), timer_update(), and write().
bool QURT::RCOutput::corked private
Definition at line 41 of file RCOutput.h.
Referenced by cork(), push(), and write().
const char* QURT::RCOutput::device_path private
Definition at line 33 of file RCOutput.h.
Referenced by RCOutput(), set_device_path(), and timer_update().
uint16_t QURT::RCOutput::enable_mask private
Definition at line 38 of file RCOutput.h.
Referenced by disable_ch(), and enable_ch().
int QURT::RCOutput::fd = -1 private
Definition at line 37 of file RCOutput.h.
Referenced by timer_update().
volatile bool QURT::RCOutput::need_write private
Definition at line 40 of file RCOutput.h.
Referenced by push(), timer_update(), and write().
uint16_t QURT::RCOutput::period[channel_count] private
Definition at line 39 of file RCOutput.h.
Referenced by read(), timer_update(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_QURT/RCOutput.h
libraries/AP_HAL_QURT/RCOutput.cpp