APM:Libraries: AP_Gripper_Servo Class Reference
AP_Gripper_Servo Class Reference
#include <AP_Gripper_Servo.h>
Public Member Functions
AP_Gripper_Servo (struct AP_Gripper::Backend_Config &_config)
void grab () override
void release () override
bool grabbed () const override
bool released () const override
bool valid () const
Public Member Functions inherited from AP_Gripper_Backend
AP_Gripper_Backend (struct AP_Gripper::Backend_Config &_config)
void init ()
void update ()
Protected Member Functions
void init_gripper () override
void update_gripper () override
Private Member Functions
bool has_state_pwm (const uint16_t pwm) const
Private Attributes
uint32_t action_timestamp
const uint16_t action_time = 3000
Additional Inherited Members
Protected Attributes inherited from AP_Gripper_Backend
struct AP_Gripper::Backend_Config & config
Detailed Description
Definition at line 21 of file AP_Gripper_Servo.h.
Constructor & Destructor Documentation
AP_Gripper_Servo::AP_Gripper_Servo (struct AP_Gripper::Backend_Config & _config) inline
Definition at line 24 of file AP_Gripper_Servo.h.
Member Function Documentation
void AP_Gripper_Servo::grab () override virtual
Implements AP_Gripper_Backend.
Definition at line 11 of file AP_Gripper_Servo.cpp.
Referenced by AP_Gripper_Servo().
bool AP_Gripper_Servo::grabbed () const override virtual
Implements AP_Gripper_Backend.
Definition at line 51 of file AP_Gripper_Servo.cpp.
Referenced by AP_Gripper_Servo().
bool AP_Gripper_Servo::has_state_pwm (const uint16_t pwm) const private
Definition at line 25 of file AP_Gripper_Servo.cpp.
Referenced by grabbed(), and released().
void AP_Gripper_Servo::init_gripper () override protected virtual
Implements AP_Gripper_Backend.
Definition at line 5 of file AP_Gripper_Servo.cpp.
Referenced by AP_Gripper_Servo().
void AP_Gripper_Servo::release () override virtual
Implements AP_Gripper_Backend.
Definition at line 18 of file AP_Gripper_Servo.cpp.
Referenced by AP_Gripper_Servo(), and init_gripper().
bool AP_Gripper_Servo::released () const override virtual
Implements AP_Gripper_Backend.
Definition at line 46 of file AP_Gripper_Servo.cpp.
Referenced by AP_Gripper_Servo().
void AP_Gripper_Servo::update_gripper () override protected virtual
Reimplemented from AP_Gripper_Backend.
Definition at line 57 of file AP_Gripper_Servo.cpp.
Referenced by AP_Gripper_Servo().
bool AP_Gripper_Servo::valid () const virtual
Reimplemented from AP_Gripper_Backend.
Definition at line 59 of file AP_Gripper_Servo.cpp.
Referenced by AP_Gripper_Servo().
Member Data Documentation
const uint16_t AP_Gripper_Servo::action_time = 3000 private
Definition at line 53 of file AP_Gripper_Servo.h.
Referenced by has_state_pwm().
uint32_t AP_Gripper_Servo::action_timestamp private
Definition at line 52 of file AP_Gripper_Servo.h.
Referenced by grab(), has_state_pwm(), and release().
The documentation for this class was generated from the following files:
libraries/AP_Gripper/AP_Gripper_Servo.h
libraries/AP_Gripper/AP_Gripper_Servo.cpp