APM:Libraries: IRLock Class Reference
IRLock Class Reference abstract
#include <IRLock.h>
Classes
struct AP_IRLock_Flags
struct irlock_target_info
Public Member Functions
virtual void init ()=0
bool healthy () const
uint32_t last_update_ms () const
size_t num_targets () const
virtual bool update ()=0
bool get_angle_to_target_rad (float &x_angle_rad, float &y_angle_rad) const
bool get_unit_vector_body (Vector3f &ret) const
Protected Attributes
struct IRLock::AP_IRLock_Flags _flags
uint32_t _last_update_ms
irlock_target_info _target_info
Detailed Description
Definition at line 26 of file IRLock.h.
Member Function Documentation
bool IRLock::get_angle_to_target_rad (float & x_angle_rad, float & y_angle_rad) const
Definition at line 12 of file IRLock.cpp.
Referenced by num_targets().
bool IRLock::get_unit_vector_body (Vector3f & ret) const
Definition at line 27 of file IRLock.cpp.
Referenced by num_targets(), AC_PrecLand_SITL_Gazebo::update(), and AC_PrecLand_IRLock::update().
bool IRLock::healthy (void) const inline
Definition at line 34 of file IRLock.h.
Referenced by AC_PrecLand_SITL_Gazebo::update(), and AC_PrecLand_IRLock::update().
virtual void IRLock::init () pure virtual
Implemented in AP_IRLock_SITL, and AP_IRLock_I2C.
uint32_t IRLock::last_update_ms (void) const inline
Definition at line 37 of file IRLock.h.
Referenced by AC_PrecLand_SITL_Gazebo::update(), and AC_PrecLand_IRLock::update().
size_t IRLock::num_targets () const inline
Definition at line 40 of file IRLock.h.
Referenced by AC_PrecLand_SITL_Gazebo::update(), and AC_PrecLand_IRLock::update().
virtual bool IRLock::update () pure virtual
Implemented in AP_IRLock_SITL, and AP_IRLock_I2C.
Referenced by num_targets().
Member Data Documentation
struct IRLock::AP_IRLock_Flags IRLock::_flags protected
Referenced by get_angle_to_target_rad(), get_unit_vector_body(), healthy(), AP_IRLock_SITL::init(), num_targets(), AP_IRLock_I2C::update(), and AP_IRLock_SITL::update().
uint32_t IRLock::_last_update_ms protected
Definition at line 60 of file IRLock.h.
Referenced by last_update_ms(), AP_IRLock_I2C::update(), and AP_IRLock_SITL::update().
irlock_target_info IRLock::_target_info protected
Definition at line 71 of file IRLock.h.
Referenced by get_angle_to_target_rad(), get_unit_vector_body(), AP_IRLock_I2C::read_frames(), AP_IRLock_I2C::update(), and AP_IRLock_SITL::update().
The documentation for this class was generated from the following files:
libraries/AP_IRLock/IRLock.h
libraries/AP_IRLock/IRLock.cpp