APM:Libraries: AP_IRLock_I2C Class Reference
AP_IRLock_I2C Class Reference
#include <AP_IRLock_I2C.h>
Classes
struct frame
Public Member Functions
void init ()
bool update ()
Public Member Functions inherited from IRLock
bool healthy () const
uint32_t last_update_ms () const
size_t num_targets () const
bool get_angle_to_target_rad (float &x_angle_rad, float &y_angle_rad) const
bool get_unit_vector_body (Vector3f &ret) const
Private Member Functions
bool timer (void)
bool sync_frame_start (void)
bool read_block (struct frame &irframe)
void read_frames (void)
void pixel_to_1M_plane (float pix_x, float pix_y, float &ret_x, float &ret_y)
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > dev
AP_HAL::Semaphore * sem
uint32_t _last_read_ms
Additional Inherited Members
Protected Attributes inherited from IRLock
struct IRLock::AP_IRLock_Flags _flags
uint32_t _last_update_ms
irlock_target_info _target_info
Detailed Description
Definition at line 9 of file AP_IRLock_I2C.h.
Member Function Documentation
void AP_IRLock_I2C::init (void) virtual
Implements IRLock.
Definition at line 35 of file AP_IRLock_I2C.cpp.
Referenced by AC_PrecLand_IRLock::init().
void AP_IRLock_I2C::pixel_to_1M_plane (float pix_x, float pix_y, float & ret_x, float & ret_y) private
Definition at line 82 of file AP_IRLock_I2C.cpp.
Referenced by read_frames().
bool AP_IRLock_I2C::read_block (struct frame & irframe) private
Definition at line 93 of file AP_IRLock_I2C.cpp.
Referenced by read_frames().
void AP_IRLock_I2C::read_frames (void) private
Definition at line 111 of file AP_IRLock_I2C.cpp.
Referenced by init().
bool AP_IRLock_I2C::sync_frame_start (void) private
Definition at line 54 of file AP_IRLock_I2C.cpp.
Referenced by read_frames().
bool AP_IRLock_I2C::timer (void) private
bool AP_IRLock_I2C::update (void) virtual
Implements IRLock.
Definition at line 154 of file AP_IRLock_I2C.cpp.
Referenced by AC_PrecLand_IRLock::update().
Member Data Documentation
uint32_t AP_IRLock_I2C::_last_read_ms private
Definition at line 39 of file AP_IRLock_I2C.h.
Referenced by read_block(), sync_frame_start(), and update().
AP_HAL::OwnPtr<AP_HAL::Device> AP_IRLock_I2C::dev private
Definition at line 19 of file AP_IRLock_I2C.h.
Referenced by init(), read_block(), sync_frame_start(), and update().
AP_HAL::Semaphore* AP_IRLock_I2C::sem private
Definition at line 38 of file AP_IRLock_I2C.h.
Referenced by init(), read_frames(), and update().
The documentation for this class was generated from the following files:
libraries/AP_IRLock/AP_IRLock_I2C.h
libraries/AP_IRLock/AP_IRLock_I2C.cpp