APM:Libraries: AP_Compass_LSM9DS1 Class Reference
AP_Compass_LSM9DS1 Class Reference
#include <AP_Compass_LSM9DS1.h>
Public Member Functions
void read () override
virtual ~AP_Compass_LSM9DS1 ()
Public Member Functions inherited from AP_Compass_Backend
AP_Compass_Backend (Compass &compass)
virtual ~AP_Compass_Backend (void)
virtual void accumulate (void)
virtual void handle_mag_msg (Vector3f &mag)
Static Public Member Functions
static AP_Compass_Backend * probe (Compass &compass, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation=ROTATION_NONE)
Static Public Attributes
static constexpr const char * name = "LSM9DS1"
Private Member Functions
AP_Compass_LSM9DS1 (Compass &compass, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation=ROTATION_NONE)
bool init ()
bool _check_id (void)
bool _configure (void)
bool _set_scale (void)
void _update (void)
uint8_t _register_read (uint8_t reg)
void _register_write (uint8_t reg, uint8_t val)
void _register_modify (uint8_t reg, uint8_t clearbits, uint8_t setbits)
bool _block_read (uint8_t reg, uint8_t *buf, uint32_t size)
void _dump_registers ()
Private Attributes
AP_HAL::OwnPtr< AP_HAL::Device > _dev
uint8_t _compass_instance
float _scaling
float _mag_x_accum
float _mag_y_accum
float _mag_z_accum
uint32_t _accum_count
enum Rotation _rotation
Additional Inherited Members
Public Types inherited from AP_Compass_Backend
enum DevTypes {
DEVTYPE_HMC5883_OLD = 0x01, DEVTYPE_HMC5883 = 0x07, DEVTYPE_LSM303D = 0x02, DEVTYPE_AK8963 = 0x04,
DEVTYPE_BMM150 = 0x05, DEVTYPE_LSM9DS1 = 0x06, DEVTYPE_LIS3MDL = 0x08, DEVTYPE_AK09916 = 0x09,
DEVTYPE_IST8310 = 0x0A
}
Protected Member Functions inherited from AP_Compass_Backend
void rotate_field (Vector3f &mag, uint8_t instance)
void publish_raw_field (const Vector3f &mag, uint32_t time_us, uint8_t instance)
void correct_field (Vector3f &mag, uint8_t i)
void publish_filtered_field (const Vector3f &mag, uint8_t instance)
void set_last_update_usec (uint32_t last_update, uint8_t instance)
uint8_t register_compass (void) const
void set_dev_id (uint8_t instance, uint32_t dev_id)
void set_external (uint8_t instance, bool external)
bool is_external (uint8_t instance)
void set_rotation (uint8_t instance, enum Rotation rotation)
Protected Attributes inherited from AP_Compass_Backend
Compass & _compass
AP_HAL::Semaphore * _sem
Detailed Description
Definition at line 11 of file AP_Compass_LSM9DS1.h.
Constructor & Destructor Documentation
virtual AP_Compass_LSM9DS1::~AP_Compass_LSM9DS1 () inline virtual
Definition at line 22 of file AP_Compass_LSM9DS1.h.
AP_Compass_LSM9DS1::AP_Compass_LSM9DS1 (Compass & compass, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation = ROTATION_NONE) private
Definition at line 60 of file AP_Compass_LSM9DS1.cpp.
Referenced by probe(), and ~AP_Compass_LSM9DS1().
Member Function Documentation
bool AP_Compass_LSM9DS1::_block_read (uint8_t reg, uint8_t * buf, uint32_t size) private
Definition at line 254 of file AP_Compass_LSM9DS1.cpp.
Referenced by _update(), and ~AP_Compass_LSM9DS1().
bool AP_Compass_LSM9DS1::_check_id (void) private
Definition at line 207 of file AP_Compass_LSM9DS1.cpp.
Referenced by init(), and ~AP_Compass_LSM9DS1().
bool AP_Compass_LSM9DS1::_configure (void) private
Definition at line 223 of file AP_Compass_LSM9DS1.cpp.
Referenced by init(), and ~AP_Compass_LSM9DS1().
void AP_Compass_LSM9DS1::_dump_registers () private
Definition at line 127 of file AP_Compass_LSM9DS1.cpp.
Referenced by ~AP_Compass_LSM9DS1().
void AP_Compass_LSM9DS1::_register_modify (uint8_t reg, uint8_t clearbits, uint8_t setbits) private
Definition at line 266 of file AP_Compass_LSM9DS1.cpp.
Referenced by _set_scale(), and ~AP_Compass_LSM9DS1().
uint8_t AP_Compass_LSM9DS1::_register_read (uint8_t reg) private
Definition at line 243 of file AP_Compass_LSM9DS1.cpp.
Referenced by _check_id(), _dump_registers(), _register_modify(), and ~AP_Compass_LSM9DS1().
void AP_Compass_LSM9DS1::_register_write (uint8_t reg, uint8_t val) private
Definition at line 261 of file AP_Compass_LSM9DS1.cpp.
Referenced by _configure(), _register_modify(), and ~AP_Compass_LSM9DS1().
bool AP_Compass_LSM9DS1::_set_scale (void) private
Definition at line 234 of file AP_Compass_LSM9DS1.cpp.
Referenced by init(), and ~AP_Compass_LSM9DS1().
void AP_Compass_LSM9DS1::_update (void) private
Definition at line 140 of file AP_Compass_LSM9DS1.cpp.
Referenced by init(), and ~AP_Compass_LSM9DS1().
bool AP_Compass_LSM9DS1::init (void) private
Definition at line 85 of file AP_Compass_LSM9DS1.cpp.
Referenced by probe(), and ~AP_Compass_LSM9DS1().
AP_Compass_Backend * AP_Compass_LSM9DS1::probe (Compass & compass, AP_HAL::OwnPtr< AP_HAL::Device > dev, enum Rotation rotation = ROTATION_NONE) static
Definition at line 69 of file AP_Compass_LSM9DS1.cpp.
Referenced by Compass::_detect_backends().
void AP_Compass_LSM9DS1::read (void) override virtual
Implements AP_Compass_Backend.
Definition at line 186 of file AP_Compass_LSM9DS1.cpp.
Member Data Documentation
uint32_t AP_Compass_LSM9DS1::_accum_count private
Definition at line 45 of file AP_Compass_LSM9DS1.h.
Referenced by _update(), and read().
uint8_t AP_Compass_LSM9DS1::_compass_instance private
Definition at line 40 of file AP_Compass_LSM9DS1.h.
Referenced by _update(), init(), and read().
AP_HAL::OwnPtr<AP_HAL::Device> AP_Compass_LSM9DS1::_dev private
Definition at line 39 of file AP_Compass_LSM9DS1.h.
Referenced by _block_read(), _check_id(), _register_read(), _register_write(), and init().
float AP_Compass_LSM9DS1::_mag_x_accum private
Definition at line 42 of file AP_Compass_LSM9DS1.h.
Referenced by _update(), and read().
float AP_Compass_LSM9DS1::_mag_y_accum private
Definition at line 43 of file AP_Compass_LSM9DS1.h.
Referenced by _update(), and read().
float AP_Compass_LSM9DS1::_mag_z_accum private
Definition at line 44 of file AP_Compass_LSM9DS1.h.
Referenced by _update(), and read().
enum Rotation AP_Compass_LSM9DS1::_rotation private
Definition at line 46 of file AP_Compass_LSM9DS1.h.
Referenced by init().
float AP_Compass_LSM9DS1::_scaling private
Definition at line 41 of file AP_Compass_LSM9DS1.h.
Referenced by _set_scale(), and _update().
constexpr const char* AP_Compass_LSM9DS1::name = "LSM9DS1" static
Definition at line 18 of file AP_Compass_LSM9DS1.h.
Referenced by Compass::_detect_backends().
The documentation for this class was generated from the following files:
libraries/AP_Compass/AP_Compass_LSM9DS1.h
libraries/AP_Compass/AP_Compass_LSM9DS1.cpp