APM:Libraries: AP_GPS_NOVA Class Reference
AP_GPS_NOVA Class Reference
#include <AP_GPS_NOVA.h>
Classes
struct bestpos
struct bestvel
union msgbuffer
union msgheader
struct nova_header
struct nova_msg_parser
struct psrdop
Public Member Functions
AP_GPS_NOVA (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
AP_GPS::GPS_Status highest_supported_status (void)
bool read ()
void inject_data (const uint8_t *data, uint16_t len) override
Public Member Functions inherited from AP_GPS_Backend
AP_GPS_Backend (AP_GPS &_gps, AP_GPS::GPS_State &_state, AP_HAL::UARTDriver *_port)
virtual ~AP_GPS_Backend (void)
virtual bool is_configured (void)
virtual void send_mavlink_gps_rtk (mavlink_channel_t chan)
virtual void send_mavlink_gps2_rtk (mavlink_channel_t chan)
virtual void broadcast_configuration_failure_reason (void) const
virtual void handle_msg (const mavlink_message_t *msg)
virtual void handle_gnss_msg (const AP_GPS::GPS_State &msg)
virtual float get_lag (void) const
Private Member Functions
bool parse (uint8_t temp)
bool process_message ()
uint32_t CRC32Value (uint32_t icrc)
uint32_t CalculateBlockCRC32 (uint32_t length, uint8_t *buffer, uint32_t crc)
Private Attributes
bool _new_position:1
bool _new_speed:1
uint32_t _last_vel_time
uint8_t _init_blob_index = 0
uint32_t _init_blob_time = 0
const char * _initialisation_blob [6]
uint32_t crc_error_counter = 0
uint32_t last_injected_data_ms = 0
struct PACKED AP_GPS_NOVA::nova_msg_parser nova_msg
Static Private Attributes
static const uint8_t NOVA_PREAMBLE1 = 0xaa
static const uint8_t NOVA_PREAMBLE2 = 0x44
static const uint8_t NOVA_PREAMBLE3 = 0x12
Additional Inherited Members
Protected Member Functions inherited from AP_GPS_Backend
int32_t swap_int32 (int32_t v) const
int16_t swap_int16 (int16_t v) const
void fill_3d_velocity (void)
void make_gps_time (uint32_t bcd_date, uint32_t bcd_milliseconds)
Protected Attributes inherited from AP_GPS_Backend
AP_HAL::UARTDriver * port
UART we are attached to.
AP_GPS & gps
access to frontend (for parameters)
AP_GPS::GPS_State & state
public state for this instance
Detailed Description
Definition at line 25 of file AP_GPS_NOVA.h.
Constructor & Destructor Documentation
AP_GPS_NOVA::AP_GPS_NOVA (AP_GPS & _gps, AP_GPS::GPS_State & _state, AP_HAL::UARTDriver * _port)
Definition at line 41 of file AP_GPS_NOVA.cpp.
Member Function Documentation
uint32_t AP_GPS_NOVA::CalculateBlockCRC32 (uint32_t length, uint8_t * buffer, uint32_t crc) private
Definition at line 308 of file AP_GPS_NOVA.cpp.
Referenced by highest_supported_status(), and parse().
uint32_t AP_GPS_NOVA::CRC32Value (uint32_t icrc) private
Definition at line 294 of file AP_GPS_NOVA.cpp.
Referenced by CalculateBlockCRC32(), and highest_supported_status().
AP_GPS::GPS_Status AP_GPS_NOVA::highest_supported_status (void) inline virtual
Reimplemented from AP_GPS_Backend.
Definition at line 30 of file AP_GPS_NOVA.h.
void AP_GPS_NOVA::inject_data (const uint8_t * data, uint16_t len) override virtual
Reimplemented from AP_GPS_Backend.
Definition at line 283 of file AP_GPS_NOVA.cpp.
Referenced by highest_supported_status().
bool AP_GPS_NOVA::parse (uint8_t temp) private
Definition at line 83 of file AP_GPS_NOVA.cpp.
Referenced by highest_supported_status(), and read().
bool AP_GPS_NOVA::process_message (void) private
Definition at line 185 of file AP_GPS_NOVA.cpp.
Referenced by highest_supported_status(), and parse().
bool AP_GPS_NOVA::read (void) virtual
Implements AP_GPS_Backend.
Definition at line 59 of file AP_GPS_NOVA.cpp.
Referenced by highest_supported_status().
Member Data Documentation
uint8_t AP_GPS_NOVA::_init_blob_index = 0 private
Definition at line 55 of file AP_GPS_NOVA.h.
Referenced by read().
uint32_t AP_GPS_NOVA::_init_blob_time = 0 private
Definition at line 56 of file AP_GPS_NOVA.h.
Referenced by read().
const char* AP_GPS_NOVA::_initialisation_blob[6] private
Initial value:
= {
        "\r\n\r\nunlogall\r\n",
        "log bestposb ontime 0.2 0 nohold\r\n",
        "log bestvelb ontime 0.2 0 nohold\r\n",
        "log psrdopb onchanged\r\n",
        "log psrdopb ontime 0.2\r\n",
        "log psrdopb\r\n"
    }
Definition at line 57 of file AP_GPS_NOVA.h.
Referenced by AP_GPS_NOVA(), and read().
uint32_t AP_GPS_NOVA::_last_vel_time private
Definition at line 53 of file AP_GPS_NOVA.h.
Referenced by process_message().
bool AP_GPS_NOVA::_new_position private
Definition at line 49 of file AP_GPS_NOVA.h.
Referenced by process_message().
bool AP_GPS_NOVA::_new_speed private
Definition at line 51 of file AP_GPS_NOVA.h.
Referenced by process_message().
uint32_t AP_GPS_NOVA::crc_error_counter = 0 private
Definition at line 66 of file AP_GPS_NOVA.h.
Referenced by parse().
uint32_t AP_GPS_NOVA::last_injected_data_ms = 0 private
Definition at line 67 of file AP_GPS_NOVA.h.
Referenced by inject_data().
struct PACKED AP_GPS_NOVA::nova_msg_parser AP_GPS_NOVA::nova_msg private
Referenced by AP_GPS_NOVA(), parse(), and process_message().
const uint8_t AP_GPS_NOVA::NOVA_PREAMBLE1 = 0xaa static private
Definition at line 44 of file AP_GPS_NOVA.h.
Referenced by parse().
const uint8_t AP_GPS_NOVA::NOVA_PREAMBLE2 = 0x44 static private
Definition at line 45 of file AP_GPS_NOVA.h.
Referenced by parse().
const uint8_t AP_GPS_NOVA::NOVA_PREAMBLE3 = 0x12 static private
Definition at line 46 of file AP_GPS_NOVA.h.
Referenced by parse().
The documentation for this class was generated from the following files:
libraries/AP_GPS/AP_GPS_NOVA.h
libraries/AP_GPS/AP_GPS_NOVA.cpp