APM:Libraries: AP_HAL::DigitalSource Class Reference
AP_HAL::DigitalSource Class Reference abstract
#include <GPIO.h>
Public Member Functions
virtual void mode (uint8_t output)=0
virtual uint8_t read ()=0
virtual void write (uint8_t value)=0
virtual void toggle ()=0
Detailed Description
Definition at line 15 of file GPIO.h.
Member Function Documentation
virtual void AP_HAL::DigitalSource::mode (uint8_t output) pure virtual
Implemented in PX4::PX4DigitalSource, VRBRAIN::VRBRAINDigitalSource, HALSITL::DigitalSource, Empty::DigitalSource, Linux::DigitalSource_Sysfs, and Linux::DigitalSource.
Referenced by AP_InertialSensor_BMI160::_configure_int1_pin(), AP_InertialSensor_Invensense::_init(), AP_InertialSensor_LSM9DS0::_init_sensor(), Linux::CameraSensor_Mt9v117::_init_sensor(), AP_Baro_BMP085::AP_Baro_BMP085(), DiscreteRGBLed::hw_init(), Linux::RCOutput_PCA9685::init(), AP_Compass_LSM303D::init(), Linux::RCInput_RPI::init(), AP_HAL::GPIO::pinMode(), Linux::SPIDevice::SPIDevice(), test_gpio_input(), and test_gpio_output().
virtual uint8_t AP_HAL::DigitalSource::read () pure virtual
Implemented in PX4::PX4DigitalSource, VRBRAIN::VRBRAINDigitalSource, HALSITL::DigitalSource, Empty::DigitalSource, Linux::DigitalSource_Sysfs, and Linux::DigitalSource.
Referenced by AP_InertialSensor_LSM9DS0::_accel_data_ready(), AP_Baro_BMP085::_data_ready(), AP_Compass_LSM303D::_data_ready(), AP_InertialSensor_Invensense::_data_ready(), AP_InertialSensor_LSM9DS0::_gyro_data_ready(), AP_InertialSensor_BMI160::_read_fifo(), AP_HAL::GPIO::pinMode(), and test_gpio_input().
virtual void AP_HAL::DigitalSource::toggle () pure virtual
Implemented in PX4::PX4DigitalSource, VRBRAIN::VRBRAINDigitalSource, HALSITL::DigitalSource, Empty::DigitalSource, Linux::DigitalSource_Sysfs, and Linux::DigitalSource.
Referenced by AP_HAL::GPIO::pinMode().
virtual void AP_HAL::DigitalSource::write (uint8_t value) pure virtual
Implemented in PX4::PX4DigitalSource, VRBRAIN::VRBRAINDigitalSource, HALSITL::DigitalSource, Empty::DigitalSource, Linux::DigitalSource_Sysfs, and Linux::DigitalSource.
Referenced by Linux::SPIDevice::_cs_assert(), Linux::SPIDevice::_cs_release(), Linux::CameraSensor_Mt9v117::_init_sensor(), DiscreteRGBLed::hw_init(), DiscreteRGBLed::hw_set_rgb(), Linux::RCOutput_PCA9685::init(), AP_HAL::GPIO::pinMode(), and test_gpio_output().
The documentation for this class was generated from the following file:
libraries/AP_HAL/GPIO.h