APM:Libraries: AP_RangeFinder_MaxsonarI2CXL Class Reference
AP_RangeFinder_MaxsonarI2CXL Class Reference
#include <AP_RangeFinder_MaxsonarI2CXL.h>
Public Member Functions
void update (void)
Public Member Functions inherited from AP_RangeFinder_Backend
AP_RangeFinder_Backend (RangeFinder &_ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state)
virtual ~AP_RangeFinder_Backend (void)
bool out_of_range (void) const
virtual void handle_msg (mavlink_message_t *msg)
Static Public Member Functions
static AP_RangeFinder_Backend * detect (RangeFinder &ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state)
Private Member Functions
AP_RangeFinder_MaxsonarI2CXL (RangeFinder &ranger, uint8_t instance, RangeFinder::RangeFinder_State &_state)
bool _init (void)
void _timer (void)
bool start_reading (void)
bool get_reading (uint16_t &reading_cm)
Private Attributes
uint16_t distance
bool new_distance
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
Additional Inherited Members
Protected Member Functions inherited from AP_RangeFinder_Backend
void update_status ()
void set_status (RangeFinder::RangeFinder_Status status)
Protected Attributes inherited from AP_RangeFinder_Backend
RangeFinder & ranger
RangeFinder::RangeFinder_State & state
AP_HAL::Semaphore * _sem
Detailed Description
Definition at line 16 of file AP_RangeFinder_MaxsonarI2CXL.h.
Constructor & Destructor Documentation
AP_RangeFinder_MaxsonarI2CXL::AP_RangeFinder_MaxsonarI2CXL (RangeFinder & ranger, uint8_t instance, RangeFinder::RangeFinder_State & _state) private
Definition at line 38 of file AP_RangeFinder_MaxsonarI2CXL.cpp.
Referenced by detect().
Member Function Documentation
bool AP_RangeFinder_MaxsonarI2CXL::_init (void) private
Definition at line 69 of file AP_RangeFinder_MaxsonarI2CXL.cpp.
Referenced by detect().
void AP_RangeFinder_MaxsonarI2CXL::_timer (void) private
Definition at line 129 of file AP_RangeFinder_MaxsonarI2CXL.cpp.
Referenced by _init().
AP_RangeFinder_Backend * AP_RangeFinder_MaxsonarI2CXL::detect (RangeFinder & ranger, uint8_t instance, RangeFinder::RangeFinder_State & _state) static
Definition at line 49 of file AP_RangeFinder_MaxsonarI2CXL.cpp.
Referenced by RangeFinder::detect_instance().
bool AP_RangeFinder_MaxsonarI2CXL::get_reading (uint16_t & reading_cm) private
Definition at line 108 of file AP_RangeFinder_MaxsonarI2CXL.cpp.
Referenced by _init(), and _timer().
bool AP_RangeFinder_MaxsonarI2CXL::start_reading (void) private
Definition at line 99 of file AP_RangeFinder_MaxsonarI2CXL.cpp.
Referenced by _init(), and get_reading().
void AP_RangeFinder_MaxsonarI2CXL::update (void) virtual
Implements AP_RangeFinder_Backend.
Definition at line 145 of file AP_RangeFinder_MaxsonarI2CXL.cpp.
Member Data Documentation
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_RangeFinder_MaxsonarI2CXL::_dev private
Definition at line 40 of file AP_RangeFinder_MaxsonarI2CXL.h.
Referenced by _init(), get_reading(), and start_reading().
uint16_t AP_RangeFinder_MaxsonarI2CXL::distance private
Definition at line 34 of file AP_RangeFinder_MaxsonarI2CXL.h.
Referenced by _timer(), and update().
bool AP_RangeFinder_MaxsonarI2CXL::new_distance private
Definition at line 35 of file AP_RangeFinder_MaxsonarI2CXL.h.
Referenced by _timer(), and update().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarI2CXL.h
libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarI2CXL.cpp