APM:Libraries: AC_AttitudeControl Class Reference
AC_AttitudeControl Class Reference abstract
#include <AC_AttitudeControl.h>
Public Member Functions
AC_AttitudeControl (AP_AHRS_View &ahrs, const AP_Vehicle::MultiCopter &aparm, AP_Motors &motors, float dt)
virtual ~AC_AttitudeControl ()
AC_P & get_angle_roll_p ()
AC_P & get_angle_pitch_p ()
AC_P & get_angle_yaw_p ()
virtual AC_PID & get_rate_roll_pid ()=0
virtual AC_PID & get_rate_pitch_pid ()=0
virtual AC_PID & get_rate_yaw_pid ()=0
float get_accel_roll_max ()
void set_accel_roll_max (float accel_roll_max)
void save_accel_roll_max (float accel_roll_max)
float get_accel_pitch_max ()
void set_accel_pitch_max (float accel_pitch_max)
void save_accel_pitch_max (float accel_pitch_max)
float get_accel_yaw_max ()
void set_accel_yaw_max (float accel_yaw_max)
void save_accel_yaw_max (float accel_yaw_max)
void relax_attitude_controllers ()
void reset_rate_controller_I_terms ()
void set_yaw_target_to_current_heading ()
void shift_ef_yaw_target (float yaw_shift_cd)
void input_quaternion (Quaternion attitude_desired_quat, float smoothing_gain)
void input_euler_angle_roll_pitch_euler_rate_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_rate_cds, float smoothing_gain)
void input_euler_angle_roll_pitch_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_angle_cd, bool slew_yaw, float smoothing_gain)
void input_euler_rate_roll_pitch_yaw (float euler_roll_rate_cds, float euler_pitch_rate_cds, float euler_yaw_rate_cds)
virtual void input_rate_bf_roll_pitch_yaw (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds)
virtual void rate_controller_run ()=0
void euler_rate_to_ang_vel (const Vector3f &euler_rad, const Vector3f &euler_rate_rads, Vector3f &ang_vel_rads)
bool ang_vel_to_euler_rate (const Vector3f &euler_rad, const Vector3f &ang_vel_rads, Vector3f &euler_rate_rads)
void use_ff_and_input_shaping (bool use_shaping)
Vector3f get_att_target_euler_cd () const
float get_att_error_angle_deg () const
void rate_bf_roll_target (float rate_cds)
void rate_bf_pitch_target (float rate_cds)
void rate_bf_yaw_target (float rate_cds)
float max_rate_step_bf_roll ()
float max_rate_step_bf_pitch ()
float max_rate_step_bf_yaw ()
float max_angle_step_bf_roll ()
float max_angle_step_bf_pitch ()
float max_angle_step_bf_yaw ()
Vector3f rate_bf_targets () const
void bf_feedforward (bool enable_or_disable)
void bf_feedforward_save (bool enable_or_disable)
bool get_bf_feedforward ()
void accel_limiting (bool enable_or_disable)
virtual void update_althold_lean_angle_max (float throttle_in)=0
virtual void set_throttle_out (float throttle_in, bool apply_angle_boost, float filt_cutoff)=0
void set_throttle_out_unstabilized (float throttle_in, bool reset_attitude_control, float filt_cutoff)
float get_throttle_in () const
float angle_boost () const
float get_althold_lean_angle_max () const
float lean_angle_max () const
float input_shaping_angle (float error_angle, float smoothing_gain, float accel_max, float target_ang_vel)
float input_shaping_ang_vel (float target_ang_vel, float desired_ang_vel, float accel_max)
Vector3f euler_accel_limit (Vector3f euler_rad, Vector3f euler_accel)
void thrust_heading_rotation_angles (Quaternion &att_to_quat, const Quaternion &att_from_quat, Vector3f &att_diff_angle, float &thrust_vec_dot)
void attitude_controller_run_quat ()
virtual void parameter_sanity_check ()
virtual bool is_throttle_mix_min () const
virtual void set_throttle_mix_min ()
virtual void set_throttle_mix_man ()
virtual void set_throttle_mix_max ()
virtual void set_throttle_mix_value (float value)
virtual void use_flybar_passthrough (bool passthrough, bool tail_passthrough)
virtual void use_leaky_i (bool leaky_i)
virtual void set_hover_roll_trim_scalar (float scalar)
virtual void passthrough_bf_roll_pitch_rate_yaw (float roll_passthrough, float pitch_passthrough, float yaw_rate_bf_cds)
void control_monitor_log (void)
float control_monitor_rms_output_roll (void) const
float control_monitor_rms_output_roll_P (void) const
float control_monitor_rms_output_roll_D (void) const
float control_monitor_rms_output_pitch_P (void) const
float control_monitor_rms_output_pitch_D (void) const
float control_monitor_rms_output_pitch (void) const
float control_monitor_rms_output_yaw (void) const
Static Public Member Functions
static float sqrt_controller (float error, float p, float second_ord_lim)
static float stopping_point (float first_ord_mag, float p, float second_ord_lim)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
Vector3f update_ang_vel_target_from_att_error (Vector3f attitude_error_rot_vec_rad)
float rate_target_to_motor_roll (float rate_actual_rads, float rate_target_rads)
float rate_target_to_motor_pitch (float rate_actual_rads, float rate_target_rads)
virtual float rate_target_to_motor_yaw (float rate_actual_rads, float rate_target_rads)
virtual float get_roll_trim_rad ()
float get_accel_roll_max_radss ()
float get_accel_pitch_max_radss ()
float get_accel_yaw_max_radss ()
float get_slew_yaw_rads ()
float get_tilt_limit_rad ()
void control_monitor_filter_pid (float value, float &rms_P)
void control_monitor_update (void)
Protected Attributes
AP_Float _slew_yaw
AP_Float _accel_roll_max
AP_Float _accel_pitch_max
AP_Float _accel_yaw_max
AP_Int8 _rate_bf_ff_enabled
AP_Int8 _angle_boost_enabled
AC_P _p_angle_roll
AC_P _p_angle_pitch
AC_P _p_angle_yaw
AP_Float _angle_limit_tc
float _dt
Vector3f _attitude_target_euler_angle
Vector3f _attitude_target_euler_rate
Quaternion _attitude_target_quat
Vector3f _attitude_target_ang_vel
Vector3f _rate_target_ang_vel
float _thrust_error_angle
float _throttle_in = 0.0f
float _angle_boost
bool _use_ff_and_input_shaping
float _althold_lean_angle_max = 0.0f
float _throttle_rpy_mix_desired
float _throttle_rpy_mix
const AP_AHRS_View & _ahrs
const AP_Vehicle::MultiCopter & _aparm
AP_Motors & _motors
struct {
float rms_roll_P
float rms_roll_D
float rms_pitch_P
float rms_pitch_D
float rms_yaw
} _control_monitor
Detailed Description
Definition at line 45 of file AC_AttitudeControl.h.
Constructor & Destructor Documentation
AC_AttitudeControl::AC_AttitudeControl (AP_AHRS_View & ahrs, const AP_Vehicle::MultiCopter & aparm, AP_Motors & motors, float dt) inline
Definition at line 47 of file AC_AttitudeControl.h.
virtual AC_AttitudeControl::~AC_AttitudeControl () inline virtual
Definition at line 67 of file AC_AttitudeControl.h.
Member Function Documentation
void AC_AttitudeControl::accel_limiting (bool enable_or_disable)
Definition at line 662 of file AC_AttitudeControl.cpp.
Referenced by get_bf_feedforward().
bool AC_AttitudeControl::ang_vel_to_euler_rate (const Vector3f & euler_rad, const Vector3f & ang_vel_rads, Vector3f & euler_rate_rads)
Definition at line 547 of file AC_AttitudeControl.cpp.
Referenced by input_quaternion(), input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), and set_yaw_target_to_current_heading().
float AC_AttitudeControl::angle_boost () const inline
Definition at line 208 of file AC_AttitudeControl.h.
void AC_AttitudeControl::attitude_controller_run_quat ()
Definition at line 380 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), and lean_angle_max().
void AC_AttitudeControl::bf_feedforward (bool enable_or_disable) inline
Definition at line 184 of file AC_AttitudeControl.h.
void AC_AttitudeControl::bf_feedforward_save (bool enable_or_disable) inline
Definition at line 187 of file AC_AttitudeControl.h.
void AC_AttitudeControl::control_monitor_filter_pid (float value, float & rms_P) protected
Definition at line 14 of file ControlMonitor.cpp.
Referenced by control_monitor_update().
void AC_AttitudeControl::control_monitor_log (void)
Definition at line 42 of file ControlMonitor.cpp.
float AC_AttitudeControl::control_monitor_rms_output_pitch (void) const
Definition at line 81 of file ControlMonitor.cpp.
float AC_AttitudeControl::control_monitor_rms_output_pitch_D (void) const
Definition at line 97 of file ControlMonitor.cpp.
float AC_AttitudeControl::control_monitor_rms_output_pitch_P (void) const
Definition at line 89 of file ControlMonitor.cpp.
float AC_AttitudeControl::control_monitor_rms_output_roll (void) const
Definition at line 57 of file ControlMonitor.cpp.
float AC_AttitudeControl::control_monitor_rms_output_roll_D (void) const
Definition at line 73 of file ControlMonitor.cpp.
float AC_AttitudeControl::control_monitor_rms_output_roll_P (void) const
Definition at line 65 of file ControlMonitor.cpp.
float AC_AttitudeControl::control_monitor_rms_output_yaw (void) const
Definition at line 105 of file ControlMonitor.cpp.
void AC_AttitudeControl::control_monitor_update (void) protected
Definition at line 25 of file ControlMonitor.cpp.
Referenced by AC_AttitudeControl_Sub::rate_controller_run(), and AC_AttitudeControl_Multi::rate_controller_run().
Vector3f AC_AttitudeControl::euler_accel_limit (Vector3f euler_rad, Vector3f euler_accel)
Definition at line 504 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), and lean_angle_max().
void AC_AttitudeControl::euler_rate_to_ang_vel (const Vector3f & euler_rad, const Vector3f & euler_rate_rads, Vector3f & ang_vel_rads)
Definition at line 533 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), and set_yaw_target_to_current_heading().
float AC_AttitudeControl::get_accel_pitch_max () inline
Definition at line 87 of file AC_AttitudeControl.h.
float AC_AttitudeControl::get_accel_pitch_max_radss () inline protected
Definition at line 288 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), and update_ang_vel_target_from_att_error().
float AC_AttitudeControl::get_accel_roll_max () inline
Definition at line 78 of file AC_AttitudeControl.h.
float AC_AttitudeControl::get_accel_roll_max_radss () inline protected
Definition at line 285 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), and update_ang_vel_target_from_att_error().
float AC_AttitudeControl::get_accel_yaw_max () inline
Definition at line 96 of file AC_AttitudeControl.h.
float AC_AttitudeControl::get_accel_yaw_max_radss () inline protected
Definition at line 291 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), and update_ang_vel_target_from_att_error().
float AC_AttitudeControl::get_althold_lean_angle_max () const
Definition at line 683 of file AC_AttitudeControl.cpp.
Referenced by AC_PosControl::accel_to_lean_angles(), and angle_boost().
AC_P& AC_AttitudeControl::get_angle_pitch_p () inline
Definition at line 71 of file AC_AttitudeControl.h.
AC_P& AC_AttitudeControl::get_angle_roll_p () inline
Definition at line 70 of file AC_AttitudeControl.h.
AC_P& AC_AttitudeControl::get_angle_yaw_p () inline
Definition at line 72 of file AC_AttitudeControl.h.
float AC_AttitudeControl::get_att_error_angle_deg () const inline
Definition at line 151 of file AC_AttitudeControl.h.
Vector3f AC_AttitudeControl::get_att_target_euler_cd () const inline
Definition at line 148 of file AC_AttitudeControl.h.
Referenced by AC_WPNav::set_spline_origin_and_destination(), and AC_WPNav::set_wp_origin_and_destination().
bool AC_AttitudeControl::get_bf_feedforward () inline
Definition at line 190 of file AC_AttitudeControl.h.
virtual AC_PID& AC_AttitudeControl::get_rate_pitch_pid () pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by control_monitor_update(), get_angle_yaw_p(), max_rate_step_bf_pitch(), rate_target_to_motor_pitch(), relax_attitude_controllers(), and reset_rate_controller_I_terms().
virtual AC_PID& AC_AttitudeControl::get_rate_roll_pid () pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by control_monitor_update(), get_angle_yaw_p(), max_rate_step_bf_roll(), rate_target_to_motor_roll(), relax_attitude_controllers(), and reset_rate_controller_I_terms().
virtual AC_PID& AC_AttitudeControl::get_rate_yaw_pid () pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by control_monitor_update(), get_angle_yaw_p(), max_rate_step_bf_yaw(), rate_target_to_motor_yaw(), relax_attitude_controllers(), and reset_rate_controller_I_terms().
virtual float AC_AttitudeControl::get_roll_trim_rad () inline protected virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 282 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), and input_euler_angle_roll_pitch_yaw().
float AC_AttitudeControl::get_slew_yaw_rads () inline protected
Definition at line 294 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_yaw().
float AC_AttitudeControl::get_throttle_in () const inline
Definition at line 205 of file AC_AttitudeControl.h.
float AC_AttitudeControl::get_tilt_limit_rad () inline protected
Definition at line 297 of file AC_AttitudeControl.h.
void AC_AttitudeControl::input_euler_angle_roll_pitch_euler_rate_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_rate_cds, float smoothing_gain)
Definition at line 194 of file AC_AttitudeControl.cpp.
Referenced by set_yaw_target_to_current_heading().
void AC_AttitudeControl::input_euler_angle_roll_pitch_yaw (float euler_roll_angle_cd, float euler_pitch_angle_cd, float euler_yaw_angle_cd, bool slew_yaw, float smoothing_gain)
Definition at line 244 of file AC_AttitudeControl.cpp.
Referenced by set_yaw_target_to_current_heading().
void AC_AttitudeControl::input_euler_rate_roll_pitch_yaw (float euler_roll_rate_cds, float euler_pitch_rate_cds, float euler_yaw_rate_cds)
Definition at line 301 of file AC_AttitudeControl.cpp.
Referenced by set_yaw_target_to_current_heading().
void AC_AttitudeControl::input_quaternion (Quaternion attitude_desired_quat, float smoothing_gain)
Definition at line 159 of file AC_AttitudeControl.cpp.
Referenced by set_yaw_target_to_current_heading().
void AC_AttitudeControl::input_rate_bf_roll_pitch_yaw (float roll_rate_bf_cds, float pitch_rate_bf_cds, float yaw_rate_bf_cds) virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 343 of file AC_AttitudeControl.cpp.
Referenced by AC_AttitudeControl_Heli::input_rate_bf_roll_pitch_yaw(), and set_yaw_target_to_current_heading().
float AC_AttitudeControl::input_shaping_ang_vel (float target_ang_vel, float desired_ang_vel, float accel_max)
Definition at line 492 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_rate_roll_pitch_yaw(), input_rate_bf_roll_pitch_yaw(), and lean_angle_max().
float AC_AttitudeControl::input_shaping_angle (float error_angle, float smoothing_gain, float accel_max, float target_ang_vel)
Definition at line 476 of file AC_AttitudeControl.cpp.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_quaternion(), and lean_angle_max().
virtual bool AC_AttitudeControl::is_throttle_mix_min () const inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 243 of file AC_AttitudeControl.h.
float AC_AttitudeControl::lean_angle_max () const inline
Definition at line 214 of file AC_AttitudeControl.h.
Referenced by AC_PosControl::accel_to_lean_angles(), and AC_WPNav::wp_and_spline_init().
float AC_AttitudeControl::max_angle_step_bf_pitch () inline
Definition at line 175 of file AC_AttitudeControl.h.
float AC_AttitudeControl::max_angle_step_bf_roll () inline
Definition at line 172 of file AC_AttitudeControl.h.
float AC_AttitudeControl::max_angle_step_bf_yaw () inline
Definition at line 178 of file AC_AttitudeControl.h.
float AC_AttitudeControl::max_rate_step_bf_pitch ()
Definition at line 744 of file AC_AttitudeControl.cpp.
Referenced by max_angle_step_bf_pitch(), and rate_bf_yaw_target().
float AC_AttitudeControl::max_rate_step_bf_roll ()
Definition at line 736 of file AC_AttitudeControl.cpp.
Referenced by max_angle_step_bf_roll(), and rate_bf_yaw_target().
float AC_AttitudeControl::max_rate_step_bf_yaw ()
Definition at line 752 of file AC_AttitudeControl.cpp.
Referenced by max_angle_step_bf_yaw(), and rate_bf_yaw_target().
virtual void AC_AttitudeControl::parameter_sanity_check () inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 240 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::passthrough_bf_roll_pitch_rate_yaw (float roll_passthrough, float pitch_passthrough, float yaw_rate_bf_cds) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 261 of file AC_AttitudeControl.h.
void AC_AttitudeControl::rate_bf_pitch_target (float rate_cds) inline
Definition at line 157 of file AC_AttitudeControl.h.
void AC_AttitudeControl::rate_bf_roll_target (float rate_cds) inline
Definition at line 154 of file AC_AttitudeControl.h.
Vector3f AC_AttitudeControl::rate_bf_targets () const inline
Definition at line 181 of file AC_AttitudeControl.h.
Referenced by DataFlash_Class::Log_Write_Rate().
void AC_AttitudeControl::rate_bf_yaw_target (float rate_cds) inline
Definition at line 160 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::rate_controller_run () pure virtual
Implemented in AC_AttitudeControl_Multi, AC_AttitudeControl_Heli, and AC_AttitudeControl_Sub.
Referenced by set_yaw_target_to_current_heading().
float AC_AttitudeControl::rate_target_to_motor_pitch (float rate_actual_rads, float rate_target_rads) protected
Definition at line 616 of file AC_AttitudeControl.cpp.
Referenced by AC_AttitudeControl_Sub::rate_controller_run(), and AC_AttitudeControl_Multi::rate_controller_run().
float AC_AttitudeControl::rate_target_to_motor_roll (float rate_actual_rads, float rate_target_rads) protected
Definition at line 593 of file AC_AttitudeControl.cpp.
Referenced by AC_AttitudeControl_Sub::rate_controller_run(), and AC_AttitudeControl_Multi::rate_controller_run().
float AC_AttitudeControl::rate_target_to_motor_yaw (float rate_actual_rads, float rate_target_rads) protected virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 639 of file AC_AttitudeControl.cpp.
Referenced by AC_AttitudeControl_Sub::rate_controller_run(), and AC_AttitudeControl_Multi::rate_controller_run().
void AC_AttitudeControl::relax_attitude_controllers ()
Definition at line 111 of file AC_AttitudeControl.cpp.
Referenced by save_accel_yaw_max(), and set_throttle_out_unstabilized().
void AC_AttitudeControl::reset_rate_controller_I_terms ()
Definition at line 127 of file AC_AttitudeControl.cpp.
Referenced by save_accel_yaw_max().
void AC_AttitudeControl::save_accel_pitch_max (float accel_pitch_max) inline
Definition at line 93 of file AC_AttitudeControl.h.
void AC_AttitudeControl::save_accel_roll_max (float accel_roll_max) inline
Definition at line 84 of file AC_AttitudeControl.h.
void AC_AttitudeControl::save_accel_yaw_max (float accel_yaw_max) inline
Definition at line 102 of file AC_AttitudeControl.h.
void AC_AttitudeControl::set_accel_pitch_max (float accel_pitch_max) inline
Definition at line 90 of file AC_AttitudeControl.h.
void AC_AttitudeControl::set_accel_roll_max (float accel_roll_max) inline
Definition at line 81 of file AC_AttitudeControl.h.
void AC_AttitudeControl::set_accel_yaw_max (float accel_yaw_max) inline
Definition at line 99 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::set_hover_roll_trim_scalar (float scalar) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 258 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::set_throttle_mix_man () inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 247 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::set_throttle_mix_max () inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 248 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::set_throttle_mix_min () inline virtual
Reimplemented in AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Definition at line 246 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::set_throttle_mix_value (float value) inline virtual
Reimplemented in AC_AttitudeControl_Multi.
Definition at line 249 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::set_throttle_out (float throttle_in, bool apply_angle_boost, float filt_cutoff) pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by AC_PosControl::accel_to_throttle(), and get_bf_feedforward().
void AC_AttitudeControl::set_throttle_out_unstabilized (float throttle_in, bool reset_attitude_control, float filt_cutoff)
Definition at line 99 of file AC_AttitudeControl.cpp.
Referenced by get_bf_feedforward().
void AC_AttitudeControl::set_yaw_target_to_current_heading () inline
Definition at line 111 of file AC_AttitudeControl.h.
void AC_AttitudeControl::shift_ef_yaw_target (float yaw_shift_cd)
Definition at line 524 of file AC_AttitudeControl.cpp.
Referenced by set_yaw_target_to_current_heading().
float AC_AttitudeControl::sqrt_controller (float error, float p, float second_ord_lim) static
Definition at line 690 of file AC_AttitudeControl.cpp.
Referenced by AC_Avoid::get_max_speed(), input_shaping_angle(), lean_angle_max(), AC_PosControl::pos_to_rate_z(), and update_ang_vel_target_from_att_error().
float AC_AttitudeControl::stopping_point (float first_ord_mag, float p, float second_ord_lim) static
Definition at line 708 of file AC_AttitudeControl.cpp.
Referenced by lean_angle_max().
void AC_AttitudeControl::thrust_heading_rotation_angles (Quaternion & att_to_quat, const Quaternion & att_from_quat, Vector3f & att_diff_angle, float & thrust_vec_dot)
Definition at line 429 of file AC_AttitudeControl.cpp.
Referenced by attitude_controller_run_quat(), and lean_angle_max().
virtual void AC_AttitudeControl::update_althold_lean_angle_max (float throttle_in) pure virtual
Implemented in AC_AttitudeControl_Heli, AC_AttitudeControl_Multi, and AC_AttitudeControl_Sub.
Referenced by get_bf_feedforward().
Vector3f AC_AttitudeControl::update_ang_vel_target_from_att_error (Vector3f attitude_error_rot_vec_rad) protected
Definition at line 566 of file AC_AttitudeControl.cpp.
Referenced by attitude_controller_run_quat(), and AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw().
void AC_AttitudeControl::use_ff_and_input_shaping (bool use_shaping) inline
Definition at line 142 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::use_flybar_passthrough (bool passthrough, bool tail_passthrough) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 252 of file AC_AttitudeControl.h.
virtual void AC_AttitudeControl::use_leaky_i (bool leaky_i) inline virtual
Reimplemented in AC_AttitudeControl_Heli.
Definition at line 255 of file AC_AttitudeControl.h.
Member Data Documentation
AP_Float AC_AttitudeControl::_accel_pitch_max protected
Definition at line 306 of file AC_AttitudeControl.h.
Referenced by accel_limiting(), get_accel_pitch_max(), get_accel_pitch_max_radss(), save_accel_pitch_max(), and set_accel_pitch_max().
AP_Float AC_AttitudeControl::_accel_roll_max protected
Definition at line 303 of file AC_AttitudeControl.h.
Referenced by accel_limiting(), get_accel_roll_max(), get_accel_roll_max_radss(), save_accel_roll_max(), and set_accel_roll_max().
AP_Float AC_AttitudeControl::_accel_yaw_max protected
Definition at line 309 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), accel_limiting(), get_accel_yaw_max(), get_accel_yaw_max_radss(), save_accel_yaw_max(), and set_accel_yaw_max().
const AP_AHRS_View& AC_AttitudeControl::_ahrs protected
Definition at line 373 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), AC_AttitudeControl_Sub::get_throttle_boosted(), AC_AttitudeControl_Multi::get_throttle_boosted(), AC_AttitudeControl_Heli::integrate_bf_rate_error_to_angle_errors(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), relax_attitude_controllers(), and set_yaw_target_to_current_heading().
float AC_AttitudeControl::_althold_lean_angle_max = 0.0f protected
Definition at line 364 of file AC_AttitudeControl.h.
Referenced by get_althold_lean_angle_max(), AC_AttitudeControl_Sub::update_althold_lean_angle_max(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), and AC_AttitudeControl_Heli::update_althold_lean_angle_max().
float AC_AttitudeControl::_angle_boost protected
Definition at line 358 of file AC_AttitudeControl.h.
Referenced by angle_boost(), AC_AttitudeControl_Sub::get_throttle_boosted(), AC_AttitudeControl_Multi::get_throttle_boosted(), AC_AttitudeControl_Sub::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), AC_AttitudeControl_Heli::set_throttle_out(), and set_throttle_out_unstabilized().
AP_Int8 AC_AttitudeControl::_angle_boost_enabled protected
Definition at line 315 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::get_throttle_boosted(), and AC_AttitudeControl_Multi::get_throttle_boosted().
AP_Float AC_AttitudeControl::_angle_limit_tc protected
Definition at line 323 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::update_althold_lean_angle_max(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), and AC_AttitudeControl_Heli::update_althold_lean_angle_max().
const AP_Vehicle::MultiCopter& AC_AttitudeControl::_aparm protected
Definition at line 374 of file AC_AttitudeControl.h.
Referenced by get_tilt_limit_rad(), and lean_angle_max().
Vector3f AC_AttitudeControl::_attitude_target_ang_vel protected
Definition at line 344 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl_Heli::integrate_bf_rate_error_to_angle_errors(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), and relax_attitude_controllers().
Vector3f AC_AttitudeControl::_attitude_target_euler_angle protected
Definition at line 330 of file AC_AttitudeControl.h.
Referenced by get_att_target_euler_cd(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), relax_attitude_controllers(), and set_yaw_target_to_current_heading().
Vector3f AC_AttitudeControl::_attitude_target_euler_rate protected
Definition at line 335 of file AC_AttitudeControl.h.
Referenced by input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), and input_rate_bf_roll_pitch_yaw().
Quaternion AC_AttitudeControl::_attitude_target_quat protected
Definition at line 339 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), relax_attitude_controllers(), and shift_ef_yaw_target().
struct { ... } AC_AttitudeControl::_control_monitor
Referenced by control_monitor_log(), control_monitor_rms_output_pitch(), control_monitor_rms_output_pitch_D(), control_monitor_rms_output_pitch_P(), control_monitor_rms_output_roll(), control_monitor_rms_output_roll_D(), control_monitor_rms_output_roll_P(), control_monitor_rms_output_yaw(), and control_monitor_update().
float AC_AttitudeControl::_dt protected
Definition at line 326 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), input_shaping_ang_vel(), input_shaping_angle(), AC_AttitudeControl_Heli::integrate_bf_rate_error_to_angle_errors(), max_rate_step_bf_pitch(), max_rate_step_bf_roll(), max_rate_step_bf_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_target_to_motor_yaw(), AC_AttitudeControl_Sub::update_althold_lean_angle_max(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), AC_AttitudeControl_Heli::update_althold_lean_angle_max(), AC_AttitudeControl_Sub::update_throttle_rpy_mix(), and AC_AttitudeControl_Multi::update_throttle_rpy_mix().
AP_Motors& AC_AttitudeControl::_motors protected
Definition at line 375 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::get_throttle_avg_max(), AC_AttitudeControl_Multi::get_throttle_avg_max(), max_rate_step_bf_pitch(), max_rate_step_bf_roll(), max_rate_step_bf_yaw(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), rate_target_to_motor_pitch(), rate_target_to_motor_roll(), AC_AttitudeControl_Heli::rate_target_to_motor_yaw(), rate_target_to_motor_yaw(), AC_AttitudeControl_Sub::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), AC_AttitudeControl_Heli::set_throttle_out(), and set_throttle_out_unstabilized().
AC_P AC_AttitudeControl::_p_angle_pitch protected
Definition at line 319 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), get_angle_pitch_p(), max_angle_step_bf_pitch(), and update_ang_vel_target_from_att_error().
AC_P AC_AttitudeControl::_p_angle_roll protected
Definition at line 318 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), get_angle_roll_p(), max_angle_step_bf_roll(), and update_ang_vel_target_from_att_error().
AC_P AC_AttitudeControl::_p_angle_yaw protected
Definition at line 320 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::AC_AttitudeControl_Sub(), get_angle_yaw_p(), max_angle_step_bf_yaw(), thrust_heading_rotation_angles(), and update_ang_vel_target_from_att_error().
AP_Int8 AC_AttitudeControl::_rate_bf_ff_enabled protected
Definition at line 312 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), bf_feedforward(), bf_feedforward_save(), get_bf_feedforward(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), and input_rate_bf_roll_pitch_yaw().
Vector3f AC_AttitudeControl::_rate_target_ang_vel protected
Definition at line 348 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), rate_bf_pitch_target(), rate_bf_roll_target(), rate_bf_targets(), rate_bf_yaw_target(), AC_AttitudeControl_Sub::rate_controller_run(), AC_AttitudeControl_Heli::rate_controller_run(), AC_AttitudeControl_Multi::rate_controller_run(), and relax_attitude_controllers().
AP_Float AC_AttitudeControl::_slew_yaw protected
Definition at line 300 of file AC_AttitudeControl.h.
Referenced by get_slew_yaw_rads().
float AC_AttitudeControl::_throttle_in = 0.0f protected
Definition at line 354 of file AC_AttitudeControl.h.
Referenced by get_throttle_in(), AC_AttitudeControl_Sub::set_throttle_out(), AC_AttitudeControl_Multi::set_throttle_out(), AC_AttitudeControl_Heli::set_throttle_out(), set_throttle_out_unstabilized(), AC_AttitudeControl_Sub::update_althold_lean_angle_max(), AC_AttitudeControl_Multi::update_althold_lean_angle_max(), and AC_AttitudeControl_Heli::update_althold_lean_angle_max().
float AC_AttitudeControl::_throttle_rpy_mix protected
Definition at line 370 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::get_throttle_avg_max(), AC_AttitudeControl_Multi::get_throttle_avg_max(), AC_AttitudeControl_Sub::is_throttle_mix_min(), AC_AttitudeControl_Multi::is_throttle_mix_min(), AC_AttitudeControl_Sub::update_throttle_rpy_mix(), and AC_AttitudeControl_Multi::update_throttle_rpy_mix().
float AC_AttitudeControl::_throttle_rpy_mix_desired protected
Definition at line 367 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl_Sub::set_throttle_mix_man(), AC_AttitudeControl_Multi::set_throttle_mix_man(), AC_AttitudeControl_Sub::set_throttle_mix_max(), AC_AttitudeControl_Multi::set_throttle_mix_max(), AC_AttitudeControl_Sub::set_throttle_mix_min(), AC_AttitudeControl_Multi::set_throttle_mix_min(), AC_AttitudeControl_Multi::set_throttle_mix_value(), AC_AttitudeControl_Sub::update_throttle_rpy_mix(), and AC_AttitudeControl_Multi::update_throttle_rpy_mix().
float AC_AttitudeControl::_thrust_error_angle protected
Definition at line 351 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), get_att_error_angle_deg(), and AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw().
bool AC_AttitudeControl::_use_ff_and_input_shaping protected
Definition at line 361 of file AC_AttitudeControl.h.
Referenced by attitude_controller_run_quat(), input_euler_angle_roll_pitch_euler_rate_yaw(), input_euler_angle_roll_pitch_yaw(), input_euler_rate_roll_pitch_yaw(), input_quaternion(), input_rate_bf_roll_pitch_yaw(), update_ang_vel_target_from_att_error(), and use_ff_and_input_shaping().
float AC_AttitudeControl::rms_pitch_D
Definition at line 385 of file AC_AttitudeControl.h.
float AC_AttitudeControl::rms_pitch_P
Definition at line 384 of file AC_AttitudeControl.h.
float AC_AttitudeControl::rms_roll_D
Definition at line 383 of file AC_AttitudeControl.h.
float AC_AttitudeControl::rms_roll_P
Definition at line 382 of file AC_AttitudeControl.h.
float AC_AttitudeControl::rms_yaw
Definition at line 386 of file AC_AttitudeControl.h.
const AP_Param::GroupInfo AC_AttitudeControl::var_info static
Definition at line 264 of file AC_AttitudeControl.h.
Referenced by AC_AttitudeControl().
The documentation for this class was generated from the following files:
libraries/AC_AttitudeControl/AC_AttitudeControl.h
libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
libraries/AC_AttitudeControl/ControlMonitor.cpp