APM:Libraries: HALSITL::RCInput Class Reference
HALSITL::RCInput Class Reference
#include <RCInput.h>
Public Member Functions
RCInput (SITL_State *sitlState)
void init () override
bool new_input () override
uint8_t num_channels () override
uint16_t read (uint8_t ch) override
uint8_t read (uint16_t *periods, uint8_t len) override
bool set_overrides (int16_t *overrides, uint8_t len) override
bool set_override (uint8_t channel, int16_t override) override
void clear_overrides () override
Public Member Functions inherited from AP_HAL::RCInput
virtual void teardown ()
virtual bool rc_bind (int dsmMode)
Private Attributes
SITL_State * _sitlState
uint16_t _override [SITL_RC_INPUT_CHANNELS]
Detailed Description
Definition at line 10 of file RCInput.h.
Constructor & Destructor Documentation
HALSITL::RCInput::RCInput (SITL_State * sitlState) inline explicit
Definition at line 12 of file RCInput.h.
Member Function Documentation
void RCInput::clear_overrides () override virtual
Implements AP_HAL::RCInput.
Definition at line 72 of file RCInput.cpp.
Referenced by init(), and num_channels().
void RCInput::init () override virtual
Call init from the platform hal instance init, so that both the type of the RCInput implementation and init argument (e.g. ISRRegistry) are known to the programmer. (It's too difficult to describe this dependency in the C++ type system.)
Implements AP_HAL::RCInput.
Definition at line 10 of file RCInput.cpp.
Referenced by RCInput().
bool RCInput::new_input () override virtual
Return true if there has been new input since the last call to new_input()
Implements AP_HAL::RCInput.
Definition at line 15 of file RCInput.cpp.
Referenced by RCInput().
uint8_t HALSITL::RCInput::num_channels () inline override virtual
Return the number of valid channels in the last read
Implements AP_HAL::RCInput.
Definition at line 15 of file RCInput.h.
uint16_t RCInput::read (uint8_t ch) override virtual
Implements AP_HAL::RCInput.
Definition at line 24 of file RCInput.cpp.
Referenced by num_channels(), and read().
uint8_t RCInput::read (uint16_t * periods, uint8_t len) override virtual
Implements AP_HAL::RCInput.
Definition at line 35 of file RCInput.cpp.
bool RCInput::set_override (uint8_t channel, int16_t override) override virtual
Implements AP_HAL::RCInput.
Definition at line 58 of file RCInput.cpp.
Referenced by num_channels(), and set_overrides().
bool RCInput::set_overrides (int16_t * overrides, uint8_t len) override virtual
Overrides: these are really grody and don't belong here but we need them at the moment to make the port work. case v of: v == -1 -> no change to this channel v == 0 -> do not override this channel v > 0 -> set v as override.
Implements AP_HAL::RCInput.
Definition at line 46 of file RCInput.cpp.
Referenced by num_channels().
Member Data Documentation
uint16_t HALSITL::RCInput::_override[SITL_RC_INPUT_CHANNELS] private
Definition at line 29 of file RCInput.h.
Referenced by clear_overrides(), read(), and set_override().
SITL_State* HALSITL::RCInput::_sitlState private
Definition at line 26 of file RCInput.h.
Referenced by new_input(), and read().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/RCInput.h
libraries/AP_HAL_SITL/RCInput.cpp