APM:Libraries: AC_PosControl Class Reference
AC_PosControl Class Reference
#include <AC_PosControl.h>
Classes
struct poscontrol_flags
struct poscontrol_limit_flags
Public Types
enum xy_mode { XY_MODE_POS_ONLY = 0, XY_MODE_POS_LIMITED_AND_VEL_FF, XY_MODE_POS_AND_VEL_FF }
Public Member Functions
AC_PosControl (const AP_AHRS_View &ahrs, const AP_InertialNav &inav, const AP_Motors &motors, AC_AttitudeControl &attitude_control, AC_P &p_pos_z, AC_P &p_vel_z, AC_PID &pid_accel_z, AC_P &p_pos_xy, AC_PI_2D &pi_vel_xy)
Constructor.
void set_dt (float delta_sec)
set_dt - sets time delta in seconds for all controllers (i.e. 100hz = 0.01, 400hz = 0.0025)
float get_dt () const
void set_dt_xy (float dt_xy)
set_dt_xy - sets time delta in seconds for horizontal controller (i.e. 50hz = 0.02)
float get_dt_xy () const
void set_speed_z (float speed_down, float speed_up)
float get_speed_up () const
get_speed_up - accessor for current up speed in cm/s
float get_speed_down () const
get_speed_down - accessors for current down speed in cm/s. Will be a negative number
float get_vel_target_z () const
get_vel_target_z - returns current vertical speed in cm/s
void set_accel_z (float accel_cmss)
set_accel_z - set vertical acceleration in cm/s/s
float get_accel_z () const
get_accel_z - returns current vertical acceleration in cm/s/s
void calc_leash_length_z ()
void set_alt_target (float alt_cm)
set_alt_target - set altitude target in cm above home
void set_alt_target_with_slew (float alt_cm, float dt)
virtual void set_alt_target_from_climb_rate (float climb_rate_cms, float dt, bool force_descend)
virtual void set_alt_target_from_climb_rate_ff (float climb_rate_cms, float dt, bool force_descend)
void add_takeoff_climb_rate (float climb_rate_cms, float dt)
void set_alt_target_to_current_alt ()
set_alt_target_to_current_alt - set altitude target to current altitude
void shift_alt_target (float z_cm)
shift altitude target (positive means move altitude up)
void relax_alt_hold_controllers (float throttle_setting)
relax_alt_hold_controllers - set all desired and targets to measured
float get_alt_target () const
float get_alt_error () const
get_alt_error - returns altitude error in cm
float get_horizontal_error () const
void set_target_to_stopping_point_z ()
set_target_to_stopping_point_z - sets altitude target to reasonable stopping altitude in cm above home
void get_stopping_point_z (Vector3f &stopping_point) const
get_stopping_point_z - calculates stopping point based on current position, velocity, vehicle acceleration
void init_takeoff ()
init_takeoff - initialises target altitude if we are taking off
bool is_active_z () const
void update_z_controller ()
update_z_controller - fly to altitude in cm above home
float get_leash_down_z () const
float get_leash_up_z () const
float get_pos_z_kP () const
get_pos_z_kP - returns z position controller's kP gain
void init_xy_controller (bool reset_I=true)
void set_accel_xy (float accel_cmss)
float get_accel_xy () const
void set_speed_xy (float speed_cms)
float get_speed_xy () const
void set_jerk_xy (float jerk_cmsss)
set_jerk_xy - set max horizontal jerk in cm/s/s/s
void set_jerk_xy_to_default ()
void set_limit_accel_xy (void)
void calc_leash_length_xy ()
const Vector3f & get_pos_target () const
get_pos_target - get target as position vector (from home in cm)
void set_pos_target (const Vector3f &position)
set_pos_target in cm from home
void set_xy_target (float x, float y)
set_xy_target in cm from home
void shift_pos_xy_target (float x_cm, float y_cm)
shift position target target in x, y axis
const Vector3f & get_desired_velocity ()
get_desired_velocity - returns xy desired velocity (i.e. feed forward) in cm/s in lat and lon direction
void set_desired_velocity_z (float vel_z_cms)
set_desired_velocity_z - sets desired velocity in cm/s in z axis
void set_desired_velocity_xy (float vel_lat_cms, float vel_lon_cms)
void set_desired_velocity (const Vector3f &des_vel)
void override_vehicle_velocity_xy (const Vector2f &vel_xy)
void freeze_ff_z ()
freeze_ff_z - used to stop the feed forward being calculated during a known discontinuity
void freeze_ff_xy ()
freeze_ff_xy - used to stop the feed forward being calculated during a known discontinuity
bool is_active_xy () const
void update_xy_controller (xy_mode mode, float ekfNavVelGainScaler, bool use_althold_lean_angle)
update_xy_controller - run the horizontal position controller - should be called at 100hz or higher
void set_target_to_stopping_point_xy ()
set_target_to_stopping_point_xy - sets horizontal target to reasonable stopping position in cm from home
void get_stopping_point_xy (Vector3f &stopping_point) const
float get_distance_to_target () const
get_distance_to_target - get horizontal distance to position target in cm (used for reporting)
void init_vel_controller_xyz ()
xyz velocity controller
void update_vel_controller_xyz (float ekfNavVelGainScaler)
float get_roll () const
get desired roll, pitch which should be fed into stabilize controllers
float get_pitch () const
float get_leash_xy () const
float get_pos_xy_kP () const
get_pos_xy_kP - returns xy position controller's kP gain
const Vector3f & get_vel_target () const
accessors for reporting
const Vector3f & get_accel_target () const
void lean_angles_to_accel (float &accel_x_cmss, float &accel_y_cmss) const
float time_since_last_xy_update () const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void pos_to_rate_z ()
void rate_to_accel_z ()
void accel_to_throttle (float accel_target_z)
void desired_vel_to_pos (float nav_dt)
desired_vel_to_pos - move position target using desired velocities
void pos_to_rate_xy (xy_mode mode, float dt, float ekfNavVelGainScaler)
void rate_to_accel_xy (float dt, float ekfNavVelGainScaler)
void accel_to_lean_angles (float dt_xy, float ekfNavVelGainScaler, bool use_althold_lean_angle)
float calc_leash_length (float speed_cms, float accel_cms, float kP) const
calc_leash_length - calculates the horizontal leash length given a maximum speed, acceleration and position kP gain
void init_ekf_xy_reset ()
initialise and check for ekf position resets
void check_for_ekf_xy_reset ()
check for ekf position reset and adjust loiter or brake target position
void init_ekf_z_reset ()
initialise ekf z axis reset check
void check_for_ekf_z_reset ()
check for ekf position reset and adjust loiter or brake target position
Protected Attributes
struct AC_PosControl::poscontrol_flags _flags
struct AC_PosControl::poscontrol_limit_flags _limit
const AP_AHRS_View & _ahrs
const AP_InertialNav & _inav
const AP_Motors & _motors
AC_AttitudeControl & _attitude_control
AC_P & _p_pos_z
AC_P & _p_vel_z
AC_PID & _pid_accel_z
AC_P & _p_pos_xy
AC_PI_2D & _pi_vel_xy
AP_Float _accel_xy_filt_hz
float _dt
float _dt_xy
uint32_t _last_update_xy_ms
uint32_t _last_update_z_ms
float _speed_down_cms
float _speed_up_cms
float _speed_cms
float _accel_z_cms
float _accel_last_z_cms
float _accel_cms
float _jerk_cmsss
float _leash
float _leash_down_z
float _leash_up_z
float _roll_target
float _pitch_target
Vector3f _pos_target
Vector3f _pos_error
Vector3f _vel_desired
Vector3f _vel_target
Vector3f _vel_error
Vector3f _vel_last
Vector3f _accel_target
Vector3f _accel_error
Vector3f _accel_feedforward
Vector2f _vehicle_horiz_vel
float _distance_to_target
LowPassFilterFloat _vel_error_filter
Vector2f _accel_target_jerk_limited
LowPassFilterVector2f _accel_target_filter
uint32_t _ekf_xy_reset_ms
uint32_t _ekf_z_reset_ms
Detailed Description
Definition at line 45 of file AC_PosControl.h.
Member Enumeration Documentation
enum AC_PosControl::xy_mode
Enumerator
XY_MODE_POS_ONLY
XY_MODE_POS_LIMITED_AND_VEL_FF
XY_MODE_POS_AND_VEL_FF
Definition at line 56 of file AC_PosControl.h.
Constructor & Destructor Documentation
AC_PosControl::AC_PosControl (const AP_AHRS_View & ahrs, const AP_InertialNav & inav, const AP_Motors & motors, AC_AttitudeControl & attitude_control, AC_P & p_pos_z, AC_P & p_vel_z, AC_PID & pid_accel_z, AC_P & p_pos_xy, AC_PI_2D & pi_vel_xy)
Constructor.
Definition at line 26 of file AC_PosControl.cpp.
Member Function Documentation
void AC_PosControl::accel_to_lean_angles (float dt, float ekfNavVelGainScaler, bool use_althold_lean_angle) protected
accel_to_lean_angles - horizontal desired acceleration to lean angles converts desired accelerations provided in lat/lon frame to roll/pitch angles
Definition at line 948 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xyz(), and update_xy_controller().
void AC_PosControl::accel_to_throttle (float accel_target_z) protected
Definition at line 455 of file AC_PosControl.cpp.
Referenced by rate_to_accel_z().
void AC_PosControl::add_takeoff_climb_rate (float climb_rate_cms, float dt)
add_takeoff_climb_rate - adjusts alt target up or down using a climb rate in cm/s should be called continuously (with dt set to be the expected time between calls) almost no checks are performed on the input
Definition at line 213 of file AC_PosControl.cpp.
Referenced by set_alt_target().
float AC_PosControl::calc_leash_length (float speed_cms, float accel_cms, float kP) const protected
calc_leash_length - calculates the horizontal leash length given a maximum speed, acceleration and position kP gain
Definition at line 1014 of file AC_PosControl.cpp.
Referenced by calc_leash_length_xy(), and calc_leash_length_z().
void AC_PosControl::calc_leash_length_xy ()
calc_leash_length - calculates the horizontal leash length given a maximum speed, acceleration should be called whenever the speed, acceleration or position kP is modified
private methodscalc_leash_length - calculates the horizontal leash length given a maximum speed, acceleration should be called whenever the speed, acceleration or position kP is modified
Definition at line 783 of file AC_PosControl.cpp.
Referenced by AC_WPNav::init_brake_target(), set_accel_xy(), set_limit_accel_xy(), set_speed_xy(), set_target_to_stopping_point_xy(), update_vel_controller_xyz(), update_xy_controller(), and AC_WPNav::wp_and_spline_init().
void AC_PosControl::calc_leash_length_z ()
calc_leash_length - calculates the vertical leash lengths from maximum speed, acceleration called by pos_to_rate_z if z-axis speed or accelerations are changed
Definition at line 345 of file AC_PosControl.cpp.
Referenced by get_accel_z(), set_accel_z(), set_speed_z(), set_target_to_stopping_point_z(), update_z_controller(), and AC_WPNav::wp_and_spline_init().
void AC_PosControl::check_for_ekf_xy_reset () protected
check for ekf position reset and adjust loiter or brake target position
Definition at line 1053 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xyz(), and update_xy_controller().
void AC_PosControl::check_for_ekf_z_reset () protected
check for ekf position reset and adjust loiter or brake target position
Definition at line 1072 of file AC_PosControl.cpp.
Referenced by update_z_controller().
void AC_PosControl::desired_vel_to_pos (float nav_dt) protected
desired_vel_to_pos - move position target using desired velocities
xy controller private methods
Definition at line 792 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xyz(), and update_xy_controller().
void AC_PosControl::freeze_ff_xy () inline
freeze_ff_xy - used to stop the feed forward being calculated during a known discontinuity
Definition at line 239 of file AC_PosControl.h.
Referenced by AC_WPNav::loiter_soften_for_landing(), set_desired_velocity(), shift_pos_xy_target(), AC_WPNav::shift_wp_origin_to_current_pos(), AC_WPNav::update_spline(), and AC_WPNav::update_wpnav().
void AC_PosControl::freeze_ff_z () inline
freeze_ff_z - used to stop the feed forward being calculated during a known discontinuity
Definition at line 236 of file AC_PosControl.h.
Referenced by init_takeoff(), shift_alt_target(), AC_WPNav::shift_wp_origin_to_current_pos(), AC_WPNav::update_spline(), and AC_WPNav::update_wpnav().
const Vector3f& AC_PosControl::get_accel_target () const inline
Definition at line 284 of file AC_PosControl.h.
Referenced by DataFlash_Class::Log_Write_Rate().
float AC_PosControl::get_accel_xy () const inline
Definition at line 186 of file AC_PosControl.h.
Referenced by AC_Circle::calc_velocities().
float AC_PosControl::get_accel_z () const inline
get_accel_z - returns current vertical acceleration in cm/s/s
Definition at line 98 of file AC_PosControl.h.
float AC_PosControl::get_alt_error () const
get_alt_error - returns altitude error in cm
Definition at line 245 of file AC_PosControl.cpp.
Referenced by get_alt_target().
float AC_PosControl::get_alt_target () const inline
get_alt_target, get_desired_alt - get desired altitude (in cm above home) from loiter or wp controller which should be fed into throttle controller To-Do: remove one of the two functions below
Definition at line 143 of file AC_PosControl.h.
Referenced by AC_WPNav::get_desired_alt(), and AC_Circle::update().
const Vector3f& AC_PosControl::get_desired_velocity () inline
get_desired_velocity - returns xy desired velocity (i.e. feed forward) in cm/s in lat and lon direction
Definition at line 218 of file AC_PosControl.h.
Referenced by AC_WPNav::calc_loiter_desired_velocity().
float AC_PosControl::get_distance_to_target () const
get_distance_to_target - get horizontal distance to position target in cm (used for reporting)
get_distance_to_target - get horizontal distance to loiter target in cm
Definition at line 621 of file AC_PosControl.cpp.
Referenced by freeze_ff_xy(), and AC_WPNav::get_loiter_distance_to_target().
float AC_PosControl::get_dt () const inline
Definition at line 69 of file AC_PosControl.h.
float AC_PosControl::get_dt_xy () const inline
Definition at line 73 of file AC_PosControl.h.
Referenced by AC_WPNav::set_spline_origin_and_destination(), AC_Circle::update(), AC_WPNav::update_brake(), AC_WPNav::update_loiter(), AC_WPNav::update_spline(), update_vel_controller_xyz(), and AC_WPNav::update_wpnav().
float AC_PosControl::get_horizontal_error () const
Definition at line 772 of file AC_PosControl.cpp.
Referenced by get_alt_target().
float AC_PosControl::get_leash_down_z () const inline
Definition at line 167 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), and AC_WPNav::calculate_wp_leash_length().
float AC_PosControl::get_leash_up_z () const inline
Definition at line 168 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), and AC_WPNav::calculate_wp_leash_length().
float AC_PosControl::get_leash_xy () const inline
Definition at line 277 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), and AC_WPNav::calculate_wp_leash_length().
float AC_PosControl::get_pitch () const inline
Definition at line 274 of file AC_PosControl.h.
Referenced by AC_Circle::get_pitch(), and AC_WPNav::get_pitch().
const Vector3f& AC_PosControl::get_pos_target () const inline
get_pos_target - get target as position vector (from home in cm)
Definition at line 206 of file AC_PosControl.h.
Referenced by AC_WPNav::get_loiter_bearing_to_target(), AC_WPNav::get_loiter_target(), AC_Circle::init(), AC_WPNav::set_spline_destination(), AC_WPNav::set_wp_destination(), and AC_WPNav::shift_wp_origin_to_current_pos().
float AC_PosControl::get_pos_xy_kP () const inline
get_pos_xy_kP - returns xy position controller's kP gain
Definition at line 280 of file AC_PosControl.h.
Referenced by AC_WPNav::advance_wp_target_along_track(), and AC_WPNav::calc_loiter_desired_velocity().
float AC_PosControl::get_pos_z_kP () const inline
get_pos_z_kP - returns z position controller's kP gain
Definition at line 171 of file AC_PosControl.h.
float AC_PosControl::get_roll () const inline
get desired roll, pitch which should be fed into stabilize controllers
Definition at line 273 of file AC_PosControl.h.
Referenced by AC_Circle::get_roll(), and AC_WPNav::get_roll().
float AC_PosControl::get_speed_down () const inline
get_speed_down - accessors for current down speed in cm/s. Will be a negative number
Definition at line 88 of file AC_PosControl.h.
float AC_PosControl::get_speed_up () const inline
get_speed_up - accessor for current up speed in cm/s
Definition at line 85 of file AC_PosControl.h.
float AC_PosControl::get_speed_xy () const inline
Definition at line 191 of file AC_PosControl.h.
Referenced by AC_Circle::calc_velocities().
void AC_PosControl::get_stopping_point_xy (Vector3f & stopping_point) const
get_stopping_point_xy - calculates stopping point based on current position, velocity, vehicle acceleration distance_max allows limiting distance to stopping point results placed in stopping_position vector set_accel_xy() should be called before this method to set vehicle acceleration set_leash_length() should have been called before this method
Definition at line 576 of file AC_PosControl.cpp.
Referenced by freeze_ff_xy(), AC_WPNav::get_loiter_stopping_point_xy(), AC_WPNav::get_wp_stopping_point_xy(), AC_WPNav::init_brake_target(), AC_WPNav::set_spline_destination(), set_target_to_stopping_point_xy(), and AC_WPNav::set_wp_destination().
void AC_PosControl::get_stopping_point_z (Vector3f & stopping_point) const
get_stopping_point_z - calculates stopping point based on current position, velocity, vehicle acceleration
Definition at line 260 of file AC_PosControl.cpp.
Referenced by get_alt_target(), AC_WPNav::set_spline_destination(), set_target_to_stopping_point_z(), and AC_WPNav::set_wp_destination().
const Vector3f& AC_PosControl::get_vel_target () const inline
accessors for reporting
Definition at line 283 of file AC_PosControl.h.
Referenced by AC_WPNav::set_spline_origin_and_destination().
float AC_PosControl::get_vel_target_z () const inline
get_vel_target_z - returns current vertical speed in cm/s
Definition at line 91 of file AC_PosControl.h.
void AC_PosControl::init_ekf_xy_reset () protected
initialise and check for ekf position resets
initialise ekf xy position reset check
Definition at line 1046 of file AC_PosControl.cpp.
Referenced by init_vel_controller_xyz(), and init_xy_controller().
void AC_PosControl::init_ekf_z_reset () protected
initialise ekf z axis reset check
Definition at line 1065 of file AC_PosControl.cpp.
Referenced by init_takeoff(), and init_vel_controller_xyz().
void AC_PosControl::init_takeoff ()
init_takeoff - initialises target altitude if we are taking off
Definition at line 300 of file AC_PosControl.cpp.
Referenced by get_alt_target().
void AC_PosControl::init_vel_controller_xyz ()
xyz velocity controller
init_vel_controller_xyz - initialise the velocity controller - should be called once before the caller attempts to use the controller
Definition at line 697 of file AC_PosControl.cpp.
Referenced by freeze_ff_xy().
void AC_PosControl::init_xy_controller (bool reset_I = true)
xy position controllerinit_xy_controller - initialise the xy controller sets target roll angle, pitch angle and I terms based on vehicle current lean angles should be called once whenever significant changes to the position target are made this does not update the xy target
init_xy_controller - initialise the xy controller sets target roll angle, pitch angle and I terms based on vehicle current lean angles should be called once whenever significant changes to the position target are made this does not update the xy target
Definition at line 636 of file AC_PosControl.cpp.
Referenced by get_pos_z_kP(), AC_Circle::init(), AC_WPNav::init_brake_target(), AC_WPNav::init_loiter_target(), and AC_WPNav::wp_and_spline_init().
bool AC_PosControl::is_active_xy () const
Definition at line 627 of file AC_PosControl.cpp.
Referenced by freeze_ff_xy(), and get_stopping_point_xy().
bool AC_PosControl::is_active_z () const
Definition at line 317 of file AC_PosControl.cpp.
Referenced by get_alt_target(), and get_stopping_point_z().
void AC_PosControl::lean_angles_to_accel (float & accel_x_cmss, float & accel_y_cmss) const
Definition at line 1006 of file AC_PosControl.cpp.
Referenced by get_accel_target(), init_vel_controller_xyz(), and init_xy_controller().
void AC_PosControl::override_vehicle_velocity_xy (const Vector2f & vel_xy) inline
Definition at line 233 of file AC_PosControl.h.
void AC_PosControl::pos_to_rate_xy (xy_mode mode, float dt, float ekfNavVelGainScaler) protected
pos_to_rate_xy - horizontal position error to velocity controller converts position (_pos_target) to target velocity (_vel_target) when use_desired_rate is set to true: desired velocity (_vel_desired) is combined into final target velocity and velocity due to position error is reduce to a maximum of 1m/s
Definition at line 813 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xyz(), and update_xy_controller().
void AC_PosControl::pos_to_rate_z () protected
z controller private methods
Definition at line 357 of file AC_PosControl.cpp.
Referenced by update_z_controller().
void AC_PosControl::rate_to_accel_xy (float dt, float ekfNavVelGainScaler) protected
rate_to_accel_xy - horizontal desired rate to desired acceleration converts desired velocities in lat/lon directions to accelerations in lat/lon frame
Definition at line 887 of file AC_PosControl.cpp.
Referenced by update_vel_controller_xyz(), and update_xy_controller().
void AC_PosControl::rate_to_accel_z () protected
Definition at line 407 of file AC_PosControl.cpp.
Referenced by pos_to_rate_z().
void AC_PosControl::relax_alt_hold_controllers (float throttle_setting)
relax_alt_hold_controllers - set all desired and targets to measured
Definition at line 230 of file AC_PosControl.cpp.
Referenced by set_alt_target_to_current_alt().
void AC_PosControl::set_accel_xy (float accel_cmss)
set_accel_xy - set horizontal acceleration in cm/s/s leash length will be recalculated the next time update_xy_controller() is called
position controllerset_accel_xy - set horizontal acceleration in cm/s/s calc_leash_length_xy should be called afterwards
Definition at line 509 of file AC_PosControl.cpp.
Referenced by AC_WPNav::calc_loiter_desired_velocity(), get_pos_z_kP(), AC_WPNav::init_brake_target(), AC_WPNav::init_loiter_target(), AC_WPNav::update_loiter(), AC_WPNav::update_wpnav(), and AC_WPNav::wp_and_spline_init().
void AC_PosControl::set_accel_z (float accel_cmss)
set_accel_z - set vertical acceleration in cm/s/s
set_accel_z - set vertical acceleration in cm/s/s leash length will be recalculated the next time update_z_controller() is called
Definition at line 121 of file AC_PosControl.cpp.
Referenced by get_vel_target_z(), AC_WPNav::update_wpnav(), and AC_WPNav::wp_and_spline_init().
void AC_PosControl::set_alt_target (float alt_cm) inline
set_alt_target - set altitude target in cm above home
Definition at line 105 of file AC_PosControl.h.
Referenced by init_vel_controller_xyz(), and AC_WPNav::set_desired_alt().
void AC_PosControl::set_alt_target_from_climb_rate (float climb_rate_cms, float dt, bool force_descend) virtual
set_alt_target_from_climb_rate - adjusts target up or down using a climb rate in cm/s should be called continuously (with dt set to be the expected time between calls) actual position target will be moved no faster than the speed_down and speed_up target will also be stopped if the motors hit their limits or leash length is exceeded set force_descend to true during landing to allow target to move low enough to slow the motors
set_alt_target_from_climb_rate - adjusts target up or down using a climb rate in cm/s should be called continuously (with dt set to be the expected time between calls) actual position target will be moved no faster than the speed_down and speed_up target will also be stopped if the motors hit their limits or leash length is exceeded
Reimplemented in AC_PosControl_Sub.
Definition at line 160 of file AC_PosControl.cpp.
Referenced by set_alt_target().
void AC_PosControl::set_alt_target_from_climb_rate_ff (float climb_rate_cms, float dt, bool force_descend) virtual
set_alt_target_from_climb_rate_ff - adjusts target up or down using a climb rate in cm/s using feed-forward should be called continuously (with dt set to be the expected time between calls) actual position target will be moved no faster than the speed_down and speed_up target will also be stopped if the motors hit their limits or leash length is exceeded set force_descend to true during landing to allow target to move low enough to slow the motors
Reimplemented in AC_PosControl_Sub.
Definition at line 179 of file AC_PosControl.cpp.
Referenced by set_alt_target(), and update_vel_controller_xyz().
void AC_PosControl::set_alt_target_to_current_alt () inline
set_alt_target_to_current_alt - set altitude target to current altitude
Definition at line 133 of file AC_PosControl.h.
void AC_PosControl::set_alt_target_with_slew (float alt_cm, float dt)
set_alt_target_with_slew - adjusts target towards a final altitude target should be called continuously (with dt set to be the expected time between calls) actual position target will be moved no faster than the speed_down and speed_up target will also be stopped if the motors hit their limits or leash length is exceeded
Definition at line 134 of file AC_PosControl.cpp.
Referenced by set_alt_target().
void AC_PosControl::set_desired_velocity (const Vector3f & des_vel) inline
set_desired_velocity - sets desired velocity in cm/s in all 3 axis when update_vel_controller_xyz is next called the position target is moved based on the desired velocity
Definition at line 230 of file AC_PosControl.h.
Referenced by init_vel_controller_xyz().
void AC_PosControl::set_desired_velocity_xy (float vel_lat_cms, float vel_lon_cms) inline
set_desired_velocity_xy - sets desired velocity in cm/s in lat and lon directions when update_xy_controller is next called the position target is moved based on the desired velocity and the desired velocities are fed forward into the rate_to_accel step
Definition at line 226 of file AC_PosControl.h.
Referenced by AC_WPNav::calc_loiter_desired_velocity(), AC_WPNav::init_loiter_target(), and AC_WPNav::update_brake().
void AC_PosControl::set_desired_velocity_z (float vel_z_cms) inline
set_desired_velocity_z - sets desired velocity in cm/s in z axis
Definition at line 221 of file AC_PosControl.h.
void AC_PosControl::set_dt (float delta_sec)
set_dt - sets time delta in seconds for all controllers (i.e. 100hz = 0.01, 400hz = 0.0025)
initialisation functionsset_dt - sets time delta in seconds for all controllers (i.e. 100hz = 0.01, 400hz = 0.0025) updates z axis accel controller's D term filter
z-axis position controller
Definition at line 85 of file AC_PosControl.cpp.
void AC_PosControl::set_dt_xy (float dt_xy)
set_dt_xy - sets time delta in seconds for horizontal controller (i.e. 50hz = 0.02)
Definition at line 97 of file AC_PosControl.cpp.
Referenced by get_dt().
void AC_PosControl::set_jerk_xy (float jerk_cmsss) inline
set_jerk_xy - set max horizontal jerk in cm/s/s/s
Definition at line 194 of file AC_PosControl.h.
Referenced by AC_WPNav::calc_loiter_desired_velocity(), AC_WPNav::init_brake_target(), AC_WPNav::init_loiter_target(), and AC_WPNav::update_loiter().
void AC_PosControl::set_jerk_xy_to_default () inline
Definition at line 195 of file AC_PosControl.h.
Referenced by AC_WPNav::update_wpnav(), and AC_WPNav::wp_and_spline_init().
void AC_PosControl::set_limit_accel_xy (void) inline
set_limit_accel_xy - mark that accel has been limited this prevents integrator buildup
Definition at line 199 of file AC_PosControl.h.
void AC_PosControl::set_pos_target (const Vector3f & position)
set_pos_target in cm from home
Definition at line 530 of file AC_PosControl.cpp.
Referenced by AC_WPNav::advance_spline_target_along_track(), AC_WPNav::advance_wp_target_along_track(), get_pos_target(), AC_WPNav::set_spline_origin_and_destination(), AC_WPNav::set_wp_origin_and_destination(), and AC_WPNav::shift_wp_origin_to_current_pos().
void AC_PosControl::set_speed_xy (float speed_cms)
set_speed_xy - set horizontal speed maximum in cm/s leash length will be recalculated the next time update_xy_controller() is called
set_speed_xy - set horizontal speed maximum in cm/s calc_leash_length_xy should be called afterwards
Definition at line 520 of file AC_PosControl.cpp.
Referenced by AC_WPNav::calc_loiter_desired_velocity(), get_accel_xy(), AC_WPNav::init_brake_target(), AC_WPNav::init_loiter_target(), AC_WPNav::set_speed_xy(), AC_WPNav::update_loiter(), and AC_WPNav::wp_and_spline_init().
void AC_PosControl::set_speed_z (float speed_down, float speed_up)
z position controllerset_speed_z - sets maximum climb and descent rates speed_down can be positive or negative but will always be interpreted as a descent speed leash length will be recalculated the next time update_z_controller() is called
set_speed_z - sets maximum climb and descent rates To-Do: call this in the main code as part of flight mode initialisation calc_leash_length_z should be called afterwards speed_down should be a negative number
Definition at line 107 of file AC_PosControl.cpp.
Referenced by get_dt_xy(), and AC_WPNav::wp_and_spline_init().
void AC_PosControl::set_target_to_stopping_point_xy ()
set_target_to_stopping_point_xy - sets horizontal target to reasonable stopping position in cm from home
Definition at line 563 of file AC_PosControl.cpp.
Referenced by freeze_ff_xy(), and AC_Circle::init().
void AC_PosControl::set_target_to_stopping_point_z ()
set_target_to_stopping_point_z - sets altitude target to reasonable stopping altitude in cm above home
set_target_to_stopping_point_z - returns reasonable stopping altitude in cm above home
Definition at line 251 of file AC_PosControl.cpp.
Referenced by get_alt_target(), and AC_Circle::init().
void AC_PosControl::set_xy_target (float x, float y)
set_xy_target in cm from home
Definition at line 543 of file AC_PosControl.cpp.
Referenced by get_pos_target(), AC_WPNav::init_loiter_target(), init_vel_controller_xyz(), AC_WPNav::loiter_soften_for_landing(), and AC_Circle::update().
void AC_PosControl::shift_alt_target (float z_cm)
shift altitude target (positive means move altitude up)
Definition at line 219 of file AC_PosControl.cpp.
Referenced by check_for_ekf_z_reset(), and set_alt_target_to_current_alt().
void AC_PosControl::shift_pos_xy_target (float x_cm, float y_cm)
shift position target target in x, y axis
Definition at line 550 of file AC_PosControl.cpp.
Referenced by check_for_ekf_xy_reset(), and get_pos_target().
float AC_PosControl::time_since_last_xy_update () const
Definition at line 690 of file AC_PosControl.cpp.
Referenced by get_accel_target(), AC_Circle::update(), AC_WPNav::update_brake(), AC_WPNav::update_loiter(), AC_WPNav::update_spline(), and AC_WPNav::update_wpnav().
void AC_PosControl::update_vel_controller_xyz (float ekfNavVelGainScaler)
update_velocity_controller_xyz - run the velocity controller - should be called at 100hz or higher velocity targets should we set using set_desired_velocity_xyz() method callers should use get_roll() and get_pitch() methods and sent to the attitude controller throttle targets will be sent directly to the motors
Definition at line 730 of file AC_PosControl.cpp.
Referenced by freeze_ff_xy().
void AC_PosControl::update_xy_controller (xy_mode mode, float ekfNavVelGainScaler, bool use_althold_lean_angle)
update_xy_controller - run the horizontal position controller - should be called at 100hz or higher
update_xy_controller - run the horizontal position controller - should be called at 100hz or higher when use_desired_velocity is true the desired velocity (i.e. feed forward) is incorporated at the pos_to_rate step
Definition at line 659 of file AC_PosControl.cpp.
Referenced by freeze_ff_xy(), AC_Circle::update(), AC_WPNav::update_brake(), AC_WPNav::update_loiter(), AC_WPNav::update_spline(), and AC_WPNav::update_wpnav().
void AC_PosControl::update_z_controller ()
update_z_controller - fly to altitude in cm above home
Definition at line 323 of file AC_PosControl.cpp.
Referenced by get_alt_target(), and update_vel_controller_xyz().
Member Data Documentation
float AC_PosControl::_accel_cms protected
Definition at line 394 of file AC_PosControl.h.
Referenced by calc_leash_length_xy(), get_accel_xy(), get_stopping_point_xy(), pos_to_rate_xy(), and set_accel_xy().
Vector3f AC_PosControl::_accel_error protected
Definition at line 412 of file AC_PosControl.h.
Referenced by accel_to_throttle().
Vector3f AC_PosControl::_accel_feedforward protected
Definition at line 413 of file AC_PosControl.h.
Referenced by rate_to_accel_xy(), rate_to_accel_z(), and relax_alt_hold_controllers().
float AC_PosControl::_accel_last_z_cms protected
Definition at line 393 of file AC_PosControl.h.
Referenced by relax_alt_hold_controllers(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), and set_alt_target_from_climb_rate_ff().
Vector3f AC_PosControl::_accel_target protected
Definition at line 411 of file AC_PosControl.h.
Referenced by accel_to_lean_angles(), get_accel_target(), init_vel_controller_xyz(), init_xy_controller(), rate_to_accel_xy(), rate_to_accel_z(), and relax_alt_hold_controllers().
LowPassFilterVector2f AC_PosControl::_accel_target_filter protected
Definition at line 419 of file AC_PosControl.h.
Referenced by accel_to_lean_angles().
Vector2f AC_PosControl::_accel_target_jerk_limited protected
Definition at line 418 of file AC_PosControl.h.
Referenced by accel_to_lean_angles().
AP_Float AC_PosControl::_accel_xy_filt_hz protected
Definition at line 382 of file AC_PosControl.h.
Referenced by accel_to_lean_angles().
float AC_PosControl::_accel_z_cms protected
Definition at line 392 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_accel_z(), get_stopping_point_z(), pos_to_rate_z(), set_accel_z(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), and set_alt_target_from_climb_rate_ff().
const AP_AHRS_View& AC_PosControl::_ahrs protected
Definition at line 369 of file AC_PosControl.h.
Referenced by accel_to_lean_angles(), accel_to_throttle(), check_for_ekf_xy_reset(), check_for_ekf_z_reset(), init_ekf_xy_reset(), init_ekf_z_reset(), init_vel_controller_xyz(), init_xy_controller(), lean_angles_to_accel(), and relax_alt_hold_controllers().
AC_AttitudeControl& AC_PosControl::_attitude_control protected
Definition at line 372 of file AC_PosControl.h.
Referenced by accel_to_lean_angles(), and accel_to_throttle().
float AC_PosControl::_distance_to_target protected
Definition at line 415 of file AC_PosControl.h.
Referenced by get_distance_to_target(), and pos_to_rate_xy().
float AC_PosControl::_dt protected
Definition at line 385 of file AC_PosControl.h.
Referenced by get_dt(), rate_to_accel_z(), set_dt(), and update_vel_controller_xyz().
float AC_PosControl::_dt_xy protected
Definition at line 386 of file AC_PosControl.h.
Referenced by get_dt_xy(), and set_dt_xy().
uint32_t AC_PosControl::_ekf_xy_reset_ms protected
Definition at line 422 of file AC_PosControl.h.
Referenced by check_for_ekf_xy_reset(), and init_ekf_xy_reset().
uint32_t AC_PosControl::_ekf_z_reset_ms protected
Definition at line 423 of file AC_PosControl.h.
Referenced by check_for_ekf_z_reset(), and init_ekf_z_reset().
struct AC_PosControl::poscontrol_flags AC_PosControl::_flags protected
Referenced by AC_PosControl(), accel_to_lean_angles(), accel_to_throttle(), calc_leash_length_xy(), calc_leash_length_z(), desired_vel_to_pos(), freeze_ff_xy(), freeze_ff_z(), get_stopping_point_z(), init_vel_controller_xyz(), init_xy_controller(), override_vehicle_velocity_xy(), pos_to_rate_z(), rate_to_accel_xy(), rate_to_accel_z(), relax_alt_hold_controllers(), set_accel_xy(), set_accel_z(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_with_slew(), set_pos_target(), set_speed_xy(), set_speed_z(), and update_z_controller().
const AP_InertialNav& AC_PosControl::_inav protected
Definition at line 370 of file AC_PosControl.h.
Referenced by get_alt_error(), get_stopping_point_xy(), get_stopping_point_z(), init_takeoff(), init_vel_controller_xyz(), pos_to_rate_xy(), pos_to_rate_z(), rate_to_accel_xy(), rate_to_accel_z(), relax_alt_hold_controllers(), set_alt_target_to_current_alt(), and set_alt_target_with_slew().
float AC_PosControl::_jerk_cmsss protected
Definition at line 395 of file AC_PosControl.h.
Referenced by accel_to_lean_angles(), set_jerk_xy(), and set_jerk_xy_to_default().
uint32_t AC_PosControl::_last_update_xy_ms protected
Definition at line 387 of file AC_PosControl.h.
Referenced by is_active_xy(), time_since_last_xy_update(), update_vel_controller_xyz(), and update_xy_controller().
uint32_t AC_PosControl::_last_update_z_ms protected
Definition at line 388 of file AC_PosControl.h.
Referenced by is_active_z(), and update_z_controller().
float AC_PosControl::_leash protected
Definition at line 396 of file AC_PosControl.h.
Referenced by calc_leash_length_xy(), get_leash_xy(), get_stopping_point_xy(), and pos_to_rate_xy().
float AC_PosControl::_leash_down_z protected
Definition at line 397 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_leash_down_z(), pos_to_rate_z(), and set_alt_target_with_slew().
float AC_PosControl::_leash_up_z protected
Definition at line 398 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_leash_up_z(), pos_to_rate_z(), and set_alt_target_with_slew().
struct AC_PosControl::poscontrol_limit_flags AC_PosControl::_limit protected
Referenced by AC_PosControl(), accel_to_lean_angles(), pos_to_rate_z(), rate_to_accel_xy(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), and set_limit_accel_xy().
const AP_Motors& AC_PosControl::_motors protected
Definition at line 371 of file AC_PosControl.h.
Referenced by accel_to_throttle(), init_takeoff(), rate_to_accel_xy(), relax_alt_hold_controllers(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), and set_alt_target_with_slew().
AC_P& AC_PosControl::_p_pos_xy protected
Definition at line 378 of file AC_PosControl.h.
Referenced by calc_leash_length_xy(), get_pos_xy_kP(), get_stopping_point_xy(), and pos_to_rate_xy().
AC_P& AC_PosControl::_p_pos_z protected
Definition at line 375 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_pos_z_kP(), get_stopping_point_z(), and pos_to_rate_z().
AC_P& AC_PosControl::_p_vel_z protected
Definition at line 376 of file AC_PosControl.h.
Referenced by rate_to_accel_z().
AC_PI_2D& AC_PosControl::_pi_vel_xy protected
Definition at line 379 of file AC_PosControl.h.
Referenced by init_vel_controller_xyz(), init_xy_controller(), rate_to_accel_xy(), and set_dt_xy().
AC_PID& AC_PosControl::_pid_accel_z protected
Definition at line 377 of file AC_PosControl.h.
Referenced by accel_to_throttle(), init_takeoff(), relax_alt_hold_controllers(), and set_dt().
float AC_PosControl::_pitch_target protected
Definition at line 402 of file AC_PosControl.h.
Referenced by accel_to_lean_angles(), get_pitch(), init_vel_controller_xyz(), and init_xy_controller().
Vector3f AC_PosControl::_pos_error protected
Definition at line 406 of file AC_PosControl.h.
Referenced by get_horizontal_error(), pos_to_rate_xy(), and pos_to_rate_z().
Vector3f AC_PosControl::_pos_target protected
Definition at line 405 of file AC_PosControl.h.
Referenced by add_takeoff_climb_rate(), desired_vel_to_pos(), get_alt_error(), get_alt_target(), get_pos_target(), init_takeoff(), pos_to_rate_xy(), pos_to_rate_z(), relax_alt_hold_controllers(), set_alt_target(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_to_current_alt(), set_alt_target_with_slew(), set_pos_target(), set_target_to_stopping_point_xy(), set_target_to_stopping_point_z(), set_xy_target(), shift_alt_target(), and shift_pos_xy_target().
float AC_PosControl::_roll_target protected
Definition at line 401 of file AC_PosControl.h.
Referenced by accel_to_lean_angles(), get_roll(), init_vel_controller_xyz(), and init_xy_controller().
float AC_PosControl::_speed_cms protected
Definition at line 391 of file AC_PosControl.h.
Referenced by calc_leash_length_xy(), get_speed_xy(), pos_to_rate_xy(), and set_speed_xy().
float AC_PosControl::_speed_down_cms protected
Definition at line 389 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_speed_down(), pos_to_rate_z(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_with_slew(), and set_speed_z().
float AC_PosControl::_speed_up_cms protected
Definition at line 390 of file AC_PosControl.h.
Referenced by calc_leash_length_z(), get_speed_up(), pos_to_rate_z(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_with_slew(), and set_speed_z().
Vector2f AC_PosControl::_vehicle_horiz_vel protected
Definition at line 414 of file AC_PosControl.h.
Referenced by override_vehicle_velocity_xy(), and rate_to_accel_xy().
Vector3f AC_PosControl::_vel_desired protected
Definition at line 407 of file AC_PosControl.h.
Referenced by desired_vel_to_pos(), get_desired_velocity(), get_stopping_point_z(), pos_to_rate_xy(), pos_to_rate_z(), relax_alt_hold_controllers(), AC_PosControl_Sub::set_alt_target_from_climb_rate(), set_alt_target_from_climb_rate(), AC_PosControl_Sub::set_alt_target_from_climb_rate_ff(), set_alt_target_from_climb_rate_ff(), set_alt_target_with_slew(), set_desired_velocity(), set_desired_velocity_xy(), set_desired_velocity_z(), set_pos_target(), and update_vel_controller_xyz().
Vector3f AC_PosControl::_vel_error protected
Definition at line 409 of file AC_PosControl.h.
Referenced by get_stopping_point_xy(), get_stopping_point_z(), rate_to_accel_xy(), and rate_to_accel_z().
LowPassFilterFloat AC_PosControl::_vel_error_filter protected
Definition at line 416 of file AC_PosControl.h.
Referenced by rate_to_accel_z(), and set_dt().
Vector3f AC_PosControl::_vel_last protected
Definition at line 410 of file AC_PosControl.h.
Referenced by rate_to_accel_xy(), rate_to_accel_z(), and relax_alt_hold_controllers().
Vector3f AC_PosControl::_vel_target protected
Definition at line 408 of file AC_PosControl.h.
Referenced by get_vel_target(), get_vel_target_z(), pos_to_rate_xy(), pos_to_rate_z(), rate_to_accel_xy(), rate_to_accel_z(), and relax_alt_hold_controllers().
const AP_Param::GroupInfo AC_PosControl::var_info static
Initial value:
= {
    AP_GROUPINFO("_ACC_XY_FILT", 1, AC_PosControl, _accel_xy_filt_hz, POSCONTROL_ACCEL_FILTER_HZ),
    AP_GROUPEND
}
Definition at line 292 of file AC_PosControl.h.
Referenced by AC_PosControl().
The documentation for this class was generated from the following files:
libraries/AC_AttitudeControl/AC_PosControl.h
libraries/AC_AttitudeControl/AC_PosControl.cpp