APM:Libraries: Linux::UARTDriver Class Reference
Linux::UARTDriver Class Reference
#include <UARTDriver.h>
Public Member Functions
UARTDriver (bool default_console)
void begin (uint32_t b)
void begin (uint32_t b, uint16_t rxS, uint16_t txS)
void end ()
void flush ()
bool is_initialized ()
void set_blocking_writes (bool blocking)
bool tx_pending ()
uint32_t available () override
uint32_t txspace () override
int16_t read () override
size_t write (uint8_t c)
size_t write (const uint8_t *buffer, size_t size)
void set_device_path (const char *path)
bool _write_pending_bytes (void)
virtual void _timer_tick (void)
virtual enum flow_control get_flow_control (void) override
virtual void set_flow_control (enum flow_control flow_control_setting) override
Public Member Functions inherited from AP_HAL::UARTDriver
UARTDriver ()
void printf (const char *s,...) FMT_PRINTF(2
void void vprintf (const char *s, va_list ap)
Public Member Functions inherited from AP_HAL::BetterStream
BetterStream (void)
Public Member Functions inherited from AP_HAL::Print
Print ()
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Static Public Member Functions
static UARTDriver * from (AP_HAL::UARTDriver *uart)
Protected Member Functions
virtual int _write_fd (const uint8_t *buf, uint16_t n)
virtual int _read_fd (uint8_t *buf, uint16_t n)
Protected Attributes
const char * device_path
volatile bool _initialised
ByteBuffer _readbuf {0}
ByteBuffer _writebuf {0}
Private Member Functions
void _allocate_buffers (uint16_t rxS, uint16_t txS)
void _deallocate_buffers ()
AP_HAL::OwnPtr< SerialDevice > _parseDevicePath (const char *arg)
Private Attributes
AP_HAL::OwnPtr< SerialDevice > _device
bool _nonblocking_writes
bool _console
volatile bool _in_timer
uint16_t _base_port
char * _ip
char * _flag
bool _connected
bool _packetise
uint64_t _last_write_time
Additional Inherited Members
Public Types inherited from AP_HAL::UARTDriver
enum flow_control { FLOW_CONTROL_DISABLE =0, FLOW_CONTROL_ENABLE =1, FLOW_CONTROL_AUTO =2 }
Detailed Description
Definition at line 11 of file UARTDriver.h.
Constructor & Destructor Documentation
UARTDriver::UARTDriver (bool default_console)
Definition at line 34 of file UARTDriver.cpp.
Member Function Documentation
void UARTDriver::_allocate_buffers (uint16_t rxS, uint16_t txS) private
Definition at line 93 of file UARTDriver.cpp.
Referenced by begin().
void UARTDriver::_deallocate_buffers () private
Definition at line 112 of file UARTDriver.cpp.
Referenced by end().
AP_HAL::OwnPtr< SerialDevice > UARTDriver::_parseDevicePath (const char * arg) private
Definition at line 124 of file UARTDriver.cpp.
Referenced by begin().
int UARTDriver::_read_fd (uint8_t * buf, uint16_t n) protected virtual
Reimplemented in Linux::RPIOUARTDriver, and Linux::SPIUARTDriver.
Definition at line 346 of file UARTDriver.cpp.
Referenced by Linux::SPIUARTDriver::_read_fd(), Linux::RPIOUARTDriver::_read_fd(), and _timer_tick().
void UARTDriver::_timer_tick (void) virtual
Reimplemented in Linux::RPIOUARTDriver, and Linux::SPIUARTDriver.
Definition at line 451 of file UARTDriver.cpp.
Referenced by Linux::Scheduler::_run_uarts(), Linux::SPIUARTDriver::_timer_tick(), Linux::RPIOUARTDriver::_timer_tick(), and from().
int UARTDriver::_write_fd (const uint8_t * buf, uint16_t n) protected virtual
Reimplemented in Linux::RPIOUARTDriver, and Linux::SPIUARTDriver.
Definition at line 327 of file UARTDriver.cpp.
Referenced by Linux::SPIUARTDriver::_write_fd(), Linux::RPIOUARTDriver::_write_fd(), and _write_pending_bytes().
bool UARTDriver::_write_pending_bytes (void)
Definition at line 356 of file UARTDriver.cpp.
Referenced by _timer_tick(), and from().
uint32_t UARTDriver::available (void) override virtual
Implements AP_HAL::Stream.
Definition at line 252 of file UARTDriver.cpp.
Referenced by from().
void UARTDriver::begin (uint32_t b) virtual
Implements AP_HAL::UARTDriver.
Definition at line 55 of file UARTDriver.cpp.
Referenced by Linux::SPIUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), and from().
void UARTDriver::begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace) virtual
Extended port open method
Allows for both opening with specified buffer sizes, and re-opening to adjust a subset of the port's settings.
Note
Buffer sizes greater than ::_max_buffer_size will be rounded down.
Parameters
baud Selects the speed that the port will be configured to. If zero, the port speed is left unchanged.
rxSpace Sets the receive buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_rx_buffer_size if it is currently closed.
txSpace Sets the transmit buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_tx_buffer_size if it is currently closed.
Implements AP_HAL::UARTDriver.
Definition at line 60 of file UARTDriver.cpp.
void UARTDriver::end () virtual
Implements AP_HAL::UARTDriver.
Definition at line 203 of file UARTDriver.cpp.
Referenced by from().
void UARTDriver::flush (void) virtual
Implements AP_HAL::UARTDriver.
Definition at line 217 of file UARTDriver.cpp.
Referenced by from().
static UARTDriver* Linux::UARTDriver::from (AP_HAL::UARTDriver * uart) inline static
Definition at line 15 of file UARTDriver.h.
Referenced by Linux::Scheduler::_run_uarts().
virtual enum flow_control Linux::UARTDriver::get_flow_control (void) inline override virtual
Reimplemented from AP_HAL::UARTDriver.
Definition at line 42 of file UARTDriver.h.
bool UARTDriver::is_initialized () virtual
Implements AP_HAL::UARTDriver.
Definition at line 226 of file UARTDriver.cpp.
Referenced by Linux::SPIUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), and from().
int16_t UARTDriver::read (void) override virtual
Implements AP_HAL::Stream.
Definition at line 271 of file UARTDriver.cpp.
Referenced by from().
void UARTDriver::set_blocking_writes (bool blocking) virtual
Implements AP_HAL::UARTDriver.
Definition at line 235 of file UARTDriver.cpp.
Referenced by from().
void UARTDriver::set_device_path (const char * path)
Definition at line 47 of file UARTDriver.cpp.
Referenced by from(), and HAL_Linux::run().
virtual void Linux::UARTDriver::set_flow_control (enum flow_control flow_control_setting) inline override virtual
Reimplemented from AP_HAL::UARTDriver.
Definition at line 47 of file UARTDriver.h.
bool UARTDriver::tx_pending () virtual
Implements AP_HAL::UARTDriver.
Definition at line 244 of file UARTDriver.cpp.
Referenced by from().
uint32_t UARTDriver::txspace (void) override virtual
Implements AP_HAL::Stream.
Definition at line 263 of file UARTDriver.cpp.
Referenced by from().
size_t UARTDriver::write (uint8_t c) virtual
Implements AP_HAL::Print.
Definition at line 286 of file UARTDriver.cpp.
Referenced by from(), and write().
size_t UARTDriver::write (const uint8_t * buffer, size_t size) virtual
Implements AP_HAL::Print.
Definition at line 304 of file UARTDriver.cpp.
Member Data Documentation
uint16_t Linux::UARTDriver::_base_port private
Definition at line 57 of file UARTDriver.h.
Referenced by _parseDevicePath().
bool Linux::UARTDriver::_connected private
Definition at line 60 of file UARTDriver.h.
Referenced by _write_fd(), begin(), and end().
bool Linux::UARTDriver::_console private
Definition at line 55 of file UARTDriver.h.
Referenced by begin(), and UARTDriver().
AP_HAL::OwnPtr<SerialDevice> Linux::UARTDriver::_device private
Definition at line 53 of file UARTDriver.h.
Referenced by _read_fd(), _write_fd(), begin(), end(), get_flow_control(), and set_flow_control().
char* Linux::UARTDriver::_flag private
Definition at line 59 of file UARTDriver.h.
Referenced by _parseDevicePath().
volatile bool Linux::UARTDriver::_in_timer private
Definition at line 56 of file UARTDriver.h.
Referenced by _timer_tick(), begin(), and end().
volatile bool Linux::UARTDriver::_initialised protected
Definition at line 71 of file UARTDriver.h.
Referenced by _allocate_buffers(), Linux::RPIOUARTDriver::_bus_timer(), _timer_tick(), available(), Linux::SPIUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), begin(), end(), is_initialized(), read(), txspace(), and write().
char* Linux::UARTDriver::_ip private
Definition at line 58 of file UARTDriver.h.
Referenced by _parseDevicePath().
uint64_t Linux::UARTDriver::_last_write_time private
Definition at line 67 of file UARTDriver.h.
bool Linux::UARTDriver::_nonblocking_writes private
Definition at line 54 of file UARTDriver.h.
Referenced by set_blocking_writes(), and write().
bool Linux::UARTDriver::_packetise private
Definition at line 61 of file UARTDriver.h.
Referenced by _parseDevicePath(), and _write_pending_bytes().
ByteBuffer Linux::UARTDriver::_readbuf {0} protected
Definition at line 75 of file UARTDriver.h.
Referenced by _allocate_buffers(), Linux::RPIOUARTDriver::_bus_timer(), _deallocate_buffers(), _timer_tick(), Linux::SPIUARTDriver::_write_fd(), available(), Linux::SPIUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), and read().
ByteBuffer Linux::UARTDriver::_writebuf {0} protected
Definition at line 76 of file UARTDriver.h.
Referenced by _allocate_buffers(), Linux::RPIOUARTDriver::_bus_timer(), _deallocate_buffers(), _write_pending_bytes(), Linux::SPIUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), tx_pending(), txspace(), and write().
const char* Linux::UARTDriver::device_path protected
Definition at line 70 of file UARTDriver.h.
Referenced by _parseDevicePath(), Linux::SPIUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), begin(), and set_device_path().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/UARTDriver.h
libraries/AP_HAL_Linux/UARTDriver.cpp