APM:Libraries: HALSITL::Scheduler Class Reference
HALSITL::Scheduler Class Reference
#include <Scheduler.h>
Public Member Functions
Scheduler (SITL_State *sitlState)
void init ()
void delay (uint16_t ms)
void delay_microseconds (uint16_t us)
void register_delay_callback (AP_HAL::Proc, uint16_t min_time_ms)
void register_timer_process (AP_HAL::MemberProc)
void register_io_process (AP_HAL::MemberProc)
void suspend_timer_procs ()
void resume_timer_procs ()
bool in_timerprocess ()
void register_timer_failsafe (AP_HAL::Proc, uint32_t period_us)
void system_initialized ()
void reboot (bool hold_in_bootloader)
bool interrupts_are_blocked (void)
void sitl_begin_atomic ()
void sitl_end_atomic ()
uint64_t stopped_clock_usec () const
Public Member Functions inherited from AP_HAL::Scheduler
Scheduler ()
virtual void delay_microseconds_boost (uint16_t us)
virtual bool register_timer_process (AP_HAL::MemberProc proc, uint8_t freq_div)
virtual void create_uavcan_thread ()
Static Public Member Functions
static Scheduler * from (AP_HAL::Scheduler *scheduler)
static void timer_event ()
Private Member Functions
void stop_clock (uint64_t time_usec)
Static Private Member Functions
static void _run_timer_procs (bool called_from_isr)
static void _run_io_procs (bool called_from_isr)
Private Attributes
SITL_State * _sitlState
uint8_t _nested_atomic_ctr
AP_HAL::Proc _delay_cb
uint16_t _min_delay_cb_ms
bool _initialized
uint64_t _stopped_clock_usec
Static Private Attributes
static AP_HAL::Proc _failsafe = nullptr
static volatile bool _timer_suspended = false
static volatile bool _timer_event_missed = false
static AP_HAL::MemberProc _timer_proc [SITL_SCHEDULER_MAX_TIMER_PROCS] = {nullptr}
static AP_HAL::MemberProc _io_proc [SITL_SCHEDULER_MAX_TIMER_PROCS] = {nullptr}
static uint8_t _num_timer_procs = 0
static uint8_t _num_io_procs = 0
static bool _in_timer_proc = false
static bool _in_io_proc = false
Detailed Description
Definition at line 11 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler::Scheduler (SITL_State * sitlState) explicit
Definition at line 27 of file Scheduler.cpp.
Member Function Documentation
void Scheduler::_run_io_procs (bool called_from_isr) static private
Definition at line 188 of file Scheduler.cpp.
Referenced by stop_clock(), and timer_event().
void Scheduler::_run_timer_procs (bool called_from_isr) static private
Definition at line 149 of file Scheduler.cpp.
Referenced by resume_timer_procs(), and timer_event().
void Scheduler::delay (uint16_t ms) virtual
Implements AP_HAL::Scheduler.
Definition at line 49 of file Scheduler.cpp.
Referenced by from().
void Scheduler::delay_microseconds (uint16_t us) virtual
Implements AP_HAL::Scheduler.
Definition at line 37 of file Scheduler.cpp.
Referenced by delay(), and from().
static Scheduler* HALSITL::Scheduler::from (AP_HAL::Scheduler * scheduler) inline static
Definition at line 14 of file Scheduler.h.
Referenced by HALSITL::SITL_State::init().
bool Scheduler::in_timerprocess () virtual
Implements AP_HAL::Scheduler.
Definition at line 114 of file Scheduler.cpp.
Referenced by from().
void Scheduler::init (void) virtual
Implements AP_HAL::Scheduler.
Definition at line 33 of file Scheduler.cpp.
Referenced by from().
bool HALSITL::Scheduler::interrupts_are_blocked (void) inline
Definition at line 38 of file Scheduler.h.
Referenced by HALSITL::SITL_State::_fdm_input_step().
void Scheduler::reboot (bool hold_in_bootloader) virtual
Implements AP_HAL::Scheduler.
Definition at line 144 of file Scheduler.cpp.
Referenced by from().
void Scheduler::register_delay_callback (AP_HAL::Proc proc, uint16_t min_time_ms) virtual
Implements AP_HAL::Scheduler.
Definition at line 62 of file Scheduler.cpp.
Referenced by from().
void Scheduler::register_io_process (AP_HAL::MemberProc proc) virtual
Implements AP_HAL::Scheduler.
Definition at line 83 of file Scheduler.cpp.
Referenced by from().
void Scheduler::register_timer_failsafe (AP_HAL::Proc failsafe, uint32_t period_us) virtual
Implements AP_HAL::Scheduler.
Definition at line 97 of file Scheduler.cpp.
Referenced by from().
void Scheduler::register_timer_process (AP_HAL::MemberProc proc) virtual
Implements AP_HAL::Scheduler.
Definition at line 69 of file Scheduler.cpp.
Referenced by from().
void Scheduler::resume_timer_procs () virtual
Implements AP_HAL::Scheduler.
Definition at line 106 of file Scheduler.cpp.
Referenced by from().
void HALSITL::Scheduler::sitl_begin_atomic () inline
Definition at line 42 of file Scheduler.h.
Referenced by HALSITL::SITL_State::_fdm_input_step().
void Scheduler::sitl_end_atomic ()
Definition at line 136 of file Scheduler.cpp.
Referenced by HALSITL::SITL_State::_fdm_input_step(), and sitl_begin_atomic().
void Scheduler::stop_clock (uint64_t time_usec) private virtual
optional function to stop clock at a given time, used by log replay
Reimplemented from AP_HAL::Scheduler.
Definition at line 218 of file Scheduler.cpp.
uint64_t HALSITL::Scheduler::stopped_clock_usec () const inline
Definition at line 52 of file Scheduler.h.
void Scheduler::suspend_timer_procs () virtual
Implements AP_HAL::Scheduler.
Definition at line 102 of file Scheduler.cpp.
Referenced by from().
void Scheduler::system_initialized () virtual
Implements AP_HAL::Scheduler.
Definition at line 118 of file Scheduler.cpp.
Referenced by from().
static void HALSITL::Scheduler::timer_event () inline static
Definition at line 47 of file Scheduler.h.
Referenced by HALSITL::SITL_State::_fdm_input_step().
Member Data Documentation
AP_HAL::Proc HALSITL::Scheduler::_delay_cb private
Definition at line 57 of file Scheduler.h.
Referenced by delay(), and register_delay_callback().
AP_HAL::Proc Scheduler::_failsafe = nullptr static private
Definition at line 59 of file Scheduler.h.
Referenced by _run_timer_procs(), and register_timer_failsafe().
bool Scheduler::_in_io_proc = false static private
Definition at line 71 of file Scheduler.h.
Referenced by _run_io_procs(), and in_timerprocess().
bool Scheduler::_in_timer_proc = false static private
Definition at line 70 of file Scheduler.h.
Referenced by _run_timer_procs(), and in_timerprocess().
bool HALSITL::Scheduler::_initialized private
Definition at line 75 of file Scheduler.h.
Referenced by system_initialized().
AP_HAL::MemberProc Scheduler::_io_proc = {nullptr} static private
Definition at line 67 of file Scheduler.h.
Referenced by _run_io_procs(), and register_io_process().
uint16_t HALSITL::Scheduler::_min_delay_cb_ms private
Definition at line 58 of file Scheduler.h.
Referenced by delay(), and register_delay_callback().
uint8_t HALSITL::Scheduler::_nested_atomic_ctr private
Definition at line 56 of file Scheduler.h.
Referenced by interrupts_are_blocked(), sitl_begin_atomic(), and sitl_end_atomic().
uint8_t Scheduler::_num_io_procs = 0 static private
Definition at line 69 of file Scheduler.h.
Referenced by _run_io_procs(), and register_io_process().
uint8_t Scheduler::_num_timer_procs = 0 static private
Definition at line 68 of file Scheduler.h.
Referenced by _run_timer_procs(), and register_timer_process().
SITL_State* HALSITL::Scheduler::_sitlState private
Definition at line 55 of file Scheduler.h.
Referenced by delay_microseconds(), and system_initialized().
uint64_t HALSITL::Scheduler::_stopped_clock_usec private
Definition at line 76 of file Scheduler.h.
Referenced by stop_clock(), and stopped_clock_usec().
volatile bool Scheduler::_timer_event_missed = false static private
Definition at line 65 of file Scheduler.h.
Referenced by _run_io_procs(), _run_timer_procs(), and resume_timer_procs().
AP_HAL::MemberProc Scheduler::_timer_proc = {nullptr} static private
Definition at line 66 of file Scheduler.h.
Referenced by _run_timer_procs(), and register_timer_process().
volatile bool Scheduler::_timer_suspended = false static private
Definition at line 64 of file Scheduler.h.
Referenced by _run_io_procs(), _run_timer_procs(), resume_timer_procs(), and suspend_timer_procs().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/Scheduler.h
libraries/AP_HAL_SITL/Scheduler.cpp