APM:Libraries: DataFlash_SITL Class Reference
DataFlash_SITL Class Reference
#include <DataFlash_SITL.h>
Public Member Functions
DataFlash_SITL (DataFlash_Class &front, DFMessageWriter_DFLogStart *writer)
void Init () override
void ReadManufacturerID ()
bool CardInserted ()
Public Member Functions inherited from DataFlash_Block
DataFlash_Block (DataFlash_Class &front, DFMessageWriter_DFLogStart *writer)
void EraseAll ()
bool NeedPrep (void)
void Prep ()
bool WritePrioritisedBlock (const void *pBuffer, uint16_t size, bool is_critical)
uint16_t find_last_log () override
void get_log_boundaries (uint16_t log_num, uint16_t &start_page, uint16_t &end_page)
void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)
int16_t get_log_data_raw (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
uint16_t get_num_logs () override
uint16_t start_new_log (void)
void LogReadProcess (const uint16_t list_entry, uint16_t start_page, uint16_t end_page, print_mode_fn print_mode, AP_HAL::BetterStream *port)
void DumpPageInfo (AP_HAL::BetterStream *port)
void ShowDeviceInfo (AP_HAL::BetterStream *port)
void ListAvailableLogs (AP_HAL::BetterStream *port)
uint32_t bufferspace_available ()
Public Member Functions inherited from DataFlash_Backend
FUNCTOR_TYPEDEF (print_mode_fn, void, AP_HAL::BetterStream *, uint8_t)
FUNCTOR_TYPEDEF (vehicle_startup_message_Log_Writer, void)
DataFlash_Backend (DataFlash_Class &front, class DFMessageWriter_DFLogStart *writer)
vehicle_startup_message_Log_Writer vehicle_message_writer ()
void internal_error ()
bool WriteBlock (const void *pBuffer, uint16_t size)
bool WriteCriticalBlock (const void *pBuffer, uint16_t size)
void EnableWrites (bool enable)
virtual bool logging_started (void) const
void set_mission (const AP_Mission *mission)
virtual void stop_logging (void)=0
void Log_Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
virtual void flush (void)
virtual void remote_log_block_status_msg (mavlink_channel_t chan, mavlink_message_t *msg)
virtual void periodic_tasks ()
uint8_t num_types () const
const struct LogStructure * structure (uint8_t structure) const
void Log_Write_EntireMission (const AP_Mission &mission)
bool Log_Write_Format (const struct LogStructure *structure)
bool Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t &mav_cmd)
bool Log_Write_Message (const char *message)
bool Log_Write_Mission_Cmd (const AP_Mission &mission, const AP_Mission::Mission_Command &cmd)
bool Log_Write_Mode (uint8_t mode, uint8_t reason=0)
bool Log_Write_Parameter (const char *name, float value)
bool Log_Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type)
uint32_t num_dropped (void) const
bool Log_Write_Emit_FMT (uint8_t msg_type)
bool Log_Write (uint8_t msg_type, va_list arg_list, bool is_critical=false)
virtual bool logging_enabled () const =0
virtual bool logging_failed () const =0
virtual void vehicle_was_disarmed ()
Private Member Functions
void BufferWrite (uint8_t BufferNum, uint16_t IntPageAdr, uint8_t Data)
void BufferToPage (uint8_t BufferNum, uint16_t PageAdr, uint8_t wait)
void PageToBuffer (uint8_t BufferNum, uint16_t PageAdr)
void WaitReady ()
uint8_t ReadStatusReg ()
uint8_t ReadStatus ()
uint16_t PageSize ()
void PageErase (uint16_t PageAdr)
void BlockErase (uint16_t BlockAdr)
void ChipErase ()
void BlockWrite (uint8_t BufferNum, uint16_t IntPageAdr, const void *pHeader, uint8_t hdr_size, const void *pBuffer, uint16_t size)
bool BlockRead (uint8_t BufferNum, uint16_t IntPageAdr, void *pBuffer, uint16_t size)
Additional Inherited Members
Public Attributes inherited from DataFlash_Backend
bool log_write_started
Protected Member Functions inherited from DataFlash_Backend
virtual void periodic_10Hz (const uint32_t now)
virtual void periodic_1Hz (const uint32_t now)
virtual void periodic_fullrate (const uint32_t now)
void _print_log_entry (uint8_t msg_type, print_mode_fn print_mode, AP_HAL::BetterStream *port)
virtual bool WriteBlockCheckStartupMessages ()
virtual void WriteMoreStartupMessages ()
virtual void push_log_blocks ()
virtual void start_new_log_reset_variables ()
Protected Attributes inherited from DataFlash_Block
uint8_t df_manufacturer
uint16_t df_device
uint16_t df_PageSize
uint16_t df_NumPages
Protected Attributes inherited from DataFlash_Backend
uint32_t dropped
uint8_t internal_errors
DataFlash_Class & _front
bool _writes_enabled = false
DFMessageWriter_DFLogStart * _startup_messagewriter
bool _writing_startup_messages
uint32_t _internal_errors
uint32_t _dropped
Detailed Description
Definition at line 12 of file DataFlash_SITL.h.
Constructor & Destructor Documentation
DataFlash_SITL::DataFlash_SITL (DataFlash_Class & front, DFMessageWriter_DFLogStart * writer) inline
Definition at line 41 of file DataFlash_SITL.h.
Member Function Documentation
void DataFlash_SITL::BlockErase (uint16_t BlockAdr) private virtual
Implements DataFlash_Block.
Definition at line 144 of file DataFlash_SITL.cpp.
bool DataFlash_SITL::BlockRead (uint8_t BufferNum, uint16_t IntPageAdr, void * pBuffer, uint16_t size) private virtual
Implements DataFlash_Block.
Definition at line 127 of file DataFlash_SITL.cpp.
void DataFlash_SITL::BlockWrite (uint8_t BufferNum, uint16_t IntPageAdr, const void * pHeader, uint8_t hdr_size, const void * pBuffer, uint16_t size) private virtual
Implements DataFlash_Block.
Definition at line 107 of file DataFlash_SITL.cpp.
void DataFlash_SITL::BufferToPage (uint8_t BufferNum, uint16_t PageAdr, uint8_t wait) private virtual
Implements DataFlash_Block.
Definition at line 96 of file DataFlash_SITL.cpp.
void DataFlash_SITL::BufferWrite (uint8_t BufferNum, uint16_t IntPageAdr, uint8_t Data) private
Definition at line 102 of file DataFlash_SITL.cpp.
bool DataFlash_SITL::CardInserted (void) virtual
Implements DataFlash_Block.
Definition at line 58 of file DataFlash_SITL.cpp.
Referenced by DataFlash_SITL().
void DataFlash_SITL::ChipErase () private virtual
Implements DataFlash_Block.
Definition at line 153 of file DataFlash_SITL.cpp.
void DataFlash_SITL::Init () override virtual
Reimplemented from DataFlash_Backend.
Definition at line 30 of file DataFlash_SITL.cpp.
Referenced by DataFlash_SITL().
void DataFlash_SITL::PageErase (uint16_t PageAdr) private virtual
Implements DataFlash_Block.
Definition at line 136 of file DataFlash_SITL.cpp.
Referenced by ChipErase().
uint16_t DataFlash_SITL::PageSize () inline private
Definition at line 78 of file DataFlash_SITL.cpp.
void DataFlash_SITL::PageToBuffer (uint8_t BufferNum, uint16_t PageAdr) private virtual
Implements DataFlash_Block.
Definition at line 90 of file DataFlash_SITL.cpp.
void DataFlash_SITL::ReadManufacturerID () virtual
Implements DataFlash_Block.
Definition at line 52 of file DataFlash_SITL.cpp.
Referenced by DataFlash_SITL().
uint8_t DataFlash_SITL::ReadStatus () inline private
Definition at line 71 of file DataFlash_SITL.cpp.
Referenced by WaitReady().
uint8_t DataFlash_SITL::ReadStatusReg () private
Definition at line 64 of file DataFlash_SITL.cpp.
void DataFlash_SITL::WaitReady () private virtual
Implements DataFlash_Block.
Definition at line 85 of file DataFlash_SITL.cpp.
The documentation for this class was generated from the following files:
libraries/DataFlash/DataFlash_SITL.h
libraries/DataFlash/DataFlash_SITL.cpp