APM:Libraries: ByteBuffer Class Reference
ByteBuffer Class Reference
#include <RingBuffer.h>
Classes
struct IoVec
Public Member Functions
ByteBuffer (uint32_t size)
~ByteBuffer (void)
uint32_t available (void) const
void clear (void)
uint32_t space (void) const
bool empty (void) const
uint32_t write (const uint8_t *data, uint32_t len)
uint32_t read (uint8_t *data, uint32_t len)
bool read_byte (uint8_t *data)
bool update (const uint8_t *data, uint32_t len)
uint32_t get_size (void) const
bool set_size (uint32_t size)
bool advance (uint32_t n)
const uint8_t * readptr (uint32_t &available_bytes)
int16_t peek (uint32_t ofs) const
uint32_t peekbytes (uint8_t *data, uint32_t len)
uint8_t peekiovec (IoVec vec[2], uint32_t len)
uint8_t reserve (IoVec vec[2], uint32_t len)
bool commit (uint32_t len)
Private Attributes
uint8_t * buf
uint32_t size
std::atomic< uint32_t > head {0}
std::atomic< uint32_t > tail {0}
Detailed Description
Definition at line 9 of file RingBuffer.h.
Constructor & Destructor Documentation
ByteBuffer::ByteBuffer (uint32_t size)
Definition at line 6 of file RingBuffer.cpp.
Referenced by ObjectBuffer< Linux::GyroSample >::ObjectBuffer().
ByteBuffer::~ByteBuffer (void)
Definition at line 12 of file RingBuffer.cpp.
Member Function Documentation
bool ByteBuffer::advance (uint32_t n)
Definition at line 116 of file RingBuffer.cpp.
Referenced by PX4::PX4UARTDriver::_timer_tick(), VRBRAIN::VRBRAINUARTDriver::_timer_tick(), HALSITL::UARTDriver::_timer_tick(), Linux::UARTDriver::_write_pending_bytes(), get_size(), read(), and read_byte().
uint32_t ByteBuffer::available (void) const
Definition at line 37 of file RingBuffer.cpp.
Referenced by Linux::RPIOUARTDriver::_bus_timer(), VRBRAIN::VRBRAINUARTDriver::_timer_tick(), PX4::PX4UARTDriver::_timer_tick(), Linux::UARTDriver::_write_pending_bytes(), advance(), VRBRAIN::VRBRAINUARTDriver::available(), PX4::PX4UARTDriver::available(), Linux::UARTDriver::available(), QURT::UDPDriver::available(), QURT::UARTDriver::available(), HALSITL::UARTDriver::available(), peek(), peekiovec(), QURT::UDPDriver::socket_check(), QURT::UARTDriver::timer_tick(), Linux::UARTDriver::tx_pending(), and update().
void ByteBuffer::clear (void)
Definition at line 49 of file RingBuffer.cpp.
bool ByteBuffer::commit (uint32_t len)
Definition at line 202 of file RingBuffer.cpp.
Referenced by PX4::PX4UARTDriver::_timer_tick(), VRBRAIN::VRBRAINUARTDriver::_timer_tick(), Linux::UARTDriver::_timer_tick(), and write().
bool ByteBuffer::empty (void) const
Definition at line 74 of file RingBuffer.cpp.
Referenced by ObjectArray< mavlink_statustext_t >::pop(), QURT::UDPDriver::read(), and QURT::UARTDriver::read().
uint32_t ByteBuffer::get_size (void) const inline
Definition at line 42 of file RingBuffer.h.
Referenced by PX4::PX4UARTDriver::begin(), VRBRAIN::VRBRAINUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), QURT::UDPDriver::begin(), and QURT::UARTDriver::begin().
int16_t ByteBuffer::peek (uint32_t ofs) const
Definition at line 246 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_write_pending_bytes(), get_size(), read_byte(), and QURT::UDPDriver::socket_check().
uint32_t ByteBuffer::peekbytes (uint8_t * data, uint32_t len)
Definition at line 157 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_write_pending_bytes(), get_size(), and read().
uint8_t ByteBuffer::peekiovec (ByteBuffer::IoVec iovec[2], uint32_t len)
Definition at line 125 of file RingBuffer.cpp.
Referenced by PX4::PX4UARTDriver::_timer_tick(), VRBRAIN::VRBRAINUARTDriver::_timer_tick(), Linux::UARTDriver::_write_pending_bytes(), and peekbytes().
uint32_t ByteBuffer::read (uint8_t * data, uint32_t len)
Definition at line 212 of file RingBuffer.cpp.
Referenced by Linux::RPIOUARTDriver::_bus_timer(), qflight_UART_read(), QURT::UDPDriver::read(), QURT::UARTDriver::read(), HALSITL::UARTDriver::read(), QURT::UDPDriver::socket_check(), and QURT::UARTDriver::timer_tick().
bool ByteBuffer::read_byte (uint8_t * data)
Definition at line 219 of file RingBuffer.cpp.
Referenced by PX4::PX4UARTDriver::read(), VRBRAIN::VRBRAINUARTDriver::read(), and Linux::UARTDriver::read().
const uint8_t * ByteBuffer::readptr (uint32_t & available_bytes)
Definition at line 238 of file RingBuffer.cpp.
Referenced by HALSITL::UARTDriver::_timer_tick(), get_size(), and peekiovec().
uint8_t ByteBuffer::reserve (ByteBuffer::IoVec iovec[2], uint32_t len)
Definition at line 171 of file RingBuffer.cpp.
Referenced by PX4::PX4UARTDriver::_timer_tick(), VRBRAIN::VRBRAINUARTDriver::_timer_tick(), Linux::UARTDriver::_timer_tick(), and write().
bool ByteBuffer::set_size (uint32_t size)
Definition at line 20 of file RingBuffer.cpp.
Referenced by Linux::UARTDriver::_allocate_buffers(), Linux::UARTDriver::_deallocate_buffers(), HALSITL::UARTDriver::_uart_start_connection(), Linux::SPIUARTDriver::begin(), PX4::PX4UARTDriver::begin(), VRBRAIN::VRBRAINUARTDriver::begin(), Linux::RPIOUARTDriver::begin(), PX4::PX4UARTDriver::end(), VRBRAIN::VRBRAINUARTDriver::end(), and get_size().
uint32_t ByteBuffer::space (void) const
Definition at line 54 of file RingBuffer.cpp.
Referenced by Linux::RPIOUARTDriver::_bus_timer(), PX4::PX4UARTDriver::_timer_tick(), VRBRAIN::VRBRAINUARTDriver::_timer_tick(), Linux::UARTDriver::_timer_tick(), HALSITL::UARTDriver::_timer_tick(), commit(), ObjectArray< mavlink_statustext_t >::push(), ObjectArray< mavlink_statustext_t >::push_force(), reserve(), PX4::PX4UARTDriver::txspace(), VRBRAIN::VRBRAINUARTDriver::txspace(), Linux::UARTDriver::txspace(), QURT::UDPDriver::txspace(), QURT::UARTDriver::txspace(), HALSITL::UARTDriver::txspace(), PX4::PX4UARTDriver::write(), VRBRAIN::VRBRAINUARTDriver::write(), Linux::UARTDriver::write(), QURT::UDPDriver::write(), and QURT::UARTDriver::write().
bool ByteBuffer::update (const uint8_t * data, uint32_t len)
Definition at line 98 of file RingBuffer.cpp.
uint32_t ByteBuffer::write (const uint8_t * data, uint32_t len)
Definition at line 79 of file RingBuffer.cpp.
Referenced by Linux::RPIOUARTDriver::_bus_timer(), QURT::UARTDriver::_read_callback(), HALSITL::UARTDriver::_timer_tick(), Linux::SPIUARTDriver::_write_fd(), QURT::UDPDriver::socket_input(), VRBRAIN::VRBRAINUARTDriver::write(), PX4::PX4UARTDriver::write(), Linux::UARTDriver::write(), QURT::UDPDriver::write(), QURT::UARTDriver::write(), and HALSITL::UARTDriver::write().
Member Data Documentation
uint8_t* ByteBuffer::buf private
Definition at line 87 of file RingBuffer.h.
Referenced by ByteBuffer(), peek(), peekiovec(), readptr(), reserve(), set_size(), update(), and ~ByteBuffer().
std::atomic<uint32_t> ByteBuffer::head {0} private
Definition at line 90 of file RingBuffer.h.
Referenced by advance(), available(), clear(), ObjectArray< mavlink_statustext_t >::clear(), empty(), ObjectArray< mavlink_statustext_t >::ObjectArray(), ObjectArray< mavlink_statustext_t >::operator[](), peek(), ObjectArray< mavlink_statustext_t >::pop(), ObjectArray< mavlink_statustext_t >::push(), readptr(), set_size(), space(), and update().
uint32_t ByteBuffer::size private
Definition at line 88 of file RingBuffer.h.
Referenced by advance(), available(), ByteBuffer(), commit(), get_size(), ObjectArray< mavlink_statustext_t >::ObjectArray(), ObjectArray< mavlink_statustext_t >::operator[](), peek(), ObjectArray< mavlink_statustext_t >::pop(), ObjectArray< mavlink_statustext_t >::push(), readptr(), reserve(), set_size(), space(), ObjectArray< mavlink_statustext_t >::space(), and update().
std::atomic<uint32_t> ByteBuffer::tail {0} private
Definition at line 91 of file RingBuffer.h.
Referenced by available(), clear(), commit(), empty(), readptr(), reserve(), set_size(), and space().
The documentation for this class was generated from the following files:
libraries/AP_HAL/utility/RingBuffer.h
libraries/AP_HAL/utility/RingBuffer.cpp