APM:Libraries: Linux::ToneAlarm_Raspilot Class Reference
Linux::ToneAlarm_Raspilot Class Reference
#include <ToneAlarm_Raspilot.h>
Public Member Functions
ToneAlarm_Raspilot ()
bool init () override
void stop () override
bool play () override
Public Member Functions inherited from Linux::ToneAlarm
ToneAlarm ()
void set_tune (uint8_t tone)
bool is_tune_comp ()
bool set_note ()
bool init_tune ()
Private Member Functions
void _set_pwm0_period (uint32_t time_us)
void _set_pwm0_duty (uint8_t percent)
Private Attributes
volatile uint32_t * _pwm
volatile uint32_t * _clk
Additional Inherited Members
Protected Attributes inherited from Linux::ToneAlarm
bool tune_comp
bool tune_changed
uint8_t default_oct
uint8_t default_dur
uint16_t bpm
uint16_t wholenote
uint16_t cur_note
uint16_t duration
int32_t prev_tune_num
uint32_t prev_time
int8_t tune_num
uint8_t tune_pos
Static Protected Attributes inherited from Linux::ToneAlarm
static const char * tune [TONE_NUMBER_OF_TUNES]
static bool tune_repeat [TONE_NUMBER_OF_TUNES] = {false,true,false,false,false,false,true,true,false,false,false}
Detailed Description
Definition at line 9 of file ToneAlarm_Raspilot.h.
Constructor & Destructor Documentation
ToneAlarm_Raspilot::ToneAlarm_Raspilot ()
Definition at line 44 of file ToneAlarm_Raspilot.cpp.
Member Function Documentation
void ToneAlarm_Raspilot::_set_pwm0_duty (uint8_t percent) private
Definition at line 181 of file ToneAlarm_Raspilot.cpp.
Referenced by _set_pwm0_period(), play(), and stop().
void ToneAlarm_Raspilot::_set_pwm0_period (uint32_t time_us) private
Definition at line 146 of file ToneAlarm_Raspilot.cpp.
Referenced by play().
bool ToneAlarm_Raspilot::init (void) override virtual
Reimplemented from Linux::ToneAlarm.
Definition at line 51 of file ToneAlarm_Raspilot.cpp.
Referenced by Linux::Util::toneAlarm_init().
bool ToneAlarm_Raspilot::play () override virtual
Reimplemented from Linux::ToneAlarm.
Definition at line 113 of file ToneAlarm_Raspilot.cpp.
Referenced by Linux::Util::_toneAlarm_timer_tick().
void ToneAlarm_Raspilot::stop () override virtual
Reimplemented from Linux::ToneAlarm.
Definition at line 108 of file ToneAlarm_Raspilot.cpp.
Referenced by play().
Member Data Documentation
volatile uint32_t* Linux::ToneAlarm_Raspilot::_clk private
Definition at line 21 of file ToneAlarm_Raspilot.h.
Referenced by _set_pwm0_period(), and init().
volatile uint32_t* Linux::ToneAlarm_Raspilot::_pwm private
Definition at line 20 of file ToneAlarm_Raspilot.h.
Referenced by _set_pwm0_duty(), _set_pwm0_period(), and init().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/ToneAlarm_Raspilot.h
libraries/AP_HAL_Linux/ToneAlarm_Raspilot.cpp