APM:Libraries: DFMessageWriter Class Reference
DFMessageWriter Class Reference abstract
#include <DFMessageWriter.h>
Public Member Functions
virtual void reset ()=0
virtual void process ()=0
virtual bool finished ()
virtual void set_dataflash_backend (class DataFlash_Backend *backend)
Protected Attributes
bool _finished = false
DataFlash_Backend * _dataflash_backend = nullptr
Detailed Description
Definition at line 7 of file DFMessageWriter.h.
Member Function Documentation
virtual bool DFMessageWriter::finished () inline virtual
Definition at line 12 of file DFMessageWriter.h.
Referenced by DataFlash_Backend::WriteMoreStartupMessages(), and DataFlash_MAVLink::WritePrioritisedBlock().
virtual void DFMessageWriter::process () pure virtual
Implemented in DFMessageWriter_DFLogStart, DFMessageWriter_WriteEntireMission, and DFMessageWriter_WriteSysInfo.
Referenced by DFMessageWriter_WriteSysInfo::DFMessageWriter_WriteSysInfo(), and DFMessageWriter_DFLogStart::set_dataflash_backend().
void DFMessageWriter::reset () pure virtual
Implemented in DFMessageWriter_DFLogStart, DFMessageWriter_WriteEntireMission, and DFMessageWriter_WriteSysInfo.
Definition at line 10 of file DFMessageWriter.cpp.
Referenced by DFMessageWriter_WriteSysInfo::DFMessageWriter_WriteSysInfo(), DFMessageWriter_WriteSysInfo::reset(), DFMessageWriter_WriteEntireMission::reset(), DFMessageWriter_DFLogStart::reset(), and DFMessageWriter_DFLogStart::set_dataflash_backend().
virtual void DFMessageWriter::set_dataflash_backend (class DataFlash_Backend * backend) inline virtual
Reimplemented in DFMessageWriter_DFLogStart.
Definition at line 14 of file DFMessageWriter.h.
Referenced by DataFlash_Backend::Log_Write_EntireMission(), and DFMessageWriter_DFLogStart::set_dataflash_backend().
Member Data Documentation
DataFlash_Backend* DFMessageWriter::_dataflash_backend = nullptr protected
Definition at line 20 of file DFMessageWriter.h.
Referenced by DFMessageWriter_WriteSysInfo::process(), DFMessageWriter_WriteEntireMission::process(), DFMessageWriter_DFLogStart::process(), and set_dataflash_backend().
bool DFMessageWriter::_finished = false protected
Definition at line 19 of file DFMessageWriter.h.
Referenced by finished(), DFMessageWriter_WriteSysInfo::process(), DFMessageWriter_WriteEntireMission::process(), DFMessageWriter_DFLogStart::process(), and reset().
The documentation for this class was generated from the following files:
libraries/DataFlash/DFMessageWriter.h
libraries/DataFlash/DFMessageWriter.cpp