APM:Libraries: AP_Avoidance Class Reference
AP_Avoidance Class Reference abstract
#include <AP_Avoidance.h>
Classes
class Obstacle
Public Member Functions
AP_Avoidance (AP_AHRS &ahrs, class AP_ADSB &adsb)
void add_obstacle (uint32_t obstacle_timestamp_ms, const MAV_COLLISION_SRC src, uint32_t src_id, const Location &loc, const Vector3f &vel_ned)
void add_obstacle (uint32_t obstacle_timestamp_ms, const MAV_COLLISION_SRC src, uint32_t src_id, const Location &loc, float cog, float hspeed, float vspeed)
void update ()
void enable ()
void disable ()
MAV_COLLISION_THREAT_LEVEL current_threat_level () const
void handle_msg (const mavlink_message_t &msg)
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Protected Member Functions
void handle_avoidance_local (AP_Avoidance::Obstacle *threat)
virtual MAV_COLLISION_ACTION handle_avoidance (const AP_Avoidance::Obstacle *obstacle, MAV_COLLISION_ACTION requested_action)=0
virtual void handle_recovery (uint8_t recovery_action)=0
void handle_threat_gcs_notify (AP_Avoidance::Obstacle *threat)
AP_Avoidance::Obstacle * most_serious_threat ()
MAV_COLLISION_ACTION mav_avoidance_action ()
bool get_destination_perpendicular (const AP_Avoidance::Obstacle *obstacle, Vector3f &newdest_neu, const float wp_speed_xy, const float wp_speed_z, const uint8_t _minimum_avoid_height)
bool get_vector_perpendicular (const AP_Avoidance::Obstacle *obstacle, Vector3f &vec_neu)
Static Protected Member Functions
static Vector3f perpendicular_xyz (const Location &p1, const Vector3f &v1, const Location &p2)
static Vector2f perpendicular_xy (const Location &p1, const Vector3f &v1, const Location &p2)
Protected Attributes
uint32_t _last_state_change_ms = 0
MAV_COLLISION_THREAT_LEVEL _threat_level = MAV_COLLISION_THREAT_LEVEL_NONE
uint32_t _gcs_cleared_messages_first_sent
const AP_AHRS & _ahrs
Static Protected Attributes
static const uint8_t _gcs_cleared_messages_duration = 5
Private Member Functions
bool check_startup ()
void init ()
void deinit ()
uint32_t src_id_for_adsb_vehicle (AP_ADSB::adsb_vehicle_t vehicle) const
void check_for_threats ()
void update_threat_level (const Location &my_loc, const Vector3f &my_vel, AP_Avoidance::Obstacle &obstacle)
void get_adsb_samples ()
bool obstacle_is_more_serious_threat (const AP_Avoidance::Obstacle &obstacle) const
Private Attributes
const uint32_t MAX_OBSTACLE_AGE_MS = 5000
const uint8_t _low_velocity_threshold = 1
AP_Avoidance::Obstacle * _obstacles
uint8_t _obstacles_allocated
uint8_t _obstacle_count
int8_t _current_most_serious_threat
MAV_COLLISION_ACTION _latest_action = MAV_COLLISION_ACTION_NONE
class AP_ADSB & _adsb
AP_Int8 _enabled
AP_Int8 _obstacles_max
AP_Int8 _fail_action
AP_Int8 _fail_recovery
AP_Int8 _fail_time_horizon
AP_Int16 _fail_distance_xy
AP_Int16 _fail_distance_z
AP_Int8 _warn_action
AP_Int8 _warn_time_horizon
AP_Float _warn_distance_xy
AP_Float _warn_distance_z
Static Private Attributes
static const uint8_t _gcs_notify_interval = 1
Detailed Description
Definition at line 41 of file AP_Avoidance.h.
Constructor & Destructor Documentation
AP_Avoidance::AP_Avoidance (AP_AHRS & ahrs, class AP_ADSB & adsb)
Definition at line 121 of file AP_Avoidance.cpp.
Member Function Documentation
void AP_Avoidance::add_obstacle (uint32_t obstacle_timestamp_ms, const MAV_COLLISION_SRC src, uint32_t src_id, const Location & loc, const Vector3f & vel_ned)
Definition at line 183 of file AP_Avoidance.cpp.
Referenced by add_obstacle(), get_adsb_samples(), and handle_msg().
void AP_Avoidance::add_obstacle (uint32_t obstacle_timestamp_ms, const MAV_COLLISION_SRC src, uint32_t src_id, const Location & loc, float cog, float hspeed, float vspeed)
Definition at line 230 of file AP_Avoidance.cpp.
void AP_Avoidance::check_for_threats () private
Definition at line 428 of file AP_Avoidance.cpp.
Referenced by update().
bool AP_Avoidance::check_startup () private
Definition at line 167 of file AP_Avoidance.cpp.
Referenced by add_obstacle(), handle_msg(), and update().
MAV_COLLISION_THREAT_LEVEL AP_Avoidance::current_threat_level () const
Definition at line 375 of file AP_Avoidance.cpp.
Referenced by disable().
void AP_Avoidance::deinit (void) private
Definition at line 156 of file AP_Avoidance.cpp.
Referenced by check_startup().
void AP_Avoidance::disable (void) inline
Definition at line 87 of file AP_Avoidance.h.
void AP_Avoidance::enable () inline
Definition at line 86 of file AP_Avoidance.h.
void AP_Avoidance::get_adsb_samples () private
Definition at line 252 of file AP_Avoidance.cpp.
Referenced by update().
bool AP_Avoidance::get_destination_perpendicular (const AP_Avoidance::Obstacle * obstacle, Vector3f & newdest_neu, const float wp_speed_xy, const float wp_speed_z, const uint8_t _minimum_avoid_height) protected
Referenced by mav_avoidance_action().
bool AP_Avoidance::get_vector_perpendicular (const AP_Avoidance::Obstacle * obstacle, Vector3f & vec_neu) protected
Definition at line 577 of file AP_Avoidance.cpp.
Referenced by mav_avoidance_action().
virtual MAV_COLLISION_ACTION AP_Avoidance::handle_avoidance (const AP_Avoidance::Obstacle * obstacle, MAV_COLLISION_ACTION requested_action) protected pure virtual
Referenced by handle_avoidance_local().
void AP_Avoidance::handle_avoidance_local (AP_Avoidance::Obstacle * threat) protected
Definition at line 505 of file AP_Avoidance.cpp.
Referenced by update().
void AP_Avoidance::handle_msg (const mavlink_message_t & msg)
Definition at line 541 of file AP_Avoidance.cpp.
Referenced by disable().
virtual void AP_Avoidance::handle_recovery (uint8_t recovery_action) protected pure virtual
Referenced by deinit(), and handle_avoidance_local().
void AP_Avoidance::handle_threat_gcs_notify (AP_Avoidance::Obstacle * threat) protected
Definition at line 385 of file AP_Avoidance.cpp.
Referenced by update().
void AP_Avoidance::init (void) private
Definition at line 131 of file AP_Avoidance.cpp.
Referenced by check_startup().
MAV_COLLISION_ACTION AP_Avoidance::mav_avoidance_action () inline protected
Definition at line 125 of file AP_Avoidance.h.
Referenced by handle_threat_gcs_notify().
AP_Avoidance::Obstacle * AP_Avoidance::most_serious_threat () protected
Definition at line 476 of file AP_Avoidance.cpp.
Referenced by update().
bool AP_Avoidance::obstacle_is_more_serious_threat (const AP_Avoidance::Obstacle & obstacle) const private
Definition at line 410 of file AP_Avoidance.cpp.
Referenced by check_for_threats().
Vector2f AP_Avoidance::perpendicular_xy (const Location & p1, const Vector3f & v1, const Location & p2) static protected
Definition at line 629 of file AP_Avoidance.cpp.
Referenced by mav_avoidance_action().
Vector3f AP_Avoidance::perpendicular_xyz (const Location & p1, const Vector3f & v1, const Location & p2) static protected
Definition at line 618 of file AP_Avoidance.cpp.
Referenced by get_vector_perpendicular(), and mav_avoidance_action().
uint32_t AP_Avoidance::src_id_for_adsb_vehicle (AP_ADSB::adsb_vehicle_t vehicle) const private
Definition at line 246 of file AP_Avoidance.cpp.
Referenced by get_adsb_samples().
void AP_Avoidance::update (void)
Definition at line 486 of file AP_Avoidance.cpp.
void AP_Avoidance::update_threat_level (const Location & my_loc, const Vector3f & my_vel, AP_Avoidance::Obstacle & obstacle) private
Definition at line 321 of file AP_Avoidance.cpp.
Referenced by check_for_threats().
Member Data Documentation
class AP_ADSB& AP_Avoidance::_adsb private
Definition at line 183 of file AP_Avoidance.h.
Referenced by get_adsb_samples(), and update().
const AP_AHRS& AP_Avoidance::_ahrs protected
Definition at line 139 of file AP_Avoidance.h.
Referenced by check_for_threats(), and get_vector_perpendicular().
int8_t AP_Avoidance::_current_most_serious_threat private
Definition at line 179 of file AP_Avoidance.h.
Referenced by check_for_threats(), current_threat_level(), init(), most_serious_threat(), and obstacle_is_more_serious_threat().
AP_Int8 AP_Avoidance::_enabled private
Definition at line 186 of file AP_Avoidance.h.
Referenced by check_startup(), disable(), enable(), and init().
AP_Int8 AP_Avoidance::_fail_action private
Definition at line 189 of file AP_Avoidance.h.
Referenced by handle_avoidance_local().
AP_Int16 AP_Avoidance::_fail_distance_xy private
Definition at line 192 of file AP_Avoidance.h.
Referenced by update_threat_level().
AP_Int16 AP_Avoidance::_fail_distance_z private
Definition at line 193 of file AP_Avoidance.h.
Referenced by update_threat_level().
AP_Int8 AP_Avoidance::_fail_recovery private
Definition at line 190 of file AP_Avoidance.h.
Referenced by handle_avoidance_local().
AP_Int8 AP_Avoidance::_fail_time_horizon private
Definition at line 191 of file AP_Avoidance.h.
Referenced by update_threat_level().
const uint8_t AP_Avoidance::_gcs_cleared_messages_duration = 5 static protected
Definition at line 116 of file AP_Avoidance.h.
Referenced by handle_threat_gcs_notify().
uint32_t AP_Avoidance::_gcs_cleared_messages_first_sent protected
Definition at line 117 of file AP_Avoidance.h.
Referenced by handle_threat_gcs_notify(), and init().
const uint8_t AP_Avoidance::_gcs_notify_interval = 1 static private
Definition at line 145 of file AP_Avoidance.h.
Referenced by handle_threat_gcs_notify().
uint32_t AP_Avoidance::_last_state_change_ms = 0 protected
Definition at line 111 of file AP_Avoidance.h.
Referenced by handle_avoidance_local(), and init().
MAV_COLLISION_ACTION AP_Avoidance::_latest_action = MAV_COLLISION_ACTION_NONE private
Definition at line 180 of file AP_Avoidance.h.
Referenced by handle_avoidance_local(), and mav_avoidance_action().
const uint8_t AP_Avoidance::_low_velocity_threshold = 1 private
Definition at line 149 of file AP_Avoidance.h.
Referenced by get_vector_perpendicular().
uint8_t AP_Avoidance::_obstacle_count private
Definition at line 178 of file AP_Avoidance.h.
Referenced by add_obstacle(), check_for_threats(), deinit(), and init().
AP_Avoidance::Obstacle* AP_Avoidance::_obstacles private
Definition at line 176 of file AP_Avoidance.h.
Referenced by add_obstacle(), check_for_threats(), check_startup(), current_threat_level(), deinit(), init(), most_serious_threat(), and obstacle_is_more_serious_threat().
uint8_t AP_Avoidance::_obstacles_allocated private
Definition at line 177 of file AP_Avoidance.h.
Referenced by add_obstacle(), deinit(), and init().
AP_Int8 AP_Avoidance::_obstacles_max private
Definition at line 187 of file AP_Avoidance.h.
Referenced by init().
MAV_COLLISION_THREAT_LEVEL AP_Avoidance::_threat_level = MAV_COLLISION_THREAT_LEVEL_NONE protected
Definition at line 112 of file AP_Avoidance.h.
Referenced by handle_avoidance_local(), and init().
AP_Int8 AP_Avoidance::_warn_action private
Definition at line 195 of file AP_Avoidance.h.
AP_Float AP_Avoidance::_warn_distance_xy private
Definition at line 197 of file AP_Avoidance.h.
Referenced by update_threat_level().
AP_Float AP_Avoidance::_warn_distance_z private
Definition at line 198 of file AP_Avoidance.h.
Referenced by update_threat_level().
AP_Int8 AP_Avoidance::_warn_time_horizon private
Definition at line 196 of file AP_Avoidance.h.
Referenced by update_threat_level().
const uint32_t AP_Avoidance::MAX_OBSTACLE_AGE_MS = 5000 private
Definition at line 144 of file AP_Avoidance.h.
Referenced by check_for_threats(), and update_threat_level().
const AP_Param::GroupInfo AP_Avoidance::var_info static
Definition at line 96 of file AP_Avoidance.h.
Referenced by AP_Avoidance().
The documentation for this class was generated from the following files:
libraries/AP_Avoidance/AP_Avoidance.h
libraries/AP_Avoidance/AP_Avoidance.cpp