APM:Libraries: Display Class Reference
Display Class Reference
#include <Display.h>
Public Member Functions
bool init (void)
void update ()
Public Member Functions inherited from NotifyDevice
virtual ~NotifyDevice ()
virtual void handle_led_control (mavlink_message_t *msg)
virtual void handle_play_tune (mavlink_message_t *msg)
Private Member Functions
void draw_char (uint16_t x, uint16_t y, const char c)
void draw_text (uint16_t x, uint16_t y, const char *c)
void update_all ()
void update_arm (uint8_t r)
void update_prearm (uint8_t r)
void update_gps (uint8_t r)
void update_gps_sats (uint8_t r)
void update_ekf (uint8_t r)
void update_battery (uint8_t r)
void update_mode (uint8_t r)
void update_text (uint8_t r)
void update_text_empty (uint8_t r)
Private Attributes
Display_Backend * _driver
bool _healthy
uint8_t _mstartpos
uint8_t _movedelay
uint8_t _screenpage
const uint16_t _send_text_valid_millis = 20000
Friends
class Display_Backend
Additional Inherited Members
Public Attributes inherited from NotifyDevice
const AP_Notify * pNotify
Detailed Description
Definition at line 12 of file Display.h.
Member Function Documentation
void Display::draw_char (uint16_t x, uint16_t y, const char c) private
Definition at line 427 of file Display.cpp.
Referenced by draw_text(), and update_gps_sats().
void Display::draw_text (uint16_t x, uint16_t y, const char * c) private
Definition at line 408 of file Display.cpp.
Referenced by update_arm(), update_battery(), update_ekf(), update_gps(), update_gps_sats(), update_mode(), update_prearm(), update_text(), and update_text_empty().
bool Display::init (void) virtual
Implements NotifyDevice.
Definition at line 320 of file Display.cpp.
void Display::update (void) virtual
Implements NotifyDevice.
Definition at line 363 of file Display.cpp.
void Display::update_all () private
Definition at line 397 of file Display.cpp.
Referenced by init(), and update().
void Display::update_arm (uint8_t r) private
Definition at line 450 of file Display.cpp.
Referenced by update().
void Display::update_battery (uint8_t r) private
Definition at line 519 of file Display.cpp.
Referenced by update_all().
void Display::update_ekf (uint8_t r) private
Definition at line 510 of file Display.cpp.
Referenced by update_all().
void Display::update_gps (uint8_t r) private
Definition at line 468 of file Display.cpp.
Referenced by update_all().
void Display::update_gps_sats (uint8_t r) private
Definition at line 503 of file Display.cpp.
void Display::update_mode (uint8_t r) private
Definition at line 526 of file Display.cpp.
Referenced by update_all().
void Display::update_prearm (uint8_t r) private
Definition at line 459 of file Display.cpp.
Referenced by update_all().
void Display::update_text (uint8_t r) private
Definition at line 544 of file Display.cpp.
Referenced by update_all().
void Display::update_text_empty (uint8_t r) private
Definition at line 535 of file Display.cpp.
Referenced by update_text().
Friends And Related Function Documentation
friend class Display_Backend friend
Definition at line 14 of file Display.h.
Member Data Documentation
Display_Backend* Display::_driver private
Definition at line 33 of file Display.h.
Referenced by draw_char(), init(), and update().
bool Display::_healthy private
Definition at line 35 of file Display.h.
Referenced by init(), and update().
uint8_t Display::_movedelay private
Definition at line 38 of file Display.h.
Referenced by init(), update_text(), and update_text_empty().
uint8_t Display::_mstartpos private
Definition at line 37 of file Display.h.
Referenced by init(), update_text(), and update_text_empty().
uint8_t Display::_screenpage private
Definition at line 39 of file Display.h.
Referenced by update().
const uint16_t Display::_send_text_valid_millis = 20000 private
Definition at line 42 of file Display.h.
Referenced by update_text().
The documentation for this class was generated from the following files:
libraries/AP_Notify/Display.h
libraries/AP_Notify/Display.cpp