APM:Libraries: AP_HAL::Device Class Reference
AP_HAL::Device Class Reference abstract
#include <Device.h>
Classes
struct checkreg
union DeviceId
struct DeviceStructure
Public Types
enum BusType { BUS_TYPE_UNKNOWN = 0, BUS_TYPE_I2C = 1, BUS_TYPE_SPI = 2, BUS_TYPE_UAVCAN = 3 }
enum Speed { SPEED_HIGH, SPEED_LOW }
typedef void * PeriodicHandle
Public Member Functions
FUNCTOR_TYPEDEF (PeriodicCb, void)
Device (enum BusType type)
enum BusType bus_type (void) const
uint8_t bus_num (void) const
uint32_t get_bus_id (void) const
uint8_t get_bus_address (void) const
void set_device_type (uint8_t devtype)
virtual ~Device ()
virtual bool set_speed (Speed speed)=0
virtual bool transfer (const uint8_t *send, uint32_t send_len, uint8_t *recv, uint32_t recv_len)=0
bool read_registers (uint8_t first_reg, uint8_t *recv, uint32_t recv_len)
bool write_register (uint8_t reg, uint8_t val, bool checked=false)
void set_checked_register (uint8_t reg, uint8_t val)
bool setup_checked_registers (uint8_t num_regs, uint8_t frequency=10)
bool check_next_register (void)
bool read (uint8_t *recv, uint32_t recv_len)
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual PeriodicHandle register_periodic_callback (uint32_t period_usec, PeriodicCb)=0
virtual bool adjust_periodic_callback (PeriodicHandle h, uint32_t period_usec)=0
virtual bool unregister_callback (PeriodicHandle h)
virtual bool set_chip_select (bool set)
void set_read_flag (uint8_t flag)
uint32_t get_bus_id_devtype (uint8_t devtype)
virtual void set_retries (uint8_t retries)
Static Public Member Functions
static uint32_t make_bus_id (enum BusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype)
static uint32_t change_bus_id (uint32_t old_id, uint8_t devtype)
Protected Member Functions
void set_device_address (uint8_t address)
void set_device_bus (uint8_t bus)
Protected Attributes
uint8_t _read_flag = 0
union DeviceId _bus_id
Private Attributes
struct {
uint8_t n_allocated
uint8_t n_set
uint8_t next
uint8_t frequency
uint8_t counter
struct checkreg * regs
} _checked
Detailed Description
Definition at line 27 of file Device.h.
Member Typedef Documentation
typedef void* AP_HAL::Device::PeriodicHandle
Definition at line 42 of file Device.h.
Member Enumeration Documentation
enum AP_HAL::Device::BusType
Enumerator
BUS_TYPE_UNKNOWN
BUS_TYPE_I2C
BUS_TYPE_SPI
BUS_TYPE_UAVCAN
Definition at line 29 of file Device.h.
enum AP_HAL::Device::Speed
Enumerator
SPEED_HIGH
SPEED_LOW
Definition at line 36 of file Device.h.
Constructor & Destructor Documentation
AP_HAL::Device::Device (enum BusType type) inline
Definition at line 44 of file Device.h.
virtual AP_HAL::Device::~Device () inline virtual
Definition at line 75 of file Device.h.
Member Function Documentation
virtual bool AP_HAL::Device::adjust_periodic_callback (PeriodicHandle h, uint32_t period_usec) pure virtual
Implemented in PX4::SPIDevice, Empty::I2CDevice, Linux::I2CDevice, VRBRAIN::I2CDevice, AP_HAL::I2CDevice, PX4::I2CDevice, Linux::SPIDevice, and AP_HAL::SPIDevice.
Referenced by read(), and AP_Compass_IST8310::timer().
uint8_t AP_HAL::Device::bus_num (void) const inline
Definition at line 55 of file Device.h.
Referenced by AP_Baro_MS56XX::_init(), PX4::DeviceBus::bus_thread(), and AP_Compass_IST8310::init().
enum BusType AP_HAL::Device::bus_type (void) const inline
Definition at line 50 of file Device.h.
Referenced by AP_InertialSensor_Invensense::_hardware_init(), AP_InertialSensor_Invensense::_has_auxiliary_bus(), AP_Baro_BMP280::_init(), AP_InertialSensor_Invensense::_set_filter_register(), PX4::DeviceBus::bus_thread(), AP_Compass_LIS3MDL::init(), and make_bus_id().
static uint32_t AP_HAL::Device::change_bus_id (uint32_t old_id, uint8_t devtype) inline static
return a new bus ID for the same bus connection but a new device type. This is used for auxillary bus connections
Definition at line 230 of file Device.h.
Referenced by get_bus_id_devtype(), and AuxiliaryBus::set_device_type().
bool AP_HAL::Device::check_next_register (void)
check next register value for correctness. Return false if value is incorrect or register checking has not been setup
Definition at line 85 of file Device.cpp.
Referenced by AP_InertialSensor_LSM9DS0::_poll_data(), AP_InertialSensor_Invensense::_read_fifo(), AP_RangeFinder_PulsedLightLRF::timer(), AP_Compass_AK09916::timer(), AP_Compass_LIS3MDL::timer(), and write_register().
AP_HAL::Device::FUNCTOR_TYPEDEF (PeriodicCb , void)
uint8_t AP_HAL::Device::get_bus_address (void) const inline
Definition at line 65 of file Device.h.
Referenced by AP_Baro_MS56XX::_init(), and AP_Compass_IST8310::init().
uint32_t AP_HAL::Device::get_bus_id (void) const inline
Definition at line 60 of file Device.h.
Referenced by check_next_register(), AP_InertialSensor_Invensense::get_auxiliary_bus(), get_bus_id_devtype(), AP_Compass_LSM303D::init(), AP_Compass_LSM9DS1::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Compass_BMM150::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), AP_Compass_LIS3MDL::init(), and set_checked_register().
uint32_t AP_HAL::Device::get_bus_id_devtype (uint8_t devtype) inline
return bus ID with a new devtype
Definition at line 240 of file Device.h.
Referenced by AP_InertialSensor_LSM9DS0::start(), AP_InertialSensor_L3G4200D::start(), AP_InertialSensor_BMI160::start(), and AP_InertialSensor_Invensense::start().
virtual AP_HAL::Semaphore* AP_HAL::Device::get_semaphore () pure virtual
Implemented in PX4::SPIDevice, VRBRAIN::I2CDevice, Empty::I2CDevice, Linux::I2CDevice, PX4::I2CDevice, Empty::SPIDevice, AP_HAL::I2CDevice, Linux::SPIDevice, and AP_HAL::SPIDevice.
Referenced by AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_Baro_BMP280::_init(), AP_Baro_MS56XX::_init(), GCS_MAVLINK::handle_device_op_read(), GCS_MAVLINK::handle_device_op_write(), Display_SH1106_I2C::hw_init(), Display_SSD1306_I2C::hw_init(), TSYS01::init(), AP_Compass_LSM9DS1::init(), AP_Compass_BMM150::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), AP_Compass_LIS3MDL::init(), read(), AP_OpticalFlow_PX4Flow::scan_buses(), AP_InertialSensor_BMI160::start(), and AP_InertialSensor_Invensense::start().
static uint32_t AP_HAL::Device::make_bus_id (enum BusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype) inline static
make a bus id given bus type, bus number, bus address and device type This is for use by devices that do not use one of the standard HAL Device types, such as UAVCAN devices
Definition at line 217 of file Device.h.
bool AP_HAL::Device::read (uint8_t * recv, uint32_t recv_len) inline
Wrapper function over transfer() to read a sequence of bytes from device. No value is written, differently from the read_registers() method and hence doesn't include the read flag set by set_read_flag()
Definition at line 150 of file Device.h.
Referenced by AP_RangeFinder_LightWareI2C::get_reading().
bool AP_HAL::Device::read_registers (uint8_t first_reg, uint8_t * recv, uint32_t recv_len) inline
Wrapper function over transfer() to read recv_len registers, starting by first_reg, into the array pointed by recv. The read flag passed to set_read_flag(uint8_t) is ORed with first_reg before performing the transfer.
Return: true on a successful transfer, false on failure.
Definition at line 107 of file Device.h.
Referenced by AP_InertialSensor_L3G4200D::_accumulate(), AP_Compass_LSM303D::_block_read(), AP_Compass_LSM9DS1::_block_read(), AP_InertialSensor_Invensense::_block_read(), AP_InertialSensor_BMI160::_check_err_reg(), Linux::RCOutput_Bebop::_get_info(), AP_InertialSensor_BMI160::_hardware_init(), AP_Baro_BMP280::_init(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_Compass_BMM150::_load_trim_values(), AP_InertialSensor_BMI160::_read_fifo(), AP_Baro_BMP085::_read_pressure(), AP_Baro_BMP085::_read_temp(), AP_Compass_LSM303D::_register_read(), AP_Compass_LSM9DS1::_register_read(), AP_InertialSensor_Invensense::_register_read(), AP_InertialSensor_LSM9DS0::_register_read_g(), AP_InertialSensor_LSM9DS0::_register_read_xm(), AP_Baro_BMP280::_timer(), AP_ADC_ADS1115::_update(), AP_Compass_BMM150::_update(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_AK8963_BusDriver_HALDevice::block_read(), check_next_register(), GCS_MAVLINK::handle_device_op_read(), AP_RangeFinder_trone::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Compass_BMM150::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), AP_Compass_LIS3MDL::init(), AP_Airspeed_MS5525::read_adc(), AP_BattMonitor_SMBus_Solo::read_block(), AP_BattMonitor_SMBus_Maxell::read_block(), Linux::RCOutput_Bebop::read_obs_data(), AP_Airspeed_MS5525::read_prom(), AP_BattMonitor_SMBus_Solo::read_word(), AP_BattMonitor_SMBus_Maxell::read_word(), AP_AK8963_BusDriver_HALDevice::register_read(), AP_OpticalFlow_PX4Flow::scan_buses(), AP_RangeFinder_PulsedLightLRF::timer(), AP_Compass_IST8310::timer(), AP_OpticalFlow_PX4Flow::timer(), AP_Compass_AK09916::timer(), and AP_Compass_LIS3MDL::timer().
virtual PeriodicHandle AP_HAL::Device::register_periodic_callback (uint32_t period_usec, PeriodicCb) pure virtual
Referenced by AP_Baro_BMP280::_init(), AP_Baro_MS56XX::_init(), Display_SH1106_I2C::hw_init(), Display_SSD1306_I2C::hw_init(), AP_IRLock_I2C::init(), TSYS01::init(), AP_Compass_LSM9DS1::init(), AP_Compass_LSM303D::init(), AP_Compass_BMM150::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), AP_Compass_LIS3MDL::init(), read(), AP_OpticalFlow_PX4Flow::setup_sensor(), AP_InertialSensor_BMI160::start(), and AP_InertialSensor_Invensense::start().
void AP_HAL::Device::set_checked_register (uint8_t reg, uint8_t val)
set a value for a checked register
Definition at line 60 of file Device.cpp.
Referenced by write_register().
virtual bool AP_HAL::Device::set_chip_select (bool set) inline virtual
Reimplemented in PX4::SPIDevice.
Definition at line 199 of file Device.h.
Referenced by AP_InertialSensor_Invensense::_read_fifo(), AP_OpticalFlow_Pixart::motion_burst(), AP_OpticalFlow_Pixart::reg_read(), AP_OpticalFlow_Pixart::reg_write(), and AP_OpticalFlow_Pixart::srom_download().
void AP_HAL::Device::set_device_address (uint8_t address) inline protected
Definition at line 271 of file Device.h.
Referenced by PX4::I2CDevice::I2CDevice(), Linux::I2CDevice::I2CDevice(), Linux::SPIDevice::SPIDevice(), and PX4::SPIDevice::SPIDevice().
void AP_HAL::Device::set_device_bus (uint8_t bus) inline protected
Definition at line 276 of file Device.h.
Referenced by PX4::I2CDevice::I2CDevice(), Linux::I2CDevice::I2CDevice(), Linux::SPIDevice::SPIDevice(), and PX4::SPIDevice::SPIDevice().
void AP_HAL::Device::set_device_type (uint8_t devtype) inline
Definition at line 70 of file Device.h.
Referenced by AP_Compass_LSM303D::init(), AP_Compass_LSM9DS1::init(), AP_Compass_BMM150::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), and AP_Compass_LIS3MDL::init().
void AP_HAL::Device::set_read_flag (uint8_t flag) inline
Some devices connected on the I2C or SPI bus require a bit to be set on the register address in order to perform a read operation. This sets a flag to be used by read_registers(). The flag's default value is zero.
Definition at line 206 of file Device.h.
Referenced by AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_BMI160::_init(), AP_Compass_LIS3MDL::init(), and AP_InertialSensor_Invensense::probe().
virtual void AP_HAL::Device::set_retries (uint8_t retries) inline virtual
Reimplemented in Linux::I2CDevice, PX4::I2CDevice, VRBRAIN::I2CDevice, and Empty::I2CDevice.
Definition at line 245 of file Device.h.
Referenced by AP_Baro_MS56XX::_init(), TSYS01::init(), AP_RangeFinder_trone::init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Airspeed_MS5525::init(), AP_Airspeed_MS4525::init(), AP_Compass_IST8310::init(), and AP_Compass_LIS3MDL::init().
virtual bool AP_HAL::Device::set_speed (Speed speed) pure virtual
Implemented in PX4::SPIDevice, Empty::I2CDevice, AP_HAL::I2CDevice, Empty::SPIDevice, Linux::SPIDevice, and AP_HAL::SPIDevice.
Referenced by AP_Compass_LSM9DS1::_check_id(), AP_InertialSensor_Invensense::_fifo_reset(), AP_Compass_LSM303D::_hardware_init(), AP_InertialSensor_BMI160::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_Baro_BMP280::_init(), AP_InertialSensor_Invensense::_read_fifo(), AP_InertialSensor_Invensense::start(), and ~Device().
bool AP_HAL::Device::setup_checked_registers (uint8_t num_regs, uint8_t frequency = 10)
setup for register value checking. Frequency is how often to check registers. If set to 10 then every 10th call to check_next_register will check a register
Definition at line 39 of file Device.cpp.
Referenced by AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_Invensense::_hardware_init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Compass_AK09916::init(), AP_Compass_LIS3MDL::init(), and write_register().
virtual bool AP_HAL::Device::transfer (const uint8_t * send, uint32_t send_len, uint8_t * recv, uint32_t recv_len) pure virtual
Implemented in PX4::SPIDevice, Linux::I2CDevice, PX4::I2CDevice, VRBRAIN::I2CDevice, Empty::I2CDevice, AP_HAL::I2CDevice, Empty::SPIDevice, Linux::SPIDevice, and AP_HAL::SPIDevice.
Referenced by TSYS01::_convert(), Linux::RCOutput_AeroIO::_hw_read(), Linux::RCOutput_AeroIO::_hw_write(), AP_Baro_MS56XX::_init(), TSYS01::_read_adc(), AP_Baro_MS56XX::_read_adc(), AP_InertialSensor_Invensense::_read_fifo(), TSYS01::_read_prom_word(), AP_Baro_MS56XX::_read_prom_word(), TSYS01::_reset(), Display_SSD1306_I2C::_timer(), Display_SH1106_I2C::_timer(), AP_Baro_MS56XX::_timer(), Display_SH1106_I2C::hw_init(), Display_SSD1306_I2C::hw_init(), read(), AP_IRLock_I2C::read_block(), read_registers(), AP_IRLock_I2C::sync_frame_start(), write_register(), and ~Device().
virtual bool AP_HAL::Device::unregister_callback (PeriodicHandle h) inline virtual
Definition at line 192 of file Device.h.
bool AP_HAL::Device::write_register (uint8_t reg, uint8_t val, bool checked = false) inline
Wrapper function over transfer() to write a byte to the register reg. The transfer is done by sending reg and val in that order.
Return: true on a successful transfer, false on failure.
Definition at line 119 of file Device.h.
Referenced by AP_Baro_BMP085::_cmd_read_pressure(), AP_Baro_BMP085::_cmd_read_temp(), AP_InertialSensor_BMI160::_configure_accel(), AP_InertialSensor_BMI160::_configure_fifo(), AP_InertialSensor_BMI160::_configure_gyro(), AP_InertialSensor_BMI160::_configure_int1_pin(), AP_InertialSensor_BMI160::_hardware_init(), AP_Baro_BMP280::_init(), AP_InertialSensor_L3G4200D::_init_sensor(), Linux::RCOutput_Bebop::_play_sound(), AP_InertialSensor_BMI160::_read_fifo(), AP_Compass_LSM303D::_register_write(), AP_Compass_LSM9DS1::_register_write(), AP_InertialSensor_Invensense::_register_write(), AP_InertialSensor_LSM9DS0::_register_write_g(), AP_InertialSensor_LSM9DS0::_register_write_xm(), Linux::RCOutput_Bebop::_toggle_gpio(), check_next_register(), GCS_MAVLINK::handle_device_op_write(), ToshibaLED_I2C::hw_init(), AP_RangeFinder_PulsedLightLRF::init(), AP_Compass_BMM150::init(), AP_Compass_IST8310::init(), AP_Compass_AK09916::init(), AP_Compass_LIS3MDL::init(), AP_AK8963_BusDriver_HALDevice::register_write(), Linux::RCOutput_PCA9685::set_freq(), AP_Compass_IST8310::start_conversion(), and AP_RangeFinder_PulsedLightLRF::timer().
Member Data Documentation
union DeviceId AP_HAL::Device::_bus_id protected
Definition at line 268 of file Device.h.
Referenced by bus_num(), bus_type(), Device(), get_bus_address(), get_bus_id(), set_device_address(), set_device_bus(), and set_device_type().
struct { ... } AP_HAL::Device::_checked
Referenced by check_next_register(), set_checked_register(), setup_checked_registers(), and ~Device().
uint8_t AP_HAL::Device::_read_flag = 0 protected
Definition at line 248 of file Device.h.
Referenced by read_registers(), Linux::I2CDevice::read_registers_multiple(), and set_read_flag().
uint8_t AP_HAL::Device::counter
Definition at line 291 of file Device.h.
uint8_t AP_HAL::Device::frequency
Definition at line 290 of file Device.h.
Referenced by setup_checked_registers(), and write_register().
uint8_t AP_HAL::Device::n_allocated
Definition at line 287 of file Device.h.
uint8_t AP_HAL::Device::n_set
Definition at line 288 of file Device.h.
uint8_t AP_HAL::Device::next
Definition at line 289 of file Device.h.
struct checkreg* AP_HAL::Device::regs
Definition at line 292 of file Device.h.
Referenced by set_checked_register().
The documentation for this class was generated from the following files:
libraries/AP_HAL/Device.h
libraries/AP_HAL/Device.cpp