APM:Libraries: QURT::RCInput Class Reference
QURT::RCInput Class Reference
#include <RCInput.h>
Public Member Functions
RCInput (const char *device_path)
void set_device_path (const char *path)
void init ()
bool new_input ()
uint8_t num_channels ()
uint16_t read (uint8_t ch)
uint8_t read (uint16_t *periods, uint8_t len)
bool set_overrides (int16_t *overrides, uint8_t len)
bool set_override (uint8_t channel, int16_t override)
void clear_overrides ()
void read_callback (char *buf, size_t size)
Public Member Functions inherited from AP_HAL::RCInput
virtual void teardown ()
virtual bool rc_bind (int dsmMode)
Static Public Member Functions
static RCInput * from (AP_HAL::RCInput *rcinput)
Private Member Functions
void add_dsm_input (const uint8_t *bytes, size_t nbytes)
Private Attributes
volatile bool new_rc_input
uint16_t _pwm_values [QURT_RC_INPUT_NUM_CHANNELS]
uint8_t _num_channels
uint16_t _override [QURT_RC_INPUT_NUM_CHANNELS]
const char * device_path
int32_t fd = -1
struct {
uint8_t frame [16]
uint8_t partial_frame_count
uint32_t last_input_ms
} dsm
Detailed Description
Definition at line 7 of file RCInput.h.
Constructor & Destructor Documentation
RCInput::RCInput (const char * device_path)
Definition at line 22 of file RCInput.cpp.
Member Function Documentation
void RCInput::add_dsm_input (const uint8_t * bytes, size_t nbytes) private
Definition at line 140 of file RCInput.cpp.
Referenced by read_callback().
void RCInput::clear_overrides () virtual
Implements AP_HAL::RCInput.
Definition at line 129 of file RCInput.cpp.
Referenced by set_device_path().
static RCInput* QURT::RCInput::from (AP_HAL::RCInput * rcinput) inline static
Definition at line 11 of file RCInput.h.
void RCInput::init () virtual
Call init from the platform hal instance init, so that both the type of the RCInput implementation and init argument (e.g. ISRRegistry) are known to the programmer. (It's too difficult to describe this dependency in the C++ type system.)
Implements AP_HAL::RCInput.
Definition at line 32 of file RCInput.cpp.
Referenced by HAL_QURT::run(), and set_device_path().
bool RCInput::new_input () virtual
Return true if there has been new input since the last call to new_input()
Implements AP_HAL::RCInput.
Definition at line 65 of file RCInput.cpp.
Referenced by set_device_path().
uint8_t RCInput::num_channels () virtual
Return the number of valid channels in the last read
Implements AP_HAL::RCInput.
Definition at line 74 of file RCInput.cpp.
Referenced by set_device_path().
uint16_t RCInput::read (uint8_t ch) virtual
Implements AP_HAL::RCInput.
Definition at line 79 of file RCInput.cpp.
Referenced by read(), and set_device_path().
uint8_t RCInput::read (uint16_t * periods, uint8_t len) virtual
Implements AP_HAL::RCInput.
Definition at line 90 of file RCInput.cpp.
void RCInput::read_callback (char * buf, size_t size)
Definition at line 60 of file RCInput.cpp.
Referenced by set_device_path().
void QURT::RCInput::set_device_path (const char * path) inline
Definition at line 15 of file RCInput.h.
Referenced by HAL_QURT::run().
bool RCInput::set_override (uint8_t channel, int16_t override) virtual
Implements AP_HAL::RCInput.
Definition at line 116 of file RCInput.cpp.
Referenced by set_device_path(), and set_overrides().
bool RCInput::set_overrides (int16_t * overrides, uint8_t len) virtual
Overrides: these are really grody and don't belong here but we need them at the moment to make the port work. case v of: v == -1 -> no change to this channel v == 0 -> do not override this channel v > 0 -> set v as override.
Implements AP_HAL::RCInput.
Definition at line 104 of file RCInput.cpp.
Referenced by set_device_path().
Member Data Documentation
uint8_t QURT::RCInput::_num_channels private
Definition at line 35 of file RCInput.h.
Referenced by add_dsm_input(), num_channels(), and read().
uint16_t QURT::RCInput::_override[QURT_RC_INPUT_NUM_CHANNELS] private
Definition at line 38 of file RCInput.h.
Referenced by clear_overrides(), read(), and set_override().
uint16_t QURT::RCInput::_pwm_values[QURT_RC_INPUT_NUM_CHANNELS] private
Definition at line 34 of file RCInput.h.
Referenced by add_dsm_input(), and read().
const char* QURT::RCInput::device_path private
Definition at line 43 of file RCInput.h.
Referenced by init().
struct { ... } QURT::RCInput::dsm
Referenced by add_dsm_input().
int32_t QURT::RCInput::fd = -1 private
Definition at line 44 of file RCInput.h.
Referenced by init().
uint8_t QURT::RCInput::frame[16]
Definition at line 48 of file RCInput.h.
uint32_t QURT::RCInput::last_input_ms
Definition at line 50 of file RCInput.h.
volatile bool QURT::RCInput::new_rc_input private
Definition at line 32 of file RCInput.h.
Referenced by add_dsm_input(), new_input(), and set_override().
uint8_t QURT::RCInput::partial_frame_count
Definition at line 49 of file RCInput.h.
The documentation for this class was generated from the following files:
libraries/AP_HAL_QURT/RCInput.h
libraries/AP_HAL_QURT/RCInput.cpp