APM:Libraries: AP_MotorsMatrix Class Reference
AP_MotorsMatrix Class Reference
#include <AP_MotorsMatrix.h>
Public Member Functions
AP_MotorsMatrix (uint16_t loop_rate, uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
Constructor.
void init (motor_frame_class frame_class, motor_frame_type frame_type)
void set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type)
void set_update_rate (uint16_t speed_hz)
void enable ()
void output_test (uint8_t motor_seq, int16_t pwm)
void output_to_motors ()
uint16_t get_motor_mask ()
Public Member Functions inherited from AP_MotorsMulticopter
AP_MotorsMulticopter (uint16_t loop_rate, uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
virtual void output ()
void output_min ()
void set_yaw_headroom (int16_t pwm)
void set_throttle_range (int16_t radio_min, int16_t radio_max)
void update_throttle_hover (float dt)
virtual float get_throttle_hover () const
void set_throttle_passthrough_for_esc_calibration (float throttle_input)
float get_lift_max ()
float get_batt_voltage_filt () const
float get_batt_resistance () const
float get_throttle_limit () const
float get_throttle_thrust_max () const
bool spool_up_complete () const
void output_motor_mask (float thrust, uint8_t mask)
int16_t get_pwm_output_min () const
int16_t get_pwm_output_max () const
FUNCTOR_TYPEDEF (thrust_compensation_fn_t, void, float *, uint8_t)
void set_thrust_compensation_callback (thrust_compensation_fn_t callback)
Public Member Functions inherited from AP_Motors
AP_Motors (uint16_t loop_rate, uint16_t speed_hz=AP_MOTORS_SPEED_DEFAULT)
bool initialised_ok () const
bool armed () const
void armed (bool arm)
void set_interlock (bool set)
bool get_interlock () const
void set_roll (float roll_in)
void set_pitch (float pitch_in)
void set_yaw (float yaw_in)
void set_throttle (float throttle_in)
void set_throttle_avg_max (float throttle_avg_max)
void set_throttle_filter_cutoff (float filt_hz)
void set_forward (float forward_in)
void set_lateral (float lateral_in)
float get_roll () const
float get_pitch () const
float get_yaw () const
float get_throttle () const
float get_throttle_bidirectional () const
float get_forward () const
float get_lateral () const
virtual void set_desired_spool_state (enum spool_up_down_desired spool)
enum spool_up_down_desired get_desired_spool_state (void) const
void set_voltage (float volts)
void set_current (float current)
void set_air_density_ratio (float ratio)
virtual void init (motor_frame_class frame_class, motor_frame_type frame_type)=0
virtual void set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type)=0
void set_radio_passthrough (float roll_input, float pitch_input, float throttle_input, float yaw_input)
void set_loop_rate (uint16_t loop_rate)
pwm_type get_pwm_type (void) const
Protected Member Functions
void output_armed_stabilizing ()
void add_motor_raw (int8_t motor_num, float roll_fac, float pitch_fac, float yaw_fac, uint8_t testing_order)
void add_motor (int8_t motor_num, float angle_degrees, float yaw_factor, uint8_t testing_order)
void add_motor (int8_t motor_num, float roll_factor_in_degrees, float pitch_factor_in_degrees, float yaw_factor, uint8_t testing_order)
void remove_motor (int8_t motor_num)
virtual void setup_motors (motor_frame_class frame_class, motor_frame_type frame_type)
void normalise_rpy_factors ()
void thrust_compensation (void) override
Protected Member Functions inherited from AP_MotorsMulticopter
void output_logic ()
virtual void update_throttle_filter ()
float get_current_limit_max_throttle ()
float apply_thrust_curve_and_volt_scaling (float thrust) const
void update_lift_max_from_batt_voltage ()
void update_battery_resistance ()
float get_compensation_gain () const
int16_t calc_thrust_to_pwm (float thrust_in) const
int16_t calc_spin_up_to_pwm () const
void save_params_on_disarm ()
Protected Member Functions inherited from AP_Motors
virtual void rc_write (uint8_t chan, uint16_t pwm)
virtual void rc_set_freq (uint32_t mask, uint16_t freq_hz)
virtual void rc_enable_ch (uint8_t chan)
virtual uint32_t rc_map_mask (uint32_t mask) const
void add_motor_num (int8_t motor_num)
int16_t calc_pwm_output_1to1 (float input, const SRV_Channel *servo)
int16_t calc_pwm_output_0to1 (float input, const SRV_Channel *servo)
Protected Attributes
float _roll_factor [AP_MOTORS_MAX_NUM_MOTORS]
float _pitch_factor [AP_MOTORS_MAX_NUM_MOTORS]
float _yaw_factor [AP_MOTORS_MAX_NUM_MOTORS]
float _thrust_rpyt_out [AP_MOTORS_MAX_NUM_MOTORS]
uint8_t _test_order [AP_MOTORS_MAX_NUM_MOTORS]
motor_frame_class _last_frame_class
motor_frame_type _last_frame_type
Protected Attributes inherited from AP_MotorsMulticopter
AP_Int16 _yaw_headroom
AP_Float _thrust_curve_expo
AP_Float _spin_min
AP_Float _spin_max
AP_Float _spin_arm
AP_Float _batt_voltage_max
AP_Float _batt_voltage_min
AP_Float _batt_current_max
AP_Float _batt_current_time_constant
AP_Int16 _pwm_min
AP_Int16 _pwm_max
AP_Float _throttle_hover
AP_Int8 _throttle_hover_learn
AP_Int8 _disarm_disable_pwm
AP_Float _yaw_servo_angle_max_deg
AP_Float _spool_up_time
bool motor_enabled [AP_MOTORS_MAX_NUM_MOTORS]
int16_t _throttle_radio_min
int16_t _throttle_radio_max
spool_up_down_mode _spool_mode
float _spin_up_ratio
float _batt_voltage_resting
LowPassFilterFloat _batt_voltage_filt
float _batt_current_resting
float _batt_resistance
int16_t _batt_timer
float _lift_max
float _throttle_limit
float _throttle_thrust_max
uint16_t _disarm_safety_timer
thrust_compensation_fn_t _thrust_compensation_callback
Protected Attributes inherited from AP_Motors
struct AP_Motors::AP_Motors_flags _flags
uint16_t _loop_rate
uint16_t _speed_hz
float _roll_in
float _pitch_in
float _yaw_in
float _throttle_in
float _forward_in
float _lateral_in
float _throttle_avg_max
LowPassFilterFloat _throttle_filter
spool_up_down_desired _spool_desired
float _batt_voltage
float _batt_current
float _air_density_ratio
uint8_t _motor_map [AP_MOTORS_MAX_NUM_MOTORS]
uint16_t _motor_map_mask
uint16_t _motor_fast_mask
float _roll_radio_passthrough = 0.0f
float _pitch_radio_passthrough = 0.0f
float _throttle_radio_passthrough = 0.0f
float _yaw_radio_passthrough = 0.0f
AP_Int8 _pwm_type
Additional Inherited Members
Public Types inherited from AP_MotorsMulticopter
enum spool_up_down_mode {
SHUT_DOWN = 0, SPIN_WHEN_ARMED = 1, SPOOL_UP = 2, THROTTLE_UNLIMITED = 3,
SPOOL_DOWN = 4
}
Public Types inherited from AP_Motors
enum motor_frame_class {
MOTOR_FRAME_UNDEFINED = 0, MOTOR_FRAME_QUAD = 1, MOTOR_FRAME_HEXA = 2, MOTOR_FRAME_OCTA = 3,
MOTOR_FRAME_OCTAQUAD = 4, MOTOR_FRAME_Y6 = 5, MOTOR_FRAME_HELI = 6, MOTOR_FRAME_TRI = 7,
MOTOR_FRAME_SINGLE = 8, MOTOR_FRAME_COAX = 9, MOTOR_FRAME_TAILSITTER = 10, MOTOR_FRAME_HELI_DUAL = 11
}
enum motor_frame_type {
MOTOR_FRAME_TYPE_PLUS = 0, MOTOR_FRAME_TYPE_X = 1, MOTOR_FRAME_TYPE_V = 2, MOTOR_FRAME_TYPE_H = 3,
MOTOR_FRAME_TYPE_VTAIL = 4, MOTOR_FRAME_TYPE_ATAIL = 5, MOTOR_FRAME_TYPE_Y6B = 10, MOTOR_FRAME_TYPE_Y6F = 11
}
enum spool_up_down_desired { DESIRED_SHUT_DOWN = 0, DESIRED_SPIN_WHEN_ARMED = 1, DESIRED_THROTTLE_UNLIMITED = 2 }
enum pwm_type { PWM_TYPE_NORMAL =0, PWM_TYPE_ONESHOT =1, PWM_TYPE_ONESHOT125 =2, PWM_TYPE_BRUSHED16kHz =3 }
Public Attributes inherited from AP_Motors
struct AP_Motors::AP_Motors_limit limit
Static Public Attributes inherited from AP_MotorsMulticopter
static const struct AP_Param::GroupInfo var_info []
Protected Types inherited from AP_MotorsMulticopter
enum HoverLearn { HOVER_LEARN_DISABLED = 0, HOVER_LEARN_ONLY = 1, HOVER_LEARN_AND_SAVE = 2 }
Detailed Description
Definition at line 14 of file AP_MotorsMatrix.h.
Constructor & Destructor Documentation
AP_MotorsMatrix::AP_MotorsMatrix (uint16_t loop_rate, uint16_t speed_hz = AP_MOTORS_SPEED_DEFAULT) inline
Constructor.
Definition at line 18 of file AP_MotorsMatrix.h.
Member Function Documentation
void AP_MotorsMatrix::add_motor (int8_t motor_num, float angle_degrees, float yaw_factor, uint8_t testing_order) protected
Definition at line 340 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix(), and setup_motors().
void AP_MotorsMatrix::add_motor (int8_t motor_num, float roll_factor_in_degrees, float pitch_factor_in_degrees, float yaw_factor, uint8_t testing_order) protected
Definition at line 346 of file AP_MotorsMatrix.cpp.
void AP_MotorsMatrix::add_motor_raw (int8_t motor_num, float roll_fac, float pitch_fac, float yaw_fac, uint8_t testing_order) protected
Definition at line 316 of file AP_MotorsMatrix.cpp.
Referenced by add_motor(), AP_Motors6DOF::add_motor_raw_6dof(), AP_MotorsMatrix(), and setup_motors().
void AP_MotorsMatrix::enable () virtual
Implements AP_Motors.
Definition at line 76 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix(), and setup().
uint16_t AP_MotorsMatrix::get_motor_mask () virtual
Implements AP_Motors.
Definition at line 141 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix().
void AP_MotorsMatrix::init (motor_frame_class frame_class, motor_frame_type frame_type)
Definition at line 27 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix(), and setup().
void AP_MotorsMatrix::normalise_rpy_factors () protected
Definition at line 636 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix(), and setup_motors().
void AP_MotorsMatrix::output_armed_stabilizing () protected virtual
Implements AP_Motors.
Definition at line 154 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix().
void AP_MotorsMatrix::output_test (uint8_t motor_seq, int16_t pwm) virtual
Implements AP_Motors.
Definition at line 297 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix(), and motor_order_test().
void AP_MotorsMatrix::output_to_motors () virtual
Implements AP_MotorsMulticopter.
Definition at line 88 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix().
void AP_MotorsMatrix::remove_motor (int8_t motor_num) protected
Definition at line 357 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix(), AP_Motors6DOF::setup_motors(), and setup_motors().
void AP_MotorsMatrix::set_frame_class_and_type (motor_frame_class frame_class, motor_frame_type frame_type)
Definition at line 59 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix().
void AP_MotorsMatrix::set_update_rate (uint16_t speed_hz) virtual
Reimplemented from AP_Motors.
Definition at line 41 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix(), init(), set_frame_class_and_type(), and setup().
void AP_MotorsMatrix::setup_motors (motor_frame_class frame_class, motor_frame_type frame_type) protected virtual
Definition at line 369 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix(), init(), and set_frame_class_and_type().
void AP_MotorsMatrix::thrust_compensation (void) override protected virtual
Reimplemented from AP_MotorsMulticopter.
Definition at line 679 of file AP_MotorsMatrix.cpp.
Referenced by AP_MotorsMatrix().
Member Data Documentation
motor_frame_class AP_MotorsMatrix::_last_frame_class protected
Definition at line 77 of file AP_MotorsMatrix.h.
Referenced by init(), AP_Motors6DOF::output_armed_stabilizing(), and set_frame_class_and_type().
motor_frame_type AP_MotorsMatrix::_last_frame_type protected
Definition at line 78 of file AP_MotorsMatrix.h.
Referenced by init(), and set_frame_class_and_type().
float AP_MotorsMatrix::_pitch_factor[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 73 of file AP_MotorsMatrix.h.
Referenced by add_motor_raw(), normalise_rpy_factors(), output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and remove_motor().
float AP_MotorsMatrix::_roll_factor[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 72 of file AP_MotorsMatrix.h.
Referenced by add_motor_raw(), normalise_rpy_factors(), output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and remove_motor().
uint8_t AP_MotorsMatrix::_test_order[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 76 of file AP_MotorsMatrix.h.
Referenced by add_motor_raw(), and output_test().
float AP_MotorsMatrix::_thrust_rpyt_out[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 75 of file AP_MotorsMatrix.h.
Referenced by output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), output_to_motors(), AP_Motors6DOF::output_to_motors(), and thrust_compensation().
float AP_MotorsMatrix::_yaw_factor[AP_MOTORS_MAX_NUM_MOTORS] protected
Definition at line 74 of file AP_MotorsMatrix.h.
Referenced by add_motor_raw(), normalise_rpy_factors(), output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing(), AP_Motors6DOF::output_armed_stabilizing_vectored(), AP_Motors6DOF::output_armed_stabilizing_vectored_6dof(), and remove_motor().
The documentation for this class was generated from the following files:
libraries/AP_Motors/AP_MotorsMatrix.h
libraries/AP_Motors/AP_MotorsMatrix.cpp