APM:Libraries: AP_Baro Class Reference
AP_Baro Class Reference
#include <AP_Baro.h>
Classes
struct sensor
Public Types
enum baro_type_t { BARO_TYPE_AIR, BARO_TYPE_WATER }
Public Member Functions
AP_Baro ()
void init (void)
void update (void)
bool healthy (void) const
bool healthy (uint8_t instance) const
bool all_healthy (void) const
float get_pressure (void) const
float get_pressure (uint8_t instance) const
float get_temperature (void) const
float get_temperature (uint8_t instance) const
void accumulate (void)
void calibrate (bool save=true)
void update_calibration (void)
float get_altitude (void) const
float get_altitude (uint8_t instance) const
float get_altitude_difference (float base_pressure, float pressure) const
float get_EAS2TAS (void)
float get_air_density_ratio (void)
float get_climb_rate (void)
float get_ground_temperature (void) const
float get_ground_pressure (void) const
float get_ground_pressure (uint8_t i) const
void set_external_temperature (float temperature)
uint32_t get_last_update (void) const
uint32_t get_last_update (uint8_t instance) const
float get_external_temperature (void) const
float get_external_temperature (const uint8_t instance) const
void setHIL (float altitude_msl)
void setHIL (uint8_t instance, float pressure, float temperature, float altitude, float climb_rate, uint32_t last_update_ms)
void set_primary_baro (uint8_t primary)
void set_type (uint8_t instance, baro_type_t type)
baro_type_t get_type (uint8_t instance)
uint8_t register_sensor (void)
uint8_t num_instances (void) const
void set_hil_mode (void)
void set_baro_drift_altitude (float alt)
float get_baro_drift_offset (void)
Public Attributes
struct {
float pressure
float temperature
float altitude
float climb_rate
uint32_t last_update_ms
bool updated:1
bool have_alt:1
bool have_last_update:1
} _hil
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void SimpleAtmosphere (const float alt, float &sigma, float &delta, float &theta)
bool _add_backend (AP_Baro_Backend *backend)
Private Attributes
uint8_t _num_drivers
AP_Baro_Backend * drivers [BARO_MAX_DRIVERS]
uint8_t _num_sensors
uint8_t _primary
struct AP_Baro::sensor sensors [BARO_MAX_INSTANCES]
AP_Float _alt_offset
float _alt_offset_active
AP_Int8 _primary_baro
AP_Int8 _ext_bus
float _last_altitude_EAS2TAS
float _EAS2TAS
float _external_temperature
uint32_t _last_external_temperature_ms
DerivativeFilterFloat_Size7 _climb_rate_filter
AP_Float _specific_gravity
AP_Float _user_ground_temperature
bool _hil_mode:1
float _guessed_ground_temperature
uint32_t _last_notify_ms
Friends
class AP_Baro_Backend
Detailed Description
Definition at line 17 of file AP_Baro.h.
Member Enumeration Documentation
enum AP_Baro::baro_type_t
Enumerator
BARO_TYPE_AIR
BARO_TYPE_WATER
Definition at line 26 of file AP_Baro.h.
Constructor & Destructor Documentation
AP_Baro::AP_Baro ()
Definition at line 141 of file AP_Baro.cpp.
Member Function Documentation
bool AP_Baro::_add_backend (AP_Baro_Backend * backend) private
Definition at line 351 of file AP_Baro.cpp.
void AP_Baro::accumulate (void)
Definition at line 576 of file AP_Baro.cpp.
Referenced by get_temperature(), and loop().
bool AP_Baro::all_healthy (void) const
Definition at line 599 of file AP_Baro.cpp.
Referenced by AP_Arming::barometer_checks(), and healthy().
void AP_Baro::calibrate (bool save = true)
Definition at line 148 of file AP_Baro.cpp.
Referenced by get_temperature(), and setup().
float AP_Baro::get_air_density_ratio (void)
Definition at line 286 of file AP_Baro.cpp.
Referenced by get_altitude().
float AP_Baro::get_altitude (void) const inline
Definition at line 67 of file AP_Baro.h.
Referenced by HALSITL::SITL_State::_simulator_servos(), get_altitude(), get_EAS2TAS(), AP_AHRS_DCM::get_position(), AP_AHRS_DCM::get_relative_position_D_home(), AP_AHRS_NavEKF::get_relative_position_D_home(), DataFlash_Class::Log_Write_Baro(), loop(), NavEKF2_core::readBaroData(), NavEKF3_core::readBaroData(), update(), and AP_TECS::update_50hz().
float AP_Baro::get_altitude (uint8_t instance) const inline
Definition at line 68 of file AP_Baro.h.
float AP_Baro::get_altitude_difference (float base_pressure, float pressure) const
Definition at line 251 of file AP_Baro.cpp.
Referenced by AP_AdvancedFailsafe::check_altlimit(), get_altitude(), AP_ADSB::send_dynamic_out(), and update().
float AP_Baro::get_baro_drift_offset (void) inline
Definition at line 150 of file AP_Baro.h.
Referenced by DataFlash_Class::Log_Write_Baro().
float AP_Baro::get_climb_rate (void)
Definition at line 299 of file AP_Baro.cpp.
Referenced by get_altitude(), DataFlash_Class::Log_Write_Baro(), and loop().
float AP_Baro::get_EAS2TAS (void)
Definition at line 268 of file AP_Baro.cpp.
Referenced by get_air_density_ratio(), and get_altitude().
float AP_Baro::get_external_temperature (void) const inline
Definition at line 105 of file AP_Baro.h.
Referenced by calibrate(), get_external_temperature(), and update_calibration().
float AP_Baro::get_external_temperature (const uint8_t instance) const
Definition at line 333 of file AP_Baro.cpp.
float AP_Baro::get_ground_pressure (void) const inline
Definition at line 90 of file AP_Baro.h.
Referenced by get_ground_pressure(), and GCS_MAVLINK::send_scaled_pressure().
float AP_Baro::get_ground_pressure (uint8_t i) const inline
Definition at line 91 of file AP_Baro.h.
float AP_Baro::get_ground_temperature (void) const
Definition at line 311 of file AP_Baro.cpp.
Referenced by get_altitude(), get_altitude_difference(), get_EAS2TAS(), and DataFlash_Class::Log_Write_Baro().
uint32_t AP_Baro::get_last_update (void) const inline
Definition at line 99 of file AP_Baro.h.
Referenced by AP_AdvancedFailsafe::check_altlimit(), get_last_update(), DataFlash_Class::Log_Write_Baro(), NavEKF2_core::readBaroData(), NavEKF3_core::readBaroData(), and update().
uint32_t AP_Baro::get_last_update (uint8_t instance) const inline
Definition at line 100 of file AP_Baro.h.
float AP_Baro::get_pressure (void) const inline
Definition at line 46 of file AP_Baro.h.
Referenced by AP_AdvancedFailsafe::check_altlimit(), get_EAS2TAS(), get_pressure(), DataFlash_Class::Log_Write_Baro(), loop(), AP_ADSB::send_dynamic_out(), GCS_MAVLINK::send_scaled_pressure(), GCS_MAVLINK::send_sensor_offsets(), and update_calibration().
float AP_Baro::get_pressure (uint8_t instance) const inline
Definition at line 47 of file AP_Baro.h.
float AP_Baro::get_temperature (void) const inline
Definition at line 50 of file AP_Baro.h.
Referenced by get_external_temperature(), get_temperature(), DataFlash_Class::Log_Write_Baro(), loop(), GCS_MAVLINK::send_scaled_pressure(), and GCS_MAVLINK::send_sensor_offsets().
float AP_Baro::get_temperature (uint8_t instance) const inline
Definition at line 51 of file AP_Baro.h.
baro_type_t AP_Baro::get_type (uint8_t instance) inline
Definition at line 122 of file AP_Baro.h.
bool AP_Baro::healthy (void) const inline
Definition at line 39 of file AP_Baro.h.
Referenced by all_healthy(), calibrate(), healthy(), DataFlash_Class::Log_Write_Baro(), loop(), AP_ADSB::send_dynamic_out(), update(), and update_calibration().
bool AP_Baro::healthy (uint8_t instance) const inline
Definition at line 40 of file AP_Baro.h.
void AP_Baro::init (void)
Definition at line 378 of file AP_Baro.cpp.
Referenced by setup().
uint8_t AP_Baro::num_instances (void) const inline
Definition at line 141 of file AP_Baro.h.
Referenced by DataFlash_Class::Log_Write_Baro(), and GCS_MAVLINK::send_scaled_pressure().
uint8_t AP_Baro::register_sensor (void)
Definition at line 587 of file AP_Baro.cpp.
Referenced by AP_Baro_BMP280::_init(), AP_Baro_MS56XX::_init(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_Baro_HIL::AP_Baro_HIL(), AP_Baro_PX4::AP_Baro_PX4(), AP_Baro_QFLIGHT::AP_Baro_QFLIGHT(), and AP_Baro_QURT::AP_Baro_QURT().
void AP_Baro::set_baro_drift_altitude (float alt) inline
Definition at line 147 of file AP_Baro.h.
void AP_Baro::set_external_temperature (float temperature)
Definition at line 324 of file AP_Baro.cpp.
Referenced by get_ground_pressure().
void AP_Baro::set_hil_mode (void) inline
Definition at line 144 of file AP_Baro.h.
void AP_Baro::set_primary_baro (uint8_t primary) inline
Definition at line 116 of file AP_Baro.h.
void AP_Baro::set_type (uint8_t instance, baro_type_t type) inline
Definition at line 119 of file AP_Baro.h.
Referenced by AP_Baro_MS56XX::_init().
void AP_Baro::setHIL (float altitude_msl)
Definition at line 47 of file AP_Baro_HIL.cpp.
Referenced by HALSITL::SITL_State::_update_barometer(), and get_external_temperature().
void AP_Baro::setHIL (uint8_t instance, float pressure, float temperature, float altitude, float climb_rate, uint32_t last_update_ms)
Definition at line 64 of file AP_Baro_HIL.cpp.
void AP_Baro::SimpleAtmosphere (const float alt, float & sigma, float & delta, float & theta) private
Definition at line 20 of file AP_Baro_HIL.cpp.
void AP_Baro::update (void)
Definition at line 502 of file AP_Baro.cpp.
Referenced by calibrate(), and loop().
void AP_Baro::update_calibration (void)
Definition at line 227 of file AP_Baro.cpp.
Referenced by get_temperature(), NavEKF2_core::resetHeightDatum(), and NavEKF3_core::resetHeightDatum().
Friends And Related Function Documentation
friend class AP_Baro_Backend friend
Definition at line 19 of file AP_Baro.h.
Member Data Documentation
AP_Float AP_Baro::_alt_offset private
Definition at line 175 of file AP_Baro.h.
Referenced by calibrate(), set_baro_drift_altitude(), and update().
float AP_Baro::_alt_offset_active private
Definition at line 176 of file AP_Baro.h.
Referenced by get_baro_drift_offset(), and update().
DerivativeFilterFloat_Size7 AP_Baro::_climb_rate_filter private
Definition at line 183 of file AP_Baro.h.
Referenced by get_climb_rate(), and update().
float AP_Baro::_EAS2TAS private
Definition at line 180 of file AP_Baro.h.
Referenced by get_EAS2TAS(), and update_calibration().
AP_Int8 AP_Baro::_ext_bus private
Definition at line 178 of file AP_Baro.h.
Referenced by init().
float AP_Baro::_external_temperature private
Definition at line 181 of file AP_Baro.h.
Referenced by get_external_temperature(), and set_external_temperature().
float AP_Baro::_guessed_ground_temperature private
Definition at line 187 of file AP_Baro.h.
Referenced by calibrate(), get_ground_temperature(), and update_calibration().
struct { ... } AP_Baro::_hil
Referenced by get_climb_rate(), AP_Baro_HIL::update(), and update().
bool AP_Baro::_hil_mode private
Definition at line 186 of file AP_Baro.h.
Referenced by init(), set_hil_mode(), and update().
float AP_Baro::_last_altitude_EAS2TAS private
Definition at line 179 of file AP_Baro.h.
Referenced by get_EAS2TAS().
uint32_t AP_Baro::_last_external_temperature_ms private
Definition at line 182 of file AP_Baro.h.
Referenced by get_external_temperature(), and set_external_temperature().
uint32_t AP_Baro::_last_notify_ms private
Definition at line 190 of file AP_Baro.h.
Referenced by update_calibration().
uint8_t AP_Baro::_num_drivers private
Definition at line 154 of file AP_Baro.h.
Referenced by _add_backend(), accumulate(), init(), and update().
uint8_t AP_Baro::_num_sensors private
Definition at line 158 of file AP_Baro.h.
Referenced by AP_Baro_Backend::_copy_to_frontend(), all_healthy(), calibrate(), init(), num_instances(), register_sensor(), update(), and update_calibration().
uint8_t AP_Baro::_primary private
Definition at line 161 of file AP_Baro.h.
Referenced by get_altitude(), get_external_temperature(), get_ground_pressure(), get_last_update(), get_pressure(), get_temperature(), healthy(), and update().
AP_Int8 AP_Baro::_primary_baro private
Definition at line 177 of file AP_Baro.h.
Referenced by set_primary_baro(), and update().
AP_Float AP_Baro::_specific_gravity private
Definition at line 184 of file AP_Baro.h.
Referenced by update().
AP_Float AP_Baro::_user_ground_temperature private
Definition at line 185 of file AP_Baro.h.
Referenced by get_ground_temperature(), and init().
float AP_Baro::altitude
Definition at line 128 of file AP_Baro.h.
Referenced by get_EAS2TAS(), get_external_temperature(), and update().
float AP_Baro::climb_rate
Definition at line 129 of file AP_Baro.h.
Referenced by get_external_temperature().
AP_Baro_Backend* AP_Baro::drivers[BARO_MAX_DRIVERS] private
Definition at line 155 of file AP_Baro.h.
Referenced by _add_backend(), accumulate(), init(), and update().
bool AP_Baro::have_alt
Definition at line 132 of file AP_Baro.h.
bool AP_Baro::have_last_update
Definition at line 133 of file AP_Baro.h.
uint32_t AP_Baro::last_update_ms
Definition at line 130 of file AP_Baro.h.
Referenced by get_external_temperature().
float AP_Baro::pressure
Definition at line 126 of file AP_Baro.h.
Referenced by get_altitude(), AP_Baro_HIL::update(), and update().
struct AP_Baro::sensor AP_Baro::sensors[BARO_MAX_INSTANCES] private
Referenced by AP_Baro_Backend::_copy_to_frontend(), calibrate(), get_altitude(), get_ground_pressure(), get_last_update(), get_pressure(), get_temperature(), get_type(), healthy(), set_type(), update(), and update_calibration().
float AP_Baro::temperature
Definition at line 127 of file AP_Baro.h.
Referenced by get_ground_pressure(), set_external_temperature(), and AP_Baro_HIL::update().
bool AP_Baro::updated
Definition at line 131 of file AP_Baro.h.
Referenced by AP_Baro_HIL::update().
const AP_Param::GroupInfo AP_Baro::var_info static
Definition at line 103 of file AP_Baro.h.
Referenced by AP_Baro().
The documentation for this class was generated from the following files:
libraries/AP_Baro/AP_Baro.h
libraries/AP_Baro/AP_Baro.cpp
libraries/AP_Baro/AP_Baro_HIL.cpp