APM:Libraries: AP_SerialManager Class Reference
AP_SerialManager Class Reference
#include <AP_SerialManager.h>
Public Types
enum SerialProtocol {
SerialProtocol_None = -1, SerialProtocol_Console = 0, SerialProtocol_MAVLink = 1, SerialProtocol_MAVLink2 = 2,
SerialProtocol_FrSky_D = 3, SerialProtocol_FrSky_SPort = 4, SerialProtocol_GPS = 5, SerialProtocol_GPS2 = 6,
SerialProtocol_AlexMos = 7, SerialProtocol_SToRM32 = 8, SerialProtocol_Lidar = 9, SerialProtocol_FrSky_SPort_Passthrough = 10,
SerialProtocol_Lidar360 = 11, SerialProtocol_Aerotenna_uLanding = 12, SerialProtocol_Beacon = 13
}
Public Member Functions
AP_SerialManager ()
void init_console ()
void init ()
AP_HAL::UARTDriver * find_serial (enum SerialProtocol protocol, uint8_t instance) const
uint32_t find_baudrate (enum SerialProtocol protocol, uint8_t instance) const
bool get_mavlink_channel (enum SerialProtocol protocol, uint8_t instance, mavlink_channel_t &mav_chan) const
SerialProtocol get_mavlink_protocol (mavlink_channel_t mav_chan) const
void set_blocking_writes_all (bool blocking)
void set_console_baud (enum SerialProtocol protocol, uint8_t instance) const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
uint32_t map_baudrate (int32_t rate) const
bool protocol_match (enum SerialProtocol protocol1, enum SerialProtocol protocol2) const
Private Attributes
struct {
AP_Int8 protocol
AP_Int32 baud
AP_HAL::UARTDriver * uart
} state [SERIALMANAGER_NUM_PORTS]
Detailed Description
Definition at line 73 of file AP_SerialManager.h.
Member Enumeration Documentation
enum AP_SerialManager::SerialProtocol
Enumerator
SerialProtocol_None
SerialProtocol_Console
SerialProtocol_MAVLink
SerialProtocol_MAVLink2
SerialProtocol_FrSky_D
SerialProtocol_FrSky_SPort
SerialProtocol_GPS
SerialProtocol_GPS2
SerialProtocol_AlexMos
SerialProtocol_SToRM32
SerialProtocol_Lidar
SerialProtocol_FrSky_SPort_Passthrough
SerialProtocol_Lidar360
SerialProtocol_Aerotenna_uLanding
SerialProtocol_Beacon
Definition at line 77 of file AP_SerialManager.h.
Constructor & Destructor Documentation
AP_SerialManager::AP_SerialManager ()
Definition at line 128 of file AP_SerialManager.cpp.
Member Function Documentation
uint32_t AP_SerialManager::find_baudrate (enum SerialProtocol protocol, uint8_t instance) const
Definition at line 238 of file AP_SerialManager.cpp.
Referenced by AP_Beacon_Pozyx::AP_Beacon_Pozyx(), AP_Proximity_LightWareSF40C::AP_Proximity_LightWareSF40C(), AP_Proximity_TeraRangerTower::AP_Proximity_TeraRangerTower(), AP_RangeFinder_LeddarOne::AP_RangeFinder_LeddarOne(), AP_RangeFinder_LightWareSerial::AP_RangeFinder_LightWareSerial(), AP_RangeFinder_MaxsonarSerialLV::AP_RangeFinder_MaxsonarSerialLV(), AP_RangeFinder_uLanding::AP_RangeFinder_uLanding(), and GCS_MAVLINK::setup_uart().
AP_HAL::UARTDriver * AP_SerialManager::find_serial (enum SerialProtocol protocol, uint8_t instance) const
Definition at line 217 of file AP_SerialManager.cpp.
Referenced by AP_Beacon_Pozyx::AP_Beacon_Pozyx(), AP_Proximity_LightWareSF40C::AP_Proximity_LightWareSF40C(), AP_Proximity_TeraRangerTower::AP_Proximity_TeraRangerTower(), AP_RangeFinder_LeddarOne::AP_RangeFinder_LeddarOne(), AP_RangeFinder_LightWareSerial::AP_RangeFinder_LightWareSerial(), AP_RangeFinder_MaxsonarSerialLV::AP_RangeFinder_MaxsonarSerialLV(), AP_RangeFinder_uLanding::AP_RangeFinder_uLanding(), AP_RangeFinder_LightWareSerial::detect(), AP_RangeFinder_MaxsonarSerialLV::detect(), AP_Proximity_TeraRangerTower::detect(), AP_RangeFinder_uLanding::detect(), AP_Proximity_LightWareSF40C::detect(), AP_RangeFinder_LeddarOne::detect(), AP_Mount_SToRM32_serial::init(), AP_Mount_Alexmos::init(), AP_Frsky_Telem::init(), AP_GPS::init(), and GCS_MAVLINK::setup_uart().
bool AP_SerialManager::get_mavlink_channel (enum SerialProtocol protocol, uint8_t instance, mavlink_channel_t & mav_chan) const
Definition at line 259 of file AP_SerialManager.cpp.
Referenced by GCS_MAVLINK::setup_uart().
AP_SerialManager::SerialProtocol AP_SerialManager::get_mavlink_protocol (mavlink_channel_t mav_chan) const
Definition at line 275 of file AP_SerialManager.cpp.
Referenced by GCS_MAVLINK::packetReceived(), and GCS_MAVLINK::setup_uart().
void AP_SerialManager::init (void)
Definition at line 145 of file AP_SerialManager.cpp.
Referenced by setup().
void AP_SerialManager::init_console ()
Definition at line 135 of file AP_SerialManager.cpp.
Referenced by init().
uint32_t AP_SerialManager::map_baudrate (int32_t rate) const private
Definition at line 324 of file AP_SerialManager.cpp.
Referenced by find_baudrate(), init(), and set_console_baud().
bool AP_SerialManager::protocol_match (enum SerialProtocol protocol1, enum SerialProtocol protocol2) const private
Definition at line 358 of file AP_SerialManager.cpp.
Referenced by find_baudrate(), find_serial(), get_mavlink_channel(), and set_console_baud().
void AP_SerialManager::set_blocking_writes_all (bool blocking)
Definition at line 292 of file AP_SerialManager.cpp.
void AP_SerialManager::set_console_baud (enum SerialProtocol protocol, uint8_t instance) const
Definition at line 303 of file AP_SerialManager.cpp.
Member Data Documentation
AP_Int32 AP_SerialManager::baud
Definition at line 137 of file AP_SerialManager.h.
Referenced by find_baudrate(), init(), and set_console_baud().
AP_Int8 AP_SerialManager::protocol
Definition at line 136 of file AP_SerialManager.h.
Referenced by get_mavlink_protocol(), and init().
struct { ... } AP_SerialManager::state[SERIALMANAGER_NUM_PORTS]
Referenced by find_baudrate(), find_serial(), get_mavlink_protocol(), init(), init_console(), set_blocking_writes_all(), and set_console_baud().
AP_HAL::UARTDriver* AP_SerialManager::uart
Definition at line 138 of file AP_SerialManager.h.
Referenced by init(), and set_blocking_writes_all().
const AP_Param::GroupInfo AP_SerialManager::var_info static
Definition at line 130 of file AP_SerialManager.h.
Referenced by AP_SerialManager().
The documentation for this class was generated from the following files:
libraries/AP_SerialManager/AP_SerialManager.h
libraries/AP_SerialManager/AP_SerialManager.cpp