APM:Libraries: AP_HAL::RCOutput Class Reference
AP_HAL::RCOutput Class Reference abstract
#include <RCOutput.h>
Public Types
enum output_mode { MODE_PWM_NORMAL, MODE_PWM_ONESHOT, MODE_PWM_BRUSHED16KHZ }
Public Member Functions
virtual void init ()=0
virtual void set_freq (uint32_t chmask, uint16_t freq_hz)=0
virtual uint16_t get_freq (uint8_t ch)=0
virtual void enable_ch (uint8_t ch)=0
virtual void disable_ch (uint8_t ch)=0
virtual void write (uint8_t ch, uint16_t period_us)=0
virtual void cork ()=0
virtual void push ()=0
virtual uint16_t read (uint8_t ch)=0
virtual void read (uint16_t *period_us, uint8_t len)=0
virtual uint16_t read_last_sent (uint8_t ch)
virtual void read_last_sent (uint16_t *period_us, uint8_t len)
virtual void set_safety_pwm (uint32_t chmask, uint16_t period_us)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
virtual void force_safety_no_wait (void)
virtual void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
virtual float scale_esc_to_unity (uint16_t pwm)
virtual bool enable_sbus_out (uint16_t rate_gz)
virtual void timer_tick (void)
virtual void set_output_mode (enum output_mode mode)
Detailed Description
Definition at line 32 of file RCOutput.h.
Member Enumeration Documentation
enum AP_HAL::RCOutput::output_mode
Enumerator
MODE_PWM_NORMAL
MODE_PWM_ONESHOT
MODE_PWM_BRUSHED16KHZ
Definition at line 130 of file RCOutput.h.
Member Function Documentation
virtual void AP_HAL::RCOutput::cork () pure virtual
Implemented in PX4::RCOutput_Tap, Linux::RCOutput_Bebop, Linux::RCOutput_AeroIO, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by RCOutputRGBLed::hw_set_rgb(), AP_MotorsHeli_Dual::move_actuators(), AP_MotorsHeli_Single::move_actuators(), AP_Motors6DOF::output_min(), AP_MotorsMulticopter::output_motor_mask(), AP_MotorsMatrix::output_test(), AP_MotorsMatrix::output_to_motors(), AP_Motors6DOF::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsCoax::output_to_motors(), and AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration().
virtual void AP_HAL::RCOutput::disable_ch (uint8_t ch) pure virtual
Implemented in Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_AeroIO, Linux::RCOutput_PCA9685, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
virtual void AP_HAL::RCOutput::enable_ch (uint8_t ch) pure virtual
Implemented in Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_AeroIO, Linux::RCOutput_PCA9685, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by SRV_Channels::enable_aux_servos(), RCOutputRGBLed::hw_init(), RC_UART::loop(), AP_Motors::rc_enable_ch(), and setup().
virtual bool AP_HAL::RCOutput::enable_sbus_out (uint16_t rate_gz) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 119 of file RCOutput.h.
Referenced by AP_BoardConfig::px4_setup_sbus().
virtual void AP_HAL::RCOutput::force_safety_no_wait (void) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 101 of file RCOutput.h.
Referenced by GCS_MAVLINK::handle_preflight_reboot(), AP_BoardConfig::px4_setup_safety(), VRBRAIN::VRBRAINScheduler::reboot(), and PX4::PX4Scheduler::reboot().
virtual void AP_HAL::RCOutput::force_safety_off (void) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 96 of file RCOutput.h.
Referenced by GCS_MAVLINK::handle_set_mode(), RC_UART::loop(), and AP_BoardConfig::px4_setup_safety().
virtual bool AP_HAL::RCOutput::force_safety_on (void) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 91 of file RCOutput.h.
Referenced by GCS_MAVLINK::handle_preflight_reboot(), GCS_MAVLINK::handle_set_mode(), VRBRAIN::VRBRAINScheduler::reboot(), and PX4::PX4Scheduler::reboot().
virtual uint16_t AP_HAL::RCOutput::get_freq (uint8_t ch) pure virtual
Implemented in Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_AeroIO, Linux::RCOutput_PCA9685, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by RCOutputRGBLed::hw_set_rgb().
virtual void AP_HAL::RCOutput::init () pure virtual
Implemented in Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_AeroIO, Linux::RCOutput_PCA9685, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by main_loop(), AP_BoardConfig::px4_setup_peripherals(), HAL_Linux::run(), and HAL_SITL::run().
virtual void AP_HAL::RCOutput::push () pure virtual
Implemented in PX4::RCOutput_Tap, Linux::RCOutput_Bebop, Linux::RCOutput_AeroIO, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PCA9685, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by AP_MotorsHeli_Dual::move_actuators(), AP_MotorsHeli_Single::move_actuators(), AP_Motors6DOF::output_min(), AP_MotorsMulticopter::output_motor_mask(), AP_MotorsMatrix::output_test(), AP_MotorsMatrix::output_to_motors(), AP_Motors6DOF::output_to_motors(), AP_MotorsTri::output_to_motors(), AP_MotorsSingle::output_to_motors(), AP_MotorsCoax::output_to_motors(), and AP_MotorsMulticopter::set_throttle_passthrough_for_esc_calibration().
virtual uint16_t AP_HAL::RCOutput::read (uint8_t ch) pure virtual
Implemented in Linux::RCOutput_AeroIO, Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_PCA9685, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by DataFlash_Class::Log_Write_RCOUT(), read_last_sent(), GCS_MAVLINK::send_servo_output_raw(), and stability_test().
virtual void AP_HAL::RCOutput::read (uint16_t * period_us, uint8_t len) pure virtual
Implemented in Linux::RCOutput_AeroIO, Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_PCA9685, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
virtual uint16_t AP_HAL::RCOutput::read_last_sent (uint8_t ch) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 72 of file RCOutput.h.
Referenced by SRV_Channels::limit_slew_rate().
virtual void AP_HAL::RCOutput::read_last_sent (uint16_t * period_us, uint8_t len) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 73 of file RCOutput.h.
virtual float AP_HAL::RCOutput::scale_esc_to_unity (uint16_t pwm) inline virtual
Reimplemented in PX4::PX4RCOutput.
Definition at line 114 of file RCOutput.h.
virtual void AP_HAL::RCOutput::set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm) inline virtual
Reimplemented in Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_Disco, PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 109 of file RCOutput.h.
Referenced by Linux::RCOutput_Disco::set_esc_scaling(), SRV_Channels::set_esc_scaling_for(), and AP_MotorsMulticopter::set_throttle_range().
virtual void AP_HAL::RCOutput::set_failsafe_pwm (uint32_t chmask, uint16_t period_us) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 84 of file RCOutput.h.
Referenced by SRV_Channels::set_failsafe_limit(), SRV_Channels::set_failsafe_pwm(), and SRV_Channels::setup_failsafe_trim_all().
virtual void AP_HAL::RCOutput::set_freq (uint32_t chmask, uint16_t freq_hz) pure virtual
Implemented in Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_AeroIO, Linux::RCOutput_PCA9685, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by drive(), RCOutputRGBLed::hw_set_rgb(), AP_Motors::rc_set_freq(), and RC_UART::setup().
virtual void AP_HAL::RCOutput::set_output_mode (enum output_mode mode) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 135 of file RCOutput.h.
Referenced by AP_Motors::rc_set_freq().
virtual void AP_HAL::RCOutput::set_safety_pwm (uint32_t chmask, uint16_t period_us) inline virtual
Reimplemented in PX4::PX4RCOutput, and VRBRAIN::VRBRAINRCOutput.
Definition at line 79 of file RCOutput.h.
Referenced by SRV_Channels::set_safety_limit().
virtual void AP_HAL::RCOutput::timer_tick (void) inline virtual
Reimplemented in PX4::PX4RCOutput.
Definition at line 125 of file RCOutput.h.
Referenced by PX4::PX4Scheduler::_timer_thread().
virtual void AP_HAL::RCOutput::write (uint8_t ch, uint16_t period_us) pure virtual
Implemented in Linux::RCOutput_Bebop, PX4::RCOutput_Tap, Linux::RCOutput_AeroIO, Linux::RCOutput_PCA9685, Linux::RCOutput_AioPRU, Linux::RCOutput_Disco, Linux::RCOutput_PRU, QURT::RCOutput, Linux::RCOutput_Sysfs, PX4::PX4RCOutput, VRBRAIN::VRBRAINRCOutput, Linux::RCOutput_QFLIGHT, Linux::RCOutput_ZYNQ, Linux::RCOutput_Raspilot, HALSITL::RCOutput, and Empty::RCOutput.
Referenced by drive(), RCOutputRGBLed::hw_set_rgb(), RC_UART::loop(), loop(), SRV_Channel::output_ch(), and AP_Motors::rc_write().
The documentation for this class was generated from the following file:
libraries/AP_HAL/RCOutput.h