APM:Libraries: AP_HAL::RCInput Class Reference
AP_HAL::RCInput Class Reference abstract
#include <RCInput.h>
Public Member Functions
virtual void init ()=0
virtual void teardown ()
virtual bool new_input (void)=0
virtual uint8_t num_channels ()=0
virtual uint16_t read (uint8_t ch)=0
virtual uint8_t read (uint16_t *periods, uint8_t len)=0
virtual bool set_overrides (int16_t *overrides, uint8_t len)=0
virtual bool set_override (uint8_t channel, int16_t override)=0
virtual void clear_overrides ()=0
virtual bool rc_bind (int dsmMode)
Detailed Description
Definition at line 8 of file RCInput.h.
Member Function Documentation
virtual void AP_HAL::RCInput::clear_overrides () pure virtual
Implemented in Linux::RCInput, QURT::RCInput, PX4::PX4RCInput, HALSITL::RCInput, VRBRAIN::VRBRAINRCInput, and Empty::RCInput.
Referenced by teardown().
virtual void AP_HAL::RCInput::init () pure virtual
Call init from the platform hal instance init, so that both the type of the RCInput implementation and init argument (e.g. ISRRegistry) are known to the programmer. (It's too difficult to describe this dependency in the C++ type system.)
Implemented in Linux::RCInput_RPI, Linux::RCInput_115200, Linux::RCInput_DSM, Linux::RCInput_Multi, Linux::RCInput_AioPRU, Linux::RCInput_SBUS, Linux::RCInput, QURT::RCInput, Linux::RCInput_UART, Linux::RCInput_PRU, Linux::RCInput_UDP, PX4::PX4RCInput, VRBRAIN::VRBRAINRCInput, Linux::RCInput_ZYNQ, Linux::RCInput_Raspilot, HALSITL::RCInput, Linux::RCInput_Navio2, and Empty::RCInput.
Referenced by main_loop(), AP_BoardConfig::px4_setup_peripherals(), HAL_Linux::run(), and HAL_SITL::run().
virtual bool AP_HAL::RCInput::new_input (void) pure virtual
Return true if there has been new input since the last call to new_input()
Implemented in Linux::RCInput, QURT::RCInput, PX4::PX4RCInput, VRBRAIN::VRBRAINRCInput, HALSITL::RCInput, and Empty::RCInput.
Referenced by RC_UART::loop(), and teardown().
virtual uint8_t AP_HAL::RCInput::num_channels () pure virtual
Return the number of valid channels in the last read
Implemented in Linux::RCInput, QURT::RCInput, PX4::PX4RCInput, VRBRAIN::VRBRAINRCInput, HALSITL::RCInput, and Empty::RCInput.
Referenced by AP_Tuning::check_input(), loop(), GCS_MAVLINK::send_radio_in(), and teardown().
virtual bool AP_HAL::RCInput::rc_bind (int dsmMode) inline virtual
Reimplemented in PX4::PX4RCInput, and VRBRAIN::VRBRAINRCInput.
Definition at line 52 of file RCInput.h.
Referenced by GCS_MAVLINK::handle_rc_bind().
virtual uint16_t AP_HAL::RCInput::read (uint8_t ch) pure virtual
Implemented in Linux::RCInput, QURT::RCInput, PX4::PX4RCInput, HALSITL::RCInput, VRBRAIN::VRBRAINRCInput, and Empty::RCInput.
Referenced by AP_ICEngine::engine_control(), RC_Channel::input(), SoaringController::is_active(), DataFlash_Class::Log_Write_RCIN(), RC_UART::loop(), loop(), RC_Channel::read(), AP_RSSI::read_channel_rssi(), GCS_MAVLINK::send_radio_in(), setup(), teardown(), and AP_ICEngine::update().
virtual uint8_t AP_HAL::RCInput::read (uint16_t * periods, uint8_t len) pure virtual
Implemented in Linux::RCInput, QURT::RCInput, PX4::PX4RCInput, HALSITL::RCInput, VRBRAIN::VRBRAINRCInput, and Empty::RCInput.
virtual bool AP_HAL::RCInput::set_override (uint8_t channel, int16_t override) pure virtual
Implemented in Linux::RCInput, QURT::RCInput, PX4::PX4RCInput, HALSITL::RCInput, VRBRAIN::VRBRAINRCInput, and Empty::RCInput.
Referenced by teardown().
virtual bool AP_HAL::RCInput::set_overrides (int16_t * overrides, uint8_t len) pure virtual
Overrides: these are really grody and don't belong here but we need them at the moment to make the port work. case v of: v == -1 -> no change to this channel v == 0 -> do not override this channel v > 0 -> set v as override.
Implemented in Linux::RCInput, QURT::RCInput, PX4::PX4RCInput, HALSITL::RCInput, VRBRAIN::VRBRAINRCInput, and Empty::RCInput.
Referenced by Linux::RCOutput_QFLIGHT::check_rc_in(), and teardown().
virtual void AP_HAL::RCInput::teardown () inline virtual
Reimplemented in Linux::RCInput_RPI.
Definition at line 17 of file RCInput.h.
Referenced by AP_HAL::panic(), and HAL_Linux::run().
The documentation for this class was generated from the following file:
libraries/AP_HAL/RCInput.h