APM:Libraries: ObjectBuffer< T > Class Template Reference
ObjectBuffer< T > Class Template Reference
#include <RingBuffer.h>
Public Member Functions
ObjectBuffer (uint32_t _size)
~ObjectBuffer (void)
void clear (void)
uint32_t available (void) const
uint32_t space (void) const
bool empty (void) const
bool push (const T &object)
bool pop (void)
bool pop (T &object)
bool push_force (const T &object)
bool peek (T &object)
bool update (const T &object)
Private Attributes
ByteBuffer * buffer = nullptr
Detailed Description
template<class T>
class ObjectBuffer< T >
Definition at line 98 of file RingBuffer.h.
Constructor & Destructor Documentation
template<class T> ObjectBuffer< T >::ObjectBuffer (uint32_t _size) inline
Definition at line 100 of file RingBuffer.h.
template<class T> ObjectBuffer< T >::~ObjectBuffer (void) inline
Definition at line 103 of file RingBuffer.h.
Member Function Documentation
template<class T> uint32_t ObjectBuffer< T >::available (void) const inline
Definition at line 114 of file RingBuffer.h.
template<class T> void ObjectBuffer< T >::clear (void) inline
Definition at line 108 of file RingBuffer.h.
template<class T> bool ObjectBuffer< T >::empty (void) const inline
Definition at line 124 of file RingBuffer.h.
template<class T> bool ObjectBuffer< T >::peek (T & object) inline
Definition at line 168 of file RingBuffer.h.
template<class T> bool ObjectBuffer< T >::pop (void) inline
Definition at line 139 of file RingBuffer.h.
Referenced by AP_InertialSensor_QURT::accumulate(), and AP_Compass_QURT::timer_update().
template<class T> bool ObjectBuffer< T >::pop (T & object) inline
Definition at line 146 of file RingBuffer.h.
template<class T> bool ObjectBuffer< T >::push (const T & object) inline
Definition at line 129 of file RingBuffer.h.
Referenced by AP_InertialSensor_QURT::data_ready().
template<class T> bool ObjectBuffer< T >::push_force (const T & object) inline
Definition at line 158 of file RingBuffer.h.
template<class T> uint32_t ObjectBuffer< T >::space (void) const inline
Definition at line 119 of file RingBuffer.h.
template<class T> bool ObjectBuffer< T >::update (const T & object) inline
Definition at line 174 of file RingBuffer.h.
Member Data Documentation
template<class T> ByteBuffer* ObjectBuffer< T >::buffer = nullptr private
Definition at line 179 of file RingBuffer.h.
The documentation for this class was generated from the following file:
libraries/AP_HAL/utility/RingBuffer.h