APM:Libraries: AP_Airspeed_MS5525 Class Reference
AP_Airspeed_MS5525 Class Reference
#include <AP_Airspeed_MS5525.h>
Public Member Functions
AP_Airspeed_MS5525 (AP_Airspeed &frontend)
~AP_Airspeed_MS5525 (void)
bool init () override
bool get_differential_pressure (float &pressure) override
bool get_temperature (float &temperature) override
Public Member Functions inherited from AP_Airspeed_Backend
AP_Airspeed_Backend (AP_Airspeed &frontend)
virtual ~AP_Airspeed_Backend ()
Private Member Functions
void measure ()
void collect ()
void timer ()
bool read_prom (void)
uint16_t crc4_prom (void)
int32_t read_adc ()
void calculate ()
Private Attributes
float pressure
float temperature
float temperature_sum
float pressure_sum
uint32_t temp_count
uint32_t press_count
uint32_t last_sample_time_ms
uint16_t prom [8]
uint8_t state
int32_t D1
int32_t D2
AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev
Additional Inherited Members
Protected Member Functions inherited from AP_Airspeed_Backend
int8_t get_pin (void) const
float get_psi_range (void) const
uint8_t get_bus (void) const
Protected Attributes inherited from AP_Airspeed_Backend
AP_HAL::Semaphore * sem
Detailed Description
Definition at line 30 of file AP_Airspeed_MS5525.h.
Constructor & Destructor Documentation
AP_Airspeed_MS5525::AP_Airspeed_MS5525 (AP_Airspeed & frontend)
Definition at line 54 of file AP_Airspeed_MS5525.cpp.
AP_Airspeed_MS5525::~AP_Airspeed_MS5525 (void) inline
Definition at line 34 of file AP_Airspeed_MS5525.h.
Member Function Documentation
void AP_Airspeed_MS5525::calculate (void) private
Definition at line 189 of file AP_Airspeed_MS5525.cpp.
Referenced by timer(), and ~AP_Airspeed_MS5525().
void AP_Airspeed_MS5525::collect () private
Referenced by ~AP_Airspeed_MS5525().
uint16_t AP_Airspeed_MS5525::crc4_prom (void) private
CRC used by MS pressure devices
Definition at line 109 of file AP_Airspeed_MS5525.cpp.
Referenced by read_prom(), and ~AP_Airspeed_MS5525().
bool AP_Airspeed_MS5525::get_differential_pressure (float & pressure) override virtual
Implements AP_Airspeed_Backend.
Definition at line 256 of file AP_Airspeed_MS5525.cpp.
Referenced by ~AP_Airspeed_MS5525().
bool AP_Airspeed_MS5525::get_temperature (float & temperature) override virtual
Implements AP_Airspeed_Backend.
Definition at line 274 of file AP_Airspeed_MS5525.cpp.
Referenced by ~AP_Airspeed_MS5525().
bool AP_Airspeed_MS5525::init (void) override virtual
Implements AP_Airspeed_Backend.
Definition at line 60 of file AP_Airspeed_MS5525.cpp.
Referenced by ~AP_Airspeed_MS5525().
void AP_Airspeed_MS5525::measure () private
Referenced by ~AP_Airspeed_MS5525().
int32_t AP_Airspeed_MS5525::read_adc () private
Definition at line 177 of file AP_Airspeed_MS5525.cpp.
Referenced by timer(), and ~AP_Airspeed_MS5525().
bool AP_Airspeed_MS5525::read_prom (void) private
Definition at line 134 of file AP_Airspeed_MS5525.cpp.
Referenced by init(), and ~AP_Airspeed_MS5525().
void AP_Airspeed_MS5525::timer () private
Definition at line 227 of file AP_Airspeed_MS5525.cpp.
Referenced by init(), and ~AP_Airspeed_MS5525().
Member Data Documentation
int32_t AP_Airspeed_MS5525::D1 private
Definition at line 65 of file AP_Airspeed_MS5525.h.
Referenced by calculate(), and timer().
int32_t AP_Airspeed_MS5525::D2 private
Definition at line 66 of file AP_Airspeed_MS5525.h.
Referenced by calculate(), and timer().
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_Airspeed_MS5525::dev private
Definition at line 68 of file AP_Airspeed_MS5525.h.
Referenced by init(), read_adc(), read_prom(), and timer().
uint32_t AP_Airspeed_MS5525::last_sample_time_ms private
Definition at line 61 of file AP_Airspeed_MS5525.h.
Referenced by calculate(), get_differential_pressure(), and get_temperature().
uint32_t AP_Airspeed_MS5525::press_count private
Definition at line 59 of file AP_Airspeed_MS5525.h.
Referenced by calculate(), and get_differential_pressure().
float AP_Airspeed_MS5525::pressure private
Definition at line 54 of file AP_Airspeed_MS5525.h.
Referenced by get_differential_pressure(), and ~AP_Airspeed_MS5525().
float AP_Airspeed_MS5525::pressure_sum private
Definition at line 57 of file AP_Airspeed_MS5525.h.
Referenced by calculate(), and get_differential_pressure().
uint16_t AP_Airspeed_MS5525::prom[8] private
Definition at line 63 of file AP_Airspeed_MS5525.h.
Referenced by calculate(), crc4_prom(), and read_prom().
uint8_t AP_Airspeed_MS5525::state private
Definition at line 64 of file AP_Airspeed_MS5525.h.
Referenced by init(), and timer().
uint32_t AP_Airspeed_MS5525::temp_count private
Definition at line 58 of file AP_Airspeed_MS5525.h.
Referenced by calculate(), and get_temperature().
float AP_Airspeed_MS5525::temperature private
Definition at line 55 of file AP_Airspeed_MS5525.h.
Referenced by get_temperature(), and ~AP_Airspeed_MS5525().
float AP_Airspeed_MS5525::temperature_sum private
Definition at line 56 of file AP_Airspeed_MS5525.h.
Referenced by calculate(), and get_temperature().
The documentation for this class was generated from the following files:
libraries/AP_Airspeed/AP_Airspeed_MS5525.h
libraries/AP_Airspeed/AP_Airspeed_MS5525.cpp