APM:Libraries: ObjectArray< T > Class Template Reference
ObjectArray< T > Class Template Reference
#include <RingBuffer.h>
Public Member Functions
ObjectArray (uint16_t _size)
~ObjectArray (void)
uint16_t available (void) const
uint16_t space (void) const
bool empty (void) const
bool push (const T &object)
bool pop (void)
void clear (void)
bool pop (T &object)
bool push_force (const T &object)
bool remove (uint16_t n)
T * operator[] (uint16_t i)
Private Attributes
T * buffer
uint16_t size
uint16_t count
uint16_t head
Detailed Description
template<class T>
class ObjectArray< T >
Definition at line 190 of file RingBuffer.h.
Constructor & Destructor Documentation
template<class T> ObjectArray< T >::ObjectArray (uint16_t _size) inline
Definition at line 192 of file RingBuffer.h.
template<class T> ObjectArray< T >::~ObjectArray (void) inline
Definition at line 197 of file RingBuffer.h.
Member Function Documentation
template<class T> uint16_t ObjectArray< T >::available (void) const inline
Definition at line 202 of file RingBuffer.h.
template<class T> void ObjectArray< T >::clear (void) inline
Definition at line 239 of file RingBuffer.h.
template<class T> bool ObjectArray< T >::empty (void) const inline
Definition at line 212 of file RingBuffer.h.
Referenced by AP_Frsky_Telem::get_next_msg_chunk().
template<class T> T* ObjectArray< T >::operator[] (uint16_t i) inline
Definition at line 293 of file RingBuffer.h.
template<class T> bool ObjectArray< T >::pop (void) inline
Definition at line 229 of file RingBuffer.h.
template<class T> bool ObjectArray< T >::pop (T & object) inline
Definition at line 247 of file RingBuffer.h.
template<class T> bool ObjectArray< T >::push (const T & object) inline
Definition at line 217 of file RingBuffer.h.
template<class T> bool ObjectArray< T >::push_force (const T & object) inline
Definition at line 260 of file RingBuffer.h.
Referenced by AP_Frsky_Telem::queue_message().
template<class T> bool ObjectArray< T >::remove (uint16_t n) inline
Definition at line 270 of file RingBuffer.h.
Referenced by AP_Frsky_Telem::get_next_msg_chunk().
template<class T> uint16_t ObjectArray< T >::space (void) const inline
Definition at line 207 of file RingBuffer.h.
Member Data Documentation
template<class T> T* ObjectArray< T >::buffer private
Definition at line 301 of file RingBuffer.h.
template<class T> uint16_t ObjectArray< T >::count private
Definition at line 303 of file RingBuffer.h.
template<class T> uint16_t ObjectArray< T >::head private
Definition at line 304 of file RingBuffer.h.
template<class T> uint16_t ObjectArray< T >::size private
Definition at line 302 of file RingBuffer.h.
The documentation for this class was generated from the following file:
libraries/AP_HAL/utility/RingBuffer.h