APM:Libraries: RangeFinder Class Reference
RangeFinder Class Reference
#include <RangeFinder.h>
Classes
struct RangeFinder_State
Public Types
enum RangeFinder_Type {
RangeFinder_TYPE_NONE = 0, RangeFinder_TYPE_ANALOG = 1, RangeFinder_TYPE_MBI2C = 2, RangeFinder_TYPE_PLI2C = 3,
RangeFinder_TYPE_PX4 = 4, RangeFinder_TYPE_PX4_PWM = 5, RangeFinder_TYPE_BBB_PRU = 6, RangeFinder_TYPE_LWI2C = 7,
RangeFinder_TYPE_LWSER = 8, RangeFinder_TYPE_BEBOP = 9, RangeFinder_TYPE_MAVLink = 10, RangeFinder_TYPE_ULANDING = 11,
RangeFinder_TYPE_LEDDARONE = 12, RangeFinder_TYPE_MBSER = 13, RangeFinder_TYPE_TRONE = 14, RangeFinder_TYPE_PLI2CV3 = 15
}
enum RangeFinder_Function { FUNCTION_LINEAR = 0, FUNCTION_INVERTED = 1, FUNCTION_HYPERBOLA = 2 }
enum RangeFinder_Status {
RangeFinder_NotConnected = 0, RangeFinder_NoData, RangeFinder_OutOfRangeLow, RangeFinder_OutOfRangeHigh,
RangeFinder_Good
}
Public Member Functions
RangeFinder (AP_SerialManager &_serial_manager, enum Rotation orientation_default)
uint8_t num_sensors (void) const
void init (void)
void update (void)
void handle_msg (mavlink_message_t *msg)
bool has_orientation (enum Rotation orientation) const
bool find_instance (enum Rotation orientation, uint8_t &instance) const
enum Rotation get_orientation (uint8_t instance) const
uint16_t distance_cm (uint8_t instance) const
uint16_t distance_cm_orient (enum Rotation orientation) const
uint16_t voltage_mv (uint8_t instance) const
uint16_t voltage_mv_orient (enum Rotation orientation) const
int16_t max_distance_cm (uint8_t instance) const
int16_t max_distance_cm_orient (enum Rotation orientation) const
int16_t min_distance_cm (uint8_t instance) const
int16_t min_distance_cm_orient (enum Rotation orientation) const
int16_t ground_clearance_cm (uint8_t instance) const
int16_t ground_clearance_cm_orient (enum Rotation orientation) const
RangeFinder_Status status (uint8_t instance) const
RangeFinder_Status status_orient (enum Rotation orientation) const
bool has_data (uint8_t instance) const
bool has_data_orient (enum Rotation orientation) const
uint8_t range_valid_count (uint8_t instance) const
uint8_t range_valid_count_orient (enum Rotation orientation) const
void set_estimated_terrain_height (float height)
bool pre_arm_check () const
const Vector3f & get_pos_offset (uint8_t instance) const
const Vector3f & get_pos_offset_orient (enum Rotation orientation) const
Public Attributes
AP_Int8 _type [RANGEFINDER_MAX_INSTANCES]
AP_Int8 _pin [RANGEFINDER_MAX_INSTANCES]
AP_Int8 _ratiometric [RANGEFINDER_MAX_INSTANCES]
AP_Int8 _stop_pin [RANGEFINDER_MAX_INSTANCES]
AP_Int16 _settle_time_ms [RANGEFINDER_MAX_INSTANCES]
AP_Float _scaling [RANGEFINDER_MAX_INSTANCES]
AP_Float _offset [RANGEFINDER_MAX_INSTANCES]
AP_Int8 _function [RANGEFINDER_MAX_INSTANCES]
AP_Int16 _min_distance_cm [RANGEFINDER_MAX_INSTANCES]
AP_Int16 _max_distance_cm [RANGEFINDER_MAX_INSTANCES]
AP_Int8 _ground_clearance_cm [RANGEFINDER_MAX_INSTANCES]
AP_Int8 _address [RANGEFINDER_MAX_INSTANCES]
AP_Int16 _powersave_range
AP_Vector3f _pos_offset [RANGEFINDER_MAX_INSTANCES]
AP_Int8 _orientation [RANGEFINDER_MAX_INSTANCES]
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
void detect_instance (uint8_t instance)
void update_instance (uint8_t instance)
void update_pre_arm_check (uint8_t instance)
bool _add_backend (AP_RangeFinder_Backend *driver)
Private Attributes
RangeFinder_State state [RANGEFINDER_MAX_INSTANCES]
AP_RangeFinder_Backend * drivers [RANGEFINDER_MAX_INSTANCES]
uint8_t num_instances:3
float estimated_terrain_height
AP_SerialManager & serial_manager
Vector3f pos_offset_zero
Friends
class AP_RangeFinder_Backend
Detailed Description
Definition at line 31 of file RangeFinder.h.
Member Enumeration Documentation
enum RangeFinder::RangeFinder_Function
Enumerator
FUNCTION_LINEAR
FUNCTION_INVERTED
FUNCTION_HYPERBOLA
Definition at line 58 of file RangeFinder.h.
enum RangeFinder::RangeFinder_Status
Enumerator
RangeFinder_NotConnected
RangeFinder_NoData
RangeFinder_OutOfRangeLow
RangeFinder_OutOfRangeHigh
RangeFinder_Good
Definition at line 64 of file RangeFinder.h.
enum RangeFinder::RangeFinder_Type
Enumerator
RangeFinder_TYPE_NONE
RangeFinder_TYPE_ANALOG
RangeFinder_TYPE_MBI2C
RangeFinder_TYPE_PLI2C
RangeFinder_TYPE_PX4
RangeFinder_TYPE_PX4_PWM
RangeFinder_TYPE_BBB_PRU
RangeFinder_TYPE_LWI2C
RangeFinder_TYPE_LWSER
RangeFinder_TYPE_BEBOP
RangeFinder_TYPE_MAVLink
RangeFinder_TYPE_ULANDING
RangeFinder_TYPE_LEDDARONE
RangeFinder_TYPE_MBSER
RangeFinder_TYPE_TRONE
RangeFinder_TYPE_PLI2CV3
Definition at line 39 of file RangeFinder.h.
Constructor & Destructor Documentation
RangeFinder::RangeFinder (AP_SerialManager & _serial_manager, enum Rotation orientation_default)
Definition at line 527 of file RangeFinder.cpp.
Member Function Documentation
bool RangeFinder::_add_backend (AP_RangeFinder_Backend * driver) private
Definition at line 593 of file RangeFinder.cpp.
Referenced by detect_instance().
void RangeFinder::detect_instance (uint8_t instance) private
Definition at line 609 of file RangeFinder.cpp.
Referenced by init().
uint16_t RangeFinder::distance_cm (uint8_t instance) const inline
Definition at line 132 of file RangeFinder.h.
Referenced by distance_cm_orient(), DataFlash_Class::Log_Write_RFND(), loop(), NavEKF2_core::readRangeFinder(), NavEKF3_core::readRangeFinder(), AP_Proximity_RangeFinder::update(), and update_pre_arm_check().
uint16_t RangeFinder::distance_cm_orient (enum Rotation orientation) const
Definition at line 753 of file RangeFinder.cpp.
Referenced by AP_Frsky_Telem::calc_attiandrng(), and distance_cm().
bool RangeFinder::find_instance (enum Rotation orientation, uint8_t & instance) const
Definition at line 742 of file RangeFinder.cpp.
Referenced by distance_cm_orient(), get_pos_offset_orient(), ground_clearance_cm_orient(), has_data_orient(), has_orientation(), max_distance_cm_orient(), min_distance_cm_orient(), range_valid_count_orient(), status_orient(), and voltage_mv_orient().
enum Rotation RangeFinder::get_orientation (uint8_t instance) const inline
Definition at line 128 of file RangeFinder.h.
Referenced by DataFlash_Class::Log_Write_RFND(), NavEKF2_core::readRangeFinder(), NavEKF3_core::readRangeFinder(), and AP_Proximity_RangeFinder::update().
const Vector3f& RangeFinder::get_pos_offset (uint8_t instance) const inline
Definition at line 187 of file RangeFinder.h.
Referenced by get_pos_offset_orient(), NavEKF2_core::selectHeightForFusion(), and NavEKF3_core::selectHeightForFusion().
const Vector3f & RangeFinder::get_pos_offset_orient (enum Rotation orientation) const
Definition at line 868 of file RangeFinder.cpp.
Referenced by get_pos_offset().
int16_t RangeFinder::ground_clearance_cm (uint8_t instance) const inline
Definition at line 152 of file RangeFinder.h.
Referenced by ground_clearance_cm_orient().
int16_t RangeFinder::ground_clearance_cm_orient (enum Rotation orientation) const
Definition at line 789 of file RangeFinder.cpp.
Referenced by ground_clearance_cm(), NavEKF2_core::readRangeFinder(), and NavEKF3_core::readRangeFinder().
void RangeFinder::handle_msg (mavlink_message_t * msg)
Definition at line 724 of file RangeFinder.cpp.
Referenced by num_sensors().
bool RangeFinder::has_data (uint8_t instance) const
Definition at line 799 of file RangeFinder.cpp.
Referenced by ground_clearance_cm(), has_data_orient(), and AP_Proximity_RangeFinder::update().
bool RangeFinder::has_data_orient (enum Rotation orientation) const
Definition at line 808 of file RangeFinder.cpp.
Referenced by ground_clearance_cm().
bool RangeFinder::has_orientation (enum Rotation orientation) const
Definition at line 735 of file RangeFinder.cpp.
void RangeFinder::init (void)
Definition at line 549 of file RangeFinder.cpp.
Referenced by num_sensors(), and setup().
int16_t RangeFinder::max_distance_cm (uint8_t instance) const inline
Definition at line 142 of file RangeFinder.h.
Referenced by max_distance_cm_orient(), and AP_Proximity_RangeFinder::update().
int16_t RangeFinder::max_distance_cm_orient (enum Rotation orientation) const
Definition at line 771 of file RangeFinder.cpp.
Referenced by NavEKF2_core::getHeightControlLimit(), NavEKF3_core::getHeightControlLimit(), max_distance_cm(), NavEKF2_core::selectHeightForFusion(), and NavEKF3_core::selectHeightForFusion().
int16_t RangeFinder::min_distance_cm (uint8_t instance) const inline
Definition at line 147 of file RangeFinder.h.
Referenced by min_distance_cm_orient(), AP_Proximity_RangeFinder::update(), and update_pre_arm_check().
int16_t RangeFinder::min_distance_cm_orient (enum Rotation orientation) const
Definition at line 780 of file RangeFinder.cpp.
Referenced by min_distance_cm().
uint8_t RangeFinder::num_sensors (void) const inline
Definition at line 105 of file RangeFinder.h.
Referenced by setup(), and AP_Proximity_RangeFinder::update().
bool RangeFinder::pre_arm_check () const
Definition at line 831 of file RangeFinder.cpp.
Referenced by update_pre_arm_check().
uint8_t RangeFinder::range_valid_count (uint8_t instance) const inline
Definition at line 166 of file RangeFinder.h.
Referenced by range_valid_count_orient().
uint8_t RangeFinder::range_valid_count_orient (enum Rotation orientation) const
Definition at line 817 of file RangeFinder.cpp.
Referenced by range_valid_count().
void RangeFinder::set_estimated_terrain_height (float height) inline
Definition at line 175 of file RangeFinder.h.
RangeFinder::RangeFinder_Status RangeFinder::status (uint8_t instance) const
Definition at line 701 of file RangeFinder.cpp.
Referenced by has_data(), loop(), NavEKF2_core::readRangeFinder(), NavEKF3_core::readRangeFinder(), status_orient(), and update_pre_arm_check().
RangeFinder::RangeFinder_Status RangeFinder::status_orient (enum Rotation orientation) const
Definition at line 715 of file RangeFinder.cpp.
Referenced by ground_clearance_cm().
void RangeFinder::update (void)
Definition at line 577 of file RangeFinder.cpp.
Referenced by loop(), and num_sensors().
void RangeFinder::update_instance (uint8_t instance) private
void RangeFinder::update_pre_arm_check (uint8_t instance) private
Definition at line 848 of file RangeFinder.cpp.
Referenced by update().
uint16_t RangeFinder::voltage_mv (uint8_t instance) const inline
Definition at line 137 of file RangeFinder.h.
Referenced by voltage_mv_orient().
uint16_t RangeFinder::voltage_mv_orient (enum Rotation orientation) const
Definition at line 762 of file RangeFinder.cpp.
Referenced by voltage_mv().
Friends And Related Function Documentation
friend class AP_RangeFinder_Backend friend
Definition at line 34 of file RangeFinder.h.
Member Data Documentation
AP_Int8 RangeFinder::_address[RANGEFINDER_MAX_INSTANCES]
Definition at line 97 of file RangeFinder.h.
Referenced by detect_instance(), and AP_RangeFinder_LightWareI2C::get_reading().
AP_Int8 RangeFinder::_function[RANGEFINDER_MAX_INSTANCES]
Definition at line 93 of file RangeFinder.h.
Referenced by AP_RangeFinder_analog::update().
AP_Int8 RangeFinder::_ground_clearance_cm[RANGEFINDER_MAX_INSTANCES]
Definition at line 96 of file RangeFinder.h.
Referenced by update_pre_arm_check().
AP_Int16 RangeFinder::_max_distance_cm[RANGEFINDER_MAX_INSTANCES]
Definition at line 95 of file RangeFinder.h.
Referenced by AP_RangeFinder_analog::update(), and AP_RangeFinder_Backend::update_status().
AP_Int16 RangeFinder::_min_distance_cm[RANGEFINDER_MAX_INSTANCES]
Definition at line 94 of file RangeFinder.h.
Referenced by AP_RangeFinder_Backend::update_status().
AP_Float RangeFinder::_offset[RANGEFINDER_MAX_INSTANCES]
Definition at line 92 of file RangeFinder.h.
Referenced by AP_RangeFinder_analog::update(), and AP_RangeFinder_PX4_PWM::update().
AP_Int8 RangeFinder::_orientation[RANGEFINDER_MAX_INSTANCES]
Definition at line 100 of file RangeFinder.h.
Referenced by find_instance(), and RangeFinder().
AP_Int8 RangeFinder::_pin[RANGEFINDER_MAX_INSTANCES]
Definition at line 87 of file RangeFinder.h.
Referenced by AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_RangeFinder_analog::detect(), and AP_RangeFinder_analog::update_voltage().
AP_Vector3f RangeFinder::_pos_offset[RANGEFINDER_MAX_INSTANCES]
Definition at line 99 of file RangeFinder.h.
AP_Int16 RangeFinder::_powersave_range
Definition at line 98 of file RangeFinder.h.
Referenced by AP_RangeFinder_Backend::out_of_range().
AP_Int8 RangeFinder::_ratiometric[RANGEFINDER_MAX_INSTANCES]
Definition at line 88 of file RangeFinder.h.
Referenced by AP_RangeFinder_analog::update_voltage().
AP_Float RangeFinder::_scaling[RANGEFINDER_MAX_INSTANCES]
Definition at line 91 of file RangeFinder.h.
Referenced by AP_RangeFinder_analog::update(), and AP_RangeFinder_PX4_PWM::update().
AP_Int16 RangeFinder::_settle_time_ms[RANGEFINDER_MAX_INSTANCES]
Definition at line 90 of file RangeFinder.h.
Referenced by AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_RangeFinder_PX4_PWM::update(), and AP_RangeFinder_analog::update_voltage().
AP_Int8 RangeFinder::_stop_pin[RANGEFINDER_MAX_INSTANCES]
Definition at line 89 of file RangeFinder.h.
Referenced by AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_RangeFinder_PX4_PWM::update(), and AP_RangeFinder_analog::update_voltage().
AP_Int8 RangeFinder::_type[RANGEFINDER_MAX_INSTANCES]
Definition at line 86 of file RangeFinder.h.
Referenced by detect_instance(), handle_msg(), loop(), pre_arm_check(), status(), and update().
AP_RangeFinder_Backend* RangeFinder::drivers[RANGEFINDER_MAX_INSTANCES] private
Definition at line 194 of file RangeFinder.h.
Referenced by _add_backend(), detect_instance(), handle_msg(), init(), pre_arm_check(), RangeFinder(), status(), and update().
float RangeFinder::estimated_terrain_height private
Definition at line 196 of file RangeFinder.h.
Referenced by AP_RangeFinder_Backend::out_of_range(), and set_estimated_terrain_height().
uint8_t RangeFinder::num_instances private
Definition at line 195 of file RangeFinder.h.
Referenced by _add_backend(), distance_cm(), find_instance(), get_orientation(), handle_msg(), init(), num_sensors(), pre_arm_check(), and update().
Vector3f RangeFinder::pos_offset_zero private
Definition at line 198 of file RangeFinder.h.
Referenced by get_pos_offset_orient().
AP_SerialManager& RangeFinder::serial_manager private
Definition at line 197 of file RangeFinder.h.
Referenced by detect_instance().
RangeFinder_State RangeFinder::state[RANGEFINDER_MAX_INSTANCES] private
Definition at line 193 of file RangeFinder.h.
Referenced by detect_instance(), has_data(), init(), pre_arm_check(), RangeFinder(), status(), update(), and update_pre_arm_check().
const AP_Param::GroupInfo RangeFinder::var_info static
Definition at line 102 of file RangeFinder.h.
Referenced by RangeFinder(), and setup().
The documentation for this class was generated from the following files:
libraries/AP_RangeFinder/RangeFinder.h
libraries/AP_RangeFinder/RangeFinder.cpp