APM:Libraries: AP_Airspeed_Backend Class Reference
AP_Airspeed_Backend Class Reference abstract
#include <AP_Airspeed_Backend.h>
Public Member Functions
AP_Airspeed_Backend (AP_Airspeed &frontend)
virtual ~AP_Airspeed_Backend ()
virtual bool init (void)=0
virtual bool get_differential_pressure (float &pressure)=0
virtual bool get_temperature (float &temperature)=0
Protected Member Functions
int8_t get_pin (void) const
float get_psi_range (void) const
uint8_t get_bus (void) const
Protected Attributes
AP_HAL::Semaphore * sem
Private Attributes
AP_Airspeed & frontend
Detailed Description
Definition at line 26 of file AP_Airspeed_Backend.h.
Constructor & Destructor Documentation
AP_Airspeed_Backend::AP_Airspeed_Backend (AP_Airspeed & frontend)
Definition at line 26 of file AP_Airspeed_Backend.cpp.
AP_Airspeed_Backend::~AP_Airspeed_Backend (void) virtual
Definition at line 32 of file AP_Airspeed_Backend.cpp.
Member Function Documentation
uint8_t AP_Airspeed_Backend::get_bus (void) const protected
Definition at line 48 of file AP_Airspeed_Backend.cpp.
Referenced by AP_Airspeed_MS5525::init().
virtual bool AP_Airspeed_Backend::get_differential_pressure (float & pressure) pure virtual
Implemented in AP_Airspeed_MS4525, AP_Airspeed_MS5525, and AP_Airspeed_Analog.
Referenced by AP_Airspeed::get_pressure().
int8_t AP_Airspeed_Backend::get_pin (void) const protected
Definition at line 38 of file AP_Airspeed_Backend.cpp.
Referenced by AP_Airspeed_Analog::AP_Airspeed_Analog(), and AP_Airspeed_Analog::get_differential_pressure().
float AP_Airspeed_Backend::get_psi_range (void) const protected
Definition at line 43 of file AP_Airspeed_Backend.cpp.
Referenced by AP_Airspeed_MS4525::_get_pressure(), and AP_Airspeed_Analog::get_differential_pressure().
virtual bool AP_Airspeed_Backend::get_temperature (float & temperature) pure virtual
Implemented in AP_Airspeed_MS4525, AP_Airspeed_MS5525, and AP_Airspeed_Analog.
Referenced by AP_Airspeed::get_airspeed_ratio(), and AP_Airspeed::get_temperature().
virtual bool AP_Airspeed_Backend::init (void) pure virtual
Implemented in AP_Airspeed_MS4525, AP_Airspeed_MS5525, and AP_Airspeed_Analog.
Referenced by AP_Airspeed::init().
Member Data Documentation
AP_Airspeed& AP_Airspeed_Backend::frontend private
Definition at line 49 of file AP_Airspeed_Backend.h.
Referenced by get_bus(), get_pin(), and get_psi_range().
AP_HAL::Semaphore* AP_Airspeed_Backend::sem protected
Definition at line 46 of file AP_Airspeed_Backend.h.
Referenced by AP_Airspeed_MS4525::_collect(), AP_Airspeed_Backend(), AP_Airspeed_MS5525::calculate(), AP_Airspeed_MS4525::get_differential_pressure(), AP_Airspeed_MS5525::get_differential_pressure(), AP_Airspeed_MS5525::get_temperature(), AP_Airspeed_MS4525::get_temperature(), and ~AP_Airspeed_Backend().
The documentation for this class was generated from the following files:
libraries/AP_Airspeed/AP_Airspeed_Backend.h
libraries/AP_Airspeed/AP_Airspeed_Backend.cpp