APM:Libraries: AP_BattMonitor_SMBus_Solo Class Reference
AP_BattMonitor_SMBus_Solo Class Reference
#include <AP_BattMonitor_SMBus_Solo.h>
Public Member Functions
AP_BattMonitor_SMBus_Solo (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
void read () override
Read the battery voltage and current. Should be called at 10hz.
Public Member Functions inherited from AP_BattMonitor_SMBus
AP_BattMonitor_SMBus (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state)
Constructor.
virtual ~AP_BattMonitor_SMBus ()
Public Member Functions inherited from AP_BattMonitor_Backend
AP_BattMonitor_Backend (AP_BattMonitor &mon, uint8_t instance, AP_BattMonitor::BattMonitor_State &mon_state)
virtual ~AP_BattMonitor_Backend (void)
virtual void init ()
uint8_t capacity_remaining_pct () const
capacity_remaining_pct - returns the % battery capacity remaining (0 ~ 100)
void set_capacity (uint32_t capacity)
set capacity for this instance
int32_t get_capacity () const
get capacity for this instance
Private Member Functions
void timer (void)
bool read_word (uint8_t reg, uint16_t &data) const
uint8_t read_block (uint8_t reg, uint8_t *data, uint8_t max_len, bool append_zero) const
uint8_t get_PEC (const uint8_t i2c_addr, uint8_t cmd, bool reading, const uint8_t buff[], uint8_t len) const
get_PEC - calculate packet error correction code of buffer
Private Attributes
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
uint8_t _button_press_count
Additional Inherited Members
Protected Attributes inherited from AP_BattMonitor_Backend
AP_BattMonitor & _mon
AP_BattMonitor::BattMonitor_State & _state
uint8_t _instance
Detailed Description
Definition at line 9 of file AP_BattMonitor_SMBus_Solo.h.
Constructor & Destructor Documentation
AP_BattMonitor_SMBus_Solo::AP_BattMonitor_SMBus_Solo (AP_BattMonitor & mon, uint8_t instance, AP_BattMonitor::BattMonitor_State & mon_state, AP_HAL::OwnPtr< AP_HAL::I2CDevice > dev)
Definition at line 35 of file AP_BattMonitor_SMBus_Solo.cpp.
Member Function Documentation
uint8_t AP_BattMonitor_SMBus_Solo::get_PEC (const uint8_t i2c_addr, uint8_t cmd, bool reading, const uint8_t buff[], uint8_t len) const private
get_PEC - calculate packet error correction code of buffer
Definition at line 176 of file AP_BattMonitor_SMBus_Solo.cpp.
Referenced by read_block(), and read_word().
void AP_BattMonitor_SMBus_Solo::read (void) override virtual
Read the battery voltage and current. Should be called at 10hz.
Implements AP_BattMonitor_Backend.
Definition at line 45 of file AP_BattMonitor_SMBus_Solo.cpp.
uint8_t AP_BattMonitor_SMBus_Solo::read_block (uint8_t reg, uint8_t * data, uint8_t max_len, bool append_zero) const private
Definition at line 138 of file AP_BattMonitor_SMBus_Solo.cpp.
Referenced by timer().
bool AP_BattMonitor_SMBus_Solo::read_word (uint8_t reg, uint16_t & data) const private
Definition at line 115 of file AP_BattMonitor_SMBus_Solo.cpp.
Referenced by timer().
void AP_BattMonitor_SMBus_Solo::timer (void) private
Definition at line 50 of file AP_BattMonitor_SMBus_Solo.cpp.
Referenced by AP_BattMonitor_SMBus_Solo().
Member Data Documentation
uint8_t AP_BattMonitor_SMBus_Solo::_button_press_count private
Definition at line 37 of file AP_BattMonitor_SMBus_Solo.h.
Referenced by timer().
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_BattMonitor_SMBus_Solo::_dev private
Definition at line 36 of file AP_BattMonitor_SMBus_Solo.h.
Referenced by AP_BattMonitor_SMBus_Solo(), read_block(), and read_word().
The documentation for this class was generated from the following files:
libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.h
libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.cpp