APM:Libraries: AP_Airspeed_MS4525 Class Reference
AP_Airspeed_MS4525 Class Reference
#include <AP_Airspeed_MS4525.h>
Public Member Functions
AP_Airspeed_MS4525 (AP_Airspeed &frontend)
~AP_Airspeed_MS4525 (void)
bool init () override
bool get_differential_pressure (float &pressure) override
bool get_temperature (float &temperature) override
Public Member Functions inherited from AP_Airspeed_Backend
AP_Airspeed_Backend (AP_Airspeed &frontend)
virtual ~AP_Airspeed_Backend ()
Private Member Functions
void _measure ()
void _collect ()
void _timer ()
void _voltage_correction (float &diff_press_pa, float &temperature)
float _get_pressure (int16_t dp_raw) const
float _get_temperature (int16_t dT_raw) const
Private Attributes
float _temp_sum
float _press_sum
uint32_t _temp_count
uint32_t _press_count
float _temperature
float _pressure
uint32_t _last_sample_time_ms
uint32_t _measurement_started_ms
AP_HAL::OwnPtr< AP_HAL::I2CDevice > _dev
Additional Inherited Members
Protected Member Functions inherited from AP_Airspeed_Backend
int8_t get_pin (void) const
float get_psi_range (void) const
uint8_t get_bus (void) const
Protected Attributes inherited from AP_Airspeed_Backend
AP_HAL::Semaphore * sem
Detailed Description
Definition at line 30 of file AP_Airspeed_MS4525.h.
Constructor & Destructor Documentation
AP_Airspeed_MS4525::AP_Airspeed_MS4525 (AP_Airspeed & frontend)
Definition at line 38 of file AP_Airspeed_MS4525.cpp.
AP_Airspeed_MS4525::~AP_Airspeed_MS4525 (void) inline
Definition at line 34 of file AP_Airspeed_MS4525.h.
Member Function Documentation
void AP_Airspeed_MS4525::_collect () private
Definition at line 130 of file AP_Airspeed_MS4525.cpp.
Referenced by _timer(), init(), and ~AP_Airspeed_MS4525().
float AP_Airspeed_MS4525::_get_pressure (int16_t dp_raw) const private
Definition at line 109 of file AP_Airspeed_MS4525.cpp.
Referenced by _collect(), and ~AP_Airspeed_MS4525().
float AP_Airspeed_MS4525::_get_temperature (int16_t dT_raw) const private
Definition at line 123 of file AP_Airspeed_MS4525.cpp.
Referenced by _collect(), and ~AP_Airspeed_MS4525().
void AP_Airspeed_MS4525::_measure () private
Definition at line 92 of file AP_Airspeed_MS4525.cpp.
Referenced by _timer(), init(), and ~AP_Airspeed_MS4525().
void AP_Airspeed_MS4525::_timer () private
Definition at line 219 of file AP_Airspeed_MS4525.cpp.
Referenced by init(), and ~AP_Airspeed_MS4525().
void AP_Airspeed_MS4525::_voltage_correction (float & diff_press_pa, float & temperature) private
correct for 5V rail voltage if the system_power ORB topic is available
See http://uav.tridgell.net/MS4525/MS4525-offset.png for a graph of offset versus voltage for 3 sensors
Definition at line 202 of file AP_Airspeed_MS4525.cpp.
Referenced by _collect(), and ~AP_Airspeed_MS4525().
bool AP_Airspeed_MS4525::get_differential_pressure (float & pressure) override virtual
Implements AP_Airspeed_Backend.
Definition at line 233 of file AP_Airspeed_MS4525.cpp.
Referenced by ~AP_Airspeed_MS4525().
bool AP_Airspeed_MS4525::get_temperature (float & temperature) override virtual
Implements AP_Airspeed_Backend.
Definition at line 251 of file AP_Airspeed_MS4525.cpp.
Referenced by ~AP_Airspeed_MS4525().
bool AP_Airspeed_MS4525::init (void) override virtual
Implements AP_Airspeed_Backend.
Definition at line 44 of file AP_Airspeed_MS4525.cpp.
Referenced by ~AP_Airspeed_MS4525().
Member Data Documentation
AP_HAL::OwnPtr<AP_HAL::I2CDevice> AP_Airspeed_MS4525::_dev private
Definition at line 61 of file AP_Airspeed_MS4525.h.
Referenced by _collect(), _measure(), and init().
uint32_t AP_Airspeed_MS4525::_last_sample_time_ms private
Definition at line 59 of file AP_Airspeed_MS4525.h.
Referenced by _collect(), get_differential_pressure(), get_temperature(), and init().
uint32_t AP_Airspeed_MS4525::_measurement_started_ms private
Definition at line 60 of file AP_Airspeed_MS4525.h.
Referenced by _collect(), _measure(), and _timer().
uint32_t AP_Airspeed_MS4525::_press_count private
Definition at line 56 of file AP_Airspeed_MS4525.h.
Referenced by _collect(), and get_differential_pressure().
float AP_Airspeed_MS4525::_press_sum private
Definition at line 54 of file AP_Airspeed_MS4525.h.
Referenced by _collect(), and get_differential_pressure().
float AP_Airspeed_MS4525::_pressure private
Definition at line 58 of file AP_Airspeed_MS4525.h.
Referenced by get_differential_pressure().
uint32_t AP_Airspeed_MS4525::_temp_count private
Definition at line 55 of file AP_Airspeed_MS4525.h.
Referenced by _collect(), and get_temperature().
float AP_Airspeed_MS4525::_temp_sum private
Definition at line 53 of file AP_Airspeed_MS4525.h.
Referenced by _collect(), and get_temperature().
float AP_Airspeed_MS4525::_temperature private
Definition at line 57 of file AP_Airspeed_MS4525.h.
Referenced by get_temperature().
The documentation for this class was generated from the following files:
libraries/AP_Airspeed/AP_Airspeed_MS4525.h
libraries/AP_Airspeed/AP_Airspeed_MS4525.cpp