APM:Libraries: RC_Channel Class Reference
RC_Channel Class Reference
Object managing one RC channel.
#include <RC_Channel.h>
Public Types
enum LimitValue { RC_CHANNEL_LIMIT_TRIM, RC_CHANNEL_LIMIT_MIN, RC_CHANNEL_LIMIT_MAX }
Public Member Functions
RC_Channel (void)
void load_eeprom (void)
void save_eeprom (void)
void save_trim (void)
void set_range (uint16_t high)
void set_angle (uint16_t angle)
bool get_reverse (void) const
void set_default_dead_zone (int16_t dzone)
uint16_t get_dead_zone (void) const
int16_t get_control_mid () const
void set_pwm (int16_t pwm)
void set_pwm_no_deadzone (int16_t pwm)
int16_t pwm_to_angle_dz_trim (uint16_t dead_zone, uint16_t trim)
float norm_input ()
float norm_input_dz ()
uint8_t percent_input ()
int16_t pwm_to_range ()
int16_t pwm_to_range_dz (uint16_t dead_zone)
uint16_t read () const
void input ()
bool in_trim_dz ()
int16_t get_radio_in () const
void set_radio_in (int16_t val)
int16_t get_control_in () const
void set_control_in (int16_t val)
int16_t get_control_in_zero_dz (void)
int16_t get_radio_min () const
void set_radio_min (int16_t val)
int16_t get_radio_max () const
void set_radio_max (int16_t val)
int16_t get_radio_trim () const
void set_radio_trim (int16_t val)
void save_radio_trim ()
bool min_max_configured () const
Static Public Attributes
static const struct AP_Param::GroupInfo var_info []
Private Member Functions
int16_t pwm_to_angle ()
int16_t pwm_to_angle_dz (uint16_t dead_zone)
Private Attributes
int16_t radio_in
int16_t control_in
AP_Int16 radio_min
AP_Int16 radio_trim
AP_Int16 radio_max
AP_Int8 reversed
AP_Int16 dead_zone
uint8_t type_in
int16_t high_in
uint8_t ch_in
Friends
class SRV_Channels
class RC_Channels
Detailed Description
Object managing one RC channel.
Definition at line 15 of file RC_Channel.h.
Member Enumeration Documentation
enum RC_Channel::LimitValue
Enumerator
RC_CHANNEL_LIMIT_TRIM
RC_CHANNEL_LIMIT_MIN
RC_CHANNEL_LIMIT_MAX
Definition at line 23 of file RC_Channel.h.
Constructor & Destructor Documentation
RC_Channel::RC_Channel (void)
Definition at line 78 of file RC_Channel.cpp.
Member Function Documentation
int16_t RC_Channel::get_control_in () const inline
Definition at line 82 of file RC_Channel.h.
int16_t RC_Channel::get_control_in_zero_dz (void)
Definition at line 257 of file RC_Channel.cpp.
Referenced by set_control_in().
int16_t RC_Channel::get_control_mid () const
Definition at line 143 of file RC_Channel.cpp.
Referenced by get_dead_zone().
uint16_t RC_Channel::get_dead_zone (void) const inline
Definition at line 39 of file RC_Channel.h.
int16_t RC_Channel::get_radio_in () const inline
Definition at line 79 of file RC_Channel.h.
Referenced by AP_Mount_Backend::angle_input(), AP_Tuning::check_input(), AP_Tuning::check_selector_switch(), SRV_Channels::copy_radio_in_out(), SRV_Channel::output_ch(), and SRV_Channels::set_trim_to_radio_in_for().
int16_t RC_Channel::get_radio_max () const inline
Definition at line 91 of file RC_Channel.h.
Referenced by AP_Mount_Backend::angle_input(), and stability_test().
int16_t RC_Channel::get_radio_min () const inline
Definition at line 88 of file RC_Channel.h.
Referenced by AP_Mount_Backend::angle_input(), and stability_test().
int16_t RC_Channel::get_radio_trim () const inline
Definition at line 94 of file RC_Channel.h.
Referenced by SRV_Channel::output_ch().
bool RC_Channel::get_reverse (void) const
Definition at line 104 of file RC_Channel.cpp.
Referenced by AP_Mount_Backend::angle_input().
bool RC_Channel::in_trim_dz ()
Definition at line 337 of file RC_Channel.cpp.
void RC_Channel::input ()
Definition at line 323 of file RC_Channel.cpp.
Referenced by get_dead_zone().
void RC_Channel::load_eeprom (void)
Definition at line 162 of file RC_Channel.cpp.
bool RC_Channel::min_max_configured () const inline
Definition at line 98 of file RC_Channel.h.
float RC_Channel::norm_input ()
Definition at line 268 of file RC_Channel.cpp.
Referenced by get_dead_zone().
float RC_Channel::norm_input_dz ()
Definition at line 287 of file RC_Channel.cpp.
Referenced by get_dead_zone().
uint8_t RC_Channel::percent_input ()
Definition at line 307 of file RC_Channel.cpp.
Referenced by get_dead_zone().
int16_t RC_Channel::pwm_to_angle () private
Definition at line 219 of file RC_Channel.cpp.
Referenced by set_pwm().
int16_t RC_Channel::pwm_to_angle_dz (uint16_t dead_zone) private
Definition at line 209 of file RC_Channel.cpp.
Referenced by get_control_in_zero_dz(), pwm_to_angle(), and set_pwm_no_deadzone().
int16_t RC_Channel::pwm_to_angle_dz_trim (uint16_t dead_zone, uint16_t trim)
Definition at line 185 of file RC_Channel.cpp.
Referenced by get_dead_zone(), and pwm_to_angle_dz().
int16_t RC_Channel::pwm_to_range ()
Definition at line 251 of file RC_Channel.cpp.
Referenced by get_dead_zone(), and set_pwm().
int16_t RC_Channel::pwm_to_range_dz (uint16_t dead_zone)
Definition at line 230 of file RC_Channel.cpp.
Referenced by get_control_in_zero_dz(), get_dead_zone(), pwm_to_range(), and set_pwm_no_deadzone().
uint16_t RC_Channel::read (void) const
Definition at line 329 of file RC_Channel.cpp.
Referenced by AnalogIn_ADS1115::_update(), SRV_Channels::copy_radio_in_out(), and get_dead_zone().
void RC_Channel::save_eeprom (void)
Definition at line 171 of file RC_Channel.cpp.
void RC_Channel::save_radio_trim () inline
Definition at line 96 of file RC_Channel.h.
Referenced by SRV_Channels::set_trim_to_radio_in_for().
void RC_Channel::save_trim (void)
void RC_Channel::set_angle (uint16_t angle)
Definition at line 91 of file RC_Channel.cpp.
Referenced by setup().
void RC_Channel::set_control_in (int16_t val) inline
Definition at line 83 of file RC_Channel.h.
void RC_Channel::set_default_dead_zone (int16_t dzone)
Definition at line 98 of file RC_Channel.cpp.
Referenced by setup().
void RC_Channel::set_pwm (int16_t pwm)
Definition at line 111 of file RC_Channel.cpp.
Referenced by get_dead_zone(), and RC_Channels::set_pwm_all().
void RC_Channel::set_pwm_no_deadzone (int16_t pwm)
Definition at line 127 of file RC_Channel.cpp.
Referenced by get_dead_zone().
void RC_Channel::set_radio_in (int16_t val) inline
Definition at line 80 of file RC_Channel.h.
Referenced by SRV_Channels::set_output_limit().
void RC_Channel::set_radio_max (int16_t val) inline
Definition at line 92 of file RC_Channel.h.
Referenced by setup().
void RC_Channel::set_radio_min (int16_t val) inline
Definition at line 89 of file RC_Channel.h.
Referenced by setup().
void RC_Channel::set_radio_trim (int16_t val) inline
Definition at line 95 of file RC_Channel.h.
Referenced by SRV_Channels::set_trim_to_radio_in_for().
void RC_Channel::set_range (uint16_t high)
Definition at line 84 of file RC_Channel.cpp.
Referenced by setup().
Friends And Related Function Documentation
friend class RC_Channels friend
Definition at line 18 of file RC_Channel.h.
friend class SRV_Channels friend
Definition at line 17 of file RC_Channel.h.
Member Data Documentation
uint8_t RC_Channel::ch_in private
Definition at line 122 of file RC_Channel.h.
Referenced by input(), RC_Channels::RC_Channels(), and read().
int16_t RC_Channel::control_in private
Definition at line 109 of file RC_Channel.h.
Referenced by get_control_in(), set_control_in(), set_pwm(), and set_pwm_no_deadzone().
AP_Int16 RC_Channel::dead_zone private
Definition at line 116 of file RC_Channel.h.
Referenced by get_control_mid(), get_dead_zone(), in_trim_dz(), load_eeprom(), norm_input_dz(), pwm_to_angle(), pwm_to_range(), save_eeprom(), and set_default_dead_zone().
int16_t RC_Channel::high_in private
Definition at line 119 of file RC_Channel.h.
Referenced by get_control_mid(), pwm_to_angle_dz_trim(), pwm_to_range_dz(), set_angle(), and set_range().
int16_t RC_Channel::radio_in private
Definition at line 106 of file RC_Channel.h.
Referenced by get_radio_in(), in_trim_dz(), input(), norm_input(), norm_input_dz(), percent_input(), pwm_to_angle_dz_trim(), pwm_to_range_dz(), set_pwm(), set_pwm_no_deadzone(), and set_radio_in().
AP_Int16 RC_Channel::radio_max private
Definition at line 113 of file RC_Channel.h.
Referenced by get_control_mid(), get_radio_max(), load_eeprom(), min_max_configured(), norm_input(), norm_input_dz(), percent_input(), pwm_to_angle_dz_trim(), pwm_to_range_dz(), save_eeprom(), set_radio_max(), and SRV_Channels::upgrade_parameters().
AP_Int16 RC_Channel::radio_min private
Definition at line 111 of file RC_Channel.h.
Referenced by get_control_mid(), get_radio_min(), load_eeprom(), min_max_configured(), norm_input(), norm_input_dz(), percent_input(), pwm_to_angle_dz_trim(), pwm_to_range_dz(), save_eeprom(), set_radio_min(), and SRV_Channels::upgrade_parameters().
AP_Int16 RC_Channel::radio_trim private
Definition at line 112 of file RC_Channel.h.
Referenced by get_radio_trim(), in_trim_dz(), load_eeprom(), norm_input(), norm_input_dz(), pwm_to_angle_dz(), save_eeprom(), save_radio_trim(), set_radio_trim(), and SRV_Channels::upgrade_parameters().
AP_Int8 RC_Channel::reversed private
Definition at line 115 of file RC_Channel.h.
Referenced by get_control_mid(), get_reverse(), load_eeprom(), norm_input(), norm_input_dz(), percent_input(), pwm_to_angle_dz_trim(), pwm_to_range_dz(), save_eeprom(), and SRV_Channels::upgrade_parameters().
uint8_t RC_Channel::type_in private
Definition at line 118 of file RC_Channel.h.
Referenced by get_control_in_zero_dz(), get_control_mid(), set_angle(), set_pwm(), set_pwm_no_deadzone(), and set_range().
const AP_Param::GroupInfo RC_Channel::var_info static
Definition at line 74 of file RC_Channel.h.
Referenced by RC_Channel().
The documentation for this class was generated from the following files:
libraries/RC_Channel/RC_Channel.h
libraries/RC_Channel/RC_Channel.cpp