APM:Libraries: HALSITL::UARTDriver Class Reference
HALSITL::UARTDriver Class Reference
#include <UARTDriver.h>
Public Member Functions
UARTDriver (const uint8_t portNumber, SITL_State *sitlState)
void begin (uint32_t b)
void begin (uint32_t b, uint16_t rxS, uint16_t txS)
void end ()
void flush ()
bool is_initialized ()
void set_blocking_writes (bool blocking)
bool tx_pending ()
uint32_t available () override
uint32_t txspace () override
int16_t read () override
size_t write (uint8_t c)
size_t write (const uint8_t *buffer, size_t size)
enum flow_control get_flow_control (void)
void _timer_tick (void)
Public Member Functions inherited from AP_HAL::UARTDriver
UARTDriver ()
virtual void set_flow_control (enum flow_control flow_control_setting)
void printf (const char *s,...) FMT_PRINTF(2
void void vprintf (const char *s, va_list ap)
Public Member Functions inherited from AP_HAL::BetterStream
BetterStream (void)
Public Member Functions inherited from AP_HAL::Print
Print ()
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Static Public Member Functions
static UARTDriver * from (AP_HAL::UARTDriver *uart)
Public Attributes
int _fd
Private Member Functions
void _tcp_start_connection (uint16_t port, bool wait_for_connection)
void _uart_start_connection (void)
void _check_reconnect ()
void _tcp_start_client (const char *address, uint16_t port)
void _check_connection (void)
Static Private Member Functions
static bool _select_check (int)
static void _set_nonblocking (int)
Private Attributes
uint8_t _portNumber
bool _connected = false
bool _use_send_recv = false
int _listen_fd
int _serial_port
bool _nonblocking_writes
ByteBuffer _readbuffer {16384}
ByteBuffer _writebuffer {16384}
const char * _uart_path
uint32_t _uart_baudrate
const char * _tcp_client_addr
SITL_State * _sitlState
Static Private Attributes
static bool _console
Friends
class HALSITL::SITL_State
Additional Inherited Members
Public Types inherited from AP_HAL::UARTDriver
enum flow_control { FLOW_CONTROL_DISABLE =0, FLOW_CONTROL_ENABLE =1, FLOW_CONTROL_AUTO =2 }
Detailed Description
Definition at line 12 of file UARTDriver.h.
Constructor & Destructor Documentation
HALSITL::UARTDriver::UARTDriver (const uint8_t portNumber, SITL_State * sitlState) inline
Definition at line 16 of file UARTDriver.h.
Member Function Documentation
void UARTDriver::_check_connection (void) private
Definition at line 349 of file UARTDriver.cpp.
Referenced by available(), and txspace().
void UARTDriver::_check_reconnect (void) private
Definition at line 397 of file UARTDriver.cpp.
Referenced by _timer_tick().
bool UARTDriver::_select_check (int fd) static private
Definition at line 370 of file UARTDriver.cpp.
Referenced by _check_connection(), and _timer_tick().
void UARTDriver::_set_nonblocking (int fd) static private
Definition at line 391 of file UARTDriver.cpp.
Referenced by begin(), HALSITL::SITL_State::gps2_pipe(), and HALSITL::SITL_State::gps_pipe().
void UARTDriver::_tcp_start_client (const char * address, uint16_t port) private
Definition at line 252 of file UARTDriver.cpp.
Referenced by begin().
void UARTDriver::_tcp_start_connection (uint16_t port, bool wait_for_connection) private
Definition at line 164 of file UARTDriver.cpp.
Referenced by begin().
void UARTDriver::_timer_tick (void)
Definition at line 405 of file UARTDriver.cpp.
Referenced by HALSITL::Scheduler::_run_io_procs(), and get_flow_control().
void UARTDriver::_uart_start_connection (void) private
Definition at line 303 of file UARTDriver.cpp.
Referenced by _check_reconnect(), and begin().
uint32_t UARTDriver::available (void) override virtual
Implements AP_HAL::Stream.
Definition at line 104 of file UARTDriver.cpp.
Referenced by read(), and tx_pending().
void HALSITL::UARTDriver::begin (uint32_t b) inline virtual
Implements AP_HAL::UARTDriver.
Definition at line 29 of file UARTDriver.h.
void UARTDriver::begin (uint32_t baud, uint16_t rxSpace, uint16_t txSpace) virtual
Extended port open method
Allows for both opening with specified buffer sizes, and re-opening to adjust a subset of the port's settings.
Note
Buffer sizes greater than ::_max_buffer_size will be rounded down.
Parameters
baud Selects the speed that the port will be configured to. If zero, the port speed is left unchanged.
rxSpace Sets the receive buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_rx_buffer_size if it is currently closed.
txSpace Sets the transmit buffer size for the port. If zero then the buffer size is left unchanged if the port is open, or set to ::_default_tx_buffer_size if it is currently closed.
Implements AP_HAL::UARTDriver.
Definition at line 50 of file UARTDriver.cpp.
void UARTDriver::end () virtual
Implements AP_HAL::UARTDriver.
Definition at line 100 of file UARTDriver.cpp.
Referenced by begin().
void UARTDriver::flush (void) virtual
Implements AP_HAL::UARTDriver.
Definition at line 134 of file UARTDriver.cpp.
Referenced by begin().
static UARTDriver* HALSITL::UARTDriver::from (AP_HAL::UARTDriver * uart) inline static
Definition at line 24 of file UARTDriver.h.
Referenced by HALSITL::Scheduler::_run_io_procs().
enum flow_control HALSITL::UARTDriver::get_flow_control (void) inline virtual
Reimplemented from AP_HAL::UARTDriver.
Definition at line 60 of file UARTDriver.h.
bool HALSITL::UARTDriver::is_initialized () inline virtual
Implements AP_HAL::UARTDriver.
Definition at line 35 of file UARTDriver.h.
int16_t UARTDriver::read (void) override virtual
Implements AP_HAL::Stream.
Definition at line 124 of file UARTDriver.cpp.
Referenced by _timer_tick(), and tx_pending().
void HALSITL::UARTDriver::set_blocking_writes (bool blocking) inline virtual
Implements AP_HAL::UARTDriver.
Definition at line 39 of file UARTDriver.h.
bool HALSITL::UARTDriver::tx_pending () inline virtual
Implements AP_HAL::UARTDriver.
Definition at line 44 of file UARTDriver.h.
uint32_t UARTDriver::txspace (void) override virtual
Implements AP_HAL::Stream.
Definition at line 115 of file UARTDriver.cpp.
Referenced by tx_pending(), and write().
size_t UARTDriver::write (uint8_t c) virtual
Implements AP_HAL::Print.
Definition at line 138 of file UARTDriver.cpp.
Referenced by _timer_tick(), and tx_pending().
size_t UARTDriver::write (const uint8_t * buffer, size_t size) virtual
Implements AP_HAL::Print.
Definition at line 147 of file UARTDriver.cpp.
Friends And Related Function Documentation
friend class HALSITL::SITL_State friend
Definition at line 14 of file UARTDriver.h.
Member Data Documentation
bool HALSITL::UARTDriver::_connected = false private
Definition at line 66 of file UARTDriver.h.
Referenced by _check_connection(), _tcp_start_client(), _tcp_start_connection(), _timer_tick(), _uart_start_connection(), available(), begin(), and txspace().
bool UARTDriver::_console static private
Definition at line 70 of file UARTDriver.h.
Referenced by HALSITL::SITL_State::_parse_command_line(), _tcp_start_connection(), and _timer_tick().
int HALSITL::UARTDriver::_fd
Definition at line 58 of file UARTDriver.h.
Referenced by _check_connection(), _tcp_start_client(), _tcp_start_connection(), _timer_tick(), _uart_start_connection(), begin(), and UARTDriver().
int HALSITL::UARTDriver::_listen_fd private
Definition at line 68 of file UARTDriver.h.
Referenced by _check_connection(), _tcp_start_connection(), and UARTDriver().
bool HALSITL::UARTDriver::_nonblocking_writes private
Definition at line 71 of file UARTDriver.h.
Referenced by set_blocking_writes().
uint8_t HALSITL::UARTDriver::_portNumber private
Definition at line 65 of file UARTDriver.h.
Referenced by _check_connection(), _tcp_start_connection(), _timer_tick(), begin(), and UARTDriver().
ByteBuffer HALSITL::UARTDriver::_readbuffer {16384} private
Definition at line 72 of file UARTDriver.h.
Referenced by _timer_tick(), _uart_start_connection(), available(), and read().
int HALSITL::UARTDriver::_serial_port private
Definition at line 69 of file UARTDriver.h.
SITL_State* HALSITL::UARTDriver::_sitlState private
Definition at line 89 of file UARTDriver.h.
Referenced by _tcp_start_connection(), _uart_start_connection(), begin(), and UARTDriver().
const char* HALSITL::UARTDriver::_tcp_client_addr private
Definition at line 79 of file UARTDriver.h.
uint32_t HALSITL::UARTDriver::_uart_baudrate private
Definition at line 76 of file UARTDriver.h.
Referenced by _uart_start_connection(), and begin().
const char* HALSITL::UARTDriver::_uart_path private
Definition at line 75 of file UARTDriver.h.
Referenced by _check_reconnect(), _timer_tick(), _uart_start_connection(), and begin().
bool HALSITL::UARTDriver::_use_send_recv = false private
Definition at line 67 of file UARTDriver.h.
Referenced by _tcp_start_client(), _tcp_start_connection(), _timer_tick(), and _uart_start_connection().
ByteBuffer HALSITL::UARTDriver::_writebuffer {16384} private
Definition at line 73 of file UARTDriver.h.
Referenced by _timer_tick(), _uart_start_connection(), txspace(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_SITL/UARTDriver.h
libraries/AP_HAL_SITL/UARTDriver.cpp