APM:Libraries: libraries/AP_HAL_QURT/dsp_main.cpp File Reference
dsp_main.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "UDPDriver.h"
#include <stdio.h>
#include <stdint.h>
#include <unistd.h>
#include "Scheduler.h"
#include "Storage.h"
#include "replace.h"
#include <qurt_dsp.h>
Functions
int ArduPilot_main (int argc, const char *argv[])
static void * main_thread (void *cmdptr)
uint32_t ardupilot_start (const char *cmdline, int len)
uint32_t ardupilot_heartbeat ()
uint32_t ardupilot_set_storage (const uint8_t *buf, int len)
uint32_t ardupilot_get_storage (uint8_t *buf, int len)
uint32_t ardupilot_socket_check (uint8_t *buf, int len, uint32_t *nbytes)
uint32_t ardupilot_socket_input (const uint8_t *buf, int len, uint32_t *nbytes)
Variables
const AP_HAL::HAL & hal
volatile int _last_dsp_line = __LINE__
volatile const char * _last_dsp_file = __FILE__
volatile uint32_t _last_counter
Function Documentation
uint32_t ardupilot_get_storage (uint8_t * buf, int len)
Definition at line 83 of file dsp_main.cpp.
Referenced by get_storage().
uint32_t ardupilot_heartbeat ()
Definition at line 65 of file dsp_main.cpp.
Referenced by main().
int ArduPilot_main (int argc, const char * argv[])
Referenced by main_thread().
uint32_t ardupilot_set_storage (const uint8_t * buf, int len)
Definition at line 71 of file dsp_main.cpp.
Referenced by send_storage().
uint32_t ardupilot_socket_check (uint8_t * buf, int len, uint32_t * nbytes)
Definition at line 99 of file dsp_main.cpp.
Referenced by socket_check().
uint32_t ardupilot_socket_input (const uint8_t * buf, int len, uint32_t * nbytes)
Definition at line 104 of file dsp_main.cpp.
Referenced by socket_check().
uint32_t ardupilot_start (const char * cmdline, int len)
Definition at line 48 of file dsp_main.cpp.
Referenced by main().
static void* main_thread (void * cmdptr) static
Definition at line 21 of file dsp_main.cpp.
Referenced by ardupilot_start().
Variable Documentation
volatile uint32_t _last_counter
Definition at line 19 of file dsp_main.cpp.
Referenced by ardupilot_heartbeat().
volatile const char* _last_dsp_file = __FILE__
Definition at line 18 of file dsp_main.cpp.
Referenced by ardupilot_heartbeat().
volatile int _last_dsp_line = __LINE__
Definition at line 17 of file dsp_main.cpp.
Referenced by ardupilot_heartbeat().
const AP_HAL::HAL& hal
Definition at line 10 of file AC_PID_test.cpp.