APM:Libraries: libraries/AP_HAL_QURT/mainapp/getifaddrs.cpp File Reference
getifaddrs.cpp File Reference
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/time.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <netinet/in.h>
#include <arpa/inet.h>
Functions
void freeifaddrs (struct ifaddrs *ifp)
static struct sockaddr * sockaddr_dup (struct sockaddr *sa)
int getifaddrs (struct ifaddrs **ifap)
const char * get_ipv4_broadcast (void)
Function Documentation
void freeifaddrs (struct ifaddrs * ifp)
Definition at line 36 of file getifaddrs.cpp.
Referenced by get_ipv4_broadcast(), and getifaddrs().
const char* get_ipv4_broadcast (void)
Definition at line 158 of file getifaddrs.cpp.
Referenced by get_ipv4_broadcast(), and socket_check().
int getifaddrs (struct ifaddrs ** ifap)
Definition at line 65 of file getifaddrs.cpp.
Referenced by get_ipv4_broadcast().
static struct sockaddr* sockaddr_dup (struct sockaddr * sa) static
Definition at line 48 of file getifaddrs.cpp.
Referenced by getifaddrs().