APM:Libraries: libraries/AP_HAL_QURT/HAL_QURT_Class.cpp File Reference
HAL_QURT_Class.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "HAL_QURT_Class.h"
#include "AP_HAL_QURT_Private.h"
#include "Scheduler.h"
#include "Storage.h"
#include "Semaphores.h"
#include "RCInput.h"
#include "RCOutput.h"
#include <AP_HAL_Empty/AP_HAL_Empty.h>
#include <AP_HAL_Empty/AP_HAL_Empty_Private.h>
#include <AP_HAL/utility/getopt_cpp.h>
#include <assert.h>
Variables
static UDPDriver uartADriver
static UARTDriver uartBDriver ("/dev/tty-4")
static UARTDriver uartCDriver ("/dev/tty-2")
static UARTDriver uartDDriver (nullptr)
static UARTDriver uartEDriver (nullptr)
static Empty::SPIDeviceManager spiDeviceManager
static Empty::AnalogIn analogIn
static Storage storageDriver
static Empty::GPIO gpioDriver
static RCInput rcinDriver ("/dev/tty-1")
static RCOutput rcoutDriver ("/dev/tty-3")
static Util utilInstance
static Scheduler schedulerInstance
static Empty::I2CDeviceManager i2c_mgr_instance
bool qurt_ran_overtime
Variable Documentation
Empty::AnalogIn analogIn static
Definition at line 40 of file HAL_QURT_Class.cpp.
Empty::GPIO gpioDriver static
Definition at line 42 of file HAL_QURT_Class.cpp.
Empty::I2CDeviceManager i2c_mgr_instance static
Definition at line 47 of file HAL_QURT_Class.cpp.
bool qurt_ran_overtime
Definition at line 49 of file HAL_QURT_Class.cpp.
Referenced by QURT::Scheduler::_run_timers(), and QURT::Scheduler::_timer_thread().
RCInput rcinDriver("/dev/tty-1") static
Referenced by HAL_QURT::run().
RCOutput rcoutDriver("/dev/tty-3") static
Referenced by HAL_QURT::run().
Scheduler schedulerInstance static
Definition at line 46 of file HAL_QURT_Class.cpp.
Empty::SPIDeviceManager spiDeviceManager static
Definition at line 39 of file HAL_QURT_Class.cpp.
Storage storageDriver static
Definition at line 41 of file HAL_QURT_Class.cpp.
UDPDriver uartADriver static
Definition at line 33 of file HAL_QURT_Class.cpp.
UARTDriver uartBDriver("/dev/tty-4") static
Referenced by HAL_QURT::run().
UARTDriver uartCDriver("/dev/tty-2") static
Referenced by HAL_QURT::run().
UARTDriver uartDDriver(nullptr) static
Referenced by HAL_QURT::run().
UARTDriver uartEDriver(nullptr) static
Referenced by HAL_QURT::run().
Util utilInstance static
Definition at line 45 of file HAL_QURT_Class.cpp.