APM:Libraries: libraries/AP_HAL_QURT/mainapp/mainapp.cpp File Reference
mainapp.cpp File Reference
#include <stdio.h>
#include <stdint.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <errno.h>
#include <AP_HAL/utility/Socket.h>
#include <qurt_dsp.h>
Macros
#define STORAGE_DIR "/var/APM"
#define STORAGE_FILE STORAGE_DIR "/" SKETCHNAME ".stg"
Functions
const char * get_ipv4_broadcast (void)
static uint64_t micros64 ()
static void send_storage (void)
static void get_storage (void)
static void socket_check (void)
static char * encode_argv (int argc, const char *argv[])
int main (int argc, const char *argv[])
Variables
static SocketAPM sock {true}
static bool connected
static uint32_t last_get_storage_us
static uint64_t start_time
Macro Definition Documentation
#define STORAGE_DIR "/var/APM"
Definition at line 22 of file mainapp.cpp.
#define STORAGE_FILE STORAGE_DIR "/" SKETCHNAME ".stg"
Definition at line 23 of file mainapp.cpp.
Referenced by get_storage(), and send_storage().
Function Documentation
static char* encode_argv (int argc, const char * argv[]) static
Definition at line 123 of file mainapp.cpp.
Referenced by main().
const char* get_ipv4_broadcast (void)
Definition at line 158 of file getifaddrs.cpp.
Referenced by get_ipv4_broadcast(), and socket_check().
static void get_storage (void) static
Definition at line 63 of file mainapp.cpp.
Referenced by main().
int main (int argc, const char * argv[])
Definition at line 144 of file mainapp.cpp.
Referenced by dsm_decode(), get_ipv4_broadcast(), and srxl_decode().
static uint64_t micros64 () static
Definition at line 28 of file mainapp.cpp.
Referenced by dsm_decode(), main(), and srxl_decode().
static void send_storage (void) static
Definition at line 43 of file mainapp.cpp.
Referenced by main().
static void socket_check (void) static
Definition at line 84 of file mainapp.cpp.
Referenced by main().
Variable Documentation
bool connected static
Definition at line 17 of file mainapp.cpp.
Referenced by socket_check().
uint32_t last_get_storage_us static
Definition at line 18 of file mainapp.cpp.
Referenced by main().
SocketAPM sock {true} static
Definition at line 16 of file mainapp.cpp.
Referenced by main(), SITL::FlightAxis::soap_request(), and socket_check().
uint64_t start_time static
Definition at line 19 of file mainapp.cpp.
Referenced by micros64(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_while_stopped_test(), and setup().