APM:Libraries: AP_HAL Namespace Reference
AP_HAL Namespace Reference
Classes
class AnalogIn
class AnalogSource
class BetterStream
class Device
class DigitalSource
class GPIO
class HAL
class I2CDevice
class I2CDeviceManager
class OpticalFlow
class OwnPtr
class Print
class RCInput
class RCOutput
class Scheduler
class Semaphore
class SPIDevice
class SPIDeviceManager
class Storage
class Stream
class UARTDriver
class Util
Typedefs
typedef void(* Proc) (void)
Enumerations
enum SPIDeviceType { SPIDevice_Type = -1 }
Functions
FUNCTOR_TYPEDEF (MemberProc, void)
const HAL & get_HAL ()
void init ()
void panic (const char *errormsg,...) FMT_PRINTF(1
uint32_t micros ()
uint32_t millis ()
uint64_t micros64 ()
uint64_t millis64 ()
template<typename T >
bool operator== (T *a, const OwnPtr< T > &b)
template<typename T >
bool operator== (const OwnPtr< T > &a, T *b)
template<typename T >
bool operator!= (T *a, const OwnPtr< T > &b)
template<typename T >
bool operator!= (const OwnPtr< T > &a, T *b)
Variables
void NORETURN
struct {
struct timespec AP_HAL::start_time
} state
struct {
uint64_t AP_HAL::start_time
} state
struct {
struct timeval AP_HAL::start_time
} state
Typedef Documentation
typedef void(* AP_HAL::Proc) (void)
Definition at line 47 of file AP_HAL_Namespace.h.
Enumeration Type Documentation
enum AP_HAL::SPIDeviceType
Global names for all of the existing SPI devices on all platforms.
Enumerator
SPIDevice_Type
Definition at line 54 of file AP_HAL_Namespace.h.
Function Documentation
AP_HAL::FUNCTOR_TYPEDEF (MemberProc , void)
const AP_HAL::HAL & AP_HAL::get_HAL ()
Definition at line 65 of file HAL_Empty_Class.cpp.
Referenced by HAL_Linux::exit_signal_handler(), loop(), HAL_SITL::run(), HAL_PX4::run(), HAL_VRBRAIN::run(), and HAL_QURT::run().
void AP_HAL::init ()
Definition at line 19 of file system.cpp.
Referenced by HALSITL::AnalogIn::AnalogIn(), VRBRAIN::VRBRAIN_I2C::do_transfer(), PX4::PX4_I2C::do_transfer(), Linux::GPIO_Sysfs::from(), Linux::RCOutput_Bebop::from(), AP_HAL::GPIO::GPIO(), AP_HAL::HAL::HAL(), PX4::PX4CAN::PX4CAN(), and PX4::PX4CANManager::PX4CANManager().
uint32_t AP_HAL::micros ()
Definition at line 38 of file system.cpp.
Referenced by AP_InertialSensor_PX4::_new_accel_sample(), AP_InertialSensor_PX4::_new_gyro_sample(), VRBRAIN::VRBRAINRCOutput::_send_outputs(), PX4::PX4RCOutput::_send_outputs(), HALSITL::SITL_State::_simulator_servos(), Linux::RCInput_Navio2::_timer_tick(), Linux::SPIUARTDriver::_timer_tick(), PX4::PX4AnalogIn::_timer_tick(), VRBRAIN::VRBRAINAnalogIn::_timer_tick(), AP_Compass_LSM9DS1::_update(), AP_Compass_LSM303D::_update(), AnalogIn_ADS1115::_update(), AP_Compass_BMM150::_update(), AP_Compass_AK8963::_update(), HALSITL::SITL_State::_update_compass(), AP_Compass_AK8963::_update_timer(), AP_RPM_Pin::irq_handler(), loop(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_HIL::read(), AP_BattMonitor_Bebop::read(), AP_Compass_LIS3MDL::read(), AP_BattMonitor_Analog::read(), AP_Scheduler::run(), GCS_MAVLINK::send_raw_imu(), SITL::ADSB::send_report(), SITL::Gimbal::send_report(), GCS_MAVLINK::send_servo_output_raw(), setup(), DataFlashTest::setup(), AP_OpticalFlow_Pixart::setup_sensor(), test_one_offset(), AP_Scheduler::time_available_usec(), AP_BattMonitor_SMBus_Solo::timer(), AP_BattMonitor_SMBus_Maxell::timer(), AP_Compass_IST8310::timer(), AP_Compass_AK09916::timer(), AP_Compass_LIS3MDL::timer(), AP_OpticalFlow_Pixart::timer(), SITL::Gimbal::update(), SITL::ADSB::update(), AP_L1_Control::update_waypoint(), and AP_InertialSensor::wait_for_sample().
uint64_t AP_HAL::micros64 ()
Definition at line 48 of file system.cpp.
Referenced by AP_InertialSensor_Invensense::_accumulate(), AP_InertialSensor_Invensense::_accumulate_fast_sampling(), HALSITL::SITL_State::_fdm_input_local(), AP_InertialSensor_Backend::_notify_new_accel_raw_sample(), AP_InertialSensor_Backend::_notify_new_gyro_raw_sample(), Linux::RCInput::_process_dsm_pulse(), Linux::PeriodicThread::_run(), AP_TECS::_update_speed(), PX4::PX4UARTDriver::_write_fd(), VRBRAIN::VRBRAINUARTDriver::_write_fd(), Linux::RCInput::add_dsm_input(), QURT::RCInput::add_dsm_input(), Linux::RCInput::add_srxl_input(), PX4::DeviceBus::adjust_timer(), PX4::DeviceBus::bus_thread(), SITL::Motor::calculate_forces(), AP_Module::call_hook_accel_sample(), AP_Module::call_hook_AHRS_update(), AP_Module::call_hook_gyro_sample(), AP_Module::call_hook_setup_complete(), AP_Module::call_hook_setup_start(), SoaringController::check_cruise_criteria(), SoaringController::check_init_thermal_criteria(), SoaringController::check_thermal_criteria(), AC_AttitudeControl::control_monitor_log(), AP_InertialSensor_QURT::data_ready(), QURT::Scheduler::delay(), VRBRAIN::VRBRAINScheduler::delay(), PX4::PX4Scheduler::delay(), HALSITL::Scheduler::delay_microseconds(), SoaringController::get_wind_corrected_drift(), AP_UAVCAN::SystemClock::getMonotonic(), AP_UAVCAN::SystemClock::getUtc(), AP_InertialSensor_SITL::gyro_drift(), GCS_MAVLINK::handle_timesync(), SoaringController::init_cruising(), SoaringController::init_thermalling(), NavEKF3::InitialiseFilter(), NavEKF2::InitialiseFilter(), AP_GPS_SBF::log_ExtEventPVTGeodetic(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_UBLOX::log_rxm_rawx(), DataFlash_Class::Log_Write_AHRS2(), DataFlash_Class::Log_Write_Airspeed(), DataFlash_Class::Log_Write_Attitude(), DataFlash_Class::Log_Write_AttitudeView(), DataFlash_Class::Log_Write_Baro(), DataFlash_Class::Log_Write_CameraInfo(), DataFlash_Class::Log_Write_Compass(), DataFlash_Class::Log_Write_Current(), DataFlash_Class::Log_Write_ESC(), DataFlash_Class::Log_Write_GPS(), DataFlash_Class::Log_Write_IMU(), DataFlash_Backend::Log_Write_MavCmd(), DataFlash_Backend::Log_Write_Message(), DataFlash_Backend::Log_Write_Mode(), DataFlash_Class::Log_Write_Origin(), DataFlash_Backend::Log_Write_Parameter(), AP_Tuning::Log_Write_Parameter_Tuning(), DataFlash_Class::Log_Write_PID(), DataFlash_Class::Log_Write_POS(), DataFlash_Class::Log_Write_Power(), DataFlash_Class::Log_Write_Radio(), DataFlash_Class::Log_Write_Rally(), DataFlash_Class::Log_Write_Rate(), DataFlash_Class::Log_Write_RCIN(), DataFlash_Class::Log_Write_RCOUT(), DataFlash_Class::Log_Write_RFND(), DataFlash_Class::Log_Write_RPM(), DataFlash_Class::Log_Write_RSSI(), SITL::SITL::Log_Write_SIMSTATE(), DataFlashTest_AllTypes::Log_Write_TypeMessages(), DataFlashTest_AllTypes::Log_Write_TypeMessages_Log_Write(), DataFlash_Class::Log_Write_Vibration(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), loop(), micros(), AP_MotorsHeli_RSC::output(), PX4::DeviceBus::register_periodic_callback(), GCS_MAVLINK::send_vibration(), SITL::Gripper_EPM::should_report(), SITL::Gripper_Servo::should_report(), SITL::Sprayer::should_report(), simulation_timeval(), SITL::Aircraft::smooth_sensors(), SoaringController::suppress_throttle(), HALSITL::Semaphore::take(), PX4::Semaphore::take(), QURT::Semaphore::take(), VRBRAIN::Semaphore::take(), Linux::Semaphore::take(), AP_Compass_QFLIGHT::timer_update(), AP_Landing::type_slope_log(), AP_RangeFinder_PX4_PWM::update(), SITL::Gripper_Servo::update(), SITL::Sprayer::update(), SITL::ICEngine::update(), AP_TECS::update_50hz(), SITL::Gripper_EPM::update_from_demand(), AP_TECS::update_pitch_throttle(), SITL::Aircraft::update_position(), SoaringController::update_thermalling(), SoaringController::update_vario(), NavEKF3::UpdateFilter(), NavEKF2::UpdateFilter(), HALSITL::SITL_State::wait_clock(), and AP_AutoTune::write_log().
uint32_t AP_HAL::millis ()
Definition at line 43 of file system.cpp.
Referenced by HALSITL::SITL_State::_airspeed_sensor(), AP_GPS_SBP::_attempt_state_update(), SITL::Calibration::_calibration_poses(), AP_Baro_BMP085::_cmd_read_pressure(), AP_Baro_BMP085::_cmd_read_temp(), AP_Airspeed_MS4525::_collect(), AP_Baro_Backend::_copy_to_frontend(), AP_Baro_BMP085::_data_ready(), AP_TECS::_detect_underspeed(), HALSITL::SITL_State::_fdm_input_step(), AP_PitchController::_get_rate_out(), AP_RollController::_get_rate_out(), AP_GPS_NMEA::_have_new_message(), AP_Airspeed_MS4525::_measure(), AP_GPS_ERB::_parse_gps(), AP_GPS_UBLOX::_parse_gps(), AP_Baro_BMP085::_read_pressure(), AP_GPS_UBLOX::_save_cfg(), AP_GPS_SBP::_sbp_process_message(), AP_GPS_NMEA::_term_complete(), AP_Airspeed_MS4525::_timer(), QURT::Scheduler::_timer_thread(), VRBRAIN::VRBRAINScheduler::_timer_thread(), PX4::PX4Scheduler::_timer_thread(), Linux::RCInput_SBUS::_timer_tick(), Linux::RCInput_115200::_timer_tick(), PX4::PX4AnalogIn::_timer_tick(), VRBRAIN::VRBRAINAnalogIn::_timer_tick(), HALSITL::SITL_State::_update_barometer(), HALSITL::SITL_State::_update_compass(), OpticalFlow_backend::_update_frontend(), HALSITL::SITL_State::_update_gps(), HALSITL::SITL_State::_update_gps_ubx(), Linux::RCInput::add_dsm_input(), QURT::RCInput::add_dsm_input(), Linux::RCInput::add_sbus_input(), AP_GPS_GSOF::AP_GPS_GSOF(), AP_GPS_SBP::AP_GPS_SBP(), AP_RangeFinder_MAVLink::AP_RangeFinder_MAVLink(), AP_InertialSensor_UserInteract_MAVLink::blocking_read(), AP_Airspeed_MS5525::calculate(), AP_Airspeed::calibrate(), AP_Baro::calibrate(), AP_AdvancedFailsafe::check(), AP_AdvancedFailsafe::check_altlimit(), ToneAlarm_PX4_Solo::check_cont_tone(), ToneAlarm_PX4::check_cont_tone(), AP_Tuning::check_controller_error(), AP_Frsky_Telem::check_ekf_status(), AC_Fence::check_fence(), AP_Avoidance::check_for_threats(), CompassCalibrator::check_for_timeout(), AccelCalibrator::check_for_timeout(), AP_Tuning::check_input(), AP_AutoTune::check_save(), AP_Tuning::check_selector_switch(), AP_Frsky_Telem::check_sensor_status_flags(), AP_GPS::detect_instance(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), AP_BattMonitor::exhausted(), AP_Mount_SToRM32::find_gimbal(), SchedTest::five_second_call(), VRBRAIN::VRBRAINRCOutput::force_safety_pending_requests(), PX4::PX4RCOutput::force_safety_pending_requests(), AP_Airspeed_MS4525::get_differential_pressure(), AP_Airspeed_MS5525::get_differential_pressure(), AP_Baro::get_external_temperature(), AC_PrecLand_SITL::get_los_body(), PID::get_pid(), AP_RangeFinder_LeddarOne::get_reading(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), AP_Airspeed_MS4525::get_temperature(), AP_Airspeed_MS5525::get_temperature(), AP_Proximity_MAV::get_upward_distance(), AP_Proximity_RangeFinder::get_upward_distance(), AP_Beacon::get_vehicle_position_ned(), SoloGimbalEKF::getStatus(), HALSITL::SITL_State::gps2_pipe(), HALSITL::SITL_State::gps_pipe(), AP_Gripper_Servo::grab(), AP_Gripper_EPM::grab(), DataFlash_MAVLink::handle_ack(), AP_Avoidance::handle_avoidance_local(), RGBLed::handle_led_control(), GCS_MAVLINK::handle_log_send_data(), GCS_MAVLINK::handle_log_send_listing(), GCS_MAVLINK::handle_mission_count(), GCS_MAVLINK::handle_mission_item(), GCS_MAVLINK::handle_mission_write_partial_list(), AP_RangeFinder_MAVLink::handle_msg(), AP_Proximity_MAV::handle_msg(), AP_GPS_MAV::handle_msg(), AC_PrecLand_Companion::handle_msg(), AP_Avoidance::handle_msg(), GCS_MAVLINK::handle_param_request_read(), GCS_MAVLINK::handle_radio_status(), DataFlash_MAVLink::handle_retry(), GCS_MAVLINK::handle_set_mode(), AP_Avoidance::handle_threat_gcs_notify(), AP_ADSB::handle_transceiver_report(), AP_ADSB::handle_vehicle(), AP_Gripper_Servo::has_state_pwm(), AC_PrecLand_SITL::have_los_meas(), AP_Beacon_SITL::healthy(), AP_Beacon_Pozyx::healthy(), AP_AHRS_DCM::healthy(), ToneAlarm_PX4_Solo::init(), AP_Mission::init(), AP_Proximity_LightWareSF40C::initialise(), AP_AHRS_NavEKF::initialised(), AP_GPS_NOVA::inject_data(), AP_GPS_GSOF::inject_data(), AP_GPS_SBF::inject_data(), AP_GPS_SBP::inject_data(), AP_Arming::ins_checks(), AC_PosControl::is_active_xy(), AC_PosControl::is_active_z(), AP_Proximity_SITL::load_fence(), DataFlash_MAVLink::Log_Write_DF_MAV(), loop(), AC_Fence::manual_recovery_start(), CompassCalibrator::new_sample(), AccelCalibrator::new_sample(), PX4::PX4AnalogIn::next_stop_pin(), VRBRAIN::VRBRAINAnalogIn::next_stop_pin(), AP_AHRS_DCM::normalize(), SchedTest::one_hz_print(), TCPServerDevice::open(), AP_Landing_Deepstall::override_servos(), GCS_MAVLINK::packet_overhead_chan(), AP_Beacon_Pozyx::parse_buffer(), DataFlash_Backend::periodic_tasks(), Linux::ToneAlarm_Raspilot::play(), Linux::ToneAlarm_Disco::play(), Linux::ToneAlarm::play(), ToneAlarm_PX4_Solo::play_tone(), ToneAlarm_PX4::play_tone(), AP_GPS_NOVA::process_message(), AP_GPS_GSOF::process_message(), AP_GPS_SBF::process_message(), AP_Proximity_LightWareSF40C::process_reply(), AP_Compass_Backend::publish_filtered_field(), AP_Compass_Backend::publish_raw_field(), GCS_MAVLINK::queued_param_send(), AP_GPS_QURT::read(), AP_GPS_NOVA::read(), AP_GPS_GSOF::read(), AP_GPS_MTK19::read(), AP_GPS_PX4::read(), AP_GPS_SBF::read(), AP_Airspeed::read(), Compass::read(), AP_GPS_UBLOX::read(), AP_IRLock_I2C::read_block(), AP_IRLock_I2C::read_frames(), NavEKF2_core::readIMUData(), SITL::XPlane::receive_data(), AC_Fence::record_breach(), AP_Gripper_Servo::release(), AP_Gripper_EPM::release(), AP_Parachute::release(), AP_Proximity_LightWareSF40C::request_new_data(), AP_AHRS_DCM::reset(), GCS_MAVLINK::reset_cli_timeout(), AC_PrecLand::run_estimator(), MissionTest::run_resume_test(), MissionTest::run_set_current_cmd_while_stopped_test(), SoloGimbalEKF::RunEKF(), GCS_MAVLINK::save_signing_timestamp(), AP_ADSB::send_adsb_vehicle(), AP_Frsky_Telem::send_D(), AP_Mount_SToRM32::send_do_mount_control(), GCS_MAVLINK::send_local_position(), DataFlash_MAVLink::send_log_block(), AP_GPS::send_mavlink_gps_raw(), GCS_MAVLINK::send_radio_in(), GCS_MAVLINK::send_raw_imu(), AP_Button::send_report(), SITL::ADSB::send_report(), SITL::Gimbal::send_report(), AP_Proximity_LightWareSF40C::send_request_for_distance(), AP_Proximity_LightWareSF40C::send_request_for_health(), GCS_MAVLINK::send_scaled_pressure(), AP_Frsky_Telem::send_SPort_Passthrough(), GCS_MAVLINK::send_system_time(), AP_Mount_SToRM32_serial::send_target_angles(), AP_Notify::send_text(), AP_InertialSensor::set_accel_peak_hold(), AP_Beacon_Backend::set_beacon_distance(), AP_LeakDetector::set_detect(), AP_Baro::set_external_temperature(), AP_Stats::set_flying(), AP_Proximity_LightWareSF40C::set_forward_direction(), Linux::HeatPwm::set_imu_temp(), PX4::PX4Util::set_imu_temp(), VRBRAIN::VRBRAINUtil::set_imu_temp(), AP_Proximity_LightWareSF40C::set_motor_direction(), AP_Proximity_LightWareSF40C::set_motor_speed(), SoloGimbal_Parameters::set_param(), AP_Rally::set_rally_point_with_index(), AC_WPNav::set_spline_destination(), AC_WPNav::set_spline_origin_and_destination(), CompassCalibrator::set_status(), AccelCalibrator::set_status(), AP_Beacon_Backend::set_vehicle_position(), AC_WPNav::set_wp_destination(), AP_Airspeed::setHIL(), AP_GPS::setHIL(), setup(), NavEKF3_core::setup_core(), CompassCalibrator::start(), AP_AutoTune::start(), DataFlash_MAVLink::stop_logging(), AP_IRLock_I2C::sync_frame_start(), AC_PrecLand::target_acquired(), GCS_MAVLINK::telemetry_delayed(), test_uart(), AP_GPS::time_epoch_usec(), AC_PosControl::time_since_last_xy_update(), AP_Baro_QURT::timer(), AP_OpticalFlow_Pixart::timer(), AP_Baro_QFLIGHT::timer_update(), AP_Compass_QFLIGHT::timer_update(), PX4::PX4UARTDriver::try_initialise(), VRBRAIN::VRBRAINUARTDriver::try_initialise(), AP_Landing::type_slope_verify_land(), AP_Proximity_MAV::update(), AP_OpticalFlow_Pixart::update(), AP_Proximity_RangeFinder::update(), AP_IRLock_I2C::update(), AP_OpticalFlow_SITL::update(), AP_RangeFinder_LightWareSerial::update(), AP_RangeFinder_MaxsonarSerialLV::update(), AP_Proximity_LightWareSF40C::update(), AP_RangeFinder_uLanding::update(), AP_Proximity_TeraRangerTower::update(), AP_Beacon_SITL::update(), AP_RangeFinder_MAVLink::update(), AC_PrecLand_Companion::update(), AC_PrecLand_SITL::update(), AP_AccelCal::update(), AC_PrecLand_SITL_Gazebo::update(), AP_Stats::update(), AC_PrecLand_IRLock::update(), AP_OpticalFlow_Onboard::update(), AP_RPM_Pin::update(), AP_Mount_SToRM32_serial::update(), AP_RPM_SITL::update(), AP_Mount_SToRM32::update(), AP_RPM_PX4_PWM::update(), AP_ICEngine::update(), AP_RangeFinder_PX4_PWM::update(), AP_Button::update(), SITL::XPlane::update(), AP_Baro::update(), AP_Mount_Servo::update(), AP_LeakDetector::update(), OpticalFlow::update(), AP_AutoTune::update(), Buzzer::update(), AP_RangeFinder_LeddarOne::update(), AP_ADSB::update(), SoloGimbal_Parameters::update(), AP_Parachute::update(), AC_Sprayer::update(), AP_AHRS_DCM::update(), GCS_MAVLINK::update(), AP_GPS::update(), AP_InertialSensor::update(), AP_Baro::update_calibration(), AP_Airspeed::update_calibration(), SITL::Aircraft::update_dynamics(), AP_AHRS_NavEKF::update_EKF2(), AP_AHRS_NavEKF::update_EKF3(), AP_ServoRelayEvents::update_events(), AP_Stats::update_flighttime(), AP_Gripper_EPM::update_gripper(), AP_GPS::update_instance(), AP_Camera::update_location(), RGBLed::update_override(), AP_Stats::update_runtime(), AP_Proximity_TeraRangerTower::update_sector_data(), AC_WPNav::update_spline(), AP_Landing_Deepstall::update_steering(), Display::update_text(), AP_Avoidance::update_threat_level(), AC_PosControl::update_vel_controller_xyz(), AC_WPNav::update_wpnav(), AC_PosControl::update_xy_controller(), AC_PosControl::update_z_controller(), AP_AHRS_DCM::uptime_ms(), AP_AHRS_DCM::use_compass(), AP_AHRS_DCM::use_fast_gains(), AP_Landing_Deepstall::verify_land(), and AP_Mission::write_cmd_to_storage().
uint64_t AP_HAL::millis64 ()
Definition at line 63 of file system.cpp.
Referenced by Linux::Perf::_debug_counters(), Linux::Scheduler::_debug_stack(), Linux::Scheduler::delay(), millis(), AP_Button::timer_update(), and AP_Button::update().
template<typename T > bool AP_HAL::operator!= (T * a, const OwnPtr< T > & b) inline
Definition at line 115 of file OwnPtr.h.
template<typename T > bool AP_HAL::operator!= (const OwnPtr< T > & a, T * b) inline
Definition at line 121 of file OwnPtr.h.
template<typename T > bool AP_HAL::operator== (T * a, const OwnPtr< T > & b) inline
Definition at line 103 of file OwnPtr.h.
template<typename T > bool AP_HAL::operator== (const OwnPtr< T > & a, T * b) inline
Definition at line 109 of file OwnPtr.h.
void AP_HAL::panic (const char * errormsg, ...)
Definition at line 24 of file system.cpp.
Referenced by AP_Baro::_add_backend(), RangeFinder::_add_backend(), AP_InertialSensor::_add_backend(), Compass::_add_backend(), AP_InertialSensor_BMI160::_check_err_reg(), AP_ADC_ADS1115::_convert_register_data_to_mv(), Linux::PWM_Sysfs::_generate_duty_path(), Linux::PWM_Sysfs_Bebop::_generate_duty_path(), Linux::PWM_Sysfs::_generate_enable_path(), Linux::PWM_Sysfs_Bebop::_generate_enable_path(), Linux::PWM_Sysfs::_generate_export_path(), Linux::PWM_Sysfs::_generate_period_path(), Linux::PWM_Sysfs_Bebop::_generate_period_path(), Linux::PWM_Sysfs::_generate_polarity_path(), AP_InertialSensor_LSM9DS0::_gyro_disable_i2c(), AP_Compass_LSM303D::_hardware_init(), AP_Baro_MS56XX::_init(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_PX4::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), Linux::CameraSensor_Mt9v117::_init_sensor(), PX4::PX4Storage::_mtd_load(), VRBRAIN::VRBRAINStorage::_mtd_signature(), VRBRAIN::VRBRAINStorage::_mtd_write_signature(), HALSITL::SITL_State::_parse_command_line(), Linux::UARTDriver::_parseDevicePath(), Linux::OpticalFlow_Onboard::_run_optflow(), Linux::RCOutput_Bebop::_run_rcout(), AP_InertialSensor::_start_backends(), Linux::Storage::_storage_create(), VRBRAIN::VRBRAINStorage::_storage_open(), Linux::Storage::_storage_open(), HALSITL::UARTDriver::_uart_start_connection(), VRBRAIN::VRBRAINStorage::_upgrade_to_mtd(), AP_AHRS_View::AP_AHRS_View(), AP_Baro_BMP085::AP_Baro_BMP085(), AP_InertialSensor::AP_InertialSensor(), AP_Proximity_SITL::AP_Proximity_SITL(), Linux::SPIUARTDriver::begin(), HALSITL::UARTDriver::begin(), QURT::UARTDriver::begin(), AP_Baro::calibrate(), Linux::CameraSensor_Mt9v117::CameraSensor_Mt9v117(), catch_sigbus(), SITL::JSBSim::create_templates(), DataFlash_Class::DataFlash_Class(), AP_InertialSensor::detect_backends(), FlashTest::flash_erase(), FlashTest::flash_read(), FlashTest::flash_write(), SITL::FlightAxis::FlightAxis(), GCS::GCS(), Linux::I2CDeviceManager::get_device(), Linux::VideoIn::get_frame(), Linux::RCInput_Navio2::init(), Linux::ToneAlarm_Raspilot::init(), PX4::PX4RCOutput::init(), VRBRAIN::VRBRAINRCOutput::init(), Linux::RCInput_ZYNQ::init(), PX4::PX4RCInput::init(), VRBRAIN::VRBRAINRCInput::init(), Linux::RCInput_PRU::init(), TSYS01::init(), Linux::RCInput_UART::init(), Linux::RCOutput_Sysfs::init(), QURT::RCInput::init(), Linux::PWM_Sysfs_Base::init(), VRBRAIN::VRBRAINGPIO::init(), Linux::Scheduler::init(), Linux::Led_Sysfs::init(), Linux::RCInput_AioPRU::init(), Linux::RCOutput_AeroIO::init(), Linux::RCInput_115200::init(), PX4::PX4GPIO::init(), AnalogIn_Raspilot::init(), AP_Baro::init(), DataFlash_MAVLink::Init(), Linux::OpticalFlow_Onboard::init(), Linux::GPIO_RPI::init(), PX4::PX4AnalogIn::init(), VRBRAIN::VRBRAINAnalogIn::init(), PX4::RCOutput_Tap::init(), DataFlash_Class::Init(), Linux::GPIO_BBB::init(), AP_Mission::init(), AP_InertialSensor_QURT::init_mpu9250(), AP_Module::module_scan(), Linux::SPIBus::open(), Linux::RCInput_Navio2::open_channel(), Linux::Perf::Perf(), AP_BoardConfig::px4_setup_pwm(), Linux::RCInput_Multi::RCInput_Multi(), Linux::RCInput_UART::RCInput_UART(), AP_InertialSensor::register_accel(), Compass::register_compass(), AP_InertialSensor::register_gyro(), Linux::SPIDevice::register_periodic_callback(), Linux::I2CDevice::register_periodic_callback(), AP_Baro::register_sensor(), AnalogSource_Navio2::set_channel(), AP_Param::set_float(), FlashTest::setup(), setup(), AP_OpticalFlow_Pixart::setup_sensor(), Linux::SPIDevice::SPIDevice(), AP_InertialSensor_BMI160::start(), Linux::Thread::start(), AP_InertialSensor_Invensense::start(), SITL::JSBSim::start_JSBSim(), HALSITL::Scheduler::system_initialized(), QURT::Scheduler::system_initialized(), Linux::Scheduler::system_initialized(), VRBRAIN::VRBRAINScheduler::system_initialized(), PX4::PX4Scheduler::system_initialized(), Linux::RCInput_RPI::termination_handler(), AP_Baro_QURT::timer(), AP_Baro_QFLIGHT::timer_update(), AP_InertialSensor_QFLIGHT::timer_update(), AP_Compass_QFLIGHT::timer_update(), and QURT::RCOutput::timer_update().
Variable Documentation
void AP_HAL::NORETURN
Definition at line 13 of file system.h.
struct timeval AP_HAL::start_time
Definition at line 16 of file system.cpp.
struct { ... } AP_HAL::state
struct { ... } AP_HAL::state
struct { ... } AP_HAL::state