APM:Libraries: libraries/AP_Math/polygon.cpp File Reference
polygon.cpp File Reference
#include "AP_Math.h"
Macros
#define sign(x) ((x)<0 ? -1 : 1)
Functions
template<typename T >
bool Polygon_outside (const Vector2< T > &P, const Vector2< T > *V, unsigned n)
template<typename T >
bool Polygon_complete (const Vector2< T > *V, unsigned n)
template bool Polygon_outside< int32_t > (const Vector2l &P, const Vector2l *V, unsigned n)
template bool Polygon_complete< int32_t > (const Vector2l *V, unsigned n)
template bool Polygon_outside< float > (const Vector2f &P, const Vector2f *V, unsigned n)
template bool Polygon_complete< float > (const Vector2f *V, unsigned n)
Macro Definition Documentation
#define sign (x) ((x)<0 ? -1 : 1)
Referenced by AP_GPS_NMEA::_parse_decimal_100(), AP_Declination::get_lookup_value(), Polygon_outside(), and print_vprintf().
Function Documentation
template<typename T > bool Polygon_complete (const Vector2< T > * V, unsigned n)
Definition at line 89 of file polygon.cpp.
Referenced by AC_PolyFence_loader::boundary_valid(), and setup().
template bool Polygon_complete< float > (const Vector2f * V, unsigned n)
Referenced by Polygon_complete().
template bool Polygon_complete< int32_t > (const Vector2l * V, unsigned n)
Referenced by Polygon_complete().
template<typename T > bool Polygon_outside (const Vector2< T > & P, const Vector2< T > * V, unsigned n)
Definition at line 38 of file polygon.cpp.
Referenced by AC_PolyFence_loader::boundary_breached(), AC_PolyFence_loader::boundary_valid(), and setup().
template bool Polygon_outside< float > (const Vector2f & P, const Vector2f * V, unsigned n)
Referenced by Polygon_complete().
template bool Polygon_outside< int32_t > (const Vector2l & P, const Vector2l * V, unsigned n)
Referenced by Polygon_complete().