APM:Libraries: libraries/AP_BoardConfig/px4_drivers.cpp File Reference
px4_drivers.cpp File Reference
#include <AP_HAL/AP_HAL.h>
#include "AP_BoardConfig.h"
#include <GCS_MAVLink/GCS.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <drivers/drv_pwm_output.h>
#include <drivers/drv_sbus.h>
#include <nuttx/arch.h>
#include <spawn.h>
Macros
#define _UAVCAN_IOCBASE (0x4000)
#define _UAVCAN_IOC(_n) (_IOC(_UAVCAN_IOCBASE, _n))
#define UAVCAN_IOCG_NODEID_INPROGRESS _UAVCAN_IOC(1)
#define MPUREG_WHOAMI 0x75
#define MPU_WHOAMI_MPU60X0 0x68
#define MPU_WHOAMI_MPU9250 0x71
#define MPU_WHOAMI_ICM20608 0xaf
#define MPU_WHOAMI_ICM20602 0x12
#define LSMREG_WHOAMI 0x0f
#define LSM_WHOAMI_LSM303D 0x49
Functions
int fmu_main (int, char **)
int px4io_main (int, char **)
int adc_main (int, char **)
int tone_alarm_main (int, char **)
int waitpid (pid_t, int *, int)
Variables
const AP_HAL::HAL & hal
Macro Definition Documentation
#define _UAVCAN_IOC (_n) (_IOC(_UAVCAN_IOCBASE, _n))
Definition at line 60 of file px4_drivers.cpp.
#define _UAVCAN_IOCBASE (0x4000)
Definition at line 59 of file px4_drivers.cpp.
#define LSM_WHOAMI_LSM303D 0x49
Definition at line 466 of file px4_drivers.cpp.
Referenced by AP_BoardConfig::px4_autodetect().
#define LSMREG_WHOAMI 0x0f
Definition at line 465 of file px4_drivers.cpp.
Referenced by AP_BoardConfig::px4_autodetect().
#define MPU_WHOAMI_ICM20602 0x12
Definition at line 463 of file px4_drivers.cpp.
Referenced by AP_BoardConfig::px4_autodetect().
#define MPU_WHOAMI_ICM20608 0xaf
Definition at line 462 of file px4_drivers.cpp.
Referenced by AP_BoardConfig::px4_autodetect().
#define MPU_WHOAMI_MPU60X0 0x68
Definition at line 460 of file px4_drivers.cpp.
Referenced by AP_BoardConfig::px4_autodetect().
#define MPU_WHOAMI_MPU9250 0x71
Definition at line 461 of file px4_drivers.cpp.
Referenced by AP_BoardConfig::px4_autodetect().
#define MPUREG_WHOAMI 0x75
Definition at line 459 of file px4_drivers.cpp.
Referenced by AP_BoardConfig::px4_autodetect().
#define UAVCAN_IOCG_NODEID_INPROGRESS _UAVCAN_IOC(1)
Definition at line 62 of file px4_drivers.cpp.
Function Documentation
int adc_main (int , char **)
Referenced by AP_BoardConfig::px4_setup_peripherals().
int fmu_main (int , char **)
Referenced by AP_BoardConfig::px4_setup_drivers(), and AP_BoardConfig::px4_setup_peripherals().
int px4io_main (int , char **)
Referenced by AP_BoardConfig::px4_setup_px4io().
int tone_alarm_main (int , char **)
Referenced by AP_BoardConfig::px4_tone_alarm().
int waitpid (pid_t , int * , int)
Referenced by AP_BoardConfig::px4_setup_canbus(), and AP_BoardConfig::px4_start_driver().
Variable Documentation
const AP_HAL::HAL& hal
Definition at line 10 of file AC_PID_test.cpp.
Referenced by AP_BoardConfig::px4_setup_canbus().