APM:Libraries: libraries/AP_HAL_QURT/replace.h File Reference
replace.h File Reference
#include <AP_HAL/AP_HAL.h>
#include <stdlib.h>
#include <stdint.h>
#include <types.h>
#include <sys/types.h>
#include <unistd.h>
#include <dirent.h>
Macros
#define HAP_PRINTF(...) HAP_printf(__FILE__, __LINE__, __VA_ARGS__)
#define HAP_LINE() do { _last_dsp_line = __LINE__; _last_dsp_file = __FILE__; _last_counter++; } while (0)
Functions
size_t strnlen (const char *s, size_t maxlen)
int asprintf (char **, const char *,...)
off_t lseek (int, off_t, int)
DIR * opendir (const char *)
int unlink (const char *pathname)
pid_t getpid (void)
void HAP_printf (const char *file, int line, const char *fmt,...)
Variables
volatile int _last_dsp_line
volatile const char * _last_dsp_file
volatile uint32_t _last_counter
Macro Definition Documentation
#define HAP_LINE () do { _last_dsp_line = __LINE__; _last_dsp_file = __FILE__; _last_counter++; } while (0)
Definition at line 37 of file replace.h.
#define HAP_PRINTF (...) HAP_printf(__FILE__, __LINE__, __VA_ARGS__)
Definition at line 31 of file replace.h.
Function Documentation
int asprintf (char ** , const char * , ...)
Definition at line 63 of file replace.cpp.
Referenced by Linux::PWM_Sysfs::_generate_duty_path(), Linux::PWM_Sysfs_Bebop::_generate_duty_path(), Linux::PWM_Sysfs::_generate_enable_path(), Linux::PWM_Sysfs_Bebop::_generate_enable_path(), Linux::PWM_Sysfs::_generate_export_path(), Linux::PWM_Sysfs::_generate_period_path(), Linux::PWM_Sysfs_Bebop::_generate_period_path(), Linux::PWM_Sysfs::_generate_polarity_path(), HALSITL::SITL_State::_parse_command_line(), SITL::JSBSim::create_templates(), Linux::I2CDeviceManager::get_device(), PX4::I2CDevice::I2CDevice(), Linux::Led_Sysfs::init(), AP_Module::init(), Linux::RCInput_Navio2::open_channel(), SITL::JSBSim::send_servos(), AnalogSource_Navio2::set_channel(), SITL::FlightAxis::soap_request(), PX4::SPIDevice::SPIDevice(), and SITL::JSBSim::start_JSBSim().
pid_t getpid (void)
Referenced by PX4::PX4UARTDriver::begin(), VRBRAIN::VRBRAINUARTDriver::begin(), QURT::Scheduler::in_timerprocess(), VRBRAIN::VRBRAINScheduler::in_timerprocess(), PX4::PX4Scheduler::in_timerprocess(), QURT::Scheduler::init(), VRBRAIN::VRBRAINScheduler::init(), PX4::PX4Scheduler::init(), PX4::PX4UARTDriver::read(), VRBRAIN::VRBRAINUARTDriver::read(), PX4::PX4UARTDriver::write(), and VRBRAIN::VRBRAINUARTDriver::write().
void HAP_printf (const char * file, int line, const char * fmt, ...)
Definition at line 73 of file dsp_functions.cpp.
Referenced by HAP_printf().
off_t lseek (int , off_t , int)
Referenced by VRBRAIN::VRBRAINStorage::_mtd_signature(), PX4::PX4Storage::_mtd_write(), VRBRAIN::VRBRAINStorage::_mtd_write_signature(), VRBRAIN::VRBRAINStorage::_timer_tick(), Linux::Storage::_timer_tick(), HALSITL::SITL_State::_update_gps_file(), and Linux::Memory_table::Memory_table().
DIR* opendir (const char *)
Referenced by Linux::I2CDeviceManager::get_device(), and AP_Module::init().
size_t strnlen (const char * s, size_t max)
QURT doesn't have strnlen()
Definition at line 31 of file replace.cpp.
Referenced by AP_Param::add_vector3f_suffix(), AP_Param::copy_name_info(), AP_Param::find(), AP_Param::find_group(), and print_vprintf().
int unlink (const char * pathname)
Referenced by HALSITL::SITL_State::_parse_command_line(), and Linux::Storage::_storage_create().
Variable Documentation
volatile uint32_t _last_counter
Definition at line 19 of file dsp_main.cpp.
Referenced by ardupilot_heartbeat().
volatile const char* _last_dsp_file
Definition at line 18 of file dsp_main.cpp.
Referenced by ardupilot_heartbeat().
volatile int _last_dsp_line
Definition at line 17 of file dsp_main.cpp.
Referenced by ardupilot_heartbeat().