APM:Libraries: libraries/AP_HAL_QURT/replace.cpp File Reference
replace.cpp File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include "replace.h"
Functions
void HAP_debug (const char *msg, int level, const char *filename, int line)
void HAP_printf (const char *file, int line, const char *format,...)
size_t strnlen (const char *s, size_t max)
int vasprintf (char **ptr, const char *format, va_list ap)
int asprintf (char **ptr, const char *format,...)
Function Documentation
int asprintf (char ** ptr, const char * format, ...)
Definition at line 63 of file replace.cpp.
Referenced by Linux::PWM_Sysfs::_generate_duty_path(), Linux::PWM_Sysfs_Bebop::_generate_duty_path(), Linux::PWM_Sysfs::_generate_enable_path(), Linux::PWM_Sysfs_Bebop::_generate_enable_path(), Linux::PWM_Sysfs::_generate_export_path(), Linux::PWM_Sysfs::_generate_period_path(), Linux::PWM_Sysfs_Bebop::_generate_period_path(), Linux::PWM_Sysfs::_generate_polarity_path(), HALSITL::SITL_State::_parse_command_line(), SITL::JSBSim::create_templates(), Linux::I2CDeviceManager::get_device(), PX4::I2CDevice::I2CDevice(), Linux::Led_Sysfs::init(), AP_Module::init(), Linux::RCInput_Navio2::open_channel(), SITL::JSBSim::send_servos(), AnalogSource_Navio2::set_channel(), SITL::FlightAxis::soap_request(), PX4::SPIDevice::SPIDevice(), and SITL::JSBSim::start_JSBSim().
void HAP_debug (const char * msg, int level, const char * filename, int line)
Referenced by HAP_printf().
void HAP_printf (const char * file, int line, const char * format, ...)
Definition at line 16 of file replace.cpp.
size_t strnlen (const char * s, size_t max)
QURT doesn't have strnlen()
Definition at line 31 of file replace.cpp.
Referenced by AP_Param::add_vector3f_suffix(), AP_Param::copy_name_info(), AP_Param::find(), AP_Param::find_group(), and print_vprintf().
int vasprintf (char ** ptr, const char * format, va_list ap)
Definition at line 43 of file replace.cpp.
Referenced by HALSITL::SITL_State::_gps_nmea_printf(), asprintf(), and SITL::FlightAxis::soap_request().