APM:Libraries: Vector2< T > Struct Template Reference
Vector2< T > Struct Template Reference
#include <vector2.h>
Public Member Functions
constexpr Vector2 ()
constexpr Vector2 (const T x0, const T y0)
void operator() (const T x0, const T y0)
bool operator== (const Vector2< T > &v) const
bool operator!= (const Vector2< T > &v) const
Vector2< T > operator- (void) const
Vector2< T > operator+ (const Vector2< T > &v) const
Vector2< T > operator- (const Vector2< T > &v) const
Vector2< T > operator* (const T num) const
Vector2< T > operator/ (const T num) const
Vector2< T > & operator+= (const Vector2< T > &v)
Vector2< T > & operator-= (const Vector2< T > &v)
Vector2< T > & operator*= (const T num)
Vector2< T > & operator/= (const T num)
T operator* (const Vector2< T > &v) const
T operator% (const Vector2< T > &v) const
float angle (const Vector2< T > &v2) const
T angle (void) const
bool is_nan (void) const
bool is_inf (void) const
bool is_zero (void) const
const T & operator[] (uint8_t i) const
void zero ()
T length_squared () const
float length (void) const
void normalize ()
Vector2< T > normalized () const
void reflect (const Vector2< T > &n)
void project (const Vector2< T > &v)
Vector2< T > projected (const Vector2< T > &v)
Static Public Member Functions
static Vector2< T > perpendicular (const Vector2< T > &pos_delta, const Vector2< T > &v1)
static Vector2< T > closest_point (const Vector2< T > &p, const Vector2< T > &v, const Vector2< T > &w)
static float closest_distance_between_radial_and_point (const Vector2< T > &w, const Vector2< T > &p)
Public Attributes
T x
T y
Detailed Description
template<typename T>
struct Vector2< T >
Definition at line 35 of file vector2.h.
Constructor & Destructor Documentation
template<typename T> constexpr Vector2< T >::Vector2 () inline
Definition at line 40 of file vector2.h.
template<typename T> constexpr Vector2< T >::Vector2 (const T x0, const T y0) inline
Definition at line 45 of file vector2.h.
Member Function Documentation
template<typename T> float Vector2< T >::angle (const Vector2< T > & v2) const
Definition at line 127 of file vector2.cpp.
Referenced by AP_Landing_Deepstall::verify_breakout().
template<typename T> T Vector2< T >::angle (void) const
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> static float Vector2< T >::closest_distance_between_radial_and_point (const Vector2< T > & w, const Vector2< T > & p) inline static
Definition at line 210 of file vector2.h.
Referenced by closest_approach_xy().
template<typename T> static Vector2<T> Vector2< T >::closest_point (const Vector2< T > & p, const Vector2< T > & v, const Vector2< T > & w) inline static
Definition at line 185 of file vector2.h.
Referenced by Vector2< int32_t >::closest_distance_between_radial_and_point().
template<typename T > bool Vector2< T >::is_inf (void) const
Definition at line 72 of file vector2.cpp.
Referenced by Vector2< T >::angle(), AP_AHRS::calc_trig(), Vector2< int32_t >::operator()(), and AP_AHRS_DCM::yaw_error_compass().
template<typename T > bool Vector2< T >::is_nan (void) const
Definition at line 66 of file vector2.cpp.
Referenced by Vector2< T >::angle(), AP_AHRS::calc_trig(), and Vector2< int32_t >::operator()().
template<typename T> bool Vector2< T >::is_zero (void) const inline
Definition at line 108 of file vector2.h.
Referenced by AC_Avoid::adjust_velocity_polygon_fence(), AC_Avoid::adjust_velocity_proximity(), and Compass::consistent().
template<typename T > float Vector2< T >::length (void) const
Definition at line 24 of file vector2.cpp.
Referenced by AC_PosControl::accel_to_lean_angles(), AC_Avoid::adjust_roll_pitch(), AC_Avoid::adjust_velocity_circle_fence(), AC_Avoid::adjust_velocity_polygon(), Vector2< T >::angle(), AC_WPNav::calc_loiter_desired_velocity(), NavEKF2_core::calcGpsGoodToAlign(), NavEKF3_core::calcGpsGoodToAlign(), Vector2< int32_t >::closest_distance_between_radial_and_point(), AC_PI_2D::get_i(), AC_PI_2D::get_i_shrink(), AP_AHRS::groundspeed(), Vector2< int32_t >::length_squared(), Vector2< int32_t >::normalize(), Vector2< int32_t >::normalized(), AP_Landing_Deepstall::predict_travel_distance(), AP_L1_Control::update_heading_hold(), AP_L1_Control::update_loiter(), AP_Avoidance::update_threat_level(), AP_L1_Control::update_waypoint(), NavEKF2_core::writeOptFlowMeas(), NavEKF3_core::writeOptFlowMeas(), and AP_AHRS_DCM::yaw_error_compass().
template<typename T> T Vector2< T >::length_squared () const inline
Definition at line 125 of file vector2.h.
Referenced by Vector2< int32_t >::closest_point().
template<typename T> void Vector2< T >::normalize (void) inline
Definition at line 134 of file vector2.h.
Referenced by AP_AHRS::calc_trig(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AP_Landing_Deepstall::update_steering(), AP_L1_Control::update_waypoint(), and AP_AHRS_DCM::yaw_error_compass().
template<typename T> Vector2<T> Vector2< T >::normalized () const inline
Definition at line 140 of file vector2.h.
Referenced by Compass::consistent(), and AP_L1_Control::update_loiter().
template<typename T> bool Vector2< T >::operator!= (const Vector2< T > & v) const
Definition at line 121 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> T Vector2< T >::operator% (const Vector2< T > & v) const
Definition at line 39 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> void Vector2< T >::operator() (const T x0, const T y0) inline
Definition at line 50 of file vector2.h.
template<typename T> Vector2< T > Vector2< T >::operator* (const T num) const
Definition at line 91 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> T Vector2< T >::operator* (const Vector2< T > & v) const
Definition at line 32 of file vector2.cpp.
template<typename T> Vector2< T > & Vector2< T >::operator*= (const T num)
Definition at line 45 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> Vector2< T > Vector2< T >::operator+ (const Vector2< T > & v) const
Definition at line 103 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> Vector2< T > & Vector2< T >::operator+= (const Vector2< T > & v)
Definition at line 78 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T > Vector2< T > Vector2< T >::operator- (void) const
Definition at line 109 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> Vector2< T > Vector2< T >::operator- (const Vector2< T > & v) const
Definition at line 97 of file vector2.cpp.
template<typename T> Vector2< T > & Vector2< T >::operator-= (const Vector2< T > & v)
Definition at line 59 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> Vector2< T > Vector2< T >::operator/ (const T num) const
Definition at line 85 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> Vector2< T > & Vector2< T >::operator/= (const T num)
Definition at line 52 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> template bool Vector2< T >::operator== (const Vector2< T > & v) const
Definition at line 115 of file vector2.cpp.
Referenced by Vector2< T >::angle(), and Vector2< int32_t >::operator()().
template<typename T> const T& Vector2< T >::operator[] (uint8_t i) const inline
Definition at line 110 of file vector2.h.
template<typename T> static Vector2<T> Vector2< T >::perpendicular (const Vector2< T > & pos_delta, const Vector2< T > & v1) inline static
Definition at line 167 of file vector2.h.
template<typename T> void Vector2< T >::project (const Vector2< T > & v) inline
Definition at line 154 of file vector2.h.
Referenced by Vector2< int32_t >::reflect().
template<typename T> Vector2<T> Vector2< T >::projected (const Vector2< T > & v) inline
Definition at line 160 of file vector2.h.
template<typename T> void Vector2< T >::reflect (const Vector2< T > & n) inline
Definition at line 146 of file vector2.h.
template<typename T> void Vector2< T >::zero (void) inline
Definition at line 119 of file vector2.h.
Referenced by AP_GPS::calc_blended_state(), AP_AHRS_NavEKF::get_variances(), NavEKF3::getLastPosNorthEastReset(), NavEKF2::getLastPosNorthEastReset(), NavEKF2_core::InitialiseFilterBootstrap(), NavEKF3_core::InitialiseFilterBootstrap(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), AC_PI_2D::reset_I(), NavEKF2_core::SelectFlowFusion(), NavEKF3_core::SelectFlowFusion(), AP_OpticalFlow_Pixart::update(), and AP_OpticalFlow_Onboard::update().
Member Data Documentation
template<typename T> T Vector2< T >::x
Definition at line 37 of file vector2.h.
Referenced by OpticalFlow_backend::_applyYaw(), Linux::OpticalFlow_Onboard::_run_optflow(), AC_PosControl::accel_to_lean_angles(), AC_Avoid::adjust_roll_pitch(), AC_Avoid::adjust_velocity(), AC_Avoid::adjust_velocity_polygon(), AP_GPS::calc_blended_state(), AC_WPNav::calc_loiter_desired_velocity(), AP_AHRS::calc_trig(), AC_PosControl::check_for_ekf_xy_reset(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), NavEKF2_core::FuseSideslip(), NavEKF3_core::FuseSideslip(), NavEKF2_core::FuseVelPosNED(), NavEKF3_core::FuseVelPosNED(), AC_Circle::get_closest_point_on_circle(), AP_AHRS_NavEKF::get_relative_position_NE_home(), AP_AHRS_NavEKF::get_relative_position_NED_origin(), AC_PrecLand::get_target_position_cm(), AP_Avoidance::get_vector_perpendicular(), SoaringController::get_wind_corrected_drift(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), NavEKF2_core::getPosNE(), NavEKF3_core::getPosNE(), NavEKF2_core::getWind(), NavEKF3_core::getWind(), AC_Fence::handle_msg(), GCS_MAVLINK::handle_set_mode(), AP_Proximity_Backend::init_boundary(), AC_WPNav::init_loiter_target(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), AC_PolyFence_loader::load_point_from_eeprom(), location_path_proportion(), DataFlash_Class::Log_Write_POS(), Vector2< T >::operator!=(), Vector2< T >::operator%(), Vector2< T >::operator*(), Vector2< T >::operator+(), Vector2< T >::operator+=(), Vector2< T >::operator-(), Vector2< T >::operator-=(), Vector2< T >::operator==(), Vector2< int32_t >::operator[](), Polygon_outside(), Linux::OpticalFlow_Onboard::push_gyro(), Linux::OpticalFlow_Onboard::push_gyro_bias(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_PosControl::rate_to_accel_xy(), SITL::CRRCSim::recv_fdm(), NavEKF2_core::ResetPosition(), NavEKF3_core::ResetPosition(), NavEKF2_core::ResetVelocity(), NavEKF3_core::ResetVelocity(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), AC_PolyFence_loader::save_point_to_eeprom(), NavEKF2_core::SelectVelPosFusion(), NavEKF3_core::SelectVelPosFusion(), AC_PI_2D::set_input(), AC_PI_2D::set_integrator(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), test_accuracy(), AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_SITL::update(), AP_Beacon_SITL::update(), AP_OpticalFlow_Onboard::update(), AP_L1_Control::update_loiter(), AP_L1_Control::update_waypoint(), AP_Landing_Deepstall::verify_land(), NavEKF2_core::writeOptFlowMeas(), NavEKF3_core::writeOptFlowMeas(), and AP_AHRS_DCM::yaw_error_compass().
template<typename T> T Vector2< T >::y
Definition at line 37 of file vector2.h.
Referenced by OpticalFlow_backend::_applyYaw(), Linux::OpticalFlow_Onboard::_run_optflow(), AC_PosControl::accel_to_lean_angles(), AC_Avoid::adjust_roll_pitch(), AC_Avoid::adjust_velocity(), AC_Avoid::adjust_velocity_polygon(), AP_GPS::calc_blended_state(), AC_WPNav::calc_loiter_desired_velocity(), AP_AHRS::calc_trig(), AC_PosControl::check_for_ekf_xy_reset(), NavEKF2_core::FuseAirspeed(), NavEKF3_core::FuseAirspeed(), NavEKF2_core::FuseOptFlow(), NavEKF3_core::FuseOptFlow(), NavEKF2_core::FuseSideslip(), NavEKF3_core::FuseSideslip(), NavEKF2_core::FuseVelPosNED(), NavEKF3_core::FuseVelPosNED(), AC_Circle::get_closest_point_on_circle(), AP_AHRS_NavEKF::get_relative_position_NE_home(), AP_AHRS_NavEKF::get_relative_position_NED_origin(), AC_PrecLand::get_target_position_cm(), AP_Avoidance::get_vector_perpendicular(), SoaringController::get_wind_corrected_drift(), NavEKF2_core::getLLH(), NavEKF3_core::getLLH(), NavEKF2_core::getPosNE(), NavEKF3_core::getPosNE(), NavEKF2_core::getWind(), NavEKF3_core::getWind(), AC_Fence::handle_msg(), GCS_MAVLINK::handle_set_mode(), AP_Proximity_Backend::init_boundary(), AC_WPNav::init_loiter_target(), NavEKF2_core::InitialiseVariables(), NavEKF3_core::InitialiseVariables(), AC_PolyFence_loader::load_point_from_eeprom(), location_path_proportion(), DataFlash_Class::Log_Write_POS(), Vector2< T >::operator!=(), Vector2< T >::operator%(), Vector2< T >::operator*(), Vector2< T >::operator+(), Vector2< T >::operator+=(), Vector2< T >::operator-(), Vector2< T >::operator-=(), Vector2< T >::operator==(), Polygon_outside(), Linux::OpticalFlow_Onboard::push_gyro(), Linux::OpticalFlow_Onboard::push_gyro_bias(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_PosControl::rate_to_accel_xy(), SITL::CRRCSim::recv_fdm(), NavEKF2_core::ResetPosition(), NavEKF3_core::ResetPosition(), NavEKF2_core::ResetVelocity(), NavEKF3_core::ResetVelocity(), AC_PrecLand::run_estimator(), AC_PrecLand::run_output_prediction(), AC_PolyFence_loader::save_point_to_eeprom(), NavEKF2_core::SelectVelPosFusion(), NavEKF3_core::SelectVelPosFusion(), AC_PI_2D::set_input(), AC_PI_2D::set_integrator(), NavEKF2_core::setAidingMode(), NavEKF3_core::setAidingMode(), NavEKF2_core::setWindMagStateLearningMode(), NavEKF3_core::setWindMagStateLearningMode(), test_accuracy(), AP_OpticalFlow_PX4Flow::timer(), AP_OpticalFlow_Pixart::update(), AP_OpticalFlow_SITL::update(), AP_Beacon_SITL::update(), AP_OpticalFlow_Onboard::update(), AP_L1_Control::update_loiter(), AP_L1_Control::update_waypoint(), AP_Landing_Deepstall::verify_land(), NavEKF2_core::writeOptFlowMeas(), NavEKF3_core::writeOptFlowMeas(), and AP_AHRS_DCM::yaw_error_compass().
The documentation for this struct was generated from the following files:
libraries/AP_Math/vector2.h
libraries/AP_Math/vector2.cpp